import csv, json, hashlib, subprocess
from pathlib import Path
from collections import Counter
OUT=Path('/tmp/nito-wave2-semantic-resolution'); ROOT=Path('/Users/morten/Documents/forsikringsapp'); TRI=Path('/tmp/source-catalog-remediation-triage'); AUD=Path('/tmp/source-catalog-completeness-audit')
J=lambda p:json.loads(Path(p).read_text())
tri=J(TRI/'triage.json'); baseline=J(OUT/'review-baseline.json'); current=J(OUT/'current-state-evidence.json')
ids=['B-015','B-017','B-018','B-019','B-020','B-021','B-022']; original={b['batch_id']:b for b in tri['batches'] if b['batch_id'] in ids}
controls=list(csv.DictReader((TRI/'regression-control-registry.csv').open()))
source_specs=[
('S01','tryg','Innbo','catalog/sources/tryg/innbo/Innbo_og_losore_Ekstra_PPK13302.pdf','4cffa3b051f329da0fe178b20243a0920d2b5928e9995d485c35b58a48f1f810','PPK13302','2026-07-01','PDF 4 §2.4','https://www.tryg.no/odpdf?vilk=Hjemforsikring-Dekningsvilkaar-Ekstra&vilkNr=05PPK13302','Tyveri og skadeverk under flytting. 30 000 per skadetilfelle ved transportbyrå/idrettslag/forening o.l.; privat flytting omfattes uten denne særgrensen. Ikke bevis for generell transportskade eller ubegrenset erstatning.'),
('S02','fremtind','Reise','catalog/sources/fremtind/reise/canonical/fremtind-reise-vilkar.pdf','2e410ce7bb27c5d355f564d4fd44c88e28e5199448cb691f139440cacc8d4267','PRE-450.200-015','2025-03-17','PDF 5–6 §8.2','https://dokument.fremtind.no/vilkar/fremtind/pm/reise/Reise_PM.pdf','Fremmøte: overnatting 6 000/person/skadetilfelle, innhenting ubegrenset. Avgang: overnatting og innhenting samlet 6 000/person/skadetilfelle; innhenting først når transportør ikke klarer ruten innen 24 timer. Klær/toalett 500/person ved overnatting og utilgjengelig ekspedert bagasje.'),
('S03','frende','Hund','catalog/sources/boat-pet/frende-dog-terms.pdf','6d052e5092d9f92050dcf95a92fa6ce5deda18a5825cdd00ca1c8cd2658c9135','Hundeforsikring','2026-01-01','PDF 3–4 §§7, 7.1.3, 7.3, 8.2, 8.4','https://www.frende.no/forsikringer/hundeforsikring/','Bruksegenskapstap inngår i valgt Tap, ikke eget kjøpbart tillegg. Ferdig trent og regelmessig brukt hund; helt tap etter sykdom/ulykke; ikke hund åtte år eller eldre; avlsevne er unntatt. 50 % av Tap-summen. Tidligere bruksverdiutbetaling trekkes fra dødsfallserstatningen.'),
('S04','storebrand','Reise','catalog/sources/storebrand/reise/canonical/reise10-vilkar-reiseforsikring.pdf','d44b4ef668a51db2e2d0c72714737dee59cb74d10fad13b65e3cde5695e5e414','reise10','2025-06-01','PDF 4 B.1.2–3; PDF 8–9 B.3/B.3.1.1–2; PDF 6 B.2.1; C.1 leiebil','https://www.storebrand.no/privat/forsikring/reiseforsikring/_/attachment/inline/d834efe9-3dd1-4ac5-b81a-e88b9e4aa8d9:e889200271f53a0b6bf8059b3aff6bd43f442696/vilkar-reiseforsikring.pdf','Generell reise starter ved avreise fra hjemmet. B.3-tabell: Standard fremmøte 3 000 hotell/20 000 videretransport, avgang 3 000 hotell/1 500 ny transport per person per hendelse; Super ubegrensede beløp. Fremmøte minst 1,5 time; avgangsinnhenting krever transportør ikke kan innen 24 timer. Beløpsutvidelse fjerner ikke triggerne.'),
('S05','storebrand','Reise','catalog/sources/storebrand/reise/canonical/Reiseforsikring-produktside.html','fc65e95caadecb0ad10d557b276e8befaf39fe5da9ebb40f70c8d3d87ce2636d',None,None,'FAQ: Når gjelder reiseforsikringen?','https://www.storebrand.no/privat/forsikring/reiseforsikring','Du og tingene dine er forsikret på dagstur eller lengre reiser. Dette gjelder generell reiseadgang, ikke alle enkeltfordelers vilkår.'),
('S06','gjensidige','Hus','catalog/sources/gjensidige/hus/Hus-Standard-alminnelige-vilkar.pdf','d237795bdfd0223a9e078bf308d86fdc2f46de953784aea06264ff8024e44edc',None,None,'PDF 3–4 Hus – Dekkes / Dekkes ikke','https://www.gjensidige.no/files/privat/vilkar/bolig-innbo-og-verdier/Hus-Standard-alminnelige-vilkar.pdf','Bekjempelse av levende mus, rotter og andre skadedyr i bygning. Skade fra mus, rotter og andre dyr omfatter fysisk bygningsskade, svekket isolasjon og lukt. Insekter unntas i grunnvilkåret på PDF 4. Ikke en kilde for universell firebeinsavgrensning.'),
('S07','gjensidige','Hus','catalog/sources/gjensidige/hus/Hus-Pluss-alminnelige-vilkar.pdf','79f127ae557e13af8c7a55f95a56c69cf890188dc2e5fcbd4b50ee051e10c792',None,None,'PDF 3–4 grunnskader; PDF 6 Råte og skadeinsekter; PDF 1 egenandeler','https://www.gjensidige.no/files/privat/vilkar/bolig-innbo-og-verdier/Hus-Pluss-alminnelige-vilkar.pdf','Beholder grunnproduktets dyreskader. På fullverdibygning: materialnedbrytning fra råtesopp/treødeleggende insekter; separat insektbekjempelse. Dekningene kommer i tillegg og erstatter ikke gnager-/andre dyreskader.'),
('S08','gjensidige','Hus','catalog/sources/gjensidige/hus/IPID-Husforsikring-EAP01.pdf','5550cd9753fe374a8d4e54e147ecca30e5be09b8c85fb34a52f04c18f3de14b9','EAP01',None,'PDF 2 valgfrie utvidelser','https://www.gjensidige.no/ipid/gfno/EAP01','Sopp/råte/skadeinsekter kan velges på Hus; inkludert i Pluss. Produktnivåbevis, ikke kundens valg.'),
('S09','gjensidige','Hund','catalog/sources/boat-pet/gjensidige-dog-product.html','fd3fcb6e6b69803bcf7fdaeec80802fab764f74a0f465e5fd5c063c2eed8db58',None,None,'Sett sammen / Liv / Bruk (valgfritt)','https://www.gjensidige.no/forsikring/dyreforsikring/hundeforsikring','Bruk legges til Liv. Valgfritt, ikke ubetinget del av Liv og ikke selvstendig tilvalg på Behandling.'),
('S10','gjensidige','Katt','catalog/sources/boat-pet/gjensidige-cat-product.html','f9bc6e31f84bfe1660b0014798ce144fa6fc5ee7f34ccbe14acf28feab883d4f',None,None,'Sett sammen / Liv / Bruk – tap av bruksverdi som avlskatt','https://www.gjensidige.no/forsikring/dyreforsikring/katteforsikring','Bruk er valgfritt tillegg til Liv. Gjelder avlskatt, ikke arbeidshund. Nettbeskrivelsen er kortfattet; fullvilkåret presiserer det kvalifiserende tapet.'),
('S11','gjensidige','Hund','catalog/sources/boat-pet/gjensidige-dog-life-use-terms.pdf','90536e3520ee46f476f480be9760bc92bd40162e29fd53e914df44b70ea150ea',None,None,'PDF 2–3 (trykt 6–7): tap av bruksverdi / opphør','https://www.gjensidige.no/forsikring/dyreforsikring/hundeforsikring','Livsvarig tap innen forsikret bruksområde. Avl 100 % fysisk tap samt kullkrav; jakt/gjeting/tjeneste minst 50 % funksjonstap og dokumentert trening/bruk. Veterinær og adekvat behandling/rekonvalesens. Bruk opphører ved hovedforfall året hunden fyller 8.'),
('S12','gjensidige','Katt','catalog/sources/boat-pet/gjensidige-cat-life-use-terms.pdf','47750999d5bdbe5fc9bf5a2ffe24def17dd1664a2b8f9886bc7868dbf8049f5e',None,None,'PDF 2 (trykt 6): tap av bruksverdi, avlskatt / opphør','https://www.gjensidige.no/forsikring/dyreforsikring/katteforsikring','Avlskatt må ha mistet fysisk avlsevne 100 %, dokumentert av veterinær, med hann-/hunnkullkrav siste to år. Bruk opphører ved hovedforfall året katten fyller 10; Liv 13 er en annen dekning.')]
sources=[]
for sid,provider,family,path,sha,number,date,location,url,meaning in source_specs:
 actual=hashlib.sha256((ROOT/path).read_bytes()).hexdigest()
 assert actual==sha,(sid,'hash mismatch')
 sources.append(dict(source_id=sid,provider=provider,family=family,agreement_scope='ordinary',local_path=path,absolute_path=str(ROOT/path),sha256=sha,hash_verified=True,document_number=number,valid_from=date,location=location,url=url,meaning=meaning,freshness='Frozen local corpus only; no current-public-freshness claim'))

def batch(bid,disposition,problem,existing,canonical,decision,layer,src,risk,model,customer,deps=()):
 b=original[bid]
 return dict(batch_id=bid,title=b['title'],original_disposition=b['source_readiness'],final_disposition=disposition,semantic_problem=problem,source_evidence=list(src),existing_catalog_state=existing,existing_canonical_state=canonical,decision=decision,implementation_layer=layer,affected_products=b['products_affected'],affected_families=b['families_affected'],customer_mode_impact=customer,dependencies=list(deps),original_review_dependencies=b['canonical_review_ids'],implementation_risk=risk,recommended_model=model,required_tests=[],named_controls=[r['control_id'] for r in controls if bid in json.loads(r['batch_ids'])],preserve=b['what_must_not_change'],finding_signatures=b['signature_ids'],implementation_files=[],plan={},remaining_requirement=None)
B=[]
B.append(batch('B-015','CANONICAL_EXTENSION_REQUIRED','MAPPING_ERROR + narrow CANONICAL_GAP: profesjonell flyttings tyveri/skadeverk står som generell transportskade.','trygInnboExtra: flytting.transport.grense = 30 000 per skadetilfelle ved transportbyrå/idrettslag/forening.','flytting.transport.grense er brukt av andre tilbydere for ytre skade/transport/bæring. Ingen egen presis flyttetyveri/skadeverk-identitet finnes. CatalogFact kan lagre en ny termnøkkel uten skjemaendring.','Flytt akkurat denne opplysningen til ny flytting.tyveri_skadeverk.grense. Privat og profesjonell flytting beholdes som eksplisitt kvalifiserte grener i samme term. Ingen global alias fra transport til tyveri.','catalog + narrow canonical identity + explicit mapping', ['S01'],'MEDIUM','GPT-6 SOL HIGH','Samme presise dokumentnøkkel vinner. Eksakt, entydig label kan mappes; gamle generiske dokumentfacts om transport må beholdes uten å omdøpes eller få denne tyverigrensen tillagt.'))
B.append(batch('B-017','READY_TO_IMPLEMENT','MAPPING_ERROR / for grov oppsummering: ubegrenset innhenting ved fremmøte fremstår som generell regel også ved forsinket avgang.','fremtind-reise: reise.forsinkelse.rute blander hendelser; avgangens samlede 6 000-grense og 24-timersvilkår mangler.','reise.forsinkelse.avgang_sum og reise.forsinkelse.fremmote_sum finnes allerede hos Tryg. Verdier er kvalifiserte tekster, ikke bare skalare tall.','Gjenbruk begge eksisterende hendelsesnøkler med egne fullstendige utløsere/beløp. Behold rute som ikke-numerisk felles ramme. Legg til den dokumenterte 500-kronersregelen som egen kildebelagt term under eksisterende reise.bagasje.forsinket, tydelig knyttet til utilgjengelig bagasje ved forsinkelse med overnatting.','catalog + explicit normalization/enrichment compatibility mapping',['S02'],'MEDIUM','GPT-6 SOL HIGH','Ikke avled kundens faktiske merutgifter fra produktgrenser. Nøyaktige dokumentnøkler/entydige hendelseslabels vinner; dokumentert bred rute-term blokkerer ny katalogavgang/fremmøte når dokumentet ikke kan deles sikkert. Historisk Eika er urørt.'))
B.append(batch('B-018','BLOCKED_BY_OTHER_BATCH','PRODUCT_COMPONENT_ERROR: del av valgt Tap er eksponert som selvstendig tillegg. I tillegg kan generisk tilleggsinferens velge hele Tap fra en underdekning etter en naiv flytting.','Tap alene gir bare dyr.liv.*. Separat frende-hund-bruksverdi gir hund.bruksverdi.* uten Tap. Bekreftet med read-only resolverprobe.','hund.bruksverdi.dekning/grense/alder/begrensning finnes. Komponentstruktur støtter innhold i Tap. Men selectedScopedAddOns søker alle komponentens hoveddekninger; den skiller ikke kjøpsbevis fra inkluderende underdekning.','Etter felles seleksjonsguard fra B-022: flytt Bruksverdi inn i frende-hund-tap; fjern den separate kjøpbare Bruksverdi-komponenten; behold betingelser og 50 %-regel. Ikke opprett Bruk → Liv-avhengighet for Frende: dette er inklusjon i Tap.','catalog composition + shared add-on selection-evidence guard',['S03'],'MEDIUM','GPT-6 SOL HIGH','Bare eksplisitt Tap/Liv-valg kan gi katalogbasert Tap-innhold. Dokumentert Bruksverdi alene bevares som dokumentfakta, men velger ikke hele Tap. Bruksverdi ikke valgt skal ikke oppheve øvrig dokumentert Tap.',['B-022']))
B.append(batch('B-019','READY_TO_IMPLEMENT','MAPPING_ERROR: kjent dagsturregel ligger under geografi; reise.overnatting blir falskt ukjent.','reise.omrade.verden inneholder Dagstur er omfattet. Probe viser unknown på reise.overnatting for Standard og Super mot Tryg.','reise.overnatting finnes hos Tryg; eksisterende presentation-concept reise.rammer gjenkjenner den. Dette er term/eligibility, ikke fravær av dekning.','Legg eksplisitt kildebelagt reise.overnatting i Storebrands common-komponent. Betydning: dagstur YES, generelt overnattingskrav NO. Behold geografi og alle fordelsspesifikke overnattingsvilkår. Ingen ny state-enum, ingen UI-teksttolking.','catalog mapping only',['S04','S05'],'LOW','GPT-6 SOL MEDIUM','Dokumentert reise.overnatting har forrang. Ny term sier ikke at alle fordeler gjelder uten overnatting; leiebil/arrangementsavbestilling har egne betingelser.'))
B.append(batch('B-020','CANONICAL_EXTENSION_REQUIRED','INHERITANCE_ERROR + CANONICAL_GAP: Pluss/tillegg bruker samme nøkler som dyr/gnagere og replacesBase sletter grunnproduktets fakta.','Standard har hus.skadedyr.bekjempelse/bygningsskade. Pluss og valgt råte/insekter erstatter disse med insektvilkår. Uvalgt tillegg skjules delvis av included-preferanse på samme nøkkel.','Generiske skadedyrnøkler skiller handling (bekjempelse/bygningsskade), men ikke dyregruppe. Ingen sikre barn for dyr versus insekter finnes. Kun å fjerne replacesBase er utilstrekkelig i både produkt- og kundemodus.','Innfør søsken under hus.skadedyr: dyr.bekjempelse/bygningsskade og insekter.bekjempelse/bygningsskade/egenandel. Grunndyr arves; insekter er optional på Standard og included på Pluss. Råte holdes separat. Ingen global omtolking av andre provideres generiske skadedyrfakta.','canonical children + inheritance + catalog/add-on composition + mapping',['S06','S07','S08'],'MEDIUM','GPT-6 SOL EXTRA HIGH','Dokumentert avslag på insekter skal ikke fjerne dyreskader og omvendt. Bred skadedyr-dokumentasjon er ikke bevis for begge undergrupper; uklar bred dokumentasjon blokkerer katalogutfylling i berørt gren fremfor å overstyres.'))
B.append(batch('B-021','READY_TO_IMPLEMENT','MAPPING_ERROR: 20 000 for fremmøte brukes også om avgang der kilden sier 1 500 for ny transport. Super mister hendelsesvilkår i generell ubegrenset-tekst.','Standard og Super har bare reise.forsinkelse.rute med sammenblandede hendelser.','Gjenbruk samme avgang_sum/fremmote_sum-identiteter som B-017/Tryg. Forskjellige grenser for hotell og transport bevares i tydelig kvalifisert term, uten å gjøre dem til én felles sum.','Felles rute-ramme uten blandede summer. Standard: fremmøte hotell 3 000/transport 20 000; avgang hotell 3 000/transport 1 500. Super erstatter hver av de to summetermene med ubegrensede beløp, men beholder 1,5-times/24-times-triggerne i riktig gren.','catalog + existing event identities/inheritance',['S04'],'MEDIUM','GPT-6 SOL HIGH','Bruk kompatibilitetsmappingen fra B-017 for dokument > katalog, uten generell alias av rute til én hendelse.',['B-017']))
B.append(batch('B-022','CANONICAL_EXTENSION_REQUIRED','CANONICAL_GAP: modellen kan kreve hovedprodukt, men ikke annet tillegg. Katt mangler artsriktig Bruk-identitet.','Gjensidige Hund Bruk kan resolveres alene uten Liv. Katt har ingen Bruk-komponent. Begge hovedprodukter er Behandling; sourceSeeds har IPID, mens relevante fullvilkår allerede finnes lokalt.','CatalogAddOn.requiresLevel validerer produkt-ID, ikke tillegg. Ingen requiresAddOnIds. Katt mangler katt.bruksverdi.*; hund.bruksverdi må ikke gjenbrukes.','Legg til eksplisitt all-of requiresAddOnIds, adskilt fra availableAddOns. Legg til eksplisitte selectionEvidenceKeys som avgrenser hva som kan velge et sammensatt tillegg. Bruk → samme arts Liv, aldri motsatt eller automatisk valg. Katt får artsavgrenset Bruksverdi. Registrer de eksisterende riktige fullvilkårene og produktsidene som faktakilder.','shared add-on constraints/selection + species registry + catalog + source records',['S09','S10','S11','S12'],'HIGH','GPT-6 SOL EXTRA HIGH','Streng manuell validering av Bruk uten Liv. PDF med eksplisitt Bruk og taus/avvist Liv beholder dokumentert Bruk, men får ikke Liv valgt eller katalogberikelse som forutsetter Liv. Ingen global Frende/Fremtind/Tryg/If/Storebrand-avhengighet.'))
byid={b['batch_id']:b for b in B}
for b in B:
    evid=original[b['batch_id']]['evidence']
    b['audit_finding_ids']=list(dict.fromkeys(x for e in evid for x in (e.get('finding_ids') or [e.get('finding_id')]) if x))
    b['audit_source_fact_ids']=list(dict.fromkeys(x for e in evid for x in (e.get('source_fact_ids') or [e.get('source_fact_id')]) if x))
    b['review_dependencies_resolution']={cr: 'SEMANTIC_REVIEW_RESOLVED_HERE; no human approval claimed; follow final disposition' for cr in b['original_review_dependencies']}

# Inherited impact is explicit rather than silently widening the original finding.
for bid in ['B-019','B-021']:
 byid[bid]['affected_products'].append('["storebrand","reise","ordinary","storebrand-reise-super","2026-09-20-canonical"]')
 byid[bid]['affected_products']=list(dict.fromkeys(byid[bid]['affected_products']))
 byid[bid]['inherited_scope_reason']='Super bruker common/Standard; kilde B.3 gjelder begge nivåer.'
common_acceptance=['Ingen endring utenfor batchens eksplisitte provider/type/scope/version/komponenter.','Ingen offentlig kildesannhet utledes fra sammenligningsmotpart. Fravær av presis motpart = unknown, ikke not covered.','Eksplisitt dokument X vinner over katalog Y med minst to alternative verdipar; taus valgfri dekning blir ikke selected.','Samme produkt mot seg selv og begge sideretninger gir stabil semantikk; kilder følger korrekt fact.','Alle tidligere godkjente Wave 1 og Wave 2-endringer består uendret; ingen ekstra oppgaver tas med.']
plans={
'B-015':dict(
 change=['Definer bare flytting.tyveri_skadeverk.grense (term) under eksisterende Innbo flytting-familie. Flytt Tryg Ekstra-raden dit; slett den feilaktige transportgrensen fra denne komponenten.','Verdien må uttrykkelig omtale tyveri/skadeverk under privat flytting og særgrensen 30 000 kr per skadetilfelle for transportbyrå/idrettslag/forening o.l. Ingen påstand om ubegrenset privat erstatning.','Registrer eventuelt bare hele, godkjente Innbo-labels som identifiserer flyttetyveri/skadeverk. Ikke alias transportskade eller generell tyverigrense. Generiske dokumentfacts bevares; ved uttrykkelig bredt dokumentert flyttevilkår må mulig overlapp blokkeres konservativt i katalogberikelsen.'],
 not_change=['Tryg Innbo basis, uhell §2.5, valgt innbosum, flytteområde/varighet og utleie.','Andre provideres flytting.transport.grense, inkludert B-005 Storebrand. Ingen migrering av deres fakta basert på Tryg.'],
 result='Egen presis flyttetyveri/skadeverk-rad; Tryg har ikke lenger en falsk generell transportgrense. Andre leverandørers usplittede fakta beholdes separat.',
 provenance='trygInnboExtra, S01 §2.4 PDF 4. Samme offentlige original/hash; ingen ny source artifact.',
 files=['lib/tryg-innbo-catalog.ts','lib/insurance-normalization.ts','lib/catalog-enrichment.ts','tests/nito-remediation-wave2.test.mjs'],
 reaudit='Kun Tryg Innbo Ekstra berørt fact/komponent; kontroll av basis og B-005 Storebrand; avgrensede sammenligninger med transportskadeprodukter begge veier.'),
'B-017':dict(
 change=['Behold reise.forsinkelse.rute som felles vilkårsramme (påbegynt reise; dokumenterte utløsere; relevante utgifts-/transportørunntak). Fjern den overbrede ubegrenset-påstanden fra rammen.','Bruk eksisterende reise.forsinkelse.fremmote_sum: for sent til forhåndsbetalt offentlig transport; hotell 6 000 kr per person per skadetilfelle; innhenting ubegrenset.','Bruk eksisterende reise.forsinkelse.avgang_sum: forhåndsbetalt transport går ikke til avtalt tid; hotell + innhenting samlet 6 000 kr per person per skadetilfelle. Bare innhentingen har vilkår om at transportøren ikke klarer ruten innen 24 timer. Ikke 6 000 for hver av de to utgiftstypene.','Behold opprinnelig reise.bagasje.forsinket §8.1. Legg til en separat CatalogFact med samme eksisterende nøkkel, presis label om utilgjengelig ekspedert bagasje og 500 kr/person ved overnatting, med egen §8.2 PDF 6-kilde. Ikke påfør denne grenen §8.1s firetimerskrav, og ikke gjør 500 til generell bagasjegrense.','Definer eksplisitte Reise-labelaliaser for avgangssum og fremmøtesum dersom manglende. Ingen alias fra rute til én av dem. I katalogberikelse: dersom en reell dokument-origin rute-term fortsatt er uspesifisert, ikke fyll de to spesifiserte katalogbarna over den. Ved eksplisitt barn + bred rute bevares barnet og rute; uavklart søsken blokkeres. Unknown-placeholder er ikke dokumentert innhold. Ikke splitt beløp ved friteksttolking.'],
 not_change=['Historiske eika-reise-p10 / eika-reise-pluss, 70/90/120/180-varighet og kanalregler.','Forsinket ankomst/tapt ferie 500/døgn og 5 000-grenser; eksisterende forsinket bagasje 5 000 og jobb-/hjemreiseregler.','Ingen skalarsammenligning som ignorerer at fremmøtebeløp kan ha ulik fordeling mellom hotell og transport.'],
 result='Fremmøte og avgang blir separate allerede kjente sammenligningsrader; betinget transittbeløp har egen kilde og beholdt hendelse.',
 provenance='fremtindReiseUnifiedTerms, S02 §8.2 PDF 5–6; ikke historisk Eika-kilde.',
 files=['lib/fremtind-reise-catalog.ts','lib/insurance-normalization.ts','lib/catalog-enrichment.ts','tests/nito-remediation-wave2.test.mjs'],
 reaudit='Bare aktivt fremtind-reise PRE-450.200-015, forsinkelses-/utilgjengelig-bagasjegrener; uendret historisk Eika-fingerprint. Kontroll mot Tryg og senere B-021 uten å endre Tryg-data.'),
'B-018':dict(
 change=['Etter B-022s selectionEvidenceKeys-guard: sett Tap-komponentens kjøpsbevis til dyr.liv.dekning / eksakt Tap-navn. hund.bruksverdi.* skal ikke kunne velge hele Tap eller blokkere resten av Tap ved et avslag bare på underdekningen.','Flytt hund.bruksverdi.dekning og .grense til frende-hund-tap; inkluder kildekvalifisering med eksisterende .alder/.begrensning: ferdig trent, regelmessig bruk, helt tap etter sykdom/ulykke, under 8 år, avl unntatt, særvilkår §7.3 og veterinærattest.','Behold 50 % av valgt Tap-sum og avkorting av senere dødsfallserstatning etter §8.4, uten å regne ut kundens sum. Fjern frende-hund-bruksverdi fra kjøpbar add-on-liste og den nå overflødige komponenten.','Gamle manuelle payloads med kun det fjernede ID-et skal avvises tydelig av eksisterende ukjent-tillegg-validering; aldri remappes automatisk til Tap. Gamle dokumentfacts/add-on-tekst bevares som dokumentasjon uten valgt Tap.'],
 not_change=['Frende Katt, Medisin/Tann, Tap-hovedopphør ved hovedforfall etter 10 år. Bruksverdiens under 8 år er et annet vilkår.','Ingen avhengighetsregel Bruk→Liv for Frende; ingen endring av andre selskapers selvstendige Bruk/Liv.'],
 result='Tap valgt gir betinget bruksverdidekning i Hund. Uvalgt Tap gir ikke kundevalgt Bruksverdi. Produktmodus viser én tilgjengelig Tap-pakke med Bruksverdi som innhold.',
 provenance='S03 §§7.1.3,7.3,8.2,8.4 PDF 3–4; samme boat-pet:frende:hund original.',
 files=['lib/boat-pet-catalog.ts','tests/nito-remediation-wave2.test.mjs'],
 reaudit='Frende Hund base/Tap og ingen/Tap-avslag/Bruksverdi alene/Tap+underdekning-avslag; Frende Katt og andre tillegg uendret. Kjør B-022s felles seleksjonsregresjoner igjen.'),
'B-019':dict(
 change=['Legg en reise.overnatting-term i common ved hjelp av eksisterende faktafunksjon og storebrandReiseProductPage. Bruk eksplisitt positiv dagsturformulering med kildens betydning: reiser med og uten overnatting omfattes generelt.','Standard og Super arver termen. Behold geografi-factens øvrige informasjon; ingen UI-parser av Dagstur og ingen ny boolsk sammenligningsmotor.','Knyt direkte dagsturbevis til S05 FAQ, støttet av S04 B.1.2–3. Ikke gi FAQ en konstruert PDF-side/gyldighetsdato; bruk eksisterende HTML-kildekonvensjon.'],
 not_change=['Storebrands geografiske unntak, medisinske kommunevilkår, avbestilling/arrangement, leiebilens overnattingskrav og tjenestereise.','Tryg Ekstra/Premium og deres fritids-/tjenestereiseformuleringer; generell reiseadgang er ikke lik dekning av alle fordeler.'],
 result='Storebrand får kjent dagsturregel på reise.overnatting i samme rad som Tryg; tilstanden er dokumentert term, ikke unavailable fordi krav på overnatting er NO.',
 provenance='Eksisterende storebrandReiseProductPage S05 FAQ; fullvilkår S04 PDF 4 underbygger den generelle rammen.',
 files=['lib/storebrand-reise-catalog.ts','tests/nito-remediation-wave2.test.mjs'],
 reaudit='Standard/Super mot Tryg Ekstra/Premium begge veier, samme produkt; reise.overnatting skal ikke være unknown. Leiebil/arrangementsavbestilling og alle øvrige facts uendret.'),
'B-020':dict(
 change=['Definer presise søsken hus.skadedyr.dyr.bekjempelse og .bygningsskade versus hus.skadedyr.insekter.bekjempelse, .bygningsskade og .egenandel. Dyr-grenen betyr mus/rotter/andre dyr etter kildens avgrensning; ikke bare gnagere og ikke insekter.','Flytt Standard-fakta til dyr-grenen, med fysisk bygningsskade, svekket isolasjonsevne og lukt. Ikke før videre katalogens usikre generelle firebeinsformulering; bruk kildeordlyden med insekt- og øvrige relevante unntak.','Pluss beholder dyr-grenen via arv og legger til insekter. Endre rotOption-filteret til å kopiere de presise insektnøklene; ingen replacesBase mot dyr-grenen.','Standard er uten insektdekning i grunndekningen, men utvidelsen er optional i produktmodus. Bruk eksisterende komponentmekanisme: ikke legg en konkurrerende unavailable-fact med samme nøkkel foran den valgfrie komponenten. Bevar eksplisitt grunnunntak som separat betingelse. Uvalgt tillegg hos kunde er unknown eller eksplisitt not_selected, aldri automatisk selected.','Behold fullverdikrav, råtesoppgren, 6 000 kr bygningsskade-egenandel med korrekt kombinert scope og 2 000 kr kun insektbekjempelse. Bevar qualificationSource til IPID for Standard-tilgjengelighet.','Ingen globale aliaser fra generisk skadedyr til dyr eller insekter. Bare eksplisitt typescopede labels må velge barn. Dokumentert bred skadedyrregel må ikke overstyres av nye presise katalogbarn ved usikker scope; blokker berikelse konservativt og behold dokumentteksten.'],
 not_change=['B-007s bygnings-/våtromsrettelser, øvrige Hus-facts, andre selskapers skadedyrnøkler, Innbo-skadedyr og Bobil.','Det er ikke tillatt å behandle lukt/isolasjon som bare materialnedbrytning eller å gjøre hele skadedyrfamilien unavailable når bare insekter er avslått.'],
 result='Standard/valgt tillegg/Pluss beholder samme dyreskader. Insekter vises som egen valgfri/inkludert gren, med egne kilder og egenandel.',
 provenance='S06 PDF 3–4 for grunnregler; S07 PDF 3–4/6/1 for Pluss; S08 PDF 2 som qualificationSource for valgfritt tillegg.',
 files=['lib/gjensidige-hus-catalog.ts','lib/insurance-normalization.ts','lib/catalog-enrichment.ts','tests/nito-remediation-wave2.test.mjs'],
 reaudit='Gjensidige Hus uten/med gjensidige-hus-rate-insekter samt Hus Pluss; kontroll av B-007 og motsatt retning. Eksisterende presentation-concept hus.rate-skadedyr gjenbrukes uten redesign.'),
'B-021':dict(
 change=['Etter B-017s mapping-/kundeprioritetsgate: skill Standard i eksisterende reise.forsinkelse.fremmote_sum og reise.forsinkelse.avgang_sum.','Fremmøte: minst 1,5 times kvalifiserende forsinkelse etter påbegynt reise; hotell inntil 3 000/person/hendelse og transport inntil 20 000/person/hendelse. Det er ikke én sum på 23 000 og ikke avgangens 24-timersvilkår.','Avgang: forhåndsbetalt offentlig transport går ikke som avtalt; hotell 3 000/person/hendelse. Ny transport 1 500/person/hendelse bare hvis transportøren ikke klarer å innhente innen 24 timer. Ikke innfør et generelt 24-timerskrav for hotell.','Super erstatter de to beløpsgrenene hver for seg med ubegrensede summer, men beholder hendelsesvilkår. Felles rute-ramme skal fortsatt ha kvalifiserende årsaker, transportøransvar og forhåndsgodkjennelse etter B.3.1; ikke alle tenkelige forsinkelser.'],
 not_change=['B-019s dagsturregel, utilgjengelig bagasje 500, forsinket bagasje 3 000/6 000, andre Super-tillegg, avbestilling og leiebil.'],
 result='Standard får aldri fremmøtebeløpet på avgangsraden; Super-utvidelse fjerner ikke trigger- og dokumentasjonsvilkår.',
 provenance='S04 tabell PDF 8, vilkår B.3.1.1–2 PDF 9. Lag riktige side/punktreferanser for beløp og betingelser.',
 files=['lib/storebrand-reise-catalog.ts','tests/nito-remediation-wave2.test.mjs'],
 reaudit='Standard/Super hver for seg, innbyrdes og mot Fremtind/Tryg begge veier. 3 000/20 000/1 500 må være i riktige grener.'),
'B-022':dict(
 change=['Utvid CatalogAddOn og BoatPetAddOnDefinition med optional requiresAddOnIds:string[] (all-of) og selectionEvidenceKeys:string[]. Fravær bevarer dagens oppførsel. Metadata er produktkonfigurasjon, aldri kundens valg.','Valider avhengighetsreferanser i samme provider/type/agreementScope og det eksakte produktets versjons-/kildescope, selvreferanse/syklus/dangling/utestengte varianter. requiresLevel forblir hovedproduktkrav.','availableAddOns skal fortsatt beskrive tilgjengelighet. Streng selectedComponents/manuell input krever eksplisitt hele valgte settet; Bruk alene skal avvises, aldri auto-velge Liv.','Produktmodus må materialisere en avhengig tilleggspakke med dens nødvendige komponenter i katalogmodus, men merke alle som optional. Skille Bruk-innhold fra Liv-innhold gjennom componentId/evidence; ikke duplisere Liv som om bare Bruk ga det og ikke mutere et kundeseleksjonssett. Eksisterende resolveCatalogFacts(product,[addon.id]) kan ikke brukes uendret for avhengige tillegg.','I selectedScopedAddOns: selectionEvidenceKeys avgrenser både generisk valgevidens og komponentavslag. Et eksplisitt avslag på underdekning blokkerer bare dens facts, ikke et dokumentert valgt overordnet tillegg. Eksakt navngitt addon-valg kan brukes; intern katalog-ID eller katalogtekst er ikke dokumentevidens.','PDF: behold Bruk selected/not_selected/conflict fra kundedokumentet. Manglende/avvist Liv med Bruk valgt gir ingen katalogutfylling som forutsetter Liv og ingen automatisk Liv-status. La base og øvrige gyldige komponenter fortsette; ikke kast hele avtalen. Behold rå dokumentfakta/provenance i eksisterende datastrukturer, ikke telemetry.','Konfigurer Gjensidige Hund Bruk → gjensidige-hund-liv; Katt Bruk → gjensidige-katt-liv. Bruk har eget valg selv når Liv er valgt. Gi Frende Tap selectionEvidenceKeys=[dyr.liv.dekning] i etterfølgende B-018. Ingen global selskapsregel basert på ordet Bruk.','Utvid Katt-register med katt.bruksverdi.dekning/alder/begrensning (og eventuelt .grense bare når eget fullvilkår faktisk gir et slikt fact). Ingen hund.bruksverdi-key for katt og ingen påfunnet sum. Legg til gjensidige-katt-bruk og artsriktig presentation-metadata i eksisterende Katt-gruppe.','Registrer de allerede lokale hund-/katt-Liv/Bruk-fullvilkårene og produktsidene som egne runtime sources med eksisterende hashes, ordinary scope og ukjent kildeversjon/dato beholdt. Knytt dependency til produktside og forsikringsinnhold til fullvilkåret; IPID er ikke eneste faktakilde. Bruk eksisterende qualificationSource-mønster (builder kan måtte føre feltet videre).','Ikke kopier ufullstendig nettsideformulering om nedsatt avlsevne som universell terskel: fullvilkåret krever 100 % fysisk avlsevnetap for katt/avlshund. Hundens arbeidsfunksjon har egen 50 %-betingelse. Fullvilkårets presisering har høyere autoritet; dette er ikke bevis for kildeferskhet.'],
 not_change=['Ingen selvstendig Liv-produktutvidelse, Valpekull/Kattungekull eller øvrige Wave 3-fakta.','Ingen global Bruk→Liv for Fremtind eller automatisk Frende Bruk-komponent. Ingen migrering av kundens ukjente kontrakt til ordinary.','Ingen ny coverage-statusmotor, objektsidentitet, priser, PDF-extraction eller prompt.'],
 result='Avhengighet er eksplisitt og håndheves uten å konvertere tilgjengelighet til kundevalg. Artsriktig Bruk blir sammenlignbart bare innen riktig art.',
 provenance='S09/S10 produktsidene dokumenterer kjøpsavhengigheten; S11/S12 fullvilkår dokumenterer arts-/hendelsesscope. Originalene finnes allerede; ingen nedlasting/byteendring.',
 files=['lib/product-catalog.ts','lib/boat-pet-catalog-builder.ts','lib/boat-pet-catalog.ts','lib/boat-pet-registry.ts','lib/catalog-product-comparison.ts','lib/catalog-enrichment.ts','lib/presentation-catalog.ts','lib/manual-agreement.ts','app/page.tsx (bare nødvendig avhengighetsvalg/validering)','tests/nito-remediation-wave2.test.mjs','tests/agreement-scope.test.mjs (eksisterende regresjonsgruppe; sjekk faktisk navn før implementasjon)'],
 reaudit='Gjensidige Hund/Katt base, Liv, Bruk alene, Liv+Bruk; Frende sammensatt Tap via B-018. Negative provider/type/scope/version/cycle-cases; produktmodus, manuell og syntetisk PDF. Andre tillegg uten metadata må være uendret.')}
for b in B:
 p=plans[b['batch_id']]
 b['implementation_files']=p.pop('files')
 b['plan']={'what_to_change':p['change'],'what_not_to_change':p['not_change'],'affected_scope':b['affected_products'],'expected_result':p['result'],'source_provenance':p['provenance'],'targeted_reaudit':p['reaudit'],'acceptance_criteria':common_acceptance+[p['result']]}
 b['code_references']=['lib/product-catalog.ts:279 availableAddOns; :315 selectedComponents; :343 resolveCatalogFacts','lib/catalog-enrichment.ts:74 selectedScopedAddOns; :188–258 document priority','lib/catalog-product-comparison.ts:190 materializeCatalogProduct; :220 valueForKey','lib/insurance-normalization.ts:460 normalizeTermName; :505 normalizeCatalogTermKey']
 b['risk_explanation']='Begrenset kilde-/mappingendring innen oppgitt scope; særskilte dokumentprioritets- og arvstester kreves.'
 if b['batch_id']=='B-019':b['risk_explanation']='Eksisterende termnøkkel og eksisterende source record; kun presis plassering av allerede kjent regel.'
 if b['batch_id']=='B-022':b['risk_explanation']='HIGH: delt tilleggsresolver, produktmodus og PDF/manuell bruker samme primitive. En naiv dependency closure kan feilaktig velge Liv, eller en streng throw kan forkaste kundedokumentet. Krever separat arkitekturgate og negative tester før katalogkobling.'
 if b['final_disposition']=='CANONICAL_EXTENSION_REQUIRED':
  b['remaining_requirement']='Ny implementeringsautorisasjon må eksplisitt omfatte den spesifiserte minimale utvidelsen og dens gate. Kildespørsmålet er avklart i frosset korpus; utvidelsen er ikke implementert eller regresjonsvalidert her.'
 if b['batch_id']=='B-018':b['remaining_requirement']='B-022s selectionEvidenceKeys-kontrakt og delt seleksjonsguard må være implementert og bestå gate før Tap-komposisjonen endres. Ikke tilstrekkelig å flytte to katalograder.'
# Clarify exact future file names and the limit of current proof.
byid['B-022']['implementation_files'][-1]='tests/agreement-scope.test.mjs'
byid['B-020']['plan']['what_to_change'].insert(4,'Avgrens hus.rate.dekning til råtesopp og dens unntak når treødeleggende insekter flyttes til egen gren. Ikke slett insektinformasjon; unngå at samme insektdekning gis to konkurrerende canonical identities. Den felles bygningsskadeegenandelen kan fortsatt oppgi begge anvendelsesområder uttrykkelig.')
# Exact conservative compatibility guards: metadata mapping, never text-value inference.
byid['B-015']['plan']['what_to_change'].append('Eksakt guard: i Innbo skal en document-origin flytting.transport.grense med dokumentert innhold blokkere katalogutfylling av flytting.tyveri_skadeverk.grense. Presis dokumentert child beholdes alltid. Dette omdøper ikke parent og hevder ikke at hendelsene er like; det hindrer usikker overlapping i eldre dokumentdata.')
byid['B-020']['plan']['what_to_change'].append('Eksakt Hus-guard: document-origin hus.skadedyr.bekjempelse blokkerer katalogfyll av dyr.bekjempelse og insekter.bekjempelse under hus.skadedyr; hus.skadedyr.bygningsskade blokkerer de to tilsvarende bygningsskadebarna; hus.skadedyr.egenandel blokkerer insekter.egenandel. Presise dokumentbarn beholdes. Ingen guarding basert på ordsøk eller gjetting av dyr i verditekst; unknown-placeholder teller ikke som dokumentert innhold.')
byid['B-018']['proof_boundary']='Feil nåværende komponentvalg er observert i resolverprobe. Risikoen etter en naiv flytting er utledet fra selectedScopedAddOns-koden, ikke fra en implementert eller mutert testkatalog.'
canonical=[]
def cd(cid,bids,kind,keys,definition,why,comparison,customer,risk,requirement):
 canonical.append(dict(decision_id=cid,batch_ids=bids,classification=kind,keys=keys,semantic_definition=definition,why_existing_structure_fails_or_suffices=why,affected_products=list(dict.fromkeys(p for bid in bids for p in byid[bid]['affected_products'])),affected_families=list(dict.fromkeys(f for bid in bids for f in byid[bid]['affected_families'])),source_evidence=list(dict.fromkeys(s for bid in bids for s in byid[bid]['source_evidence'])),comparison_behavior=comparison,customer_mode_implication=customer,false_equivalence_risk=risk,regression_requirements=requirement))
cd('CD-015',['B-015'],'CANONICAL_GAP',['flytting.tyveri_skadeverk.grense'],'Tap ved tyveri/skadeverk under flytting med eksplisitt utførerscope og per-skadetilfelle-grense. Term, ikke generell transportskadedekning.','Generell transport/bæring, tyveri utenfor hjem og uhell er ikke samme hendelse. Ny presis child-key i eksisterende flytting-familie er nok; ingen schemautvidelse.','Egen rad; ikke match mot transportskade. Motpart uten egen dokumentasjon blir unknown.','Eksakt dokumentfact har forrang; aldri global alias av gammel transportnøkkel.','Privat flytting kan få feil 30 000-tak; profesjonelt tyveri kan bli oppfattet som generell transportskade.',['Utfører og hendelse beholdt','Ingen cross-provider remapping','Dokumentprioritet med gamle og presise keys'])
cd('CD-017-021',['B-017','B-021'],'EXISTING_KEYS_REUSED',['reise.forsinkelse.avgang_sum','reise.forsinkelse.fremmote_sum','reise.forsinkelse.rute','reise.bagasje.forsinket'],'Avgang: avtalt transport går ikke som planlagt. Fremmøte: kunden når ikke planlagt transport. Beløp for hotell/transport beholdes kvalifisert; samme key betyr samme hendelsesfamilie, ikke identisk vilkår.','Eksisterende Tryg-nøkler og tekstlige CatalogFact verdier kan bevare trigger, person/hendelse og hotell/transport. Ingen ny scalar-beløpsmodell er nødvendig for disse batchene.','To egne rader under eksisterende Forsinkelse; hele kvalifiserte verdier sammenlignes, aldri bare 1 500 mot 20 000 uten trigger. Betinget utilgjengelig bagasje beholdes med egen kilde som del av bagasjetermen.','Ingen one-to-many alias fra rute. Dokumentert uspesifisert rute må konservativt blokkere nye undergrense-fills som kan stride mot dokumentet.','24 timer må ikke flyttes til fremmøte/hotell; Fremtinds samlede 6 000 må ikke bli 6 000 per utgiftstype.',['Separate hendelsesgrenser','Standard/Super-arv','Dokument X > katalog Y','Ingen Eika-migrering'])
cd('CD-018',['B-018'],'EXISTING_KEYS_COMPOSITION_FIX',['hund.bruksverdi.dekning','hund.bruksverdi.grense','hund.bruksverdi.alder','hund.bruksverdi.begrensning','dyr.liv.dekning'],'Frende Bruksverdi er et betinget innhold i valgt Tap, ikke kjøpbart separat produkt.','Eksisterende keys og komponentmekanisme er tilstrekkelige for fakta; delt seleksjonsguard fra CD-022-SELECT er nødvendig for kundemodus.','Optional via Tap i produktmodus. Valgt Tap materialiserer betingede child facts; ingen egen valgfri Bruksverdi-pakke.','Bruksverdi-evidens alene må ikke produsere Liv/Tap-valg. Bare avslag på Bruksverdi må ikke fjerne øvrig Tap.','Frende inklusjon må ikke bli samme arkitekturregel som Gjensidige valgfritt Bruk→Liv.',['Tap-only dekning','Child selection/not_selected uten parent escalation','Katt-isolasjon','Under 8 år mot livsopphør ved hovedforfall etter 10'])
cd('CD-019',['B-019'],'EXISTING_KEY_REUSED',['reise.overnatting'],'Generell adgang for dagstur/reise uten overnatting. YES for dagstur; NO for et generelt overnattingskrav; ikke NOT_COVERED.','Nøkkelen finnes allerede. Mangel er katalogplassering, ikke manglende produktkunnskap eller behov for ny state-enum.','Samme rad som Tryg; termtekst med egen kilde. Ingen UI-utledning fra geografi.','Overnattingsvilkår for spesifikke fordeler er uavhengige av generell trip eligibility.','Generell dagstur kan feilaktig frigjøre leiebil/avbestilling fra vilkår; Tryg tjenestereise kan kopieres.',['OVERNIGHT-01','Standard/Super begge veier mot Tryg Ekstra/Premium','Leiebil og arrangementsavbestilling beholdt'])
cd('CD-020',['B-020'],'CANONICAL_GAP',['hus.skadedyr.dyr.bekjempelse','hus.skadedyr.dyr.bygningsskade','hus.skadedyr.insekter.bekjempelse','hus.skadedyr.insekter.bygningsskade','hus.skadedyr.insekter.egenandel'],'To søsken etter skadevoldergruppe, hver med handling/ytelse. Dyr betyr kildens mus/rotter/andre dyr med egne unntak, ikke bare gnagere; insekter betyr kildebestemte skadeinsekter.','Generiske keys får replacesBase og included-preferanse til å slå sammen/fjerne ulike ytelser. Nye child keys er nok; ingen ny product inheritance-motor.','Egne presise rader under eksisterende Råte og skadedyr. Ingen tvungen ekvivalens til andre provideres brede pest-facts. Standard inkludert dyr + optional insekter; Pluss begge.','Presise avslag og dokumentfakta for hver gren isoleres. Bred skadedyrregel bevares uten å tolkes som to sikre valg.','Mus/rotter≠insekter; bekjempelse≠materialnedbrytning; lukt/isolasjon≠kun råte; insektegenandel må ikke brukes for alle dyr.',['Standard uten/med tillegg/Pluss','Ingen inherited fact loss','Optional vises selv med inkludert søsken','Dokument X>Y, artsgrenisolasjon'])
cd('CD-022-DEP',['B-022'],'CANONICAL_GAP',['CatalogAddOn.requiresAddOnIds'],'Optional all-of liste over tillegg som eksplisitt må være valgt for en gyldig katalogkombinasjon. Krever ikke automatisk kundeseleksjon.','requiresLevel gjelder hovedprodukt. exclusiveGroup er gjensidig utelukkelse, ikke avhengighet. Produktarv ville uriktig gjøre Bruk inkludert i Liv.','Katalogmodus viser conditional optional med dependency-evidens; den kan materialisere en mulig pakke uten kundeseleksjon.','Streng manuell validering. PDF dokumentfakta beholdes selv ved ufullstendig/konfliktende avhengighet; bare avhengig katalogberikelse blokkeres.','En dependency closure kan auto-velge Liv; sykler/dangling eller cross-scope referanser kan gi feil produkter.',['Ingen/Bruk/Liv/Liv+Bruk','Cycle/self/dangling/cross-scope/version negatives','Product materialization vs customer selection','Selected/not_selected/unknown/conflict'])
cd('CD-022-SELECT',['B-022','B-018'],'CANONICAL_GAP',['CatalogAddOn.selectionEvidenceKeys'],'Eksplisitt hvilke canonical parent-keys som kan velge eller blokkere hele tilleggskomponenten; øvrige faktanøkler er innhold/underdekninger. Eksakt navngitt dokumentvalg er fortsatt mulig.','selectedScopedAddOns utleder alle parent keys fra faktalisten og bruker alle som valg-/avslagsbevis. Dette blander produktkomposisjon og individuell seleksjon.','Ingen ny fact/rad; kun trygg materialisering/valg. Fravær av metadata bevarer dagens kompatibilitet.','Tap kan velges av dokumentert Tap/Liv, ikke av en Bruksverdi-child; Bruksverdi-avslag fjerner bare child, ikke resten av Tap.','Child→parent escalation og child-avslag→parent-avslag. Katalogtekst må aldri være dokumentevidens.',['Explicit parent selected + child not_selected','Child selected + parent unknown/not_selected','Unchanged addons without metadata','No array-order dependence'])
cd('CD-022-CAT',['B-022'],'CANONICAL_GAP',['katt.bruksverdi.dekning','katt.bruksverdi.alder','katt.bruksverdi.begrensning'],'Katt: dokumentert tap av avlsegenskaper innen forsikret bruksområde, betinget av eget Bruk-valg og Liv.','Katt-register mangler Bruk. hund.bruksverdi gjelder hund og blir avvist eller feilsemantisk på katt. Ingen ny generell dyr-liv-fact kan erstatte artsdistinksjonen.','Egen Katt Bruksverdi-undergruppe innen eksisterende produktvisning; ingen Hund↔Katt-akse. Other-cat unknown er ikke not covered.','Katt Bruk-facts krever dokumentvalg; behold fullvilkårets terskel/varighet som betingelser, ikke vurder individets egnethet.','50 % arbeidshund må ikke bli kattens avlsterskel; Liv 13 år må ikke bli Bruk 10 år.',['Species isolation','Cat100% versus dog work50%','Bruk expiry vs Liv','PDF/document priority and source-page separation'])

mapping=[]
for b in B:
 mapping.append(dict(mapping_id='MD-'+b['batch_id'][2:],batch_id=b['batch_id'],classification=b['semantic_problem'].split(':')[0],from_state=b['existing_catalog_state'],to_state=b['decision'],provider_type_scope=b['affected_products'],layer=b['implementation_layer'],preserve=b['preserve'],customer_policy=b['customer_mode_impact'],prohibited_shortcut='Ingen global broad→narrow alias, UI-friteksttolking, summer uten trigger, automatisk addonvalg eller peer-baserte fakta.',dependency=b['dependencies']))

# These are future regression specifications, not new tests executed in this review.
reg=[]
def test(bid,category,scenario,expected):
 n=sum(r['batch_id']==bid for r in reg)+1;tid=f'R-{bid[2:]}-{n:02d}'
 reg.append(dict(test_id=tid,batch_id=bid,category=category,scenario=scenario,expected_result=expected,source_ids=byid[bid]['source_evidence'],named_controls=byid[bid]['named_controls'],execution_status='PLANNED_NOT_IMPLEMENTED',privacy='Syntetiske avtaler og offentlige katalogkilder; ingen private PDF-er'))
 byid[bid]['required_tests'].append(tid)
for b in B:
 bid=b['batch_id']
 test(bid,'SOURCE_PROVENANCE','Alle oppgitte kilde-ID-er, egne sider/punkt, original SHA-256 og produkt-/komponentscope','Originalbytes uendret; fact peker på nøyaktig støttende kilde og qualificationSource der nødvendig.')
 test(bid,'SCOPE','Samme provider/type men annen agreementScope/versjon, samt annen provider og type','Ingen kilde-/fact-/addonlekkasje; ordinary og ukjente versjoner konverteres ikke til andre avtaler.')
 test(bid,'SAME_PRODUCT','Hvert berørt eksakt produkt mot seg selv med samme konfigurasjon','Ingen kunstig forskjell eller uventet unknown på implementerte presise fakta.')
 test(bid,'SIDE_SWAP','Alle batchens berørte sammenligninger A→B og B→A','Tekst, scope, state, kilde og optionality flytter side uten betydningsendring.')
 test(bid,'CUSTOMER_MODE_SYNTHETIC','Eksakt dokumentfact X mot katalog Y, to alternative X/Y-verdipar, ukjent og eksplisitt avslag','Dokument X beholdes med document-origin; unknown er ikke not_selected; katalogtilgjengelighet er aldri kundens valg.')
 test(bid,'POSITIVE_CONTROL','Alle navngitte kontroller knyttet til batchen i det frosne regression-control-registry','Ingen utilsiktet betydningsendring. Kontroller beskytter scope/fakta, ikke den feilaktige nøkkelplasseringen som skal rettes.')

test('B-015','CATALOG_UNIT','Ekstra §2.4 privat versus transportbyrå/idrettslag/forening','30 000 kun profesjonell/organisert tyveri/skadeverk per skadetilfelle; ingen ubegrenset-påstand for privat.')
test('B-015','CROSS_PRODUCT','Tryg Innbo basis/Ekstra versus Storebrand Super og andre eksisterende transportskadeprodukter','Presis tyveri/skadeverk-rad skilles fra generell transport/bæring; B-005 uendret.')
test('B-015','TYPE_ISOLATION','Liknende transportord i Reise/Bil og uspesifisert dokumentlabel Skade ved flytting','Ingen feilaktig ny Innbo-tyverikey. Dokumentfakta beholdes konservativt.')
test('B-017','CATALOG_UNIT','Fremmøte, avgang og bagasje uten tilgang under overnatting i samme produkt','6 000 hotell/ubegrenset innhenting gjelder fremmøte; avgang har samlet 6 000 og betinget 24-timersinnhenting; bagasjegrense 500 særskilt.')
test('B-017','INHERITANCE','Aktivt fremtind-reise mot historisk eika-reise-p10/pluss og eksisterende kanalvalg','Ingen endring av historiske Eika-facts eller varighetsvalg; ingen kopiering mellom source versions.')
test('B-017','PRODUCT_COMPARISON','Fremtind mot Tryg og Storebrand etter B-021','Separate avgang/fremmøte-rader med person/hendelse og hotell/transport uttrykt; ingen falsk likhet basert kun på beløp.')
test('B-017','CUSTOMER_MODE_SYNTHETIC','Eldre dokument-key reise.forsinkelse.rute med reelt innhold, med/uten presist barn og etter gjentatt normalisering','Behold dokumenttekst/barn; ingen usikker katalogutfylling av avgang/fremmøte. Tom/unknown-placeholder behandles separat.')
test('B-018','ADDON','Ingen / Tap / Bruksverdi alene / gammelt addon-ID / Tap med Bruksverdi avslått','Ingen Tap-inferens fra child; Tap-valg gir betinget bruksverdifakta; gammelt ID auto-migreres ikke; child-avslag fjerner ikke Liv.')
test('B-018','CATALOG_UNIT','Tap-bruksverdi under 8 år, særvilkår og 50 % av avtalt Tap-sum','Ingen numerisk kundesum; hovedforfall etter 10 år på Tap forveksles ikke med child-alderskravet; avl-unntak og attest bevares.')
test('B-018','SPECIES_ISOLATION','Frende Hund/Katt, Medisin/Tann; Fremtind separat Bruk og Storebrand inkludert bruksverdi','Bare Frende Hund Tap-komposisjon endres; ingen generell Bruk→Liv-policy kopieres.')
test('B-019','PRODUCT_COMPARISON','OVERNIGHT-01: Standard og Super mot Tryg Ekstra/Premium i begge retninger','Kjent reise.overnatting på Storebrand; ingen false unknown eller unavailable; ingen kopiert tjenestereise.')
test('B-019','INHERITANCE','Standard/Super common, særskilt leiebil og avbestilling/arrangement','Generell dagstur omfattet sameksisterer med spesifikke overnattingskrav; geografi og medisinske unntak uendret.')
test('B-019','TYPE_ISOLATION','Ordet overnatting i bolig midlertidig bosted og reise sykeledsagelse','Ingen generell trip eligibility utledes fra en fordelsbetingelse.')
test('B-020','INHERITANCE','Hus Standard / Standard med råte-insekt-tillegg / Hus Pluss','Dyr-gren består i alle tre; Pluss/tillegg beholder lukt/isolasjon og legger til insektgren uten erstatning.')
test('B-020','ADDON','Insekter tilgjengelig men uvalgt, eksplisitt valgt, eksplisitt avslått; dyr inkludert','Produktmodus viser optional insekter ved siden av inkludert dyr; kundemodus krever valg og bevarer dyredekning ved insektavslag.')
test('B-020','CATALOG_UNIT','Bekjempelse mot bygningsskade, fullverdi, 2 000 versus 6 000 egenandel','Ingen blanding av handling, insekt/dyr/råte eller egenandelsområde; ikke bare materialnedbrytning for mus/rotter.')
test('B-020','CROSS_PRODUCT','Gjensidige mot uendrede Tryg/If/Fremtind/Storebrand/Frende Hus med brede keys','Ingen automatisk smal motpart fra generisk pest-tekst; ingen global datamigrering.')
test('B-020','TYPE_ISOLATION','Innbo-skadedyr og Bobil-skadedyr samt presis/uklar dokumentregel for Hus','Kun Hus-barna mappes når eksplisitt; ingen oppfunnet splitting av brede dokumentfacts.')
test('B-021','CATALOG_UNIT','Standard fremmøte og avgang med summer fra samme kilde-tabell','3 000/20 000 ved fremmøte; 3 000/1 500 ved avgang; ingen 23 000 eller gjensidig utbytting.')
test('B-021','INHERITANCE','Super som arver Standard og erstatter de to summetermene','Ubegrenset i hver korrekt hendelse; 1,5-time-/24-time-betingelser blir stående; ingen feilrettet hotellterskel.')
test('B-021','PRODUCT_COMPARISON','Storebrand Standard/Super versus Fremtind og Tryg','Samme hendelsesfamilie side ved side; hele scoped texts beholdes; bagasje500 og B-019 unaffected.')
test('B-022','ADDON','Gjensidige Hund/Katt: ingen, Liv, Bruk, Liv+Bruk; ulike rekkefølger','Streng manuell Bruk alene avvises; Liv alene inkluderer ikke Bruk; Liv+Bruk gyldig og deterministisk.')
test('B-022','SCOPE','Dependency self/cycle/dangling/provider/type/scope/version, ekskludert/foreløpig ugyldig komponent','Avvis ugyldig katalogkonfigurasjon/valg; ingen global ID-resolving på tvers av produktkontekst.')
test('B-022','CUSTOMER_MODE_SYNTHETIC','Bruk selected med Liv missing/not_selected/conflict; Liv selected med Bruk missing/not_selected','Behold dokumentfacts og base; ingen automatisk Liv eller Bruk; bare betinget katalogberikelse blokkeres, ikke hele avtalen.')
test('B-022','PRODUCT_COMPARISON','Produktmodus materialiserer tilgjengelig avhengig Bruk','Optional med dependency; Liv-facts dupliseres ikke under Bruk og ingen kundevalg muteres.')
test('B-022','SPECIES_ISOLATION','Hund arbeidsfunksjon versus Hund avl versus Katt avl og opphør','Behold 50 % arbeidsfunksjon/100 % fysisk avlsevnetap; 8-års Hund Bruk/10-års Katt Bruk versus separate Liv-opphør. Ingen hund-key på katt.')
test('B-022','CROSS_PRODUCT','Alle eksisterende tillegg uten nye metadata; Frende/Tryg/If/Storebrand/Fremtind kontrollkombinasjoner','Backward compatibility; ingen global Bruk→Liv eller endring av eksisterende topp-/leiebil-/maskinskadetillegg.')
for b in B:
 b['plan']['tests']=b['required_tests']
for c in canonical:
 c['planned_test_ids']=[r['test_id'] for r in reg if r['batch_id'] in c['batch_ids']]
unresolved=[]
for b in B:
 if b['remaining_requirement']:
  unresolved.append(dict(dependency_id='DEP-'+b['batch_id'][2:],batch_id=b['batch_id'],dependency_type='OTHER_BATCH' if b['dependencies'] else 'CANONICAL_EXTENSION_IMPLEMENTATION',depends_on=b['dependencies'],exact_requirement=b['remaining_requirement'],source_research_required=False,human_domain_review_required=False,closure_evidence='Nye avgrensede regresjoner og targeted source→catalog re-audit fra batchplanen; senere eksplisitt implementeringsautorisasjon.',status='NOT_IMPLEMENTED'))
counts={d:sum(b['final_disposition']==d for b in B) for d in ['READY_TO_IMPLEMENT','READY_TO_IMPLEMENT_AFTER_SPLIT','SOURCE_RESEARCH_REQUIRED','HUMAN_DOMAIN_REVIEW_REQUIRED','CANONICAL_EXTENSION_REQUIRED','KEEP_CURRENT_CONSERVATIVE_STATE','BLOCKED_BY_OTHER_BATCH']}
order=['B-019','B-017','B-021','B-015','B-020','B-022','B-018']
gates=[]
for i,bid in enumerate(order,1):
 gates.append(dict(sequence=i,batch_id=bid,requires_passed_batches=byid[bid]['dependencies'],gate='Source hash + egne katalog-/mappingtester + document>catalog + scope + same-product/side-swap + navngitte positive controls + berørt source→catalog re-audit.',canonical_gate_first=byid[bid]['final_disposition']=='CANONICAL_EXTENSION_REQUIRED',note='B-022 må gate delt add-on/selection-kontrakt før providerdata kobles på; B-018 kjøres deretter.' if bid=='B-022' else 'Ingen implementering utført i denne reviewen.'))
final_gate=['Hele eksisterende suite må fortsatt bestå (sist dokumentert 2038/2038) sammen med nye regresjoner.','TypeScript, ESLint, webpack production build, syntetisk HTTP/PDF-runtime og git diff --check.','Ny målrettet re-audit av bare berørte produkter/familier, og kontrollfingerprint for tidligere validerte 22 produkter/182 uendrede. Ingen ny 204-produkt full-audit.','Bevar source-originaler og alle tidligere arbeidspunkter. Ingen commit/push/deploy uten egen ordre.']
report=dict(title='NITO_WAVE2_SEMANTIC_RESOLUTION',status='WAVE2_SEMANTIC_RESOLUTION_COMPLETE',review_date='2026-10-02',mode='READ_ONLY_PROJECT; new artifacts only in /tmp/nito-wave2-semantic-resolution',baseline={'head':baseline['head'],'branch':baseline['branch'],'staged_count':0,'working_tree_expected_modified_or_untracked':17,'previous_validated_tests':'2038/2038 PASS (previous run, NOT rerun in this review)','previous_gates':'TypeScript, ESLint, webpack build, synthetic HTTP/PDF, diff check and targeted re-audit PASS','completed_batches':'B-001–B-014 and B-016','resolved_P1_signatures_before_review':21,'previously_intentional_products':22,'previously_unchanged_products':182,'previous_verified_hashes':16,'previous_comparison_directions':714,'previous_affected_comparison_rows':496},input_batches=ids,counts=counts,batches=B,canonical_decisions=canonical,mapping_decisions=mapping,sources=sources,source_research_required=[],human_domain_review_required=[],source_qualification='Only frozen local corpus. Unknown Gjensidige versions/dates remain unknown; no public freshness or broad pilot-readiness claim.',source_interpretation_notes=['Gjensidige web Bruk is availability/dependency evidence; exact thresholds/expiry come from its own full terms. General abbreviated webpage wording is not used to relax specific full-term eligibility.','Frende Bruksverdi inclusion and Gjensidige Bruk dependency are different relationships.','Original CR human_signoff placeholders are NOT treated as human approval. No global HR queue item is a dependency of these seven batches; future implementation still requires new authorization.','Source totals are not retested globally; only the 12 artifacts cited by these seven resolutions were targeted hash-checked.'],execution_order=gates,final_implementation_gate=final_gate,wave3_readiness={'answer':'YES','conditional':True,'current_wave3_authorized':False,'explanation':'Etter at HELE den spesifiserte sekvensen, inkludert de tre canonical-utvidelsene og B-018-avhengigheten, er implementert og alle gates består, er disse Wave 2-avhengighetene semantisk lukket. Bare de tre READY-batchene er ikke nok. Dette autoriserer ikke Wave 3 nå og sertifiserer ikke pilotklarhet eller løser andre bølgers source/human-spørsmål.'},unresolved_dependencies=unresolved,regression_plan=reg,child_batches=[],next_step='Be om/gi en egen kontrollert implementeringsordre for den nå spesifiserte Wave 2-sekvensen. Start B-019; ingen ny kilde- eller menneskelig domeneavklaring er identifisert som nødvendig for disse sju batchenes avgrensede spørsmål. Ikke start implementering i denne oppgaven.')

def dump(name,obj): (OUT/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
def csvout(name,rows,fields=None):
 fields=fields or list(rows[0])
 with (OUT/name).open('w',newline='') as f:
  w=csv.DictWriter(f,fieldnames=fields);w.writeheader()
  for r in rows:w.writerow({k:json.dumps(v,ensure_ascii=False) if isinstance(v,(list,dict)) else v for k,v in r.items() if k in fields})
dump('wave2-resolution.json',report)
csvout('batch-resolutions.csv',B)
csvout('canonical-decisions.csv',canonical)
csvout('mapping-decisions.csv',mapping)
csvout('unresolved-dependencies.csv',unresolved)
csvout('regression-plan.csv',reg)

def source_md(ids):
 return '\n'.join(f"- **{s['source_id']}**: [{s['local_path']}]({s['absolute_path']}); {s['location']}; dokument {s['document_number'] or 'ikke oppgitt'}, gyldighet {s['valid_from'] or 'ikke oppgitt'}. SHA-256 `{s['sha256']}`. [Offisiell referanse]({s['url']}). {s['meaning']}" for s in sources if s['source_id'] in ids)
md=['# NITO_WAVE2_SEMANTIC_RESOLUTION','', 'Status: **WAVE2_SEMANTIC_RESOLUTION_COMPLETE**. Analyse fullført; ingen batch er implementert i denne oppgaven.','', '## Baseline','',f"Branch main; HEAD `{baseline['head']}`; 17 eksisterende prosjektendringer; 0 staged. Sist dokumentert validering er 2038/2038, TypeScript, lint, webpack build, syntetisk HTTP/PDF-runtime og targeted audit PASS. Disse implementeringskontrollene er ikke kjørt på nytt i en read-only semantikkreview.",'','Wave 1 og trygg Wave 2: 21 P1-signaturer løst, 22 produkter tilsiktet endret, 182 uendret, 16 tidligere kildehasher, 714 sammenligningsretninger og 496 berørte rader kontrollert. Ingen av tallene er omregnet som nye resultater her.','', '## Batch decisions','', '| Batch | Disposition | Risiko | Anbefalt implementeringsmodell |','|---|---|---|---|']
md += [f"| {b['batch_id']} | {b['final_disposition']} | {b['implementation_risk']} | {b['recommended_model']} |" for b in B]
md += ['',f'Input batches: 7. Sum sluttklassifiseringer: {sum(counts.values())}.','']+[f'- {k}: **{v}**' for k,v in counts.items()]
md+=['','## Semantiske beslutninger per batch']
for b in B:
 md+=['',f"### {b['batch_id']} — {b['title']}",'',f"**{b['final_disposition']}** — {b['semantic_problem']}",'',f"**Katalog nå:** {b['existing_catalog_state']}",'',f"**Canonical nå:** {b['existing_canonical_state']}",'',f"**Beslutning:** {b['decision']}",'',f"**Produktvisning:** {b['plan']['expected_result']}",'',f"**Kundemodus:** {b['customer_mode_impact']}",'',f"**Avhengigheter:** {', '.join(b['dependencies']) or 'Ingen annen batch'}. Opprinnelige review-ID-er: {', '.join(b['original_review_dependencies'])}.",'',f"**Risiko:** {b['implementation_risk']} — {b['risk_explanation']}",'',f"**Gjenstående krav:** {b['remaining_requirement'] or 'Ingen uavklart semantikk; egen ordre kreves før implementering.'}",'', '**Avgrenset kildebevis:**','',source_md(b['source_evidence']),'',f"**Testplan:** {', '.join(b['required_tests'])}. Navngitte kontroller: {', '.join(b['named_controls'])}.",'',f"**Fremtidige filer:** {', '.join(b['implementation_files'])}."]
 if b.get('proof_boundary'):md+=['',b['proof_boundary']]
md+=['','## Canonical decisions','']
for c in canonical:
 md += [f"- **{c['decision_id']} / {c['classification']}**: {c['semantic_definition']} {c['why_existing_structure_fails_or_suffices']}"]
md += ['','Alle nøkkeldefinisjoner, scope, produkt-/kundekonsekvenser, falsk-ekvivalensrisiko og test-ID-er står i `canonical-decisions.csv` og JSON. Tre batcher trenger utvidelse; ikke tre nye generelle motorer. B-015 og B-020 trenger smalere termidentiteter. B-022 trenger eksplisitte tilleggsavhengigheter, seleksjonsevidens og et artsriktig Katt-barn.','', '## Mapping decisions','', 'B-017 og B-021 gjenbruker eksisterende avgang_sum/fremmote_sum. B-019 gjenbruker reise.overnatting. B-018 er komposisjon, ikke et nytt forsikringsbegrep. Ikke aliaser brede eldre keys globalt til ett eller flere presise barn. Dokumenter med usikker scope beholdes konservativt; de gir ikke lisens til å fylle en motstridende kataloggrense.','', '## Source research required','', 'Ingen ny source-research-oppgave er identifisert for de sju avgrensede semantiske spørsmålene. Gjensidiges ukjente dokumentdatoer/versjoner beholdes som ukjente. Rapporten validerer ikke offentlig ferskhet. Nettsidens korte Bruk-omtale erstatter ikke fullvilkårenes presise kvalifikasjoner.','', '## Human review required','', 'Ingen av de fem globale human-domain-spørsmålene er registrert som avhengighet til disse sju batchene. Ingen menneskelig godkjenning er simulert. De tidligere CR-plassholderne for human signoff er ikke bevis for faktisk godkjenning; implementering og de spesifiserte arkitekturutvidelsene må autoriseres separat.','', '## Implementation-ready batches','', '**B-017, B-019, B-021**. B-021 har eksplisitt ordnet avhengighet av B-017s mapping-/kundeprioritetsgate. **B-015, B-020, B-022** har konkrete minimale utvidelsesdesign, men klassifiseres som CANONICAL_EXTENSION_REQUIRED. **B-018** venter på B-022s delte seleksjonsguard. Fullstendige fremtidige endringsinstruksjoner finnes i `implementation-ready-batches.md`.','', '## Recommended execution order','', '**B-019 → gate → B-017 → gate → B-021 → gate → B-015 (canonical gate først) → gate → B-020 (canonical gate først) → gate → B-022 (delt kontrakt før providerkobling) → gate → B-018 → full Wave 2-gate.**','', 'Ingen child batches er opprettet; READY_TO_IMPLEMENT_AFTER_SPLIT = 0. De interne arkitekturgatene er ikke nye batch-ID-er.','', '## Regression plan','',f'{len(reg)} eksplisitte fremtidige testspesifikasjoner i regression-plan.csv; ingen nye prosjekttester er skrevet eller kjørt. Dekker egne kilder, scope, arv, tilvalg, samme produkt, sideskifte, kryssprodukt, produktvisning, syntetisk kundemodus og relevant type-/artsisolasjon.','', 'Navngitte positive kontroller er koblet maskinlesbart til hver batch. OVERNIGHT-01 er eksplisitt inkludert. PC-2076 beskytter Fremtinds riktige fremmøteregel; PC-0534 beskytter Storebrands betingede bagasje500; PC-0826/0847 beskytter Gjensidiges grunnunntak/tilvalgsgrense; Frende Tap-opphør og artsisolasjon beholdes.','', 'Endelig implementeringsgate:','']+['- '+x for x in final_gate]
md += ['','## Wave 3 readiness','', '**YES — betinget av implementering og PASS for hele sekvensen, inkludert utvidelsene.** Det er ikke grønt lys for Wave 3 nå. Bare å gjennomføre de tre READY-batchene lukker ikke Wave 2. Ingen av de 73 Wave 3-batchene er vurdert eller igangsatt. Dette er heller ikke en ny pilotgodkjenning.','', '## Project integrity','', 'Se quality-check.json for faktisk sluttverifikasjon mot review-baseline.json: HEAD, branch, staged, git-status, alle prosjektfingeravtrykk og alle tre immutable inputtrær. En dirty working tree med de samme 17 endringene er forventet og korrekt. .env.local er ikke lest eller endret. Ingen stage/commit/push/deploy/reset/revert/stash/clean; Railway urørt.','', '## Output files','']
required=['wave2-resolution-summary.md','wave2-resolution.json','batch-resolutions.csv','canonical-decisions.csv','mapping-decisions.csv','implementation-ready-batches.md','unresolved-dependencies.csv','regression-plan.csv','quality-check.json']
md += [f'- [{x}]({OUT/x})' for x in required]
md += ['', 'Støttefiler i samme tillatte mappe: review-baseline.json, current-state-probe.mjs, current-state-evidence.json og write-review.py. Proben leste nåværende kode/katalog (13 avgrensede produkter, fire komponentkombinasjoner, fire sammenligningspar og én syntetisk dokumentnøkkel), uten mutert katalog eller nye tester. Node varslet bare eksisterende MODULE_TYPELESS_PACKAGE_JSON; ingen endring utført.','', '## Next step','',report['next_step'],'', 'STOPP. Ingen implementering startet.']
(OUT/'wave2-resolution-summary.md').write_text('\n'.join(md)+'\n')
planmd=['# Fremtidig Wave 2-implementering — ikke utført','', 'Denne filen er en konkret gjennomføringsplan, ikke en autorisasjon eller en utført endring. Kun B-017, B-019 og B-021 er READY_TO_IMPLEMENT. Øvrige batcher har navngitte inngangsgates.','', '**Rekkefølge:** '+' → gate → '.join(order)+' → full gate.']
for bid in order:
 b=byid[bid];p=b['plan'];planmd += ['',f"## {bid} — {b['final_disposition']}",'',f"Avhengigheter: {', '.join(b['dependencies']) or 'ingen'}. Modell: {b['recommended_model']}. Risiko: {b['implementation_risk']}.",'',f"Inngangskrav: {b['remaining_requirement'] or 'Separat implementeringsordre; kilder og semantikk avklart.'}"]
 for label,key in [('WHAT TO CHANGE','what_to_change'),('WHAT NOT TO CHANGE','what_not_to_change'),('AFFECTED SCOPE','affected_scope'),('EXPECTED RESULT','expected_result'),('SOURCE / PROVENANCE','source_provenance'),('TESTS','tests'),('TARGETED RE-AUDIT','targeted_reaudit'),('ACCEPTANCE CRITERIA','acceptance_criteria')]:
  v=p[key];planmd+=['',f'### {label}','']+(['- '+str(s) for s in v] if isinstance(v,list) else [v])
 planmd+=['','### FILES','']+['- '+f for f in b['implementation_files']]
planmd+=['','## Final gate','']+['- '+x for x in final_gate]
(OUT/'implementation-ready-batches.md').write_text('\n'.join(planmd)+'\n')

# Integrity and consistency checks. Read-only shell commands; no env/config contents read.
def git(*args):return subprocess.check_output(['git',*args],cwd=ROOT,text=True)
head=git('rev-parse','HEAD').strip();branch=git('branch','--show-current').strip();status=git('status','--short');staged=git('diff','--cached','--name-only')
paths=sorted(set(git('ls-files','--cached','--others','--exclude-standard','-z').split('\0'))-{''})
project={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in paths if not Path(p).name.startswith('.env') and (ROOT/p).is_file()}
inputs={}
for root in ['/tmp/source-catalog-completeness-audit','/tmp/source-catalog-remediation-triage','/tmp/nito-catalog-remediation-evening']:
 for p in sorted(Path(root).rglob('*')):
  if p.is_file():inputs[str(p)]=hashlib.sha256(p.read_bytes()).hexdigest()
# Accommodate baseline root convention explicitly, not by silently dropping entries.
base_project=baseline['project_hashes'];base_inputs=baseline['input_hashes']
if base_project and next(iter(base_project)).startswith(str(ROOT)+'/'):project={str(ROOT/p):h for p,h in project.items()}
diff=subprocess.run(['git','diff','--check'],cwd=ROOT,capture_output=True,text=True)
checks=dict(seven_batches=len(B)==7 and {b['batch_id'] for b in B}==set(ids),one_disposition_each=len({b['batch_id'] for b in B})==7 and sum(counts.values())==7,all_ready_have_exact_plan=all(set(['what_to_change','what_not_to_change','affected_scope','expected_result','source_provenance','tests','targeted_reaudit','acceptance_criteria'])<=set(b['plan']) and b['required_tests'] for b in B if b['final_disposition']=='READY_TO_IMPLEMENT'),all_unresolved_have_exact_requirement=all(b['remaining_requirement'] for b in B if b['final_disposition']!='READY_TO_IMPLEMENT'),dependencies_resolve=all(d in byid for b in B for d in b['dependencies']),execution_order_respects_dependencies=all(order.index(d)<order.index(b['batch_id']) for b in B for d in b['dependencies']),child_batch_ids_unique=True,no_source_research_needed=True,no_human_domain_dependency=True,all_sources_have_verified_hashes=all(s['hash_verified'] for s in sources),head_unchanged=head==baseline['head'],branch_unchanged=branch==baseline['branch'],staged_unchanged=staged==baseline['staged'],git_status_unchanged=status==baseline['status'],project_membership_and_hashes_unchanged=project==base_project,immutable_inputs_membership_and_hashes_unchanged=inputs==base_inputs,git_diff_check_pass=diff.returncode==0)
parsed={}
for name in required:
 p=OUT/name
 if name.endswith('.json') and name!='quality-check.json':json.loads(p.read_text());parsed[name]='PASS'
 elif name.endswith('.csv'):
  rows=list(csv.DictReader(p.open()));assert rows and all(None not in r for r in rows);parsed[name]=dict(status='PASS',rows=len(rows))
checks['all_required_outputs_except_quality_present']=all((OUT/n).exists() for n in required if n!='quality-check.json')
checks['output_json_csv_parse']=True
quality=dict(status='PASS' if all(checks.values()) else 'FAIL',review_status='WAVE2_SEMANTIC_RESOLUTION_COMPLETE' if all(checks.values()) else 'WAVE2_SEMANTIC_RESOLUTION_INTEGRITY_FAILURE',checks=checks,counts=counts,input_batches=7,total_dispositions=sum(counts.values()),ready_batches=[b['batch_id'] for b in B if b['final_disposition']=='READY_TO_IMPLEMENT'],canonical_decision_count=len(canonical),mapping_decision_count=len(mapping),planned_regressions=len(reg),new_project_tests_executed=0,prior_full_suite='2038/2038 PASS; not rerun',targeted_read_only_probes={'product_count':13,'addon_combinations':4,'comparison_pairs':4,'synthetic_document_key_cases':1,'catalog_mutations':0},source_hash_checks=len(sources),head=head,branch=branch,staged_count=len(staged.splitlines()),existing_working_tree_changes=len(status.splitlines()),project_fingerprint_file_count=len(project),immutable_input_fingerprint_file_count=len(inputs),project_changed_paths=sorted(p for p in set(project)|set(base_project) if project.get(p)!=base_project.get(p)),input_changed_paths=sorted(p for p in set(inputs)|set(base_inputs) if inputs.get(p)!=base_inputs.get(p)),parse_checks=parsed,forbidden_operations={'project_writes':False,'private_PDF_access':False,'env_read_or_write':False,'web_or_download':False,'stage_commit_push_deploy':False,'reset_revert_stash_clean':False,'Railway_changes':False,'Wave3_review_or_implementation':False},output_directory=str(OUT))
dump('quality-check.json',quality)
assert J(OUT/'quality-check.json')['status']=='PASS',json.dumps({k:v for k,v in checks.items() if not v})
print(json.dumps({'status':quality['status'],'counts':counts,'planned_regressions':len(reg),'source_hashes':len(sources),'project_files':len(project),'input_files':len(inputs),'required_outputs':len(required)},ensure_ascii=False,indent=2))
