import test from 'node:test';
import assert from 'node:assert/strict';
import {enrichExtractedAgreementWithCatalog} from '../lib/catalog-enrichment.ts';
import {canonicalCoverage} from '../lib/coverage-status.ts';
import {groupInsurances,groupTerms,groupAddOnNames} from '../lib/comparison.ts';
import {coverageDetailPresentation} from '../lib/coverage-detail-presentation.ts';
import {parseExtractionResponse} from '../lib/analysis-output.ts';
import {planExtractionBatches} from '../lib/analysis-batching.ts';
import {enrichBatch,mergeBatchResults} from '../lib/analysis-merge.ts';
import {createAnalysisTelemetry} from '../lib/analysis-telemetry.ts';
import {portfolioPrice} from '../lib/portfolio-price-presentation.ts';
const date=new Date('2026-09-24');
const term=(name,value,canonicalKey)=>({name,value,canonicalKey:canonicalKey??null});
const enrich=(terms=[],productName='Kasko',company='Gjensidige',coverageSummary=null)=>enrichExtractedAgreementWithCatalog({company,totalAnnualPremium:null,totalAnnualPremiumScope:'partial_or_unclear',insurances:[{type:'Bil',productName,annualPremium:null,deductible:null,coverageSummary,addOns:[],importantTerms:terms}]},date).insurances[0];
const values=(r,key)=>r.importantTerms.filter(t=>t.key===key);
const status=(r,key)=>canonicalCoverage(r,'Bil',`${key}.dekning`)?.status;
const details=(a,b=a)=>coverageDetailPresentation(groupTerms(groupInsurances([a],[b],null)[0],null));
for(const key of ['bilnokkel.egenandel','veihjelp.egenandel','kasko.egenandel','reparasjon.garanti'])test(`asymmetry: silence/unknown leaves same eligible catalog ${key}`,()=>{
 const a=enrich(),b=enrich([term('Bilnøkkel','Ikke dokumentert'),term('Veihjelp','Ikke dokumentert')]);assert.deepEqual(values(a,key),values(b,key));assert.equal(values(b,key)[0].coverageOrigin,'catalog');assert.ok(values(b,key)[0].source.note.includes('forsikringsbevis'));
});
for(const [label,key,value] of [['Bilnøkkel – egenandel','bilnokkel.egenandel','1 000 kr'],['Bilnøkkel – forsikringssum','bilnokkel.grense','9 000 kr'],['Veihjelp – egenandel','veihjelp.egenandel','900 kr']])test(`asymmetry: explicit customer ${key} never copied across sides`,()=>{const a=enrich([term(label,value)]),b=enrich();assert.deepEqual(values(a,key).map(t=>t.value),[value]);assert.equal(values(a,key)[0].coverageOrigin,'document');assert.notEqual(values(b,key)[0].value,value);});
for(const product of ['Kasko','Pluss'])for(const [text,expected] of [['Ikke dokumentert','unknown'],['Ikke valgt','not_selected'],['Valgt','selected']])test(`optional ${product} ${expected}`,()=>{const r=enrich([term('Leiebil',text)],product);assert.equal(status(r,'leiebil'),expected);assert.equal(values(r,'leiebil.dager').length>0,expected==='selected');assert.ok(r.catalogFacts.some(f=>f.key==='leiebil.dager'));});
test('optional silence is unknown despite catalog details',()=>{const r=enrich();assert.equal(status(r,'leiebil'),'unknown');assert.equal(values(r,'leiebil.dager').length,0);});
test('another provider uses same silence policy',()=>{const a=enrich([],'Kasko','Tryg'),b=enrich([term('Veihjelp','Ikke dokumentert')],'Kasko','Tryg');assert.ok(a.catalogReference);assert.deepEqual(a.importantTerms.filter(t=>t.coverageOrigin==='catalog'&&t.key.startsWith('veihjelp.')),b.importantTerms.filter(t=>t.coverageOrigin==='catalog'&&t.key.startsWith('veihjelp.')));assert.ok(a.importantTerms.some(t=>t.key.startsWith('veihjelp.')));});
for(const value of ['750 kr','900 kr'])test(`semantic roadside deductible, not numeric mapping ${value}`,()=>{const r=enrich([term('Veihjelp – egenandel',value,'veihjelp.grense')]);assert.deepEqual(values(r,'veihjelp.egenandel').map(t=>t.value),[value]);assert.equal(values(r,'veihjelp.transport.grense').length,0);});
test('source catalog roadside amount remains a deductible',()=>{const r=enrich();assert.match(values(r,'veihjelp.egenandel')[0].value,/750.*offentlig/);assert.ok(!r.importantTerms.some(t=>t.key.startsWith('veihjelp.')&&t.key.includes('grense')&&t.value.includes('750')));});
test('key composite splits sum deductible count with document origin',()=>{const r=enrich([term('Bilnøkkel','Forsikringssum 7 500 kr; egenandel 1 500 kr; maks ett skadetilfelle')]);for(const [key,value] of [['bilnokkel.grense','7 500 kr'],['bilnokkel.egenandel','1 500 kr'],['bilnokkel.antall_skader','maks ett skadetilfelle']]){assert.deepEqual(values(r,key).map(t=>t.value),[value]);assert.equal(values(r,key)[0].coverageOrigin,'document');}const d=details(r);assert.equal(d.additional.filter(t=>t.key==='bilnokkel.grense').length,1);assert.equal(d.additional.filter(t=>t.key==='bilnokkel.egenandel').length,1);assert.equal(d.additional.filter(t=>t.key==='bilnokkel.antall_skader').length,1);});
test('summary deductible is not extracted as key sum',()=>{const r=enrich([],'Kasko','Gjensidige','Bilnøkkel egenandel 900 kr.');assert.equal(values(r,'bilnokkel.egenandel')[0].value,'900 kr');assert.equal(values(r,'bilnokkel.grense')[0].coverageOrigin,'catalog');});
for(const value of ['15 000 km','17 000 km','20 000 km'])test(`document totalskade wins only its own identity ${value}`,()=>{const r=enrich([term('Totalskadegaranti – kilometer',value,'nyverdi.km'),term('Årlig kjørelengde','20 000 km','nyverdi.km'),term('Kilometerstand','164 000 km'),term('Avtalt maksimal kilometerstand','180 000 km'),term('Maskinskade – kilometer','200 000 km')]);assert.deepEqual(values(r,'nyverdi.km').map(t=>t.value),[value]);assert.equal(values(r,'nyverdi.km')[0].coverageOrigin,'document');assert.deepEqual(values(r,'kjoretoy.kjorelengde').map(t=>t.value),['20 000 km']);assert.ok(details(r).compact.some(t=>t.key==='nyverdi.km'&&t.first===value));});
test('ambiguous kilometergrense cannot become document nyverdi',()=>{const r=enrich([term('Kilometergrense','20 000 km')]);assert.equal(values(r,'nyverdi.km')[0].coverageOrigin,'catalog');});
test('catalog 20000 is directly sourced to Kasko full terms page 15',()=>{const f=values(enrich(),'nyverdi.km')[0];assert.equal(f.value,'Inntil 20 000 km');assert.equal(f.source.documentId,'gjKasko');assert.equal(f.source.page,15);assert.equal(f.coverageOrigin,'catalog');});
for(const [first,second] of [['Valgt','Ikke valgt'],['Valgt','Ikke dokumentert'],['Valgt','Valgt'],['Ikke dokumentert','Ikke dokumentert']])test(`family child labels survive ${first}/${second}`,()=>{const r=enrich([term('Leiebil',first),term('Veihjelp',second)],'Unknown','Unknown');const rows=details(r).compact.filter(t=>t.key.endsWith(':status'));assert.ok(rows.some(t=>t.label==='Leiebil'));assert.ok(rows.some(t=>t.label==='Veihjelp'));assert.equal(status(r,'leiebil'),first==='Valgt'?'selected':first==='Ikke valgt'?'not_selected':'unknown');});
test('different family also retains child identity',()=>{const r=enrich([term('Bilnøkkel','Valgt'),term('Ladekabel','Ikke valgt')],'Unknown','Unknown');const rows=details(r).compact;assert.ok(rows.some(t=>t.label==='Bilnøkkel'&&t.first==='✓ Valgt'));assert.ok(rows.some(t=>t.label==='Ladekabel'&&t.first==='❌ Ikke valgt'));});
function rawCar(id,productName,unknown=false){return {type:'Bil',company:'Gjensidige',productName,canonicalProductName:productName,annualPremium:null,deductible:null,coverageSummary:null,documentRole:'individual_agreement',agreementPeriod:null,documentIndices:[1],objectIdentifiers:[{type:'registration',value:id,documentIndices:[1]}],addOns:[],importantTerms:[
 term('Årlig kjørelengde','20 000 km','nyverdi.km'),term('Leiebil',productName==='Kasko'?'Ikke valgt':'Valgt'),
 ...(productName==='Kasko'?[term('Totalskadegaranti','1 år / 15 000 km'),...(unknown?[term('Bilnøkkel','Ikke dokumentert'),term('Veihjelp','Ikke dokumentert')]:[])]:[
 term('Maskinskade','10 år / 200 000 km'),term('Bilnøkkel – forsikringssum','15 000 kr','bilnokkel.grense'),
 term('Leiebil ved reparasjon','60 dager'),term('Leiebil ved totalskade/tyveri','30 dager'),term('Leiebil ved tekniske problemer i Norden','30 dager'),term('Leiebil på feriereise utenfor Norden','15 dager')]),
 ...['premie.ekskl_tfa','premie.tfa','premie.total'].map((key,i)=>term(['Forsikringspris','Trafikkforsikringsavgift','Totalpris'][i],`${(productName==='Kasko'?[12457,2329,14786]:[9518,3270,12788])[i]} kr`,key))
 ].map(t=>({...t,documentIndices:[1]}))};}
function pipeline(side,reverse=false,completeReverse=false){let records=[rawCar('ZZ10001','Kasko',side==='offer'),rawCar('ZZ10002','Pluss')];if(reverse)records=records.toReversed();const docs=records.map((r,documentIndex)=>({side,documentIndex,text:'Synthetic '.repeat(9000),pages:1}));let batches=planExtractionBatches(docs).map(batch=>({batch,agreement:enrichBatch(parseExtractionResponse({output_text:JSON.stringify({company:'Gjensidige',totalAnnualPremium:null,totalAnnualPremiumScope:'partial_or_unclear',insurances:batch.documents.map(d=>records[d.documentIndex])})}),batch,createAnalysisTelemetry('00000000-0000-0000-0000-000000000000'))}));assert.equal(batches.length,2);if(completeReverse)batches=batches.toReversed();return mergeBatchResults(batches,side,false);}
for(const reverse of [false,true])for(const completeReverse of [false,true])test(`two-car extraction/batch/comparison/pricing reversed=${reverse}/${completeReverse}`,()=>{
 const a=pipeline('existing'),b=pipeline('offer',reverse,completeReverse),left=a.insuranceData.insurances,right=b.insuranceData.insurances;
 const groups=groupInsurances(left,right,null);assert.equal(groups.length,2);for(const group of groups){assert.equal(group.first.length,1);assert.equal(group.second.length,1);assert.equal(group.first[0].objectIdentifiers[0].value,group.second[0].objectIdentifiers[0].value);}
 for(const side of [left,right]){const kasko=side.find(r=>r.productName==='Kasko'),pluss=side.find(r=>r.productName==='Pluss');assert.equal(status(kasko,'leiebil'),'not_selected');assert.equal(status(pluss,'leiebil'),'selected');assert.equal(status(pluss,'maskinskade'),'selected');assert.equal(values(kasko,'nyverdi.km')[0].value,'15 000 km');assert.equal(values(kasko,'kjoretoy.kjorelengde')[0].value,'20 000 km');assert.equal(values(pluss,'maskinskade.alder')[0].value,'10 år');assert.equal(values(pluss,'maskinskade.km')[0].value,'200 000 km');assert.equal(values(pluss,'bilnokkel.grense')[0].value,'15 000 kr');assert.match(groupAddOnNames([pluss],'bil'),/Leiebil/);assert.match(groupAddOnNames([pluss],'bil'),/Maskinskade/);for(const duration of ['60 dager','30 dager','15 dager'])assert.ok(pluss.importantTerms.some(t=>t.coverageOrigin==='document'&&t.value===duration));}
 const ka=left.find(r=>r.productName==='Kasko'),kb=right.find(r=>r.productName==='Kasko');for(const key of ['bilnokkel.egenandel','veihjelp.egenandel'])assert.deepEqual(values(ka,key),values(kb,key));
 for(const doc of [a,b])assert.deepEqual(portfolioPrice(doc).components.map(c=>c.amount),[2197500,559900,2757400]);
 const mobility=details(ka,kb).compact.filter(r=>['Leiebil','Veihjelp'].includes(r.label));assert.equal(mobility.length,2);assert.ok(mobility.every(r=>r.first===r.second));
});
