import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {matchObjects,normalizeObjectIdentifier,objectWarning,missingEvidence,objectMatchingCounts} from '../lib/object-matching.ts';
import {groupInsurances,groupTerms,createDifferences,groupAddOnNames} from '../lib/comparison.ts';
import {presentImportantDifferences} from '../lib/comparison-presentation.ts';
import {runHybridMatching} from '../lib/hybrid-matching.ts';
import {parseExtractionResponse,buildExtractionRequest,sanitizeAnalysisDocumentForClient} from '../lib/analysis-output.ts';
import {planExtractionBatches} from '../lib/analysis-batching.ts';
import {enrichBatch,mergeBatchResults} from '../lib/analysis-merge.ts';
import {createAnalysisTelemetry} from '../lib/analysis-telemetry.ts';
const id=(value,type='registration')=>({type,value,documentIndices:[1]});
const object=(type='Bil',value='AB10001',index=1)=>({type,company:'If',productName:'Kasko',canonicalProductName:'Kasko',objectIdentifiers:value?[id(value)]:[],annualPremium:null,deductible:null,coverageSummary:null,documentIndices:[1],addOns:[],importantTerms:[{name:'Forsikringspris',key:'premie.ekskl_tfa',value:`${index}000 kr`,coverageOrigin:'document'},{name:'Grense',key:type==='Bil'?'nyverdi.km':'tilhenger.gods.sum',value:`${index}0 000 km`,coverageOrigin:'document'}]});
const portfolio=()=>[object('Bil','AB10001',1),object('Bil','AB10002',2),object('Bil','AB10003',3),object('Tilhenger','AB20001',4),object('Tilhenger','AB20002',5),object('Snøscooter','AB30001',6),object('Campingvogn','AB40001',7)];
const shuffled=a=>[a[4],a[2],a[6],a[0],a[5],a[1],a[3]].map(i=>({...structuredClone(i),company:'Tryg',productName:'Pluss',canonicalProductName:'Pluss'}));
const doc=insurances=>({source:'pdf',insuranceData:{company:null,totalAnnualPremium:null,insurances}});
function compare(a,b,context={}){const groups=groupInsurances(a,b,null,context);const differences=createDifferences(doc(a),doc(b),groups,null);return {groups,differences,shown:presentImportantDifferences(differences,groups,null)};}
test('full portfolio: 3 cars, 2 trailers, snowmobile and caravan match shuffled provider/product-independent IDs',()=>{
 const a=portfolio(),b=shuffled(a),result=compare(a,b);assert.equal(result.groups.length,7);
 for(const g of result.groups){assert.equal(g.objectMatch.reason,'EXACT_OBJECT_ID');assert.equal(g.first[0].objectIdentifiers[0].value,g.second[0].objectIdentifiers[0].value);assert.notEqual(g.first[0].company,g.second[0].company);assert.notEqual(g.first[0].productName,g.second[0].productName);assert.ok(groupTerms(g,null).every(t=>!t.first||!t.second||t.first===t.second));}
 assert.ok(result.shown.every(d=>d.kind!=='object'));assert.equal(new Set(result.groups.map(g=>g.scopeId)).size,7);
});
for(const index of [0,1,2,3,4,5,6])test(`missing object ${index} visible without contaminating other pairs`,()=>{
 const a=portfolio(),b=shuffled(a).filter(i=>i.objectIdentifiers[0].value!==a[index].objectIdentifiers[0].value);const r=compare(a,b);
 assert.equal(r.groups.filter(g=>g.objectMatch.status==='matched').length,6);const absent=r.groups.find(g=>g.objectMatch.status==='unmatched_existing');assert.equal(absent.first[0],a[index]);assert.equal(absent.objectMatch.reason,index<5?'MISSING_OBJECT':'MISSING_TYPE');assert.equal(r.shown.filter(d=>d.kind==='object').length,1);assert.ok(!r.differences.some(d=>d.kind==='price'));assert.match(r.shown.find(d=>d.kind==='object').text,/ikke funnet/);
});
test('new offer-only object has its own warning; known car does not absorb it',()=>{const a=portfolio(),b=[...shuffled(a),object('Bil','AB10009')];const r=compare(a,b);assert.equal(r.groups.filter(g=>g.objectMatch.status==='matched').length,7);assert.equal(r.groups.at(-1)?.key==='bil'||r.groups.some(g=>g.objectMatch.status==='unmatched_offer'),true);assert.equal(r.shown.filter(d=>d.kind==='object').length,1);});
for(const type of ['Bil','Tilhenger','Snøscooter','Campingvogn']){
 test(`${type}: two unknown IDs never pair by index, name, provider, product or price`,()=>{const a=[object(type,null),object(type,null)];const r=compare(a,[...a].reverse());assert.equal(r.groups[0].objectMatch.status,'ambiguous');assert.deepEqual(groupTerms(r.groups[0],null),[]);assert.equal(r.shown.length,1);assert.equal(r.shown[0].kind,'object');});
 test(`${type}: a unique type pair is explicitly weaker than exact identity`,()=>{const m=matchObjects([object(type,null)],[object(type,null)]);assert.equal(m[0].reason,'UNIQUE_TYPE_PAIR');});
 test(`${type}: conflicting explicit IDs prevent one-to-one fallback`,()=>{const m=matchObjects([object(type,'AB10001')],[object(type,'AB10002')]);assert.deepEqual(m.map(m=>m.status),['unmatched_existing','unmatched_offer']);});
 test(`${type}: one-sided identifier is ambiguous`,()=>{assert.equal(matchObjects([object(type,'AB10001')],[object(type,null)])[0].status,'ambiguous');});
}
test('exact matches do not enable a leftover unique fallback among originally multiple objects',()=>{const a=[object(),object('Bil',null)];const m=matchObjects(a,structuredClone(a));assert.equal(m.filter(m=>m.status==='matched').length,1);assert.equal(m[1].status,'ambiguous');});
test('matching registration plus conflicting VIN fails closed',()=>{const a=object(),b=object();a.objectIdentifiers.push(id('ABCDEFGH123456789','vin'));b.objectIdentifiers.push(id('ABCDEFGH987654321','vin'));assert.equal(matchObjects([a],[b])[0].reason,'IDENTITY_CONFLICT');});
test('duplicate registrations never produce a match',()=>{const a=[object(),object()];assert.equal(matchObjects(a,[object()])[0].status,'ambiguous');});
test('conflicting identifiers inside one extracted object fail closed',()=>{const a=object();a.objectIdentifiers.push(id('AB10002'));assert.equal(matchObjects([a],[object()])[0].reason,'IDENTITY_CONFLICT');});
test('same identifier never crosses canonical insurance type',()=>{assert.ok(matchObjects([object('Bil')],[object('Tilhenger')]).every(m=>m.status!=='matched'));});
test('car aliases normalize before scoped identity matching',()=>{for(const type of ['Bilforsikring','Personbil','Motorvognforsikring'])assert.equal(matchObjects([object(type)],[object('Bil')])[0].reason,'EXACT_OBJECT_ID');});
test('registration normalization is exact, with no arbitrary punctuation or OCR repair',()=>{assert.equal(normalizeObjectIdentifier(id(' ab 10001 ')),'AB10001');assert.equal(normalizeObjectIdentifier(id('AB-10001')),null);assert.notEqual(normalizeObjectIdentifier(id('ABI0001')),'AB10001');});
test('VIN and serial normalizers retain their distinct safe rules',()=>{assert.equal(normalizeObjectIdentifier(id('abcdefgh123456789','vin')),'ABCDEFGH123456789');assert.equal(normalizeObjectIdentifier(id('ABCDEFGH I23456789','vin')),null);assert.equal(normalizeObjectIdentifier(id('AbC-123','serial')),'AbC-123');assert.notEqual(normalizeObjectIdentifier(id('AbC-123','serial')),normalizeObjectIdentifier(id('abc-123','serial')));});
test('general architecture: two synthetic non-vehicle objects use an injected exact strategy',()=>{
 const strategies={'synthetic asset':{asset_id:value=>/^ASSET-\d{3}$/.test(value)?value:null}};
 const a=['ASSET-001','ASSET-002'].map(value=>({type:'synthetic asset',objectIdentifiers:[id(value,'asset_id')]}));const b=[a[1],a[0]].map(i=>({...i,productName:'Other product'}));
 const m=matchObjects(a,b,strategies);assert.deepEqual(m.map(x=>[x.existing[0],x.offer[0]]),[[0,1],[1,0]]);assert.ok(m.every(x=>x.reason==='EXACT_OBJECT_ID'));assert.ok(matchObjects(a,b).every(x=>x.status!=='matched'));
});
for(const side of ['existing','offer'])test(`partial failure on missing ${side} side weakens evidence only for that side`,()=>{
 const m=matchObjects(side==='offer'?[object()]:[],side==='existing'?[object()]:[])[0];const context=side==='offer'?{failedOffer:1}:{failedExisting:1};assert.equal(missingEvidence(m,context),'NOT_FOUND_WITH_PARTIAL_FAILURE');assert.match(objectWarning(m,context),/ufullstendig/);assert.equal(missingEvidence(m,side==='offer'?{failedExisting:1}:{failedOffer:1}),'CONFIRMED_ABSENT_FROM_ANALYZED_SET');assert.match(objectWarning(m),/ikke nødvendigvis/);});
test('object count telemetry has only numeric counts and no raw/normalized IDs',()=>{const value=objectMatchingCounts(matchObjects(portfolio(),shuffled(portfolio())));assert.ok(Object.values(value).every(Number.isInteger));assert.doesNotMatch(JSON.stringify(value),/AB\d/);});
test('price, TFA, effective facts and presentation never mix car/trailer objects',()=>{
 const a=portfolio(),b=shuffled(a);for(const item of b)item.importantTerms=item.importantTerms.map(t=>({...t,value:t.key==='premie.ekskl_tfa'?t.value.replace('000','100'):t.value.replace('0 000','1 000')}));
 const r=compare(a,b);for(const g of r.groups){const rows=groupTerms(g,null);const price=rows.find(t=>t.key==='premie.ekskl_tfa');assert.equal(price.first,g.first[0].importantTerms[0].value);assert.equal(price.second,g.second[0].importantTerms[0].value);const shown=r.shown.filter(d=>d.objectScope===g.scopeId);assert.ok(shown.length>0);assert.ok(shown.every(d=>d.insuranceKey===g.key));}assert.equal(new Set(r.differences.filter(d=>d.kind==='price').map(d=>d.objectScope)).size,7);
});
test('semantic fallback is one bounded call over already matched scopes, with no identity in audit',async()=>{
 const a=portfolio().map(i=>({...i,importantTerms:[{name:'Synthetic alpha',value:'11'}]})),b=shuffled(a).map(i=>({...i,importantTerms:[{name:'Synthetic beta',value:'12'}]}));let calls=0,metrics;
 const plan=await runHybridMatching(a,b,async batch=>{calls++;assert.equal(batch.typeCandidates.length,0);assert.equal(batch.termScopes.length,7);assert.doesNotMatch(JSON.stringify(batch),/AB[1234]000/);return {decisions:batch.termScopes.map(s=>({kind:'term',scopeId:s.id,leftId:s.leftTerms[0].id,rightIds:[s.rightTerms[0].id],decision:'match',confidence:1,reason:'synthetic'}))};},m=>metrics=m,true);
 assert.equal(calls,1);assert.equal(plan.termMatches.length,7);assert.equal(new Set(plan.termMatches.map(t=>t.objectScope)).size,7);assert.doesNotMatch(JSON.stringify(metrics),/AB[1234]000/);
 const groups=groupInsurances(a,b,plan);for(const g of groups)assert.equal(groupTerms(g,plan).filter(t=>t.first&&t.second).length,1);
});
test('ambiguous and unmatched objects never invoke semantic object matching',async()=>{let calls=0;await runHybridMatching([object('Bil',null),object('Bil',null)],[object('Bil',null),object('Bil',null)],async()=>{calls++;return{};},undefined,true);assert.equal(calls,0);});
test('an unscoped legacy semantic decision cannot leak across cars',()=>{const a=[object(),object('Bil','AB10002')].map(i=>({...i,importantTerms:[{name:'left only',value:'1'}]})),b=a.map(i=>({...i,importantTerms:[{name:'right only',value:'2'}]}));const plan={insuranceMatches:[],assessments:[],termMatches:[{leftTypeKey:'bil',rightTypeKey:'bil',leftKey:'left only',rightKeys:['right only'],confidence:1,reason:''}]};for(const g of groupInsurances(a,b,plan))assert.ok(groupTerms(g,plan).every(t=>!t.first||!t.second));});
const telemetry=()=>createAnalysisTelemetry('00000000-0000-0000-0000-000000000000');
function rawProduct(item,index=1){return {...item,documentIndices:[index],objectIdentifiers:item.objectIdentifiers.map(id=>({...id,documentIndices:[index]})),importantTerms:item.importantTerms.map(t=>({name:t.name,value:t.value,canonicalKey:t.key==='premie.ekskl_tfa'?t.key:null,documentIndices:[index]}))};}
function agreement(items){return parseExtractionResponse({output_text:JSON.stringify({company:'If',totalAnnualPremium:null,totalAnnualPremiumScope:'partial_or_unclear',insurances:items})});}
function merged(items,side,distribution){const docs=distribution==='one'?1:distribution==='separate'?items.length:3;const batch=planExtractionBatches(Array.from({length:docs},(_,documentIndex)=>({side,documentIndex,text:'Synthetic policy only',pages:1})))[0];const result=enrichBatch(agreement(items.map((p,i)=>rawProduct(p,(i%docs)+1))),batch,telemetry());return sanitizeAnalysisDocumentForClient(mergeBatchResults([{batch,agreement:result}],side,false));}
for(const mode of ['one','separate','mixed'])test(`7 objects through extraction/enrichment/sanitizer across ${mode} PDF layout`,()=>{
 const a=merged(portfolio(),'existing',mode),b=merged(shuffled(portfolio()),'offer','mixed');const r=compare(a.insuranceData.insurances,b.insuranceData.insurances);assert.equal(r.groups.filter(g=>g.objectMatch.status==='matched').length,7);for(const g of r.groups){assert.ok(g.first[0].objectIdentifiers[0].sources[0].documentId.startsWith('pdf:existing:'));assert.ok(g.second[0].objectIdentifiers[0].sources[0].documentId.startsWith('pdf:offer:'));assert.ok(g.first[0].catalogReference);assert.ok(g.first[0].importantTerms.some(t=>t.coverageOrigin==='document'));}
});
test('batch completion order is immaterial to object pairs',()=>{
 const items=portfolio();const batches=planExtractionBatches(items.map((p,documentIndex)=>({side:'existing',documentIndex,text:'x'.repeat(45000),pages:1})));const results=batches.map(batch=>({batch,agreement:enrichBatch(agreement(batch.documents.map((d,i)=>rawProduct(items[d.documentIndex],i+1))),batch,telemetry())}));assert.ok(results.length>1);assert.deepEqual(mergeBatchResults(results,'existing',false),mergeBatchResults([...results].reverse(),'existing',false));
});
test('identity references must be within product document provenance',()=>{const batch=planExtractionBatches([0,1].map(documentIndex=>({side:'existing',documentIndex,text:'Synthetic',pages:1})))[0];const p=rawProduct(object());p.objectIdentifiers[0].documentIndices=[2];assert.throws(()=>enrichBatch(agreement([p]),batch,telemetry()),/Faktareferanse/);});
test('schema requires explicit identifiers, rejects unknown types and secrets as extra identity fields',()=>{const schema=buildExtractionRequest('synthetic',2).text.format.schema.properties.insurances.items;assert.ok(schema.required.includes('objectIdentifiers'));for(const patch of [{type:'policy_number'},{token:'not a secret'},{documentIndices:[0]}]){const p=rawProduct(object());Object.assign(p.objectIdentifiers[0],patch);assert.throws(()=>agreement([p]));}});
// Render the actual result components without adding production exports or test routes.
import ts from 'typescript';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import {objectDisplayLabel} from '../lib/object-matching.ts';
import {providerDisplayName} from '../lib/provider-presentation.ts';
import {catalogConnectionStatus} from '../lib/product-catalog.ts';
const page=fs.readFileSync('app/page.tsx','utf8');
const ast=ts.createSourceFile('page.tsx',page,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
const declarations=ast.statements.filter(node=>['ConceptFamilyCard','InsuranceRows','SourceDetails'].includes(node.name?.text)).map(n=>n.getText(ast)).join('\n');
const require=createRequire(import.meta.url);
let code=ts.transpileModule('const {objectDisplayLabel,objectWarning,catalogConnectionStatus,groupAddOnNames,providerDisplayName}=globalThis.__objectUi;\n'+declarations+'\nexport {ConceptFamilyCard,InsuranceRows};',{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext}}).outputText;
code=code.replace('"react/jsx-runtime"',JSON.stringify(pathToFileURL(require.resolve('react/jsx-runtime')).href));
globalThis.__objectUi={objectDisplayLabel,objectWarning,catalogConnectionStatus,groupAddOnNames,providerDisplayName};
const {ConceptFamilyCard,InsuranceRows}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
delete globalThis.__objectUi;
test('missing warning is visible without opening a details disclosure',()=>{const r=compare([object()],[]);const html=renderToStaticMarkup(React.createElement(ConceptFamilyCard,{difference:r.shown[0]}));assert.match(html,/ikke funnet/);assert.doesNotMatch(html,/<details/);assert.match(html,/AB10001/);});
test('ambiguous detail shows separate objects and never paired values or fabricated missing coverages',()=>{const a=[object('Bil',null,1),object('Bil',null,2)],b=[object('Bil',null,3),object('Bil',null,4)];const r=compare(a,b);const html=renderToStaticMarkup(React.createElement(InsuranceRows,{group:r.groups[0],matchingPlan:null}));assert.match(html,/Ingen objektpar er antatt/);assert.equal((html.match(/<summary>/g)||[]).length,4);assert.doesNotMatch(html,/Ikke valgt|billigere|0 kr per år/);for(const value of ['1000 kr','2000 kr','3000 kr','4000 kr'])assert.ok(html.includes(value));});
test('unmatched detail preserves source links and only its own facts',()=>{const a=object();a.importantTerms[0].sources=[{documentId:'pdf:existing:0',filename:'Synthetic document',termsNumber:'',effectiveFrom:'',page:1,section:'Test source'}];const g=compare([a],[]).groups[0];const html=renderToStaticMarkup(React.createElement(InsuranceRows,{group:g,matchingPlan:null}));assert.match(html,/Synthetic document/);assert.match(html,/10 000 km/);assert.doesNotMatch(html,/Ikke valgt/);});
test('UI scopes overview, type views, prices and details by object; responsive shared layout remains',()=>{assert.match(page,/difference\.objectScope === group\.scopeId/);assert.match(page,/key=\{group\.scopeId \|\| group\.key\}/);assert.match(page,/sm:grid-cols-2/);assert.match(page,/partial\?\.failures\?\.filter/);assert.match(page,/Vis detaljert sammenligning/);});
test('partial analysis cannot infer a unique no-ID pair from an incomplete type count',async()=>{const a=[object('Bil',null)],b=[object('Bil',null)];assert.equal(compare(a,b,{failedOffer:1}).groups[0].objectMatch.status,'ambiguous');let calls=0;await runHybridMatching(a,b,async()=>{calls++;return{};},undefined,true,{failedOffer:1});assert.equal(calls,0);});
test('explicit exact ID remains usable for surviving documents after partial failure',()=>{const a=portfolio(),b=shuffled(a).filter(p=>p.objectIdentifiers[0].value!=='AB20002');const r=compare(a,b,{failedOffer:1});assert.equal(r.groups.filter(g=>g.objectMatch.status==='matched').length,6);assert.match(r.shown.find(d=>d.kind==='object').text,/ufullstendig/);});
test('the production route opts into object-scoped semantic matching after batch merge',()=>{const route=fs.readFileSync('app/api/analyze/route.ts','utf8');assert.ok(route.indexOf('mergeBatchResults(pipeline.results')<route.indexOf('runHybridMatching('));assert.match(route,/telemetry\.semanticMatcher,\s+true,/);assert.match(route,/failedOffer: pipeline\.failures/);});
test('missing/ambiguous cards precede price lists and identity sources remain side-specific',()=>{assert.ok(page.indexOf('key={`warning:${group.scopeId}`}')<page.indexOf('key={`prices:${group.scopeId'));assert.match(page,/firstSources=\{group\.first\[0\]\.objectIdentifiers/);assert.match(page,/secondSources=\{group\.second\[0\]\.objectIdentifiers/);});
for(const kind of ['vin','serial'])test(`${kind} alone identifies the same object without registration`,()=>{const a=object();a.objectIdentifiers=[id(kind==='vin'?'ABCDEFGH123456789':'SERIAL-123',kind)];assert.equal(matchObjects([a],[structuredClone(a)])[0].reason,'EXACT_OBJECT_ID');});
test('three cars retain individual TFA and selected/not-selected/unknown coverage status',()=>{
 const a=portfolio().slice(0,3).map((p,i)=>({...p,importantTerms:[...p.importantTerms,{key:'premie.tfa',name:'TFA',value:`${100+i} kr`,coverageOrigin:'document'},...(i<2?[{key:'leiebil.dekning',name:'Leiebil',value:i===0?'Valgt':'Ikke valgt',coverageOrigin:'document'}]:[])]}));const b=[a[2],a[0],a[1]].map(p=>structuredClone(p));
 const r=compare(a,b);r.groups.forEach((g,i)=>{const rows=groupTerms(g,null);assert.equal(rows.find(t=>t.key==='premie.tfa').first,`${100+i} kr`);assert.equal(rows.find(t=>t.key==='premie.tfa').second,`${100+i} kr`);if(i<2){const coverage=rows.find(t=>t.firstCoverage?.id==='leiebil.dekning');assert.equal(coverage.firstCoverage.status,i===0?'selected':'not_selected');assert.equal(coverage.secondCoverage.status,i===0?'selected':'not_selected');}else assert.ok(rows.every(t=>t.firstCoverage?.id!=='leiebil.dekning'||t.firstCoverage.status==='unknown'));});
});
test('one accepted semantic term match cannot affect any other car scope',async()=>{const a=portfolio().slice(0,3).map(p=>({...p,importantTerms:[{name:'Alpha test',value:'1'}]})),b=[a[2],a[0],a[1]].map(p=>({...p,importantTerms:[{name:'Beta test',value:'2'}]}));const plan=await runHybridMatching(a,b,async batch=>{const s=batch.termScopes[0];return{decisions:[{kind:'term',scopeId:s.id,leftId:s.leftTerms[0].id,rightIds:[s.rightTerms[0].id],decision:'match',confidence:1,reason:'synthetic'}]};},undefined,true);const g=groupInsurances(a,b,plan);assert.equal(groupTerms(g[0],plan).filter(t=>t.first&&t.second).length,1);assert.ok(g.slice(1).every(g=>groupTerms(g,plan).every(t=>!t.first||!t.second)));});
test('unmatched object retains selected add-ons and overridden catalog base provenance',()=>{const a=object();a.addOns=[{name:'Leiebil',importantTerms:[],classification:'add_on',coverageOrigin:'document'}];a.importantTerms.push({name:'Leiebil',key:'leiebil.dekning',value:'Valgt',coverageOrigin:'document'});a.importantTerms[0].overriddenBase=[{value:'999 kr',source:{documentId:'catalog:synthetic',filename:'Synthetic original terms',termsNumber:'SYNTHETIC',effectiveFrom:'',page:2,section:'Test'}}];const html=renderToStaticMarkup(React.createElement(InsuranceRows,{group:compare([a],[]).groups[0],matchingPlan:null}));assert.match(html,/Tilleggsdekninger: Leiebil/);assert.match(html,/999 kr/);assert.match(html,/Synthetic original terms/);});
