import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PDFParse} from 'pdf-parse';
import {getPath} from 'pdf-parse/worker';
import {catalogAgreementScope} from '../lib/agreement-scope.ts';
import {productCatalog,availableAddOns,findCatalogProduct,catalogProductIdentity} from '../lib/product-catalog.ts';
import {compareCatalogProducts,materializeCatalogProduct} from '../lib/catalog-product-comparison.ts';
import {canonicalCoverage} from '../lib/coverage-status.ts';
import {product,facts,fact,sourceHash,date,enrich,manual,documentPriority} from './helpers/wave3-catalog-gate.mjs';
// Source-led RC-032/SCRC-033. SR-037 complete rider/high-limit rules remain unknown.
// B056_EXPLICIT_FIVE_CORRECTION_EXCEPTION does not extend general G1 repair budgets.
const ids=['gjensidige-snoscooter-ansvar','gjensidige-snoscooter-delkasko','gjensidige-snoscooter-kasko'];
const files=['gjensidige-snoscooter-ansvar-alminnelige-vilkar.pdf','gjensidige-Snoscooter-Delkasko-alminnelige-vilkar.pdf','gjensidige-Snoscooter-Kasko-alminnelige-vilkar.pdf','gjensidige-snoscooterforsikring.html','gjensidige-MOT05.pdf'];
const hashes=['5c7e634313b96147b294cfa18ef6edf6e3f8c8e668dd2e1ea2ecead56b34e8be','ac376b33b1d9c90d82c2a478f9336eb7b09122a96a4bc90022d3432b0f9ce27b','ba089fbe156e6f025971d3ab7ef6d78d9a6832d4bfac0af6743b1fa5494d47b4','a777ebfa6dfb20479382fa62691b1192a6867daf8044fbf6c21ee9f9989e531c','24c231e42bf532f5d94ad9edfd2a6e2f66b1de58223786a3228cc87597a01901'];
const bindings=[["04343ea6f16b4f9f", [["GAP-2568", "SF-3667", 0], ["GAP-2598", "SF-3701", 1], ["GAP-2629", "SF-3736", 2]]], ["0cb67dee0d9e323e", [["GAP-2572", "SF-3671", 0], ["GAP-2602", "SF-3705", 1], ["GAP-2633", "SF-3740", 2]]], ["30f8e097f606ae3a", [["GAP-2588", "SF-3689", 1], ["GAP-2618", "SF-3723", 2]]], ["4259b78847645953", [["GAP-2564", "SF-3663", 0], ["GAP-2594", "SF-3697", 1], ["GAP-2625", "SF-3732", 2]]], ["4ac4099aa97cebfe", [["GAP-2557", "SF-3656", 0], ["GAP-2579", "SF-3680", 1], ["GAP-2609", "SF-3714", 2]]], ["51a4e5da1f01e5d5", [["GAP-2556", "SF-3655", 0], ["GAP-2578", "SF-3679", 1], ["GAP-2608", "SF-3713", 2]]], ["67b32f613e47d713", [["GAP-2586", "SF-3687", 1], ["GAP-2616", "SF-3721", 2]]], ["ad2546bd6f7ddff3", [["GAP-2567", "SF-3666", 0], ["GAP-2597", "SF-3700", 1], ["GAP-2628", "SF-3735", 2]]], ["be21b93cabcccc3f", [["GAP-2571", "SF-3670", 0], ["GAP-2601", "SF-3704", 1], ["GAP-2632", "SF-3739", 2]]], ["cc134f7ded664c57", [["GAP-2587", "SF-3688", 1], ["GAP-2617", "SF-3722", 2]]], ["cec57012fd3b83ea", [["GAP-2558", "SF-3657", 0], ["GAP-2580", "SF-3681", 1], ["GAP-2610", "SF-3715", 2]]], ["d06ca1e67b975050", [["GAP-2573", "SF-3672", 0], ["GAP-2603", "SF-3706", 1], ["GAP-2634", "SF-3741", 2]]], ["e1c8e1869470aeca", [["GAP-2555", "SF-3654", 0], ["GAP-2577", "SF-3678", 1], ["GAP-2607", "SF-3712", 2]]], ["efaa28c0ed5f57c4", [["GAP-2620", "SF-3726", 2]]], ["fcdffe493c75df64", [["GAP-2565", "SF-3664", 0], ["GAP-2595", "SF-3698", 1], ["GAP-2626", "SF-3733", 2]]], ["ff05ca4bb2f3dbe6", [["GAP-2566", "SF-3665", 0], ["GAP-2596", "SF-3699", 1], ["GAP-2627", "SF-3734", 2]]]];

const own=(id,key)=>fact(id,'snoscooter.'+key);
const check=(f,patterns)=>{for(const p of patterns)assert.match(f.value,p);return f;};
function dimension(sig,tier){const id=ids[tier];switch(sig){
 case 'e1c8e1869470aeca':return[check(own(id,'ansvar.dekning'),[/Bilansvarsloven/,/Ordinær egenandel 0 kr/,/særregler om forhøyet egenandel/,/kundens forsikringsbevis går foran/]),check(own(id,'ansvar.grense'),[/Ubegrenset personskade/,/100 millioner kr tingskade/,/Ordinær egenandel 0 kr/])];
 case '51a4e5da1f01e5d5':return[check(own(id,'ulykke.dekning'),[/rettmessig fører og passasjerer/,/Ordinær egenandel 0 kr/]),check(own(id,'ulykke.grense'),[/Dødsfall 100 000 kr/,/medisinsk invaliditet 200 000 kr ved 100 % invaliditet/,/etter forsikringsbeviset/])];
 case '4259b78847645953':return[check(own(id,'ulykke.dekning'),[/rettmessig oppholder seg i\/på\/ved motorvognen/,/motorvognen eller tilkoplet utstyr er den direkte årsak/,/Plutselig og uforutsett ytre fysisk hendelse i forsikringstiden/,/fall som ikke er forårsaket av sykdom/,/vridning av kne eller ankel/,/skulder, arm, håndledd, lårbein, leggbein, skinnlegg, ankel eller hælbein/,/hard eller feil landing etter hopp/,/fysisk eller psykisk funksjonsnedsettelse/,/uten hensyn til yrke, inntektsevne eller fritidsinteresser/])];
 case 'fcdffe493c75df64':return[check(own(id,'ulykke.grense'),[/Dødsfall må følge av ulykkesskaden innen ett år/,/tidligere forskudd på invaliditetserstatning for samme skade trekkes fra/,/50 000 kr dersom/,/på skadetidspunktet/,/barn eller ektefelle\/samboer i live eller forsørget sine foreldre/,/Medvirkende sykdom, disposisjon eller mén/,/dødsfalls-\/invaliditetserstatningen forholdsmessig/])];
 case 'ff05ca4bb2f3dbe6':{const f=check(own(id,'ulykke.grense'),[/Delvis invaliditet erstattes forholdsmessig/,/ingen invaliditetserstatning ved død innen ett år/,/tidligere helt funksjonsudyktig kroppsdel eller organ/,/tidligere delvis funksjonsudyktighet trekkes fra/,/senest tre år etter skadedagen/,/varig tilstand på treårsdagen/,/invaliditetsgrad for samme skade er høyst 100 %/,/flere personer ved samme ulykkestilfelle/,/motorvogn-\/arbeidsmaskindekningen/,/samlet erstatning begrenset til 1 000 000 kr/,/fordeles forholdsmessig mellom de skadelidte/,/ikke en individuell invaliditetssum/]);assert.doesNotMatch(f.value,/flere passasjerer ved samme/);return[f];}
 case 'ad2546bd6f7ddff3':return[check(own(id,'ulykke.dekning'),[/Unntatt skade som følge av deltakelse i slagsmål eller forbrytelser/,/sykdom, besvimelse eller sykelig tilstand\/disposisjon/,/psykisk skade alene uten samtidig fysisk skade/,/erstatningsmessig varig medisinsk invaliditet/,/myalgier\/uspesifikke smertetilstander/,/tendinitter, tendinoser og impingement selv om ulykke kan påvises/,/tannskade ved tygging/,/invaliditetserstatning for tannskade/,/Selvmord\/forsøk er unntatt/,/likevel dekkes selvmord ved sannsynliggjort akutt sinnsforvirring med ytre årsak, ikke sinnslidelse/])];
 case '4ac4099aa97cebfe':return[check(own(id,'rettshjelp.dekning'),[/Rettshjelp i Norden/,/Forsikringssum 100 000 kr per tvist etter forsikringsbeviset/,/4 000 kr pluss 20 % av utgiftene som dekkes av forsikringen/,/Utenrettslig mekling ved Mekle.no har egenandel 0 kr/])];
 case '04343ea6f16b4f9f':return[check(own(id,'rettshjelp.dekning'),[/eier, rettmessig bruker eller fører av forsikret motorvogn/,/Tvist oppstått i forsikringstiden/,/tidligere eier etter salg og opphørt forsikring/,/tvist med selger ved neste kjøp før overtakelse\/egen forsikring/,/tidligere tilsvarende kjøretøy var forsikret i Gjensidige på kjøpstidspunktet/])];
 case 'be21b93cabcccc3f':return[check(own(id,'rettshjelp.dekning'),[/Unntatt straffesak, erstatningskrav eller tvist som har utspring i ulovlig handling fra sikredes side/,/Ikke ankegebyr, idømte sakskostnader, voldgift eller utgifter før tvist/,/yrke\/erverv/,/familie\/arv\/skifte/,/uforsikret motorvogn\/båt i Gjensidige/,/ved nytegning, ikke ved flytting fra annet selskap/,/ful[l]*t utnyttet administrativ klageadgang/,/senere søksmål kan dekkes, men ikke utgifter under forvaltningsbehandlingen/,/dokumentert manglende betalingsevne hos motpart/])];
 case '0cb67dee0d9e323e':return[check(own(id,'rettshjelp.dekning'),[/flere parter forsikret i Gjensidige på sikredes side/,/én sum per tvist/,/1–2 parter 100 000 kr/,/3–10 parter 250 000 kr/,/11–25 parter 500 000 kr/,/26–49 parter 750 000 kr/,/50 eller flere parter 1 000 000 kr/,/alltid begrenset til den økonomiske verdien av sikredes interesse/,/fremmet gruppesøksmål samlet inntil 500 000 kr/,/avvist saksanlegg inntil 20 000 kr per sikrede i Gjensidige/,/begge begrenset til antatt økonomisk interesse/,/trekkes fra ved senere innvilget rettshjelp/])];
 case 'd06ca1e67b975050':return[check(own(id,'rettshjelp.dekning'),[/4 000 kr pluss 20 % av utgiftene som dekkes av forsikringen/,/én egenandel per tvist også med flere parter på samme side/,/Mekle.no har egenandel 0 kr/,/økonomisk interesse overstiger fast egenandel/,/egen advokat under meklingen dekkes ikke/])];
 case 'cec57012fd3b83ea':return[check(own(id,'avtale.geografi'),[/Europa unntatt Kosovo, Russland og Belarus/,/rettshjelp bare i Norden/])];
 case '67b32f613e47d713':return[check(own(id,'brann.dekning'),[/Brann, lynnedslag og eksplosjon/,/ordinær egenandel 6 000 kr/,/forsikringsbevis går foran/]),check(own(id,'tyveri.dekning'),[/Tyveri og forsøk på tyveri av snøscooteren/,/ordinær egenandel 6 000 kr/])];
 case 'cc134f7ded664c57':return[check(own(id,'losore.dekning'),[/Skade på eller tyveri/,/låst oppbevaringsrom på snøscooteren/,/skade som dekkes av valgt produktnivå/]),check(own(id,'losore.grense'),[/Inntil 5 000 kr/,/låst oppbevaringsrom på snøscooteren/,/skade som dekkes av valgt produktnivå/])];
 case '30f8e097f606ae3a':{const f=check(own(id,'utstyr.grense'),[/10 000 kr for fastmontert ekstrautstyr i basisdekningen/,/Økt utstyrssum kan avtales som utvidelse/,/høyere sum krever kundens dokumenterte avtale/,/Henger er en separat mulig utvidelse/,/ikke valgt gjennom det offentlige beviseksemplet/,/fullstendige utvidelsesvilkår og en eventuell høyere sum er ikke dokumentert her/]);assert.equal(f.qualificationSource.documentId,'vehicle:'+files[4]);return[check(own(id,'utstyr.dekning'),[/skade som dekkes av valgt produktnivå/]),f];}
 case 'efaa28c0ed5f57c4':{const f=check(own(id,'kasko.dekning'),[/plutselig ytre påvirkning/,/kollisjon, utforkjøring og velt som du selv er skyld i/,/motorskade ved feilfylling av drivstoff/,/fra 4 000 til 8 000 kr/,/offentlig beviseksempel 8 000 kr er ikke kundens dokumenterte valg/]);assert.equal(f.qualificationSource.documentId,'vehicle:'+files[3]);return[f];}
 default:assert.fail(sig);
}}
for(const[sig,rows]of bindings)for(const[gap,sf,tier]of rows)test(`R-056-${sig}: ${gap}/${sf} own-source dimensions`,()=>{for(const f of dimension(sig,tier)){assert.equal(f.source.documentId,'vehicle:'+files[sig==='cc134f7ded664c57'?3:tier]);assert.ok(f.source.section);assert.ok(f.source.page>=1&&f.source.page<=8);assert.equal(f.source.effectiveFrom,'');}});

test('R-056-SOURCE: five original hashes, exact16signatures/43bindings, direct source contents',async()=>{
 for(let i=0;i<files.length;i++)sourceHash('catalog/sources/vehicle-extensions/'+files[i],hashes[i]);
 const batch=JSON.parse(readFileSync(new URL('../docs/audit/legacy-local/source-catalog-remediation-triage/triage.json',import.meta.url))).batches.find(b=>b.batch_id==='B-056');assert.deepEqual(batch.signature_ids.slice().sort(),bindings.map(b=>b[0]).sort());assert.deepEqual(batch.dependencies,[]);assert.deepEqual(batch.P2_piggyback_signatures,[]);assert.equal(bindings.flatMap(b=>b[1]).length,43);
 const expected=batch.evidence.flatMap(e=>e.finding_ids.map((g,i)=>[g,e.source_fact_ids[i],JSON.parse(e.product_identities[i]??e.product_identity)[3]]));assert.deepEqual(expected.sort(),bindings.flatMap(b=>b[1].map(([g,s,t])=>[g,s,ids[t]])).sort());
 PDFParse.setWorker(getPath());for(let tier=0;tier<3;tier++){const parser=new PDFParse({data:readFileSync(new URL('../catalog/sources/vehicle-extensions/'+files[tier],import.meta.url))});try{const pdf=await parser.getText();const text=pdf.text.replace(/\s+/g,' ');assert.match(text,/Skades flere personer ved samme ulykkestilfelle/);assert.match(text,/begrenset til kr 1 000 000/);assert.match(text,/Dersom det er flere parter forsikret i Gjensidige på sikredes side/);assert.match(text,/4 000/);assert.match(text,/20 % av utgiftene som dekkes av forsikringen/);assert.match(text,/Mekle.no benyttes, er egenandel kr 0/);assert.match(pdf.pages[0].text,/100 000/);assert.match(pdf.pages[0].text,/200 000/);}finally{await parser.destroy();}}
});

const PCs=[[1006,0,'tier'],[1007,0,'admin'],[1008,1,'tier'],[1009,1,'ATV'],[1010,1,'newvalue'],[1011,1,'admin'],[1012,2,'tier'],[1013,2,'ATV'],[1014,2,'newvalue'],[1015,2,'admin']];
for(const[pc,tier,kind]of PCs)test(`R-056-PC-${pc}: own source positive control`,()=>{const id=ids[tier],p=product(id),rows=facts(id);assert.equal(p.providerId,'gjensidige');assert.equal(p.insuranceType,'Snøscooter');assert.equal(catalogAgreementScope(p),'ordinary');assert.equal(p.version,null);
 if(kind==='tier'){for(const k of ['ansvar','ulykke','rettshjelp'])assert.ok(rows.some(f=>f.key===`snoscooter.${k}.dekning`));assert.equal(rows.some(f=>f.key==='snoscooter.brann.dekning'),tier>0);assert.equal(rows.some(f=>f.key==='snoscooter.kasko.dekning'),tier===2);}
 if(kind==='admin')assert.ok(rows.every(f=>!/^snoscooter\.(administrasjon|klage|fornyelse|personvern|premie)\./.test(f.key)));
 if(kind==='ATV'){assert.ok(rows.every(f=>!/^snoscooter\.(glass|redning)\.dekning/.test(f.key)));assert.equal(own(id,'redning.begrensning').value,'Transport til og fra verksted ved reparasjon er unntatt');}
 if(kind==='newvalue')assert.ok(rows.every(f=>!/^snoscooter\.(nyverdi|leasing|kjorelengde)\./.test(f.key)));
});

test('R-056-PROVENANCE: full ordered primary+qualification in every conversion',()=>{for(const[id,key]of [[ids[1],'utstyr.grense'],[ids[2],'utstyr.grense'],[ids[2],'kasko.dekning']]){const f=own(id,key),refs=[f.source,f.qualificationSource];for(const out of[enrich(id,[]),manual(id)]){const t=out.importantTerms.find(t=>t.key===f.key);assert.ok(t);assert.equal(t.value,f.value);for(const ref of refs)assert.ok(t.sources.some(s=>Object.entries(ref).every(([k,v])=>k==='note'?s.note.includes(v):s[k]===v)));}const t=materializeCatalogProduct(product(id)).facts.find(t=>t.key===f.key);assert.equal(t.sources.length,2);assert.deepEqual(t.sources.map(s=>{const{sourceType,...ref}=s;void sourceType;return ref;}),refs);}});

test('R-056-STATE: included base, no customer chosen extension or deductible',()=>{for(let tier=0;tier<3;tier++){const id=ids[tier],out=enrich(id,[]),m=materializeCatalogProduct(product(id));for(const k of ['ansvar','ulykke','rettshjelp',...(tier>0?['brann','tyveri','utstyr','losore']:[]),...(tier===2?['kasko']:[])]){assert.equal(canonicalCoverage(out,'Snøscooter',`snoscooter.${k}.dekning`).status,'selected');assert.equal(m.facts.find(f=>f.key===`snoscooter.${k}.dekning`).state,'included');}assert.deepEqual(out.addOnIds,[]);assert.deepEqual(availableAddOns(product(id),date),[]);assert.equal(out.annualPremium,null);assert.equal(out.deductible,null);assert.ok(facts(id).every(f=>!f.key.includes('.henger.')&&!f.key.endsWith('kasko.egenandel')));}const row=compareCatalogProducts(product(ids[0]),product(ids[2])).sections.flatMap(s=>s.rows).find(r=>r.key==='snoscooter.kasko.dekning');assert.equal(row.first.state,'unknown');assert.equal(row.second.state,'included');});

test('R-056-PRIORITY: explicit documentary sums and decline outrank catalog',()=>{for(const id of ids){documentPriority(id,'snoscooter.ulykke.grense','Kundens dokumenterte invaliditetssum 277 777 kr');for(const key of ['snoscooter.ulykke.dekning','snoscooter.rettshjelp.dekning']){documentPriority(id,key,'Ikke valgt');const out=enrich(id,[{name:fact(id,key).label,canonicalKey:key,value:'Ikke valgt'}]);assert.equal(canonicalCoverage(out,'Snøscooter',key).status,'not_selected');assert.equal(out.addOnIds.length,0);}}for(const id of ids.slice(1))documentPriority(id,'snoscooter.utstyr.grense','Kundens avtalte utstyrssum 27 777 kr');});

test('R-056-COMPARE: own values, same product, all current snow peers and both directions',()=>{const peers=productCatalog.products.filter(p=>p.insuranceType==='Snøscooter'&&catalogAgreementScope(p)==='ordinary');assert.ok(ids.every(id=>peers.some(p=>p.productId===id)));for(const id of ids)for(const peer of peers){const p=product(id),a=compareCatalogProducts(p,peer),b=compareCatalogProducts(peer,p);for(const row of a.sections.flatMap(s=>s.rows)){const reverse=b.sections.flatMap(s=>s.rows).find(r=>r.key===row.key);assert.ok(reverse);assert.deepEqual(row.first,reverse.second);assert.deepEqual(row.second,reverse.first);if(catalogProductIdentity(p)===catalogProductIdentity(peer))assert.equal(row.different,false);}for(const f of facts(id)){const row=a.sections.flatMap(s=>s.rows).find(r=>r.key===f.key);assert.ok(row);assert.ok(row.first.facts.some(t=>t.value===f.value));}}});

test('R-056-SCOPE: exact provider/type/scope/version, no foreign or car/ATV facts',()=>{for(const id of ids){const p=product(id);for(const overrides of[{insuranceType:'Campingvogn',agreementScope:'ordinary'},{insuranceType:'Snøscooter',agreementScope:'nito'}])assert.equal(findCatalogProduct(p.providerId,p.productId,p.version,overrides),null);assert.equal(findCatalogProduct('if',id,null,{insuranceType:'Snøscooter',agreementScope:'ordinary'}),null);assert.equal(findCatalogProduct(p.providerId,id,'invented',{insuranceType:'Snøscooter',agreementScope:'ordinary'}),null);assert.ok(facts(id).every(f=>f.key.startsWith('snoscooter.')));assert.doesNotMatch(own(id,'ulykke.grense').value,/250 000/);}for(const p of productCatalog.products.filter(p=>p.providerId!=='gjensidige'||p.insuranceType!=='Snøscooter'))assert.ok(facts(p.productId).every(f=>!files.slice(0,3).some(file=>f.source.documentId==='vehicle:'+file)&&f.qualificationSource?.documentId!=='vehicle:'+files[3]));});
