from continue_audit import *
A=Audit();path='catalog/sources/frende/Vilkar_kjoretoyforsikring.pdf';ipid='catalog/sources/mc-bobil/frende-bobil-ipid.pdf';web='catalog/sources/mc-bobil/frende-bobil-page.html';general='catalog/sources/frende/Generelle_vilkar-01012026.pdf'
A.root('SCRC-019','Frende Bobil lacks several independently documented Utvidet subcoverages while preserving other scoped terms correctly. Full package comparison is unfinished; do not extrapolate Bil omissions to Bobil or resolve conflicting web/IPID scopes.','Exact Bobil base+availableoptional facts read against15pvehicleterms,2pBobilIPID andlocalHTML. Utvidet lacks ladekabel/startleie despite8.3/8.6 andIPIDexplicitBobilapplicability.',['Bobil'],['frende'],'RB-17')
for pid in ['frende-bobil-ansvar','frende-bobil-delkasko','frende-bobil-kasko','frende-bobil-utvidet']:
 p=A.p[pid];lvl=['ansvar','delkasko','kasko','utvidet'].index(pid.split('-')[-1]);rows=[('Ulykke','standardstatus','Bobilproduktsideharulykkeinkludertpåalle4nivåer.',web,'HTMLtable',PRESENT,['ulykke.dekning'],'','Correct type-specific included status, distinct from optionalMC.')]
 if lvl>=1:rows += [('Brann/tyveri','egenandel','6000ellerlaverebevis;tyveri0fungerendealarm.',path,'PDF9punkt11.11',PRESENT,['brann.egenandel','tyveri.egenandel'],'','Bothdeductibles correctlyonDelkasko unlikeBil; protectpositivecontrol.'),('Løsøre','sumkonflikt','Fullterms3.9/8.8Bobil20000/Utvidet100000;HTMLallefysiskenivåer20000+10000perting;IPIDDelkaskoekskluderertyveripersonligløsøre.',path,'PDF2,5punkt3.9/8.8',REVIEW,['bobil.losore.grense'],'','Sourceconflict retained;no arbitraryper-itemcapaddition.'),('Utleie','tilleggsegenandel','Utleidbobil:ekstra6000vedbrann/tyveri/kaskoskade.',path,'PDF9punkt11.11',MISSING,[],'P1','No source-equivalent rentedvehicle deductible fact in exactBobilbase/optional.')]
 if lvl>=2:rows += [('Maskinskade','aldersordlyd','Utpolicyåret12vseldreenn12ibestemttabell;catalogpreservesboth.',path,'PDF5,6,9punkt9.1/9.3/11.11',PRESENT,['maskinskade.alder'],'','Positivecontrol: no false singleage normalization.'),('Leiebil','tidsgrenser','Helereparasjonstiden,31dinnløsning/tyveri;kontant250inntil31;ferie1500x15alternativ.',path,'PDF4punkt7',PRESENT,['leiebil.dager','leiebil.begrensning','bobil.feriegaranti.dagsbelop','bobil.feriegaranti.dager'],'','All exact durations/cashandexpensealternative represented; webcashnormalrepairtimeconflict remains separate.'),('Maskinskade','valgbarnivå','IPIDmuligtilleggKasko;HTMLtabellkunUtvidet.',ipid,'IPID1/HTMLtable',REVIEW,['maskinskade.dekning'],'','Availabilityconflict not safelyresolved bycurrentKaskoavailability. No invented customerselection.'),('Maskinskade','garantiunntak','AvvistgarantikravkanerstatteshvisellersdekketogFrendeovertarkrav.',path,'PDF6punkt9.3',COARSE,['maskinskade.begrensning'],'P1','Catalogguaranteeexclusionomits rejectedclaim carveout.'),('Maskinskade','komponentscope','Navngitteinkludertefremdrift/komfort/sikkerhetssystemerogekskludertebremser/12V/lykter/hjuloppheng;gradvisslitasjebatterikapasitet.',path,'PDF5–6punkt9.1–9.3',COARSE,['maskinskade.dekning','maskinskade.begrensning'],'P1','Generic oppregnedecomponents lacks materialexplicitcomponentboundaries.')]
 if lvl==3:rows += [('Ladekabel','Utvidetdekning','Skadet/stjåletladekabelutenegenandel/bonustap;BobilIPIDexplicit.',path,'PDF4–5punkt8.3',MISSING,['ladekabel.dekning'],'P1','No equivalentladekabelfactinUtvidetbaseoravailableaddons.'),('Leasing','startleie','Gjenværendestartleieproporsjonaltvedtotalskade/tyveri;BobilIPID/HTMLexplicit. HTML150000taknotfullterms.',path,'PDF5punkt8.6',MISSING,['leasing.startleie'],'P1','Wholecoverageabsent; safeevent/basis documented, webcapkeptunresolved.'),('Fukt','kontroll/unntak','Godkjenttestviseroppståttsiste12mnd;ikkereplekkasje/ikke rørlekkasje/rørbrudd.',path,'PDF5punkt8.7',PRESENT,['bobil.fukt.kontroll','bobil.fukt.begrensning'],'','Exactsourceconditions represented, unlike genericonlyinclusion.'),('Fastutstyr','sumkonflikt','Fullterms/IPIDUtvidet50000;HTMLUtvidet20000.',path,'PDF5punkt8.4',REVIEW,['utstyr.grense'],'','Fulltermsvalue supported but webscopeconflict held open.')]
 for sub,dim,val,art,loc,cls,keys,pr,reason in rows:
  comp='frende-bobil-maskinskade' if sub=='Maskinskade' else 'frende-bobil-leiebil' if sub=='Leiebil' else ''
  A.fact(pid,sub,dim,val,art,loc,cls,keys,pr,reason,'SCRC-019',comp,'FR-BO-'+sub+'-'+dim,extra={'review_depth':'TARGETED_SOURCE_FIRST_DIMENSIONS','remaining_full_inventory':'frende-vehicle-independent-inventory.json rules remain to compare systematically'})
 A.product_review(pid,[path,ipid,web,general],False,'Sharedterms all15p/IPID2p/materialwebbody read. Allcatalogfacts inspected; targeteddimensions recorded. Full61ruleinventorytoBobilmatch and fullreverseclosure NOTcompleted. Nextresume must finish, not startnewresearch.')
A.a['source_conflicts'].append(dict(id='SC-014',provider='frende',family='Bobil',sources=[path,ipid,web],claim='Bobil content/accessory sums; peritemlimit; leasecap; machinelevel; rentalcashduration',observed='Fullterms/IPIDUtvidetcontents100000/accessory50000vsweb20000/20000. Web10000peritem/150000startleie notfoundmainterms. IPIDmachineoptionalKaskovswebonlyUtvidet. Webcashnormalreptimevsfull31d.',status='SOURCE_VERSION_APPLICABILITY_REVIEW_REQUIRED',action='No invented caps or arbitrary scopepriority; securelydocumentedmissingUtvidetcoverage separatelyrecorded.'))
A.checkpoint('Budget checkpoint: Frende Bobil targeted gaps/positive controls recorded; finish full shared-rule matrix next','Bobil','frende','frende-bobil-ansvar','frende-bobil-maskinskade')
r=load('resume.json');r['next_exact_action']='Complete Frende Bobil source-first61rule comparison from frende-vehicle-independent-inventory.json against4exactproducts; base/optionalvalues alreadyread. Preserve targetedfindings. Then scopeFrendecamp/snow/trailerseparately; do not repeat sourceparse.';r['budget_checkpoint']={'weekly_used_percent':100,'weekly_remaining_percent':0,'ordinary_usage_allowed_at_last_check':True,'reset_credit_consumed':False,'note':'Reported weekly capacity exhausted; current bounded evidence persisted, no claim full audit completion.'};save('resume.json',r)
