from continue_audit import *
A=Audit();root='SCRC-011';M='catalog/sources/storebrand/vilkar-motorvognforsikring-motor09.pdf';MC='catalog/sources/vehicle-extensions/storebrand-mc-forsikring.html'
# Targeted follow-up of already read shared full packages. Not new blanket audit.
for pid in ['storebrand-snoscooter-delkasko','storebrand-snoscooter-kasko']:
 p=A.p[pid]
 A.fact(pid,'Bagasje','ordinær grense og hendelser','Ordinær bagasje 10000 ved brann/tyveri, også kaskoskade for Kasko. Motor09s1 eksplisitt felles typeomfang; §6.4.6 unntar snøscooter bare fra Super-utvidelsen. MC-nettsidens unntak er ikke en snøscooterkilde.',M,'s1 felles anvendelse; s3–4/7 tabeller; §6.4.6s17',MISSING,['snoscooter.bagasje.grense'],'P1','Manglende dokumentert ordinær bagasje; ikke importere MC-spesifikt webunntak til annen type.',root,inventory_id='SB-MO-015-followup',extra={'followup_of':'SB-MO-015','source_scope_resolution':'TYPE_SPECIFIC_CONFLICT_NOT_TRANSFERABLE'})
 for f in A.f:
  if f['product']==pid and f.get('source_first_inventory_id')=='SB-MO-015':f.update(classification='SOURCE_FACT_ALREADY_REPRESENTED_BY_CHILDREN',reason='Audit candidate superseded by exact-type follow-up. MC-specific webpage cannot create Scooter conflict; follow-up fact contains final missing classification.')
conf=next(x for x in A.a['source_conflicts'] if x['id']=='SC-006')
conf.update(family='MC/Bobil/Bil',observed='MC only: shared motor09s1/s7 ordinary luggage10000 versus MCweb explicit no luggage/goods. Bobil Kasko: generic §1.2 new-value cell versus §10.3 registered person/varebil qualification; vehicle registration class not established by product name. Bil Delkasko: §10.3 general settlement right versus §1.2 empty Delkasko cell. Scooter is excluded from this conflict because no applicable Scooter source contradicts generic coverage; §6.4.6 only excludes Super extension.',action='Local package review complete. Official dated product-level clarification needed for MCbagage, Bobilregistration applicability and BilDelkasko settlement. No guessed catalog fill; no online research.')
ids=['sb-bil-delkasko','storebrand-snoscooter-delkasko','storebrand-snoscooter-kasko','storebrand-mc-delkasko','storebrand-mc-kasko','storebrand-bobil-delkasko','storebrand-bobil-kasko']
for pid in ids:
 old=next(x for x in A.a['manual_review']['products'] if x['product_id']==pid)
 note='Targeted closure after original complete66-rule source inventory/full33-page pass: '+('Scooter ordinary bagage confirmed by explicit all-type scope; MCweb excluded as inapplicable. No unresolved ordinary bagage question remains.' if 'snoscooter' in pid else 'All locally resolvable material dimensions checked. SC006 is finalized SOURCE_RESEARCH_REQUIRED, not an unfinished reading task. Source ambiguity is retained; no affirmative new-value/MCbagage fact manufactured.')
 if pid=='storebrand-bobil-delkasko':note='Original inventory complete. Bobilordinary new-value question belongs to Kasko cell/registered-class rule; no unqualified Delkasko entitlement asserted. General settlement/insured-sum rules already checked. Source-scoped research gate retained.'
 A.product_review(pid,old['source_paths'],True,old['reasoning']+' FOLLOW-UP: '+note)
for pid in ['storebrand-campingvogn-super','storebrand-tilhenger-brann-og-tyveri','storebrand-tilhenger-kasko']:
 old=next(x for x in A.a['manual_review']['products'] if x['product_id']==pid)
 A.product_review(pid,old['source_paths'],True,old['reasoning']+' FOLLOW-UP CLOSURE: 38-rule inventory and every53catalog claim were already checked. Remaining SC007 source conflicts have no additional applicable local evidence. Closed available-local audit with SOURCE_RESEARCH_REQUIRED, not a claim the conflicting coverages are known. Trailer redning/fire-deductible reverse claims remain conflict status; no arbitrary precedence.')
for f in A.f:
 if f['product'] in ids+['storebrand-campingvogn-super','storebrand-tilhenger-brann-og-tyveri','storebrand-tilhenger-kasko'] and f['classification']=='SOURCE_AMBIGUOUS':f['local_review_disposition']='LOCAL_REVIEW_EXHAUSTED_SOURCE_RESEARCH_REQUIRED';f['finding_validation_scope']='Ambiguity/conflict verified, affirmative coverage not proven'
A.a['source_research_queue'].append(dict(queue_id='storebrand-motor-camp-final-questions',product=ids+['storebrand-campingvogn-super','storebrand-tilhenger-brann-og-tyveri','storebrand-tilhenger-kasko'],reason='SC006/007: exact applicability and conflicting sums/deductibles cannot be reconciled from frozen local package.',external_source_needed_if_unresolved='Dated official MC ordinary luggage clarification; motor09 Delkasko new-value/registered Bobil applicability; camp02 Super contents and trailer roadside/deductible application.',downloaded=False))
A.checkpoint('Storebrand shared motor/camp partial queue closed locally; Scooter luggage missing proven; six conflict dimensions remain research-gated','Innbo','storebrand','sb-innbo-standard')
