from continue_audit import *
A=Audit()
for pid in ['sb-innbo-standard','sb-innbo-super']:
 p=A.p[pid];old=next(x for x in A.a['manual_review']['products'] if x['product_id']==pid)
 for f in A.f:
  if f['product']==pid and f.get('source_first_inventory_id')=='SB-IN-043':
   f.update(classification='SOURCE_AMBIGUOUS',local_review_disposition='LOCAL_REVIEW_EXHAUSTED_PRODUCT_CONTEXT_REQUIRED',reason='innbo09 cover and B4.9 explicitly distinguish home from holiday-home contents. Source rule itself is known (40000/80000), but current generic Innbo identity has no declared occupancy/product-context discriminator. Do not automatically import the holiday-home replacement rule into home coverage or claim absent coverage. Exact product applicability requires scoped clarification, no missing/falseunknown counted.')
 A.product_review(pid,old['source_paths'],True,old['reasoning']+' FOLLOW-UP: B1/B2/B4.9 and cover rechecked. Conditional holiday-home replacement is known source truth but exact catalog product context is unresolved; retained SOURCE_AMBIGUOUS with separate applicability research requirement. All other81rules/reverseclaims already completed. Local review closure is not assertion of holiday-home applicability.')
H='catalog/sources/storebrand/hus/Vilkar-hus-og-hytte-HUS10.pdf'
for pid in ['storebrand-hus-standard','storebrand-hus-super']:
 old=next(x for x in A.a['manual_review']['products'] if x['product_id']==pid)
 A.fact(pid,'Badeinnretning','aldersfradrag omfang','Tabellen omfatter vannbasseng/annen badeinnretning som boblebad/badestamp, samt innvendig badeinnretning tilknyttet elektrisk anlegg. Kataloglabel begrenser hele konseptet til elektrisk tilknyttet; sats2/10%/80% er korrekt.',H,'B.6.4.11 fysisk s29','CATALOG_FACT_SEMANTICALLY_MISMAPPED',['hus.aldersfradrag.badeinnretning'],'P2','Labelens omfang er snevrere enn kildeobjektene; ikke endre prosentsatsene. Dette er avklart katalogsemantikk, ikke uløst kildekonflikt.','SCRC-014',inventory_id='SB-HU-047-followup')
 for c in A.support:
  if c['product_identity']==A.p[pid]['identity'] and c['key']=='hus.aldersfradrag.badeinnretning':c.update(full_claim_validated=False,support_status='LABEL_SCOPE_MISMATCH',manual_reverse_evidence='HUS10B6.4.11physical29: electrical qualification applies to indoor bath devices, not all pool/bath objects; numeric schedule supported.')
 A.product_review(pid,old['source_paths'],True,old['reasoning']+' FOLLOW-UP: remaining exact source branches exhausted. Badeinnretning resolved as label-scope mismatch. SC008 retained on declared contradictory clauses/versions; no unsupported reconciliation. Available-local 83-rule material inventory/reverse review closed, externally gated questions remain.')
ad=next(x for x in A.a['addon_coverage'] if x['addon_id']=='storebrand-hus-utleie');ad.update(status='COMPLETE',semantic_audit_status='COMPLETE',fully_audited=True,notes=ad['notes']+' FOLLOW-UP: optional availability and all6claims/8rules reviewed; HUS10F vsUTLEI03 conflicting applicability retained as final research gate, not unresolved reading. No selected status inferred. Exact max3/transfer terms require clarification before remediation.')
for pid in ['storebrand-reise-standard','storebrand-reise-super']:
 old=next(x for x in A.a['manual_review']['products'] if x['product_id']==pid)
 A.product_review(pid,old['source_paths'],True,old['reasoning']+' FOLLOW-UP: local review exhausted; SC009 is the final source-conflict disposition. No web freshness claim or arbitrary IPID exception. Overnight positive control already completed separately; source-truth answer remains no general overnight requirement, distinct from arrangement-specific conditions.')
for f in A.f:
 if f['product'] in ['storebrand-hus-standard','storebrand-hus-super','storebrand-reise-standard','storebrand-reise-super'] and f['classification']==REVIEW:f.update(classification='SOURCE_CONFLICT_REVIEW_REQUIRED',local_review_disposition='LOCAL_REVIEW_EXHAUSTED_SOURCE_RESEARCH_REQUIRED')
for qid,pids,why,need in [('storebrand-innbo-holiday-context',['sb-innbo-standard','sb-innbo-super'],'Source differentiates home/holiday-home, exact catalog applicability context unspecified.','Official exact home/holiday product identity clarification; not new terms values.'),('storebrand-hus-final-questions',['storebrand-hus-standard','storebrand-hus-super'],'SC008 exact source clauses/versions contradict; all local pages read.','Dated HUS10 B2/B3/B6.2/B6.3 and UTLEI03/HUS10F applicability clarification, alarm deductible and IPID level confirmation.'),('storebrand-reise-purchase-transfer',['storebrand-reise-standard','storebrand-reise-super'],'SC009 transfer exception in IPID versus categorical full-term restriction.','Dated applicability of direct-transfer exception for journey already started.')]:
 A.a['source_research_queue'].append(dict(queue_id=qid,product=pids,reason=why,external_source_needed_if_unresolved=need,downloaded=False))
A.checkpoint('Storebrand remaining property/travel reviews closed locally with explicit research dispositions; no ambiguous coverages invented','Bil','frende','frende-ansvar')
