from continue_audit import *
A=Audit();V='catalog/sources/frende/Vilkar_kjoretoyforsikring.pdf';G='catalog/sources/frende/Generelle_vilkar-01012026.pdf'
# Targeted unresolved claims rechecked in local source cache, reuse all independent inventories.
for pid in ['frende-bil-ansvar','frende-bil-delkasko','frende-bil-kasko','frende-bil-utvidet']:
 old=next(x for x in A.a['manual_review']['products'] if x['product_id']==pid)
 A.product_review(pid,old['source_paths'],True,old['reasoning']+' FOLLOW-UP: §3–5,§9.1/9.3/11.11 exact local wording rechecked. Age cutoff disagreement is genuine internal source conflict; no cutoff invented. Accident purchase status remains bevis-conditioned and IPID heading does not prove default inclusion. Source-location mismatch for leased machine exclusion recorded. Local61-rule and reverse review closed, SC012 explicitly research-gated.')
for pid in ['frende-mc-ansvar','frende-mc-delkasko','frende-mc-kasko']:
 old=next(x for x in A.a['manual_review']['products'] if x['product_id']==pid)
 A.product_review(pid,old['source_paths'],True,old['reasoning']+' FOLLOW-UP: §3.5 names riding gear but does not create all-risk coverage; selected physical cause under4/5/6 still governs. MCcatalog conditional equipment presence on physical levels is conservative; no cover on Ansvar asserted. Glass clause5.1 general versus exact MCsummary applicability remains final SOURCE_RESEARCH_REQUIRED (no proof from omission). All other exact dimensions and optional accident checked. Local review complete.')
 # No unsupported negative from absence on Ansvar or outside Kasko.
 for f in A.f:
  if f['product']==pid and f['classification']==REVIEW:
   f['local_review_disposition']='TYPE_APPLICABILITY_RETAINED_NO_INCLUSION_INFERRED' if f['semantic_subject'] in ['Kjøreutstyr','Maskinskade'] else 'LOCAL_REVIEW_EXHAUSTED_SOURCE_RESEARCH_REQUIRED'
for pid in ['frende-bobil-ansvar','frende-bobil-delkasko','frende-bobil-kasko','frende-bobil-utvidet']:
 old=next(x for x in A.a['manual_review']['products'] if x['product_id']==pid)
 # These general clauses were already fully read and catalog inspected; finish previously explicit unfinished matrix.
 for s,d,v,l in [('Generelle unntak','krig/terror','ABC/radioaktiv/biologisk/krigsbegrensninger;6ukers uventet krigsutbrudd og selskapets100millioner terror/epidemiårstak. Ikke kundens egen forsikringssum.','Generelle s2§1'),('Datakriminalitet','fysisk følgeskade','Generelt cyberunntak har forbehold for fysisk skade som dekkes av den enkelte produktforsikring.','Generelle s4§9'),('Eierskifte','ettervern','14 dager til ny kjøper dersom ikke egen forsikring.','Generelle s3§5')]:
  A.fact(pid,s,d,v,G,l,MISSING,[],'P2','Fullt lest fellesvilkår; materiell avgrensning ikke representert i eksakt Bobilprodukt eller tilgjengelige tillegg. Ikke flytt regler mellom typer uten anvendelig delt original.','SCRC-019',inventory_id='FR-BO-GENERAL-'+d)
 A.fact(pid,'Generelt','administrasjon','Oppsigelse, svik, renter, skjønn og regress uten egne nye ordinære dekningsrader.',G,'Generelle s2–4','NOT_COMPARISON_RELEVANT',reason='Administrasjon gjenbrukt fra samme kontrollerte fire siders original.',inventory_id='FR-BO-GENERAL-ADMIN')
 A.product_review(pid,old['source_paths'],True,old['reasoning']+' FOLLOW-UP: general4p matrix now explicit. All61-rule and base/optional reverse checks complete. SC014 exact dated source disagreements retained as final research requirements; does not certify web values or product-level availability in conflict. Shared §9 age wording treated as SC012-type conflict, no arbitrary resolution.')
for aid in ['frende-maskinskade','frende-bobil-maskinskade','frende-bobil-leiebil']:
 ad=next(x for x in A.a['addon_coverage'] if x['addon_id']==aid);ad.update(status='COMPLETE',semantic_audit_status='COMPLETE',fully_audited=True,notes=ad['notes']+' FOLLOW-UP: all locally available availability/limits/conditions/provenance checked. Completion denotes available-local audit closure with external applicability gate, not certainty of conflicting age/level/cash words. Customer selected status not inferred.')
# Pregnancy numerical boundary: source is explicit, catalog internally inconsistent.
pid='frende-reiseforsikring';T='catalog/sources/frende/reise/Vilkar-reiseforsikring-01032026.pdf'
A.fact(pid,'Graviditet','presis avgrensning','Kilden unntar fødsel/svangerskapskomplikasjoner etter36.svangerskapsuke; katalogens første setning sier føruke36, andre setning etter36. Ingen kilde støtter at grensen skal flyttes til starten av uke36.',T,'§6.3s7 og§3.3s3','CATALOG_FACT_SEMANTICALLY_MISMAPPED',['reise.medisinsk.graviditet'],'P2','Bevar kildens presise ordlyd; to ulike terskler i samme katalogfact kan gi falsk innsnevring. Ingen medisinsk tolkning av dager er nødvendig eller gjort.','SCRC-010',inventory_id='FR-RE-PREGNANCY-FOLLOWUP')
for f in A.f:
 if f['product']==pid and f['semantic_dimension']=='uke36formulering':f.update(classification='SOURCE_FACT_ALREADY_REPRESENTED_BY_CHILDREN',reason='Audit candidate closed by FR-RE-PREGNANCY-FOLLOWUP. Final boundary mismatch counted only in that occurrence.')
for c in A.support:
 if c['product_identity']==A.p[pid]['identity'] and c['key']=='reise.medisinsk.graviditet':c.update(full_claim_validated=False,support_status='LABEL_BOUNDARY_MISMATCH',manual_reverse_evidence='Fullterms6.3p7/3.3p3 after36 versus first catalog sentence before36; preserve exact source formulation without inferred day.')
old=next(x for x in A.a['manual_review']['products'] if x['product_id']==pid);A.product_review(pid,old['source_paths'],True,old['reasoning']+' FOLLOW-UP: last reverse claim closed as numeric-boundary mismatch, not unexplained REVIEW_REQUIRED. All55 claims accounted,56-rule inventory complete.')
# Remaining complete source packages with research-limited applicability questions.
for pid,issue in [('frende-innbo-standard','Naturskade Norway claim relies on referenced law unavailable as applicable local legal text; no neighboring Hus rule imported. §9 introduction covers owner/tenant but9.1 narrows to building owner; local full wording does not safely resolve broad legal scope.'),('frende-hus-standard','Wrong internal §3.1→4.1/1–10 reference and alternative fire§4.2 versus Standard§5 remain exact-source applicability uncertainty.'),('frende-hus-utvidet','Same source internal references; Standard physical clauses must not be inferred from alternative fire package absent clarification.'),('frende-bat-brann-og-tyveri','Lower-level contents conflict in SC010; source§8 motor-only is separate certificate product, outside active full-boat levels.'),('frende-bat-kasko','Transport§5.1.4 proven; generic external-event§5.1.5 is not sufficient to guarantee every named launch/recovery event. Preserve conditional wording; broad label applicability requires clarification.'),('frende-bat-utvidet','Source80%/30000 versus HTML60%/10000 remain SC010; secure guaranteeage and50000 contents already inventoried separately. Combined transport-label scope also retained.'),('frende-katt-veterin-r','2026 fullterms6.1 burglary-theft versus2025IPID disappearance remains SC011. No current disappearance inclusion certified; research needs exact version applicability.')]:
 old=next(x for x in A.a['manual_review']['products'] if x['product_id']==pid)
 A.product_review(pid,old['source_paths'],True,old['reasoning']+' FOLLOW-UP LOCAL CLOSURE: '+issue+' Complete independent material inventory/catalog pass/reverse claims already performed. Remaining uncertainty disposition is SOURCE_RESEARCH_REQUIRED; no claim source conflicts resolved or affirmative coverage invented.')
 for f in A.f:
  if f['product']==pid and f['classification'] in [REVIEW,'SOURCE_AMBIGUOUS']:f['local_review_disposition']='LOCAL_REVIEW_EXHAUSTED_SOURCE_RESEARCH_REQUIRED'
ad=next(x for x in A.a['addon_coverage'] if x['addon_id']=='frende-katt-tap');ad.update(status='COMPLETE',semantic_audit_status='COMPLETE',fully_audited=True,notes=ad['notes']+' All local optional dimensions reviewed; SC011 retained as final research/version gate. No disappearance assertion for current2026contract.')
for fam,question in [('Bil','SC012 machine-policyyear versus birthday cutoff, accident default/package choice and exact newvalue under/notolder boundary. Need exact dated Frende contract-product clarification.'),('MC','SC013 glass applicability and physical event scope for riding gear. Need exact MC clauses/endorsement, not inference from missing IPID bullet.'),('Bobil','SC014 machinelevel/age, accessory/contents caps, peritem cap, leasing cap, rental cash duration. Need dated channel/full-term reconciliation.'),('Hus','SC004 internal source references: smallbuilding Standard scope and applicability of fire§4.2 exclusions.'),('Båt','SC010 exact level contents,80/60%newvalue,30000/10000storage; transport/launch/recovery source wording.'),('Katt','SC011 disappearance in2025IPID versus2026fullterms; current exact optional Tap applicability.')]:
 A.a['source_research_queue'].append(dict(queue_id='frende-'+fam.lower()+'-final-local-closure',product=fam,reason=question,external_source_needed_if_unresolved='Official dated exact-product clarification of named clauses. No source research authorized in this audit.',downloaded=False))
A.checkpoint('All204product reviews closed against available local sources; retained source research gates, pregnancy boundary and Bobilgeneral matrix completed','ADDON_REVIEW_QUEUE','gjensidige','gjensidige-bobil-kasko','gjensidige-bobil-utleie')
