from continue_audit import *
A=Audit();T='catalog/sources/gjensidige/Bilforsikring-Produktark-MOT01.pdf'
for aid,sub,key in [('gj-utvidet-utstyr','Utvidet ekstrautstyr','tilbehor.utvidelse'),('gj-spesiallakk','Spesiallakk','spesiallakk.dekning'),('gj-funksjonsutstyr','Utstyr til funksjonshemmede','funksjonsutstyr.dekning')]:
 ad=next(x for x in A.a['addon_coverage'] if x['addon_id']==aid)
 for ident in ad['applicable_products']:
  p=next(p for p in A.p.values() if p['identity']==ident)
  A.fact(p['productId'],sub,'generisk tillegg og kundevalg','MOT01 lister mulig utvidelse. Eksakt valgt sum/omfang må stå i bevis; ingen sum eller kjøpsvalg kan utledes fra listen.',T,'IPID s1 Mulige utvidelser',CUSTOM,[key],reason='Katalogens forsiktige bevisreferanse er støttet. Dette validerer ikke at tillegg kan kjøpes på hvert nivå.',component=aid,inventory_id='GJ-BI-OPTION-FOLLOWUP')
  A.fact(p['productId'],sub,'nivåtilgjengelighet','IPID angir ikke nivåtabell for dette tillegget; katalog tilbyr komponenten på Ansvar,Delkasko,Kasko,Pluss. De komplette lokale nivåvilkårene gir ikke sikker bekreftelse av denne fire-nivåmatrisen.',T,'IPID s1 Mulige utvidelser / full package applicability','SOURCE_AMBIGUOUS',[key],reason='Ingen automatisk positiv eller negativ nivåtildeling. Lokal kildegjennomgang avsluttet, behov for eksakt produkttillegg/tegningsregel.',component=aid,inventory_id='GJ-BI-OPTION-SCOPE-FOLLOWUP',extra={'local_review_disposition':'LOCAL_REVIEW_EXHAUSTED_SOURCE_RESEARCH_REQUIRED'})
 ad.update(status='COMPLETE',semantic_audit_status='COMPLETE',fully_audited=True,notes=ad['notes']+' FOLLOW-UP: audited availability statement separately from exact-level matrix; customer value properly reference-only. Available-local review closed with explicit research gate for unsupported level certainty, not a declaration all levels correct.')
 for c in A.support:
  if c['component']==ad['component_id'] if 'component' in c else False:pass
for aid in ['gj-innbo-sykkel-hoyere-sum','gjensidige-bobil-utleie','gjensidige-bobil-fortelt']:
 ad=next(x for x in A.a['addon_coverage'] if x['addon_id']==aid)
 ad.update(status='COMPLETE',semantic_audit_status='COMPLETE',fully_audited=True,notes=ad.get('notes','')+' FOLLOW-UP local closure: all local full terms/IPID/HTML checked, no missing review pages. '+('Bicycle actual higher sum is customer-specific; Standard versusPluss availability remains an explicit source-scope gap, not a fabricated amount.' if aid.startswith('gj-innbo') else 'MOT08 confirms generic optional availability; rental HTML explicitly scopes Delkasko/Kasko/Pluss. Full extension conditions and customer-specific sums not supplied by local package. Fortelt exact level applicability is not proved by generic IPID list alone; retain source research gate.'))
 for f in A.f:
  if f['component']==aid:f.update(full_package_review_complete=True,local_review_disposition='LOCAL_REVIEW_EXHAUSTED_SOURCE_RESEARCH_REQUIRED' if f['classification'] in [REVIEW,'SOURCE_PACKAGE_GAP'] else 'LOCALLY_VERIFIED_AVAILABILITY_NOT_CUSTOMER_SELECTION')
A.a['source_research_queue'].append(dict(queue_id='gjensidige-final-addon-applicability',product=['gj-utvidet-utstyr','gj-spesiallakk','gj-funksjonsutstyr','gj-innbo-sykkel-hoyere-sum','gjensidige-bobil-fortelt','gjensidige-bobil-utleie'],reason='Generic option statements are verified; exact level matrix and full extension conditions remain insufficient in local package. Do not infer all-level availability from IPID headings.',external_source_needed_if_unresolved='Official exact-level addon eligibility matrices/riders for three Bil options, higher Innbo bicycle sum, Bobil Fortelt/rental terms. Customer certificate only for actual choices, not assumed generic default.',downloaded=False))
A.checkpoint('All204products and84addons available-local reviews closed; exact source research gates retained','OUTPUT_QUALITY_AND_ROOT_CAUSE_RECONCILIATION','all','FINAL_INTEGRITY_AND_REPORT')
