from continue_audit import save
R=[]
def r(s,d,v,l,scope='both'):R.append(dict(id=f'EP10-{len(R)+1:02d}',subject=s,dimension=d,value=v,location=l,scope=scope))
r('Produkt','version','P10 01.01.2025+P15 Pluss; historisk og ikke aktiv nytegning. N75bedrift ikkeordinary.','s2/27–30')
r('Personer','eligibility','Norgeadresse/folkeregister/norsktrygd/retur;familiepartner sammeadresse;barn21;barne/oldebarn medreisende utenannenreiseforsikring.','§1.2 s4')
r('Reise','scope','77d,heleverden,start/sluttNorge,fritid/tjeneste,IKKE kravovernatting;utvidelseavtalesføravreise.','§1.3 s5')
r('Reise','exclusions','Ikkehjem/arbeid/studie/barnehage (arbeidsskapunntak),ekspedisjoner,krigsrisikovedinnreise;streik/konkurs/lønnstap.','§1.3 s5')
r('Evakuering','limits','Nærmestsikkert/hjemNorge ogoppholdmax45d;tapferie1600/døgn/sikret max45d,Pluss2500;UDkrig/naturutenNorge/epidemiutenNorge.','§1.3 s5;P15.14s27')
r('Reisegods','sum','Standard40000enkelt/familie120000nårminst2reiser;Plussingen totalsum.','§2.3s6;P15.4s27')
r('Reisegods','sublimits','PassStandard20000/person/Plussubegrenset;cash6000/10000perhendelse;arbeidsgiver10000/skade tjeneste;sykkel10000/40000;skap5000;øvrigting15000/40000perting.','§2.3s6;P15.1–5s27')
r('Reisegods','scope','Privatting,leidansvarskontrakt,innsjekketmedsammetransportunntatttransportørseparasjon;ikkeverktøy/varer/data/flytte/motor/båt/seilbrett/mat/dyr,luftsport/droneibruk.','§2.3s6')
r('Reisegods','triggers','Tyveri/ran/innbrudd/natur/trafikk/brann/vann/båtuhell/innsjekket;ikkemistet/finner.','§2.4s7')
r('Reisegods','exclusions','Normalbruk/kosmetisk/transportøransvar/væske/gjenstandsknus/indirektetap/familiehærverk/underslag/kjæledyr.','§2.4s7')
r('Reisegods','settlement','Alderbruk anvendelighetsfradrag,økonomisktap;kontant/reparasjon/tilsvarende;egenandel500førreduksjon,høyesteavtaleperhendelse;Pluss0.','§2.5–6s8;P15.19s28')
r('Reisegods','security','Tilsyn/lås/safe;verdifulleibilhanskeromseparatbagasje/skiboks;ikkebil/camping/båt/telt00–06;ingeninnsjekkingverdifulle;sykkellås.','§2.7s9')
r('Medisinsk','scope','Akutt/ulykke/kroniskakutt/død;sykehus/lege/fysio/medisin/transport/hotellkost;3.50/kmprivat;telefon5000;kriseterapi ran/ulykke forhåndgodkjent.','§3.3–4s10–11')
r('Tann','limits','Ulykke10000/person,akutt/spising1000/skade iutlandet.','§3.4s10')
r('Medisinsk','exclusions','Kjentogbehandlingsbehov/sannsynlig,konsultasjonsreise/planlagt,privateNorden,fortsattutlandfrivillig;graviditetmenakuttalvorligfør36dekket;fødsel36.','§3.4s10')
r('Aktiviteter','restrictions','Kamp,luftsport,strikk/base,superG/utfor,motor,dypdykk40/fridykk10,ekspedisjon;høydesyke>4000;rus/slagsmål/feilbehandling/redningsaksjon. Fjell/offpiste/kite/downhillkanavtales/Plussinkl.','§3.4s11;8.4s22–23;P15.16s28')
r('Hjemtransport','scope','Legeforordnet/godkjent nødv ekstrareise/ledsager;egen/familiesyk/død,boligforretningkontorskade,nødvendigblodtransfusjoniNorge;egen død.','§3.4s11')
r('Reiseavbrudd','limits','Sykehus/legebeordretsengeleie/hjemreise;1600/døgn/sikret (families3matrise3200);Plussubegrensetmenreellkost;egenbil3.50/kmsamlet;utflukt10000/Plussubegrenset.','§3.4s11–12;P15.13s27')
r('Reiseavbrudd','conditions','Bare reiser≤77d,innhentingalternativikkeplussavbrudd;legeførstebesøk ogSOSved>5d;ettfamiliemedlemmedsammeforsikring.','§3.4s11–12')
r('Eneste ledsager','sum','100000/skade ekstrakost utoverkompensasjon;hele reisen sammen,ikkefellesadresse/medforsikret;forhåndsgodkjent.','§3.4s12')
r('Tilkalling','scope','2familiemedlem/nærstående;godkjenningøkonomifly/opphold;ikkeskade/hospitalhjemfylket/snarlighjemtransport.','§3.4s13')
r('Medisinsk','duration','60d fortløpendebehandlingførstelege;SOSvedsykehuseller>5000;ingenegenandel.','§3.5–7s13')
r('Ansvar','limits','UtenforNorden privat15mill;reisekostrettsmøte;500egenandelStandard/0Pluss.','§4.2–5s14–15;P15.19s28')
r('Ansvar','exclusions','Næring/kontrakt/punitiv/familie/reiseledsager/leide-lånte/forurensning/fast eiendom/motorbåtluft,medsmallmachine10km/t/rullestol15/kano/paragliderunntak.','§4.3s14–15')
r('Rettshjelp','limits','UtenforNorden100000/tvist,250000min3parter,økonomiskinteresse;500egenandel/Pluss0.','§5.2–5s16–17;P15.19s28')
r('Rettshjelp','exclusions','Grunnlagpåreisen;yrke/eiendom/familie/straff/motorkjøretøysmv/mellomsameiere/salær/preexisting/avslagrettshjelp.','§5.3s16–17')
r('Forsinket fremmøte','limits','≥1.5timerettertransportstart, vær/teknisk/ulykke/nødlanding;innhentingubegrenset;losji6000person20000familieellersamme dag,Plussubegrensetlosji;EU261fradrag.','§6.3s18;P15.9s27')
r('Forsinket fremmøte sykdom','limits','Legeordre20000/person50000familie,Plussubegrenset.','§6.3s18;P15.10s27')
r('Forsinket avgang','limits','Offentlig betalttransportvær/teknisk;6000/person20000familielosji beggeproduktnivå;bekreftetårsaken.','§6.3s18')
r('Forsinket bagasje','limits','4timer6000/personklær/toalett/sportleie påutreise;21d før tapt;Plusstjeneste10000 menss3matrise6000.','§6.3s18;P15.8s27')
r('Avbestilling','limits','50000person100000familie;Plussubegrenset;ikke-refunderbarogførstebetalingetterforsikringsstart.','§7.3s19;P15.11s27')
r('Avbestilling','triggers','Sykdomegen/nærfamilie/enesteledsager,boligkontorskade,fremskyndetutsattbehandlingmelding<14d,rettsinnkalling<14d,ledsagerkort,krigepideminatur<72tfør.','§7.4s19')
r('Avbestilling','exclusions','Kjent/arrangementavlyst/påregnelig/medisinskråd/rus;graviditetskomplikasjonfør36unntak;skattavgiftbonus;seminarkursbilletterikke.','§7.3s19')
r('Ulykke','scope','24tutenreise;risikoyrkeunntak,begrensetkontorarbeidmedmenoffshore/luft/sjøtransportunntak.','§8.2s21')
r('Ulykke','sums','Standardensliginvalid400000,død300000;familievoksen300000/300000,barn500000/50000. Plussenslig700000/300000,familievoksen700000/500000,barn700000/150000;75år100000reduksjon,fra80kundinvaliditet.','§8.3s21;P15.15s28')
r('Ulykke','exclusions','Sykeligtilstand/degenerativ/psykisk/forgiftning/behandling/infeksjon,insekterunntaklokal/blodforgiftning;yrke/risikosport/proinntekt>1G,militærutland,motivetforsett.','§8.4s21–23')
r('Ulykke','settlement','Dødinnen1år;invaliditet3år/barnunder16 5år,legesymptom3år;ingenkosmetisk/tanninvaliditet;max100%;min1årførsluttoppgjør.','§8.5s24')
r('Ulykke behandling','limits','2år/5%invalidsum;kriseterapi6mnd;barnpermanenttannsenere menoppgjør2år;egenandel1000,barntannunder21 500;Plussfritak.','§8.5/7/9s25;P15.19s28')
r('Uhell','sum','Pluss6000/FORSIKRINGSÅR,kjenttidsfestetytrehendelse;ikkearbeidsgiver.','P15.6s27','plus')
r('Forsinket fly','sum','>8tut/hjemværellerteknikk,1000/påbegyntdøgn,max5000person10000hendelse.','P15.7s27','plus')
r('Avbestilling','group','Gruppe≤6enblirsyk,ogbarnevakt/avløsernøkkelperson.','P15.12s27','plus')
r('Leiebil','scope','Kunferiefritid,kaskoCDW+TP,kontraktegenandel;ikkeoffroad/motor,leasing/bilpool/privat/flytting/reparasjonsbil.','P15.17s28','plus')
r('Veterinær','sum','Akuttsyk/ulykkepåreiseutenNorden2500/skade.','P15.18s28','plus')
r('Bedrift','scope','N75egenbevisavtale,arbeidsgiver50000,remplassering14d/retur2mnd;ikkeordinaryarv.','N75s29–30','outside')
save('eika-p10-independent-inventory.json',dict(source_first=True,rules=R,review='All30p, P10PIPID, historicalFAQ77d and claims settlementwebsite read; P15overridesexplicit, N75excluded fromordinary. Not evidence active currentFremtind.'))
print(len(R))
