from continue_audit import *
R=[]
def r(s,d,v,l,animal='both',component='base',doc='vet'):
 R.append(dict(id=f'FPT-{len(R)+1:02d}',subject=s,dimension=d,value=v,location=l,animal=animal,component=component,doc=doc))
r('Veterinær','scope','Navngittdyr/Nordenbosted/verden;hendelseogutgiftiforsikringstid;førstesymptomsomsykdomstid.','§1–5s1')
r('Karenstid','days','20dsykdom,60dallergi/hud/øre;ulykkedag1;gjelderutvidelsesum/dekning,ikkeflyttingtilsvarende;førsykdomikke.','§5s1')
r('Sum','basis','Kundebevisvalgt sum perforsikringsår;webvalg30/40/50/75k.','§6s1;webSykdom')
r('Veterinær','coverage','Nødvendigsykdom/ulykke,reseptmedisin,komplikasjonvaksine/kastrering;innenårssum.','§7s1')
r('Allergi','lifetime','Hundatopi/allergiutredning/behandling/medisin15000livstid.','§7s1','dog')
r('Artrose','lifetime','Hundartrose/forkalkning/spondylose15000livstid,ogsåToppingenoverride.','§7s1','dog')
r('MR/CT','annual','Samlet15000perår base.','§7s1')
r('Avliving','sum','Avliving/kremeringsamlet2000kunveddekketdiagnose.','§7s1')
r('Hund tann','negative','Baseikke melketann/bitt/tannstilling/tannstein/stomatitt/gingivitt/periodontitt/karies/resorpsjon/emalje/cyste/rotspissunntattfraktur;ulykkestennerIPID.','§7s1','dog')
r('Katt tann','coverage','Fraktur/karies/emalje/resorpsjon;resorpsjon15000livstid;melketann/cyste/bittmedisinskfør4mnd;ikkestein/stomatitt/gingivitt/periodontitt/rotspissutenfraktur.','§7s1','cat')
r('Medfødte ledd','condition','HD/AD/OCD/patella/shortulna/CalveLeggPerthesuavbruttveterinærfør4mnd;hundHDADforeldreHD A/BogAD0.', '§7s2')
r('Hund keisersnitt','condition','En ganglivstid,20mndalder,1åruavbruttveterinær,NKKetiskparring;raseunntak.','§7s2','dog')
r('Katt keisersnitt','condition','En ganglivstid,1åruavbruttveterinær,ikke2ellerflere tidligerekeisersnitt.','§7s2','cat')
r('Veterinær','exclusions','Kosmetikk/psyke/forplantning/hormonbehandling kastreringvedlistetsykdom;følgeravunntattskade/tilstand.','§7s1')
r('Kostnader','excluded','Ikke rehab/kiro/alternativ i base;transport/hjemmebesøk/gebyrattest/fôrtilskudd/forebygging.','§7s2')
r('Hund raser','exclusions','BOAS/trachea/gane/nesebor/svelg BostonMopsEngFrBulldogChihuahuaPomeranianPekingeseShihTzumixer;øyeøre/hudSharpeiChow;entropionMopsBoxerBulldog;Cavalier syringo/Chiari;keisersnitt7raserogmixer.','§7s2','dog')
r('Katt raser','exclusions','Perser/ExoticBOASogmixer;Scottishfoldleddskjelettogmixer.','§7s2','cat')
r('Egenandel','structure','135d fraførsteutgift;hund1300/2000/3500/katt1300/2000/4000 +20%resten;webkatt3500eravvik.','§8s2')
r('Oppgjør','requirements','IDkontroll/korrektalder/rase,utenlandskengelsk-maskinskrevetjournal;direkteoppgjørNorge;velferdsavliving/obduksjonbestiltbetales.','§8s2')
r('Varighet','termination','Veterinærhelelivetweb;slutterveddød/eierskifte/oppsigelsefull.','§8s2;webvarighet')
r('Topp allergi','limit_override','Tilvalgtårssum;15000livstidbaseoverskrives.','Topp§dekker s3','dog','topp')
r('Topp MR/CT','limit_override','Tilvalgtårssum;15000årsbaseoverskrives.','Topp§dekker s3','dog','topp')
r('Topp tann','condition','Karies/emalje/resorpsjon;medisinskmelketann/cyste/bittfør4mnd;bitttannstillingattest7uker–4mndutenmerknad.','Topp§dekker s3','dog','topp')
r('Topp rehab','duration','Fysio/rehab/kiro innen6mnd etterbestiltavbehandlendeveterinær;innenårssum/valgtegenandel.','Topp§dekker s3','dog','topp')
r('Liv','trigger','Valgfritt;død/avlivingvedulykkeellerdekketsykdom;forsvinning/tyveri;ikkeunntattveterinærtilstand;kundenssum.','Død/tap s1','both','life','life')
r('Liv','settlement','Tilsvarendedyrpåskadedagopptilbevis;dødogeierskifte/oppsigelseavslutter.','Død/tap s1','both','life','life')
r('Hund liv','age_table','20%/årfradragvedhovedforfalletter5/7/9åravhengigrase;gruppert8/10/12år opphør;gulv1500. Heletypeliste i source måbevares,ikkestandardalle7/10.','Død/tap s1tabeller','dog','life','life')
r('Katt liv','age','20%/årfradragvedhovedforfalletter7år,min1500;opphørhovedforfalletter12år.','Død/tap s1','cat','life','life')
r('Liv','disappearance','Politiogannonsering;tidligst3mnd ettermeldtossogpoliti.','Død/tap s1','both','life','life')
r('Bruksverdi','trigger','Valgfritt;varigveterinærdokumenterttapetterbehandlinghvile,praktisk/offisiellbruk siste12mnd;dekketvetårsak.','Bruksverdi s1','dog','use','use')
r('Bruksverdi','threshold','Jakt/gjeter/tjeneste trent/regelmessig minst50%tap;avl100%,min1kullsiste2år/NKK,normalfødselhunn;ikkeutstilling/andreformål.','Bruksverdi s1','dog','use','use')
r('Bruksverdi','termination','Hovedforfall etter8år,ellersdød/eierskifte/oppsigelse;bevisvalgt sum.','Bruksverdi s1','dog','use','use')
r('Kjøp','eligibility','5uker–7år;7–inntil10kunflytting;IDmerkingpåkrevd;hundingennyattestkravweb.','SB1Greitåvite','both','base','web')
r('FirstVet','service','Fri onlineveterinærvedsykdom/skade,vetproduktIPID/web;ingenantattlivkundeservicestatus.','SB1Online;IPID','both','base','web')
r('Liv katt','eligibility','Kunrasekatt.','SB1matrix/IPID','cat','life','web')
r('Valpekull','optional','Valgtillegg6000/valp itilleggtispe,2kulllivstid,fødsel→leveringmax3mnd,kunvet;førfødsel/avlshund/NKKparring. Egetfullvilkårikkei322lokale.','SB1Valpeforsikring FAQ/IPID','dog','puppy','web')
r('Produktnivå','structure','HundTopp er valgfriutvidelseavbasePDF/IPID,webtolevelnavn;livkan kjøpesseparat;ikkeautomatiskvalgt.','SB1/VetTopp/IPID','dog','base','web')
r('Katt kildekonflikt','deductible','Fullvet4000 vsSB1web3500somtredjevalg,ikkevelgarbitrært.','§8s2/SB1Egenandel','cat','base','web')
r('Liv kildekonflikt','boundary','Webmellometteralderogdetåretfyller;fullhovedforfalletterfylt. Riktigdateboundarymåavklares,ikkenormaliserebort.','SB1varighet/fullDød-tap','both','life','web')
r('Medlemsfordel','outside_scope','LOfavør5%prisrabatt ognavnet gjelderikkeordinary;innboansvar ogreisefaqikkevetprodukt.','SB1LOfavør/FAQ','both','base','web')
save('fremtind-pet-independent-inventory.json',dict(source_first=True,rules=R,review='Dogvet3p includesTopp, catvet2p, life1each,use1,IPID2each,fullmaterialSB1dogandcatweb. Sharedgeneralalreadyread; customer choices not defaulted.'))
print(len(R))
