from continue_audit import save
R=[]
def r(s,d,v,l,scope='all',source='Vilkar_Topp_Hus.pdf'):
 R.append(dict(id=f'FHU-{len(R)+1:02d}',subject=s,dimension=d,value=v,location=l,scope=scope,source=source))
r('Bygning','eligibility','Permanent bolig; ikke næring eller minst tre eierseksjoner; fraflyttet/ubebodd bare brann og natur.','IPID s1',source='IPID_Hus.pdf')
r('Sikrede','ownership','Eier/panthaver; 14 dagers eierskifte inntil ny forsikring; dødsbo.','Standard §1 s2')
r('Geografi','place','Bevissted; natur og vind svakere enn storm i Norge.','Standard §2 s2')
r('Bygning','scope','Fast utstyr og midlertidig lagrede materialer i Norge; småbygg inntil10m2 kun brann/natur; kunst bare Topp.','Standard §3.1 s3;Topp §1 s1')
r('Utvendige ledninger','scope','Til offentlig ledning/brønn; ikke overvann/infiltrasjon/drensfelt/brønnhull.','Standard §3.2 s3')
r('Hage','limits','5 dekar; basseng/boblebad Standard200000/Topp500000; egen tre/flytebrygge100000 inkl montering, ikke fellesbrygge/landbruk.','Standard §3.3 s3;Topp §1 s1')
r('Offentlig påbud','limits','Nødvendig oppgradering ved dekket skade; førsterisiko20%av sum. Ingen uavhengig eksisterende påbud, arealtap, antikvarisk metode eller forebygging.','Standard §3.4 s3;§5.5.1 s6')
r('Riving/rydding','limits','Nødvendig kostnad, førsterisiko20%av sum; normal gjenoppbyggingsperiode prisstigning og flytting/lagring.','Standard §3.4 s3;§5.5.3 s7')
r('Ubeboelig/rentetap','period','Normal reparasjonstid; umøblert markedsleie, ikke korttidsleie; sparte utgifter/renter trekkes. Fritidsbolig25k/ubegrenset er ikke Hus-grense.','Standard §3.4 s3;§5.5.2 s6;Topp §1 s1')
r('Brann','scope','Brann/lyn/spenning/eksplosjon/sprenging/nedsoting; ikke svi/gnist uten brann, heksesot, material-/konstruksjons-/monteringsfeil eller spenning i bygg.','Standard §4.1 s3')
r('Vann','scope','Rør/tilkoblet utstyr/akvarium; grunn/avløp må stå over gulv; tilstøtende rom ved utett våtrom. Ikke søl/bruk/kondens, våtrommet selv, takrenne/takdrensnedløp, sopp/råte.','Standard §4.2 s4')
r('Rørbrudd','limits','Innvendig rør/radiator/bereder, utvendig tank/kum; tining ute50k inkl følgekost; ikke takrenne/nedløp/drensledning.','Standard §4.3 s4')
r('Annen skade','scope','Tilfeldig plutselig fysisk skade, med tidligere unntak; ikke fundament/tele/setning/design/slitasje, dyr/insekter, kosmetisk, punktert glass, hageklima, bassengfrost/snø, brygge/snøstopper ved snø, renterhærverk.','Standard §4.4 s4')
r('Natur','extension','Lovbestemt natur; antenner/markiser/flytebrygge egen utvidelse, ikke bryggemooring/forskyvning alene.','Standard §4.5 s4;Natur s12–13')
r('Oppgjør','method','Selskap velger reparasjon/nytt/kontant; egeninnsats250/time; udokumentert arbeid75% eksMVA.','Standard §5.1 s5')
r('Gjenoppbygging','period','Innen5år, kjøp er ikke gjenoppbygging; max gjenoppføringspris minus rest.','Standard §5.2.1 s5')
r('Fullverdi','conditions','Samme sted/formål og eier/ektefelle/arving innen5år ingen aldersfradrag; annet sted/formål fradrag verdiøkning>40%; ingen gjenoppbygging/annen eier markedsverditap og all verdiøkning.','Standard §5.2.2 s5')
r('Boligkjøp etter totalskade','limits','Kjøp i Norge samme formål innen2år; min gjenoppføring eksMVA og markedsverdi+40%; innenfor sum1mill tilpasning innen2år etterkjøp; ikke offentligpåbud/prisstigning; rentetap stopper overtakelse.','Standard §5.2.2.4 s5')
r('Førsterisiko','limit','Avtalt maksimal sum; verdiøkning>40%trekkes. Vesentlig ubrukt bygg markedsverditap og alle forbedringer trekkes.','Standard §5.2.3 s5;§5.2.4–5 s6')
r('Aldersfradrag','table','12 rader max80%: nonplast ute-/undergrunnsrør20år5%; nonplast/glassfibertank20år5%; sjø/jordvarmeslange20år5%; basseng5år10%; jordvarme7år10%; luftvarme5år10%; bereder/vannpumpe5år5%; varmekabel10år10%; hvitevarer5år10%; solcelle20år5%; smarthus5år10%.','Standard §5.3 s6')
r('Aldersfradrag','trigger','Kun elektrisk/lyn/annet plutselig/rørbrudd; påbegynt år etter friperiode; eldste del, alle reparasjonskostnader.','Standard §5.3 s6')
r('Hageoppgjør','limits','Reparasjonskost; uten reparasjon min markedsfall/kost; unge butikkplanter; ingen forebygging.','Standard §5.4 s6')
r('Egenandel','general','Bevis, etter avkorting; høyeste ved samme hendelse.','Standard §6 s7')
r('Egenandel','prevention','6000reduksjon FGalarmsentral/NEK405-02 siste5år/vannhovedventil/sikkerhetsutstyr; overvannsforebyggingstiltak0.','Standard §6.1 s7')
r('Egenandel','special','Glass/sanitær2000; integrerte hvitevarer2000; gjentatt vann sammeårsak24mnd+20000; ansvar4000; rettshjelp4000+20%; natur8000.','Standard §6.2–7 s7–8')
r('Ansvar','sum','Rettslig person/ting/følgetap, bevisstyrt sum; DNB produktside5mill per skade; ingen generell sum fastslått i fullvilkår.','Ansvar §3 s8–9;DNB sammenligning')
r('Ansvar','exclusions','Kontrakt, familie/felles/leide-lånte, næring, gradvis forurensning, forsett; byggherre eget forsikret bygg unntak fra grave/sprengningsnegativ.','Ansvar §3 s8–9')
r('Rettshjelp','limits','100k/tvist økonomiskinteresse; kan250k minst3parter; FinKN15k, forlik/jordskifte25k; ikke rettsoppnevnt sakkyndig20%;4000+20%.','Rettshjelp §4–5 s10–12')
r('Rettshjelp','eligibility','Personlig eier/fester avtalt eiendom; ikke preexisting tvist; også solgt eiendom og ny bolig/tomt før innflytting når gammel forsikret på kjøpstid.','Rettshjelp §1–3 s10')
r('Rettshjelp','exclusions','Yrke/familie/straff/andre eiendommer, ikke direkte innkreving ubestridt; husleietvist unntak fra namsmyndighetnegativ.','Rettshjelp §4.2 s10–11')
r('Naturskade','limits','Brannforsikret Norge og tomt5dekar; ikke alminnelig frost/tele/nedbør/snø; byggenekt ved nyfare gir tomtemarkedsverdi5dekar og totalskadeerstatning.','Natur §1–3 s12–13')
r('Utett tak/vegg','scope','Følgeskade tak≤50år eller overterrenginntrengning; ikke kondens, selve tak/vegg eller mangelutbedring.','Topp §2.1 s1','top')
r('Dyr/skadedyr','scope','Fullverdibygg; fysisk skade, redusert isolasjon, lukt; bekjempelse ved påvist aktivitet med valgt firma; ikke førperiode/kosmetisk/ren rengjøring/udokumentert isolasjonstap, kjæledyr/insekter/bakterier.','Topp §2.2 s1','top')
r('Håndverker våtrom','conditions','Autorisert/godkjent; feil material/design/montasje; utenfor reklamasjon eller innenfor ved konkurs; rettidig reklamasjon; oppdaget innen10år; ingen mangel selv/egenarbeid/kjentfeil/udokumentertforskrift.','Topp §2.3 s1','top')
r('Håndverker øvrig','conditions','Fundament/setning/tele/material/design/montasje; samme10år/reklamasjon/godkjenning; ikke kondens/drenering/råte/bakterier eller tak/vegg selv ved lekkasje.','Topp §2.4 s2','top')
r('Totalskadegaranti','trigger','Skade>75%gjenoppføringspris uten riving/rydding/prisstigning i nevner; rest rives/fjernes innen2år.','Topp §3.1 s2','top')
r('Skadedyr','deductible','Bekjempelse2000, øvrig bevis/Standard.','Topp §4 s2','top')
r('Råte/sopp','optional','Valgfri bevisavtale, bare fullverdibygg; treødeleggende sopp/råte.','§1 s1','rot','Vilkar_Sopp_og_Rate_valgbar.pdf')
r('Råte/sopp','exclusions','Ikke blåved/sverte/mugg/jordslag, kosmetisk, over taksperre, dør/vindu/lekter/utvendig tre eller laftetyttervegg; bare utvikling i forsikringstid; ikke tilgang via ikkeerstatningsmessig konstruksjon.','§1.1 s1','rot','Vilkar_Sopp_og_Rate_valgbar.pdf')
r('Insekter','scope','Fysisk skade/isolasjon/lukt; skadegjørende insektbekjempelse; ikke kosmetisk eller før/etterperiode; firma/metode bestemmes.','§1.2 s1','rot','Vilkar_Sopp_og_Rate_valgbar.pdf')
r('Råte/insekter','deductible','Krypkjeller/jordgulv +15000; insektbekjempelse2000; øvrig bevis.','§2 s1','rot','Vilkar_Sopp_og_Rate_valgbar.pdf')
r('Utleie','optional','Lovlig utleie og varslet/avtalt bevis; kan omfatte hel/delbolig.','IPID s1;§1 s1','rental','Vilkar_Utleie_valgbar.pdf')
r('Utleie','rent','6mnd ubetalt leie, kun én gang per leietaker; avtaltleie og eventuell rettslig innkrevingskostnad.','§1.1/2.1 s1','rental','Vilkar_Utleie_valgbar.pdf')
r('Utleie','eviction','20000 nødvendige juridiske utkastelseskost ved opphørt/bruttavtale.','§1.2 s1','rental','Vilkar_Utleie_valgbar.pdf')
r('Utleie','vandalism','500000/skade, forsettlig leietaker/gjest, bolig/tilhørendeinnbo/uteareal; ikke slitasje/kosmetisk/vedlikehold/kjæledyr.','§1.3 s1','rental','Vilkar_Utleie_valgbar.pdf')
r('Utleie','settlement','Innbo min1/3verdifall før fradrag, bruktkjøp/arv/gave markedsverdi; bygg egne regler.','§2.3–4 s1','rental','Vilkar_Utleie_valgbar.pdf')
r('Utleie','deductible','3mnd leie (min depositum/garanti) trekkes først; korttidsutleie under1mnd egenandel30000.','§3 s1','rental','Vilkar_Utleie_valgbar.pdf')
r('Egenandel','choice','SpareBank1 og DNB fra6000til25000; kundens faktiskvalg ikke antatt.','Egenandeler/FAQ',source='SpareBank1-husforsikring.html')
r('Medlemsfordel','scope','LOfavør Topp til standardpris og1000lavere egenandel; skal ikke inn i ordinary.','LOfavør-boks',source='SpareBank1-husforsikring.html')
r('Kanaloversikt','transition','Eika nytegning fra13.10.2025; eksisterende vilkår individuelt i nettbank.','Vilkår ingress',source='Eika-vilkarsoversikt.html')
r('Glass','thermal','Begge nivå dekker termisk brudd; punktert vindu er ikke brudddekning.','FAQ termisk/punktert vindu',source='SpareBank1-husforsikring.html')
r('Sikkerhet','conditions','Steng hovedkran/tøm ved ubebodd>7d, varme/frost/snomåking, godkjent elektroVVS og vedlikehold; ikke generisk inkludert uten plikter.','Sikkerhetsforskrift FAQ',source='SpareBank1-husforsikring.html')
save('fremtind-hus-independent-inventory.json',dict(source_first=True,rules=R,review='13p full terms, 2p IPID, both1paddons, SB1/DNB complete material website contents and Eika archive. LOfavør kept outside ordinary.'))
print(len(R))
