from continue_audit import save
R=[]
def r(s,d,v,l):R.append(dict(id=f'FRE-{len(R)+1:02d}',subject=s,dimension=d,value=v,location=l))
r('Personkrets','eligibility','Nordisk folkeregistrert adresse og norsk trygd/EØS; familie ektefelle/samboer egne/foster/vergebarn/husstandsbarn; barn til21; barne/oldebarn alene med sikrede.','§1 s1')
r('Utstasjonert','special','Særavtale diplomater/militære utenforNorden; medisinsk arbeidsordning, hjemkallelse ved nærfamilie; ikke ordinær global oppholdsdekning.','§1 s1')
r('Geografi','scope','Hele verden fra/til fastadresse Norden; ansvar/rettshjelp bare utenforNorden.','§2–3 s1')
r('Reisetid','choice','Fullvilkår antalldøgn avtaltbevis; IPID V104standard70d; ingen valgalternativ90/120/180 i lokal fulltekst/IPID.','§3 s1;IPID s2')
r('Geografi','exclusions','Ikke fastarbeid/studie/barnehage i Norden tid (unntakmobil); militær; over6000m/ekspedisjoner/UDfrarådet hele reisen.','§2 s1')
r('Avtale','timing','Må kjøpes førreise; avbestilling underavtale føravreise; ulykke24t stopper75år.','§3 s1–2')
r('Generelle unntak','risk','Arbeidskonflikt/konkurs/lønnstap/rus/slagsmålforbrytelse/selvmord/lete-redning.','§4 s2')
r('Reisegods','scope','Personlig låntleid skriftlig førreise, arbeidsgivers ansvar, innsjekket når reiser med; ingen samlet generell sum angitt.','§7.1 s3')
r('Reisegods','sublimits','Kontanter10000/person;pass15000/skade inklreise/opphold foranskaffelse ikke ny hjemreise; arbeidsgiver50000.','§7.1 s3')
r('Reisegods','valuables','40000samlet/skade for navngitt gruppe smykker/elektronikk/musikk/sport/våpen/kjøreutstyr og sykkel uten bosted/studie/arbeidskommune; øvrigenkeltgjenstand40000perting/skade.','§7.1 s3')
r('Reisegods','excluded_objects','Ikke motorvogn/utstyr i bruk/sammenbil,el-sykkel/småel,båt unntattkano/kajakk/seilbrett,luftsport,flytte/varer/verktøy/dokumentdata/kort/programvare/drone/inventar/sykkelibruk/lokal/matfirma-mobil.','§7.1 s3')
r('Reisegods','triggers','Tyveri ikke mistetbeholdtfinner;ran/hærverk/natur/brann/vann/trafikk/båtkollisjon/innsjekket tap.','§7.2 s3')
r('Reisegods','exclusions','Ikke emballasje/væskelekkasje/kosmetikk/egenmangel/slitasje/ukjent/mistet/sporti bruk/elsykkel/arbeidsgivermobil.','§7.2 s3–4')
r('Uhell','limits','Annen plutselig fysisk2500/skade; samme unntak, ikke mobil/data/nett/lesebrett/fjernstyrt/drone.','§7.3 s4')
r('Mobil','scope','Plutselig ytre kjentårsak/tid, avtaleverksted, også fastarbeid/studie; ikke hjemme/kosmetisk/egenfeil/fukt/innhold/firma;2000egenandel.','§7.4/7.5.6 s4–5')
r('Reisegodsoppgjør','methods','Fradrag alder/bruk/forbedring, bruktkjøp/gave/arv markedspris; selskap velger reparasjon/nytt/kontant og leverandør; smykker/edelmetall nypris, samleobjekt bruktverdi.','§7.5 s4–5')
r('Aldersfradrag','table','Mobil1år20%, elektronikk1år10%,sykkel3år20%,briller1år10%,max80perpåbegyntår; toalettsaker50%.','§7.5.1 s4')
r('Forsinket bagasje','limits','5000/person klær/toalett og leiebarnevogn/sport;4timer men ingenventetidjobbreise;PIR og kvittering; ikke hjemreise.','§8.1 s5')
r('Forsinket reise','triggers','Vær/ekstraordinærtrafikk/teknisk/ulykke privatbergingsbehov/nødlanding; merkostikke EU261 ansvar,måreisen gjennomføres;mat/drikkeunntatt.','§8.2 s5–6')
r('Forsinket fremmøte','limits','For sent tilbetalt kollektivtransport;innhentingubegrenset,overnatting6000/person/skade.','§8.2 s5')
r('Forsinket avgang','limits','Forhåndsbetalttransport ikkeavgang;6000/person/skade;innhenting nårtransportørikkeinnen24t;klær/toalett500/person vedovernatting ogbagutilgjengelig.','§8.2 s5–6')
r('Forsinket ankomst','limits','Merenn8t rutefly/charter/turoperatør;500/person/påbegyntdøgn max5000/person;turisttjenester5000/skade.','§8.2 s6')
r('Leiebil','scope','Fritid/tjeneste personbil fra godkjentfirma medkasko; egenandel dokumentert i kontrakt; ikkeleasing/langtids/bilpool/privat/flytting/reparasjonsbil/feilfylling/andretyper.','§9 s6')
r('Medisinsk','scope','Akutt uventet/kroniskakutt/ulykke; sykehus/lege/medisin/utstyr/transport/opphold ved utsatthjemreise; ingen hovedbeløpsgrense angitt.','§10.1 s6–7')
r('Medisinsk','exclusions','Ikke etterhjemkomst/kjent før/planned/uke36/frivilligabort/privateklinikkNorden/fortsattutland nårhjemtransportforsvarlig/tolk/mat/nærfamiliesykpåreisemålmerkost.','§10.1 s6–7')
r('Psykolog','sum','Førstehjelp etterhjemkomst ran/ulykke/natur/terror25000/skade.','§10.1 s7')
r('Tann','limits','Ulykke5000/skade,spising/plutseligtannsykdom1000/skade; nødvendigpåreisen.','§10.1 s7')
r('Innhenting etter sykdom','sum','150000/skade etterlegeinstruks;kontakt førnye billetter.','§10.1 s7')
r('Tilkalling','limits','2nærmeste Norden vedakutt fysiskalvorlig eller2blir;2veddød;forhåndsgodkjenning;telefon5000/skade.','§10.1 s7')
r('Eneste medreisende','sum','Hotell/innhenting/hjemreise/forsinkelse/avbrutt;50000/skade.','§10.2 s7')
r('Hjemtransport','triggers','Akutt alvorlig/kroniskforverring/ulykke/egenellerfamiliedød/boligforretningsskade; nødvendigbehandlingikke tilgjengelig, avtalt, pasientreisekmsats/losji; ikke nyhjemreisevedfortsattdestinasjon.','§10.3 s7–8')
r('Avbrutt reise','limits','Sykehus/hjemtransport2000/person/døgn begrensetreisekostnad; alternativretur;enestemedreisende/medforsikret må være reiseforsikret hososs;ikkevisum/eiendom/poeng.','§10.4 s8')
r('Sengeleie','limits','Legeordinert minst3d fraførstebesøk;750/person/dag maks10d/reise;ettfamiliemedlem/enesteledsager.','§10.5 s8')
r('Ubenyttet arrangement','sum','5000/skade vedlegeforbud/akuttsyk/ulykke; forhåndsbetaltutflukt/turisttjeneste ikke transport/overnattingunderveis.','§10.6 s8–9')
r('Medisinsk','duration','30d fraførstelegebehandling med unntak når hjemreiseuforsvarlig; forhånd SOSsykehus/hjemreise/tilkall/kost>5000.','§10.7 s9')
r('Ulykke','sums','Under21invaliditet700k/død150k;21–70 500k/begge;70–75 100k/begge;behandling5%avinvalidsum.','§11.1 s9')
r('Ulykke','sports','Ekstrem/organisertluft/paraski/dykk>40/kamp/motorløp/ekspedisjon/risikoyrke/organisertkonkurranse/idrettinntekt>1G; aktivitetsunntak gjelderikkeunder16.','§11.1 s9')
r('Ulykke','other_exclusions','Sykdom/disposisjon,psykiskutenfysisk,behandlingmedisinkomplikasjon,arr<15%,flått/insekt/virus,kriminalitet/slagsmål,rustilstander;visseunntakikkeunder16.','§11.1 s9–10')
r('Ulykke behandling','limits','Norden2år,ikkeutgifterunder1000;barnutsatttannoppgjørsenest23år;ikkeprivatutengodkjenning/hjelpemidler/spisetann.','§11.2 s10')
r('Ulykke invaliditet','conditions','Varig fastslåttinnen3år;proposjonalgradmax100%;førsykdomsandel trekkes.','§11.4 s10–11')
r('Avbestilling','triggers','Egen/enesteledsager/nærfamilie/samreisendegruppe≤8/nøkkelpersonsykdom;boligforretningsskade;UD/lokalevak72tfør;vitne/meddommer;innenlandregjeringsråd.','§12.1 s11')
r('Avbestilling','expenses','Egenandelavforhåndsbetaltreise/opphold/turisttjeneste ikkeandre;dyrepensjonat2500;ingenhovedsumangitt.','§12.1 s11')
r('Avbestilling','exclusions','Forutsigbar/planlagtbehandling/forlengesykehus,graviditet/frivilligabort/fødsel36;visum/skatter/timeshare/returnertepoeng/delreise/alleredeUDfrarådet/deltakerarrangement.','§12.1 s11')
r('Evakuering','scope','Natur/pandemiutenNorge,krig/terror tidligerefredelig;myndighetensråd,tilnærmestesikredestinasjon;andresrefusjonunntatt.','§13 s12')
r('Evakuering','lost_holiday','2000/person/døgn max150000/forsikringsår ut frareisekost.','§13 s12')
r('Ansvar','scope','UtenforNorden,bevisstyrtsum;person/ting/følgetap;kontrakt/familie/lånt/næring/fast eiendom/motorkjøretøynegativ med14fot10hkbåt/drone750kSDR-unntak.','Ansvar s12–14')
r('Rettshjelp','limits','UtenforNorden;100k/økonomiskinteresse,250kmin3parter;FinKN15kforlik25ksakkyndig20%;bevisegenandel+20%;preexisting/yrke/familie/straff/objektunntak.','Rettshjelp s14–17')
save('fremtind-reise-independent-inventory.json',dict(source_first=True,rules=R,review='17p current full terms and V104 IPID; responsibility/legal shared exacttext with House except layout; EikaFAQ77d belongs P10 not inferredcurrent. Ownchannelwebsitecopies absent.'))
print(len(R))
