from continue_audit import save
R=[]
def r(s,d,v,l,scope='all',type='motor'):
 R.append(dict(id=f'FLV-{len(R)+1:02d}',subject=s,dimension=d,value=v,location=l,scope=scope,type=type))
r('Personkrets','scope','Eier/rettmessigfører/panthaveravtalt;14d eierskifte inntilnyavtale.','PMO357§1s1')
r('Geografi','scope','SnøscooterNorden,ansvarEØS;MC EuropaTyrkiaIsrael;rettshjelpNorden.','PMO357§2s1;IPID')
r('Avregistrering','transition','Minikasko/Kasko blirlagring;bareansvar avsluttes.','PMO357§5s1')
r('Sesongpris','table','Snø Jan–Des14/14/23/23/10/1/1/1/1/1/4/7%;MC2/2/4/8/12/14/14/14/14/9/5/2%;ikkeproporsjonalårsrefusjon,ikkebilbytte.','PMO004.411s1snø/s2MC')
r('Ansvar','limits','Ubegrensetperson/100millting/hendelse,norskregelgunstigEØS,kontraktsansvarunntatt;traktor10mill gjelderikkeMCsnø.','FMO001§1–2s1–2snø/s2–3MC')
r('Ulykke','sums','Førerpassasjer i/på/utenforkjøretøy, måkjøretøyutløst;død100kvedpartner/barnunder20ellers50k;invaliditetvoksen200kbarnunder20 1mill.','FMO002§1–2s2snø/s3MC')
r('Ulykke','limits','Ikke sykdom/besvimelse/forgiftning/rus(siste2ikkeunder16);dødinnen1år,invalid1årvurderingendelig3år,proposjonal.','FMO002§1/5s2–3snø/s3–4MC')
r('Rettshjelp','limits','Norden,eier/bruker,ogsolgtobjekt;100k/tvistinteressetak,250kmin3parter,FinKN15kforlik25ksakkyndig20%;egenandelbevis+20%.','FF003s8–10snø/s9–11MC')
r('Rettshjelp','exclusions','Ikkegrunnlagføravtale/yrke/familie/straff/annetobjekt/salærtvist;ingen vilkårligfast egenandel.','FF003s8–10snø/s9–11MC')
r('Minikasko','object','Serieutførelse og ekstradekk;fasttillegg10000,brannsluk/førstehjelp,kjøreutstyr;ingenoppgittegenkjøreutstyrsum i PDF.','PMO357.110§1s3–4snø/s4–5MC','mini')
r('Brann','scope','Brann/lyn/eksplosjon.','Mini§2.1s4snø/s5MC','mini')
r('Tyveri','scope','Tyveri/brukstyveri/forsøk/hærverk;ikkehusstand/ansattsjåfør;dekk/felguskaddunntatt;stjålen nøkkelprogrammering/omkodingnårforebyggende.','Mini§2.2/3.5s4/6snø/s5/7MC','mini')
r('Glass','applicability','Bareveteran/mopedbil/traktor;ikkegenereltMC/snøscooter.','Mini§2.3s4snø/s5MC','mini')
r('Redning kjøretøy','scope','Transportetterdekketskade,tilligger inkl,nærmesteverksted;driftsstoppSNØekskl,terrengstoppikke,MCdriftsstopp/hjem/tomdrivstoff;egenandel500.','Mini§2.4.2s5/4.3s7snø/s6/8MC','mini')
r('Feilfylling','limits','Tøm/rens10000,nystartmotorfeildrivstoffikke;IPIDviserfeilfyllingunderKasko menrenseytelseiMini.','Mini§2.4.2s5snø/s6MC;IPID','mini')
r('Totalskade','market','Markedsverdi,selskapgjenoppbygge/restbeholdfradrag;stjåletvent21d.','Mini§3.3/3.5s5–6snø/s6–7MC','mini')
r('Oppgjør','repair','Selskapverkstedvalg,slitasjefradrag,50%arbeidkontanteksMVA;ikkegaranti/verditap/foreløpig/overtid/flyfrakt.','Mini§3.4s6snø/s7MC','mini')
r('Alarm','deductible','4000reduksjontyveri aktivFG/fabrikkalarmellerFGgjenfinning.','Mini§4.1s7snø/s8MC','mini')
r('Kasko','scope','Kollisjon/utforkjøring/velt/annenytre;maskinskade/leiebilunntattmedMCegenrentalpositiv.','Kasko§1s7snø/s8MC','kasko')
r('Kasko','excluded_use','Forsett/rus/ulovligterreng/bane(unntaktrafikkskole/godkjentkurs)/utleie/erverv.','Kasko§1s7snø/s8MC','kasko')
r('Kasko','deductible','Bevisvalg;under23ikkeopplyst+12000;dyre2000reduksjonkunveteranikkeMC/snø.','Kasko§3s7–8snø/s8–9MC','kasko')
r('Løsøre','limits','MC husstandstinglåstpåmontertboks5000,ikkepenger/smykker/klokker;verdifallmin1/3førfradrag.','Mini§1.3/3.8s5/7MC','mini','mc')
r('Personreise','limits','MC hjemreiseførerpassasjersyk/død/drift/dekketskade/tyveri;fortsattreisehvisrimeligere;utekaskoNordenrental350/dag30dveddekketskadeikkealenedrift;forhåndgodkjent. SNØikke.','Mini§2.4.1s5–6MC','mini','mc')
r('Nyverdi','conditions','MCogmoped≤3mnd≤2000km,kost>80%nypris,ingenførskade>10%,registrertfabrikkny påeier. SNØikke.','Mini§3.3.1s6MC','mini','mc')
r('Leiebil','limits','MCKasko350/dag15dnormalreparasjon,godkjentleverandør. SNØikke.','Kasko§1.2s8MC','kasko','mc')
r('Bonus','rules','MCstart60web;bonus ingenforulykke/legal/branntyv/glassredning/natur/dyr;75%4årførsteskade0;80førsteskade70%;bevisvalg;3årubruktbortfaller.','PMO004.412s2MC','all','mc')
r('Egenandel','choice','MCKasko4000/7000/10000/15000;kundespesifiktvalg.','SB1webEgenandeler','kasko','mc')
r('Kjøreutstyr','source_boundary','SB1websamlerkjøreutstyrunder10000tillegg;fullPDFfører egenbulletkjøreutstyrutenfastsum. Ikkeantaekstraubegresetsum.','SB1webTilleggsutstyr;Mini§1.2s5MC','mini','mc')
r('Sikkerhet','requirements','MCkjøreutstyrlåsttilsykkel/veske,nøkkelseparat/service/hjelm/førerrett;tilhengersikringmedMC;LOfavør1000lavereegenandelikkeordinary.','SB1webSikkerhetsforskrifter','all','mc')
r('Typer/nivå','scope','CampingMini/Kasko;TilhengerkunKaskomedMini,EuropaTyrkiaIsrael;14deierskifte/bevisegenandel høyesteperhendelse.','PMO354§1–4s1;IPID','all','tow')
r('Forsikringsobjekt','scope','Tilhengerbevis;campingfasteutstyr/fortelt/tilbygg/campingbyggibevis;løsøresamlebevis,10000perting,ikkecashpapir/smykker/yrkesløsøre.','Mini§1s1','all','tow')
r('Brann/tyveri','scope','Brannlyn/eksplosjon,tyv/forsøk/hærverk;ikkehusstand/ansattsjåfør,tyverifraførtelt,lås/omkodingelleruskaddhjul.','Mini§2.1–2s1–2','all','tow')
r('Glass','limits','Campingglassinkl takluke,600reparasjonsgrense0egenandel,2500skifte ogmax50%markedsverdi;ikkeTilhenger.','Mini§2.3/3.5.1/4.2s2–4','all','camp')
r('Redning','scope','Transportnærmesteverkstedetterdekketskade/driftpåtilgjengeligvei;billigerereparerpåsted;ikkeservice;500egenandel.','Mini§2.4/4.3s2/4','all','tow')
r('Sum/oppgjør','limits','Avtaltmarkedsverditak,fortelt/tilbyggmåinkludert;totalrestfradrag.','Mini§3.1–2s2','all','tow')
r('Nyverdi','conditions','Camping/Tilhenger≤1årfabrikknyregistrertpåeier,rep>80%nypris,ikkeførskade>10%.','Mini§3.2s2','all','tow')
r('Oppgjør','repair','Selskapvalg,slitasjefradrag,50%arbeid kontant/MVAdokumentert;stjålet21d;ingenverdifall/garanti/overtid/flyfrakt.','Mini§3.3–4s2–3','all','tow')
r('Aldersfradrag','objects','Campinghvit/brun5år10%,elektronikk1år20%,fortelt2år10%,påbegyntårmax80%;genereltverdifallmin1/3førfradrag.','Mini§3.5.3–4s3','all','camp')
r('Tilbygg','rigging','Campingtilbyggned/opprigg20000nårannen dekket skade.','Mini§3.5.4s3','all','camp')
r('Alarm','deductible','CampingtyveriaktivFG/fabrikkalarm ellerFGsikring4000reduksjon.','Mini§4.1s4','all','camp')
r('Kasko','scope','Plutseligytrekollisjon/velt;ikkeforsett/rus/erverv/tilhengergodsutenannenhendelse/campingråte/forteltløsørevann/monteringsskadeutenannenhendelse.','Kasko§1.1s4','kasko','tow')
r('Ferieavbrudd','limits','KunCampingKasko,planlagtferie>3d,hindretavdekketskade;1500/dagmax15normalrep;godkjent,dokumentert.','Kasko§1.2s4–5','kasko','camp')
r('Fukt','conditions','KunCampingKasko,til15år;godkjentbeståttautorisertkontrollførskade,gyldig1år;innenforsikringsperioden;ikkeTilhenger.','Kasko§1.3s5','kasko','camp')
r('Ansvar/ulykke/rettshjelp','conflict','IPIDCamping/TilhengerharAnsvar-liste,5sfullpakkeharikkedissetre;ikkeimportbilforsikringautomatisk.','IPIDV103s1;fullpakke','all','tow')
save('fremtind-light-vehicle-independent-inventory.json',dict(source_first=True,rules=R,review='Snow10p, MC11p token-diffsharedfullterms plusbonusread, twoIPIDs, SB1completeMCweb; tow5p/IPID2p. Exacttype-specific rules preserved. Generelle sharedPDF already reviewed earlier.'))
print(len(R))
