from continue_audit import *
R=[]
def r(s,d,v,l,scope='all',doc='terms'):
 R.append(dict(id=f'FBT-{len(R)+1:02d}',subject=s,dimension=d,value=v,location=l,scope=scope,doc=doc))
r('Sikret','persons','Eier/rettmessigfører/panthaveravtalt;14dny-eier tilnyavtale.','PMO380§1s1')
r('Geografi','scope','Europa200nmfrafastland inklIsland/Svalbard/UK/Azorer/Madeira/Kanari;redningNorden.','§2s1')
r('Egenandel','choice','Bevisvalg;høyesteperhendelse;reduksjonførfratrekk.','§4s1')
r('Forsikrede ting','limits','Båt/motor/seil/brukstilbehørinnenbevis;fastutstyr20000ogløsøre50000i tillegg;ikkemobil/cash/papir/smykke/klokke.','Mini§1.1s1')
r('Vannscooterplattform','scope','Tilhørendeflytedokk30000kunvannscooter,ikkeautomatiskallbåt.','Mini§1.1s1')
r('Ansvar','scope','Eier/føreransvar;ikkeerverv.','Mini§1.2s1/5.1s4')
r('Ulykke','scope','Fører/passasjer,ikkeerverv.','Mini§1.3s1–2')
r('Brann','trigger','Brannlyn/eksplosjon.','Mini§2.1s2')
r('Natur','trigger','Skredstormflomstormflo/hagl.','Mini§2.2s2')
r('Tyveri','trigger','Tyveri/forsøk/hærverk.','Mini§2.3s2')
r('Transport','trigger','Nærmesteverkstedetterdekketskade;hjemtransportfunnetstjåletbåt.','Mini§2.4s2')
r('Redning','trigger','Sleptryggfortøyningdrift/plutseligskade,bergelønnlovverk,750egenandel;Norden.','Mini§2.5–6s2/4.2s4')
r('Vrak','trigger','Offentligpålagt/dekketskade.','Mini§2.7s2')
r('Forsikringssum','customer','Kundenfastsettermarkedsverdi,avtaltsumtak.','Mini§3.1–2s2–3')
r('Reparasjon','settlement','Selskapvalg,slitasjefradrag,ingenreparasjonsansvar,arbeid50%kontanteksMVA,ingenverditap/garanti/overtid/flyfrakt.','Mini§3.3s3')
r('Tyveri','waiting','21d førutbetaling,markedsverdiinntilbevis,tilbakekjøp21d.','Mini§3.4s3')
r('Løsøre','depreciation','Kjøpsbevis;fradragalder/slitasje/brukstid,ingenegen1/3-terskelher.','Mini§3.5–6s3')
r('Aldersfradrag','table','Kalesje2frieår10%;drev3år10%;rigg5år10%;undervannshus3år10%;påbegyntårmaks60%.','Mini§3.7s4')
r('Utleie','condition','Uavtaltutleieforholdsmessigreduksjon;Kaskoikkeutenbevis.','Mini§3.10s4/Kasko§2.1s5')
r('Gjenfinning','deductible','FGsøksystemtyveri4000reduksjon.','Mini§4.1s4')
r('Ansvar','sum_ambiguity','PDF skriver 3020000 millioner SDR/person og1510000million SDR/ting;ekstra millionord dimensjonaltfeil/uklart. Ikkeeksternlovtolkningnå.','Mini§5.1s4')
r('Ansvar','exclusions','Kontrakt/låntleid/oppreisning/familie/medeier/erverv/forsett/gradvisforurensning/transport/motorhastighetsregatta.','Mini§5.1s4')
r('Ansvar','settlement','Fysiskperson/ting ogderesøkonomisktap;førstkonstatertperioden;egneutredningskosti tillegg.','Mini§5.2–4s5')
r('Kasko løsøre/jolle','limits','Tilbehør/løsøre100000samlet;jolle≤12fot≤15HK50000.','Kasko§1.1s5','kasko')
r('Kasko','trigger','Kollisjon/kantring/synk/mastbom/opplagtransport/sjøsetting/forurensetdrivstoff/feilfylling/seilregatta.','Kasko§2.1s5–6','kasko')
r('Kasko','exclusions','Erverv/uavtaltutleie/motorhastighet/garanti/nedbørfrostis(menisberøringboblehavninkl)/varmgang;isolertmotorseilkunannen dekketskade.','Kasko§2.1s5–6','kasko')
r('Ferieavbrudd','limits','Planlagt>3d;dekketskade;1000/dag10dnormalrep;leiebåt/bil/losji,godkjentdokumentert.','Kasko§2.2s6','kasko')
r('Ung fører','deductible','Under23ogikkeforsikringstaker+6000.','Kasko§4.1s6','kasko')
r('Topp løsøre','sum','Ubegrensetpersonligeeiendeler,øvrigeunntakMini.','Topp§1.1s6','top')
r('Topp ferie','limits','1500/dag15dnormalrep;planlagt>3d,godkjentdokumentertleiebåt/bil/losji.','Topp§2.1s6–7','top')
r('Avbrutt båttur','trigger','Hjemreise/midlertidigoppholdvedpersonulykke/sykdom/død,dekketskade,elleruhellmedsjøudyktigbåt.','Topp§2.2s7','top')
r('Motor/seil','coverage','Seil/motor/maskindel≤10år;varmgangvedtettkjøling;tilfeldigplutseligbrudd;motor/gir/aksling/ECU/drivstoff;demonteringkostoveregenandel.','Topp§2.3s7','top')
r('Motor/seil','exclusions','Konstruksjon/råte/korrosjon/tæring/materialtretthet/nedbørfrostis;ikkemotorpåjolle.','Topp§2.3s7','top')
r('Opplagsutstyr','coverage','Stativ/presenning/krybbe.','Topp§2.4s7','top')
r('Motor/seil','deductible_depreciation','4000egenandel;seil/maskin1årfradragsfrittderetter10%perpåbegyntårmax60%;fradrag>4000ingenegenandel;bruktedelerbarearbeidsfradraginkMVA.','Topp§3.1/4.1s7','top')
r('Nyverdi','threshold','Ny båtog/ellermotor≤3åretterkjøptny;rep>60%nyverdi;båt/motoraldreseparate.','Topp§3.2s7','top')
r('Ulykke','limits','100000død/200000invaliditet/15000behandling;kroppsskade,båtdirekteårsak.','PMO380481§1–3s8')
r('Ulykke','conditions','Død1år,invaliditet1–3år,behandling2år/barnunder16 3år;1000egenandel;ikkespisingtann/briller/privateutenstøtte/redninghotell.','PMO380481§5–6s8–9')
r('Rettshjelp','limits','Norden100000interessetak/250000min3parter;15kFinKN25kforlik20%sakkyndig;bevisegenandel+20%.','FFE003s9–12')
r('Rettshjelp','exclusions','Tvistgrunnlagførsamt yrke/familie/straff/annetobjekt/salærtvistunntak;solgtbåttvistinkl.','FFE003s9–12')
r('Egenandel','options','Kasko/Topp4000/7000/10000;750redningfast.','SB1Egenandeler','kasko','web')
r('Utleie','channel','2mnd/årutenekstrakost,menmeldselskapet;kanharmoneremedbevisendringikkefribetingelsesløs.','SB1Leieut','all','web')
r('Registrering','eligibility','Verdiunder50000uregistrertmulig;merkreverSmåbåt/Securmark/NOR. Lik50000ikkeentydig.','SB1Registrering','all','web')
r('Kanal','conflicts','FAQmotor knytter<10årtilbåt vsPDF≤10årmotor/seil;webbilligsteFAQimplisererjolle/ferieToppmensmatrix/fullKasko;IPIDTopp-listeutelaterubegrensetløsøreog100kplassertKasko.','SB1FAQ/IPIDV103','all','web')
r('Sesong/rabatt','customer','Sesongprisbruksperiode;5%per4sikringstiltakmax20%;LOfavør1000reduksjon/ToppprisKaskoikkeordinary.','SB1sesong/rabatt','all','web')
r('Administrativt','limits','Skadeplikt/skjønn/regress ogfullgeneral terms allerede lest;ikkemodellehveradministrativsetning.','Fullpakken/General','all')
save('fremtind-boat-independent-inventory.json',dict(source_first=True,rules=R,review='Full12p plusIPIDV1032p and complete materialSB1HTML. FFE003tokenidentical toalreadyreviewedBobil. SDRdimensiontypo retained unresolved.'))
print(len(R))
