from continue_audit import save
R=[]
def r(s,d,v,l,scope='all'):R.append(dict(id=f'FIN-{len(R)+1:02d}',subject=s,dimension=d,value=v,location=l,scope=scope))
r('Personkrets','eligibility','Fastfolkeregistrerthusstandikkebokollektiv;utdanning/vernepliktbarnutensadresseendring;egnebarnannetstedunder20;14deierskifte;2mndsamlivsbrudd.','§1s1')
r('Geografi','duration','AvtaltstedogNordenmidlertidiginntil3år+nybosted;naturogsvakvindNorge;ansvar/rettshjelpNorden.','§2s1')
r('Forsikringssum','agreed','Avtalttotalinnbosumbevis;egneogtingrisikooverførtvedlov/skriftligavtale.','§3.1s1')
r('Objektgrenser','valuables','Gull/smykker350k,annetmetall350k,vin/sprit500k,kunst500k,enkeltting/samling350k;utvidbarbevis. IPIDkunst350k konflikt.','§3.1s1;IPIDs1')
r('Lagring','sum','EksterntlagerStandard100k/Topp350k;ikkeubegresetsum.','§3.1s1')
r('Sykkel','sum','Standard20k/Topp40k;el-sykkellovlig.','§3.1s1')
r('Penger','sum','Standard15k/Topp30k;verdipapirmed.','§3.1.1s2')
r('Ting','small_objects','Kano/kajakk/seilbrett;hageutstyr≤10km/t;hobbyveksthus/telt20k/40k.','§3.1.1s2')
r('Kjøretøytilbehør','sum','Løsebildeler20k/40k,båtdeler20k/40kibygning/container;tilhenger20k/40k;ikkemotorkjøretøy/elsparkesykkel/nøklerhjulfelger.','§3.1.1s2')
r('Yrkesløsøre','limits','Standardhjem50k/arbeidsbygning25k/skap5k;Topp100k/50k/10k;ikkefastselvstendigvirksomhetutenforbolig.','§3.1.1s2')
r('Leid/sameid bolig','fixtures','Varmepumpe/kjøling;egentillegginnredningStandard100k/Toppingensærgrensehvisikkeerstattetbygning/leieopphør;integrertehvitevarer;tyverirom20k/40k.','§3.1.2s2')
r('Ubeboelig','accommodation','Normalreparasjonstidgodkjentmeropphold;Standard100k/Toppingenegenbeløpsgrense;fradragsparteutgifter/leietap.','§3.2s2')
r('Merutgifter','removal','Nødvendigflytting/lagring/rydding/bortkjøring/deponering.','§3.2s2')
r('Rekonstruksjon','sum','25k/50knotaterfoto/data;ikkereiseopphold;Toppikkeetteruhell/mobil.','§3.2s2')
r('Gass/vann','loss','Lekkasjeutstrømning20k/40k.','§3.2s2')
r('Brann','coverage','Brann/lyn/spenningsfeil/eksplosjon/nedsoting;ikkesvi/gnistutenbrann/heksesot.','§4.1s3')
r('Vann','coverage','Rør/utstyr/akvarium;grunn/avløpståendeovergulv;ikkesøl/bruk/kondens/soppråte.','§4.2s3')
r('Vann','ingress','Toppoverterrenggjennomutettbygg;Standardingenpositivslikregel.','§4.2s3','top')
r('Glass/porcelain','scope','Standardbruddleidsameieglassdørvindu/sanitær/platetoppinnbygging;ikkereper/punktering. Topp§4.10annetplutseligmedunntak.','Standard§4.3s3;Topp§3.1.2s2/§4.10s5')
r('Vind/snø','coverage','Standardeksplicitvindsvakstorm/snøtakrasikketelt/veksthus;Toppannenfysiskplutselig§4.10medunntak.','Standard§4.4–5s3;Topp§4.10s5')
r('Tyveri hjemme','limits','Bygning;hærverkvedtyveri/ulovliginntrengningikkeøvrig;fellesbod100k/350k;privatuteareal50k/100k;ikkeverdigjenstanderbod/ute/felles.','Standard§4.6.1s4;Topp§4.3.1s3')
r('Tyveri utenfor','limits','Annenbeboddbolig;arbeidpersonlig20k/40k;sykehus200k;allmennbygning20k/40k;barnevognsykkelhenger;ikkepengerverdipapir/fritidsboligavtale.','Standard§4.6.2s4;Topp§4.3.2s3–4')
r('Tyveri lager','limits','100k/350kbygning/container;ikkeverdigjenstander.','Standard§4.6.3s4;Topp§4.3.3s4')
r('Tyveri fra bil/båt','limits','40kpersonligogyrkesløsøre,bilMCbåt/låstboks;ikkeverdigjenstander.','§4.3.4s4','top')
r('Ran','scope','Ran/overfall;nappingfra/påveske20k/40k;ikkefritidsboligavtale.','Standard§4.7s4;Topp§4.4s4')
r('Matvarer','sum','Utilsiktettemperatur20k/50k;skadepåfrysekjøleenhetsomfølgeomfattes;oppbevarskadetmat.','Standard§4.8s4;Topp§4.5s4')
r('Flytting','coverage','Nordenhelflyttingtransport/inn-utbæring/lagringstyveri;transporttyveri100k;enkeltgjenstand100k.','§4.6s4','top')
r('Flytting','exclusions','Ikkeverdigjenstandstyveribil/tilhenger,kosmetisk,tilhenger/hobbyhus,penger,piano/flygel,dyr/planter,underslag.','§4.6s4','top')
r('Insekter','limits','Veggedyr/kakerlakk/skjeggkre150k;skjeggkre3befaringer;ikkeførinnflytting/etterutflytting.','§4.7s4','top')
r('Mobil','repair','Tilfeldigplutseligytrekjenttidårsak;avtaleverksted;ikkemangel/kosmetisk/innholdgjenoppretting;2kegenandel.','§4.8s4;§6.2s8','top')
r('Mus/rotter','scope','Skadeinnefraaktivitetstartetetteravtale;ikketingslagretgarasje/utebod/låve.','§4.9s4–5','top')
r('Uhell','limits','Annenfysiskplutseligytrekjenttid/årsak;utenforsted50k;§4.1–9unntakgjelderfortsatt.','§4.10s5','top')
r('Uhell','excluded_objects','Ikke sykkelmikromob/sportunderbruk,fjernstyrt/drone,veksthus/telt,motorkjøretøytilhenger,mobil,frimerkerpenger,yrkesgjenstand,utleiet,innsjekket,basseng,dyr(unntakakvarieglass).','§4.10s5','top')
r('Uhell','excluded_causes','Ikkeegenmangel/slitasje,kjæledyr,kondensfukt,bakterierinsekter,utettglass,frost;mistet/borte/ukjent/kosmetisk/underslagrekonstruksjon.','§4.10s5','top')
r('Rullestol','limits','300k/hendelsevarigulykkeinvaliditetellerbarnmedfødt/adoptert;boligsikredesvedhendelse,godkjentfør,utgifterinnen10år.','§4.11s5–6','top')
r('ID-tyveri','assistance','Mistankeelleroppdaget/dokumentertperiode;rådogkredittoppryddingNorden,0assistanseegenandel.','§4.12s6','top')
r('ID-tyveri','legal','1milljuridisktvist/betalingsanmerkning;godkjenning4k+20%;ikkeøkonomisk/indirektetap,næring,familie/tiltrodde.','§4.12.1–2s6;§6.2s8','top')
r('Oppgjør','cash_work','Likeverdigreparasjon/nytt/kontantvalg;250/timeegeninnsats;75%arbeidutendok/MVAikke.','Standard§5.1s4;Topp§5.1s7')
r('Oppgjør','used','Min1/3verdifallforfradrag;bruktkjøpgavearv/samler/ikkebruk/andreennhusstandmarkedsverdi;edeltmetallnyverdi.','Standard§5.3s5;Topp§5.3s7')
r('Aldersfradrag','table','Max80%;hvitebrune5år10%,mobil1år20%,elektronikk1år10%,varmepumpe5år10%,jacuzzi5år10%,sykkel3år10%,briller1år10%;påbegyntår.','Standard§5.3.1s5;Topp§5.3.1s7')
r('Egenandel','general','Bevisstyrt;høyesteperhendelse/utstyr,etteravkorting.','Standard§6s5;Topp§6s8')
r('Egenandel','prevention','FGalarmsentralbrann/tyveri,elNEK,vannhovedinntak,sikkerhetsutstyr:min3k/4kreduksjon;overvannsforebygging0.','Standard§6.1s5;Topp§6.1s8')
r('Egenandel','special','Sykkel4kFGregistrerttyveri2k;bygningsglass/sanitær/hvitevarer2k;ansvar4k;legal4k+20%;natur8k.','Standard§6.2s6;Topp§6.2s8')
r('Yrkesskade','limits','Privatarbeidsgiveruten sumtak/egenandel;ikkefrivillig/enkeloppdrag/under10timeuke.','Standard§7s6;Topp§7s8')
r('Ansvar','agreed','Nordenprivatretterstatning;sumibevisperhendelse;person/ting/følgetap,egenandel4k.','StandardAnsvars6–8;ToppAnsvars9–10')
r('Ansvar','exclusions','Kontrakt/leide-lånte/familie/felles/næring/fast eiendom/forurensningikketilfeldig/objektivtforeldreansvarunntatt.','StandardAnsvar§3.1s6–7;Topp§3.1s9–10')
r('Ansvar','special_objects','Unntakfraobjektunntak:el25km/t,gressmaskin/rullestol,hanggliderutenmotor,båt≤14fot≤10hk,kano;droneA1–A3hobbyregistrert750000SDR.','StandardAnsvar§3.1s7;Topp§3.1s9')
r('Rettshjelp','limits','Privattvist100køkonomiskinteresse,min3parterkan250k;15kFinKN25kforlik/jordskifte,sakkyndig20%;4k+20%.','StandardRettshjelps8–10;ToppRettshjelps11–13')
r('Rettshjelp','exclusions','Tvistegrunnlagføravtale/yrke/familie/straff/annetobjekt/motorkjøretøy/båt>15foteller10hk;egenbygningsrettshjelpikkeparalleltviaInnbo.','StandardRettshjelps8–10;ToppRettshjelps11–13')
r('Naturskade','scope','BrannforsikretløsøreNorge;ras/storm/flom/stormflo/flodbølge/meteor/jordskjelv/vulkan;antenne/markiseegenutvidelse;ikkevanlignedbør/frost/tele/tørke/snøtyngde.','§3.6s3;StandardNatur10–11;ToppNatur13–14')
save('fremtind-innbo-independent-inventory.json',dict(source_first=True,rules=R,source_package='Standard11p+Topp14p+IPID2p. Shared legal/nature reused by exact clause and text; top is standalone broader full terms, not blind inheritance.'))
print(len(R))
