from continue_audit import save
R=[]
def r(subject,dimension,value,doc,location,scope='all'):R.append(dict(id=f'FBI-{len(R)+1:02d}',subject=subject,dimension=dimension,value=value,doc=doc,location=location,scope=scope))
r('Avtale','persons','Forsikringstaker/rettmessigbruker;panthaveravtalt;14d eierskifte inntil nyforsikring.','ansvar','s1§1')
r('Geografi','territory','Europa unntattTyrkia/Kosovo/Russland/Belarus;grenseforsikring etterland,egenansvardakunførerpassasjer.','ansvar','s1§2')
r('Avregistrering','transition','KunAnsvaravsluttes;Mini/Kasko/Toppomgjøreslagring;solgt/vraket/stjålet/leasingopphørslutter.','ansvar','s1§5')
r('Egenandel','customer_selected','Bevisstyrt;sammehendelsekunhøyesteegenandel,fradragførreduksjon.','ansvar','s1§4')
r('Bonus','exceptions','Ikke tap vedulykke/legal/brann/tyveri/hærverk/glass/redning/leiebil/maskin/natur/dyr;Topparkeringtilførsteforfall6år.', 'ansvar','s1Bonus')
r('Bonus','system','Ubruktbort3år;60oglavere+10/-10,70etter3år+5/-10,75etter3år+ordning/-5;valgfri75år4førsteska0eller80/-10.','ansvar','s1–2Bonus')
r('Ansvar','sum','Personubegrenset;ting100mill;EØSnorskregelomgunstigere;kontraktsansvarunntatt.','ansvar','s2FMO001§1–2')
r('Førerpassasjer','scope','Ulykkeri/utenforkjøretøyhvorbilendirekteårsak;ikke sykdom/besvimelse/forgiftning/rusmidler;to sisteikkeunder16.','ansvar','s2–3FMO002')
r('Førerpassasjer','sums','Død100kmedektefelle/samboer/barnunder20ellers50k;invaliditetvoksen200k,barnunder20 1mill.','ansvar','s3§2')
r('Førerpassasjer','settlement','Dødinnen1år;tidligereinvaliditettrekkesfra;varigmedisinskgradetter1åropptil3årforholdsmessig.','ansvar','s3§5')
r('Rettshjelp','scope','Personligeier/rettmessigfører/bruker;Norden;tvistoppstårperiode,ikketvistegrunnlagfør;ogsåettersalgtidligereeier.','ansvar','s4FFE003§1–3')
r('Rettshjelp','sums','100køkonomiskinteresse;min3parterkan250k;FinKN15k,forlik/jordskifte25k,sakkyndig20%sum.','ansvar','s4–5§4–5')
r('Rettshjelp','deductible','Egenandelbevis+20%advokat/sakkyndig;enpertvist.','ansvar','s6§5.2')
r('Rettshjelp','exclusions','Ikkeyrke/erverv/andreobjekter/straff/familie/inkasso/konkurs;forvaltningsklageførstuttømt.','ansvar','s4–5§4.2')
r('Forsikrede ting','scope','Bil levertnyforhandler,ekstradekk/felger,nøkkel,ladekabel;ikkefastmontertbygningsladekabel,ugodkjenttrim.','mini','s4§1.1','physical')
r('Tilleggsutstyr','sum','50k fastmontertellerbevisvalg;slokkeapparat/førstehjelp/barneseter;Bobil50kforteltgjelderikkepersonbil.','mini','s4§1.2','physical')
r('Personlige eiendeler','sum_exclusions','20k;ikke penger/gavekort/verdipapir/smykker/klokker;Bobil40k10kitemikkebil.','mini','s4§1.3','physical')
r('Brann','trigger','Brann,lyn,eksplosjon.','mini','s4§2.1','physical')
r('Tyveri/hærverk','trigger','Tyveri/forsøk;ikkehusstand/ansattsjåfør;underslagvedprøvekjøringsalgmedoffentligannonse;hærverk.','mini','s4§2.2','physical')
r('Glass','scope','Brudd rute/glasstak/takluke;ikkesolcelle;skifteopptil50%markedsverdi.','mini','s4§2.3;s6§3.5','physical')
r('Redning','persons','Hjemrimeligstevedulykke/sykdom/død,dekketskade/upåregneligstopp/tyveri;viderereisehvisbilligere.','mini','s5§2.4.1','physical')
r('Redning leiebil','conditional','UtenforNordenveddekketskadeikkebaredriftsstans600/dag45d,følgfastlagtruteogforhåndsgodkjent.','mini','s5§2.4.1','physical')
r('Redning','car_transport','Bil+tilhenger/campingtilnærmestverksted,ogbostedsdriftsstans/tomtank;hentetransportmax50%markedsverdi.','mini','s5§2.4.2','physical')
r('Feilfylling','emptying','Tømming/rens10k,nårikke startetmotor feilfuel;skadeetterstartikkeunderdenneredningsytelsen.','mini','s5§2.4.2','physical')
r('Totalskade','market_settlement','Markedsverdi tilsvarende vesentligstand;nybil1år15kkm>80%nyverdi,ikkelesing;utgåttmodellkontantsisteliste.','mini','s5–6§3.2','physical')
r('Leasing','start_rent','1år15kkm>80%,startleienedskrivesgjenværendemåneder.','mini','s6§3.2.2','physical')
r('Reparasjon','guarantee','8årvedavtaleverkstedprivatbil≤3500kgfra2023;ikkeglass/slitasje;leiebil600/dag45d,veihjelp;reklamasjon2mnd.','mini','s6§3.3','physical')
r('Reparasjon','settlement','Tilvarendeogbruktedeler;forringelsefratrekk;kontantarbeid50%eksMVA,MVAetterdokumentert;ikkeverditap/garantitap.','mini','s6§3.3','physical')
r('Tyveri','waiting_key','Bilikkeretur21dmarkedsverdi;stjåletnøkkelomkodingnyhvisforebyggende.','mini','s6§3.4','physical')
r('Eiendeler','depreciation','Alder/slitasjemvfradragkunverdiforringelse≥1/3.','mini','s7§3.7','physical')
r('Kjørelengde/trim','risk','Årligavtaltkjørelengdeoverstigelseproporsjonalreduksjon;godkjenttrimogsåmeldes;ugodkjentikke.','mini','s7§3.10','physical')
r('Kasko','trigger','Sammenstøt/utforkjøring/velt/feilfuel/annenplutseligytrepåvirkning.','kasko','s8§1.1','kasko')
r('Kasko','exclusions','Maskin/leiebilegnedekninger;slitasje/gradvis/frost,ruskjøring/utmark/bane(medkursunntak),utleiehvisikkeavtalt,drosje/bud/næringikke.','kasko','s8§1.1','kasko')
r('Kasko','deductible','Bevisvalgt;+12kveduopplystførerunder23;dyrredusererinntil2k.','kasko','s8§3.1','kasko')
r('Bilnøkkel','limits','Topp15kny/programmering/omkodingautorisertvedmistet/stjålet/plutseligytre;egenandel1k.','topp','s8§1.1.1;s10§3.1','topp')
r('Ladekabel','limits','Topp10ktyveri/plutseligytre,ikkebygningsfast;egenandel1k.','topp','s9§1.1.2;s10§3.2','topp')
r('Rens interiør','limits','10kplutseligsøl1kegenandelutenbonustap;ikkeelektronikk/følge/rifter;over10kordinærkasko.','topp','s9§1.1.3;s10§3.3','topp')
r('Parkering','age_conditions','Tilførstehovedforfalletter6år;ukjentskadevolder,kjenttid/sted;ellersordinærkaskobonus.','topp','s9§1.1.4','topp')
r('Feilfylling','deductible','Topp1kegenandel;bonustap.','topp','s9§1.1.5;s10§3.4','topp')
r('Totalskade','expanded','3år100kkm>80%nyverdi;ikkelease;utgåttmodellkontantsisteliste.','topp','s9§2.1','topp')
r('Leasing','expanded','3år100kkm>80%,startleieforholdsmessigrestmåneder.','topp','s9§2.1','topp')
r('Leiebil','optional_limits','ValgfriKasko/Topp;600/dag45dnormalreparasjon tilsvarendebil;godkjentleverandør;ikkeglass/drivstoff/bom/parkering.','rental','s1§1;IPIDV106s1','addon_rental')
r('Leiebil','total_loss','Totalskade/tyveri15d etter tilbud sendt,totalt45d fra skademelding.','rental','s1§2.1','addon_rental')
r('Maskinskade','optional_limits','ValgfriKasko/Topp;tilførste hovedforfall etter10år eller200 000kmførst.','machine','s1§1.1;IPIDV106s1','addon_machine')
r('Maskinskade','components','Plutseligtilfeldig;motorblokk/topplokk/turbo/coil/innsuginnsprøyting/EGR/vann/start/dynamo/lambda/NOX/AdBlue;EVbatteriDCinverterladerelmotorstyringladekontakt/PTCACmedbatterifunksjon;gir/driv/servo/styring.','machine','s1§1.1','addon_machine')
r('Maskinskade','exclusions','Ikke bremser/fjæring/tørrclutch/ledning/høyvoltskabel/understell/slitasje/eksosrør/infotainment;ikkeoljevarmgangfrostirrfukt/gradvis/garanti/trimugodkjent/terrengbaneunntattkurs.','machine','s1§1.1','addon_machine')
r('Maskinskade','battery_deduction','Bilfra5år10%perårmax50%,egenandeletterfradrag;bruktlikeverdigkunegenandel;uvanligslitasjeekstrafratrekk.','machine','s1§2.1','addon_machine')
r('Maskinskade','deductible','Til99999km10k;100000–14999915k;150000–20000020k.','machine','s2§3','addon_machine')
r('Maskinskade','settlement','Ikkekontantoppgjør;øvrigMinikasko§3.','machine','s2§2.2','addon_machine')
r('Kanal/version','legacy_separation','EikaM05PPluss/Kasko6år60kmaskininkludert/nybil1år15k mv er annet dokument enn dagensV106medvalgfriekomponenter.Offisiellkanalside dagensnytegningfra13.10.2025;ikkeoverførhistoriskEika.', 'legacy','s1–2;Eikavilkår/IPIDsidelokalt','all')
r('Generelle vilkår','exceptions','Generelle begrensningerkrig/terror/atom;terrorfelles500mill/år,tingutenforNordenikke;bevisforrang.','general','s1§1','all')
r('Administrativt','administration','Skjønn/renter/kravmelding/oppsigelse/gjenopptak/lovvalg;grunnleggendeadministrasjon,ikkeallemånycanonicalrad.','general','s1–3§2–15','all')
save('fremtind-bil-independent-inventory.json',dict(source_first=True,rules=R,scope_note='PMO shared terms explicitly checked across four level PDFs. Channel-specific published additions require saved source artifacts; do not infer from insurer alone.',source_comparison='Shared text diff reviewed, only pagination/layout reorder; same named legal clauses. Minikasko nybil rule is in its own full terms, IPID lists it under Kasko: record source applicability conflict.'))
print(len(R))
