from continue_audit import save
rows=[]
def r(subject,dim,value,page,section,scope='both',component='',priority='P2',kind='RULE'):
 rows.append(dict(inventory_id=f'FR-HU-{len(rows)+1:03}',subject=subject,dimension=dim,value=value,page=page,section=section,scope=scope,component=component,priority_if_missing=priority,kind=kind))
r('Forsikringsform','fullverdi/førsterisiko','Bevisstyrt fullverdi uten forsikringssum eller førsterisiko med valgt sum; særgrenser gjelder også fullverdi.',8,'6.14',priority='P1',kind='CUSTOMER_SPECIFIC')
r('Bygning','omfang','Navngitte bygg, fastmontert utstyr og midlertidig nedmonterte bygningsdeler. Frittstående uforsikret bygg inntil ti m² på stedet dekkes uten bevisoppføring, med angitt hendelseshenvisning.',2,'3.1',priority='P1')
r('Utvendige anlegg','rør/solceller','Utvendige ledninger/tilkoblet utstyr frem til offentlig tilknytningspunkt eller spredeledning; solceller til privat strømbruk.',2,'3.2')
r('Hage','areal/omfang','Fem dekar; basseng/boblebad/badestamp med ledninger inkludert; drivhus ikke hage.',2,'3.3',priority='P1')
r('Brygge','sum/vilkår','Fast trebrygge 100 000 ved brann/naturskade inkl riving/rydding/deponering. Stein/betong/molo/flytebrygge/landgang ikke omfattet.',2,'3.3–3.4, fortsetter side3',priority='P1')
r('Utvendige anlegg','unntak','Brønn/borehull/infiltrasjon/spredesystem unntatt. Drenering kun mot brann/naturskade. Produksjonsutstyr/-skog/avling/dyrket mark/utmark unntatt.',2,'3.4')
r('Standard','hendelser','Brann/nedsoting/lyn/elektrisk fenomen, eksplosjon, rørbrudd/vann, forurensning, snøtyngde/snøpress/vind under storm, tyveri/hærverk, naturskade og annen plutselig/uventet skade.',4,'5.1',priority='P1')
r('Vann','inntrenging/utstrømming','Terreng-/grunnvann som flyter over gulv; utvendig ledning; følgeskade ved dekket bygningsskade; innvendig ledning/utstyr.',4,'5.1/3–5',priority='P1')
r('Forurensning','årsak','Bygning/hage ved eget dekket rør-/tankbrudd eller lekkasje fra tanker/rør på naboeiendom.',4,'5.1/6')
r('Skadedyr standard','inkludert','Vis Forsikring; plutselig/uventet dyreskade på bygg med boenhet og frittstående garasje i beviset, samt bekjempelse mus/rotter etter påvist aktivitet.',4,'5.2',priority='P1')
r('Skadedyr standard','tidsvilkår','Bekjempelse bare når aktivitet starter etter kjøp og bare mens forsikringen er i kraft, selv om aktivitet startet tidligere i forsikringstiden.',4,'5.2',priority='P1')
r('Tining','grense','Rimelig/nødvendig tining av utvendig vann-/avløpsrør 50 000; står i Standard, ikke kun Utvidet.',4,'5.3',priority='P1')
r('Rullestoltilpasning','sum/vilkår','250 000 ved livsvarig rullestolbehov etter ulykke eller medfødt fysisk handikap hos nyfødt; utført innen fem år; samordnes med NAV/skadevolder.',5,'5.5',priority='P1')
r('Standard','viktige unntak','Utett våtrom/følgeskade, takrenne/nedløp, drenering, væsketap, sopp/råte/heksesot/insekter/kjæledyr, tele/setning/fundamentering og konstruksjon/montasje/slitasje, estetikk/punktert glass, leietakerskade og klimaskade på hage er begrenset. Særdekningene kan fravike presise deler.',5,'5.6',priority='P1')
r('Tilleggsutgifter','standard','Riving/rydding/deponering, indeksprisstigning, tap av egenbruk og bevisavtalt husleietap i normal reparasjon/gjenoppføringstid.',5,'5.8',priority='P1')
r('Offentlig påbud','sumvariant','Fullverdi alle dekningsmessige utgifter; fredet bygg én million; førsterisiko 25 % av sum og maksimalt250 000.',5,'5.8/5',priority='P1')
r('Offentlig påbud','vilkår/unntak','Merutgifter gjenoppføring, grunn/fundament og nødvendig arkeologi. Ikke påbud som kunne vært gitt før skade, provisorisk bygg, planlagt ombygging eller opprettholdt innvendig areal. For større nytt bygg forholdsmessig areal.',7,'6.6',priority='P1')
r('Fullverdigaranti','sted/formål/tid','Samme sted/gnr-bnr og formål innen fem år: ikke verdiøkningsfradrag.',6,'6.4',priority='P1')
r('Fullverdigaranti','annet sted/formål','Annet sted samme formål: fradrag for verdiøkning over40 %. Nektes gjenoppføring, fritak innen samme kommune. Annet formål: hele økningen trekkes.',6,'6.4',priority='P1')
r('Førsterisiko','oppgjør','Valgt sum begrenser; ved gjenoppføring innen fem år trekkes verdiøkning over40 % av tidligere markedsverdi.',6,'6.5',priority='P1')
r('Gjenoppføring','femårsfrist/annen eier','Ikke gjenoppført innen fem år: tilleggstak verdifall. Ny eier: begrenset til markedsverdifall med unntak ektefelle/samboer/livsarving.',7,'6.7 og side9/6.16',priority='P1')
r('Egenbrukstap','beregning','Egen helårsbolig markedsleie umøblert; hytte/midlertidig/sekundærbolig faktisk bruk maks50 000; sparte utgifter og renter trekkes.',7,'6.10, fortsetter side8',priority='P1')
r('Aldersfradrag','årsaker/beregningsbase','Kun angitte elektriske hendelser/ledningsbrudd/utstyr. Reparasjon/gjenskaffelse og eldste del styrer.',8,'6.12',priority='P1')
r('Aldersfradrag','utvendig/bunnledning','Ikke plast/glassfiber: fem prosent per år over20, maksimalt80 %; samme for brudd på bunnledninger.',8,'6.12 – tabell',priority='P1')
r('Aldersfradrag','pumper/bereder','Ti prosent per år over fem år for varmtvannsbeholder og innvendige/utvendige pumper.',8,'6.12 – tabell',priority='P1')
r('Aldersfradrag','basseng/oppvarming','Basseng/boblebad/badestamp ti prosent per år over fem; annen varme/kjøleinnretning fem prosent per år over ti.',8,'6.12 – tabell',priority='P1')
r('Egenandel','standard/spesial','Bevisets egenandel; skadedyr/råteskade6 000, bekjempelse2 000, glass6 000, sprenging+6 000; naturskade8 000; vind understorm/overflate-/terrengvann8 000 med mindre høyere avtalt.',8,'6.14 – tabell, fortsetter side9',priority='P1')
r('Egenandel','gjentatt skade','+20 000 ved samme type vannårsak/avløp/mus-rotter/rørbrudd innen24måneder.',9,'6.14',priority='P1')
r('Egenandel','fritak og samordning','Ingen ved aktiv varslende tyverialarm eller skade kun vern/alarm. Aldersfradrag og egenandel summeres ikke; høyeste av disse.',9,'6.14',priority='P1')
r('Ansvar','omfang','Eieransvar for forsikret bygg i Norden, ikke yrke/næring/styreverv/annen eiendom; familie/lånte ting/graving/sprenging og gradvis fukt begrenses.',10,'7.1–7.2')
r('Ansvar','sum/egenandel','Fem millioner per skade og år;6 000 egenandel.',10,'7.4',priority='P1')
r('Rettshjelp','omfang','Tvist som eier av forsikret bygg i Norden, med særregel ved salg eller nytt kjøp før ny forsikring. Ekskluderer næring/styreverv/annen eiendom.',11,'8.1')
r('Rettshjelp','sum/egenandel','100 000;250 000 ved minst tre parter;én million ved minst20. Økonomisk interesse begrenser.6 000 +20 % av øvrige kostnader.',12,'8.4',priority='P1')
r('Rettshjelp','mekling','Mekle gratis/uten egenandel før øvrige kostnader; tilbake til ordinær rettshjelp mulig.',11,'8.2')
r('Rettshjelp','unntak','Eierskifteforsikret selgertvist, familie/arv/skifte, straff/ubestridt inkasso, sameiere, advokatsalær; forvaltningssak før klageadgang uttømt og tvist før kjøp.',11,'8.3, fortsetter side12')
r('Utvidet','innvendig vannfølgeskade','Tak, vegg over bakken, gulv/vegg på/underbakke når vann flyter på gulv; innenfor tettesjiktet.',13,'9.1',scope='extended',priority='P1')
r('Utvidet våtrom','skille feil/følgeskade','Følgeskade i andre rom fra utett våtrom; våtromsskade etter dekket håndverkerfeil inkluderer retting av selve feilen på våtrommet.',13,'9.2',scope='extended',priority='P1')
r('Utvidet håndverker','årsaker/alder/sum','Materialfeil/konstruksjon/montasje/fundamentering: følgeskade innen ti år etter arbeid utført av autorisert håndverker med ansvarsrett;ti millioner samlet for alle feil.',13,'9.3',scope='extended',priority='P1')
r('Utvidet håndverker','unntak','Ikke eget arbeid, kjent feil før kjøp, for sen reklamasjon eller selve feilretting utenfor våtrom. Ikke reparasjon av utett tak/vegg. Leverandøransvar prøves først; hvis forgjeves kan dekket skade erstattes.',13,'9.5',scope='extended',priority='P1')
r('Isolerglass','punktering/alder','Punktering dekket;ti prosent fradrag per år over ti.',13,'9.4',scope='extended',priority='P1')
r('Råte/skadedyr','valg/leverandør','Vis Forsikring valgt i beviset; bygg med boenhet og frittstående garasje oppført i beviset.',13,'10',component='frende-hus-rate-skadedyr',priority='P1')
r('Råte/skadedyr','nedbrytning','Skade ved råtesopp eller langvarig mer enn ett år og aktiv vannskade.',13,'10.1',component='frende-hus-rate-skadedyr',priority='P1')
r('Råte/skadedyr','bekjempelse','Skadeinsekter: aktivitet startet etter kjøp; bare bekjempelse mens avtalen løper; Vis avgjør metode/tilkomst.',13,'10.1',component='frende-hus-rate-skadedyr',priority='P1')
r('Råte/skadedyr','unntatte bygningsdeler','Råte/vannskade på fast innredning/utstyr,dører,vinduer,lekter,tak,laft og annet utvendig treverk unntatt; blåved/mugg/ren estetikk unntatt.',14,'10.2',component='frende-hus-rate-skadedyr',priority='P1')
r('Utleie','bevisstyrt og skadeverk','Beviset må si helt/delvis utleid; leietakers forsettlige skadeverk inntil500 000 samlet12måneder;ikke slitasje/riper/hakk. Ikke hytte.',4,'5.4',component='frende-hus-utleie',priority='P1')
r('Utleie','leietap etter skade','Dekket skade, normal reparasjons-/gjenoppføringstid; avtalt leie og skriftlig kontrakt med depositum/garanti og vilkår; sparte kostnader/renter trekkes.',5,'5.8/4 og6.10 side7–8',component='frende-hus-utleie',priority='P1')
r('Bygg under oppføring','tilgjengelig særdekning','Valgfri bevisført særdekning: materialer/eide brakker, leide brakker med skriftlig ansvar50 000,eget verktøy50 000;tyverikrav;utsatt innflytting100 000;utvidet byggherreansvar/rettshjelp.',14,'11',component='SOURCE_OPTIONAL_UNMODELED',priority='P1',kind='OPTIONAL_COMPONENT')
r('Bruksbegrensning','fraflytting','Ikke fraflyttet bolig eller hybelhus/hospits/institusjon mv; skader pga kjent/forventet brudd unntatt, brann/naturskade likevel ved fraflytting.',15,'13')
r('Sikkerhet','vann/frost','Minst10grader;steng hovedvann ved fravær overén måned;snørydding/rensing av sluk/takrenner, lekkasjeutbedring og sikring under arbeid.',15,'14, fortsetter side16')
r('Administrasjon','generelle krav','Endringer før hovedforfall, meldefrist/avkortning/oppgjør; generalvilkår01.01.2026 lest via byteidentisk Innbo-original.',16,'12–15 og generelle',kind='ADMINISTRATIVE')
save('frende-hus-independent-inventory.json',{'phase':'SOURCE_INVENTORY_COMPLETE','source_first':True,'catalog_fact_values_inspected':False,'source':'catalog/sources/frende/hus/canonical/Vilkar-husforsikring.pdf','read':'all16pages+IPID2+bothstoredHTML+general4hash-reused','source_notes':['IPID2025 versusfullterms2026 preserved.','Productpage tiningmatrix saysboth included, prose saysutvidet;fullterms5.3 explicitlystandard.','Publicpage saysfullverdigaranti withoutconditions;fullterms6.4prevails.','Sectionnumbercrossreferences in source stale; source headings/fullcontext read instead.'],'rules':rows})
print(len(rows),'independent source rules saved')
