from continue_audit import O,save
rows=[]
def r(subject,dimension,value,page,section,component='base',priority='P2',kind='RULE'):
 rows.append(dict(inventory_id=f'FR-IN-{len(rows)+1:03}',subject=subject,dimension=dimension,value=value,page=page,section=section,component=component,priority_if_missing=priority,kind=kind))
r('Husstand','personkrets','Forsikringstaker, ektefelle/samboer med samme folkeregistrerte bolig, hjemmeboende barn og barn borte på utdanning/førstegangstjeneste uten adresseendring, andre faste husstandsmedlemmer. Leietakere/bokollektiv ikke omfattet.',2,'1',priority='P1')
r('Geografi','midlertidig borte','Midlertidig borte fra forsikringsstedet i Norden inntil tolv måneder; barnets studiested/tjenestested omfattet.',2,'2.1–2.2')
r('Forsikringssum','total','Ubegrenset med mindre annen sum er avtalt i beviset.',2,'3.1',priority='P1')
r('Verdigjenstander','grenser','500 000 per enkeltgjenstand, 500 000 samlet kunst og 500 000 per samling; særskilte tyveristedsgrenser gjelder i tillegg.',3,'3.1',priority='P1')
r('Innbo','spesielle objekter','På forsikringsstedet: hobbydrivhus 40 000; badestamp/basseng samlet 40 000; fritidsbåt under 15 fot/motor inntil 10 hk samlet 40 000; tilhenger/løse deler/tilbehør unntatt dekk/felger samlet 40 000; yrkesløsøre i bygning 40 000.',3,'3.1')
r('Kontanter','sum og sted','20 000 kroner samlet inne i boenheten.',3,'3.1')
r('Andres løsøre','risiko og grense','100 000 på forsikringsstedet når risiko overtatt ved lov eller skriftlig avtale; andres penger/verdipapirer ikke dekket.',3,'3.1')
r('Utstyr','felles sublimit','Luft-/vannsportsutstyr, droner og motorredskap/arbeidsmaskin inntil 750 kg utenfor bilansvarsloven samlet 40 000.',3,'3.2')
r('Sykkel','sted og sum','Ubegrenset skade/tyveri fra bygning på forsikringsstedet; tyveri/hærverk andre steder 40 000 per sykkel inklusive tilbehør.',3,'3.3',priority='P1')
r('Standard','dekningshendelser','Plutselig/uventet brann/nedsoting/lyn/elektrisk fenomen, eksplosjon/sprenging, rørbrudd/vann, bygningssammenbrudd ved snø/vind under storm, naturskade, temperaturstigning i fryser med mat/luktskade, ran, tyveri/hærverk.',4,'5.1',priority='P1')
r('Vann','inntrenging','Terreng-/grunnvann ved nedbør/snøsmelting/kjøving når vann flyter over gulv, utvendig ledning, innvendig ledning/tilknyttet utstyr og inntrenging etter dekket bygningsskade.',4,'5.1',priority='P1')
r('Tyveri','fellesbod','100 000 kroner i egen bod i felles kjeller/loft.',4,'5.1 – tabell',priority='P1')
r('Tyveri','kjøretøy/uteareal','40 000 kroner i kjøretøy og 40 000 på ute-/fellesareal ved bosted.',4,'5.1 – tabell')
r('Tyveri borte','bygning/garderobe/service','Bebodd bolig ordinære summer; rom bare sikrede har tilgang til 40 000; garderobeskap 10 000; håndverker 40 000.',5,'5.1 – tabell')
r('Lagring','avtalt oppussing/flytting','Rom bare sikrede har tilgang til, avtalt med Frende: ordinære/særskilt avtalte summer; ingen kontanter/verdipapirer.',5,'5.1 – tabell')
r('Leietaker/sameie/borettslag','bygningsdeler','Glass/sanitærporselen 40 000 og bygningsskade ved innbrudd 40 000.',5,'5.1')
r('Standard','viktige skadeunntak','Hærverk/slitasje fra beboer/bruker/leietaker; sopp/råte/heksesot/bakterier/insekter; drenering/takrenne/nedløp; søl/kondens; riper/rift/hakk/hull/avskalling; kjæledyr; slitasje/egenfeil. Rene vedlikeholds- og driftsfeil er ikke like dekket vannhendelse.',5,'5.2',priority='P1')
r('Rekonstruksjon','sum','Notater/tegninger/datalagre 30 000.',5,'5.3')
r('Borteboing','merutgifter','Merutgifter til annen bolig, flytting og lagring i normal reparasjon/gjenoppføring ved bygningsforsikringsdekket skade; forhåndsavtale. Samordnes med bygningsforsikringens kompensasjon.',5,'5.3',priority='P1')
r('Tap av væske','sum','Forhøyet vannavgift/fyringsolje/annen væske/gass etter lekkasje 10 000.',5,'5.3')
r('Leietaker','påkostet innredning','100 000 for egen påkostet innredning når leieforhold avsluttes eller skade ikke utbedres; ikke borettslags-/aksjeleilighet.',5,'5.3')
r('Aldersfradrag','oppgjørsregel','Konkret alder/slitasje/brukstid/markedsverdi; eldste del styrer når deler har ulik alder. Brukt/arvet/gitt ting beregnes som tilsvarende brukt, kunst/samling til markedsverdi.',6,'6.3 og 6.5',priority='P1')
r('Egenandel','standard','Kundens avtalte egenandel står i beviset.',6,'6.7',kind='CUSTOMER_SPECIFIC')
r('Egenandel','naturskade og spesialvann/vind','8 000 for naturskade; samme ved vind under storm og vann fra terreng/grunn.',7,'6.7',priority='P1')
r('Sykkel','egenandelsrabatt','2 000 kroner lavere egenandel med aktivt abonnement i FG-godkjent sykkelregister.',7,'6.7')
r('Egenandel','alarm/vern','Ingen egenandel ved tyveri med aktiv alarm som varsler alarmsentral/vaktselskap/nabo etter fast avtale; heller ikke skade bare på overspenningsvern/brannalarm/innbruddsalarm.',7,'6.7')
r('Skadedyr','leverandør og omfang','Vis Forsikring bekjemper veggedyr/kakerlakker/skjeggkre/andre skadeinsekter samt rotter/mus; bare forsikringsstedet.',7,'7.1–7.2',priority='P1')
r('Skadedyr','sum/egenandel','150 000 per skadetilfelle og 2 000 egenandel.',7,'7.2',priority='P1')
r('Skadedyr','unntak','Undersøkelse, forebygging og tiltak uten Vis sitt samtykke ikke dekket; bekjempelse er ikke samme som skade på innbo.',7,'7.3',priority='P1')
r('Ansvar','sum/egenandel','5 millioner per skadetilfelle og samlet per år; 6 000 egenandel.',9,'8.4',priority='P1')
r('Ansvar','privat rolle/vesentlige unntak','Privatpersonansvar i Norden; yrke/næring/styreverv/annen fast eiendom, motorvogn/båt, drone ikke CE-leketøy eller minst 250 gram, familie og lånte/leide ting er begrenset/unntatt. Jordbruk under 100 000 årlig inntekt særunntak.',8,'8.1–8.2; 2.2',priority='P1')
r('Rettshjelp','summer','100 000 per tvist; 250 000 med minst tre parter og én million med minst 20 parter; økonomisk interesse begrenser; summer gjelder på tvers av forsikringer/selskaper.',10,'9.4',priority='P1')
r('Rettshjelp','egenandel','4 000 + 20 % av øvrige kostnader; én egenandel per tvist.',10,'9.4',priority='P1')
r('Rettshjelp','mekling','Mekle kostnadsfritt/uten egenandel før andre rettshjelpskostnader påløper; ordinær egenandel ved overgang til rettshjelp.',9,'9.2')
r('Rettshjelp','rolleavgrensning','Fullvilkår er et innbodokument men 9.1 bruker uttrykket tvist som eier av bygning, mens innledning gjelder eier/leier av bolighus/leilighet og hytteunntak. Bred privat tvistedekning kan ikke utledes uten avklaring.',9,'9 og 9.1',kind='SOURCE_AMBIGUOUS')
r('Rettshjelp','vesentlige unntak','Familie/arv/skifte, ubestridt inkasso/konkurs, straffesak, forvaltningsvedtak før klageadgang er uttømt, sameiere, motorvogn/båt, advokatsalær og kostnader før tvist/tvistegrunnlag før start.',10,'9.3',priority='P1')
r('ID/nettmisbruk','praktisk bistand','Mehrwerk gratis praktisk hjelp og rådgivning; avvisning av uberettigede krav/sletting av anmerkninger; bistand med uønsket materiale/profiler/kontoer og avindeksering.',11,'10–10.2')
r('ID/nettmisbruk','viktige begrensninger','Ikke økonomisk tap, ID-papirer/kort, advokat eller utenlandske kreditorer uten norsk inkasso/rettsinstans. Kortsvindel ikke ID-tyveri. Nettmateriale norsk/dansk/svensk/engelsk; ikke samtykket/lukkede grupper.',11,'10.1/10.3, fortsetter side12',priority='P1')
r('Uhell','valg','Bare inkludert når valgt i forsikringsbeviset. Standardens skadedyrbekjempelse er ikke uhell.',12,'11','frende-innbo-uhell',priority='P1')
r('Uhell','hendelse','Tyveri eller skade ved plutselig/uventet ytre hendelse som sikrede ser når den skjer; mistet/gjenglemt unntatt.',12,'11.3–11.4','frende-innbo-uhell',priority='P1')
r('Uhell','summer/sted','Hjemmet: ubegrenset/avtalt sum. Flytting i Norden 100 000 inkl transport/inn- og utbæring. Andre steder 40 000. Boliginnbo verdensdekning, hytte bare forsikringsstedet.',12,'11.3 og side2/2.3','frende-innbo-uhell',priority='P1')
r('Uhell','objektunntak','Kontanter/verdipapirer, luft-/vannsportsutstyr/båt, kjøretøy/deler/tilbehør/tilhenger, droner/radiostyrt utstyr, sykkel/el-sykkel, yrkesløsøre, utlånte/utleide og transporterte ting unntatt.',12,'11.2','frende-innbo-uhell',priority='P1')
r('Uhell','skadeunntak og kildeforskjell','Vilkår 01.09.2026 unntar sopp/råte/bakterier/insekter, kjæledyr, riper/rift/hakk/hull/avskalling, slitasje/egenfeil. IPID 01.01.2025 sier derimot skader gjort av skadedyr under Uhell.',12,'11.4 mot IPID side1','frende-innbo-uhell',priority='P1',kind='SOURCE_CONFLICT')
r('Uhell','egenandel','Første skade i forsikringsåret inntil 40 000: 2 000. Skade over 40 000 eller fra skade nummer to: bevisets egenandel.',6,'6.7, fortsetter side7','frende-innbo-uhell',priority='P1')
r('Fraflytting','dekningsreduksjon','Fraflyttet fast bolig: skade som skyldes fraflytting unntatt, men brann/naturskade beholdes; gjelder ikke hytte/bygg under oppføring.',13,'13')
r('Sikring','frost/vann og sykkel','Minst ti grader alle rom; stenge vann ved fravær over én måned i bolighus. Sykkel låst, nøkkel separat, lett demonterbart tilbehør tas med og tilhenger låses til sykkel.',13,'14')
r('Administrasjon','generelle krav','Riktige opplysninger, tilsyn, autoriserte arbeider og ettårs meldefrist gjennomlest; generelle vilkår administrasjon/sanksjoner/cyber med produktunntak.',14,'12–15 og generelle1–11',kind='ADMINISTRATIVE')
save('frende-innbo-independent-inventory.json',{'phase':'SOURCE_INVENTORY_COMPLETE','source_first':True,'catalog_fact_values_inspected':False,'source':'catalog/sources/frende/innbo/Vilkar_innboforsikring_01092026.pdf','source_sha256':'608a09ff2513ac8756bd3cb12736a4d04e3dce51b87ca4a986c47b5ab2bc12db','other_sources':['IPID_Innbo.pdf 01.01.2025','Generelle_vilkar-01012026.pdf'],'read':'all14+2+4pages','rules':rows})
print(len(rows),'source rules saved before catalog inspection')
