from continue_audit import save
rows=[]
def r(subject,dim,value,page,section,priority='P2',kind='RULE',source='terms'):
 rows.append(dict(inventory_id=f'FR-RE-{len(rows)+1:03}',subject=subject,dimension=dim,value=value,page=page,section=section,priority_if_missing=priority,kind=kind,source=source))
r('Personkrets','familie','Bevisvalgt person/familie; ektefelle/samboer og barn/foster/adoptiv/surrogat under21; barne/oldebarn under21 bare på fellesreise uten egen forsikring; folketrygd og registrert Norge.',2,'1','P1')
r('Reiselengde','standard','75 dager per reise; ferie/fritid/arbeidsreise men ikke rutinemessige yrkesreiser.',2,'2','P1')
r('Reiselengde','fortsettelse','Kundespesifikk fortsettelse over75 dager; bevisperiode/område; bestilles/betales før avreise og per enkeltreise.',2,'2','P1','CUSTOMER_SPECIFIC')
r('Geografi','standard','Hele verden; ikke hjem/jobb/skole/barnehage/midlertidig bosted; ikke Arktis unntatt Svalbard, Antarktis eller Grønland.',2,'2','P1')
r('Reiseråd','inngang','Ikke til områder frarådet av UD eller med overhengende fare før avreise. Avbestilling kan gjelde ved bestilling/betaling før rådet.',2,'2','P1')
r('Avbestilling','årsak','Akutt sykdom/skade/død eller uventet akutt kjent sykdomsforverring etter betaling; legeerklæring før avreise; familie/ene-reisefølges familie må bo EØS; reisefølge inntil seks.',3,'3.1','P1')
r('Avbestilling','andre årsaker','Endret operasjonsdato, nøkkelperson innen14d, jurymedlem/meddommer/vitne innen14d, alvorlig hjemskade, nye UD-råd/overhengende fare.',3,'3.1','P2')
r('Avbestilling','økonomisk omfang','Urefunderbare transport-/overnattingskostnader; arrangement/utflukt bare når betalt overnatting dekkes; ubegrenset etter produktsiden.',3,'3.1 + produktside','P1')
r('Avbestilling','unntak','Forventet kjent sykdom, graviditet etteruke36, planlagt behandling, bare bortfalt formål, kostnader før avtale uten sammenhengende overføring, betaling etter årsak og påbegynt reise.',3,'3.1, fortsetter4','P1')
r('Avbestilling','utgiftunntak','Ikke skole/kurs/messe/seminar/timeshare, refusjon/bonuspoeng, konkurs, kostnader for personer uten forsikring selv om betalt av sikrede.',4,'3.1.1','P2')
r('Forsinkelse','viderereise','Minst1,5 time: ekstraordinært vær/trafikkulykke/offentlig teknisk feil eller privat feil med berging; nødvendig innhenting ubegrenset, hotell6000/person.',4,'3.2.1','P1')
r('Forsinkelse','avgang','Vær/teknisk feil eller kansellering uten alternativ innen24timer: nødvendig videre transport og hotell6000/person.',4,'3.2.2','P1')
r('Forsinkelse','arrangement','Ankomst minst8timer sen, minstén overnatting, forhåndsbetalt arrangement+hotell maks6000/person; ikke yrkesreise. Lagret produktside oppgir5000.',4,'3.2.3','P1')
r('Forsinkelse','unntak','Ikke mat/drikke,tapt inntekt,privat-/leasingleie,annet ennbil/MC; streik/lockout/personalmangel/konkurs unntatt; subsidiær andre betalere.',4,'3.2.4, fortsetter5','P2')
r('Reisegods','hvem/hendelser','Eget og lånt/leid ved ansvarskrav, ikke arbeidsgivers; tyveri/ran/hærverk,trafikk/forlis/brann/vann/natur og innlevert bagasje subsidiært transportør.',5,'3.3','P1')
r('Reisegods','uhell','8000 per forsikringsår; kjent observert plutselig ytre skadeårsak.',5,'3.3','P1')
r('Reisegods','grenser','Samlet ubegrenset; gjenstand med tilbehør40000; kontanter10000; reisedokumenter og nødvendige merutgifter20000; lokalt leide ting20000; hjemnøkkel4000.',5,'3.3.1','P1')
r('Reisegods','unntak','Kofferter/bagger,ren kosmetikk/slitasje,innsjekket væskesøl,kjøretøy/båtdeler/nøkler,droner i bruk,toll,sikredes familie,ikke-funksjonell sykkelskade og bortkommet/glemt ting begrenses.',5,'3.3.1','P1')
r('Bagasjeforsinkelse','innkjøp','Utreise6000/person nødvendige klær/toalett samt leie av ski/golf/fiskeutstyr mens bagasjen borte; PIR; ikke hjemreise.',5,'3.3.2, fortsetter6','P1')
r('Bagasjeforsinkelse','transit','Ufrivillig overnatting med utilgjengelig bagasje500/person. Ikke streik/lockout/personalmangel/konkurs.',6,'3.3.2','P2')
r('Leiebil','egenandel','Bil/MC feriereise med minstén overnatting; kontraktsfestet egenandel, dekket tyveri/ytre skade og hendelsen kjent ved tilbakelevering; ingen sumgrense.',6,'3.4 + produktside','P1')
r('Leiebil','unntak','Ikke bobil,privat bildele-/leasingbil,private leiebiler og andre kjøretøy; ikke når leid forandre.',6,'3.4','P1')
r('Skadedyr','omfang','Vis Forsikring bekjemper veggedyr/kakerlakker i bagasje og norsk hjem etterreise; oppstart etteravtale, kun mensaktiv; forhåndsgodkjent og ikke forebygging/undersøkelse/rengjøring.',6,'3.5','P1')
r('Skadedyr','sum/egenandel','50000 pertilfelle;maks to gangerperår;2000 egenandel hjem,500 bagasjebehandling.',10,'4.2','P1')
r('Sykdom','omfang','Akutt uventet sykdom/skade eller uventet akutt forverring av kjentsykdom; forsikringslege vurderer uventethet.',6,'3.6','P1')
r('Sykdom','aktivitetunntak','Over6000m, organisert lagcup/serie unntattbedrift, idrettinntekt>1G, motorløp/kampidrett/base/fallskjerm/dykk>40m, kriminalitet/slåssing og rus begrenses.',6,'3.6, fortsetter7','P1')
r('Sykdom','andre unntak','Ikke planlagt/forventet medisinsk behov, privat behandling i Norden,etteruke36, lete/redningsaksjon eller behandlingetterhjemkomst underreisesykebranchen.',7,'3.6','P1')
r('Sykdom','utgifter','Nødvendig lege/sykehus/legemiddel,legeordinert fysio/kiropraktor,reise og ekstrahotell;egenbil5kr/km;tyggingtooth1000,ulykkestann5000.',7,'3.6.1','P1')
r('Sykdom','reiseplan','Nødvendig innhenting av reiserute etter legens ordre om opphold i ro.',7,'3.6.2','P2')
r('Hjemtransport','vilkår','Kan ikke få nødvendig behandling; legegodkjenning; familie iEØS alvorligsyk/død eller alvorlig hjem-/forretningsskade; dødtransport eller lokalgrav40000.',7,'3.6.3','P1')
r('Ledsager','omfang','Nødvendig medisinsk/nærståendes ledsagelse; returreise innen14d behandlingavsluttetsåfremtinnenopprinneligplan;tilkallelse tofamilie fraNorden og forhåndsgodkjent.',8,'3.6.4–3.6.6','P2')
r('Reisefølge','sykdomsfølge','Eneste medreisende som blirsyk/skadet eller måhjem ved familieEEA-sykdom, nødvendige reise-/hotellutgifter og merhjemreise.',8,'3.6.7','P2')
r('Kriseterapi','sum/vilkår','20000 iNorge etterran/overfall/ulykke/brann/trafikk/natur/terror påreise.',8,'3.6.8','P1')
r('Medisinsk rådgivning','tjeneste','Falck medisinsk vurdering før avreise utenkostnad ved alvorlig/kronisk/nyoppståttsykdom.',8,'3.6.9','P2')
r('Tapte feriedager','fortsettelseunntak','Ikke fortsettelsesforsikring; produktsidens generelle sammevilkår-formulering kan ikkeoverstyre spesifiktunntak.',8,'3.7','P1')
r('Tapte feriedager','beregning','Hjemtransport/sykehus/legeordinert skriftlig sengeleie/solecompanion og UDavbrudd; transport/losji+maxtoarrangement prorata,énledsager,egenbil5kr/km.',8,'3.7, fortsetter9','P1')
r('Evakuering','utbrudd/varighet','Krig/terror/natur/pandemi etterankomst; forsikringgjelder seksuker ogUDoppfordring;preapprovalvedevakuering.',9,'3.8','P1')
r('Kjæledyr','reise','Egetmedbrakt utenforNorden1000 pertilfelleakuttsykdom/skade;ikkeutstilling/konkurranse/avl;ID/vaksiner.',9,'3.9 og17/13.5','P2')
r('Reisegods','aldersoppgjør','Markedsverdi/bruk/eldstedel, brukt/arv/gaveting likbruktgjenstand; ingen universell prosentsats.',10,'4.1','P2')
r('Egenandel','generell','Ingen medmindrebevisstyrt; skadedyr/rettshjelp har spesifikke egenandeler.',10,'4.3','P1')
r('Ulykke','summer/alder','Dødvoksen500000/barnunder21150000; invalidvoksen500000/barn700000; fra75begge100000,opphør80;prosentinvalid.',11,'5.1–5.3','P1')
r('Ulykke','behandling','Norge, femprosentinvalidsum,inntiltreår,nødvendiglege/refusjonsberettigetfysio/meds/proteser/reise;ikketyggingtann,hjelpemidler/oppholdrehab.',12,'5.4','P1')
r('Ulykke','vurdering','Invaliditetfastsettes tidligstettår,maxtrer; tidligerefunksjonstap trekkes; død førinvalidoppgjør medførerdødserstatning.',11,'5.2–5.3, fortsetter12','P2')
r('Ulykke','dødsbegunstigelse','Dødsfallutbetales ektefelle/samboer/barn;uten slike eller testamentariskbegunstiget ingen utbetaling.',11,'5.2','P1')
r('Ulykke','unntak','Ikke sykdom/svimingsårsak/medisinsktreatunlessulykke,hjerte/kreft/ledd,insektsdød/invaliditet,intoks/sport;ryggmåpåvisesbrudd medpassasjerunntak;psykiskkunPTSDetterpermanentulykke.',12,'5.5, fortsetter13','P1')
r('Ansvar','område/rolle','PrivatpersonutenforNorden; ikkearbeid/næring/styre/fast eiendom.',13,'6.1','P1')
r('Ansvar','sum/egenandel','15millioner pertilfelleogår; ingendeler; godkjentesakskost/renterutover.',14,'6.4','P1')
r('Ansvar','unntak','Kjøretøy/båt/luft/hest/visse droner,lånte/leide ting,familie/egenselskapandel≥50,kontrakt,bøter/oppreisning.',13,'6.2, fortsetter14','P2')
r('Rettshjelp','område/rolle','PrivattvistutenforNorden, ikkevirksomhet/yrke/styre/eiendom;yrkesskadedomstolsunntak.',14,'7.1','P1')
r('Rettshjelp','sum/egenandel','100000 pertvistalleparter/poliser, økonomiskinteresse begrenser;4000+20prosent.',15,'7.3','P1')
r('Rettshjelp','unntak','Familie/arv/straff/ubestridtgjeld/konkurs,forvaltningførklageuttømt,investeringover100000/allaksjehandel,kjøretøy/båt,advokatsalær;motsideskost/ankegebyrikkedekket.',14,'7.2–7.3, fortsetter15','P2')
r('Sikkerhet','relevant','Sikringavverdier/bagasje/sykkel; legeinnen72h ogvarslingkost>5000/opphold>5d;dykkesertifikat;dyrIDvaksine.',16,'13, fortsetter17','P2')
r('Administrasjon','standard','Melding/oppgjør/klage/generellevilkår; ordinaryadministrativinformasjon ikkeegenpremiumforskjell.',16,'8–12','P2','ADMINISTRATIVE')
r('Digital lege','tjeneste','Eyr gratis ubegrenset norsklege påvideo påfritidsreise,ikkeegenmedisinskforsikringssum.',None,'Legetimepåmobilen21.05.2026','P2',source='eyr')
r('Midlertidig Midtøsten','ekstraordinært','Datert28.02.2026:ekstrahjemreise10000,psykførstehjelp,6ukerutvidelse utover75 vedufrivilligopphold; hendelsesavgrenset,ikkegenerellbase.',None,'Ekstraordinæretiltak','P1','TIME_LIMITED_SPECIAL_RULE',source='midtosten')
r('Bagasjefrysing','fordel','Produktsiden omtaler rabattpåhenting/frysing/levering vedmistanke omveggedyr/kakerlakk; ikkedokumentertsum/rabattprosent.',None,'Skadedyrikofferten','P2',source='web')
save('frende-reise-independent-inventory.json',{'phase':'SOURCE_INVENTORY_COMPLETE','source_first':True,'catalog_fact_values_inspected':False,'read':'Full17pterms+2pIPID+4storedHTML+general4pre-readbyhash; historical2020excluded','rules':rows,'source_notes':['StoredHTMLarrangement5000contradicts2026terms6000;fulltermsgovern.','HTMLsameconditionsforextensionversusfull3.7exclusionmustremainexplicit.','Midtosten2026specialmeasuresarenotordinarycanonicalbase.']})
print(len(rows),'independent source rules saved')
