from continue_audit import *
R=[]
def r(tiers,sub,dim,val,loc,src='full'):
 R.append(dict(id=f'GJ-BO-{len(R)+1:03d}',tiers=tiers,subject=sub,dimension=dim,value=val,location=loc,source=src))
all=['delkasko','kasko','pluss'];kp=all[1:];pl=['pluss']
r(all,'Produktnivå','hierarki','Delkaskoansvar/legal/ulykke/brann/tyveri/redning;Kaskoytrehendelser/seilregatta/transport/opplag/fuel;Plusmotor/ferie/opplagsutstyr/frost/nyverdi.','IPID1','ipid')
r(all,'Geografi','område','Europa200nautiskemilfrafastland,inklSvalbard/Island/Storbritannia/Madeira/Azorene/Kanariøyene;hjemtransportbåtbareSkandinavia.','object')
r(all,'Reisevarighet','periode','Inntil12månedersammenhengendebortefrapermanentbevisangitthavn.','object')
r(all,'Sikrede','personkrets','Eier/forsikringstaker/lovligbruker/tinglystemedeiereogrettigheter.','object')
r(all,'Objekt','fastutstyr/jolle','Båtfastmontertutstyr;tilhørendejolle<=12fot,utenbordsmotor<=15HK,inntil50k.','object')
r(all,'Løst utstyr/løsøre','sum','Delkasko/Kasko50k;Plussubegrenset;ikke kontanter/verdipapir/ulovligimport.','1;object')
r(all,'Brann/tyveri','omfang','Åpneflammer/lyn/eksplosjon,tyveri/forsøk;hærver kbareKaskoPluss.','body')
r(all,'Brann/tyveri','egenandel','4kproduktsideogDelkasko1;kundebevisstyrer.','Egenandel','product')
r(all,'Tyveri','egenandelsfritak','0hvisFGgodkjentgjenfinningmedtyverialarmifunksjon.','settlement')
r(all,'Redning','utløser','Skade/tyveri/driftsstans,personsykdom/ulykke/død;assistanse/bergelønn.','body')
r(all,'Redning','transport/reparasjon','Nærmeste kompetenteverkstedellerbilligerereparasjonpåsted;ellershjemtransport. Repairedboathjemtransport.','body')
r(all,'Redning','person/hotell','Hjemtransportbåt/personervedpersonhendelse,nødvendiglokalovernatting/lege/sykehus/hotellalternativtilhjemtransportvedrimeligreparasjonstid.','body')
r(all,'Redning','egenandel','750;0fortotalmedlemiRedningsselskapet.','1')
r(all,'Utleie','valg/varighet','Kreversærskiltbevisavtale;privatinntil3mnd;utenavtaleutleieskaderunntatt.','IPID2;FAQ','ipid')
r(all,'Tillegg','fartsområde/bygging','Fartsområdekanutvides;byggeforsikringmulig.','2','ipid')
r(all,'Smartbåt','valg/service','OptionalGPS/geofence/vannstandtemperaturapp/turlogg;abonnementogkjøp,ikkeautomatisksikringsutstyr.','Sensorpakke','product')
r(all,'Sikkerhet','lås/opplag','Fortøyning/lens/tilsyn/sjødyktig,låstmotor/drive,hengerkobling,scooterutenuniknøkkelfysisklåst,løsøreinnelåst,presenningikkekunkalesje+tilsyn.','1')
r(all,'Endring','meldeplikt','Teknisk/endretbruk/fartsområdeskalavtales;sikringsendringpåvirkeroppgjør.','1/Pluss2')
r(all,'Sesongpris','andel','Jan5feb4mar4apr6mai9jun12jul19aug13sep10okt8nov5des5%;opphørsavregningikke12dellikpris.','season')
r(kp,'Kasko','risiko','Grunnstøting/kollisjon/stranding/synking/kantring/ytreplutseliguforutsett;maste/bombrudd;tyverihjemtransport.','body')
r(kp,'Transport/opplag','dekning','Transport,opptak,sjøsetting,opplagomfattetdekkethendelse;ikkeopplagskalesje.','body')
r(kp,'Seilregatta','dekning/egenandel','Seilregattaomfattet;2%avforsikringssumminavtaltegenandel;motorregatta/fartsprøveunntatt.','body;settlement')
r(kp,'Drivstoff','skadeomfang','Drivstoffsystemplutseliguforutsettforurenset/infisert/feilfylling;ikketapavdrivstoffellerjolle/ekstramotor.Kaskomotorskadealeneavforurensetdrivstoffunntatt.','body')
r(kp,'Frost/is','unntak/carveout','Frostogis/følgeskadeunntatt;betaltopplaghostredjepartsviktboblehavndekkes;Plusslandstrømtilleggunntak.','body')
r(kp,'Fysisk skade','unntak','Slitasje/gradvisråtekorrosjontæringtretthet,garanti,reparasjonsverditap,seilalene;Kaskovarmgangallcauses.','body')
r(pl,'Frost','landstrøm','Skadevedvarmekildesviktsomfølgeavbruddilandstrømbetingetcovered.','4')
r(pl,'Tæring','særutvidelse','Ekstraordinærtæringoppståttmaksimaltettår.','4')
r(pl,'Motorskade','komponenter','Hovedmotor(er),drivverk/drivlinje,plutseliguforutsettvarmegangogannenplutseliguforutsettskade. Ikkejolle/ekstramotor.','4')
r(pl,'Motorskade','alderskonflikt','Bevis1førstehovedforfalletter10år;dekning4unntarover10år;webframtil10. Ikkevilkårliglikestill.','1,4')
r(pl,'Motorskade','aldersfradrag','Etter1årfrakjøptny:5%nyprisprpåbegyntår,max50%;motor/gir/drevfabrikknyforhandleralder.','17')
r(pl,'Motorskade','montering','Demonteringbetales;nymotormonteringinntil50kinkl nødvendigombygging.','17')
r(pl,'Motorskade','unntak','Feilbruk/uforsvarligbelastning/material-konstruksjonsfeil/svak-konstruksjon/feilmontering/garantiogreklamasjon.','4')
r(pl,'Motorskade','sikkerhet','Minstettdrivstoffilterskiftesårlig;produsentbruk/vedlikehold/utrustningdokumentert;ingenHKendring.','1')
r(pl,'Feriegaranti','sum/varighet','1500daginntil14;etterdekketskadebåtenikkebrukbartilplanlagtformål.','4')
r(pl,'Opplagsutstyr','omfang/sum','Krybbe,presenning,stativ;webutenmakssum;Kasko/Delkaskounntatt.','4;webopplagsutstyr')
r(pl,'Totalskade','terskel','Båtog/ellermotortaptellerreparasjonskost>60%tilsvarendelisteprisimportørpås kadetidspunkt.','17')
r(pl,'Totalskade','alder/basis','Inntil3årfrabåtog/ellermotorkjøptny;ikkealderfraførsteregistreringellersammetidbåt/motor.','17')
r(pl,'Totalskade','oppgjør','Nytilsvarendemodellårgangutstyrellerkontantselskapetspris;ikkeubegrensethvorvildetaljhandel.','17')
r(all,'Reparasjon','grunnlag','Likeverdige deler/forbedringsfradrag/totalcapforsikringssum;ingenfradragformast/rigg.','settlement')
r(all,'Elektronikk','aldersfradrag','Etter5år10%prpåbegyntårmax80.','settlement')
r(all,'Tap/totalskade','markedsverdi','Markedsverdifabrikat/type/år/standoppadbegrensetforsikringssum;Plussnygaranti særregel.','settlement')
r(all,'Ansvar','sum/egenandel','Person3 020 000SDR,ting1 510 000SDR;0egenandelbevis.','liability;1')
r(all,'Ansvar','omfang','Eier/rettmessigbrukerEuropaperson/ting/formue;vrakfjerningsjenerende/skjemmende;passasjeransvarinntekt<=50kår,sjølovensbegrensning.','liability')
r(all,'Ansvar','unntak','Yrke/næring,nærfamilie/leide-lånte-transporterte-forvarteting,kontrakt,bøter,gradvisforurensning/fukt/forsett.','liability')
r(all,'Ulykke','sum/egenandel','100kdød/500k100%invaliditet/15kbehandling;0egenandel.','1')
r(all,'Ulykke','person/trigger','Fører/passasjerrettmessigombordellervedbåtnårbåtdirekteårsak;plutseligytre+fall/vridning/bruddspesifikkeutvidelser.','accident')
r(all,'Ulykke','behandling','Inntil2år;offentligleg e/sykehus,fysio/kiro/tann/legerekvirertalternal medisiner/proteser/reise/opptrening;ikkedobbeltoppgjør.','accident')
r(all,'Ulykke','død/invaliditetsbegrensninger','Dødinnen1år,50khvisingenforsørgetektefellebarnforeldre;invaliditetproporsjonal,3årvurdering,multiplepeoplemax1m,ingeninvaliditetveddød1år.','accident')
r(all,'Ulykke','unntak','Sykdommedvirkning/psykiskalene/tyggetann/privateklinikker/slåssing/ulovlig/jordskjelvNorgeogdiagnosescope.','accident')
r(all,'Rettshjelp','sum/egenandel/geografi','100k/økonomiskinteresse,4k+20%;Mekle0;EUROPAforbåtikkenorden.WEBegendelavsnittsier0i konfliktmedFAQogfull.','legal')
r(all,'Rettshjelp','tvist/sumstruktur','Eierbrukerfører/salg/pretakeoverbåttvist;multipleparts100/250/500/750k1m;40%expert,groupdispute20k500k.','legal')
r(all,'Rettshjelp','Mekle','Alternativupartiskmekling,n oownlawyercost;kanavslutteogbeholdrettshjelp.','legal')
r(all,'Rettshjelp','unntak','Yrke/erverv/straff/familiearv/inkasso/gjeld/annenfast eiendomførretts tvistutgifter,ankegebyr/tilkjentkost. HTUplussminusinternkonfliktmedlavbåtrelevans.','legal')
r(all,'Vilkår','kundebevis','Offentligsammenligningsmalikkekundebevis;eksempelsummer/ikkevalgtmåikkebliautomatiskavtale.','Vilkår','product')
r(all,'Registrering','tegning','<60kkanuten;60–500kutenregisterkreverskrogmotornr;>500kregistrertSmåbåt/Securmark/NOR.','FAQregistrering','product')
r(all,'Objekttyper','valg','Kajakk/kano/vannscooterDelkasko/Kasko;ingenautomatiskPlussellerallebåtspesifikkeytelserpåslikvariant.','FAQkajakk','product')
# Shared exact general pages already read in prior completed reviews, type scope retained.
prior={int(q['id'][-3:]):q for q in load('gjensidige-bil-independent-inventory.json')['rules']}
for n in [70,71,72,73]:
 q=prior[n];r(all,q['subject'],q['dimension'],q['value'],'general')
save('gjensidige-boat-independent-inventory.json',dict(source_first=True,catalog_values_inspected=False,rules=R,page_reuse='gjensidige-boat-page-reuse.json',all_local_contents_read=True,scope_notes='3exactlevels. PDFpageandprintedpage differ by4/6; usePDFindex. Conflictsmotor10 andlegal0 retained. No Bilinheritance.'))
print(len(R),'sourcefirst rules')
