from continue_audit import *
rows=[]
def r(scope,sub,dim,val,sp,pp=None,source='full'):
 rows.append(dict(id=f'GJ-HU-{len(rows)+1:03d}',scope=scope,subject=sub,dimension=dim,value=val,standard_pages=sp,pluss_pages=pp or sp,source=source))
r('all','Personkrets','sikrede','Forsikringstaker/husstand/barn etter folkeregisterregler, tinglyste medeier/pante-/sikkerhetsrettshavere.','3')
r('all','Forsikrede ting','bygning','Bevisbygning med fastmontert utstyr; private solceller; frittstående bygg tilogmed10kvmBTA automatisk.','3')
r('all','Forsikrede ting','utvendige rør','Utvendige ledninger/utstyr fram til spredeledning eller offentligledning; brønn/borehull selv unntatt.','3')
r('all','Hage','omfang','Inntil5dekar inkludert utvendig badekilde/basseng.','3')
r('all','Brygge','sum/årsaker','Fast brygge tilhørende bygning100k kun brann/natur; ikke flytebrygge/landgang/molo også som fundament.','3')
r('all','Bygningsobjekter','unntak','Hobbyveksthus, tank/fyrkjelmineralolje, uregistrertsidebygg over10kvm er ikke dekket.','3')
r('all','Bygging','gjenstander','Oppføring/rehabilitering/tilbygg/påbygg: materialer,brakker,lagerskur,containere påforsikringssted.','3')
r('all','Bygging','begrensninger','Tyveri materialer ute ikke dekket; snø/vindunderstorm ikke ved uferdig utvendigarbeid; Plussutelukker da også utettbygning.','4','4–5')
r('all','Brann','hendelser','Brann/lyn/eksplosjon/nedsoting/elektrisk; ikke svimerke/gnist utenbrann.','3')
r('all','Vann','hendelser','Rør/installasjon/akvarium; grunn/terrengvann mådanne vannspeil; åpning etter dekketbygning; utettvåtrom følgeskadepåtilstøtenderom.','3')
r('standard','Vann','utett bygning/våtrom','Ikke vann gjennom utettbygning, grunnfuktutenvannspeil, utettvåtrommet selv innenfor bjelkelag/stenderverk.','3')
r('pluss','Vann','utett bygning','Innvendig følgeskadevedutettbygning overbakkeplan; ikke feil/mangel/tak-veggselv; fullverdi kreves ogutett tak eldreenn50år unntatt.','3')
r('all','Tyveri','bygning','Tyveri og skade etter tyveri frabygning.','3')
r('rental','Utleie','valg/hendelser','Måståibevis:leietakersvilletskadeverk,6mndmislighold én gangperleietaker,20kutkastelse,husleietapgodkjentvarigoppholdsrom etterdekketskade.','3')
r('rental','Utleie','egenandel','10k både misligholdt husleie ogskadeverkavleietaker; ikke Innbo-regelen.','1')
r('rental','Utleie','begrensninger','Ikke rettmessig tilbakeholdtleie,merenn6mndvedhus+innbo,utgifterutovermislighold,vask/rydding/hardbruk.','3–4')
r('rental','Utleie','kontrakt/tid','Skriftligleiekontrakt meddepositum/bankgaranti,tvangsgrunnlag;varselinnen14d,14dbetalingsfrist,begjæringinnen6uker.','1,17','1,18')
r('all','Skadedyr','skade og bekjempelse','Levende mus/rotter/andreskadedyribygning;fysiskskade/svekketisolasjon/lukt avdyr.','3')
r('all','Skadedyr','avgrensninger','Ikke fredededyr/kjæledyr,forebygging,utrevetutenavtale,isolasjonutenpåvistsvekkelse eller rester/ekskrementerutenbygningsskade.','4')
r('standard','Råte/insekter','baseunntak','Standardunntar råte/soppoginsektbekjempelse/skade uten særskiltutvidelse.','4')
r('all','Naturskade','hendelser','Lovbestemtnatur8kegenandel; Standardtekst6årsaker,Plussuttrykkeligogsåflodbølge/meteoritt.','1,4')
r('all','Annenplutseligskade','omfang','Andreplutseligeuforutsetteskaderdekket; ikke baredeopplistedeårsaker.','4')
r('all','Andreunntak','årsaker','Vedlikehold/slitasje,garantibetaler,fukt/sopp,bakterier,heksesot,kosmetikk/punktertglass,tele/setning/fundamentering,materialfeil/montasje inklfølgeskade unntatt medPlussuttrykkeligeutvidelser.','3–4')
r('all','Hage/basseng/brygge','vær/dyr','Ikke dyr/insekt/frost/sjøgang/annetklima; flomlignendesituasjonlikeveldekket.','4')
r('all','Snø','glasshagestue','Snø/istyngde påhagestueogandreutestueravglassunntatt.','4')
r('all','Drensledning','årsaker','Barebrann/natur; andreårsakerunntatt.','4')
r('pluss','Håndverkerfeil våtrom','utløser/tid','Skadepåvåtrom etter material/konstruksjon/prosjektering/montasjefeil avfaglært/godkjent;oppståttforsikringstid ogkonstatertinnen10åretterarbeid.','5')
r('pluss','Håndverkerfeil våtrom','begrensninger','Ikke eget/ufaglærtarbeid,bakterier/heksesot,kosmetikk,betalingsdyktiggarantiansvarlig.','5')
r('pluss','Håndverkerfeil øvrig','utløser/tid','Følgeskaderpåbygning avfaglært/godkjent feil;oppståttitid ogkonstatertinnen10år.','5')
r('pluss','Håndverkerfeil øvrig','begrensninger','Ikke selvefeil,tilkomstutoverfølgeskadereparasjon,drensledning,eget/ufaglærtarbeid,søl/bakterier/heksesot,kosmetikk,betalingsdyktiggaranti.','5')
r('all','Rullestol','sum/frister','250k ombygging;10åretterulykke/10årettermedfødt rullestoltildeling senest20årfødsel;ikke dobbelthusinnbo eller medisinskkomplikasjon.','5')
r('all','Etter skade','utoversum','Riving/rydding/bortkjøring/deponering,prisstigning,øktvannavgift ogoffentligpåbudtillegg.','5','6')
r('all','Brukstap','egen bolig','Markedsleie for egenbebodd bolig veddekketskade/redning/blokkertadkomst;10millionmaksavtaltsum fornaturskade/blokkertadkomst.','5','6')
r('all','Offentlig påbud','unntak','Ingen omleggingutvendigevann-kloakk/renseanleggsomfølgeavlekkasje.','5','6')
r('rot','Råte','fullverdi/omfang','Fullverdibygning:materialnedbrytningavråtesopp/treødeleggendeinsekter;Standardvalgfrittnåravtalt.','6','6')
r('rot','Råte','unntak','Ikke skadeutviklingfør/etterdekning;utvendigtre/dører/vinduer/lekter/laft,blåved/svertesopp/mugg/kosmetikk,næring/landbruk,forebygging/vedlikehold.','6','6')
r('rot','Insekter','bekjempelse','Stokkmaur/husbukk/borebille/kakerlakk/veggedyr/skjeggkre/andreskadeinsekter;metodebestemmesavselskap;ikkeaktivitetfør/etterelleroppryddingdøde/preparater.','6','6')
r('rot','Råte/insekter','egenandel','Pluss6k skader,2k bekjempelse; produktside6kråte/2kskadeinsekter gir muliggrensekonfliktfysiskinsektskade.','1','1')
r('all','Ansvar','sum/sted','EierforsikreteiendomiNorden5millperhendelse/serieskade4kegenandel.','1,6–7','1,7–8')
r('all','Ansvar','tillegg','Plutseligforurensning,landbruksomsetninghøyst100k,ulønnetarbeidshjelp. Byggeansvarinklgraving/sprengningog2åretteropphørforårsaketitiden.','6','7')
r('all','Ansvar','unntak','Yrke/familie/lånte/leieting/kontrakt,gradvisforurensning/fukt,sopp/råte,styreverv,navngittekjøretøy ogdroneunntak.','6','7')
r('all','Rettshjelp','grunndimensjoner','EierforsikreteiendomNorden100k;4k+20%;0Mekle;multipart250k/500k/750k/1m,økonomiskinteressetak.','8–10','9–11')
r('all','Rettshjelp','tvistgrener','Ettersalg/førovertakelse/visse100klandbruk;husprioritetforaninnbo;gruppesøksmål20kavvist/500kfremmet,40%sakkyndig.','8–10','9–11')
r('all','Rettshjelp','unntak','Familie/yrke/tidligeregrunnlag/unndragelsemv;Mekleegenadvokatikke,oppbruddbevarerrett. HTU15kpositivogHTUunntakmotstrid.','8–10','9–11')
r('all','Helsehjelp','hvem/hvor','Husstandsomdefinert,heleverden;ikkepåstandomsykehusutgift eller akutthjelp.','11','12')
r('all','Helsehjelp','innhold','Fri allmennlegevideo24/7,1psykologvideo/person/12mnd,1fysioterapeutvideo/person/12mnd,selvhjelp,utvalgtetjenesterabatt/digitalveiviser.','11','12')
r('all','Helsehjelp','unntak','Akutt/øyeblikkelighjelpogbehandlingsutgiftersykehus/klinikkikkeomfattet.','11','12')
r('all','Generelt','materiell','Forsikringsbevisførvilkår;14dagereierskifteettervern,krig/terror/ABCtypedifferensiert.','12–13','13–14')
r('all','Generelt','administrasjon','Fornyelse/klage/opplysningsplikt/skjønn/personvern holdesutenordinæresammenligningsfacts.','12–15','13–16')
r('all','Fullverdi','vilkår','Ingenverdiøkningsfradragvedsammeformål/stedinnen5år;annetted/formålfradragforheleverdiøkning.','16','17')
r('all','Svanemerket','sum/vilkår','250kmerkostnadtotalskade nårGjensidigestårforgjenoppføringpåsammeplass/formål.','16','17')
r('all','Totalskade','terskel','Størreenn75%avgjenoppføringskostnad girretttiltotalskadeoppgjør utenrestverdifradrag;resterrevet/fjernetinnen2år.','16','17')
r('all','Førsterisiko','oppgjør','Avtaltsuminnen5år;verdiøkningover40%markedsverdifradrag;nyplass/formålallverdiøkning.','16','17')
r('all','Manglende gjenoppføring','oppgjør','Etter5år lavesteavnormaltberegnetoppgjør/verdifall;byggsomskullerivesbarebrukbarematerialer.','16–17','17–18')
r('all','Oppgjør','arbeid/form','Selskapvelgerreparasjon/gjenoppbygging/kontant/leverandør;75%arbeidsatsutenfaktura,300krøvrigtime,kontantkostnadstak.','16','17')
r('all','Oppgjør','hage/import','Planterungvekst;importvareutennorskforhandlerkjøpesuminklfrakt/toll.','16','17')
r('all','Fullverdi','underforsikring','Tilbyggmeldesinnenfornyelse;feilarealellerikkevarsletutbygging girproporsjonalprisbasertreduksjon.','2,17','2,18')
r('all','Brukstap','varighet','Normalbygginginklmyndighetsbehandling;ingenbygging3mnd;egenmarkedsleie/leidkontrakt,shortstaybareinngåttekontrakter;innspart/renteavkortes.','17','18')
r('all','Brukstap','dokumentasjon','Uten dokumenterteboutgifterannetsted begrensestil50%avgjeldendeleiepris.','17','18')
r('all','Aldersfradrag','utvendigerør','Ikkeplast/glassfiber5%perpåbegyntårfra20,max80,eldstedelbestemmer;elektriskutstyregentabell.','17','18')
r('all','Aldersfradrag','luftluftvarmepumpe','10%perpåbegyntårfra5,maks80.','17','18')
r('all','Aldersfradrag','annenVVS','Oppvarming/kjøling/ventilasjonVVS10%fra7,maks80;tilhørenderør0.','17','18')
r('all','Aldersfradrag','hvitevarer','Integrerte10%fra5,maks80;reparasjon0.','17','18')
r('all','Aldersfradrag','varmekabler/bereder','10%fra10,maks80;punktreparasjon0.','17','18')
r('all','Aldersfradrag','badekilde','Utvendigmedutstyr10%fra5,maks80.','17','18')
r('all','Aldersfradrag','fritak/beregningsbasis','Kundenfradragpåskadetobjekt+nødvendigarbeid;ingenfradragfullverditotalskade/brann/natur.','17','18')
r('all','Egenandel','fritak','Vannstopphelerørsystem,elsjekksiste5årgodkjentkontrollør+attest,skadebarealarm/overspenningsvern:ingenegenandel.','17','18')
r('smart','Smart','egenandel','Reduksjoninntil8kvedbrann/tyverinåralarmvarslerogtilkobletstasjon;ikkegenereltfritakalleskader.','17–18','18–19')
r('all','Naturskade','nytomt','Nektetgjenoppføringetterfare,ellerustabiltomt,hus/uthussomtotalskadeogtomtmarkedsverdimaks5dekar;avtalt sikringalternativ.','18','19')
r('all','Offentlig påbud','vilkår','Nødvendigedekketbygningspåbud/undersøkelse/fundamentering;ikkenyttearealtap,tidligerehjemmel,antikvarisk/urasjonell/midlertidigellerplanlagtrehabilitering;arealforhold.','18','19')
r('all','Egenandel','standard/valg','8kstandard;valg8k–20k; særansvar4k,natur8k,glass3k,rettshjelp4k+20%.','1','1')
r('all','Sikkerhet','frost/bygningsvern','Låsing,nøkler,varme;ikke-fast-beboddover3døgnstoppkran+tømming;snø/isfjernes,slukvårhøst,synligfeilutbedres;godkjenthåndverker.','1')
r('all','Fraflyttet','dekning','Etter12mndubeboddkunbrann/naturmedmindreavtalt.','2')
r('all','Bryggeutvidelse','tilvalg','IPIDtilbyrhøyerefastbryggesum;intetfastbeløpellerkundensvalgioriginalen.','2',source='ipid')
r('standard','Råteutvidelse','tilvalg','IPID/produktsidetilbyrråte/skadeinsektsutvidelseforHusStandard;eksaktbevis avgjøromfang/egenandel.','2',source='ipid')
r('all','Vann/rør','tining','Produktsidesierhjelptiltiningav utvendigerør;ingenegenbeløpsgrenseder.','Brann-, vann- og naturskader',source='product')
r('all','Helsehjelp','rabatt','Produktside15%fysiskDrDropinogutvalgtetjenester;egenvalgtbehandlingerikkeforsikringsoppgjør.','Helsehjelp24/7',source='product')
r('all','Håndverker','klageforutsetning','Produktsideklagetilhåndverkerførstinnen5år;følgeskadehvisikkereparerer/konkursinnen10år.','Skade på våtrom/Følgeskader håndverksfeil',source='product')
r('smart','Smart','tilvalgpakker','Vann/brann160krmnd;vann/brann/innbrudd359krmnd,utstyrleies,ingenbinding;seegneoppsigelsesregler.','Alarmtjenesten',source='smartpage')
r('smart','Smart','installasjon','Brann/vannselvgratisellers2050;innbruddinstallasjoninkludert;kostnadsfribytteavannetalarmogingenbetalinggamme loppsigelsestid.','Kostnadsfri installasjon',source='smartpage')
r('smart','Smart','utrykning','24/7stasjon,vektervedtilgjengelighet/adkomst;ikkegaranti ihel eNorgeellereksakttid;misbrukkanfaktureres.','6',source='smartterms')
r('smart','Smart','aktivering','Alarmtjenestenstarterførstetterkontaktprosedyre,ikkealenefakturering;kundemåvedlikeholdekontakt/utstyr.','7',source='smartterms')
r('smart','Smart','ansvarsgrense','Tjenestefeildirektetap maks100k,samsvarvilkår9;ingenhendelsesgaranti,indirekte/næring/nett-strømfeilunntatt.','9',source='smartterms')
r('smart','Smart','utstyr/sky','Utstyrleidmåreturneres;bestilteekstrakamera12månedskyellersnyavtale;ringeklokkesomkjøpesegen.','1.4,1.7,10',source='smartterms')
r('smart','Smart','oppsigelse','Ingenfristvedbortfaltbehov,1mndvedselskapsflytting;flyttingfraadresseavslutter,nyadressekreveravtaleogdekning.','8,10',source='smartterms')
r('smart','Smart','pakkeinnhold','4røykvarsler,1vannsensor,1sentral;innbruddleggersirene/kamera/panel/2magnet;andreutstyrkanvelges,egnemedlemsfordelikkeordinary.','Hva inneholder alarmtjenesten',source='smartpage')
save('gjensidige-hus-independent-inventory.json',dict(source_first=True,source_read_complete=True,rules=rows,source_files=['Hus-Standard-alminnelige-vilkar.pdf','Hus-Pluss-alminnelige-vilkar.pdf','IPID-Husforsikring-EAP01.pdf','Husforsikring-produktside.html','Hus-Smart-produktside.html','Hus-Smart-alarmvilkar.html'],reuse='gjensidige-hus-page-reuse.json; only exact normalized matches reused',notes='No onlinefreshnessclaim; HTML repeated responsive copies read, menus/admin notcatalogdimensions; full package before catalog matching.'))
print(len(rows))
