from continue_audit import *
rows=[]
def r(families,tiers,sub,dim,val,location,source='terms'):
 rows.append(dict(id=f'GJ-MB-{len(rows)+1:03d}',families=families,tiers=tiers,subject=sub,dimension=dim,value=val,location=location,source=source))
ALL=['MC','Bobil'];levels=['ansvar','delkasko','kasko','pluss'];physical=levels[1:];kas=levels[2:]
r(ALL,levels,'Produktnivå','hierarki','Alleansvar/ulykke/rettshjelp;Delkaskobranntyveriglassutstyr/løsøre/veihjelp;Kaskoutviderkollisjon/utforkjøring/velt. BobilPlussmaterielletillegg,MCingenPluss.','IPID1','ipid')
r(ALL,levels,'Ansvar','sum/egenandel','Personubegrenset,ting100mill,ingenordinæregenandel.','1')
r(ALL,levels,'Rettshjelp','sum/egenandel','100k,4k+20%,Norden;bevisogøkonomiskinteressebestemmer.','1;legal')
r(ALL,levels,'Ulykke','sum/egenandel','Død100k/invaliditet200k,ingenegenandel;fører/passasjer.','1')
r(ALL,levels,'Geografi','områder','Europa minusKosovo/Russland/Belarus;rettshjelpNorden;weboggeneralexcludeUDområder.','3;general;HTMLgeografi')
r(ALL,levels,'Personkrets','sikrede','Forsikringstaker/lovligbruker,physicalogsåregistrerteier/tinglystrett;BobilAnsvarogsåregistrerteier.','3')
r(ALL,levels,'Registrering','opphør','Kunregistrert;avsluttesautomatiskvraking/tyveri/avregistrering/salg/eierskifte/endretleasingtaker;se14d etterverngenerelt.','1;general')
r(['MC'],levels,'Ung fører','egenandel','Rabattalleover23menførermindre23:10kekstrakaskoeller10kvedkunansvar. IkkeBil15k-regel.','1')
r(ALL,levels,'Uten fører','egenandel','Trillerutenførerprivat5k,næring15k,ogsånåringenannenegenandel.','1')
r(ALL,levels,'Bruk/endring','meldeplikt','Privattilnæringstransport/tekniskendringmeldeplikt;avkortningmulig. Feilstand/årligkjørelengdeproporsjonalprisreduksjon/fraforrigehovedforfall.','2')
r(ALL,physical,'Sikkerhet','lås','Låstkjøretøy,nøklerseparat,ekstrahjulikkeåpentfellesrom,verdierinnelåstskjult.MCparkerthengerlåstmottrekk.Bobilfortelt/tilbygglukketlåst.','1')
r(ALL,levels,'Sikkerhet','dekk','Lovligmønsterdybde ogføreforhold.','1')
r(ALL,physical,'Objekt','ekstrahjul/verdier','Ettsettekstradekk/felger;kontant/verdipapir/ulovligimportikke.','3')
r(['MC'],physical,'MC sidevogn/tilhenger','omfang','MC-sidevognogMC-tilhengerincludedforsikredeting.','3')
r(ALL,physical,'Brann','hendelser/egenandel','Åpneflammer/lyn/eksplosjon;6kegenandeloffentligtemplate.','1,3')
r(ALL,physical,'Tyveri','hendelser/egenandel','Tyveri/forsøk;6kegenandeloffentligtemplate.','1,3')
r(ALL,physical,'Glass','sum/egenandel','Bruddpårute(Bobilogsåglasstak);reparasjonssum1000/egenandel0;skifteubegrenset/egenandel3000.','1,3')
r(['Bobil'],physical,'Glass','solcelle','Solcellepanelskadeikkeglass,evkasko.','3')
r(['MC'],physical,'Løsøre','sum/vilkår','5kpersonligetingilåstoppbevaringsrom,dekkethendelse.','1;HTML53–54','product')
r(['MC'],physical,'Ekstrautstyr','sum/valg','10kfastmontert/ombygging,dekkethendelse;høyeresumkanvelgesmotpris.','1;HTML55–57','product')
r(['Bobil'],physical,'Løsøre','sum/valg','Delkasko/Kasko10k,Pluss50k,dekkethendelse;høyeresumkanavtales.','1;HTML56–58','product')
r(['Bobil'],physical,'Fastmontert ekstrautstyr','sum','Ubegrensetsum,dekkethendelse;forteltkreverseparatutvidelse.','1,3')
r(['Bobil'],physical,'Tilvalg','fortelt/utleie','Fortelt,utleie,øktløsøre/ekstrautstyrmuligeutvidelser;utleiebeviseksempelikkevalgt erikkeuniverseltnei. Nivåtilgjengelighetutleie3webmarkører +basisbevis.','IPID1;HTML59–63','ipid')
r(ALL,physical,'Veihjelp','status/egenandel','750egenandel;skade/tyveri/driftsstansogfører/passasjersykdom/ulykke/død;ogsåhjemmepåweb.','1,3–4')
r(ALL,physical,'Veihjelp','tauing','Kjøretøy+henger nærmesteverksted,ogsåutelåsing;ikkeautomatiskreparasjon/deler.','3–4')
r(ALL,physical,'Veihjelp','hjemtransport/hotell','Vedpersonhendelseellertyveri/ikkereparertinnen2virkedager:hjemreise;bilrestitusjonetterreparasjon/funn. Alternativthotellrimeligtidoglokaltransport.','3–4')
r(ALL,physical,'Veihjelp','begrensninger','Maksobjektverdi;ikkeordinærereiseutgifter/reparasjon/deler/videresendt gods;billigsttransport;kanførerkjørehjemingenhjemtransport;garantiansvarunntatt.','3–4')
r(['MC'],['kasko'],'Veihjelp ferie utenforNorden','alternativt kjøretøy','Ikkereparerbarinnen2virkedager,tilnærmetsammetypekjøretøyinntil15dforfullførtferie.KunKaskoegenutvidelse.','4')
r(['Bobil'],kas,'Veihjelp ferie utenforNorden','alternativt kjøretøy','Ikkereparerbarinnen3virkedager,tilnærmetsammebilinntil15dforfullførtferie.Kasko/PlussikkeDelkasko.','4')
r(['MC'],levels,'Bane/hastighet','unntak/carveout','Banekjøring/hastighet/fritrening/roadracingunntatt;Norgeobligatoriskførerkort/førerutviklingskursansvarligarrangør/instruktør/trafikksikkerhetlovligdokumentertdeltakelseinkludert.','3')
r(['MC'],physical,'Fysisk skade','unntak','Ugodkjenttrim/tuning/software,garanti/importøransvar,verdiforringelseetterreparasjon. Kaskoogsåslitasje/gradvis/varmgang/rust/irr/tæring.','3')
r(['Bobil'],physical,'Fysisk skade','unntak','Ugodkjenttrim/tuning/software,slitasje/gradvis,garanti/reklamasjon,verdiforringelse;Kasko/Plussujevnveiovertid,frost/snøtyngde;Kaskoogsåfukt,varmgang/rust/irr/tæring.','3')
r(ALL,kas,'Kasko','omfang','Plutseligytreskade,kollisjon/utforkjøring/velt,hærverk;feilfyllingmotorskadestøttetproduktside.','3;HTMLkasko','product')
r(ALL,kas,'Kasko','kundens egenandel','Offentligtemplate8k;webkundek anvelge6k–12k;ikkeuniverselt8k.','1;HTMLogFAQ','product')
r(['MC'],['kasko'],'Ladekabel','omfang/egenandel','ElMCtyveri/ytreskade egenandel2k.','1,3')
r(['Bobil'],kas,'Skadedyr','dekning','Mus/gnagere,insekter/andre skadedyr,ogsåvinterlagring.','3;HTML72–73','product')
r(['Bobil'],kas,'Totalskade','alder/km','Kasko/Pluss inntil1årfraregistrering/inntil20kkm etterfullterms. Webunder1år;IPIDPlussutvidettotalskadeutenekstranumeric.','settlement')
r(['Bobil'],kas,'Totalskade','utløser/oppgjør','Taptellerreparasjonkostovermarkedsverdisammebil;nytilsvarendemarke/modell/utstyrellerkontantselskapetsnybilpris.','settlement')
r(['Bobil'],kas,'Totalskade','unntak','Bedriftseidinklleaseunntatt;brann/tyverikunikkebrukt-kjøptavdenneeier.','settlement')
r(['MC'],['kasko'],'Totalskade','type applicability','Fellesoppgjørsarkavgrensernyverdigarantitilperson/varebil<=3.5t ogbobil,ikkeMC;ingenutledningavMCnyverdi.','settlement')
r(['Bobil'],['pluss'],'Nøkkel','sum/egenandel','Tapt/stjålet/skadet15kegenandel1500,1skadeperforsikringsår.','1,3')
r(['Bobil'],['pluss'],'Maskinskade','alder/km','Førstehovedforfall etter15årfraregistreringeller200kkmførst;webunder15forenklingikkeendret.','1,3')
r(['Bobil'],['pluss'],'Maskinskade','komponenter','Plutseliguforutsettmotor/gir/drivakslerknuter/mellomaksler/diff/fordelingsgir/start/dynamo/styring/pumper/styringsenhet/turbo/intercooler/EGR/lambda/radiator/kjølevæskebeholder/eksosmanifold/svinghjul/AdBlueelektronikk/HUD+elektronikk. Elhybridhøyspentbatteri/lader/ACvednødkrabbemodus.','3')
r(['Bobil'],['pluss'],'Maskinskade','unntak','Clutchinklsylinderhydraulikk,unormaloljeforbrukutenbrudd,eksosanleggmenikkemanifold,katalysator/partikkelfilter;slitasje/gradvis/garanti.','3')
r(['Bobil'],['pluss'],'Maskinskade','egenandel','0–119999km10k;120000–15999914k;160000–20000018k;ingenprosent oppført.','15')
r(['Bobil'],['pluss'],'Maskinskade','service','Produsentservice/forbedringsprogramdokumentert,tidligereeierservice,egenrepkvitteringer;ingenmotoreffektendring.','1')
r(['Bobil'],['pluss'],'Fukt','alder/geometri','Vegger/tak/gulv,ikkeeldreenn15årfraproduksjon,skadekonstatertiavtaletid.','3')
r(['Bobil'],['pluss'],'Fukt','kontroll','Fuktighetskontrollutenanmerkningeravforhandler/bobilverkstedmindreenn1årførskadeoppdages. Ikke bareårligegenkontroll.','3')
r(['Bobil'],['pluss'],'Feriegaranti','sum/dager','1500dagmax14til dokumentertleiebobil/hotelltilsvarendenårplanlagtferieover6dagerikkebrukbaretterdekketskade.','4')
r(['Bobil'],['pluss'],'Feriegaranti','unntak','Ikkeutlån/utleie.','4')
r(['Bobil'],['pluss'],'Tegning','alder','Plusskankjøpesframtilåretbobilen14år;holdseparatfradekningsopphør15.','36,94','product')
r(['MC'],levels,'Sesongpris','opphør','Jan1feb1mars2apr6mai14jun15jul18aug17sep15okt8nov2des1%;årsbeløpmånedsdeltmenopphørsavregningsesong.','ansvar3,øvrig4;HTML93–95')
r(['MC'],levels,'MC-varianter','kundevalg','Lett/tung;lettfra16 medforelderforsikringhvisunder18,veteran>=30årseparatsammegrunnlevelsutenbonus. Ikkeautomatiskordinærkanoniskveteran.','143–148','product')
r(ALL,levels,'Lagring','avregistrering','Avregistreringstopperpolicyselvvedvinterlagring;egenlagringsforsikringmåavtales,ikkeforutsettinkludert.','MC109–113/Bobil156–164','product')
# Reuse only previously reviewed source rules whose actual pages are verified byte/text-identical and generic scope applies.
prior={int(q['id'][-3:]):q for q in load('gjensidige-bil-independent-inventory.json')['rules']}
for n in [42,43,44,45,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73]:
 q=prior[n];tiers=physical if n in [42,43,44,45,69] else levels
 r(ALL,tiers,q['subject'],q['dimension'],q['value'], 'settlement' if n in [42,43,44,45] else 'accident' if n in [58,59,60,61] else 'legal' if n in range(62,68) else 'bonus' if n in [68,69] else 'general')
rows[-5]['value']='Brann/tyveri/glass/veihjelp/dyr/natur/ladekabel/nøkkel/maskinskade utenbonustap bare når relevant dekning faktisk følgerproduktet; bonusregeloppfinnerikke dekning.' if rows[-5]['subject']=='Bonus' else rows[-5]['value']
# Additional source distinctions not universalized.
r(['MC'],levels,'Bonus','start','60%startbonus ogmaks10%tap produktside,eksisterendebonusoverføres;veteranutenbonus separat.','128–144','product')
r(ALL,levels,'Offentlige kilder','kundebevis','Alminneligevilkår/IPIDoffentligsammenligningsgrunnlagikkeindividuellavtale;bevisetgårforan;datoversjonikkeoppgitt.','MC164–172/Bobil192–201','product')
save('gjensidige-mc-bobil-independent-inventory.json',dict(source_first=True,catalog_values_inspected=False,rules=rows,page_reuse='gjensidige-mc-bobil-page-reuse.json',complete_contents_read=True,scope_notes='Do not inherit Bil-specificlimits. MCtotal-loss typeblock excluded. No optional selection inferred frompublictemplates. BobilPlussnewvalueIPID conflictkept. Individualsettlementsnotassessed.'))
print('Independent source rules',len(rows))
