from continue_audit import *
import re
rows=[]
def r(scope,sub,dim,val,sp,pp=None,source='full'):
 rows.append(dict(id=f'GJ-RE-{len(rows)+1:03d}',scope=scope,subject=sub,dimension=dim,value=val,standard_pages=sp,pluss_pages=pp or sp,source=source))
r('all','Reiseavtale','grunnomfang','Helårs ferie/fritids/yrkesreiser over hele verden inntil10uker, start/slutt på bostedsadresseNorge.','1,3')
r('all','Personkrets','bosted','FolkeregistrertfastNorge, minst6månederårligNorge og folketrygdhelse; ikke utvandret.','3')
r('all','Personkrets','familievalg','Enkeltperson ellerfamilie er kundensvalg; ektefelle/samboer/barn/fosterbarn under21; samboer/fosterbarn sammeadresse.','1',source='ipid')
r('all','Personkrets','barn/barnebarn','Barnunder21 uansettmedreisende/egenadresseiNorge;barne/oldebarnbarepåreisealene medforsikret.','3')
r('all','Reisested','hjemme/arbeid','Ikke hjemme/arbeids-/studiested/barnehage;studenter/vernepliktige midlertidigNorge har to bostedsadresser,Svalbardfolketrygdadressegodkjent.','3,8','3,9')
r('all','Reisestart','avtaletid','Ikke reise startetfør forsikringensstart,medmindre gyldigkontinuitetannet selskap.','3')
r('all','Geografi','krig/ekspedisjon','OffisiellUDkrig/urofraråding ikkeomfattetutenavtale;Grønlandiskryssing,Himalayaklatring/vandre/sykkelover4500m,Arktis/Antarktisspesialekspedisjonunntatt.','3')
r('all','Risikoaktiviteter','unntak/valg','Boksing,dykkdypere40m,BASEunntatt;fallskjerm/luftsportkanavtales særskilt.','3')
r('all','Generelle reiseunntak','hendelser/utgift','Ingenlete/redningsaksjon,kjøretøy/båthjemtransport,streik/konkurs/arbeidskonflikt,økonomisktaputoveropplistede,refusjonspliktandre,ulovligimport.','3')
r('all','Sikkerhet','bagasje','Tilsyn/innlåsing;sykkellåsogløstagbarGPS/batteri;ikkeinnsjekket elektronikk/smykker/kontanter/medisin/skjørevarer;forsvarligpakking.','2')
r('all','Sykdom','behandling','Uventetakuttpåreise:lege/medisin/sykehus/alvorligulykkestann ubegrenset;foreskrevetfysio/kiro/kriseterapi ognødvendigtransport3.50kr/km.','1,4')
r('all','Sykdom','godkjenning','Sykehus/alvorligulykkestann/kriseterapi/ledsager/tilkalling/hjemkalling kreverforhåndsgodkjenningforstjernemerkedeytelser.','4,8','4,9')
r('all','Sykdom','utvidet opphold/rute','Legerekvirertforlengetoppholdog innhentingavfastrute etterpålagtsengeleie/sykehus mednødvendigeutgifter.','4')
r('all','Hjemtransport','sum/alternativ','Medisinsknødvendig hjemtransport ubegrenset;dødsfalltransportellerbegravelsepåsted50k alternativ.','1,4')
r('all','Ledsager/tilkalling','personantall','Énmedreisendeledsager;alvorlig sykdom/skade gir reise ogoppholdfor2tilkalt,reisekostsomfraNorge.','4')
r('all','Hjemkalling','hendelser','Akuttalvorlig sykdom/ulykke/dødsnærfamilie ellerstor skadeegenbolig/forretningkrevertilstedeværelse.','4')
r('all','Sykdom','kjent/behandling unntak','Kjentbehandling/utredning/forverringsfareføravreise;planlagtbehandlingkomplikasjon,rus(unntakbarnunder16),kosmetikk,ordinærtann,tygging,tannkjøtt;fødseletterfullendt37uke;fortsattbehandlingmotrådadhjemtransport;privateklinikkNordenogetterhjemkomst.','4')
r('all','Telefon','sykdomssum','Telefonutgiftervedalvorligsykdom/ulykkeinntil5000.','1')
r('all','Feriekompensasjon','vilkår/dager','Ferie/fritidsreisemedplanlagtvarighettil5uker;lokallegesengeleieellerinnleggelse;fralokallegedag/innleggelsesmaks10dager;ogsåénfamiliemedlem.','4')
r('all','Feriekompensasjon','sum','20kforbetaltferie, ikke bonuspoeng/tredjepartsgaver.','1,4')
r('all','Ferieavbrudd','sum','Godkjenttidlighjemtransport/hjemkalling:Reise50k/Pluss100k,2000perdagperpersonproporsjonaltbetalteutgifter;forhåndsbetalteenkeltarrangementmedfølger.','1,5')
r('all','Ferieavbrudd','bil/båtgrunnlag','Egenbil3.50/kmogegenbåt5kr/nautiskmil kortestturretur i prepaidholiday calculation.','5')
r('all','Returreise','sum/tid','Énreturreise10ketterhjemkalling innenplanlagtperiode.','1,5')
r('all','Reisefølge','én medreisende','Enestemedreisende syk kanutløse kompmax10d/ekstraopphold/rute/hjemtransport/avbrudd;ogsåfamilieetterangittscope.','5')
r('all','Bagasje','hendelser','Tyveri/ran/skadeverk;brann/vann/natur;trafikkpåve i/vannsnøscooter,boatgrounding/collision/capsize;innsjekkettransporttap/skade;ulykkesomkreverumiddelbarlege;dyrskade.','5')
r('all','Bagasje','summer','Reise100k,Plussubegrenset;andretingpergjenstandReise20k,Pluss40k.','1,6')
r('all','Bagasje','verdifullegrense','Elektronisk/optisk/foto/data,klokker/smykker samletReise20k/Pluss40k.','1,6')
r('all','Bagasje','kontanter','KontantgavekortReise2k/Pluss5k,perfamilieReise5k/Pluss10k.','1,6')
r('all','Bagasje','lånt/pass','Lånte/leietingbraktfra hjeminkludert;pass/reisedoknyutstedelseoginnhentingforhåndsbetaltrute.','5–6')
r('all','Bagasje','unntak','Arbeidsgiverting,kjøretøy/båt/tilhenger(nonecanoekayak)/nøklerutstyr;motorklærunderbruk;smykkemetall/mynt;mistet/glemt/underslag/svindel/hittegods;konkurranseskade,husstandskadeverk,kosmetikk,fugl/insekt/egnedyr.','5')
r('all','Sykkel','sum/geografi','40k sykkel/sykkeltilhenger/småelektriskekjøretøy utenforNorge;elover25km/tunntatt;deler/tilbehørinnen sum.','1,3,5,8','1,3,5,9')
r('all','Leid sportsutstyr','sum/vilkår','10kskade/tapmeddokumentertutleierkrav;ikkeby sykkel/sparkesykkel,skadetingikkelevert,tilbehøralene.','1,6')
r('all','Mobil','hendelser','Knustskjermeller tyveri/ran/brann; ikke mistet/glemt,slitasje/kosmetikk,innhold,hittegods,arbeidstelefon,smartklokke/tabletPC.','6')
r('all','Mobil','erstatningsform','Elcare;reparert/brukt/rensettilsvarendemodellkanannenfarge;selskapvelgerreparasjon/bytte/kontant.','6,18','6,21')
r('all','Mobil','egenandel','1000standardpartner,3000pertelefon/skadeannenleverandør.','1,6,18','1,6,21')
r('all','Forsinket bagasje','sum/vilkår','Reise3k/Pluss5k nødvendige klær/utstyrkjøp/leie under dokumentertforsinkelse;ingenventetid men ikkehjemkomst.','1,6')
r('all','Forsinket transport','trigger','Minst1.5t kansellering/forsinkelsepga vær/skred/ras/tekniskmekaniskfeil/trafikkuhell/nødlanding;sittellerplanlagt;oppstått/varsletetteretappestart.','6–7')
r('all','Forsinket transport','sum/utgift','Reise20k/Pluss25k nødvendigekstratransport/overnattingtilinnhentingforhåndsbetaltpublicrute;egenbil3.50/kmkortestevei;ikkepersonellmangel/refusjonspliktreiseellerikkegjennomførtreise.','1,6')
r('pluss','Forsinket leiebil','sum/vilkår','10k endringforhåndsbetalteleieavtalenårsenthentingsomfølgeavdekkettransportforsinkelse;ikkeoppgradering.','1,6')
r('pluss','Forsinket ankomst','sum/tid','Minst8timersforsinketferie/fritidsankomst5000 forénforhåndsbetaltovernattingog/ellerenkeltarrangement.','1,7')
r('all','Evakuering','hendelser/godkjenning','Ubegrensetnødvendigeekstrakosthjemellertryggdestinasjonopptilsammekostnad;UD/lokalmyndighetanbefalerforlatepga krig/uro/terror/natur/epidemi,pandemi utenforNorge;forhåndsgodkjent;ikkeinnreiseettervarsel/situasjon.','1,7')
r('all','Evakuering','tapteferiedager','15k totalt2000/dag/personforbetalttransport/losjiproporsjonalavbruttferie.','1,7')
r('all','Avbestilling','sum','Reise50k/Plussubegrensetforhåndsbetaltreise/overnatting/leieogenkeltarrangementveddekketreiseavbestilling.','1,7–8')
r('all','Avbestilling','sykdomskrets','Akuttsykdom/ulykke/dødself,soletraveller,nærfamilie,nøkkelpersonbarnevakt/reiseleder,gruppeinntil8sammenkjøpt;datoendretplanlagtoperasjonselfspousechildren/soletravellerattestert.','7')
r('all','Avbestilling','andretrigger','Storbolig/businessskade;UDnyttfrarådingsrådpåavreisedag;naturhendelsehøyst72tfør+evakueringsanbefaling;samlivsbruddfamiliepolicy;rettsoppmøtevitne/jury/meddommer.','7–8')
r('all','Avbestilling','tid/kontinuitet','Utløsendehendelseetterhel/delbetalingføravreise;prepolicybookingbarekontinuitetfraannetselskap.','7–8')
r('all','Avbestilling','unntak','Pågåendeutredning/behandlingsvurdering,lengresykehusennforventet,fødseletter37uke,alleredeUDvarsel;reisehensiktborte,bonuspoeng,gavertilandre,faste/årligerentalfees,employerpaidbusiness/refusjoner.','7–8')
r('pluss','Leiebilegenandel','sum/krav','Ubegrensetfastavtaltegenandelvedskade/tyveri påleiebil/MCover125cm3 påénferiereisemedminsténovernatting;CDW+TP,kundenskontraktbeviserkrav.','1,8')
r('pluss','Leiebilegenandel','begrensninger','Ikkeleasing/privatutleier/NOabonnementdelingpool/serviceerstatningsbil;moped/scooter/ATV;leieutoverénferiereise;utleiersavsavn.','8')
r('all','Ansvar','sum/sted','15millperhendelse/serieskadeprivatreiseutenforNorden,bevisegenandel.','1,9–10','1,12–13')
r('all','Ansvar','leietbygning','Skadepåleiefasteiendom/hotellrominkludert;inventarunntatt;rentformuestapkanomfattes.','9–10','12–13')
r('all','Ansvar','unntak','Yrke/nærfamilie/kontrakt/bøter/lånteleieting/inventar/gradvisforurensing/fukt/sopp/kriminalitet/vissekjøretøy;elsparkutenforNorgeklassifiseresikkesom motorvogn,fritidsbåtunntakfra båtunntak.','9','12')
r('all','Rettshjelp','sum/geografi','PrivattvistutenforNorden100k;ogsåfornærmetistraffesak;begrensetøkonomiskinteresse.','1,11–13','1,14–16')
r('all','Rettshjelp','flerpart/sakkyndig','3–10parter250k,11–25500k,26–49750k,50+1m;ikkedomstolsoppnevntsakkyndig40%sum/økonomiskinteresse.','11–13','14–16')
r('all','Rettshjelp','egenandel','Reiseingenegenandel medmindreannetbevis;Mekle0;ikkegenerell4k+20regelutenreiseforrang. Reisebevisstandard1000/Pluss0.','1,13','1,16')
r('all','Rettshjelp','unntak/HTU','Mekleegenadvokatikke;familie/yrke/eiendomutenforNorden/tidligeregrunnlagogøvrigematerielleunntak. HTU15kpositivogetterfølgendeHTUunntak måregistreres konflikt.','11–12','14–15')
r('pluss','Ulykke','omfang','Pluss24/7 ogsåhjemme;varigmedisinskinvaliditet/død/behandlingetterhjemkomst.','1,3,8,10')
r('pluss','Ulykke','voksensummer','Vokseninvaliditet300k/død100k/behandlingetterhjemkomstinkl tann15k.','1')
r('pluss','Ulykke','barnsummer','Barnunder21 invaliditet500k/død100k/behandling25k.','8')
r('pluss','Ulykke','behandlingstid','2åretterulykke;barnunder21 utsatttannbehandlingtilutgangenåret25 hvisikkeoffentligbetalt.','8')
r('pluss','Ulykke','hendelsesdefinisjon','Plutseliguforutsettytrefysiskulykke;ogsåikkesykdomsfall,kne/ankelvridning,oppregnedebruddhard/feilhopplanding;psykiskskadebarenårfysiskvarigdekning.','10')
r('pluss','Ulykke','begrensninger','Ingen lisensidrett,slagsmål/forbrytelse,dykk>40/boksing/BASE;sykdom/diagnoseunntak,smitte,medisinskekomplikasjoner,tyggetann,privatesykehus.','8,10')
r('pluss','Ulykke','invaliditet/dødsfrist','Dødinnen1år;ingeninvaliditetveddødinnen1år;delvisinvaliditetproporsjonal,max100%,endeligstatusetter3år;tidligerefunksjonstap/sykdommedvirkningavkortes.','11')
r('all','Aldersfradrag','elektronisk/optisk','Foto/video/data/annet elektroniskoptisk10%perår.','18','21')
r('all','Aldersfradrag','mobil','20%forhvertpåbegyntår fra1år.','18','21')
r('all','Aldersfradrag','klokke/nettbrett','Smart/aktivitetsklokke/tablet20%perår.','18','21')
r('all','Aldersfradrag','klær/sport/briller','10%perår.','18','21')
r('all','Aldersfradrag','sykkel','20%perårfradetåretsykkeler5år.','18','21')
r('all','Aldersfradrag','maks/annet','Maks80%;annetbagasje etterbrukstid/slitasje,bruktkjøpbruktpris/arvetmarkedsverdi.','18','21')
r('all','Generelt','krig/katastrofe','Alleredeiområdenårkrigutbryterinntil6uker;reiseunntatt1mrdterrorcap;atom500millallekunderprhendelse;jordskjelv/vulkanreiseomfattet.','15','18')
r('all','Administrasjon','vilkår','Bevisforrang;årsfornyelse,oppgjør/klage/personvern/skadebehandling beholdesutenordinæreproduktdimensjoner.','14–18','17–21')
r('duration','Reisevarighet utvidelse','periode/valg','Tilleggmåkjøpesføravreise tilhelårspolicy,gjelderénreiseinntil12mnd;kundebestemtdager,måikkeøkenormalstandard10uker.','1',source='extension')
r('duration','Reisevarighet utvidelse','maks/oppfølging','42ekstrauker(295dager) stårordrett;kanikkeforlengesunderreise;12mndén gangutenmis folketrygd ifølgeweb.42ukeraritmetikker294,ikkegjett.','33–44',source='days')
r('airsport','Luftsport tilvalg','valg/omfang','Luftsportkanavtales føravreise;fallskjermfra fly/hang/paraglide/mikro/ultralett;ikkeBASE.','1',source='extension')
r('expedition','Ekspedisjon tilvalg','valg/grenser','Himalayaover4500metterIPID;produktsideprofesjoneltarrangert4500–6000ogGrønlandiskryssing;Arktis/Antarktisunntatt.','1',source='extension')
r('war','Krigsrisiko tilvalg','valg','Innreisei krig/urofrarådetområdetkanavtalessærskiltetterindividuellvurdering.','1–2',source='extension')
r('all','Reise','overnattingskrav','Gjelderalle småogstoreturer/butikk/nabolagfraduforlaterhjemmet;overnattingikkegrunnkrav menleiebilegenandelharminsténnatt.','31,155,199,214',source='product')
r('all','Reise','tegning/alder','Kjøpfra18år,ingenøvrealderelleralderbasertlavereerstatning;studieoppholdutlandikkeReise/ReisePluss.','200–208',source='product')
r('all','Mobil','produktsideutvidelse','HTML229 inkludererknustbakside+andre skadersamtidigknustskjerm;fullPDF6 bareknustskjerm/tyveri/ran/brann.','228–230',source='product')
r('all','Feriekompensasjon','produktsidegrense','HTML59 siermindreenn5uker,fullPDF4 inntil5uker;avbruddwebviser100kutenReise50kpresisering.','58–61',source='product')
r('all','Alarmsentral','tjeneste','TravelAssistance24/7/365,legepåsted/hjemtransportveiledning/medisinskesykepleierleger;beggeprodukter.','30–44',source='alarm')
r('all','Onlinelege','tjeneste','DrDropinvideogeneralpracticepåreiseutenforNorge,helefamilievalg;ingenegenandel,åpent07–22norsktid.','30–55',source='online')
r('all','Onlinelege','avgrensning','Resept/lokalbehandlingoftealarmsentral/lokallege;akuttnødnummer/alarmsentralikkeonline;rabattfysiske/digitalehelsetjenesterikkegratisbehandling.','43–44,70–83',source='online')
r('all','Kildebruk','kundebevis','Offentligealminneligevilkår/IPIDlikeforalleogikkedelavkundensavtale;endeligbevispersonliginfoharforrang.','257–264',source='product')
B='catalog/sources/gjensidige/reise/';C=load('corpus.json');arts=[a for a in C['artifacts'] if a['path'].startswith(B)]
read=[]
for a in arts:read.append({'path':a['path'],'sha256':a['sha256'],'review':'ALL_CACHED_MATERIAL_CONTENT_READ; fullterms/PDFtables + fullHTMLsections, navigation excluded','text_cache':a['text_cache']})
save('gjensidige-reise-independent-inventory.json',dict(method='PASS1 SOURCE FIRST BEFORE READING GJENSIDIGE REISE CATALOG; publiclocalonly',rules=rows,artifacts=read,exact_page_reuse={'pluss12–21':'standard9–18; exact normalized text after footer-page removal verified'},catalog_not_consulted_for_inventory=True))
print('Saved independent rules',len(rows))
