from continue_audit import *
R=[]
def r(types,tiers,sub,dim,val,loc,src='full'):
 R.append(dict(id=f'GJ-EX-{len(R)+1:03d}',types=types,tiers=tiers,subject=sub,dimension=dim,value=val,location=loc,source=src))
ALL=['snoscooter','campingvogn','tilhenger'];levels=['ansvar','delkasko','kasko','pluss'];phy=levels[1:];kas=levels[2:]
r(ALL,levels,'Produktnivå','hierarki','Snøscooteransvar/ulykke/rettshjelp;Delkaskobranntyveriutstyr/løsøre;Kaskoytreskade. CampingDelkaskobranntyveri/veihjelp,glassIPIDkonflikt;Kaskoglass/skadedyr/ytre;Plussfukt/ferie/høyere løsøre. TilhengerDelkaskobranntyveri/redning;Kaskoytre.','1–3')
r(['snoscooter'],levels,'Ansvar','sum/egenandel','Personubegrenset,ting100mill,ordinæregenandel0.','1')
r(['snoscooter'],levels,'Ulykke','sum/egenandel','Fører/passasjerdød100k/invaliditet200k,egenandel0.','1')
r(['snoscooter'],levels,'Rettshjelp','sum/geografi/egenandel','100k,Norden,4k+20%,0Mekle.','legal')
r(['snoscooter','tilhenger'],levels,'Geografi','område','EuropaunntattKosovo/Russland/Belarus;snøscooterrettshjelpNorden. Tilhengerrettshjelpbegrensningi template betyrikkeegenrettshjelpdekning.','body')
r(['campingvogn'],phy,'Geografi','mobil/fast','MobilEuropa;faststedNorge/Sverige/Danmark/Finland. IPIDkortEuropamedunntattKosovo/Russland/Belarus.','3')
r(['snoscooter'],levels,'Ung fører','rabatt/egenandel','Hvisrabattalleførereover23ogførermindre23:10kekstrakasko/10kvedkunansvar. Web30%rabattvedalleminst23.','1')
r(ALL,levels,'Uten fører','egenandel','Trillerutenførerprivat5k,næring15k;ogsåvedingenannenegenandel.','1')
r(['snoscooter'],levels,'Registrering','opphør/lagring','Kunregistrert;avregistrering/salg/vraking/tyveriavslutter;separateavregistrertforsikringmulig,ikkebeholddekningautomatisk.','1;websommer')
r(['snoscooter'],levels,'Bane/utmark','unntak','Kjøringavsperretområde/bane/vei ogulovligutmarkikke;ikkeMCgodkjentkurscarveoututledet.','body')
r(ALL,phy,'Sikkerhet','lås','Låstkjøretøy/fortelt,tilhengerkoblingslås,nøklerseparat,ekstrahjulfast/innelåst;verdierikke synlig(nontilhenger).','1')
r(ALL,phy,'Brann/tyveri','hendelser/egenandel','Brann/lyn/eksplosjon,tyveriforsøk;snøscooter/camping6k;tilhenger4k.','1;body')
r(['snoscooter'],phy,'Løsøre','sum/condition','5ktinglåstoppbevaringsrom,skadetypevalgtdekning.','webpersonligeting','product')
r(['snoscooter'],phy,'Ekstrautstyr','sum/valg','10kfastmontert,økt sumkanavtalesIPID;hengerseparatutvidelseikkevalgtpublictemplate.','1;IPID1')
r(['snoscooter'],phy,'Veihjelp/glass','type applicability','MOT05gjelderogsåATV,menveihjelp/glasskunATV. Snøscootertransporttil/fra reparasjonunntattselvdekketskade.','IPID1;body','ipid')
r(['snoscooter'],levels,'Sesongpris','andel','Jan11,feb14,mar22,apr25,mai10,jun1,jul1,aug1,sep1,okt1,nov5,des8%;opphørsberegningikkejevn12del.','body')
r(['snoscooter'],['kasko'],'Kasko','omfang/egenandel','Plutseligytreskade;kollisjon/utforkjøring/velt/feilfyllingweb. Valg4–8k,fulltemplate8kikkestandarduniverselt.','body;webFAQ','product')
r(['snoscooter'],phy,'Fysisk skade','unntak','Trim/tuning/softwareug odkjent,garanti/reklamasjon/verditap;Kaskogradvis/varmgang/rust/irr/tæring.','body')
r(['campingvogn'],phy,'Fastmontert ekstrautstyr','sum','Ubegrensetpåalle3nivåer;forteltinngårikke,måutvides.','1,3')
r(['campingvogn'],phy,'Løsøre','sum/valg','Delkasko/Kasko10k,Pluss50k;størrekundevalgvedkontakt;ogsåtingifortelt/tilbyggvedmedforsikringogdekkethendelse.','webpersonligetingFAQ','product')
r(['campingvogn'],phy,'Fortelt/tilbygg','kundevalg/sum','Separattilvalgmedavtaltsum,publictemplate15kikkegenerellstandard;sammedekningshendelser,eksempelplatting/terrasse.','1,3;webFAQ')
r(['campingvogn'],phy,'Tilbygg','riving/rydding','Inntil10%avtilbyggverdi,begrenset10%registrertforsikringssum.','settlement')
r(['campingvogn'],phy,'Utleie','valg','Måavtalessærskilt,publicutleieikkevalgtikkeuniverseltnei;vedbet altutleieoppdateravtalen.','FAQutleie','product')
r(['campingvogn'],kas,'Glass','sum/egenandel','Rute/takluke:reparasjon1000sum/0egenandel,skifte3kegenandel. Solcellepanelikkeglassmenkasko.','1,3')
r(['campingvogn'],['delkasko'],'Glass','source conflict','IPIDnevnerDelkaskoglassmenownfull1/3barebrann/tyveri;nettsidensnivåmarkeringmåkontrolleres;ikketvingdekning.','IPID1','ipid')
r(['campingvogn'],kas,'Skadedyr','omfang','Gnagere/insekter/andreskadedyrinkludertogsåvinterlagring.','3')
r(['campingvogn'],kas,'Naturskade','hendelser/egenandel','Flom/storm/skredomfattetviautvidelseytreskade;flom20kegenandel;øvrigvalgtkasko6–12k,8ktemplate.','1;webnaturskade','product')
r(['campingvogn'],['delkasko'],'Naturskade','unntak','Flomogandrenaturskaderuttrykkeligunntatt.','3')
r(['campingvogn'],kas,'Kasko','omfang/egenandel','Plutseligytrepåvirkningogsåmedforsikretfortelt/tilbygg;egenandelkundens6–12kweb.','3;FAQ','product')
r(['campingvogn'],phy,'Fysisk skade','unntak','Slitasje/gradvis,garanti,verditap;KaskoPlussujevnvei,ustabilgrunnsetning/frost/snøtyngde;Kaskoogsåfukt/varmgang/rust/irr/tæring.','3')
r(['campingvogn'],['pluss'],'Fukt','alder/condition','Vegger/tak/gulv<=15årfraproduksjon;kontrollutenanmerkningavforhandler/campingverksted<1årførskadeoppdages;konstatertipoliseperioden.','3')
r(['campingvogn'],['pluss'],'Feriegaranti','sum/dager/condition','Planlagtferieover6dkanikkegjennomføresfordek ketskade;dokumentertcampingleie/hotell1500dagmax14;ikkeutlån/utleie.','3–4')
r(['campingvogn'],['pluss'],'Tegning','alder','Kankjøpesfremtilåretvognen14;separatfra15årfuktopphør.','produktnivåPluss','product')
r(['campingvogn'],phy,'Bruk','mobil/fast','Velgmobil/fast;fastvedflytting1–2gangeråret,omfangsammehendelsermengeografiforskjell;endringtilbyggmåmeldes.','FAQfaststed','product')
r(['campingvogn','tilhenger'],phy,'Ansvar','trekkvogn','Tredjepartskaderunderkjøringviabilansvar,egenhengercampingpoliseikkeansvar;IPIDcampingpåståransvar/ulykke/legalgeneriskmenfullkilderikke;konfliktikkeinheritedincluded.','FAQansvar','product')
r(['campingvogn','tilhenger'],phy,'Veihjelp','omfang/egenandel','750;skade/tyveri/driftsstans,trekkfør er/passasjerulykkesykdomdød;tauingnærmesteverkstedinklutelåsing. Campingpåveiogkjørbarførskade;webhjemhjelpkonflikt.','body')
r(['campingvogn','tilhenger'],phy,'Veihjelp','hjemtransport','Vedavbruttpersonhendelse,funnetettertyveriellerikkereparerbar2virkedager;tilhengertransport førstetterreparert/funnet.','body')
r(['campingvogn','tilhenger'],phy,'Veihjelp','begrensninger','Maksobjektverdi,ikkevanligereiseutgifter/reparasjon/deler/gods;ikketrekkvognveihjelpiannetselskap;kanfører/passasjerkjørehjemikkehjemtransport.','body')
r(['tilhenger'],phy,'Forsikret objekt','sum/dekk','Allehengertypermenikke campingviaweb;ettsettekstradekk/felger;markedsverdibegrensetkundesum,15ktemplateikkegenerelt.','1,2;settlement')
r(['tilhenger'],['kasko'],'Kasko','omfang/egenandel','Plutseligytrepåvirkning,hærverk/kollisjon/utforkjøring/velt;6koffentligtemplate,bevisbestemmer.','1,2')
r(['tilhenger'],phy,'Fysisk skade','unntak','Trim,gradvis/garanti/verditap;skadepåbatterialene;Kaskovarmgang/rustogbaneunntakmedNorgeførerkort/kurscarveout.','2')
r(['tilhenger'],phy,'Utleie','valg usikkert','Publictemplateutleieikkevalgtmeningenfullutleieutvidelse,termsavailabilityogvalgkreverbevis.','1')
r(ALL,phy,'Erstatning','oppgjør','Likeverdigdeler/markedsverdisammetypeårstand,forbedringsfradrag;kontant50%arbeid+mvaetterbetaling.','settlement')
r(ALL,phy,'Utstyr','aldersfradrag','Ettermontertelektronikketter1år10%prpåbegyntårmax50.','settlement')
r(ALL,phy,'Dyrpåkjørsel','egenandel','2kreduksjonkun<=3.5t;ingensikkervektantakelse.','settlement')
r(['snoscooter','tilhenger'],phy,'Totalskadegaranti','ikke applicability','Bil1yr20kifellesarketavgrensestilperson/varebil<=3.5t/bobil,ikke disseobjektene.','settlement')
prior={int(q['id'][-3:]):q for q in load('gjensidige-bil-independent-inventory.json')['rules']}
for n in range(58,68):
 q=prior[n];r(['snoscooter'],levels,q['subject'],q['dimension'],q['value'],'accident' if n<62 else 'legal')
for n in [70,71,72,73]:
 q=prior[n];r(ALL,levels,q['subject'],q['dimension'],q['value'],'general')
save('gjensidige-extension-independent-inventory.json',dict(source_first=True,catalog_values_inspected=False,rules=R,page_reuse='gjensidige-extension-page-reuse.json',scope_notes='Exact type applicability; no ATV veilhelp/glass forsnøscooter, noBilnyverdifortrailer/snow. Publicexample choices not selection. IPIDcampingcopyerrors/conflicts retained.'))
print(len(R),'source-first rules')
