from continue_audit import *
R=[]
def r(species,component,sub,dim,val,loc,src='treatment'):
 R.append(dict(id=f'GJ-PE-{len(R)+1:03d}',species=species,component=component,subject=sub,dimension=dim,value=val,location=loc,source=src))
all=['dog','cat']
r(all,'base','Veterinær','omfang/periodetak','Sykdom/ulykke,bevisvalgtmaksperforsikringsårOGsammeskadetilfelle;nyårsresetikkegjenåpnercasegrense.','2')
r(['dog'],'base','Veterinær','sumvalg','20/30/40/50kvalg,ikke50kuniverselt.','Behandling','product')
r(['cat'],'base','Veterinær','sumvalg','Kundevelgeropptil50kårlig;ingenminimumtrinndokumentert her.','Behandling','product')
r(all,'base','Geografi','område','Heleverden.','2','ipid')
r(all,'base','Varighet','opphør','Behandlingvarerheledyretslivtiloppsagt/eierskifte;livaldersgrensegjelderikkeveterinær.','Opphør3;FAQ','product')
r(all,'base','Egenandel','formel/periode','Standardfast1300+20%restenperulykke/sykdom,ikkemedhverregning;beviskanrenprosent.','Egenandel','product')
r(['dog'],'base','Egenandel','valg','Fast2000eller3500kanvelgesforlaverepremie;20%resten.','Egenandel','product')
r(all,'base','Karens','20d/kjente','Sykdomtilstedevedtegning/første20dikkeomfattet;ogsåsumøkning/utvidelse.Eksisterendetilstandogsymptomfatterikkebaredefinitivdiagnose.','2')
r(['dog'],'base','Allergikarens','kildekonflikt','Web60dagersallergi;full2generell20dingenegen60;IPID20generisk. Separatallergiregellokaltwebdokumentertmenfullversjonukjent.','FAQ','product')
r(all,'base','Medisiner','omfang','Veterinærrekvirertmedisin/preparat/bandasje/beskyttelseveddekketskade/dokumentertjournal.','2')
r(all,'base','Allergi','sum','Allergi/atopi5kinnengrunnsum. CatIPIDlifetimecap;bevis/full5kutenegenperiodedefinisjon.','1')
r(['cat'],'base','Allergi','livstidsperiode/vilkår','IPID5kallergisumgjelderhelekattenslevetid;fullsymptomøre/hudførtegning/karenstidutelukker.','1','ipid')
r(all,'base','MR/CT','sum/periodetak','5kperårELLERskadetilfelleinngårivalgtforsikringssum.','MRogCT','product')
r(['dog'],'base','Medfødt/ledd','eligibility','HD/AD/AA/OCD/patella/shortulna/CalvéLeggPerthes/annenmedfødtkreveruavbruttvetforsikretfør4mnd,ogHDforeldreNKKfrieogegnebilderNKKavlest.','2')
r(['dog'],'base','Korsbånd','eligibility','Uavbruttvetfra før4mndELLERmin1årførskade.','2')
r(['cat'],'base','Medfødt','unntak','Medfødtemisdannelserunntatt.','2')
r(['dog'],'base','Tann','melketann/bitt','Tilbakeholdtemelketenner/bittfeil/feilstiltmedisinskproblem:kontinuitetfør4mnd;forbittstillingvetattest7uker–4mndutenanmerkning.','2')
r(['dog'],'base','Tann','karies/emalje','Karies/emaljedefekteromfattet;årligtannhelsekontroll+rensvedbehov. Tannabscessavskalling/frakturcarveout.','1–2')
r(['dog'],'base','Tann','fraktur/unntak','Ulykkesfrakturinkludert;gingivitt/stomatitt/periodontitt/tannstein/følgersamtøvrigtannikke;abscesscarveoutsep.','2')
r(['cat'],'base','Tann','fraktur/unntak','Trekkingpermanentulykkesfrakturinkludert;TR/FORL/stomatitt/gingivitt/periodontitt/tannstein/øvrigtannutelukket.','2')
r(['dog'],'base','Fysikalsk behandling','source scope','Fullakupunkturv etrekvirertinkludert;fullRehabiliteringogfysikalski5ktillegg;webfysio/kiro/akupunkturiBehandlingmenssvømme/wateroptional. Scopekonfliktikkeautomatiskallinkludert.','2–3')
r(['cat'],'base','Rehabilitering','unntak','Rehabilitering/fysikalsk/vanntreningogalternativbehandlingutelukket.','2')
r(all,'base','Avliving/kremering','sum/aldersvilkår','Dog2000tilrasensLivopphørsalder;cat1500før13år;samletinnenvalgtvet sum,erstatningsmessigdiagnose.','1–3')
r(all,'base','Keisersnitt','antall/karens','Ettlivstid;min1åruavbruttvetpåbehandlingstid. Dogogsåmin20mndalder;catingen20mndregel.','2')
r(['dog'],'base','Diagnostikk ledd/rygg','sum/selvskadenunntatt','Undersøkelsefremtildiagnose3kselvdiagnoseikkeerdekket.','1,3')
r(all,'base','Komplikasjon','carveout','Normaltikkehovedsykdomunntatt,menkastrering/sterilisering/vaksinasjoniforsikringstidkomplikasjoninkludert.','2–3')
r(['dog'],'base','Behandlingsunntak','hormon/organ','Kryptorkisme/innbiltsvangerskap/hormonubalanse/navlebrokk;kastrasjonforhudepilepsiatferdinnbiltdrektighetunormalløpjur/cyster/CEHutelukket.','2')
r(['cat'],'base','Behandlingsunntak','organ','Kryptorkisme/navlebrokkutelukket.','2')
r(all,'base','Andre unntak','materielle','Forebyggende/rutine/atferd/aggressivitet/ulovligimport;reise/diettfôr/oljesjampo/gebyrattest,alternativbehandlingutelukket.','2–3')
r(all,'base','Online veterinær','service','FirstVetubegrensetvideokonsultasjon0egenandel;diagnose/råd/henvisning.','Onlineveterinær','product')
r(all,'base','Obduksjon','sum/krav','Nødvendigobduksjonvedusikkerdiagnoseinnt il1500;utenobduksjonkandekningbortfalle;veterinærattest.','settlement')
r(all,'base','Direkteoppgjør','service/egenkostnad','Vetkanvanligvisordnedirekteoppgjør,kundebetaleregenandelogevveterinæradmin gebyrselv.','FAQ','product')
r(all,'base','Tegning','aldersvindu','Dogfra5ukertil7år;catfra5ukertil10år. Ikkeopphørsalder.','FAQ','product')
r(['dog'],'rehab','Rehabilitering','optional/grense','ValgfritilleggvedBehandling;5kperår/skadetilfelleinnenvetmaks,etterdekketskade.','IPID1;webRehabilitering','ipid')
r(['dog'],'rehab','Rehabilitering','frist/sted','Måfullføres3mndettervetforeskrivelsepåklinikkellervethenviststed.','8')
r(all,'life','Liv','død/tyveri','Død/avlivningdyrevelferdvedulykke/sykdom;dogtyveri/bortkomst;catbaretyveriinnbruddbygning,bortkomstunntatt.','2','life')
r(all,'life','Liv','sum/egenandel','Kundevalgtlivsum;0egenandel;ikkeautomatiskdelavBehandling.','1','life')
r(all,'life','Liv','karens/tilstand','Sykdomførstart/første20dogsumøkning/utvidelse;medfødtdogeligibilityfør4mndmv,catmedfødtunntatt;dyrevelferdattest.','2','life')
r(['dog'],'life','Liv','opphør/raser','Hovedforfallåret8storeliste/12småliste/10øvrige;eksakteraserogblandinghøydeitilknyttettabell.Kundensrasemåavklares.','2–3','life')
r(['cat'],'life','Liv','opphør','Hovedforfallåret13;ikkefødselsdag.','2','life')
r(['dog'],'life','Liv','aldersfradrag','Fraforfallåret5store/9små/7øvrige:20%årlig,minsum1500. Ikkealdersfradragpåvet.','8;webraselister','life')
r(['cat'],'life','Liv','aldersfradrag','Fraforfallåret10:20%årlig,minsum1500.','7','life')
r(all,'life','Tyveri/bortkomst','venteperiode','Politimelding/etterlysning;minimum3mndetterregistrertkrav.Vedgjenfinnbetalingtilbakecatuttrykkelig.','settlement','life')
r(all,'use','Bruk','dependency','OptionalBrukleggestilLiv;ikkeegenvalgfriBehandlingautomatisk.','Liv/Bruk','product')
r(all,'use','Bruk','tap/avl','Livsvarigtapinnenforsikretbruk;avldokumentert100%fysiskmistetevne,hannfarmin1kull2år,hunnnormalfødselmin1kull2år.','2','life')
r(['dog'],'use','Bruk','arbeidshund','Jakt/gjeting/tjeneste:trent/regelmessigbrukt/min50%funksjonstap,utredetbehandletrehabiliterttilstrekkelig.','2','life')
r(all,'use','Bruk','opphør','Dogforfallåret8;catforfallåret10.','dog3/cat2','life')
r(all,'use','Bruk','gjenverdi','Utbetalingsumminusgjenverdiminst5k;Livsumreduserestilgjenverdi.','settlement','life')
r(all,'life','Liv','dokumentasjonterskel','Dog>30k/cat>20kkrevervetattest/verdidokument/IDmerking.','FAQ','product')
r(all,'other','Kull','separat produkt','Valp6k/5–12uker,kitten6k/5–15uker,morpåGjensidige;min1000eller20%perunge;kjøpførfødsel. Egetproduktutenfornåværendekatalog,ikketvingbase.','Kull','product')
r(all,'base','Sikkerhet','tilsyn/forebyggende','Vaksine/tannårlig/transportvarmsolbil/vetstraks,korrektrase;dogikkebundettilbil/utentilsyn.','1')
r(all,'base','Definisjoner','skadetid/sammesykdom','Discoverytime,alleutgifterforsammesykdomsammesak;frisktikkekroniskvet12mndellerdiagnoseuten symptomer.','3')
r(all,'base','Administrativt','bevis/klage','Årsvilkår/frister/bevisprioritetadmin;offentligeeksemplerikkekundebevis.','1,general')
save('gjensidige-pet-independent-inventory.json',dict(source_first=True,catalog_values_inspected=False,rules=R,page_reuse='gjensidige-pet-page-reuse.json',all_source_contents_read=True,scope_notes='Treatment2products plus optionalLiv/Bruk/Rehab, separatekullnotinvented. Exactdog/catdifferences preserved. Generalsharedpage textverified.'))
print(len(R),'independent rules')
