from continue_audit import save
R=[]
def r(scope,sub,dim,val,loc,src='terms'):
 R.append(dict(id=f'IF-BO-{len(R)+1:03d}',scope=scope,subject=sub,dimension=dim,value=val,location=loc,source=src))
r('all','Sikrede','bosted/eierskifte','Bosatt Norge;14 dagers ny eier ved eierskifte hvis ikke annen forsikring;panthaver krever bekreftelse.','2 §1')
r('all','Geografi','radius/overfart','Europeiske farvann inntil200NMfra fastlandets grunnlinje;overfart Svalbard/Island/UK/Madeira/Azorene/Kanariøyene;Svalbard sør for Nordre Isfjorden nasjonalpark.','2 §2')
r('all','Bruk','transport/regatta','Opplag/sjøsetting/opptak og transport land/vann samt seilregatta omfattet;rettshjelp Norden.','2 §2')
r('all','Sum','kundevalg','Båt/motor/seil/utstyr innen avtalt markedsverdisum;verdiendringer må meldes.','2–3 §3.1/3.3')
r('all','Sikkerhetsutstyr','sum','Sikkerhets- og redningsutstyr utenfor forsikringssummen.','2 §3.1')
r('lower','Bagasje','sum','Midlertidig bagasje50k/skadetilfelle;andres bagasje bare resterende etter sikredes.','3 §3.1')
r('lower','Opplagsutstyr','sum','50ksamlet/skadetilfelle.','3 §3.1')
r('all','Jolle','grenser','Hovedbåt>18fot;jolle<=12fot,påhengsmotor<=15hk,samletverdi<=50k. IPIDtilordnerKasko,mens§3.1erutenproduktforbehold.','3 §3.1')
r('all','Ting','unntak','Ikke utvendige fortøyninger/penger/verdipapirer/smykker/kunst/antikviteter/forbruksvarer.','3 §3.2')
r('all','Ansvar/rettshjelp/ulykke','avtale','Grunnkapitler gjelder når avtalt;IPIDfamilien Delkasko inkluderer alle tre.','3 §4.1;IPID1')
r('all','Brann/theft','status/utløser','Brann/lynnedslag/eksplosjon;tyveri og hærverk følger Delkasko og høyere.','3 §4.2')
r('upper','Kasko','utløser','Grunnstøting/sammenstøt/synking/kantring/mast- og bombrott/feilfylling/annenplutseligytrepåvirkning.','3–4 §4.3')
r('upper','Grunnstøting','undersøkelse','Undersøkelse av skrog etter grunnstøting dekkes også uten påvist skade;0egenandel.','4 §4.4;14 §7')
r('all','Transport','skadetilfelle','Transport til nærmeste verksted og nødvendig midlertidig reparasjon etter dekningsmessig skade.','4 §4.5')
r('all','Bergelønn','sum/trigger','Delkasko/Kasko etter de respektive forsikrede farer.','4 §4.6')
r('all','Vrakfjerning','sum/trigger','Offentlig pålegg etter dekningsmessig skade;10%avforsikringssum.','4 §4.7')
r('upper','Assistanse','utløser','Slep til nærmeste trygge havn når uforutsett hendelse stopper videre seilas;forhåndsgodkjenning fra If.','4 §4.8;14 §7.1.5')
r('motor','Motor/gir','tilvalg','Valgfritt sammen med Kasko,ikke automatisk inkludert i Super.','4 §4.9;IPID1')
r('motor','Motor/gir','komponenter','Motorblokk/bevegelige deler/topplokk/manifold/turbo/kompressor/kjøling/innsprøyting/start/dynamo/servo/tilt/hydraulikk/ECU;gear/propell/vannjet/aksel/clutch/lameller.','5 §4.9.1')
r('motor','Motor/gir','opphørsalder','Motor/gir/drev ikke eldre enn15år;aldersberegning fra1januar etter kjøptny.','5 §4.9.2;6 §4.9.5')
r('motor','Motor/gir','unntak','Ikke garantiforpliktelse som faktisk oppfylles,konstruksjon/materialtretthet/råte/korrosjon/frost/vær/udeklarertimport/økonomisktidstap.','5 §4.9.2')
r('motor','Motor/gir','vedlikehold','Årlig olje/filter/timingbelt og dokumentert maritimt elektrisk arbeid;Ifkontakt før reparasjon.','5–6 §4.9.3–4')
r('motor','Motor/gir','egenandel','Tilogmed5år4k;tilogmed10år8k;11år10%,12år20%,13år30%,14år40%,15år50%,alle prosent minst8k.','6 §4.9.5')
r('motor','Motor/gir','oppgjør','Maks gjenanskaffelsesverdi før skade;egenandel trekkes av verdi,og unormal slitasje kan gi fradrag.','6 §4.9.4–6')
r('super','Super','tilvalgstruktur','Super er valgfri utvidelse sammen med Kasko.','6 §4.10')
r('super','Bagasje','sum','Ubegrenset,øvrige delkaskofarer/§3.1rammer består.','6 §4.10.1')
r('super','Ferieavbrudd','dag/sesong','2k/daginntil21dager,1mai–31august;planlagt båtreise hindres av dekningsmessig brann/tyveri/kaskoskade som gjør båten sjøudyktig.','7 §4.10.2')
r('super','Reise/henting','omfang','Hjem-/videre billigste reise for fører/passasjerer,ekstra overnatting;henting reparert båt til hjemmehavn.','7 §4.10.3–4')
r('super','Totalskadegaranti','alder/form','Inntil3år siden første gang solgt ny;egen kjøpspris eller høyere gjenanskaffelsesverdi,maks avtalt sum;rettsum ved start/kontrakt/førstesalg dokumenteres.','7 §4.10.5')
r('super','Opplagsutstyr','sum/egenandel','Ubegrenset,sumunntaket erstatter50k;samme egenandel som Kasko.','7 §4.10.6')
r('super','Uhell','sum/egenandel','Navigasjons-/sikkerhetsutstyr fysisk plutselig kjent hendelse;40k/gjenstand,2k/gjenstand maks4k/skadetilfelle.','7 §4.10.7')
r('super','Uhell','tingunntak','IkkePC/mobil/nettbrett/data/programvare.','7 §4.10.7')
r('all','Skade','hovedunntak','Ikke konstruksjon/slitasje/tretthet/råte/korrosjon;motorskade alene uten særskilt fare;varmkjøring uansett årsak;snø/is/frost/vær.','8 §5.1')
r('all','Is','unntaksunntak','Iskontakt likevel dekket i boblehavn drevet av marina/båtforening.','8 §5.1')
r('all','Seil/bagasje','avgrensning','Seilalene vind ikke dekket;løstutstyr/bagasje under Kasko bare navngitte båtfarer,ikke enhverplutseligytrehendelse.','8 §5.1')
r('all','Utleie/bruk','vilkår','Ikke motorregatta/speedrace/trening/erverv/utleie,med mindre utleieavtale fremgår av bevis.','8 §5.2')
r('all','Motor/risko','kundevalg','Endret motorstyrke/andre risikoforhold må meldes;forholdsmessig erstatning eller ingen om ny risiko ikke ville blitt forsikret.','9 §5.3')
r('all','Sikkerhet','vinter/vedlikehold','Ved sjøligge1nov–31mars steng bunnkraner når ubrukt;jevnlig vedlikehold og årlig bensinfilter;ikke automatisk vinterforbud.','10 §5.4')
r('all','Sikkerhet','tyveri','Småbåt<=12fot sikres;utenbordsmotor boltet/låst,avmontert innelåst;tilhenger låses og løstutstyr innelåses.','10–11 §5.4')
r('all','Oppgjør','form/slitasje','Reparasjon eller tilsvarende markedsverdi før skade innen avtalt sum;fradrag forbedring/alder/bruk,ikke estetisk likhet.','11–13 §6')
r('all','Oppgjør','arbeid/mva','Ikke verkstedarbeid50%arbeidskost;MVA bare dokumentert betalt.','12 §6.1')
r('all','Mast/bom','totalskade','Ved totalskade på mast/bom gjøres ikke aldersfradrag.','12 §6.2.1')
r('all','Ny båt','alder/skadegrad/form','Inntil1år;reparasjon>60%nybåtinklfastutstyr;nybåtalternativ krever faktisk tilsvarende gjenkjøp/originalkjøpskontrakt,ellers markedsverdi.','12 §6.2.2')
r('all','Egenandel','struktur','Høyeste egenandel ved flere dekninger sammehendelse;ansvar0,rettshjelp4k+20%,assistanse/bergelønn0.','13 §7')
r('all','Brann/tyveri','egenandel','6k hvis ikke annet avtalt.','13 §7')
r('all','Tyveri','reduksjon','Registrert/merketbåt Småbåt/Securmark/NOR-2k,motorSecurmark-2k,trackertilalarmsentral-4k.','13 §7')
r('upper','Kasko/jolle','egenandel','Kasko6k hvisikkeannetavtalt,jolle4k.','14 §7')
r('all','Ansvar','sum/rolle','50mill/skadetilfelle;eier og rettmessig bruker/fører.','15–16 §8')
r('all','Ansvar','unntak','Kontrakt/familie/låntting/egenbåt,passasjer-/godserverv,racing,næring.','15–16 §8.2')
r('all','Ulykke','person/sum','Når avtalt,rettmessigfører/passasjer ikke betalende;ombord/ulykke direkte forårsaket av båten:invaliditet200k, død100k/person.','17–19 §9')
r('all','Ulykke','grenser','Ikke sykdom/psykisk/tann/arrunder15%;død innen2år minus invaliditet;tidligere nedsattfunksjon trekkes fra.','18–19 §9')
r('all','Rettshjelp','scope/kildehenvisning','Privat eier/fører/bruker og ettersalg;Norden;båten oppført/sikrede navngitt;generellevilkår§22 er innlemmet,eksakt2023versjon ikke identifisert i boatpakken.','2 §2;20 §10')
r('all','IPID','kunde/liggested','Ikke firmaregistrert båt eller fastliggende utenforNorden.','2','ipid')
r('lower','Jolle/opplagsutstyr','nivåkonflikt','IPID legger jolle/opplagsutstyr under Kasko,full§3.1eruten nivåforbehold. Krever avklaring for Delkasko.','1','ipid')
r('all','Administrasjon','oppgjør/plikt','Skademelding,svik,opplysninger,avgifter/månedligsesongpremie er kildebeholdt administrasjon.','14–15 §7')
save('if-boat-independent-inventory.json',dict(source_first=True,source='BÅT2-1 Feb2023 p1–21 + IPID p1–2 read in cached extraction before catalog',rules=R))
print(len(R))
