from continue_audit import save
R=[]
def r(scope,sub,dim,val,loc,src='terms'):
 R.append(dict(id=f'IF-HU-{len(R)+1:03d}',scope=scope,subject=sub,dimension=dim,value=val,location=loc,source=src))
r('all','Sikrede','eierskifte','Tinglyst eier/pant;ny eier inntil14d uten annen forsikring.','4 pkt1')
r('all','Geografi','sted','Forsikringsstedet i bevis.','4 pkt2')
r('all','Bygning','omfang','Fastmontert utstyr;utvendige ledninger til sprede/offentligledning;ikke brønn/borehull.','4 pkt3.1')
r('all','Småbygg','areal','Frittliggende<=10m² på stedet også uten bevisføring.','4 pkt3.1')
r('all','Kunst','sum','Fast utsmykning200k.','4 pkt3.1')
r('all','Hage','areal/omfang','5dekar med tilførselsvei,fasttilkoblet basseng,gjerde/flaggstang.','5 pkt3.1')
r('all','Brygge','sum/form','Egen fast trebrygge100k;ikke fellesbrygge/andre kaiarter.','5 pkt3.1')
r('all','Trygghetsgaranti','varighet','Nye bygg/tilbygg siden siste forfall med,meldeplikt før neste.','5 pkt3.1.2')
r('all','Riving/rydding','dekning','Verdiløse rester etter dekket skade.','5 pkt3.2.1')
r('all','Ubeboelig','beregning','Normal utbedringstid,rom godkjent varigopphold;markedsleie tilsvarende umøblert bolig,nødvendig dokumenterttap;uten faktiske boutgifter50%;fratrekk spart.','5 pkt3.2.2')
r('all','Påbud','omfang/unntak','Skadddel/endret teknisk krav direktefølge;grunnarbeid/byggetillatelsesbetingelse med;ikke latentpåbud/kulturminne/kjellerutgraving/størrebygg/taptareal.','5–6 pkt3.2.3;18 pkt5.5')
r('all','Prisstigning','mekanisme','SSBindeks til normal utbedring,utbetales etter reparasjon.','6 pkt3.2.4')
r('super','Boligsjekk','intervall/vilkår','Kostnadsfri Anticimex hvert4år ved forespørsel;helårsbolig,ikke næringsrom/fritid/utenbiladkomst.','6 pkt3.3')
r('super','Overvannsrapport','sum/utløser','10k én gang per eiendom ved dekket vanninntrengning/flomskade hage.','6 pkt3.4')
r('all','Brann','utløser/svi','Brann/nedsoting/eksplosjon;gnist/svi uten brann10k.','6–7 pkt4.1.1')
r('all','Elektrisk','utløser','Lyn/kortslutning/kabelbrudd; basseng bare nettleverandørdokumentert overspenning.','7 pkt4.1.2')
r('all','Natur','omfang','Lovbestemte naturhendelser Norge inklflodbølge/meteoritt og ustabilgrunn;ikke generell forebygging.','7 pkt4.2')
r('all','Snø/is','utløser','Snø/isras fra/på tak,tyngde/press.','7 pkt4.3')
r('all','Snø/is','unntak/rydding','Råte/konstruksjonsfeil,veksthus/pergola,hage/basseng/brygge,ikke-boligtak>50år unntatt;svakkonstruksjon/gammeltikke-bolig150krydding likevel.','7 pkt4.3')
r('all','Vann','utløser','Rørlekkasje/tilbakeslag/utstrømming/brudd;terrengvann krever synlig vann pågulv,ikke oppforetgulv;flomliknende hageskade.','7–8 pkt4.4')
r('all','Frosset ledning','tiningstak','50kinklmerutgift/tap for utvendig ledning uteavdrift.','8 pkt4.4')
r('upper','Vanninntrenging','takalder/utett','Overterreng;ikke selve utetthet;tak/balkong/terrasse/overgang eldre50årunntatt,eldstedelalder.','8 pkt4.4')
r('upper','Våtrom','følgeskade','Følgeskade dekket,selvevåtromikke;Basis uttrykkelig ikke tilstøtende/underliggende.','8 pkt4.4')
r('all','Vann','unntak','Takrenne/nedløp/drens/spredning,kondens/damp,sopp/råte/bakterier,slukoppforing/våttolerante gulvvegger unntatt.','8 pkt4.4')
r('all','Tyveri/skadeverk','begrensning','Påstedet;husstandsskadeverk/kosmetikkunntatt;politianmeldelse.','8 pkt4.5')
r('super','Nøkkel','sum/egenandel','5k perhendelse for låsbytte ved tapt utgangsdørnøkkel;1kegenandel.','9 pkt4.6;20 pkt5.7.5')
r('all','Annen skade','plutselig','Plutseliguforutsett annet enn nevnte farer,ikke alt fysisk tap.','9 pkt4.7')
r('all','Annen skade','unntak','Rør/tank,kondens/frost/tele/heksesot/setning/materialfeil/rust/konstruksjon,råte/organismer,isolerglassutett,maskinalene,markise/pergola,hage/basseng/brygge og innblåstsnø unntatt. Egne farer må ikke omtolkes.','9 pkt4.7')
r('all','Utleie','inkludertvilkår','Privat helårsbolig,ikke næring;skriftligavtale medfravikelse,min2mnddepositum/bankgaranti førinnflytting.','9–10 pkt4.8')
r('all','Utleie','husleietap','6mnd fra namsmannbegjæring til tilbakebesittelse+2mnd;én gang per leieavtale.','10 pkt4.8.1')
r('all','Utleie','utkastelse','20k nødvendigfravikelse.','10 pkt4.8.2')
r('all','Utleie','skadeverk/tyveri','Leietaker/gjestforsettlig skade;tyveri/underslagleietaker/husstand;ikkekosmetikk/dyr/hardellerfeilbruk.','10 pkt4.8.3–4')
r('upper','Boligtilpasning','sum/utløser','250kmin50%ulykkesinvaliditet ellerbarnfødtmedskade/sykdom,utgiftinnen5år;alternativtdokumentavgift250k vedflyttprimærbolig.','10–11 pkt4.9')
r('all','Gnagere','skade/bekjempelse','Fysiskbygningsskade,vedvarendeluktdødegnagere og bekjempelse Anticimex;bevisetsfast/fritidNordensbolig.','11 pkt4.10')
r('upper','Skadedyr','utvidelse','Fysiskbygningsskade og bekjempelse skadeinsekter;husbukksærunntak tillater varme/frysing/gass hvisnødvendig.','11 pkt4.10')
r('all','Skadedyr/gnagere','unntak','Ikke kosmetikk/isolasjonutenpåvistsvekkelse/innbo/konstruksjonsåpning/næringsangrep/ikke-boligbygg/vedlikehold/indirektetap.','11–12 pkt4.10')
r('all','Skadedyr/gnagere','tid/leverandør','Ikke aktivitetførstart/etteropphør;kontaktIfAnticimexførtiltak,ekstratransport betales utenbiladkomst.','11 pkt4.10')
r('upper','Råte/sopp','utløser','Treødeleggendesopp/råte utviklet i perioden;ingen del etteropphør.','12 pkt4.11')
r('upper','Råte/sopp','unntak','Ikke tidligeredekningsløs vannskade,mugg/blåved/bakterier,ytterdør/vindu/frilufttreverk/laftyttervegg ellerikke-boligbygg>50år.','12 pkt4.11')
r('super','Håndverker våtrom','vilkår','Konstatertfølgeskade=>selvevåtromgulvvegg ved autorisertfeil<10år,faktura;utoverreklamasjon elleransvarligkonkurs.','13 pkt4.12.1')
r('super','Håndverker følgeskade','vilkår','Autorisertfeil<10år/faktura/reklamertid;utenfor reklamasjon ellerkonkurs;ikke selvefeil/tilkomst.','13–14 pkt4.12.2')
r('super','Håndverker','fellesunntak','Ikke egen-/egetfirmaarbeid,kosmetikk,kjentførSuper,råte/bakterier,arbeid>10år,andrebetalingsdyktigesansvar;følgeskadeikkeanleggalene/utvendigrør/hage/basseng/kondens.','13–14 pkt4.12')
r('super','Håndverker','juridiskservice','Innen reklamasjon15kperforsikringsår,0egenandel,Solver,offentligsalærsats+200.','13 pkt4.12.2')
r('all','Bygging','ting/sum','Nybygg/tilbygg,materialer;egenverktøy100k,låntbrakke50k medskriftligansvar;entreprenørverktøyikke.','14 pkt4.13.1')
r('all','Bygging','risiko','Tyverilåst/bruddglass;vær/vann/snø før tettbygg unntatt;uhell/utleie/skadedyr/råte/håndverkerunntattunderoppføring.','14–15 pkt4.13.2–3')
r('all','Bygging','ansvarsutvidelse','Grave/sprengningsansvar300kting/3millperson.','15 pkt4.13.4')
r('all','Fullverdi','mekanisme','Sammeformål/sted(godkjentkommunealternativ)/eierfamilie/5år;areal-/endringsunderforsikring;beviskanhaførsterisiko.','15–16 pkt5.1')
r('all','Fullverdi','verdiøkning','40%verdiøkningfradrag ikke fastbolig;kjøpannetfradragover100%;fraflyttet markedsverditap.','16 pkt5.1.1')
r('all','Annen bolig','vilkår/tak','Totalskade=>kjøp i Norge sammeformålinnen5år,maxgjenoppføringutenmva/omsetning+100%;oppussing1millinnen2år;ingenpåbud/prisstigning;megler50k.','16–17 pkt5.1–5.2.2')
r('all','Oppgjør','kontant/estetikk','Punktreparasjon,ikke uskadetgjennomgåendeparkett/fargenyanse;arbeidutenfaktura75%avtalepris utenmva.','15 pkt5')
r('all','Hageoppgjør','vekster','Ungvanliggartnerivekst,ikkevoksentreverdi;utenreparasjonlavestkost/markedsverditap;ikkeforebygging.','17 pkt5.3')
r('all','Vannutstyr','aldersfradrag','Varmtvann/fyrkjele/pumper5%påbegyntårfra5år,max80%.','19 pkt5.7.1')
r('all','Varme/kjøling','aldersfradrag','Elektriskvarme/kjøling10%påbegyntårfra5år,max80%.','19 pkt5.7.1')
r('all','Teknisk utstyr','aldersfradrag','Varmekabel/ventilasjon/strømproduksjon10%fra10år,max80%.','19 pkt5.7.1')
r('all','Hvitevarer','aldersfradrag','Integrert10%fra5år,max80%.','19 pkt5.7.1')
r('all','Utvendig rør','aldersfradrag','Ikkeplast5%fra20år,max80%,inklgraving/eldstedel;bunnledninglikt.','19 pkt5.7.1')
r('all','Basseng/bad','aldersfradrag','10%fra2år,max80%,inklinnvendigtilknyttetelektrisk.','19 pkt5.7.1')
r('upper','Tak/våtrom','ekstrafradrag','Over30år tillegg8k utoveregenandel,eldstedel.','19 pkt5.7.2')
r('all','Innvendig rør','ekstrafradrag','Over50år tillegg8k utoveregenandel.','19 pkt5.7.2')
r('all','Egenandel','kundevalg','Bevisstyrt,høyesteénvedsammehendelse;aldersfradragfør.','19 pkt5.7')
r('all','Naturskade/vind','egenandel','Natur8k;vindunderstorm8kellerhøyereavtalt.','20 pkt5.7.3')
r('all','Frost innvendigrør','egenandel','Avtalt+8k,ikke hvisbaretining elleraldersfradrag>50årallerede.','20 pkt5.7.4')
r('all','Glass/sanitær','egenandel','Alene4k.','20 pkt5.7.6')
r('all','Utleie','egenandel','Vanligtyveriskadeverk:depositummin10k;IfUtleie3mnd leie ellerhøyere sikkerhet,førstfradrag.','20 pkt5.7.7')
r('all','Skadedyr/gnagere','egenandel','Bekjempelse2k,0råd/art/tilsendtmiddel;ikke2kallebygningsskader.','20 pkt5.7.8')
r('all','Fraflyttet','restriksjon','12mnd;uriktigbeboddopplysning=>ingenpest/råte/overterrengvann,øvrig+16kfradrag,markedsverditap;utleid/fritidbevisunntak.','21–22 pkt6.1.1')
r('all','Utleie/bruk','restriksjon','Uriktigegenbeboelse=>ikkeutleie+16køvrig;næringsutleieansvarbort,ulovligbrukhelt/delvisbort.','22 pkt6.1.2–4')
r('all','Sikkerhet','vedlikehold','Utbedre tak/lekkasje,strøm/VVSautorisert,frostvern,vannsteng>3uker/3d,halvårstilsyn/snømåking.','22–23 pkt6.3')
r('all','Ansvar','rolle/sum/egenandel','Personligeierenforsikret eiendomNorden5mill+kost,4kegenandel;utbyggingsansvarannentak.','PDF3–4 pkt2','legal')
r('all','Rettshjelp','rolle/sum/egenandel','PersonligeierNordiskforsikret eiendom;100k/250kmin3parter,4k+20%resten;etter-salg/nyboligkontinuitet.','PDF1–2 pkt1','legal')
r('all','Ansvar/rettshjelp','materielleunntak','Anneteiendom/næring/låntting/familie/gravearbeidgrunnvilkår/latenttvist/salærsatsbegrensning.','PDF1–4','legal')
r('all','Byggteknisk rådgivning','inkludert','Fagekspertråd gratis påalle3nivå.','Dekningstabell','web')
r('super','Juridisk rådgivning','timer','Solver2timerprivatrettperår,adskilt15k håndverkertvist.','Tjenester','web')
r('super','Supergaranti','periode','Minstlikegodevilkårvedflytting,2år;egenfullgarantitekst mangler i pakken.','Supergaranti','web')
r('super','Tryggere Hjem','alarm/egenandel','Ohmaalarm inkludert Super;ingenegenandel vedutløstsensorogbegrensningstiltak;fulletjenestereglerikkemed.','Fordeler','web')
r('all','Standard egenandel','nivå','WebBasis/Utvidet10k,Super8k;kundebevisforrang.','FAQ egenandel','web')
r('all','Nivånavn','kildeavvik','IPIDStandard/Super vs BGN/WebBasis/Utvidet/Super;datertanvendelighet IPIDikkeavklart. Ikke tvingStandardtilBasisutenbelegg.','1','ipid')
r('all','Generelle vilkår','pakketilhørighet','Lokalfil er2020generellevilkår medhelseforsikring ogavtaleperiode,ikkeGEN2-9. AnvendelighetforBGN1-0måbekreftes før generellepåstander.','1–6','general')
r('all','Administrasjon','prosedyre','Skjønn/klage/skademelding ogregress,ikkebehovforegenfacthverprosedyre.','20–24')
save('if-hus-independent-inventory.json',{'source_first':True,'catalog_values_inspected':False,'rules':R,'source_contents_read':['BGN1-0 all25pages','IPID2pages','full local product HTML','SV0064pages reused exacthash and property clauses checked','General file first5pages;healthsection outofscope;wrong-packagecandidate'], 'notes':'No web freshness;full exact Basis/Utvidet/Super local rules isolated;IPID level issue and generalpackage applicability unresolved.'})
print(len(R))
