from continue_audit import *
R=[]
def r(scope,sub,dim,val,loc,src='terms'):
 R.append(dict(id=f'IF-IN-{len(R)+1:03d}',scope=scope,subject=sub,dimension=dim,value=val,location=loc,source=src))
r('all','Sikrede','husstand','Bevisperson, ektefelle/samboer folkeregister og fast husstand; ikke bokollektiv. Annens ting bare skriftlig risiko-/forsikringsplikt førskade.','3 pkt1')
r('all','Forsikringssum','kundevalg','Beviset bestemmer sum. Ubegrenset gjelder bare når avtalt; ingen underforsikringsregel, men avtalte objektgrenser gjelder.','6 pkt3.4;12 pkt5.1')
r('all','Ubegrenset sum','særgrenser','500k hver for smykker/ur/gull, kunst, annet edelt metall, alkohol, enkeltgjenstand/samling. Høyere sum kan avtales. Ikke én felles500kpott.','6 pkt3.4')
r('all','Trygghetsgaranti','nyanskaffelse','Dokumentert kjøpt etter hovedforfall dekkes utover sum; må meldes før neste forfall for videre dekning.','6 pkt3.3')
r('all','Geografi','Basis','Forsikringsstedet; naturskade bare Norge. Utvidede nivåers tillegg separat.','4 pkt2')
r('upper','Geografi','utenfor hjem','Norden midlertidig inntil2år, salg/flytting, permanent lagring i annenbygning40k. Båt/kjøretøydeler/tilhenger/basseng/yrkesløsøre bare hjemme.','4 pkt2')
r('all','Penger','sum','Penger/verdipapirer10k samlet.','4 pkt3.1')
r('all','Kjøretøydeler','sum/omfang','Løse deler40k på forsikringssted; dekk/felg og registreringspliktig/>25km/tkjøretøy med fasttilbehør unntatt.','4–5 pkt3.1')
r('all','Småbåt/tilhenger','sum/omfang','Båt inntil15fot/10hk40k perbåt/motor og biltilhenger40k pertilhenger bare forsikringsstedet; egne skadetypeunntak gjelder.','4 pkt3.1')
r('all','Yrkesløsøre','sum','40k samlet på stedet, eid eller skriftlig forsikringsplikt, arbeidsgivers ting ikke uten overført eierskap.','4–5 pkt3.1')
r('all','Hobbybygg/basseng','sum','Hobbyveksthus/plasthall/lagertelt40k;frittstående basseng/bad40k bare på stedet, skadetypeunntak gjelder.','4 pkt3.1')
r('super','Integrerte hvitevarer','sum','40k per hendelse.','5 pkt3.1')
r('all','Ting unntatt','digitale/dyr/toll','Digitalvaluta/digitalkunst/dyr/ikke-tolldeklarerte ting unntatt; ikke verdiantakelser om kunden.','5 pkt3.1')
r('all','Rydding/flytting','utover sum','Nødvendig rydding/bortkjøring av rester og flytting/lagring etterdekketskade utoverforsikringssum.','5 pkt3.2')
r('all','Ubeboelig bolig','opphold','Nødvendige merutgifter ved dekket bygningsskade på folkeregistrert fastbolig; utover1uke forhåndsavtale;fratrekk sparte utgifter/husleietap.','5 pkt3.2.2')
r('baseupper','Ubeboelig bolig','hotelltak','Hotell100k, øvrigopphold ingen særskilt sumgrense.','5 pkt3.2.2')
r('super','Ubeboelig bolig','hotelltak','Ingen særskilt begrensning forhotell; utløser/faktiske rimelige merutgifterfortsatt.','5 pkt3.2.2')
r('all','Prisstigning','mekanisme','Dokumentert prisstigning til normal reparasjon/gjenkjøp, SSBindeks minus opptjente renter, utovergrunnsum.','5 pkt3.2.4')
r('all','Rekonstruksjon','sum/utgifter','Notater/tegninger/datalagre40k, ikke reise/opphold, utovergrunnsum.','5 pkt3.2.5')
r('all','Tilleggsinnredning','sum','Selvbekostet i leid/sameid bolig som ikke utbedres100k.','5 pkt3.2.6')
r('all','Brann','utløsning/unntak','Brann/plutselig nedsoting/eksplosjon, ikke svi/gnist utenbrann.','6 pkt4.1')
r('all','Elektrisk','utløsning/unntak','Kortslutning/lysbue/overslag/overspenning; basseng bare nettleverandørdokumentert overspenning.','6 pkt4.2')
r('all','Naturskade','område/unntak','Lovbestemtehendelser bare Norge; ikke tilhenger/småbåt/tingideres eller skade alene påskilt/antenne/markise.','6–7 pkt4.3')
r('all','Vann','utløsning/unntak','Plutselig utstrømming rør/tilkoblet utstyr/akvarium/slokker og vannplutseliginnibygg; ikke sopp/råte/bakterier eller kosmetiskflekk.','7 pkt4.4')
r('all','Vann','tap væske','Taptgass/vann/væske ved slik utstrømming40k.','7 pkt4.4')
r('all','Tyveri','stedgrenser','Forsikringssted: bodmedfellesadgang100k;fellesrom/garasje40k;privatute40k perhendelse.','7 pkt4.5.1')
r('all','Innbrudd','bygningssum','Bygningsskade40k.','7 pkt4.5.1')
r('all','Leietakertyveri','basisgrense','Tyveri/underslag leietaker/husstand/gjester40k, ubegrenset bare når IfUtleiekriterier oppfylt på øvrenivå; ikke utenomhjemutleie.','7 pkt4.5.1')
r('upper','Tyveri ute','steder/sykkel','Arbeidsplass/sykehjem/felles/offentlig rom/veskenapping/andresteder40k perhendelse;sykkel/elsykkel/tilhenger/barnevogn40k per objekt.','7 pkt4.5.1')
r('all','Ran','geografi','Basis på forsikringssted,Utvidet/Super også utenfor innenNorden. Politianmeldelse.','7–8 pkt4.5.2')
r('all','Skadeverk','utløsning/sum/unntak','Forsettlig;leietaker/gjest eller utenforhjem40k;ikke husstand/dyrehold/kosmetisk/hardellerfeilbruk. IfUtleie kan utvide ogsåbygningsskade.','8 pkt4.5.3')
r('all','Bygningsfølgeskade','dokumentasjon','Direktefølge av erstatningsmessig skade underhuseiers forsikring med dokumentertdekning.','8 pkt4.6')
r('super','Frysevarer','sum/utløsning','40k temperaturstigning ved strømbrudd/elektrisk fenomen, ikke enhver temperaturstigning.','8 pkt4.7')
r('upper','Glass/sanitær','unntak','Brudd, ikke kosmetiske riper/avskalling, utettisolerglass, næringstilknyttet ellerhobbyveksthus.','8 pkt4.8')
r('upper','Flytting','hendelse','Plutseligytre undertransport/inn-/utbæringtilnybolig/fritidsbolig;ikkekosmetisk.','8–9 pkt4.9')
r('upper','Uhell','utløser/geografi/tak','Annenfysisk plutseligytre skade; kjentårsak/tid oggjenstandmåfremvises;utenforforsikringssted40kperhendelse innenNorden.','9 pkt4.10')
r('upper','Uhell','ting unntatt','Leid/utleid løsøre,båt/tilhenger/arbeidsmaskin,hobbybygg,luftsport/droneibruk,innsjekketbagasjeunntatt.','9 pkt4.10')
r('upper','Uhell','årsaker unntatt','Frost/bakterier/insekter/kjæledyr/kosmetikk/slitasje/alder/snøvekt/vindunderstorm,gnagereiikke-boligbyggunntatt.','9 pkt4.10')
r('upper','Utleie','inkludert med vilkår','Privat helårsbolig,ikke næring;skriftlig avtale med tvangsfravikelse,minimum2mnddepositum innbetalt førinnflytting ellerbankgaranti.','9 pkt4.11')
r('upper','Utleie','leietap','Maks6mnd,fra begjæringnamsmann tiltilbakebesittelse+2mnd;én gangperleietaker.','10 pkt4.11.1')
r('upper','Utleie','utkastelse','Rimelig nødvendig fravikelseskostnadmaks20k.','10 pkt4.11.2')
r('upper','Utleie','egenandel og frister','3mndhusleie egenandel fratrekkes først, høyere sikkerhet ogsåfratrekk;14d varsel/14drettefrist, begjæringogIfvarslinginnen6ukerførstemislighold.','13 pkt5.4;16 pkt6.4.5')
r('upper','Utleid bolig','tyveriegenandel','Vanlig leietakertyveri/underslag/skadeverk: høyesteav10k/depositum; separat fra3mnd IfUtleie.','13 pkt5.4')
r('super','Bunad','sum/område/vilkår','500kheleverdeninkltilbehør;plutseligytre eller tapmed kjentårsak/tid;ikke slitasje/feil/gradvis/insekter/mark.','4 pkt2;10 pkt4.12')
r('super','Bunad','egenandel','500kroner.','14 pkt5.4')
r('upper','Boligtilpasning','sum/utløser','250kvedmin50%varigmedinvalidetterulykke ellerbarnfødtmedfødt skade/sykdom i perioden;dokumenterte utgifter innen5år,tilleggtiloffentligstøtte.','10 pkt4.13')
r('all','ID-tyveri','juridisk service/sum','Forebyggingvidere misbruk/fjernefeilbetalingsanmerkning;1millperhendelse,samletrelatertehandlinger. Ikkefaktiskøkonomisktaputover juridiskassist.','10–11 pkt4.14')
r('all','ID-tyveri','unntak','Næring/nærfamiliehandling/grovuaktsomfamili ehandlingunntatt;oppståttogkonstatert i forsikringstid.','11 pkt4.14')
r('upper','Skadedyr','bekjempelse/sum/sted','Anticimex150kperhendelse;gnagere/skjeggkre/veggedyr/kakerlakker i bevisets fastbolig/fritidsboligNorge;kontakt førtiltak.','11 pkt4.15')
r('upper','Skadedyr','ingen fysisk skade','Bekjempelseikkeinnboskade/døde dyr/etterlatenskaper/konstruksjonsåpning;visseuhellskaderannenregel.','11–12 pkt4.15')
r('upper','Skadedyr','tid/tiltak/tilgjengelighet','Aktivitetførstart/etteropphørikke;ingenikke-skadeinsekt/råteinsekt/gassing/varmefrysing/andreleverandør utenavtale;utenbiladkomstkundenekstratransport.','11–12 pkt4.15')
r('upper','Skadedyr','bygningstyper','Ikkenæringsrelatertangrep/garasje/låve/utebod/fellesadkomstbod/utendørs/vareparti/planter ellerforebyggendevedlikehold.','12 pkt4.15')
r('upper','Skadedyr','egenandel/service','2kbekjempelse,0rådgivning/artsbestemmelse/selvtiltakutstyrsendtavAnticimex.','13 pkt5.4')
r('all','Oppgjør','alder/bruktverdi','Lavest reparasjon/tilsvarendegjenkjøp,fradrag for alder/bruk/anvendelighet. Bruktkjøpt/arvet/gitt/ulagret/utrangertogbo bruktsalgsverdi;ikke fasttallstabell.','12 pkt5')
r('all','Sykkel','oppgjørstak','Aldri over faktisk anskaffelsespris;skiltfra40ktyverigrense.','12 pkt5')
r('all','Egenandel','standard','4kperhendelse omikkeavtaltannet;fradrag før egenandel;sammehendelseflereIfprodukter barehøyesteegenandel.','13 pkt5.4')
r('basis','Naturskade','egenandel','Basis8k;Utvidet/Super ikke detteBasisunntaket, dermedavtaltestandard4k dersomikkeannet.','13 pkt5.4')
r('super','Uhell/tyveri/ran/skadeverk','redusert egenandel','2kpergjenstand,maks4kperhendelse. Ikkeubetinget2khelehendelsen.','13 pkt5.4')
r('all','Rettshjelp','sum/egenandel','100kpertvist/250kmin3parter;4k+20%resten;boligselgertvist salærsats+200tak.','PDF2 pkt1.6–1.7','liability')
r('all','Rettshjelp','rolle/område','Innbo:privatperson,Norden;etter-salg ognyboligførinnflyttmedkontinuitet;øvrigeeiendom/motor/båt/driftunntak/carveouts.','PDF1–2 pkt1.1–1.5','liability')
r('all','Ansvar','sum/egenandel/område','Privatperson,Norden;5millperhendelse+sakskost,4kegenandel;modellfly/drone750kSDRmedvilkår.','PDF3–4 pkt2.2–2.7','liability')
r('all','Ansvar','unntak/carveouts','Lånt/leidting/familie/næring/avtaleansvar/motorunntatt;arbeidsmaskin<=10km/t<=750kgpåegengrunn ogsmåbåt<15fot/<10hk carveout;drone utenoperatørtillatelse.','PDF3 pkt2.5','liability')
r('all','Sikkerhet','vann/tyveri','Boligfravær>3uker/fritid>3d stengvann;sykkellås/ikkelaGPSigjen;verdierikkefellesbod/ikkeetterlatikjøretøy;halvårligtilsyn.','15–16 pkt6.4')
r('cycleaddon','Sykkeltillegg','tilgjengelighet','IPIDtilleggvedverdi>40k;detaljer/sumvalgikkeifullkildepakken.','1','ipid')
r('valueaddon','Høy verdi','tilgjengelighet','Tilleggforenkeltgjenstand/samling>500k;sumfraavtale,ikkeautomatiskbasis.','2','ipid')
r('super','Supergaranti','kildebegrensning','IPIDgarantertlikesåbraellerbedrevilkårvedflytting;fullgarantiregelikkeiIBO/SV006.','1','ipid')
r('all','Administrasjon','frister/prioritet','Bevisforrang,generellevilkårunntattgenerellrettshjelp erstattetSV006,politimelding/klage/skjønn;ikkeegetfaktumhverprosedyre.','3,14–18')
save('if-innbo-independent-inventory.json',dict(source_first=True,catalog_values_inspected=False,rules=R,source_contents_read=['IBO2-1 all18pages','SV006 all4physicalpages;printed2–5','IPID bothpages','GEN2-9 exactshared13pages read in prior motor checkpoint'],scope_notes='Basis/Utvidet/Super separate, no customer sum invented, coverage risk differs from thing eligibility. Generallegal23 is expressly displaced bySV006.'))
print(len(R),'rules saved')
