from continue_audit import *
R=[]
def r(types,scope,subject,dimension,value,location,source='mot'):
 R.append(dict(id=f'IF-MO-{len(R)+1:03d}',types=types,scope=scope,subject=subject,dimension=dimension,value=value,location=location,source=source))
all=['bil','mc','bobil','snøscooter','campingvogn','tilhenger']; motor=['bil','mc','bobil','snøscooter']; living=['bobil','campingvogn']
r(all,'all','Geografi','område','Europa, bare europeisk Tyrkia; Kosovo, Russland og Belarus unntatt. Rettshjelp bare Norden.','3 pkt2')
r(all,'all','Avtalevalg','individuelt bevis','Dekningsnivå, tilvalg, sum og egenandel bestemmes av bevis; kundeverdi skal ikke oppfinnes fra standardvilkåret.','2,4,18')
r(motor,'all','Ansvar','rettslig mekanisme','Ansvar etter lov på skadested; EØS bruker norsk lov når gunstigere, særregel personskade utenfor EØS. Ingen egenandel.','4 pkt4.1;19 pkt8.5.1')
r(motor,'all','Fører/passasjer','personkrets og sum','Rettmessig fører og passasjer uten betaling; 200 000 medisinsk invaliditet proporsjonal grad og 100 000 dødsfall. Bevis avklarer avtalt ulykkesdekning.','21–22 pkt11.2–11.5')
r(motor,'all','Fører/passasjer','utløsende hendelse og begrensninger','Ulykke under bruk; fører utenfor ved kjøretøy som direkte årsak. Tannskade ikke invaliditet; arr under15% unntatt; sykdomsutløst og psykisk lidelse ikke omfattet.','22 pkt11.4/11.6')
r(motor,'all','Fører/passasjer','dødsfallstid','Dødsfall må følge ulykken innen2år; tidligere invaliditetsutbetaling trekkes fra.','23–24 pkt11.7')
r(motor,'all','Rettshjelp','rolle og etteropphør','Personlig eier/rettmessig bruker/fører; økonomisk tvist bare sikret i bevis. Tvist etter salg og leasingretur kan omfattes.','24 pkt12')
r(motor,'all','Rettshjelp','sum og flerpart','100 000 per tvist; 250 000 hvis minst3parter på samme side og i vesentlig samme spørsmål. Ikke idømte saksomkostninger.','10–11 pkt23.2–23.3','general')
r(motor,'all','Rettshjelp','egenandel','4 000 +20% av overskytende; én egenandel per tvist.','19 pkt8.5.2')
r(motor,'all','Rettshjelp','materielle unntak','Ingen førerkortbeslag/straffesak som mistenkt; næringsutøvelse og eksisterende tvistegrunnlag unntatt; administrative klagemuligheter må utnyttes.','11 pkt23.5','general')
r(all,'physical','Brann/natur','utløsning','Brann må ha åpen flamme; kortslutning elektronikk/batteri først ved åpen flamme utenfor enheten. Natur i Norden: skred/storm/flom/stormflo/jordskjelv/vulkan.','4–5 pkt4.2/4.5')
r(all,'physical','Tyveri/hærverk','utløsning og underslag','Tyveri/forsøk, ikke husholdningsmedlem; forsettlige skader, ikke påkjørsel. Underslag prøvekjøring ved offentlig annonsert salg omfattet, andre underslag unntatt.','5 pkt4.3/4.4')
r(['bil','mc','bobil','campingvogn'],'physical','Glass','omfang og erstatningstak','Brudd i glass/plexi kupe/førerhus/lasterom; ikke lykter/slitasje. Utskifting maks50% av gjenanskaffelsesverdi.','5 pkt4.6')
r(['bil','mc','bobil','campingvogn'],'physical','Glass','egenandel','3 000 ved bytte;0 ved reparasjon.','19 pkt8.5.4')
r(all,'physical','Fastmontert utstyr/bagasje','sum og samlet mekanisme','40 000 samlet, maks50% av kjøretøyverdi. Høyere sum kan avtales; ordinært fabrikk-/nybilutstyr inngår som del av kjøretøy.','3 pkt3')
r(all,'physical','Utstyr/bagasje','avgrensning','Ikke penger/verdipapirer eller fast hjemmeladestasjon. Bagasje låst; verdigjenstander/data/foto/pass skal ikke etterlates.','4 pkt3;15 pkt7.2')
r(['bil','mc','bobil','campingvogn','tilhenger'],'physical','Veihjelp','utløsning','Motorstopp, startproblem, tomt/drivstoff/strøm, feilfylling, nøkkel innelåst/mistet, ekstraordinær punktering; nærmeste egnede verksted eller rimeligere nødreparasjon. Krever fremkommelig lovlig adkomst.','5–6 pkt4.7')
r(['bil','mc','bobil','campingvogn','tilhenger'],'physical','Veihjelp','hjemtransport og sum','Rimeligste hjemtransport ved ventetid over3dager/omfattende skade mv; maks50% av kjøretøyverdi. Feilfylling tanktømming maks5 000. Ikke ordinær verkstedreparasjon eller annen garanti/medlemsdekning.','6 pkt4.7')
r(['bil','mc','bobil','campingvogn'],'physical','Veihjelp','egenandel','750 kroner; ingen bonustap.','19 pkt8.5.6;20 pkt9.4')
r(all,'physical','Egenandel','standard og individuelle avvik','Brann/tyveri/hærverk/natur standard8 000; individuell/særvilkår går foran.','18–19 pkt8.5')
r(all,'kasko','Kasko','utløsning','Kollisjon/utforkjøring/velt og annen tilfeldig plutselig ytre hendelse; feilfylling, men separat maskindekning kreves for internt havari uten ytre dekket skade.','6 pkt4.8;13 pkt5')
r(all,'kasko','Kasko','egenandel og dyrepåkjørsel','Standard8 000; dyrepåkjørsel løs på vei reduserer2 000 ved straks politimelding/viltnemnd og gir ikke bonustap. Individuelt bevis går foran.','19–20 pkt8.5.5/9.4')
r(all,'physical','Skadeoppgjør','verdi og avtalt sum','Tilsvarende gjenanskaffelsesverdi før skaden; bevis sum øvre tak; ikke verdiforringelse. Kontantreparasjon fratrekker50% arbeid og moms til kvittert.','16–18 pkt8')
r(motor,'physical','Nyverdi standard','alder/km/terskel','Innen1år fra førstegangsregistrering, ikke mer enn15 000km, reparasjon over80% kjøpesum ny. Kontant-/tilsvarendeoppgjør mulig.','18 pkt8.4.2')
r(motor,'physical','Nyverdi standard','forutsetninger','Ikke leasing/drosje/trafikkskole/utleie/prøvekjennemerke/CD/tollskilt; norsk merkeforhandler gjenkjøp, original kjøpsdokumentasjon/prismekanisme, ellers gjenanskaffelsesverdi.','18 pkt8.4.2')
r(all,'physical','Viktige unntak','vær/slitasje/tuning','Ikke varme/korrosjon/slitasje/gradvis forringelse; nedbør/snøisvekt/frost/issprengning også medvirkende årsak; ikke ulovlig tuning eller lov/garanti-ansvar hos selger. Særvilkår kan utvide.','13 pkt5.2')
r(all,'all','Bruksbegrensning','bane/is/utleie','Bane unntatt bortsett fra nevnt føreropplæring/godkjent trening. Islagt vann uten offentlig merket trasé unntatt. Utleie må avtales; bobil/camping særregel separat.','14 pkt6.1')
r(motor,'all','Årlig kjørelengde/ung fører','kundevalg og konsekvens','Overskridelse avtalt kjørelengde kan redusere erstatning forholdsmessig; ukorrekt yngstealder tilsvarende eller bevisets særskilte egenandel. Ikke totalskade/maskinskade-km.','14–15 pkt6.2')
r(['bil'],'kasko','Reparasjonstrygghet','varighet/omfang','Livslang til vraking på betalt kaskokarosserireparasjon hos anvist avtaleverksted, person/varebil<=3,5tonn; mekanikk/elektronikk/batteri/slitedeler unntatt.','17 pkt8.3.7')
r(['bil','bobil'],'machine','Maskinskade','valg og terskel','Valgfri med Kasko; plutselig uforutsett skade på navngitte komponenter; skade når kjørt mer enn200 000km unntatt. Ingen motorvognalder oppgitt her.','6–9 pkt4.9')
r(['bil','bobil'],'machine','Maskinskade','komponenter','Motor/gir/kraftoverføring, høyvoltbatteri og intern lading, elektronisk styring, styring/varme/kjøling, spesifisert sikkerhet/komfort; ikke generell all-komponent-garanti.','7–8 pkt4.9.1')
r(['bil','bobil'],'machine','Maskinskade','unntak','Clutchlamell/understell/bremser/hjullager/eksos/DPF/ekstern ladekabel/slanger/ledningsnett alene/startbatteri/luftbelg unntatt; slitasje/klima/oljeforbruk/software/tuning/garanti også medvirkende årsak.','8–9 pkt4.9.2–4.9.3')
r(['bil','bobil'],'machine','Maskinskade','egenandel/fradrag','8 000 etter kilometerfradrag: før100k0%, passert100k10%,150k20%,175k30%; skade over200k ikke dekket. Fradrag per uavhengig feil.','9 pkt4.9.6')
r(['bil','bobil'],'machine','Maskinskade','vedlikehold og oppgjør','Fabrikantservice/registerreim og godkjent verksted, dokumentasjon. Ikke standard/Super nyverdioppgjør; totalskade etter gjenanskaffelsesverdi minus kilometerfradrag og egenandel.','9–10 pkt4.9.4–4.9.7')
r(['bil','bobil'],'rental','Leiebil','valg/utløsning','Valgfri med Kasko, erstatningsmessig skade/tyveri; glass alene ikke nok; ikke overlapp lov/garanti, men inntil7d forhandleransvar ellers dekningsmessig skade over egenandel.','10 pkt4.10')
r(['bil'],'rental','Leiebil','reparasjon','Inntil90dager faktisk reparasjon fra innlevering til ferdig.','10 pkt4.10.5')
r(['bil','bobil'],'rental','Leiebil','dagpris og alternativ','Tilsvarende størrelse, maks500kr/d inklmva; valgfri kontant200kr/d, normal taksert reparasjonstid maks15d.','10 pkt4.10.3–4.10.5')
r(['bil','bobil'],'rental','Leiebil','tyveri/totalskade','Fra skademelding/faktisk savntid til10d etter tilbud/avgjørelse; kontantbegrenset15d. Bobil særvilkår45d total øvre tak.','10–11 pkt4.10.5')
r(['bil','bobil'],'rental','Leiebil','maskinskade/utenfor Norden','Ved avtalt maskindekning avklaring inntil7d; hvis dekket ordinær reparasjonsperiode. Utenfor Norden ved >3dagers reparasjon eller tyveri ekstra15d utover normal avbruddstid. Bobil45d særgrense.','10 pkt4.10.1')
r(['bil','bobil'],'super','Nyverdi Super','alder/km/terskel','Skade innen3år fra registrert fabrikkny, før60 000km, reparasjon må overstige gjenanskaffelsesverdi. Ikke leaset.','11 pkt4.11.1A')
r(['bil','bobil'],'super','Nyverdi Super','gjenkjøp/tyveri','Ny samme merke/modell fra norsk merkeforhandler ellers normaloppgjør. Modell utgått siste listepris. Totaltyveri ikke gjenfunnet30d følger8.4 og ikke automatisk3år-garanti.','11 pkt4.11.1A')
r(['bil','bobil'],'super','Leasing/startleie','forholdsmessig tap','Totaltap eller totaltyveri erstatter betalt startleie forholdsmessig etter gjenstående måneder. Separat fra ny bil til eier.','11 pkt4.11.1B')
r(['bil','bobil'],'super','Uhell','barn og betingelser','Nøkkel inklparkeringsvarmerfjernkontroll mistet/stjålet/skadet med kjent tidspunkt/årsak; feil væske; ladekabel ytre skade/tyveri/hærverk, ikke fast ladestasjon.','11–12 pkt4.11.2')
r(['bil','bobil'],'super','Uhell','sum/egenandel/bonus','20 000 per skadetilfelle;1 000egenandel; intet bonustap. Overskytende kan velges ordinær Kasko med dens egenandel/bonus.','12 pkt4.11.3/4.11.6/4.11.7')
r(['bil','bobil'],'super','Parkering','sum/utløsning/egenandel','Ukjent annet kjøretøy skader parkert bil, kjent sted/tid, straks melding;20 000 per hendelse, valgt Kaskoegenandel, intet bonustap.','12 pkt4.11.4–4.11.7')
r(all,'all','Administrative bestemmelser','avtale/oppsigelse/skjønn','Premie, varsler, svik, klage, skjønn og lovvalg beholdes i kilde; ikke alle til egne sammenligningsfakta.','2,19–26;GEN3–12')
r(['mc','snøscooter'],'physical','Kjøreutstyr','omfang','Personlig hjelm/dress/hansker/støvler/ryggskinne/airbagutstyr inngår i tillegg til motorvilkåret. WebMC sier ubegrenset sum.','1 pkt1','692')
r(['mc'],'machine','Maskinskade MC','valg/eligibility','Valgfritt tillegg til Kasko bare mellomtung/tung; ikke lettMC/moped/snøscooter. Kjøp før7år fra IPID/web, opphør når8år eller mer fra særvilkår.','1–2 pkt2','692')
r(['mc'],'machine','Maskinskade MC','komponenter','Navngitte motor-/gir-/drivverks-/elMC-/motorstyrings-/varme-/ABS/TCS/GPS-komponenter. Ikke Bilens hele komfortliste.','1–2 pkt2.1','692')
r(['mc'],'machine','Maskinskade MC','egenandel/aldersfradrag','4 000 etter aldersfradrag av motor/gir/drivverk: mindre5år10%, tilogmed5år15%,6år20%,7år30%; alder fra1.januar etter nykjøpsår. Ingen egen generell kmgrense.','2 pkt2.6','692')
r(['mc'],'machine','Maskinskade MC','unntak','Slitasje/varme/klima/dårlig lagret drivstoff/software/tuning;clutchlamell/kjede/drev/belte/ramme/fjæring/brems/ekstern kabel/startbatterier unntatt. Garantiansvar likevel hvis kundekrav ikke fører frem og ellers dekket.','2 pkt2.2–2.3','692')
r(['mc'],'machine','Maskinskade MC','oppgjør','Ikke nyverdi; maks gjenanskaffelsesverdi minus aldersfradrag og egenandel, per uavhengig feil.','2–3 pkt2.5–2.7','692')
r(['mc','snøscooter'],'physical','Tyveri','låsreduksjon','FG-godkjent tilleggslås i bruk reduserer bevisegenandel2 000; utstyr låst til kjøretøy eller boltet rom.','3 pkt3/4.1','692')
r(['mc','snøscooter'],'all','Egenandel særregel','annen/ung fører og utmark','10 000 tillegg ved avvik eier-enestefører/yngstealder;ektefelle/samboer likestilt.10 000 tillegg hvis ikke dokumentert lovlig utmark/vassdrag/offentlig scooterløype.','3 pkt4.2','692')
r(['mc','snøscooter'],'all','Sesongpremie','oppsigelse','MC sommervektet/snøscooter vintervektet eksakt månedsfordeling i tabell;1/30 perdag; bytte prorata uten sesongtabell.','3–4 pkt5','692')
r(living,'physical','Tilbygg','sum og nivåspørsmål','Bygningskonstruksjon til campingvogn/bobil40 000; særvilkåret angir ikke Kasko-minimum, campingweb angir Kasko/Super, ikke Delkasko.','2 pkt1','707')
r(living,'physical','Frigjøring/transport','sum og scope','Frigjøring campingvogn fra tilbygg og transport til kjørbar vei5 000 ved dekket skade, går foran vanlig veihjelp. Ikke automatisk alle bobiltransportkostnader.','2 pkt2.1','707')
r(['campingvogn'],'physical','Stasjonær campingvogn','transport','Forsikret også frakt etter kjøp og til/fra vinterlagring; vinterlagring annet sted omfattet.','2 pkt2.2','707')
r(['bobil'],'rental','Leiebil Bobil','maks dager','Valgfritt på Kasko/Super; reparasjon/totalskade/tyveri oppad45dager, ordinære kontantregler beholdt.','2 pkt3.2','707')
r(living,'super','Fukt/vann','alder','Nyere enn15år fra produksjonsår; ikke automatisk inkluderende15år.','2 pkt3.3.1','707')
r(living,'super','Fukt/vann','intern lekkasje','Ferskvann/avløp/varmerør boenhet: ingen krav om fuktkontroll.','2 pkt3.3.1','707')
r(living,'super','Fukt/vann','annen fukt/kontroll','Andre fuktskader krever bestått kontroll hos autorisert caravanforhandler/Viking;gjelder1år etter kontroll, ny kontroll nødvendig, måleresultater og stedskisse dokumenteres.','3 pkt3.3.1','707')
r(living,'super','Fukt/vann','frost/snø','Frost/snøtyngde også som medvirkende årsak unntatt;frostsikring/avtapping/vedlikehold kreves.','3 pkt3.3.1','707')
r(living,'super','Feriegaranti','dagbeløp/varighet/utløsning','Dekket skade etter påbegynt ferietur: dokumentert alternativ overnatting/leiebil1 500perdag, resterende planlagt ferie maks15dager. Ikke fri kontantytelse.','3 pkt3.3.2','707')
r(living,'super','Utstyr/bagasje','utvidet samlet sum','Samlet100 000 i campingvogn/bobil/campingpåbygg.','3 pkt3.3.3','707')
r(living,'super','Skadedyr','scope','Uforutsett insekts-/gnagerskade på kjøretøy;utstyr/bagasje bare samtidig kjøretøyskade. Lukket ved lagring.','3 pkt3.3.4','707')
r(living,'physical','Særskilte unntak','løsøre/tilbygg/frost','Ingen tyveri løse ting fra dukfortelt, ingen montering/demonteringtilbygg, løst uhell krever samtidig kjøretøyskade, ingen frost/snø/tette isolerglassfuger/vibrasjon-vridning.','3–4 pkt4','707')
r(living,'physical','Sikkerhetskrav','tilbygg/flom','Tilbygg lukket/låst/sikret, forskriftsmessig plassering;campingvogn ikke flomutsatt.','4 pkt5','707')
r(living,'physical','Utleie','egenandel','Ikke forhåndsavtalt utleie gir10 000økt egenandel; web>10 000årsinntekt varsles; hovedvilkår utleieansvarforbehold må scopeavklares.','5 pkt6.2.1','707')
r(['bobil'],'all','Sesongpremie','oppsigelse','Måneder3/3/5/7/10/15/18/16/10/6/4/3%;1/30dag, bytte prorata uten sesongfordeling.','5 pkt7','707')
r(['tilhenger'],'physical','Tilhenger','objektverdi/bonus','Gjenanskaffelsesverdi serieutførelse+fast utstyr;bevis dekning;ingen bonus.','1 pkt1–4','709')
r(['mc'],'physical','Bagasje og utstyr','web-sum/utstyrstype','Fastmontert/bagasje40k felles, separat ikke monterte kjøretøydeler40k;kjøreutstyr ubegrenset.','Kjøreutstyr, bagasje og fastmontert utstyr','web-mc')
r(['mc'],'all','Egenandel','valgbare','Kundevelger2 000–25 000; ansvar0,veihjelp750,FGtyveri-2000.','FAQ egenandel','web-mc')
r(['mc'],'all','Bonus','start/maks','60%start,75%maks,10%årlig til70deretter3årtil75;min40vedoverføring og matching av bedre;nyBil/MCsammebonusfor eier/ektefelle/samboer.','FAQ bonus','web-mc')
r(['bobil'],'super','Nyverdi Super','motstrid i samme side','Webintro sier3år/100 000km;dekningstabell3år/60 000km og MOT60 000. Ikke vilkårlig velge100k.','Fordeler/ekstra erstatning','web-bobil')
r(['bobil'],'machine','Maskinskade','tegning','Kan kjøpes før15år og under150 000km;skadegrense200 000,ikke samme som tegning.','Motor- og girskade','web-bobil')
r(living,'super','Supergaranti','service/varighet','Ved flytting minst like gode vilkår som forrige selskap i2år;egen garanti lenket, ikke komplett lokal fullregel.','Supergaranti','web-living')
r(['campingvogn'],'super','Nyverdi','web-alder','Ny vogn ved totalskade inntil3år;MOT generisk Super med bil/km krever typevurdering, web har ingen kmgrense for campingvogn.','Ekstra erstatning','web-camping')
r(['campingvogn'],'higher-equipment','Utstyr/bagasje','valgbar høyere sum','Kan kjøpe høyere samlet sum opptil300 000; ikke basis100/40k byttet uten kundevalg.','Ekstra erstatning for bagasje og fastmontert utstyr','web-camping')
r(['campingvogn'],'higher-building','Tilbygg','valgbar høyere sum','Høyere enn40 000 kan kjøpes, beløp individuelt.','Tilleggsdekning for spikertelt og tilbygg','web-camping')
r(['campingvogn','tilhenger'],'all','Ansvar','trekkbil/egen plikt','Egen ansvarsforsikring ikke pålagt;trekkbilens ansvar ved kjøring;egen skade krever egen fysisk dekning.','FAQ','web-nonmotor')
r(['snøscooter'],'physical','Tyveri','kildekonflikt egenandel','Webintro/SV692 sier FG-2000;FAQ standard8000til4000 med FG og0medFG+alarm. Konflikt dokumenteres, ikke justeres bort.','Fordeler/FAQ egenandel','web-snow')
r(['snøscooter'],'all','Egenandel','valg','4 000–25 000;ansvar0.','FAQ egenandel','web-snow')
r(['snøscooter'],'physical','Utstyr/bagasje','web-sum','Samlet40 000;deler tilhørende kjøretøy men umontert separat40 000.','Fastmontert tilleggsutstyr og bagasje','web-snow')
r(['tilhenger'],'physical','Veihjelp','egenandelkildekonflikt','Web500;MOT750;S709 angir ingen avvik. Ikke hevde én sikkert gjeldende standard uten avklaring.','Veihjelp i Europa','web-trailer')
r(['tilhenger'],'physical','Egenandel','valg','Web valg2 000eller4 000;MOTdefault8000medbevisoverstyring. Skille kundens valg fra default.','Egenandel ved skade','web-trailer')
save('if-motor-independent-inventory.json',dict(source_first=True,catalog_values_inspected=False,rules=R,source_contents_read=['MOT2-2 all26pages','GEN2-9 all13pages','SV692 all4pages','SV707 all5pages','S709 bothpages','MC/Bobil IPID bothpages each','MC/Bobil/Camping/Snoscooter/Tilhenger HTML allbody content'],scope_notes='Exact type and component rules apply; common document alone does not prove identical product. Specific conflicts retained; no canonical source data modified.'))
print(len(R),'independent source rules saved')
