from continue_audit import save
R=[]
def r(scope,sub,dim,val,loc,old=''):
 R.append(dict(id=f'IF-PET-{len(R)+1:03d}',scope=scope,subject=sub,dimension=dim,value=val,location=loc,prior_subject=old))
r('all','Veterinær','årsperiode','Valgt sum per forsikringsår,egenandel per skade/sykdom.','4 §5.1','Veterinær')
r('all','Veterinær','opphør','Beholdes hele livet;sykdom måoppståetterkarenstid.','4 §4','Veterinær')
r('all','Tannulykke','dekning','Alle nivåer tannulykke/fraktur og rotspissabcess ved avskalling/fraktur.','4 §5.1.2','Tannulykke')
r('all','Medisin','nivåomfang','Basis hosveterinær;Standard/Superogsåseparatkjøpetterbehandling.','4 §5.1.1','Medisin')
r('upper','Tannsykdom','grense/årsak','Standard Hund15k/Katt5kihelelivet;karies/TR.Superårligveterinærsum,menKattTR5kårlig.','4 §5.1.3','Tannsykdom')
r('upper','Tannsykdom','ungdyrvilkår','Melketenner/cyster/emalje/bittfeil medisinsknødvendigvedkontinuerligtilsvarendedekningfør4mnd;Kattordlydforsikretfør4mnd.','4 §5.1.3')
r('all','Allergi','nivåomfang','Basisutredning,Standardbehandling15kilivet,Superårligveterinærsum.','4–5 §5.1.4','Allergibehandling')
r('super','Rehabilitering','frist','Veterinærrekvirert/utførtfysio/rehab/kiropraktikk innen1åretterskade,inntilveterinærsum.','5 §5.1.5','Rehabilitering')
r('all','Fødselshjelp','varighet/antall','Én gangperliv,minst1årtilsvarendedekning,ikketidligere2ellerflerekeisersnitt.','5 §5.1.6')
r('dog','Fødselshjelp','raser/avl','Bostonterrier/chihuahua/pomeranian/engelsk-franskbulldog måhadokumentertnaturligkullfør;NKKetiskavl.','5 §5.1.6')
r('all','Medfødt','kvalifikasjon','Dekningførs4mnd,utenkjent/symptomvedungdyrkontrollførlevering;helse-/funksjonsbetydning.','5 §5.1.7')
r('all','Avlivning','aldersgrense','Dyrevernmessiganbefaltveterinær tilogmedåret10år;veterinærbehandlingellershelelivet.','5 §5.1.8')
r('super','Rollover','kvalifiserende vilkår','10kforSKADEFRITTår;redusertvedsumreduksjon;maxdobbeltvalgtsum,bareSuper.','5 §5.1.9','Rollover')
r('life','Liv','valgfrihet','Barevalgtlivibevis,ikkeautomatiskveterinærnivå.','5 §5.2','Liv')
r('life','Liv','sumtak/ID','Valgtbeløpmenmaxnytilsvarenderase;hundIDhvis>15k/kattalltidID;bruksverdiutbetalingredusererhundliv;annenlivserstatningutelukkerdobbel.','5 §5.2')
r('life','Liv','aldersmodell','Hundgruppe1fra6år20%forrigesumtilhovedforfall8;gruppe2fra8til10;gruppe3fra10til12.Kattfra10år20%forrigesumtil13.','Hund6/Katt5 §5.2','Liv')
r('life','Liv','raselister','Hundgruppe1berner/granddanois/irskulvehund/leonberger/newfoundland/pyreneer/napolitansk/sanktbernard;gruppe3eksaktnavngittliste;øvrige/blandinggruppe2.','Hund6 §5.2')
r('life','Liv','dødsårsak','Død/veterinæranbefaltavlivningavdekketulykke/sykdom;ikkeallårsaksdekning.','Hund6/Katt5 §5.2.1')
r('life','Kremering','sum','Felleskremering;separatvalgtmaks1500veddekningsmessigdød.','Hund6/Katt5 §5.2.2')
r('life','Forsvinning','ID/tid','ID-merketdyr,tyveri/borte,politiogIfmelding;ansessavnetetter6mnd.','Hund6/Katt6 §5.2.3')
r('doglife','Bruksverdi','andel/alder/definisjon','50%livssuménlivgang,tilogmedforsikringsåret7år;varigtapveterinærattest;trentjevnligpraktiskarbeid,ikkeavl/utstilling.','3 §1.1;6 §5.2.4')
r('all','Arvelig/navlebrokk','unntak','Veterinær/livikke arvelig/navlebrokk,unntaksunntakHD/AD/andreleddseparat.','Hund7/Katt6 §6.1.1–2')
r('all','HD/AD','artsspesifiktunntak','Hundkreverforsikretfør4mndOGbeggeforeldreNKKfri;Kattfør4mndELLERbeggeforeldrefrie.','Hund7/Katt6 §6.1.3')
r('all','Andre leddlidelser','unntaksunntak','OCD/patella/shortulna/CalvéLeggPerthes barevedsammenhengendeforsikretfør4mnd.','Hund7/Katt6 §6.1.4')
r('all','Import/sinnslidelse','unntak','Ikkeparasitt/smittevedimport/atferdslidelse/vanskjøtsel/ikkeveterinærråd.','Hund7–8/Katt6–7 §6.1.5–7')
r('all','Karenstid','sykdom','20dager,ingenveddirekteflytting/annenIfeier;nyperiodeforutvidelse.','Hund8/Katt7 §6.2.1','Karenstid')
r('all','Komplikasjoner','unntaksunntak','Komplikasjonudekketlidelseikkedekket;komplikasjonvaksine/kastrering/steriliseringspesifiktdekket.','Hund8/Katt7 §6.2.2')
r('all','Kastrering/kryptorkisme','unntak','Kastreringkunveddekketannenlidelse;ikkehundinnbiltsvangerskap,ikkekryptorkisme.','Hund8/Katt7 §6.2.3–4')
r('all','Behandling','unntak','Ikkealternativakupunktur/gull/homeopati;ikkeforebyggendevaksine/klipp/tannrens;ikkediettfôr/tilskudd/utstyrhjemme.','Hund8/Katt7 §6.2.5–7')
r('all','Transport/vakt','vilkår','Ikkereise-/transportutgifter;vakttilleggbarekanikkeventeordinæråpning.','Hund8/Katt8 §6.2.8')
r('dog','Raseunntak','luftvei/øyelokk/hud','LuftveiBoston/engelskfranskbulldog/griffon/mops/pekingeser/shihtzu;øyelokkbasset/blod/boxer/bullmastiff/bulldog/mops/granddanois/napolitansk/sharpei;hudbasset/blod/engelskbulldog/bullmastiff/napolitansk/sharpei;inklrasemiks.','9 §6.3')
r('cat','Raseunntak','luftvei','Exotic/Perserogblandinger:kirurgikorrigeringgane/svelg/luftveiunntatt.','8 §6.3')
r('all','Oppgjør','symptomdato','Forsikringssumvedførstesymptom/påvisningførst,ikkebarefakturadato.','Hund10/Katt8 §7.2.1')
r('all','Oppgjør','egenandel/beløp','Faktiskvalgtbeløp/egenandelbevis,ikkeénoppfunnetstandard.','Hund10/Katt8 §7.2.2','Veterinær')
r('all','Helse','kontroll/vaksine','Årligesjekk/vaksinasjonetterVeterinærkatalogen;raseriktigellersforholdsmessigavkorting.','Hund11/Katt9 §7.4')
r('out','Ungdyrprodukt','utenforaktivenivåer','Separatvalpe-/kattungeavtale30k/kull2k/skade,til12uker/overlevering,måkjøpesførfødsel;Kattmorfør6år. Ikkeaktivkatalogtillegg.','Hund7/Katt6 §5.3')
r('all','Administrasjon','skademelding','Skademelding,direkteoppgjør,obduksjonIfpålegg/adminbeholdeskildeutenrad.','Hund9–11/Katt8–9 §7','Administrasjon')
r('all','Geografi','artsdekning','VeterinærEuropa,livheleverden. Ikkeimportlivtilveterinær.','3 §3')
r('all','IPID','fødselsvilkårkonflikt','Fullvilkårminst1år/ikketidligere2ellerflere;IPIDmerenn1år/ikkeflereenn2. Matematiskgrenseforskjell.','IPID1')
save('if-pet-independent-inventory.json',dict(source_first=True,reuses='Existing source-first reviews.py and SF0033–0070; extends beyond previously partial inventory, no prior work discarded.',rules=R))
print(len(R))
