from continue_audit import save
R=[]
def r(scope,sub,dim,val,loc,src='terms'):
 R.append(dict(id=f'IF-RE-{len(R)+1:03d}',scope=scope,subject=sub,dimension=dim,value=val,location=loc,source=src))
r('all','Sikrede','valg/bosted','Bevispersoner,Norsk folkeregister/folketrygd;familieektefelle/samboersammeadresse,barn under21medforelderadresse.','3–4 pkt1.2')
r('super','Familie','barnebarn','Barnebarn/oldebarnunder21påreisemedtaker,bareutenannenreiseforsikring.','4 pkt1.2')
r('all','Reise','start/slutt','Hjemmefra-tilhjem;gyldigførstart,utenkravovernatting forselveproduktet.','4 pkt1.3')
r('all','Reisedager','Norge','Ubegrensetantallreisedagerinnenlands,utenlandsbevisfraNorgeuttilinn.','4 pkt1.3')
r('all','Reisedager','standard/valg','45standardfrawebtabell,45eller90kundevalgIPID;180ikkeoppgittidagenslokalekanoniskekilder.','1','ipid')
r('extension','Reisedager','ekstra','Ekstradagerførreisenellersenestsistedag,etteravtale;maks365d;ikkeautomatiskstandard.','FAQ varighet','web')
r('all','Geografi','kundevalg','Nordenellerverdenbevis;ikkehjem/arbeid/studiestedNorgeunderarbeid/studiehellerikkeeiendelerder.','4 pkt1.4')
r('all','UD','begrensning','Ikkeområdermedreiseråd;ugyldighele reisen selv ved opphevelse etteravreise.','4 pkt1.4')
r('all','Ekspedisjon','grunnunntak','Fjerninfrastruktur/sykehus,Arktis/verdenshavseilas/fjell>5000m krevertilleggsavtale.','4 pkt1.4')
r('all','Arbeidskonflikt','unntak','Ikke streik/lockout/konkurs/taptarbeidsfortjeneste.','5 pkt1.5–6')
r('upper','Avbestilling','sum/tid','Ubegrensetikke-refunderbareegne/medforsikredereisekostnader,bestiltførhendelse,dekningførførsteinnbetaling,avbestillføravreise.','5 pkt2.1–2')
r('upper','Avbestilling','personkrets','Akuttsykdom/ulykke/død selv/nærfamilie/enestemedreisendeogfamilie/enavgruppeinntil6/nøkkelperson/vertselvreiseralene;ikke kjentsykdomskomplikasjon.','5 pkt2.2.1')
r('upper','Avbestilling','andreutløsere','Endretfastsattoperasjonsdato,graviditetfør36/28vedflerling,samlivsbrudd,rettsinnkalling,alvorligbolig/forretningsskade,UDreiseråd72t/naturkatastrofe.','6 pkt2.2.2–8')
r('upper','Avbestilling','unntak','Ikkejobbreise/bonuspoeng/timeshare/andrebetalt/skatt/gebyr/avlystreise/voucher;ikkeforlengetbehandling/venteliste/rus/karantene/frykt/bortfaltformål.','6–7 pkt2.3–4')
r('super','Avlyst turisttjeneste','sum/vilkår','5kperson25kfamilie,reiseovernattingoffentligtjenesteavlyst/flyttetutoverperiode,Supervedbetaling.','6 pkt2.2.9')
r('upper','Forsinkelse','transport/overnatting','Rimelignødvendigubegrensetinnhenting/overnatting;vedforsinketavgangtransport3k/person,transportørmåikkeinnhenteinnen24t.','7–8 pkt3.1')
r('upper','Forsinkelse','utløser/unntak','Ekstremvær/ekstraordinærtrafikk/tekniskfeilulykke,privatbilberging;sufficientconnectiontime;ikkeflyselskapsansvarEU/matdrikke/bonuspoeng.','8 pkt3.1')
r('super','Tapt hotell/tjeneste','sum/tid','Ankomstmin8tforseint,énhotellnatt/tjeneste5kperson;ikkejobbreise/refunderbart.','8–9 pkt3.2')
r('super','Tapt leieavtale','sum/tid','Min1.5tforsinketoppmøte,forhåndsbetaltkansellertbil/MC10kcase;ikkemopedATV/snow/privatleie/jobbreise.','8–9 pkt3.2')
r('upper','Forsinket bagasje','sum','Nødvendigklær/reiseartiklerkjøp/leie5kperson25kfamilie;ikkehjemreise.','9 pkt3.3')
r('upper','Transittbagasje','sum','Ufrivilligovernattingflyforsinkelse/ikkeadgangbagasje1kperson5kfamilie.','9 pkt3.3.1')
r('super','Spesialbagasje','ekstrasum','Ytterligere5kperson25kfamilie vedforsinketbarnevogn/instrument/sportsutstyr.','9 pkt3.3.1')
r('super','Bagasje fortsatt savnet','ekstrasum/tid','Etter5dagerankomstytterligere5kperson25kfamilie.','9 pkt3.3.1')
r('upper','Reisegods','sum/utløser','Egnetingubegrensetgenerelt;tyveriran/hærverk/natur/trafikk/brann/vann/innsjekket;mistet/bortkommet/underslagikke tyveri.','10 pkt4.1–2')
r('upper','Reisegods','tingunntak','Kjøretøy/båt/kjøreutstyribruk,flyttegods/møbler/samling/dyr/arbeidsgiverting/yrkesting/udeklarertunntatt.','11–12 pkt4.5.1')
r('upper','Reisegods','skadeunntak','Vanligbruk/kosmetikk/taptøkonomi/luftsportdroneibruk/kjæledyr/innsjekketkoffertunntatt.','12 pkt4.5.2')
r('upper','Reisegods','oppbevaring','Verdiersafe/medbærtikkebil/båt/telt;elektronikk/medisin/pass/verdiikkeinnsjekket;sykkellås.','11 pkt4.4')
r('upper','Penger','sum','5kperson10kfamiliecase.','11 pkt4.3.1')
r('upper','Smykker/klokker','sum','30ksamletperskadetilfelle,kategoritakikkeperitem.','11 pkt4.3.2')
r('upper','Enkeltgjenstand','sum','Andreting40kinkltilbehør;sykkelaldrioverskaffelsespris.','11 pkt4.3.3')
r('upper','Reisegods','aldersoppgjør','Reparasjontilsvarende,alderbrukfunksjonfradrag,arv/bruktbruktsalgsverdi;ingenfastaldersprosent.','12–13 pkt4.6')
r('upper','Pass','gjenanskaffelse','Rimelignødvendigpass/innhentingvednavngittefarer4.2.1–6;ikkebaretilfeldigtap.','10 pkt4.2.8')
r('super','Uhell','egenandel/utløser','Ytreplutseligfysisk,kjentårsak/tid/fremvisning,3kpercase;kap4grenserfortsatt.','11 pkt4.2.9')
r('all','Sykdom','sum/utløser','Ubegrensetrimelignødvendigakuttsykdom/ulykke/død;ikke kjentsykdomskomplikasjon,utgiftinnenreiseperioden.','13 pkt5.1')
r('all','Medisinsk','omfang','Lege/sykehus,lokaltforeskrevetmedisin/utstyr/spesialist.','13 pkt5.2.1')
r('all','Tann','sum','5kperskadetilfelle.','13 pkt5.2.1')
r('all','Hjemtransport','vilkår','Legeordre,ikkeadekvatbehandlinglokalt,ledsager,kisteurne;begravelsepåstedmax40k/maksreturkost.','14 pkt5.2.2')
r('all','Endret reise','periode','Familiealvorligsykdom/dødpådestinasjon:forlengetopphold/endretruteinntil14d.','14 pkt5.2.2')
r('all','Tilkallelse','personer','Inntil3nærefamiliemedlemmer vedsværtalvorlig/livstruende/død,ikkealleredehjemtransportbestemt/lokalthjemsykehus.','14 pkt5.2.3')
r('all','Hjemkallelse','omfang','Alvorlignærfamilie/bolig/forretning;énreiseprcasebegrensetreturNorgekost.','14 pkt5.2.4')
r('upper','Tapte feriedager','beregning','Forhåndsgodkjenthjemreise/evakueringallemedforsikrede;sykehusmin1dsyke+én;prisandelavdagertapt/planlagt,ingenbonus/timeshare.','14–15 pkt5.2.5–6')
r('all','Returreise','alternativ','Innenopprinneligreisetid,i stedetfor avbruddkompensasjon ogmaxsammebeløp. Basisgren utenegenferiekompensasjonkreverforbehold.','15 pkt5.2.7')
r('all','Tapt turisttjeneste','sykdomstak','5kcase vedlegeforbud;ikke itilleggtilferietapkompensasjon.','15 pkt5.2.8')
r('all','Eneste medreisende','sum','60kcase reise/oppholdsomfølgeavenestemedreisendeshjemtransport/hjemkallelse.','15 pkt5.2.9')
r('all','Psykologisk førstehjelp','timer/vilkår','10timerakuttkriseetteralvorlighendelse,umiddelbart/inettverk,ikkelangtidspåkjenning/ordinærbehandling.','15 pkt5.2.10')
r('all','Sykdom','unntak','Ikkeetterhjem/venteliste/privatklinikkNorden/ikkelegerekvirertfly/rus/kosmetikk/feilbehandling/fødsel>=36eller28flerling/søkredning.','15–16 pkt5.3')
r('all','Sykdom','behandlingsperiode','Sammesykdom/ulykke løpendebehandlingførste30dageretterførstelege/tannlegebesøk.','16 pkt5.4.3')
r('all','Sykdom','forhåndskontakt','Kontakt vedforventet>10kmedisinsk/alvorligskade/endrethjemreise/hjemtransport/tilkallelse.','16 pkt5.4.1')
r('all','Evakuering','sum/utløser','UbegrensetetterUD/angittemyndighet/If vedkrigterror/natur/pandemiutenlands;ikkeforhåndsreiseråd;overnattinginntilevakueringmulig.','17 pkt6')
r('all','Ansvar','geografi/sum','UtenforNorden,privat;10millBasisStandard/15millSuperpercase+sakskost.','17–19 pkt7')
r('all','Ansvar','unntak','Kontraktsansvar,låntting,familie,næring,motor/båt/eiendom/forurensingunntak medsmalehjelpemiddelunntak.','17–18 pkt7.2')
r('all','Rettshjelp','geografi/sum','UtenforNorden100kpertvist/250kmin3parter,sammepørsmål;tvistførsluttreise.','19 pkt8.1')
r('all','Rettshjelp','unntak','Idømtkost/yrke/eiendom/familie/motor/straff/forvaltningførklageuttømt/Ifoppgjørunntatt;egenandellokalweb0.','19–20 pkt8.2')
r('all','ID-tyveri','sum/status','1milljuridiskassistcase,meldetpoliti/skjeddogkonstatertiperioden;forebyggeyterligereogbetalingsanmerkning.','21 pkt9')
r('all','ID-tyveri','unntak','Ikkenæring/nærfamilie/grovfamiliestraff/økonomisktapannetennjuridisk.','21 pkt9.3')
r('super','Leid transportmiddel','sum/utløser','Ubegrensetavtaleegenandel ytre skade/tyveri/nøkkel:bil/bobil<=7500kg,MC>50cc,sykkel/el;ferieminovernatting.','21–22 pkt10.1')
r('super','Leid transportmiddel','vilkår','Gyldigførerkort,kaskoCDW+TPmotorkjøretøy;privatleiekunoffentligbildelingsaktør;ikkearbeid/reparasjonserstatning/leasing/abonnement/motorsport/kosmetisksykkel.','22 pkt10.1–2')
r('super','Skadedyr','sum/egenandel/sted','100kcase/2kegenandel,AnticimexiNorgefastboligetterdokumentertutenlandsreise.','22 pkt11.1')
r('super','Skjeggkre','serviceperiode','3befaringerførsteår,utstyrselvhjelp/rådi4årforutsattløpendeavtale.','22 pkt11.1')
r('super','Skadedyr','unntak','Ikkeandrebygg/fellesbod/fysiskinnboskade/byggåpning/dødedyr/varme/kulde/gass/førstart/etteropphør/utendørs/næring;selvbetaltbilfriadkomst.','23 pkt11.2')
r('expedition','Ekspedisjon','tillegg','Utvidergeografi/risikomiljøforpersonerogperiodeibevis;ikkeautomatiskvalgt,ikkegenersøkredningstillagt.','23 pkt12')
r('all','Fast ulykkeserstatning','uttrykkelignei','Medisinskeutgifterdekkes;ingenutbetalingformedisinsk invaliditetellerdød.','Dekningstabell sykdom','web')
r('all','Tjenestereise','omfang','Selveproduktogmedisinskja;avbestillingnei,Superleieegenandel/forseinkettjenestenefrieunntakholdes.','FAQ alle reiser','web')
r('all','Digital lege','service','Gratis,Hjemmelegene07–22norsk,digitaldersomfysiskikketrengs;kontaktinnen20min;døgnåpenIftelefonadskilt.','Slik får du hjelp','help')
r('all','ID-tyveri','juridisk førstelinje','10timerSolverførstehjelp;separat1milltvist.','Tabell ID-tyveri','web')
r('all','Egenandel','standard','IngenegenandelunntattSuperuhell3k/skadedyr2k.','Egenandeler','web')
r('super','SmartDelay','service/vilkår','>1tforsinkelse,selv+4,registrering>=24tfør;FlightStatsmelding;lounge/alternativt40EURpersonutenlounge;ikke kansellert/utsatttilneste24timer.','Hva er og FAQ','smart')
r('super','SmartDelay','frivilligekstratjeneste','AirHelpvalgfritt,>3t/opptil600EURsøknad,35%honorar;ikkeegenubetingetforsikringssum.','AirHelp','smart')
r('super','Supergaranti','periode','2årvedflytting;fullsærvilkårikkeilokalpakke,ingenautomatiskcatalogoverride.','Supergaranti','web')
r('all','Psykologisk førstehjelp','kildekonflikt','Fullvilkår10timer;web10behandlinger. Ikke anta ekvivalens eller utvide automatisk.','15 pkt5.2.10 vs webtabell','terms')
r('all','Administrasjon','prosedyre','Dokumentasjon/bevisforrang/skjønn/regress,ikkehverprosedyrenyttcanonicalfact;generalGEN2-9deltlokaltmenkontraktversjonavklares.','3;24–25')
save('if-reise-independent-inventory.json',{'source_first':True,'catalog_values_inspected':False,'rules':R,'source_contents_read':['ERA3-4 all26pages effective2025-03-22','IPID2pages','all4localHTMLbodies/FAQ inclSmartDelay','GEN2-9 exactlocalgeneralreadpreviouscheckpoint;versionapplicabilitynotassumed'], 'scope':'Basis/Standard/Super;45/90 customerchoice and365 extension separate;nohistorical180import;expeditionoptional.'})
print(len(R))
