# These lines are executed inside reviews.py before serialization.
ps=['storebrand-bat-delkasko','storebrand-bat-kasko','storebrand-bat-super'];f='storebrand-boat-terms.pdf'
for p in ps:
 fact([p],f,16,'9.1 Ansvar','Ansvar','person- og tingsum','3 020 000 SDR person; 1 510 000 SDR ting',COARSE,['bat.ansvar.dekning'],'P1',note='Inkludert uten de to sumgrensene. SDR beholdes; ingen valutakonvertering.',status='LIMITATION')
 fact([p],f,19,'10.5 og 10.6','Rettshjelp','sum og egenandel','100 000 kr per tvist; 4 000 kr + 20 % over dette',COARSE,['bat.rettshjelp.dekning'],'P1',note='Dekningen har ingen sum-/egenandelsrader. Gruppegrenser finnes i samme punkt og skal ikke generaliseres til standardtvist.',status='LIMITATION')
 fact([p],f,20,'11.2','Fører/passasjerulykke','dekning og summer','Død 100 000 kr; invaliditet voksen 200 000 kr / barn under 18 år 500 000 kr; samlet 1 000 000 kr',MISSING,['bat.ulykke.dekning','bat.ulykke.dod','bat.ulykke.invaliditet'],'P1',note='Oversikt, IPID og pkt11 dokumenterer inkludert på alle tre nivåer; ingen tilsvarende katalogfact eller tillegg. Utleie og betalende passasjerer unntatt.')
 fact([p],f,6,'4 Forsikrede ting;side7/5.1.1–2;side10/5.3.2;side11/6.10','Bagasje','sum per hendelse',('100 000 kr' if p.endswith('super') else '50 000 kr')+';bagasje med verdi over15 000kr per gjenstand er unntatt (6.10)',MISSING,['bat.losore.dekning','bat.losore.grense'],'P1',note='Brann-/tyveridekning av løsøre følger alle nivåer. Fullvilkår, produktside og IPID kontrollert; ikke antatt full allriskdekning.',status='LIMITATION')
 fact([p],f,8,'5.1.3 Båtredning, presisering1 og egenandel','Redning','egenandel','750 kr',MISSING,['bat.redning.egenandel'],'P1',note='Båtredning er uttrykkelig del av delkasko og arves av Kasko/Super. Forelderen finnes bare i de to siste.',status='LIMITATION')
 fact([p],f,8,'5.1.3 Båtredning, presisering1 og egenandel','Redning','dekningsmekanisme','Slep til nærmeste trygge fortøyningssted etter plutselig uforutsett uhell',MISSING if p.endswith('delkasko') else COARSE,['bat.redning.dekning'],'P1',note='IPID oppgir Båtredning i Delkasko. Katalogens delkasko mangler den; høyere nivå sier bare Inkludert.')
 fact([p],f,8,'5.1.3 Kriseterapi, presisering6','Kriseterapi','antall og frist','10 behandlingstimer innen 12 måneder etter skade',MISSING,[],'P2',note='Eksplisitt tilleggstjeneste;anbefalt nested provider-detalj. Egenandel ikke konkludert her.')
 fact([p],f,8,'5.1 Egenandeler','Brann/tyveri','egenandel','6 000kr hvis ikke annet fremgår av forsikringsbeviset',MISSING,['bat.brann.egenandel','bat.tyveri.egenandel'],'P1',status='LIMITATION')
 fact([p],f,5,'2 Geografi','Geografi','område','Skandinavia; utvidet Europa 1.april–30.september med angitte havområder',PRESENT,['bat.geografi.omrade'],note='Katalogen bevarer sesongutvidelsen, men full rute/12nm-tekst ligger i kilde; ikke feilaktig helårs-Europa.')
 fact([p],'storebrand-boat-product.html',0,'FAQ egenandeler','Egenandel','kundens valgte kaskoandel','6 000 / 8 000 / 12 000 / 16 000 kr kan velges; særregler egne',CUSTOM,[],note='Faktisk valg må hentes i forsikringsbevis. Vilkårets standard og den offentlige valgmuligheten må begge bevares.',status='CUSTOMER_SPECIFIC_REFERENCE')
for p in ps[1:]:
 fact([p],f,9,'5.2 Dekningstabell','Opplagsutstyr','grense','20 000 kr',MISSING if p.endswith('super') else COARSE,['bat.opplagsutstyr.dekning','bat.opplagsutstyr.grense'],'P1',note='Super inkluderer eksplisitt hele Kasko. Kasko har bare forelder; Super mangler både forelder og grense fordi radsettet er gjenoppbygd separat.',status='LIMITATION')
 fact([p],f,9,'5.2 Dekningstabell','Rigg','dekning','Skade ved brudd på rigg og følgene av bruddet',MISSING,['bat.rigg.dekning'],'P1',note='Separat dokumentert hendelsestype; generell kasko-forelder er ikke full representasjon.')
 fact([p],f,9,'5.2 Dekningstabell;side11/6.22','Drivstoff','kvalifisert skade','Feilfylling eller plutselig tilførsel forurenset drivstoff; ikke gradvis mikroorganismevekst',MISSING,[],'P2',note='Typebestemt underdetalj til kasko; foreslår ikke ny universell allriskdekning.')
 fact([p],f,9,'5.2 Kasko','Kasko','dekning','Skade på egen båt ved sammenstøt, kantring/synking mv.',PRESENT,['bat.kasko.dekning'])
fact([ps[2]],f,10,'5.3 presisering1','Ferieavbrudd','dagssats og sesong','2 promille av forsikringssum per dag; 15.april–15.september; maks30d/60 000kr',COARSE,['bat.ferieavbrudd.dekning','bat.ferieavbrudd.dager','bat.ferieavbrudd.grense'],'P1',note='Antall og totalgrense er korrekte. Dagssats og sesong kan endre utbetaling, og er ikke representert.',status='LIMITATION')
fact([ps[2]],f,10,'5.3 presisering6','Totalskade','ny/brukt og terskel','Ny: >80 % reparasjon/nypris og ny til eier; Brukt: eget kjøpesumsoppgjør; begge innen3år etter kjøp',COARSE,['bat.totalskade.dekning','bat.totalskade.alder'],'P1',note='Tre år alene skiller ikke nybåtgaranti fra kjøpesumsgaranti. Fullvilkår og produktside avgrenser dette likt.',status='LIMITATION')
fact([ps[2]],f,10,'5.3 presisering5','Jolle','størrelse og motor','Jolle/gummibåt/livbåt inntil4m; motor inntil10hk',MISSING,['bat.jolle.dekning','bat.jolle.begrensning'],'P1',note='Hele Super-fordelen mangler; ikke gi samme standardfordel til lavere nivåer.')
fact(ps,f,11,'6.18 Unntak','Maskinskade','uavhengig mekanisk skade','Ingen separat motor-alene-dekning påvist; angitte kaskohendelser er noe annet',REVIEW,['bat.maskinskade.dekning'],note='Kilden unntar motor alene unntatt angitte hendelser. Katalogens manglende uavhengige maskinskadefact skal ikke behandles som falskt ukjent.',status='EXCLUSION')
review(ps,[f,'storebrand-boat-ipid.pdf','storebrand-boat-product.html'],'Alle22 fysisk PDF-sider og IPID/HTML lest. Kasko/Super-inheritance eksplisitt kontrollert. Detaljer om søksmål/skadeadministrasjon utelatt. Valgt kaskoegenandel og båtsum holdes kundespesifikk. Full inventering ennå ikke attestert.')
# MC/Bobil source-first focused deep controls. Scope explicitly less than full package.
for p in ['tryg-mc-kasko','tryg-mc-mc-ekstra']:
 f='tryg-05PAU25405.pdf'
 fact([p],f,4,'3.4 Nyverdi','Nyverdi','alder/km/skadegrad','1 år / 10 000km / >80 %; eier siden ny, ikke leasing, tyveri3uker',PRESENT,['nyverdi.alder','nyverdi.km','nyverdi.skadegrad','nyverdi.begrensning'],note='Alle viktige dimensjoner er representert, inklusive konservativ >-terskel. Bobil får ikke denne MC-regelen.')
 fact([p],f,1,'2.1','Kasko','kundeegenandel','Avtalt egenandel i beviset',CUSTOM,['kasko.egenandel'],status='CUSTOMER_SPECIFIC_REFERENCE')
 fact([p],f,2,'2.4 Glass','Glass','kjøretøykvalifikasjon','Bare3-/4-hjuls MC, ikke vindskjerm; 3000kr bytte/0reparasjon',PRESENT,['glass.dekning','glass.begrensning','glass.egenandel','glass.reparasjon.egenandel'])
 fact([p],f,1,'2.1 Påkjørsel dyr','Dyrepåkjørsel','egenandel/bonus','2000kr; ingen bonustap når politi/viltnemnd varsles',MISSING,[],'P2',note='Kundevalgt vanlig kaskoegenandel representerer ikke denne hendelsesspesifikke egenandelen.')
 fact([p],f,1,'2.1 Vær','Værskade','egenandelsfritak','Ingen egenandel hvis parkert innendørs i garasje eller lignende',MISSING,[],'P2',note='Provider-spesifikk underdetalj, ikke krav om symmetrisk rad hos alle.')
f='tryg-05PAU27010.pdf';ps=['tryg-mc-mc-ekstra']
fact(ps,f,1,'Maskinskade','Maskinskade','alder/egenandel','8år;4000kr til3år,6000kr3–7år; slitasje/garantiavgrensninger',PRESENT,['maskinskade.alder','maskinskade.egenandel','maskinskade.begrensning'])
fact(ps,f,1,'Leiebil','Leiekjøretøy','dager/sats/bruk','10d normal reparasjon;500kr/dag; bil eller MC; faktura; ikke andre bruksutgifter',PRESENT,['mc.leiekjoretoy.dekning','mc.leiekjoretoy.dager','mc.leiekjoretoy.dagsbelop','mc.leiekjoretoy.begrensning'])
fact(ps,f,1,'Transportkostnader langtur','Reservedelstransport','sum/utløser/egenandel','3000kr ved teknisk feil, reise minst3timer hjemmefra;0 egenandel',MISSING,[],'P2',note='Fullteksten dokumenterer en egen transportfordel. Ikke lik veihjelp; ingen analog universell motpart kreves.')
fact(ps,f,2,'Sykehusinnleggelse','Sykehuskompensasjon','utløser og engangssum','5000kr/skadetilfelle etter minst48t sammenhengende innleggelse',MISSING,[],'P2',note='Egen MC Ekstra-fordel er ikke tilsvarende valgfri invaliditetsforsikring.')
fact(ps,f,2,'Utvidet sum invaliditet','Ulykke','betinget tillegg','500000kr ved >25 % invaliditet, bare hvis ulykke avtalt',PRESENT,['ulykke.invaliditet'],component='tryg-mc-ulykke-ekstra',note='Faktisk addon-nøkkel kontrollert; valgfrihet bevares.',status='OPTIONAL_AVAILABILITY')
for p in ['tryg-bobil-kasko','tryg-bobil-bobil-ekstra']:
 f='tryg-05PAU25305.pdf'
 fact([p],f,1,'2.1','Skadedyr','hendelse','Insekter/gnagere/andre skadedyr',PRESENT,['bobil.skadedyr.dekning'])
 fact([p],f,1,'2.1 Egenandel','Kasko','ung fører','Avtalt egenandel +5000kr under23år, ikke hvis fører er forsikringstaker',PRESENT,['kasko.egenandel'])
 fact([p],f,4,'3.3','Utstyr','aldersfradrag','Fast elektronikk10 % per år, maks50 %',MISSING,['utstyr.begrensning'],'P2',note='Utbetalingsdetalj mangler; kontroller typebestemt understruktur ved remediell implementering.',status='LIMITATION')
 fact([p],f,4,'3.3 Totalskade','Totalskade','oppgjør','Markedsverdi; ingen nyverdigaranti i dette Bobil-fullvilkåret',REVIEW,['nyverdi.dekning'],note='Ikke lov å overføre MCs1år/10000km til Bobil. Ingen falsk unknown konkludert uten komplett resterende pakke.',status='EXCLUSION')
f='tryg-05PAU27007.pdf';ps=['tryg-bobil-bobil-ekstra']
fact(ps,f,1,'Løst utstyr','Løsøre','sum/gjenstand/fortelt','100000kr;10000kr/gjenstand;15000kr samlet fortelt;1000kr egenandel; ikke utleie',PRESENT,['bobil.losore.grense','bobil.losore.gjenstand','bobil.losore.egenandel','bobil.losore.begrensning'])
fact(ps,f,1,'Fuktskade','Fukt','alder/egenandel/unntak','15år;8000kr til10år;25 % min8000kr fra10;fortelt/rør/frost unntatt',PRESENT,['bobil.fukt.alder','bobil.fukt.egenandel','bobil.fukt.begrensning'])
fact(ps,f,1,'Avbrutt ferie','Feriegaranti','sats/varighet/utløser','2000kr/dag maks14d resterende planlagt ferie;ikke utleie;dokumenterte merutgifter',PRESENT,['bobil.feriegaranti.dekning','bobil.feriegaranti.dagsbelop','bobil.feriegaranti.dager','bobil.feriegaranti.begrensning'])
review(['tryg-mc-kasko','tryg-mc-mc-ekstra'],['tryg-05PAU25405.pdf','tryg-05PAU25935.pdf','tryg-05PAU27010.pdf'],'Fullt lest Kasko/Delkasko/Ekstra med katalog motkontroll. Produktavtale, ansvar/rettshjelp,ulykke,IPID/HTML gjenstår; ikke full pakke.',depth='TARGETED_FULL_DOCUMENT_REVIEW')
review(['tryg-bobil-kasko','tryg-bobil-bobil-ekstra'],['tryg-05PAU25305.pdf','tryg-05PAU27007.pdf'],'Fullt lest Kasko/Ekstra, målrettet materiell katalogmotkontroll. Delkasko/produktavtale/ansvar/tillegg/HTML gjenstår; ikke full pakke.',depth='TARGETED_FULL_DOCUMENT_REVIEW')
# Shared official Frende vehicle conditions, byte-identical copies; type wording checked explicitly.
for family,token,source,page in [('Snøscooter','snoscooter','frende-SnowmobileInsurance.pdf','frende-snoscooterforsikring.html'),('Campingvogn','campingvogn','frende-CaravanInsurance.pdf','frende-campingvognforsikring.html'),('Tilhenger','tilhenger','frende-TrailerInsurance.pdf','frende-tilhengerforsikring.html')]:
 ps=[p['productId'] for p in C['products'] if p['providerId']=='frende' and p['insuranceType']==family]
 fact(ps,source,12,'14.4','Rettshjelp','sum og egenandel','100000kr/tvist;250000kr ved minst3parter;4000kr+20 %',COARSE,[f'{token}.rettshjelp.dekning'],'P1',note='Rettshjelp gjelder uttrykkelig alle privatkunder pkt14, ikke Bil-only. Hele base/tillegg undersøkt; ingen sum eller egenandel. Hver type får egen nøkkel.',status='LIMITATION')
 fact(ps,source,2,'2','Geografi','område','Europa unntatt Russland,Tyrkia,Belarus;rettshjelp Norden',PRESENT,[f'{token}.avtale.geografi'])
 fact(ps,source,7,'11.1 Skademelding','Administrasjon','frist','Meld skade senest1år',ADMIN,status='ADMINISTRATIVE_RULE',note='Vanlig skadeoppgjørsregel, ikke egen sammenligningsdekning.')
 insured=[p for p in ps if not p.endswith('ansvar')]
 fact(insured,source,2,'3.7','Fastmontert utstyr','sum','20000kr',PRESENT,[f'{token}.utstyr.grense'])
 fact(insured,source,8,'11.6','Tyveri','ventetid før tapt','Tidligst30d før kjøretøy/campingvogn/tilhenger regnes som tapt',MISSING,[],'P2',note='Kjøretøyspesifikk oppgjørsdetalj; ikke livsforsikring eller nyverdi.',status='LIMITATION')
 review(ps,[source,page],'Alle15 sider i felles byte-identisk kjøretøyvilkår gjennomlest én gang; egen produktside gjennomlest per type. Bil/maskinskade/utvidet-Bil-regler overføres ikke til tilhenger/snøscooter. Generelle vilkår/IPID-pakkekontroll gjenstår.',depth='TARGETED_FULL_DOCUMENT_REVIEW')
 if family=='Snøscooter':
  fact(insured,source,8,'11.6 Snøscooter','Tyverioppgjør','gjenanskaffelsesvilkår','Markedsverdi hvis tilsvarende snøscooter kjøpes innen60d; ellers60 %',MISSING,[],'P1',note='Eksplisitt snøscooterregel, ikke generell kjøretøyregel. Kan redusere oppgjøret vesentlig og mangler helt i katalogen.',status='LIMITATION')
  fact(ps,page,0,'Dekningsmatrise fører/passasjerulykke + vilkår pkt12','Ulykke','valgfri tilgjengelighet','Tilvalg på Ansvar,Brann/tyveri,Kasko; dødsfall100000kr betinget,invaliditet200000kr',MISSING,['snoscooter.ulykke.dekning'],'P1',note='Produktside dokumenterer tilvalg og fullvilkår pkt12 innhold. Ingen tilgjengelig add-on i runtime for disse produktene. Skal ikke markeres inkludert.',status='OPTIONAL_AVAILABILITY')
  fact(ps,page,0,'FAQ Bonus','Bonus','opptjening','Ingen bonusopptjening på snøscooter',MISSING,[],'P2',note='Bil/MC-bonusmodell må ikke brukes.')
 if family=='Campingvogn':
  fact(ps,page,0,'Dekningsmatrise Forsikringssum løsøre','Løsøre','gjenstandsgrense','10000kr per enkeltgjenstand,innen samlet20000kr',COARSE,['campingvogn.losore.grense'],'P1',note='Samlet standard er korrekt; produktsidens uttrykkelige enkeltgjenstandsgrense finnes ikke i katalogen. Høyere valgt sum krever bevis.',status='LIMITATION')
  fact([p for p in ps if p.endswith('kasko')],source,3,'6.1.2 +18.1.11','Fukt','utløser og test','Godkjent årlig fukttest;oppstått siste12mnd;ikke utbedring lekkasje/rør',PRESENT,['campingvogn.fukt.dekning','campingvogn.fukt.begrensning'],note='Den vesentlige årsak/frist-begrensningen er bevart; krav om autorisert utførende ligger fortsatt i kilde.')
  fact(ps,source,9,'11.11 Utleid bobil/campingvogn','Utleie','tilleggsegenandel','+6000kr ved brann/tyveri/kasko under utleie',MISSING,[],'P1',note='Bare dersom kunden faktisk leier ut; ikke merk som standardegenandel.',status='LIMITATION')
  fact(ps,page,0,'FAQ Forsikringssum','Løsøre','valgt sum','20000 standard;utvidelse100000/200000 kan avtales',COARSE,['campingvogn.losore.grense'],'P2',note='Katalogens eller avtalt sum er ikke feil, men valgstrukturen er utelatt.',status='CUSTOMER_SPECIFIC_REFERENCE')
 if family=='Tilhenger':
  fact(ps,source,9,'11.11 Egenandel-tabell','Tilhenger','særegenandel','2000kr skade under tilhengerforsikring;tabellen har også generelle brann/tyverisatser',REVIEW,[],note='2000 er eksplisitt, men forrang mot6000brann/tyveri må avklares før entydig sats implementeres.',status='LIMITATION')
  fact(ps,source,2,'3.9','Løsøre','uttrykkelig unntak','Løse ting og bagasje gjelder ikke tilhenger',PRESENT,['tilhenger.kasko.begrensning'],note='Unntaket står under kasko-begrensning også på brann/tyveri; informasjon finnes, mulig presentasjonsplassering er separat spørsmål.',status='EXCLUSION')
  fact(ps,page,0,'FAQ Ting som fraktes','Tilhengerlast','annen forsikring','Mulig via innbo utvidet uhell;ikke tilhengerproduktet',ADMIN,note='Skal ikke legges som inkludert dekning i Tilhenger.',status='CROSS_PRODUCT_REFERENCE')
# Older families: focused source-first probes, explicitly not full package closure.
for pid,f in [('tryg-innbo','Innbo_og_losore_PPK13301.pdf'),('tryg-innbo-ekstra','Innbo_og_losore_Ekstra_PPK13302.pdf')]:
 fact([pid],f,1,'1.1','Forsikringssum','faktisk valg','Forsikringstaker velger sum i beviset',CUSTOM,['innbo.forsikringssum'],status='CUSTOMER_SPECIFIC_REFERENCE')
 fact([pid],f,1,'1.1 Motorvogn,båt,luftfartøy','Småbåt/tilhenger i innbo','brann/tyveri på forsikringssted',('40000kr' if pid.endswith('ekstra') else '20000kr')+';båt<=15fot,motor<=10hk,ikke selvstendig båtforsikring',MISSING,[],'P2',note='Kildestøttet særgrense; ikke overfør til selvstendig Båt/Tilhenger-katalog.')
 fact([pid],f,3,'2.3 Vann','Vann','terreng-egenandel','Minimum8000kr ved terreng/grunn',MISSING,[],'P1',note='Generisk kundens egenandel viser ikke uttrykkelig unntak; alle materialiserte base-/tilleggsfacts kontrollert.',status='LIMITATION')
 fact([pid],'Produktvilkar_PPK13300.pdf',1,'3 Geografi','Flytting','område/varighet','Norden;gammelt og nytt bosted i flytteperioden maks1år',PRESENT,['innbo.geografi'])
 review([pid],[f,'Produktvilkar_PPK13300.pdf'],'Dekningsfullvilkår (Ekstra fulltekst;Basis side1–4) og produktvilkår lest. Naturskade/ansvar/rettshjelp/utleie/generelle vilkår gjenstår i pakkekontrollen.',depth='TARGETED_FULL_DOCUMENT_REVIEW')
fact(['tryg-innbo-ekstra'],'Innbo_og_losore_Ekstra_PPK13302.pdf',4,'2.5','Uhell','presise unntak','Ukjent årsak,kosmetikk,slitasje,garanti,kjæledyr,sykkelgrense/konkurranse',PRESENT,['uhell.dekning','uhell.begrensning','uhell.egenandel'],note='Tidligere vag formulering er ikke grunnlag for nytt funn: nå finnes materialt relevante unntak i egen childfact.')
fact(['tryg-innbo-ekstra'],'Innbo_og_losore_Ekstra_PPK13302.pdf',4,'2.4 vs Basis2.4','Fellesgarasje','mulig foreldrerest','Ekstra har egen uttømmende tyveritabell;arvet15000kr kommer fra Basis',REVIEW,['tyveri.fellesgarasje.grense'],note='Kode beviser inheritsProductId og rest fra Basis. Full gjenværende kildepakke må gjennomgås før unsupported-klassifisering. Ikke funn om at riktig erstatning nødvendigvis er et bestemt annet tall.',status='LIMITATION')
fact(['tryg-hus'],'05PPK11501.pdf',3,'2.3 Vann','Våtrom','følgeskade','Vann fra utett våtrom,inkl.sluk,er unntatt',PRESENT,['hus.vatrom.folgeskade','hus.vatrom.selverommet'],status='EXCLUSION')
fact(['tryg-hus-ekstra'],'05PPK11502.pdf',3,'2.3 Våtrom','Våtrom','følgeskade/selve rommet','Tilstøtende/underliggende rom;egen våtromsdekning fagfolk,10år,ikke feil uten følgeskade',PRESENT,['hus.vatrom.folgeskade','hus.vatrom.selverommet'])
fact(['tryg-hus-ekstra'],'05PPK11502.pdf',7,'3.4','Isolerglass','aldersfradrag','10år fradragsfritt;10 % per år maks100 %;bare punktering',PRESENT,['hus.aldersfradrag.isolerglass','hus.glass.isolerglass_punktering'],note='Kombinert parent/childstruktur bevarer regel. Ikke slå sammen med bruddskade.')
fact(['tryg-hus-ekstra'],'05PPK11502.pdf',6,'3.3.2','Gjenoppføring','annet sted','Fradrag for omsetningsverdiøkning over40 %',PRESENT,['hus.gjenoppforing.annetsted'],note='Materielt oppgjørsvilkår representert; ikke kun Fullverdi-label.')
review(['tryg-hus'],['05PPK11501.pdf'],'Målrettet side3–4 vann/rør/våtrom. Alle andre kilder og større del av fullvilkåret gjenstår.',depth='TARGETED_SECTION_REVIEW')
review(['tryg-hus-ekstra'],['05PPK11502.pdf'],'Side1,3–9 lest;våtrom,oppgjør,aldersfradrag kontrollert. Side2 og øvrige hoved-/tilleggskilder gjenstår.',depth='TARGETED_SECTION_REVIEW')
fact(['bil-kasko'],'Bilforsikring-Kasko.pdf',4,'3.4','Nyverdi','alder/km/terskel','1år/15000km/>80 %;tyveri3uker;ikke leasing',PRESENT,['nyverdi.alder','nyverdi.km','nyverdi.skadegrad','nyverdi.tyveri','nyverdi.unntak'],note='Tryg Bil,ikke Gjensidige-kundegrunnlag. Ingen kundedokumenter brukt.')
fact(['bil-kasko'],'Bilforsikring-Kasko.pdf',4,'3.3','Fast elektronikk','aldersfradrag','10 % per år,maks50 %',MISSING,[],'P2',note='Oppgjørsregel finnes i kilden,ikke materialiserte base/tillegg.',status='LIMITATION')
fact(['bil-kasko'],'Bilforsikring-Kasko.pdf',3,'3.2','Kontantoppgjør','arbeidsandel','70 % av takst utenMVA;ikke leiebil',PRESENT,['reparasjon.kontant'])
review(['bil-kasko'],['Bilforsikring-Kasko.pdf'],'Side3–4 fullt lest;egen nyverdimodell og aldersfradrag undersøkt. Resterende kildepakke gjenstår.',depth='TARGETED_SECTION_REVIEW')
for pid in ['tryg-reise','tryg-reise-ekstra']:
 fact([pid],'PRF46000-Produktvilkar.pdf',2,'4 Varighet','Reisevarighet','automatisk forlengelse','2d forsinkelse/30d sykdom når forhåndsbestilt retur innenperioden',PRESENT,['reise.varighet.automatisk_forlengelse'])
 fact([pid],'PRF46000-Produktvilkar.pdf',1,'1/2 Avtale','Hvem som er sikret','kundespesifikt','Forsikringsbeviset angir personene og valgene',CUSTOM,['reise.personer.omfang','reise.avtale.forbehold'],note='Kildens kundespesifikke henvisning er legitim,ingen oppdiktet standardfamilie.',status='CUSTOMER_SPECIFIC_REFERENCE')
 fact([pid],'PRF46000-Produktvilkar.pdf',2,'3 Geografi','Reise','ud-unntak','Advarsel ved avreise gjør reisen ugyldig selv om senere opphevet',PRESENT,['reise.omrade.ud'],status='EXCLUSION')
 fact([pid],'Forsikringssummer-08.2026.pdf',1,'Reisegods / mobil','Mobil','gjentatt skade-egenandel','Andre tap/skade innen3forsikringsår:2000kr',PRESENT,['reise.bagasje.mobil_egenandel.gjentatt'])
 review([pid],['PRF46000-Produktvilkar.pdf','Forsikringssummer-08.2026.pdf'],'Produktvilkår3sider lest;sumtabell varighets-/mobilprober. Øvrige deknings-/ulykkes-/sikkerhetskilder gjenstår.',depth='TARGETED_SECTION_REVIEW')

# Nonordinary channel scopes remain separate exact identities.
p=['fremtind-mc-kasko'];f='fremtind-mc-terms.pdf'
fact(p,f,6,'Minikasko3.3.1;Kasko8/2 viser til Mini3','Nyverdi','alder/km/skadegrad','3måneder/2000km/>80%;ikke tidligere skade>10%;fabrikkny på eier',MISSING,['nyverdi.alder','nyverdi.km','nyverdi.skadegrad','nyverdi.begrensning'],'P1',note='Spesielt motorsykkel/moped,uttrykkelig Kasko-henvisning. Ingen nyverdi i alle28 katalogfacts. Bare ordinary-sparebank1;ingen overføring til DNB/Eika.')
fact(p,f,8,'Kasko1.2','Leiebil','inkludert avgrensning','350kr/dag,normal reparasjon maks15d,forhåndsgodkjent bruk/leverandør',PRESENT,['leiebil.dekning','leiebil.dager','leiebil.dagsgrense'],note='Spesifikk MC1.2 overstyrer generelt leiebilunntak i1.1. Katalogen bevarer dette.')
fact(p,f,5,'Minikasko1.3','Bagasje','sum/plassering','5000kr samlet i påmontert låsbar boks/veske,faste husstand,ikke penger/smykker/klokker',PRESENT,['mc.bagasje.dekning','mc.bagasje.grense','mc.bagasje.begrensning'])
fact(p,f,5,'Minikasko2.3','Glass','typeavgrensning','Denne glassdekningen gjelder ikke MC;bare veteran,mopedbil,traktor',ADMIN,note='Ingen falsk unknown for MC basert på annen kjøretøytype i samme PDF.',status='CROSS_PRODUCT_REFERENCE')
fact(p,f,8,'Kasko3.1','Kasko','ung fører','Avtalt egenandel+12000kr hvis under23ikke oppgitt',MISSING,['kasko.egenandel'],'P2',note='Katalogen henviser bare til bevis. Særregelen er produktfaktum,ikke kundens faktiske alder.',status='LIMITATION')
review(p,[f],'PDFside4–8 lest;egen MC-nyverdi,leiebil,bagasje og typeunntak kontrollert. Resterende1–3,9–11 og kanal/IPID må gjennomgås;scope ordinary-sparebank1 beholdt.',depth='TARGETED_SECTION_REVIEW')
p=['fremtind-bobil-topp'];f='fremtind-bobil-topp.pdf'
fact(p,f,9,'Toppkasko2.1.4','Parkering','alder/utløser','Tilførstehovedforfall etter6år;ukjent skadevolder,kjent tid/sted,ingen bonustap',PRESENT,['parkering.dekning','parkering.alder'])
fact(p,f,9,'Toppkasko2.1.6;3.1/3.2','Ferie','overnatting','1500kr/dag,maks15d,resterende planlagtferie,kvittering',PRESENT,['bobil.feriegaranti.dekning','bobil.feriegaranti.dagsbelop','bobil.feriegaranti.dager'])
fact(p,f,9,'Toppkasko2.1.7','Fukt','alder/test','Inntil15år;bestått autoriserttest,ettårsvindu,ikke utenforforsikringsperioden',PRESENT,['bobil.fukt.dekning','bobil.fukt.alder','bobil.fukt.kontroll','bobil.fukt.begrensning'])
fact(p,f,10,'Toppkasko3.1','Startleie','oppgjørsmodell','Forholdsmessig etter resterende leiemåneder;3år/100000km/>80%',COARSE,['nyverdi.begrensning'],'P1',note='Leaset kjøretøy unntatt nyverdi,men egen startleieregel med grenser er dokumentert. Katalog bare henviser til egenregel uten innhold.',status='LIMITATION')
fact(p,f,9,'Toppkasko2.1.3 og side10/4.3','Interiørrens','sum/egenandel/bonus','10000kr;1000kr egenandel;ingen bonustap;plutselig søl,ikke rifter/elektronikk',MISSING,[],'P2',note='Ligger i navngitt Toppkasko Bobil,ikke overført fra Bil. Nested provider-detalj,ikke universell motpart.')
fact(p,f,9,'Toppkasko2.1.2 og side10/4.2','Ladekabel','el/hybrid','10000kr/1000kr egenandel;bare el/hybrid,ikke fastmontert bygning',MISSING,['ladekabel.grense','ladekabel.egenandel'],'P2',note='Betinget del av uttrykkelig Bobil-fullvilkår;bare relevant når bobilen er el/hybrid,ikke ny Bil-dekning.',status='LIMITATION')
review(p,[f],'Side1–5,8–13 lest;6–7 ikke attestert på grunn av avkortet output. Topp-regler motkontrollert. Add-onkilder og DNBHTML gjenstår;ordinary-dnb ikke slått sammen med andrekanaler.',depth='TARGETED_SECTION_REVIEW')
