from continue_audit import *
A=Audit();I=load('fremtind-pet-independent-inventory.json');B='catalog/sources/boat-pet/'
A.root('SCRC-059','Fremtind dyr har foreldrefacts som utelater prosentegenandel, ventetid, sublimits og sykdomsvilkår. Hund base/Topp er ikke tilstrekkelig dimensjonert; MR/CT årsgrense feilaktig presentert som valgt sum, allergi bare tilvalg, og livsfradrag mangler niårsgruppe.','40 source-first rules acrossvet3/2p,life/use1p,IPIDs,SB1pages;exact2productsand4addons;runtimeoptional/base finding verified.',['Hund','Katt'],['sparebank1-fremtind'],'RB-55',kind='ADDON',complexity='SMALL_CODE')
K={1:['dyr.veterinar.dekning','dyr.geografi'],2:['dyr.karenstid'],3:['dyr.veterinar.sum.valgbar'],4:['dyr.veterinar.dekning','dyr.medisin.dekning'],5:['dyr.allergi.dekning','dyr.allergi.grense'],6:[],7:['dyr.diagnostikk.grense'],8:[],9:['dyr.tann.dekning','dyr.tannsykdom.dekning'],10:['dyr.tann.dekning','dyr.tannsykdom.dekning'],11:[],12:[],13:[],14:['dyr.veterinar.dekning'],15:['dyr.rehabilitering.dekning'],16:[],17:[],18:['dyr.veterinar.egenandel.fast','dyr.veterinar.egenandel.prosent','dyr.veterinar.egenandel.periode'],19:[],20:[],21:['dyr.allergi.dekning','dyr.allergi.grense'],22:['dyr.diagnostikk.dekning','dyr.diagnostikk.grense'],23:['dyr.tannsykdom.dekning'],24:['dyr.rehabilitering.dekning'],25:['dyr.liv.dekning'],26:['dyr.liv.dekning'],27:['dyr.liv.reduksjon.start','dyr.liv.reduksjon.sats','dyr.liv.opphor'],28:['dyr.liv.reduksjon.start','dyr.liv.reduksjon.sats','dyr.liv.opphor'],29:['dyr.liv.forsvinning','dyr.liv.tyveri'],30:['hund.bruksverdi.dekning'],31:['hund.bruksverdi.dekning'],32:['hund.bruksverdi.alder'],33:[],34:['dyr.veterinar.digital'],35:['dyr.liv.dekning'],36:[],37:[],38:['dyr.veterinar.egenandel.fast'],39:['dyr.liv.reduksjon.start','dyr.liv.opphor'],40:[]}
why={1:'Verden/Nordenpersonkrets/navngittogførstesymptom mangler iinkludertparent.',2:'20/60ventetid ogflytte/utvidelsesregler mangler.',3:'Årssum erbevisriktig;webvalgmengde girvalgstrukturikkeantatt sum.',4:'Medisin ogvaksine/kastreringskomplikasjon ikke presist representert.',5:'Baseallergi15000livstid finnes, men eneste allergycoverage liggeriToppoptional; runtimeviserbaretilgjengeligtillegg. Detteerstatus/lagmismatch.',6:'Artrose/spondylose15000livstid finnesogsåmedTopp utenoverride, men katalogmangler.',7:'Hundbase15000/år er erstattet medbarevalgt sum;Topp kanfjerne15000sublimit. Katt15000/år korrekt.',8:'2000avliving/kremeringmeddekketdiagnose mangler.',9:'Ulykkestann ogbase-negative sykdomsliste savnes;Topp skalhaegenutvidelse.',10:'Katt positivetann og15000resorpsjonlivstid/før4mndkrav manglerhelt.',11:'Leddsykdom tidliguavbrutt ogHundforeldrefrihet er vesentlige vilkår utenrepresentasjon.',12:'Hundkeisersnitt1gang20mnd1årNKKograsenegativer mangler.',13:'Kattkeisersnitt1gang1år/ikketo før mangler.',14:'Konkrete sykdoms-/behandlingsnegativer mangler.',15:'Base rehabnegativ ogfôr/forebygging/transport mangler;ikkekorrigerToppvalgtilbaserehab.',16:'Hundensnavngitteraseunntak mangler.',17:'Kattensraseunntak mangler.',18:'Fastdelog135d finnes;20%restetterfast mangler;Katt4000vsweb3500 er separatkonflikt.',19:'ID/alder/rase/utenlandsdokumentasjon/oppgjør ikke konkret, administrativedeler kanliggeikilde.',20:'Livslangvet/ikkealdersopphør ogvedeierskifte er ikke representert.',21:'Toppvalgfri korrekt menårsgrenseogoverridefralivstidbase ikke representert.',22:'Toppvalgfri korrekt;egenMRCTlimitoverride mangler. Generiskbasevalgt sum harfeilproduktscope.',23:'Topp tannkunvalgfri utenunder4mnd/attest7uker–4mnd ogpositivelidelsestyper.',24:'Topp rehabkunvalgfri uten6mndfrarekvisisjon ogaktuellårssum.',25:'Livvalgfri korrekt;avliving kunveterinærdekketårsak ikke konkret.',26:'Livbevis/markedsverdioppgjør er ikke konkret.',27:'Katalogfradrag5/7 utelaterden9årigegruppen;rasegrupper/gulv1500oghovedforfall ikke presist.',28:'Tall7/12og20riktig;hovedforfall ogminimum1500 mangler.',29:'Politi/annonse/3mndkarens er ikke med i inkludert-når-valgt.',30:'Barevalgfri, mangler dokumentasjon/utredning/hvile/siste12mndbruk.',31:'50%jakt/gjeter/tjeneste vs100%avl ogkull2årNKK/utstillingsnegativ mangler.',32:'Hovedforfalletter8årkorrekt;bevisvalgogvanligopphør ikke egengap.',33:'Kjøpsalder/flytting7–10/IDkrav mangler.',34:'FirstVetfri bruk mangler.',35:'Bare rasekatt liv mangler i tilgjengelighet/coverage.',36:'Valpekull finnes ioffisieltIPID/web, men ikke katalogtillegg. Fullrider manglerlokalt;brukbarewebreglerogqueue.',37:'Topputvidelseplassering oglivseparat errett, ingen egenToppmainproduktkreves.',38:'Valg4000full vs3500web erkonfliktikkesikker feil.',39:'Hovedforfalletterfødselsdagvsdetåret ibeggeweb er boundarykonflikt;ikkeforenkle.',40:'Medlemsrabatt oginnbo/reiseFAQerikkeordinaryveterinærdekninger.'}
rows={}
for animal in ['dog','cat']:
 pid='sparebank1-fremtind-'+('hund'if animal=='dog'else'katt')+'-veterin-r';p=A.p[pid];paths={d:B+f'fremtind-{animal}-{d}-terms.pdf'for d in ['vet','life','use']};paths['web']=B+f'fremtind-sb1-{animal}-product.html';paths['ipid']=B+f'fremtind-{animal}-ipid.pdf';used={paths['ipid']}
 for n,q in enumerate(I['rules'],1):
  if q['animal']not in ['both',animal]:continue
  comp=''if q['component']=='base'else 'sparebank1-fremtind-'+('hund'if animal=='dog'else'katt')+'-'+{'topp':'topp','life':'liv','use':'bruk','puppy':'valpekull'}[q['component']]
  fs=p['facts'] if not comp else p['addonFacts'].get(comp,[]);keys=K[n];cls=COARSE if any(f['key']in keys for f in fs)else MISSING;pri='P2'if n in {1,14,19,26}else'P1';reason=why.get(n,'Eksaktregelrepresentert.');source=paths[q['doc']];used.add(source)
  if n==3:cls=CUSTOM;pri=''
  if n==7 and animal=='cat' or n==32:cls=PRESENT;pri=''
  if n in [37,40]:cls='SOURCE_ONLY_ACCEPTABLE';pri=''
  if n in [38,39]:cls='SOURCE_CONFLICT_REVIEW_REQUIRED';pri='P1'
  if n==5 or n==7 and animal=='dog' or n==27:cls='CATALOG_FACT_SEMANTICALLY_MISMAPPED'
  if n==36:cls='SOURCE_FACT_OPTIONAL_COMPONENT'
  rows[(animal,n)]=A.fact(pid,q['subject'],q['dimension'],q['value'],source,q['location'],cls,keys,pri,reason,'SCRC-059',component=comp,inventory_id=q['id'],extra={'source_first_inventory':'fremtind-pet-independent-inventory.json','catalog_component_exists':comp in p['addonFacts']if comp else True})
 fs=p['facts']+sum(p['addonFacts'].values(),[])
 A.reverse(pid,{f['key']:{'locations':[{'artifact':B+f['source']['filename'],'section':f['source'].get('section'),'page':f['source'].get('page')}]}for f in fs})
 for cl in A.support:
  if cl['product_identity']!=p['identity']:continue
  badn=7 if animal=='dog'and cl['key']=='dyr.diagnostikk.grense'else 27 if animal=='dog'and cl['key']=='dyr.liv.reduksjon.start'else 38 if animal=='cat'and cl['key']=='dyr.veterinar.egenandel.fast'else None
  if badn:
   f=rows[(animal,badn)];cl.update(full_claim_validated=False,support_status='SOURCE_CONFLICT_REVIEW_REQUIRED'if badn==38 else'SEMANTIC_SCOPE_OR_BOUNDARY_MISMATCH',source_fact_ids=[f['source_fact_id']],finding_ids=[f['finding_id']],manual_reverse_evidence={'artifact':f['source_artifact'],'location':f['source_location'],'reason':f['reason']})
   if badn!=38:A.a['unsupported_catalog_claims']['proven'].append(dict(cl))
 A.product_review(pid,sorted(used),True,'40source-first rules exactanimal/base/component; all fullPDFandmaterialHTML reviewed.4registeredaddonschecked inclToppinheritance. Missingvalpekullcatalogcomponent fromsourceflagged withoutinventingfullrider. DogMRCTbase andlife9yr defectproven;sourceconflicts retained.')
for ad in A.a['addon_coverage']:
 if ad['addon_id']in ['sparebank1-fremtind-hund-topp','sparebank1-fremtind-hund-liv','sparebank1-fremtind-hund-bruk','sparebank1-fremtind-katt-liv']:ad.update(status='COMPLETE_WITH_RECORDED_GAPS',fully_audited=True,notes='Fullnamed2025component/sourcewebsite/availability/optionalstatus reviewed. Limits, waiting andqualificationgaps recorded; noactualcustomerselection.')
for i,claim,obs in [(67,'Katt fixed deductible options','Cat§8 1300/2000/4000 versusSB1page1300/2000/3500;same135d+20mechanism.'),(68,'Pet life expiry boundary','Full firstrenewalAFTERattainedage;webalsofirstrenewalINyearofage. Not necessarilysamedate;flag precisely.')]:
 A.a['source_conflicts'].append(dict(id=f'SC-{i:03d}',provider='sparebank1-fremtind',family='Hund/Katt',product='sparebank1-fremtind-pet',sources=[B+'fremtind-cat-vet-terms.pdf',B+'fremtind-sb1-cat-product.html',B+'fremtind-dog-life-terms.pdf',B+'fremtind-sb1-dog-product.html'],claim=claim,observed=obs,status='SOURCE_CONFLICT_REVIEW_REQUIRED',action='Obtain channel clarification;no arbitraryresolution.'))
A.a['source_research_queue'].append(dict(queue_id='fremtind-pet-puppy-and-conflicts',product='sparebank1-fremtind-hund/katt',reason='Missingpuppyfullterms;fixedcatdeductibleandlifeboundaryconflicts',external_source_needed_if_unresolved='Valpeforsikring rider;precisedatedchannel terms fordeductible/expiry',downloaded=False))
V=load('verified-false-unknowns.json');x=load('runtime-fremtind-pet-probe.json')[1];r=x['forward'][0];rr=x['reverse'][0];assert r['first']['state']=='unknown'and rr['second']['state']=='unknown';f=rows[('dog',5)]
V.append(dict(product_identity=x['left'],key=r['key'],peer_identity=x['right'],display_state='unknown',display_text=r['first']['text'],source_fact_ids=[f['source_fact_id']],finding_ids=[f['finding_id']],side_swap_consistent=True,cause='Base15000lifetimeallergysublimitabsent;addonavailabilitydoesnotrepresentbasecoverageorlimit.',source_scope_note='Dogvet§7p1',probe='runtime-fremtind-pet-probe.json'))
save('verified-false-unknowns.json',V);A.a['catalog_counts']['verified_visible_false_unknown_cases']=len(V);A.a['blindspot_validation']['visible_false_unknowns']=V
A.checkpoint('Fremtind pets complete available-local review: base/Topp diagnostic/allergy and life age defects proven; all initially unstarted products now reviewed','Bil','storebrand','PARTIAL_REVIEW_QUEUE')
