from continue_audit import *
A=Audit();I=load('if-motor-independent-inventory.json')
M='catalog/sources/if/Kjoretoyforsikring-MOT2-2.pdf';G='catalog/sources/if/innbo/If_Generelle_vilkar_GEN2-9.pdf'
A.root('SCRC-036','Ifs lokale felles- og særvilkår inneholder rådgiverrelevante detaljer som mangler eller er for grovt representert i eksakte kjøretøyprodukter. Bil mangler blant annet ordinær nyverdi, mens MC/Bobil har denne fra samme hovedvilkår.','if-motor-independent-inventory.json; if-catalog.ts kontra MOT2-2 §8.4.2; source-first gjennomgang av full lokal motorpakke.',['Bil','MC','Bobil','Snøscooter','Campingvogn','Tilhenger'],['if'],'RB-32')
K={1:['geografi.dekning','geografi.rettshjelp'],2:[],3:['ansvar.dekning','ansvar.egenandel'],4:['ulykke.invaliditet','ulykke.dod','ulykke.avtalevilkar'],5:['ulykke.omfang','ulykke.unntak'],6:['ulykke.dod'],7:['rettshjelp.dekning'],8:['rettshjelp.grense'],9:['rettshjelp.egenandel'],10:['rettshjelp.begrensning'],11:['brann.dekning','brann.unntak','natur.dekning'],12:['tyveri.dekning','haerverk.dekning'],13:['glass.dekning','glass.grense.bytte','glass.unntak'],14:['glass.egenandel.bytte','glass.egenandel.reparasjon'],15:['tilbehor.bagasje.grense'],16:['tilbehor.bagasje.unntak'],17:['veihjelp.dekning'],18:['veihjelp.transport.grense','veihjelp.unntak'],19:['veihjelp.egenandel','bonus.delkasko'],20:['brann.egenandel','tyveri.egenandel'],21:['kasko.dekning'],22:['kasko.egenandel','bonus.kasko'],23:['avtale.forsikringssum'],24:['nyverdi.alder','nyverdi.km','nyverdi.skadegrad'],25:['nyverdi.unntak'],26:['avtale.begrensning'],27:['avtale.bruksomrade'],28:['kjoretoy.kjorelengde','avtale.forer'],29:['reparasjon.garanti'],30:['maskinskade.dekning','maskinskade.km'],31:['maskinskade.dekning','maskinskade.fossil','maskinskade.el','maskinskade.drivverk'],32:['maskinskade.unntak'],33:['maskinskade.egenandel','maskinskade.fradrag'],34:['maskinskade.oppgjor'],35:['leiebil.vilkar','leiebil.unntak'],36:['leiebil.dager'],37:['leiebil.bilklasse','leiebil.kontant'],38:['leiebil.kondemnasjon','leiebil.kontant'],39:['leiebil.vilkar'],40:['nyverdi.alder','nyverdi.km','nyverdi.skadegrad'],41:['nyverdi.unntak'],42:['leasing.startleie'],43:['bilnokkel.dekning','ladekabel.dekning','feilfylling.dekning'],44:['parkering.grense','bilnokkel.egenandel','ladekabel.egenandel','bonus.uhell'],45:['parkering.dekning','parkering.grense','parkering.egenandel','bonus.parkert'],46:[]}
full={1,6,9,11,13,14,15,19,20,21,30,31,33,35,36,37,40,42}
reason={3:'Lovmekanismen er grovt norsk; gunstigere EØS-/utenlandsregel og 0egenandel mangler.',4:'Sum og avtalevilkår er med; betalte passasjerer er unntatt og invaliditet følger grad, uten tydelig katalogregel.',5:'Katalogen har sentrale unntak, men sykdomsutløst ulykke og arrterskel15% mangler.',7:'Rettshjelpparenten mangler etter-salg/retur og rolleavgrensning.',8:'Den generelle vilkårskilden er lokalt tilgjengelig og eksplisitt innlemmet viaMOT§12.5, men100k/250k mangler.',10:'Materielle tvistbegrensninger mangler; dette er ikke at kilden er taus.',12:'Underslag ved salg er representert, men husholdning/annen underslag-avgrensning mangler.',16:'Objektunntak er med; låsing/verdigjenstander i bilen mangler.',17:'Veihjelputløsere finnes, men lovlig tilgjengelig sted/nærmeste egnete verksted er ikke spesifisert.',18:'50% og garantiunntak er med;5k tanktømming og >3d hjemtransport mangler.',22:'Standardegenandel er korrekt;2k reduksjon/bonusvern ved dokumentert dyrepåkjørsel mangler.',23:'Materielt oppgjørsgrunnlag/kontantarbeidsfradrag/avtalt sumstruktur mangler.',24:'Ordinær nyverdi1år/15k/80% mangler helt i IfBilDelkasko/Kasko selv om egetMOT§8.4.2 dokumenterer.',25:'Ordinære nyverdiforutsetninger mangler sammen med dekningen.',26:'Materiale vær/slitasje/tuning-unntak utenfor maskinkomponent er ikke representert.',27:'Bane/is/utleie-avgrensning mangler; Super har noe eget unntak men ikke dette fulle bruksomfanget.',28:'Kundevalgt årlig kjørelengde skal forbli ukjent; risiko-konsekvens ved overskridelse/ungfører mangler som produktregel.',29:'Livslang begrenset karosserireparasjonstrygghet er kildebelagt men ikke katalogført.',32:'Noen store unntak finnes, men klima/garanti/software/eksternladekabel mv er utelatt fra grov liste.',34:'Dokumenterte vedlikeholdskrav og uttrykkelig utelukkelse av nyverdioppgjør mangler.',38:'10d etter tilbud og kontantalternativ finnes; starttid/tyverigjenfunnforløp er forkortet bort.',39:'7d avklaring finnes; ekstra15d ved skade/tyveri utenforNorden mangler.',41:'Gjenkjøpsvilkår og at totaltyveri følger ordinær8.4regel mangler; nyverdipåstand kan ellers leses for bredt.',43:'Barnedekninger finnes; krav om kjent nøkkeltid/årsak og fastladestasjon-unntak er ikke knyttet eksplisitt til Super-barn.',44:'20k er pakket under parkering;1kegenandel ligger bare feilfylling, ikke nøkkel/ladekabel, og bonusfriheten for Uhell mangler.',45:'Parkering er rikt representert; straks-meldingskravet mangler.'}
for tier in ['ansvar','delkasko','kasko','super']:
 pid='if-bil-'+tier;p=A.p[pid];rows=[]
 for q in I['rules']:
  if 'bil' not in q['types']:continue
  n=int(q['id'][-3:]);scope=q['scope']
  if scope=='physical' and tier=='ansvar' or scope in ['kasko','machine','rental'] and tier not in ['kasko','super'] or scope=='super' and tier!='super':continue
  if n in [24,25] and tier=='super':continue
  comp='if-motor-gir' if scope=='machine' else 'if-leiebil' if scope=='rental' else ''
  cls=PRESENT if n in full else COARSE if any(f['key'] in K[n] for f in p['facts']+sum(p['addonFacts'].values(),[])) else MISSING
  pri='' if cls==PRESENT else 'P1'
  if n in [4,5,10,12,16,17,22,23,27,28,32,38,43,45]:pri='P2'
  if n==2:cls=CUSTOM;pri=''
  if n==46:cls=ADMIN;pri=''
  f=A.fact(pid,q['subject'],q['dimension'],q['value'],G if q['source']=='general' else M,q['location'],cls,K[n],pri,reason.get(n,'Kontrollert mot eksakt lokal hovedvilkårsregel; representasjonen bevarer denne dimensjonen.'),'SCRC-036',component=comp,inventory_id=q['id'],extra={'source_first_inventory':'if-motor-independent-inventory.json','customer_mode_impact_class':'LIKELY_SHARED_WITH_CUSTOMER_MODE' if pri else 'UNKNOWN'})
  rows.append(f)
 rev={}
 for f in p['facts']+sum(p['addonFacts'].values(),[]):
  evidence=[x for x in rows if f['key'] in x['proposed_keys']]
  if not evidence:
   extra={'bonus.kasko':('20 pkt9.4','Ansvar/Kasko kan gi bonustap.'),'feilfylling.egenandel':('12 pkt4.11.3' if tier=='super' else '19 pkt8.5.5','Eksakt egenandel ved relevant nivå.'),'super.unntak':('11 pkt4.11','Egne Super-bruksbegrensninger.')}
   if f['key'] in extra:
    loc,val=extra[f['key']];evidence=[A.fact(pid,'Reverse '+f['key'],'egen påstand',val,M,loc,PRESENT,[f['key']],inventory_id='IF-BIL-REVERSE-'+f['key'])]
  if evidence:rev[f['key']]={'locations':[{'artifact':x['source_artifact'],'location':x['source_location']} for x in evidence],'note':'Eksakt eksisterende påstand støttet; ikke generell attest om at alle dimensjoner er komplette.'}
 A.reverse(pid,rev)
 A.product_review(pid,[M,G],True,'MOT2-2 samtlige26sider og eksplisitt innlemmetGEN2-9 lest kilde-først. Eksakt Ansvar/Delkasko/Kasko/Super inklbegge reelle tillegg reversekontrollert. Ordinær nyverdi og flere materielle detaljer mangler; kundevalg beholdes. Ingen online freshness-påstand.')
for ad in A.a['addon_coverage']:
 if ad['addon_id'] in ['if-leiebil','if-motor-gir']:ad.update(status='COMPLETE',fully_audited=True,source_artifacts=[M],review_notes='FullMOT4.9/4.10 lest, alle egne katalogpåstander kontrollert, materielle mangler registrert; valgfri status riktig.')
V=load('verified-false-unknowns.json');probe=load('runtime-if-motor-probe.json')[0]
for key in ['nyverdi.alder','nyverdi.km']:
 row=next(r for r in probe['forward'] if r['key']==key);rev=next(r for r in probe['reverse'] if r['key']==key)
 assert row['first']['state']==rev['second']['state']=='unknown'
 fs=[f for f in A.f if f['product']=='if-bil-kasko' and f['source_first_inventory_id']=='IF-MO-024']
 if not any(v['product_identity']==probe['left'] and v['key']==key for v in V):V.append(dict(product_identity=probe['left'],key=key,peer_identity=probe['right'],display_state='unknown',display_text=row['first']['text'],source_fact_ids=[f['source_fact_id'] for f in fs],finding_ids=[f['finding_id'] for f in fs],side_swap_consistent=True,cause='Egen fullkildeMOT2-2§8.4.2 støtter ordinær nyverdi; eksaktIfBilKasko base+tillegg mangler alle tilsvarende fakta.',source_scope_note='Gjensidige brukes kun som visningsprobe; If-kildens egne regler begrunner funnet.',probe='runtime-if-motor-probe.json'))
save('verified-false-unknowns.json',V);A.a['catalog_counts']['verified_visible_false_unknown_cases']=len(V);A.a['blindspot_validation']['visible_false_unknowns']=V
A.checkpoint('If Bil 4 produkter og 2 tillegg gjennomgått; ordinær nyverdi er kildebelagt men vises ukjent','MC','if','if-mc-ansvar')
