from continue_audit import *
A=Audit();I=load('fremtind-boat-independent-inventory.json');B='catalog/sources/boat-pet/';paths={'terms':B+'fremtind-boat-terms.pdf','web':B+'fremtind-sb1-boat-product.html'};ipid=B+'fremtind-boat-ipid.pdf'
A.root('SCRC-058','Fremtind Båt minikasko har svært få facts selv om fullvilkår dokumenterer redning, natur, løsøre, utstyr og ulykke. Kasko/Topp mangler detaljerte summer, kvalifikasjoner og aldersfradrag.','46 source-first rules;full12p,IPID2p,SB1HTML; three exactproducts fullycompared;presentation probes verifyactualunknowns.',['Båt'],['sparebank1-fremtind'],'RB-54')
K={1:[],2:['bat.geografi.omrade'],3:[],4:['bat.utstyr.grense','bat.losore.grense'],5:[],6:['bat.ansvar.dekning'],7:['bat.ulykke.dekning'],8:['bat.brann.dekning'],9:['bat.naturskade.dekning'],10:['bat.tyveri.dekning'],11:['bat.transport.dekning'],12:['bat.redning.dekning','bat.redning.egenandel'],13:['bat.vrakfjerning.dekning'],14:[],15:[],16:['bat.tyveri.dekning'],17:['bat.losore.grense'],18:[],19:['bat.utleie.dekning'],20:[],21:['bat.ansvar.grense'],22:['bat.ansvar.dekning'],23:['bat.ansvar.dekning'],24:['bat.losore.grense','bat.jolle.grense'],25:['bat.kasko.dekning','bat.transport.dekning'],26:['bat.kasko.dekning'],27:['bat.ferieavbrudd.dekning','bat.ferieavbrudd.dager','bat.ferieavbrudd.dagsbelop'],28:[],29:['bat.losore.grense'],30:['bat.ferieavbrudd.dekning','bat.ferieavbrudd.dager','bat.ferieavbrudd.dagsbelop'],31:[],32:['bat.maskinskade.dekning','bat.maskinskade.alder'],33:['bat.maskinskade.dekning'],34:[],35:['bat.maskinskade.egenandel'],36:['bat.totalskade.dekning','bat.totalskade.alder'],37:['bat.ulykke.dekning','bat.ulykke.dod','bat.ulykke.invaliditet'],38:['bat.ulykke.dekning'],39:['bat.rettshjelp.dekning'],40:['bat.rettshjelp.dekning'],41:[],42:['bat.utleie.dekning'],43:[],44:['bat.maskinskade.alder'],45:[],46:[]}
why={1:'14d eierskifte/personkrets mangler.',2:'200nm ogdokumenterteoverfarter finnes, men listen ogNordenredning ikke konkret.',3:'Kundebevis skal gi egenandel;ingenantatt sum.',4:'50000løsøre/20000ekstrautstyr ogkonkreteunntak mangler.',5:'Vannscooterplattform er typespesifikk ogskalikkebli allebåtersbenefit.',6:'Ansvar inkludert, men ervervavgrensning ikke konkret.',7:'Fører-/passasjerulykke helt fraværende.',9:'Naturskade ogde fem triggerne mangler.',11:'Mini dekker transportetterdekketskade selvutenKasko;Kaskotransportharbredereutløsere.',12:'Delkaskoredning mangler helt;andre nivåer mangler Norden/750egenandel/tryggfortøyning/bergelønn.',13:'Pålagtvrakfjerningetterdekketskade ikke representert.',14:'Sum er kundensbevis/markedsverdi;skalikkefyllesgenerisk.',15:'Reparasjonsoppgjør og50%kontantarbeid mangler.',16:'21dventetid ikke uttrykt.',17:'Dokumentasjon/aldersfradrag mangler.',18:'Firekonkretealdersrader10%max60% mangler.',19:'Utleiekreveravtale;webkanaltilbudogvarslingegenregel.',20:'4000sikringsreduksjon mangler.',21:'Ekstra millionord gir uavklart enhet;ingeneksternlovresearch tillatt og ingenverifisertsum her.',22:'Viktigeansvarsunntak mangler.',23:'Økonomisktap etterfysiskskade/egnekosti tillegg savnes.',24:'100000samletløsøre/tilbehør ogjolle50000/12fot/15HK mangler.',25:'KunKaskoparent;dieseldyr/feilfylling/seilregatta/mastbom ogsjøsetting ikkepresist.',26:'Motorskadealene/frostis/næring/utleie/garanti ogboblehavnunntak mangler.',27:'1000/10d riktig;>3d/normalrep/godkjenning/utgiftstyper mangler.',28:'Under23ikkeforsikringstaker+6000 mangler.',29:'Toppubegrensetløsøreheltfraværende.',30:'1500/15d riktig;>3d/normalrep/godkjenning/utgiftstyper mangler.',31:'Avbruttbåtturperson/hjemreise erikkeferieavbrudd ogmangler.',32:'Parent sierbegrensningerutenåvise10år/komponenttyper/varmgangtriggerogutredning;webalderkonfliktregistrertseparat.',33:'Konstruksjon/korrosjon/isogjolleunntak mangler.',34:'Skadetstativ/presenning/krybbe mangler.',35:'4000medfradragsregel henviseruten1frår10%max60%/egenandelfritak/bruktedeler.',36:'Inkludert uten3årkjøpnyog>60%terskel/båtogmotorseparat.',37:'100000/200000/15000 mangler.',38:'Behandling2år/barn3år/1000egenandel/død1år ogvesentligeunntak mangler.',39:'Kuninkludertrettshjelp uten100/250k ogegenandelbevis20/særgrenser.',40:'Viktige tvisteavgrensninger mangler.',41:'Valg4000/7000/10000beskriverkundensvalgstruktur;skalikkeantaresultat.',42:'Kanal tilbyr2mndgratis medmeldeplikt;fullkreveravtale. Sikkerregel erbetingettilbudikke ubetingetkundeleie.',43:'Registreringover50000 er kjøpskrav;eksaktgrense lik50000uklar.',44:'Motoralder vsbåtalder og<versus≤10 kreveravklaring;FAQjolleToppmotKaskofull/matrix. Ikkeinnførfeilnegative.',45:'Sesong/pris/medlemsrabatt er ikke fastordinarydekning.',46:'Administrativ kontraktmekanikk behøverikke detaljmodellering.'}
added={}
for pid in ['sparebank1-fremtind-bat-delkasko','sparebank1-fremtind-bat-kasko','sparebank1-fremtind-bat-toppkasko']:
 p=A.p[pid];top=pid.endswith('toppkasko');kasko=not pid.endswith('delkasko');fs=p['facts']
 for n,q in enumerate(I['rules'],1):
  if q['scope']=='kasko'and not kasko or q['scope']=='top'and not top:continue
  if n==27 and top:continue
  if n==4 and kasko: # equipment20k stillapplies, contents ownlevel rule below
   value='Fastmontert tilleggsutstyr20000 i tillegg tilavtaltsum; mobil/cash/papir/smykke/klokke fortsattunntatt.'
  else:value=q['value']
  keys=K[n];cls=COARSE if any(f['key']in keys for f in fs)else MISSING;pri='P2'if n in {1,2,6,15,16,17,22,23,26,33,38,40}else'P1'
  if n in [8,10]:cls=PRESENT;pri=''
  if n in [3,14,41]:cls=CUSTOM;pri=''
  if n in [5,45]:cls='SOURCE_ONLY_ACCEPTABLE';pri=''
  if n==46:cls=ADMIN;pri=''
  if n==21 or n==43:cls='SOURCE_AMBIGUOUS';pri='P1'if n==21 else'P2'
  if n==44:cls='SOURCE_CONFLICT_REVIEW_REQUIRED';pri='P1'
  f=A.fact(pid,q['subject'],q['dimension'],value,paths[q['doc']],q['location'],cls,keys,pri,why.get(n,'Eksakt kilderegel representert.'),'SCRC-058',inventory_id=q['id'],extra={'source_first_inventory':'fremtind-boat-independent-inventory.json'});added[(pid,n)]=f
 A.reverse(pid,{f['key']:{'locations':[{'artifact':paths['terms'],'page':f['source'].get('page'),'section':f['source'].get('section')}]}for f in fs})
 A.product_review(pid,[paths['terms'],paths['web'],ipid],True,'Full source-first46rules,all3levels,allmaterialexactclaimsupports;legalbyte-equivalenttokensreused;noaddons. Numerical SDRtyporemainsambiguous, motorvsboatageconflictqueued. No unsupported P0assumed. Complete available-local review with explicit conflicts.')
for idx,claim,obs in [(65,'Ansvar SDR unit','Fullp4contains3020000millioner/1510000millionSDR;not safe to silently repairunit. Officialclarification needed.'),(66,'Motor age and product-level FAQ','FullTopp≤10yearmotor/seil;webFAQ<10yearboat. FAQimpliesjolle/holidayToppbutmainmatrix/fullKasko. Conflicts preserved.')]:
 A.a['source_conflicts'].append(dict(id=f'SC-{idx:03d}',provider='sparebank1-fremtind',family='Båt',product='sparebank1-fremtind-bat-*',sources=list(paths.values()),claim=claim,observed=obs,status='SOURCE_CONFLICT_REVIEW_REQUIRED',action='Official source clarification required; no external browsing in current audit.'))
A.a['source_research_queue'].append(dict(queue_id='fremtind-boat-unit-age',product='sparebank1-fremtind-bat-*',reason='SDRunit typo and motor/vessel-age conflict',external_source_needed_if_unresolved='Corrected officialfullterms and exactchannel FAQ clarification',downloaded=False))
V=load('verified-false-unknowns.json')
for x in load('runtime-fremtind-boat-probe.json'):
 pid=next(p['productId']for p in A.p.values()if p['identity']==x['left'])
 for row in x['forward']:
  if row['key']=='bat.maskinskade.alder':continue # source age object conflict: not verifiedfalseunknown
  n={'bat.redning.dekning':12,'bat.losore.grense':24,'bat.totalskade.alder':36}[row['key']];sf=added[(pid,n)];rev=next(r for r in x['reverse']if r['key']==row['key']);assert row['first']['state']=='unknown'and rev['second']['state']=='unknown'
  V.append(dict(product_identity=x['left'],key=row['key'],peer_identity=x['right'],display_state='unknown',display_text=row['first']['text'],source_fact_ids=[sf['source_fact_id']],finding_ids=[sf['finding_id']],side_swap_consistent=True,cause='Exact source-backed rule missing in all resolved/component facts; presentationunknownconfirmed.',source_scope_note=sf['source_location'],probe='runtime-fremtind-boat-probe.json'))
save('verified-false-unknowns.json',V);A.a['catalog_counts']['verified_visible_false_unknown_cases']=len(V);A.a['blindspot_validation']['visible_false_unknowns']=V
A.checkpoint('Fremtind Boat three levels reviewed; source-backed redning, contents and new-value visible unknowns verified; source age/unit ambiguities retained','Hund','sparebank1-fremtind','sparebank1-fremtind-hund-veterin-r')
