from continue_audit import *
A=Audit();pid='storebrand-reise-standard';path='catalog/sources/storebrand/reise/canonical/reise10-vilkar-reiseforsikring.pdf';web='catalog/sources/storebrand/reise/canonical/Reiseforsikring-produktside.html';ipid='catalog/sources/storebrand/reise/canonical/IPID-reiseforsikring.pdf'
A.root('SCRC-020','An overnight/day-trip dimension is present inside Storebrand geography free text but is absent from the explicit overnight comparison key. Key-based comparison legitimately does not reinterpret narrative; advisor sees an avoidable unknown alongside known equivalent information in another row. Tryg overnight text also combines journey purpose, which must not be inferred for Storebrand.','lib/catalog-product-comparison.ts:222,257–260;runtime-reise-overnatting-probe.json;StorebrandownHTMLFAQdaytrips+B1.2;exactStandardbasefactreise.omrade.verden.',['Reise'],['storebrand'],'RB-18',kind='CANONICAL_MAPPING',complexity='SMALL_CODE')
f=A.fact(pid,'Reise med eller uten overnatting','generelt overnattingskrav','Generelt overnattingskrav: nei. Dagstur er omfattet. B.1.2reise frafolkeregisteradresse/tilbake, B.1.3stedsspesifikkeunntak. AvbestillingsarrangementB.2.1 ogSuperleiebilC1har egneovernattingsvilkår som ikke endrer generelldefinisjon.',web,'HTMLFAQ Når gjelder reiseforsikringen?','STRUCTURAL_MAPPING_GAP',['reise.omrade.verden','reise.overnatting'],'P1','Katalogen kjenner dagstur i geografifaktum menovernattingsraden blirunknown. Strukturertdimensjon bør uttrykkes eksplisitt utenUIteksttolking; ikke kopierTrygtjenestereiseclaim.','SCRC-020',inventory_id='USER-REISE-OVERNATTING-2026-10-01',extra={'source_truth':'OVERNIGHT_NOT_REQUIRED_GENERALLY','catalog_truth':'EQUIVALENT_MEANING_IN_OTHER_KEY','comparison_truth':'UNKNOWN_ON_REISE_OVERNATTING','presentation_truth':'VERIFIED_STRUCTURAL_FALSE_UNKNOWN','strict_verified_catalog_false_unknown':False,'strict_exclusion_reason':'Equivalent source-backed meaning already represented under geography; fails strict missing-catalog condition4, not counted in12 catalog-omissionfalseunknowns.','source_synthesis':[{'artifact':path,'pdf_page':4,'printed_page':3,'section':'B.1.2–3','evidence':'Journey beginswhenleavingregisteredaddress; namedplaceexceptions; no generalovernightcondition.'},{'artifact':path,'pdf_page':6,'section':'B.2.1','evidence':'PrepaidarrangementcancellationrequiresjourneywithovernightANDtransport; restrictedbenefit.'},{'artifact':ipid,'pdf_page':2,'evidence':'Worldexceptnamedlocations; no overnightrequirement.'}],'manual_review_not_restarted':True})
g=next(x for x in A.a['findings'] if x['finding_id']==f['finding_id']);g.update(remediation_type='CANONICAL_MAPPING',remediation_complexity='SMALL_CODE',customer_mode_impact='UNKNOWN',proposed_regression='TrygEkstra/PremiumvsStorebrandStandard inbothdirections: daytripknowledge aligned to general overnightdimension; no inferredbusiness/cancellation/leiebil entitlement.',no_shared_engine_bug_proven=True)
raw=load('runtime-reise-overnatting-probe.json');snap=[]
for x in raw:
 a=next(r for r in x['rows'] if r['key']=='reise.overnatting');b=next(r for r in x['rows'] if r['key']=='reise.omrade.verden');swap=next(r for r in x['reversed'] if r['key']=='reise.overnatting');assert a['second']['state']=='unknown' and 'Dagstur er omfattet' in b['second']['text'];snap.append({'first':x['first'],'second':x['second'],'overnight_row':{'key':a['key'],'label':a['label'],'storebrand_state':a['second']['state'],'storebrand_text':a['second']['text']},'other_row':{'key':b['key'],'storebrand_text':b['second']['text']},'side_swap_consistent':swap['first']==a['second']})
control={'id':'CONTROL-REISE-OVERNATTING-001','provider':'storebrand','product':pid,'product_identity':A.p[pid]['identity'],'scope':'ordinary','source_artifacts':[{'path':p,'sha256':A.art[p]['sha256']} for p in [path,web,ipid]],'source_location':'reise10June2025 PDF4B1.2–3 andproductHTMLFAQ','short_source_evidence':'Du og tingene dine er forsikret, enten du er på dagstur eller lengre reiser.','source_answer':'B: does not require overnight stay for general journey coverage','model_answer':'E: representation disperses dimensions across keys; not absence of sourceknowledge','scope_qualifications':'No claimallbenefitsapplywithoutovernight: B2.1eventcancellation andSupercarhire benefit requireovernight; location/medicalmunicipality exclusionsremain. Businessjourneys not inferred fromTryg.','catalog_representation':next(x for x in A.p[pid]['facts'] if x['key']=='reise.omrade.verden'),'visible_comparison_representation':snap,'classification':'STRUCTURAL_MAPPING_GAP','confidence':'HIGH','advisor_impact':'Avoidable unknown on specificovernight question despite sourceandcatalogknowingdaytripcoverage.','strict_verified_catalog_false_unknown':False,'source_fact_id':f['source_fact_id'],'finding_id':f['finding_id'],'future_presentation_requirement':{'states':['JA','NEI','IKKE DEKKET','TILVALG','BEGRENSET','UKLART I TILGJENGELIG KILDEGRUNNLAG'],'principle':'Use explicitsource-backedsemanticdimension; retain unknownforgenuineambiguity, not UIinference/free-textparsing.'},'implemented':False}
save('reise-overnatting-control.json',control);A.a.setdefault('structural_false_unknown_controls',[]).append(control)
A.a.setdefault('presentation_candidates',[]).append({'id':'PRES-QUESTION-001','concept':'question-like dimensions','evidence_control':'CONTROL-REISE-OVERNATTING-001','requirement':control['future_presentation_requirement'],'implemented':False})
A.checkpoint('New Reise overnight control: Storebrand daytrip already catalogued; key-structure mismatch reproduced, not counted as missing catalog knowledge','Snøscooter','frende','frende-snoscooter-ansvar')
