from continue_audit import *
A=Audit();I=load('fremtind-bil-independent-inventory.json');B='catalog/sources/sparebank1-fremtind/'
A.root('SCRC-051','Fremtind Bil deler detaljerte kjernekomponenter på tvers av fire registrerte provider-IDer. Materiale om veihjelpens betingede leiebil, leasing, oppgjør og kvalifikasjoner er utelatt; kanalspesifikke kilder må bekreftes separat fra generiske vilkår.','52uavhengigeregler;4nivåfullvilkår,2tillegg,V106,legacyM05P,Eikas egne lenkesider. 16exactresolvedprodukter kontrollert;8vanlige og2SB1kanaltillegg.',['Bil'],['fremtind','sparebank1-fremtind','dnb-fremtind','eika-fremtind'],'RB-47')
paths={k:B+n for k,n in {'ansvar':'Vilkar_ansvar_bil.pdf','mini':'Vilkar_Minikasko_Bil.pdf','kasko':'Vilkar_Kasko_Bil.pdf','topp':'Vilkar_Toppkasko_Bil.pdf','rental':'Vilkar_leiebil.pdf','machine':'Vilkar_maskinskade.pdf'}.items()};paths['legacy']='catalog/sources/eika-fremtind/IPID_Bil_M05P.pdf';paths['general']='catalog/sources/vehicle-extensions/fremtind-Generelle_vilkar_skadeforsikring.pdf'
K={1:[],2:['geografi.dekning'],3:[],4:['delkasko.egenandel','kasko.egenandel'],5:['bonus.regel'],6:['bonus.ordning'],7:['ansvar.dekning','ansvar.person.grense','ansvar.ting.grense'],8:['ulykke.omfang'],9:['ulykke.invaliditet','ulykke.invaliditet.barn','ulykke.dod'],10:['ulykke.invaliditet','ulykke.dod'],11:['rettshjelp.dekning','geografi.rettshjelp'],12:['rettshjelp.grense'],13:['rettshjelp.egenandel'],14:['rettshjelp.dekning'],15:[],16:['tilbehor.grense'],17:['bagasje.grense'],18:['brann.dekning'],19:['tyveri.dekning'],20:['glass.dekning'],21:['veihjelp.dekning'],22:[],23:['veihjelp.dekning','veihjelp.transport.grense'],24:['veihjelp.feilfylling.grense'],25:['nyverdi.alder','nyverdi.km','nyverdi.skadegrad','nyverdi.unntak'],26:['nyverdi.unntak'],27:['reparasjon.garanti'],28:[],29:['tyveri.dekning'],30:['bagasje.grense'],31:[],32:['kasko.dekning'],33:['kasko.dekning'],34:['kasko.egenandel','kasko.egenandel.ung','kasko.egenandel.dyr'],35:['bilnokkel.dekning','bilnokkel.grense','bilnokkel.egenandel'],36:['ladekabel.dekning','ladekabel.grense','ladekabel.egenandel'],37:['interiorrens.grense','interiorrens.egenandel'],38:['parkering.dekning','parkering.alder','bonus.parkert'],39:['feilfylling.egenandel'],40:['nyverdi.alder','nyverdi.km','nyverdi.skadegrad','nyverdi.unntak'],41:['nyverdi.unntak'],42:['leiebil.dager','leiebil.bilklasse','leiebil.dagsgrense','leiebil.godkjenning','leiebil.unntak'],43:['leiebil.kondemnasjon'],44:['maskinskade.alder','maskinskade.km'],45:['maskinskade.dekning','maskinskade.el'],46:['maskinskade.unntak'],47:['maskinskade.batteri.fradrag'],48:['maskinskade.egenandel.0-99999','maskinskade.egenandel.100000-149999','maskinskade.egenandel.150000-200000'],49:[],50:[],51:[],52:[]}
PRESENTS={9,13,18,32,34,35,38,42,43,44,48}
why={1:'14d eierskifte og panthaveravtale mangler.',2:'Europeisk unntaksgeografi korrekt; grenseforsikringsrestriksjon mangler.',3:'Avregistrering/lagringsovergang mangler.',4:'Bevisegenandel riktig; sammehendelse kunhøyeste og rekkefølge ikke representert.',5:'Hærverk/natur/dyr unntak fra bonus ikke eksplisitt i blantannetparent.',6:'Valgnevnt,men tabellprosent/ubrukt3år mangler.',7:'Tall/lovvalg riktig; kontraktsansvarnegativ mangler.',8:'At bilen må være direkte årsak og sentrale ulykkesunntak mangler.',10:'Dødinnen1år riktig;fratrekk tidligereinvaliditet og gradert1–3årsoppgjør mangler.',11:'Norden/eier riktig; tvistegrunnlagførperiode/etter salg mangler.',12:'100/250k riktig; FinKN15k/forlik25k/sakkyndig20%/interessetak mangler.',14:'Rettshjelpens materielle begrensninger mangler.',15:'Forsikredeekstrahjul/nøkkel/kabel og bygningsladekabelunntak mangler.',16:'50k/bevisverdi riktig; sikkerhetsutstyr/barneseter mangler.',17:'20k riktig;verdigjenstandsunntak mangler.',19:'Tyveri/hærverkparent,husstand/sjåførnegativ og offentligannonsebetingelse utelatt.',20:'Glassbrudd riktig;50%verditakogsolcelleunntak mangler.',21:'Veihjelpparent for grov for personsykdom/død/tyveri og billigere videreføringsvalg.',22:'Egen leiebilytelse ved dekket skade utenforNorden600/dag45d er ikke samme som valgfritt leiebiltillegg; ingen korrekt representasjon.',23:'50%tak riktig;assistansebosted/tom tank/bilmedtilhenger detaljer mangler.',24:'10ktømming riktig;motorenkanikkestartesforredningsytelsen mangler.',25:'Alder/km/80%/ikkelesingkorrekt,men markedsverdiform/sistelisteutgåttmodell utelatt.',26:'Leasinghenvisning uten startleieberegning/restmåneder.',27:'8år/3500kg/verksted/unntak riktig;garantileiebil600/dag45d+veihjelp mangler.',28:'Kontant50%arbeid/bruktedeler/MVA/garantiverditapsunntak mangler.',29:'Tyveri21dventetid/stjåletnøkkelomkoding forebyggende mangler.',30:'Minimum1/3verdifall for eiendelsfradrag mangler.',31:'Årligkjørelengdeoverstigelse og trimrisikoregler mangler.',33:'Bane/kurs/utleie/næring/frostbegrensninger mangler; maskin/rentalforblioptional i egenstruktur.',36:'10k1kriktig; fastmontert i bygning negativ mangler.',37:'10k1kriktig;utenbonus/skadetypenegativ/ordinærkaskoover10k mangler.',39:'1kriktig;bonustap eksplisitt mangler.',40:'3år100kkm80%/leasingunntak riktig;utgåttmodelloppgjør mangler.',41:'Leasingnevnt,men80%/3år100kkm/restmåneder ikke representert på leasingdimensjon.',45:'Oppregnede komponenter parent mister blantannet NOX/AdBlue/PTC-batterifunksjon og komponentavgrensning.',46:'Flere materielle unntak oppregnet,men motorolje/ledningsnett/høyvoltkabel/infotainment/baneunntak ikke konkretisert.',47:'Alder/prosenttak riktig;egenandelsrekkefølge og bruktedelerunntak mangler.',49:'Maskinskade kan ikke kontantoppgjøres; mangler.',51:'Generelle krig/terror/atomgrenser er ikke katalogisert.'}
for p in A.c['products']:
 if p['insuranceType']!='Bil'or'fremtind'not in p['providerId']:continue
 pid=p['productId'];tier=pid.split('-')[-1];physical=tier!='ansvar';kasko=tier in ['kasko','topp','toppkasko'];top=tier in ['topp','toppkasko'];fs=p['facts']+sum(p['addonFacts'].values(),[]);used={paths['ansvar'],B+'IPID_Bil.pdf',paths['general']};rows=[]
 for n,q in enumerate(I['rules'],1):
  if q['scope']=='physical'and not physical or q['scope']=='kasko'and not kasko or q['scope']=='topp'and not top or q['scope'].startswith('addon_')and not kasko:continue
  if top and n in [25,26]:continue
  keys=K[n];val=q['value'];loc=q['location'];path=paths[q['doc']];used.add(path);cls=PRESENT if n in PRESENTS else COARSE if any(f['key']in keys for f in fs)else MISSING;pri=''if cls==PRESENT else'P1';reason=why.get(n,'Eksakt sum/status/grense representert og kontrollert i lokale originaler.')
  if n in [1,2,4,5,6,7,10,11,14,15,16,23,24,25,28,30,31,36,37,39,40,46,47,49,51]:pri='P2'if cls!=PRESENT else''
  if n==50:cls='SOURCE_ONLY_ACCEPTABLE';pri='';reason='Historisk Eika M05P klart adskilt; gjeldende Eika-lenker i lagretHTMLpeker PMO/V106. Ingen nytegning fra M05P.';used.update(['catalog/sources/vehicle-extensions/eikaforsikring-vilkar.html','catalog/sources/vehicle-extensions/eikaforsikring-produktinformasjon.html'])
  if n==52:cls=ADMIN;pri='';reason='Generell kontraktadministrasjon ikke ny sammenligningsdimensjon.'
  if n==25 and tier=='delkasko':cls='SOURCE_CONFLICT_REVIEW_REQUIRED';pri='P1';reason='Nybil1år15kregel står i selveMinikaskofullvilkåret,menV106leggerNybilunderKasko i tillegg. Ikke påstå dekningen mangler/erfeil uten avklaring.'
  comp=''
  if q['scope'].startswith('addon_'):
   kind='leiebil'if q['scope']=='addon_rental'else'maskinskade';comp=next(x for x in p['addonFacts']if x.endswith('-'+kind))
  rows.append(A.fact(pid,q['subject'],q['dimension'],val,path,loc,cls,keys,pri,reason,'SCRC-051',component=comp,inventory_id=q['id'],extra={'source_first_inventory':'fremtind-bil-independent-inventory.json','channel_support_note':'Generic current named terms supported; unarchived channel-specific web statement not independently asserted.'}))
  if comp.startswith('fremtind-')and p['providerId']=='fremtind':
   comp2='fremtind-sb1-'+comp.split('fremtind-',1)[1]
   rows.append(A.fact(pid,q['subject'],q['dimension'],val,path,loc,cls,keys,pri,reason,'SCRC-051',component=comp2,inventory_id=q['id'],extra={'source_first_inventory':'fremtind-bil-independent-inventory.json','distribution_channel':'SpareBank 1','runtime_component_evidence':'runtime-fremtind-channel-probe.json'}))
 # Shared exact-base values were compared exhaustively for all16and found identical; allcorepositive/numericclaims checked with label semantics.
 A.reverse(pid,{cf['key']:{'locations':[{'artifact':B+cf['source']['filename'],'location':str(cf['source'].get('page'))+' '+str(cf['source'].get('section'))}],'note':'Whole claim including label qualifiers checked. Channel independence is source-package limitation; omitted contextual conditions recorded separately.'}for cf in fs})
 if tier=='delkasko':
  for cl in A.support:
   if cl['product_identity']==p['identity']and cl['key'].startswith('nyverdi.'):cl.update(full_claim_validated=False,support_status='SOURCE_CONFLICT_REVIEW_REQUIRED',support_scope='Minikasko full terms explicit new-value clause but IPID lists as Kasko extension; do not remove/import arbitrarily.')
 A.product_review(pid,sorted(used),True,'52 source-first rules, four full levels text-compared and all material exact resolved claims checked. Legacy/channel aliases retained in204scope. No claim of independent channel-specific page freshness: missing archivedSB1/DNBBilpagesqueued. Source review complete for available local package, not gapfree. Conditional assistance rental is distinct from optional component.')
for ad in A.a['addon_coverage']:
 if ad['addon_id']in['sb1-leiebil','sb1-maskinskade','dnb-leiebil','dnb-maskinskade','eika-leiebil','eika-maskinskade','fremtind-leiebil','fremtind-maskinskade','fremtind-sb1-leiebil','fremtind-sb1-maskinskade']:
  ad.update(status='COMPLETE_WITH_RECORDED_GAPS',fully_audited=True,notes='Generic active named add-on originals source-checked; optional Kasko/Topp, customer selection preserved. Explicit channel runtimeprobe reconciles SB1IDs excluded whenchannelNone. Independent channelweb authority remains source research limitation.')
  if ad['addon_id'].startswith('fremtind-sb1-'):ad.update(insurance_type=['Bil'],applicable_products=[A.p[x]['identity']for x in ['fremtind-bil-kasko','fremtind-bil-topp']],distribution_channel='SpareBank 1',audit_enumeration_evidence='runtime-fremtind-channel-probe.json')
A.a['source_conflicts'].append(dict(id='SC-056',provider='fremtind',family='Bil',product='*-bil-delkasko',sources=[paths['mini'],B+'IPID_Bil.pdf'],claim='Minikasko nybil',observed='Minikasko§3.2.1/3.2.2 gir1år15kkm80% og leasing;V106plasserer beggeunderKasko i tillegg.',status='SOURCE_CONFLICT_REVIEW_REQUIRED',action='Krev avklaring om utløser/produktnivå; bevarfullvilkårets positive tekst og IPIDavvik.'))
A.a['source_research_queue'].append(dict(queue_id='SR-fremtind-bil-channel-minikasko',product=[p['productId']for p in A.c['products']if p['insuranceType']=='Bil'and'fremtind'in p['providerId']],reason='Arkiverte egneSB1/DNBBilproduktsider mangler i322corpus; kommentarer/reporapporter er ikke selvstendige originaler. MinikaskoNybilnivåkonflikt motV106. Ikke konkluder identiske sluttprodukter kun fra forsikringsgiver.',external_source_needed_if_unresolved='Offisielle kanalarkiver/aktuell avtalevariant og presisert Minikasko nyverdiregel; ikke web i denne audit.',downloaded=False))
A.checkpoint('Fremtind Bil sixteen registered identities and ten channel addons source-reviewed; conditional rental gap and Minikasko source conflict retained','Innbo','fremtind','fremtind-innbo-standard')
