from continue_audit import *
A=Audit();I=load('fremtind-hus-independent-inventory.json');B='catalog/sources/fremtind/hus/canonical/'
A.root('SCRC-053','Fremtind Hus har bredt representerte summer og tillegg, men Standard har feil positiv kunstnerisk utsmykning og aldersfradrag mangler material-/hendelsesavgrensning. Flere materielle oppgjørs- og dekningsvilkår er komprimert bort.','52 uavhengige kilderegler mot begge nivå og begge tillegg; Standard s3 høyre kolonne versus Topp s1; full reversekontroll.',['Hus'],['fremtind'],'RB-49')
K={1:['hus.avtale.ipid'],2:[],3:['hus.avtale.forbehold'],4:['hus.bygninger.dekning','hus.bygninger.tilbehor','hus.bygninger.utsmykning'],5:['hus.ror.utvendig'],6:['hus.hage.objekter','hus.hage.basseng','hus.hage.brygge'],7:['hus.pabud.dekning'],8:['hus.rydding.dekning'],9:['hus.brukstap.dekning','hus.leietap.skade'],10:['hus.brann.dekning','hus.elektrisk.dekning'],11:['hus.vann.utstromming','hus.vann.terreng','hus.vatrom.folgeskade','hus.vatrom.selverommet','hus.takvegg.folgeskade'],12:['hus.ror.brudd','hus.ror.tining'],13:['hus.plutselig.dekning'],14:['hus.naturskade.dekning'],15:[],16:['hus.gjenoppforing.hovedregel'],17:['hus.gjenoppforing.hovedregel','hus.gjenoppforing.annetsted'],18:['hus.gjenoppforing.markedsverdi'],19:['hus.forsikringsform'],20:['hus.aldersfradrag.utvendige_ledninger'],21:[],22:[],23:['hus.egenandel.generell'],24:['hus.sikkerhet.egenandelsreduksjon'],25:['hus.glass.dekning','hus.hvitevarer.egenandel','hus.vann.egenandel.gjentatt_vann','hus.ansvar.egenandel','hus.rettshjelp.egenandel','hus.naturskade.egenandel'],26:['hus.ansvar.grense','hus.ansvar.dekning'],27:['hus.ansvar.dekning'],28:['hus.rettshjelp.grense','hus.rettshjelp.egenandel'],29:['hus.rettshjelp.dekning'],30:['hus.rettshjelp.dekning'],31:['hus.naturskade.dekning'],32:['hus.takvegg.folgeskade'],33:['hus.skadedyr.bygningsskade','hus.skadedyr.bekjempelse'],34:['hus.vatrom.selverommet'],35:['hus.handverker.folgeskade'],36:['hus.gjenoppforing.totalskade'],37:['hus.skadedyr.egenandel'],38:['hus.rate.dekning'],39:['hus.rate.dekning'],40:['hus.skadedyr.bygningsskade','hus.skadedyr.bekjempelse'],41:['hus.rate.egenandel','hus.skadedyr.egenandel'],42:['hus.utleie.vilkar'],43:['hus.utleie.mislighold'],44:['hus.utleie.utkastelse'],45:['hus.utleie.skadeverk'],46:[],47:['hus.utleie.egenandel'],48:['hus.egenandel.generell'],49:[],50:['hus.avtale.forbehold'],51:['hus.glass.dekning'],52:['hus.avtale.forbehold']}
positive={3,5,16,25,26,37,38,41,42,43,44,47,50,51}
P2={2,6,7,9,10,11,12,15,19,22,23,24,27,28,29,30,32,35,36,40,45,46,52}
why={1:'Permanent bolig/ubebodd brann-natur og næring/3seksjoneravgrensning er ikke representert av IPIDnavn alene.',2:'Eierskifte14d og hvem sikret mangler.',4:'Midlertidige byggematerialer mangler; kunstnerisk utsmykning vurderes separat per nivå.',6:'Grenser korrekt; landbruksarealunntak mangler.',7:'20% riktig; arealtap/antikvariske metoder/grunnutenforeiendom unntak mangler.',8:'Rydding riktig; prisstigning og flytting/lagring ikke representert.',9:'Periode/beregningsleie riktig; sparte utgifter/renterfradrag mangler.',10:'Positiv dekning og svignist korrekt; heksesot/byggfeil unntak mangler.',11:'Hovedutløsere korrekt; søl/kondens/sopp unntak mangler.',12:'50k korrekt; ikke takrenner/nedløp/drensledninger savnes.',13:'Generisk unntaksparent mister renterhærverk, glasspunktering, snø-/basseng/brygge og mekanisk skadescope.',14:'Lovhenvisning mister eksplisitt utvidelse antenne/markise/flytebrygge med avgrensning.',15:'250/time og75% kontantarbeid ikke representert.',17:'Fullverdi mangler eier/arving og ved annen eier/ingen rebuild allverdiøkning; ikke ubetinget fullverdi.',18:'1mill og2år representert, men konkret tak min(gjenoppføring eksMVA,markedsverdi+40%) og egen tilpasningsfrist mangler.',19:'Førsterisikosum riktig;40%verdiøkning/ubrukthusrestriksjon ikke konkret.',20:'Tabellen dekker alle12kategorier med konsolidering, men ikke plastunntaket for ute-/bunnledninger.',21:'Hendelsesavgrensning/eldste del ikke i structuredValue; kan gi falsk universell aldersregel.',22:'Ung handelsplante og min(markedsfall,reparasjon) utenreparasjon savnes.',23:'Kundevalg riktig; høyesteperhendelse/etteravkorting savnes.',24:'6000/overvann0riktig; NEK5år og tiltak på hovedinntak ikke konkrete.',27:'Ansvar juridiskparent uten store unntak og byggherrepositiv.',28:'100k/250k riktig; FinKN15k/forlik25k/sakkyndig20%/interessetak savnes.',29:'Eier/fester riktig; tidligere eier og ny bolig førinnflytting savnes.',30:'Vesentlige tvistunntak/tidsavgrensning savnes.',31:'Lovhenvisning gir ikke femdekar/begrensninger og tomterstatning ved byggenekt.',32:'50år ogvegg/feil korrekt; kondens ikke uttrykkelig.',33:'Fullverdi/fysiskskade/firma riktig; førperiode/kosmetisk/utenbevistisolasjonstap mangler.',34:'10år/autorisert/mangelselv riktig; reklamasjon/konkurs og kjente feil mangler på våtromfaktum.',35:'Reklamasjon/konkurs riktig; øvrige presise negativer savnes.',36:'75% og2år riktig; nevner ekskluderer riving/rydding/prisstigning ikke angitt.',39:'Noen unntak riktig; over taksperre/laft/tilkomst og kosmetisk mangler.',40:'Fysisk skade og kosmetisk korrekt; før/etteraktivitet mangler i insektreglene.',45:'500k riktig; kosmetisk/slitasje/kjæledyrunntak savnes.',46:'Tilleggs innbooppgjørskriterier1/3verdifall/brukt mangler.',48:'Bevisstyrt actualvalue riktig; dokumentert valgområde6000–25000 ikke representert.',52:'Generell sikkerhetsreferanse savner7d-stengekrav og hovedforpliktelser.'}
for pid in ['fremtind-hus-standard','fremtind-hus-topp']:
 p=A.p[pid];top=pid.endswith('topp')
 for n,q in enumerate(I['rules'],1):
  if q['scope']=='top'and not top:continue
  component={'rot':'fremtind-hus-rate-insekter','rental':'fremtind-hus-utleie'}.get(q['scope'],'');keys=K[n];cls=PRESENT if n in positive else COARSE if keys else MISSING;pri=''if cls==PRESENT else'P2'if n in P2 else'P1';reason=why.get(n,'Eksakt vilkår og produkt støtter representasjonen.');val=q['value']
  if n==20:keys=[f['key'] for f in p['facts']if f['key'].startswith('hus.aldersfradrag.')]
  if n==49:cls='SOURCE_ONLY_ACCEPTABLE';pri='';reason='Medlemsregel tilhører ikke ordinary; ingen ordinary-mangel opprettes.'
  if n==50:cls=ADMIN;pri='';reason='Eika overgangen er provenance; ingen historisk Eika-likhet påstås.'
  if n==6:val=val.replace('Standard200000/Topp500000','500000'if top else'200000')
  if n==26:reason='DNB-side dokumenterer5mill med bevisforbehold; fullvilkår er bevisstyrt; ikke like kanalprodukter utledet.'
  A.fact(pid,q['subject'],q['dimension'],val,B+q['source'],q['location'],cls,keys,pri,reason,'SCRC-053',component,inventory_id=q['id'],extra={'source_first_inventory':'fremtind-hus-independent-inventory.json'})
 art=A.fact(pid,'Kunstnerisk utsmykning','coverage','Topp inkluderer kunstnerisk utsmykning, Standard ekskluderer eksplisitt.',B+'Vilkar_Topp_Hus.pdf','Topp§1.1s1;Standard§3.1s3',PRESENT if top else'CATALOG_FACT_NOT_SUPPORTED_BY_APPLICABLE_SOURCE',['hus.bygninger.utsmykning'],''if top else'P1','Toppriktig; Standard har positiv katalogpåstand fra eksklusjonskolonnen.' if not top else'Toppstøttekontroll','SCRC-053',inventory_id='FHU-04')
 A.reverse(pid,{f['key']:{'locations':[{'artifact':B+f['source']['filename'],'section':f['source'].get('section'),'page':f['source'].get('page')}],'note':'Full claim numeric/source check performed; material lost conditions separately inventoried.'}for f in p['facts']+sum(p['addonFacts'].values(),[])})
 for c in A.support:
  if c['product_identity']!=p['identity']:continue
  if c['key']=='hus.bygninger.utsmykning':
   c['manual_reverse_evidence']={'artifact':B+'Vilkar_Topp_Hus.pdf','location':'Topp§1.1s1'if top else'Standard§3.1s3','reason':'Kunstnerisk utsmykning under Omfattes ikke på Standard; Topppositiv§1.1'}
   if not top:
    c.update(full_claim_validated=False,support_status='UNSUPPORTED_APPLICABILITY_OR_SEMANTICS',source_fact_ids=[art['source_fact_id']],finding_ids=[art['finding_id']]);A.a['unsupported_catalog_claims']['proven'].append(dict(c))
  if c['key'].startswith('hus.aldersfradrag.'):
   c.update(full_claim_validated=False,support_status='QUALIFIER_REVIEW_REQUIRED',support_scope='Numerical free years/annual/max and source supported; missing trigger/eldestpart; nonplastic limit lost specifically in consolidated pipe key.')
 A.product_review(pid,[x for x in A.art if x.startswith(B)],True,'52 source-first rules + explicit arts reverse check. All12depreciationrows checked, broad source package and own channel websites read;2addons reviewed exact availability/limits/conditions. Standard art falsepositive flagged. Fritidsbolig/LO dimensions not imported into ordinary Hus. No external freshness claim.')
for a in A.a['addon_coverage']:
 if a['addon_id']in['fremtind-hus-rate-insekter','fremtind-hus-utleie']:a.update(status='COMPLETE',fully_audited=True,notes='Both level applicability, optional status, limits, major qualifications and exclusions, deductibles and source provenance checked against independent inventory; positive control plus gaps retained.')
A.a['source_conflicts'].append(dict(id='SC-058',provider='fremtind',family='Hus',product='fremtind-hus-topp',sources=[B+'IPID_Hus.pdf',B+'Vilkar_Topp_Hus.pdf'],claim='Tak alder ved50år',observed='IPID V103 under50år versus fullToppikkeeldreenn50år (inkl50). SB1webinntil50. Literal boundary conflict, no arbitrary normalization.',status='SOURCE_CONFLICT_REVIEW_REQUIRED',action='Avklar takets inkluderende aldersgrense i rett versjon.'))
A.a['source_research_queue'].append(dict(queue_id='SR-fremtind-hus-roof-boundary',product=['fremtind-hus-topp'],reason='IPID under50 versus main≤50',external_source_needed_if_unresolved='Avklart versjon/datertIPID; ingen henting.',downloaded=False))
A.checkpoint('Fremtind Hus levels and two addons closed; Standard artistic-decoration false positive verified; age-rule qualifiers and settlement gaps retained','Reise','fremtind','fremtind-reise')
