from continue_audit import *
A=Audit();I=load('frende-vehicle-independent-inventory.json');path=I['source'];ipid='catalog/sources/frende/IPID_Personbil.pdf';general='catalog/sources/frende/Generelle_vilkar-01012026.pdf'
A.root('SCRC-017','Frende Bil preserves many exact limits but omits source-documented conditions, events and settlement rules. Fire/theft deductibles are attached only to Kasko despite Delkasko applicability. Parking-bonus text introduces unsupported age/police conditions and omits exact parking/time/vehicle qualifiers.','lib/frende-catalog.ts exact rows and inherited resolution; full15pterms+2pIPID+4pgeneral;61 source-first rules. No inference about authoring cause.',['Bil'],['frende'],'RB-15')
K={1:[],2:['geografi.dekning'],3:[],4:[],5:[],6:['tilbehor.grense'],7:['bagasje.grense'],8:[],9:['brann.dekning'],10:['tyveri.dekning'],11:['glass.dekning'],12:['veihjelp.dekning'],13:[],14:[],15:['kasko.dekning'],16:['bilnokkel.dekning','bilnokkel.grense'],17:['nyverdi.alder','nyverdi.km','nyverdi.skadegrad'],18:['nyverdi.alder','nyverdi.km','nyverdi.skadegrad','nyverdi.unntak'],19:[],20:['leiebil.bilklasse'],21:['leiebil.dager'],22:['leiebil.kondemnasjon'],23:['leiebil.kontant'],25:['ladekabel.dekning'],26:['leasing.startleie'],28:['maskinskade.dekning'],29:['maskinskade.alder','maskinskade.km'],30:['maskinskade.dekning'],31:['maskinskade.unntak'],32:[],33:['maskinskade.egenandel.0-99999','maskinskade.egenandel.100000-149999','maskinskade.egenandel.150000-200000'],34:[],35:[],36:[],37:[],39:[],40:['glass.egenandel.bytte','glass.egenandel.reparasjon'],41:['veihjelp.egenandel'],42:['brann.egenandel','tyveri.egenandel'],43:[],44:[],45:[],46:[],47:['bonus.kasko'],48:['bonus.delkasko','bonus.parkert'],49:[],50:['ulykke.dod'],51:['ulykke.invaliditet'],52:[],53:['ansvar.dekning'],54:['rettshjelp.dekning'],55:['rettshjelp.dekning'],56:['rettshjelp.grense'],57:['rettshjelp.egenandel'],58:[],59:[],60:[],61:[]}
why={1:'Forsikret krets utover generell ansvarstekst mangler.',2:'Europaunntak korrekt; særskilt Nordenrettshjelp mangler.',3:'Ekstrahjulsett og separat merverdihjulsum mangler; ikke samme som fastmontertutstyr.',4:'Batteri/kabel i objektgrunnlaget mangler utenforUtvidet; skadeårsaker skal fortsatt scopes.',5:'Navngitt sikkerhetsutstyr mangler.',6:'Sum riktig; lakk/folie-avgrensning mangler.',8:'Kontanter/verdipapirerunntak mangler.',9:'Brannhendelser riktig; startkomponent/svimerke/følgeskadeskille mangler.',10:'Tyverihendelser riktig; husstand/ansatt/utlån-unntak mangler.',12:'Hjemme+årsaker korrekt; nærmesteverksted/påkobletvogn/billigererep avgrensning mangler.',13:'Hjemtransport/hotellvilkår mangler.',14:'Kjøretøyhenting/gjenfunnetbil og markedsverditak mangler.',17:'Verdier kjent; leasingunntak og kontantrett mangler på Kasko; inklusivaldersordlyd vurderes separat.',19:'Materielle kaskounntak og avvistgaranti-mekanisme mangler.',20:'KlasseC riktig; dekketskadetype som utløsende krav mangler.',28:'Inkludert komponentfamilie riktig; kjørestopp/service/trimvilkår mangler.',30:'Generell oppregnede komponenter uten faktisk liste; rådgiver får ikke skille inkluderte systemer.',31:'Summarisk unntak skjuler konkrete komponentunntak og avvistgarantiunntak; leasing står kun IPID,ikke sitert9.3.',32:'Maskinskadeoppgjør varsling/slitasjefradrag/delefremlegging mangler.',35:'Reparasjonsverdiregler mangler.',36:'Kontant50%arbeid/mva-regler mangler.',37:'Markedsverdi/30d/tilbakebetaling mangler.',39:'Tre konkrete aldersfradragstabeller og fabrikkmontert fritak mangler.',42:'Beløpsregler mangler Delkasko; alarmfritak mangler også Kasko/Utvidet.',43:'Vilt6000reduksjon og meldingsvilkår mangler.',44:'Ungfører8000 og ansvarproporsjonalregress mangler.',45:'Årligkjørelengdeavkortning med delkaskounntak mangler.',46:'Bonusopptjeningstrinn mangler.',47:'Generell bonusnivå/opptjeningsår opplyser ikke konkrete satser.',48:'Deleravfritak finnes; korrektparkering,maskin,vilt/naturulykke og relevanteforbehold mangler.',49:'Ulykkedefinisjon/personkrets og bevisvalgbetingelse mangler.',51:'200000ved100%riktig; delvisinvaliditet/forfunksjon/3årsoppgjør mangler.',52:'Ulykkeunntak og presistPTSD-unntak mangler.',53:'Ulovfestetansvar nevnt men10000000/hendelse/år og vegfraktunntak mangler.',54:'Grunnscope riktig; etter-salg/før-nykjøp/voldgift mangler.',55:'Rettshjelputgiftsscope og materielle unntak mangler.',56:'Begge beløp riktig; takøkonomiskinteresse mangler.',58:'Bruksbegrensninger og opplæringsunntak mangler.',59:'Sikkerhetskrav mangler.',60:'Tyverisikringens konkrete krav mangler.'}
for pid in ['frende-bil-ansvar','frende-bil-delkasko','frende-bil-kasko','frende-bil-utvidet']:
 p=A.p[pid];lvl=['ansvar','delkasko','kasko','utvidet'].index(pid.split('-')[-1]);full=p['facts']+sum(p['addonFacts'].values(),[]);actual={f['key'] for f in full}
 for q in I['rules']:
  n=int(q['inventory_id'].split('-')[-1]);scope=q['scope']
  if scope in ['snow','motorhome']:continue
  if scope in ['physical','delkasko'] and lvl<1:continue
  if scope in ['kasko','rental','machine'] and lvl<2:continue
  if scope=='utvidet' and lvl<3:continue
  if n==17 and lvl==3:continue
  keys=[k for k in K.get(n,[]) if k in actual];cls=COARSE if keys else MISSING;pr='P2' if n in [1,35,36,37,39,45,46,47,59,60] else 'P1';val=q['value'];reason=why.get(n,'Exact rule checked against inherited and optional facts.');comp='frende-leiebil' if scope=='rental' else 'frende-maskinskade' if scope=='machine' else ''
  if n in [7,11,15,21,22,23,25,26,33,40,41,50,57]:cls=PRESENT;pr='';reason='Exact scoped catalog claim preserves this rule. Missing adjacent conditions separately inventoried.'
  if n==7:val='PersonligeiendelertyveriKasko10000/Utvidet20000;andretyperholdesadskilt.'
  if n==16:
   cls=PRESENT if lvl==3 else COARSE;pr='' if lvl==3 else 'P1';reason='Utvidet20000utenegenandel/bonustap korrekt.' if lvl==3 else 'Kaskonøkkelhendelser korrekt, men eksplisitt egenandel=avtaltkasko mangler.'
  if n==29:cls=REVIEW;pr='';reason='12årsordlyd internt sprikende; ut forsikringsåret bevart i katalog og må ikke vilkårlig endres til fødselsdag.'
  if n==34:cls=CUSTOM;pr='';reason='Separat bevisvalgt panthaverprodukt utenfor eksisterende Bilnivåer; ingen kundevalg antas.'
  if n==61:cls=ADMIN;pr='';reason='Administrativ skademelding.'
  if n==18:cls=COARSE;pr='P2';reason='3/60000/80%ogunntak riktig; aldersoperator under3 kontra ikkeeldreenn3 er strengere på grensen. Hold nøyaktig ordlyd.'
  A.fact(pid,q['subject'],q['dimension'],val,path,f'PDFside{q["pages"]}punkt{q["section"]}',cls,keys or K.get(n,[]),pr,reason,'SCRC-017',comp,q['inventory_id'],extra={'shared_source_inventory':'frende-vehicle-independent-inventory.json','provider_type_applicability':'Personbil IPID2026, no inheritance to MC/Bobil without separate applicability review'})
 # Common terms: full read, material exclusions separately recorded rather than automatically labelling every administrative clause a gap.
 for sub,dim,val,loc,cl,pri,reason in [('Generelleunntak','krig/terror','ABC/radioaktiv/biologisk/krigområderegler,6ukerveduventetutbrudd;terror/epidemi100millionerselskapstak/år.','PDF2punkt1',MISSING,'P2','Materiale generelle begrensninger mangler; aggregattak er ikke kundens sum.'),('Datakriminalitet','unntak/fysiskfølgeskade','Cyberunntakmedunntakforfysiskskadesomdekkesavdetenkelteprodukt.','PDF4punkt9',MISSING,'P2','Unntaket må bevares sammen med fysiskfølgeskadeforbehold.'),('Eierskifte','ettervern','14dnykjøperhvisingenegenforsikring.','PDF3punkt5',MISSING,'P2','Dokumentertettervern mangler.'),('Administrasjon','generellavtale','Oppsigelse/svik/renter/skjønn/vinning;ikke ordinære sammenligningsrader.','PDF2–4punkt2–8/10–11',ADMIN,'','Administrative regler holdes uten ordinær coverage.')]:A.fact(pid,sub,dim,val,general,loc,cl,[],pri,reason,'SCRC-017',inventory_id='FR-VE-GENERAL-'+dim)
 # Reverse support; exclude exact disputed catalog claims rather than certify all via row presence.
 excluded={'bonus.parkert','nyverdi.alder','maskinskade.unntak'}
 A.reverse(pid,{f['key']:dict(artifact=path,pdf_page=f['source'].get('page'),section=f['source'].get('section'),note='Source full15page+IPID read. Exact value/label supported; omitted surrounding dimensions separately recorded.') for f in full if f['key'] not in excluded})
 if lvl>=2:
  A.fact(pid,'Parkeringsskade','bonusvilkår','Ukjentkjøretøyskadervedbestemtparkeringiavgrensettidsrom. Ingenunderseksårsgrenseellerpolitivilkår i11.13. Katalogleggerdissetilogsavnerpresisertevilkår.',path,'PDF10punkt11.13.3','CATALOG_FACT_SEMANTICALLY_MISMAPPED',['bonus.parkert'],'P1','Aktuell kilde støtter ikke katalogens ekstraalder/politibetingelser; konsekvens kan være falsk innsnevring og for grov sammenligning.','SCRC-017',inventory_id='FR-VE-PARKING-REVERSE')
  for c in A.support:
   if c['product_identity']!=p['identity']:continue
   if c['key']=='bonus.parkert':c.update(full_claim_validated=False,support_status='UNSUPPORTED_CONFIRMED',manual_reverse_evidence='2026terms11.13.3 p10 requires unknownvehicle+specifiedparking/time; no under6years/policereport conditions. Full15pterms/IPID2p/general4p reviewed.');A.a['unsupported_catalog_claims']['proven'].append(dict(c))
   elif c['key']=='nyverdi.alder':c.update(full_claim_validated=False,support_status='LABEL_BOUNDARY_MISMATCH',manual_reverse_evidence='Catalog under1/3years;maintermsnotolderthan1/3years. Sameagevalue but strictoperator differs. IPIDunder wording also present; reviewsourceprecision.')
   elif c['key']=='maskinskade.unntak':c.update(full_claim_validated=False,support_status='SOURCE_ATTRIBUTION_AND_CONDITION_GAP',manual_reverse_evidence='Leasedcar exclusionIPIDp2, notcitedterms9.3. Guaranteeexclusionin9.3hasconditionalcoverforunsuccessfulclaim,missingcatalog.')
 # Ordinary base lower levels can close; Kasko family remains partial for machine age and accident inclusion scope.
 A.product_review(pid,[path,ipid,general],False,'All15terms+2IPID+4generalpages read,61sourcefirstrules filteredbyBil/exactlevel. Reverse allclaims checked; parking unsupported confirmed. Remaining: accidentselected/default scopeIPIDvsbevis, machineageinternalwording, exactnewvalueageboundary. No sourcefreshness claim.')
for aid in ['frende-leiebil','frende-maskinskade']:
 ad=next(x for x in A.a['addon_coverage'] if x['addon_id']==aid);done=aid=='frende-leiebil';ad.update(status='COMPLETE' if done else 'PARTIAL',fully_audited=done,semantic_audit_status='COMPLETE' if done else 'PARTIAL',notes='Bil rental exactscope/durations/cash fullyaudited; triggeringconditiongap recorded.' if done else 'Allclauses read; agewordinginternalconflict and leasedexclusionIPIDattribution unresolved; component/unntakgaps recorded.')
A.a['source_conflicts'].append(dict(id='SC-012',provider='frende',family='Bil',sources=[path,ipid],claim='Maskinskade age cutoff; accident selection; totalskade boundary precision',observed='Terms9.1/9.3endpolicyyear12 vs11.11/IPIDolderthan12. IPIDaccidentseparateheading whiletermsrequiresbevis. Newvaluefulltermsnotolderthan1/3 vsIPIDunder1/3. Lease-machineexclusiononlyIPID.',status='SOURCE_APPLICABILITY_REVIEW_REQUIRED',action='Preserve exact wording and customer-bevisselection; no arbitrary cutoff/default. Rental independentlyclosed.'))
# Normalize newly introduced pet dependency classification to canonical audit enum.
for f in A.f:
 if f.get('source_first_inventory_id')=='FR-PE-DEPENDENCY':f['classification']='CATALOG_FACT_SEMANTICALLY_MISMAPPED'
for g in A.a['findings']:
 if g.get('product')=='frende-hund-veterin-r' and g.get('semantic_dimension')=='Tap-componenttilknytning':g['classification']='CATALOG_FACT_SEMANTICALLY_MISMAPPED'
A.checkpoint('Frende Bil all four levels source-first checked; parking unsupported claims and deductible inheritance gap; rental optional closed','MC','frende','frende-mc-ansvar')
