from continue_audit import *
A=Audit();I=load('fremtind-reise-independent-inventory.json');B='catalog/sources/fremtind/reise/canonical/';pid='fremtind-reise';p=A.p[pid]
A.root('SCRC-054','Aktiv Fremtind Reise mister flere eksplisitte beløp og kvalifikasjoner fra eget fullvilkår. Forsinkelse samler fremmøte og forsinket avgang under ulikt innhentingstak; sikkerhetsfaktum har kildepunkt7.6 som ikke finnes i arkivert gjeldende pakke.','47 source-first regler, alle17sider+IPIDV104, gjenbrukte rettsvedlegg kontrollert med tekstsammenligning.',['Reise'],['fremtind'],'RB-50')
K={1:['reise.personer.omfang'],2:[],3:['reise.omrade.verden'],4:['reise.varighet.valg','reise.varighet.maks'],5:['reise.omrade.ud','reise.aktivitet.unntak'],6:['reise.ulykke.dekning'],7:[],8:['reise.bagasje.dekning'],9:[],10:['reise.bagasje.verdisaker'],11:[],12:['reise.bagasje.dekning'],13:['reise.bagasje.dekning'],14:['reise.bagasje.uhell'],15:['reise.bagasje.mobil','reise.bagasje.mobil_egenandel'],16:[],17:[],18:['reise.bagasje.forsinket'],19:['reise.forsinkelse.rute'],20:['reise.forsinkelse.rute'],21:['reise.forsinkelse.rute'],22:['reise.forsinkelse.ankomst'],23:['reise.leiebil.egenandel'],24:['reise.medisinsk.behandling'],25:['reise.medisinsk.kjent','reise.medisinsk.graviditet'],26:[],27:['reise.medisinsk.tann'],28:[],29:['reise.sykeledsagelse'],30:[],31:['reise.hjemtransport'],32:['reise.reiseavbrudd'],33:['reise.reiseavbrudd'],34:['reise.reiseavbrudd.arrangement'],35:['reise.medisinsk.behandling','reise.tjeneste.alarm'],36:['reise.ulykke.invaliditet','reise.ulykke.dodsfall','reise.ulykke.behandling'],37:['reise.aktivitet.unntak'],38:[],39:['reise.ulykke.behandling','reise.ulykke.behandling_egenandel'],40:[],41:['reise.avbestilling.dekning'],42:['reise.avbestilling.dekning','reise.avbestilling.dyrepensjonat'],43:['reise.medisinsk.kjent','reise.medisinsk.graviditet'],44:['reise.evakuering'],45:['reise.evakuering'],46:['reise.ansvar.dekning','reise.ansvar.sum','reise.ansvar.egenandel'],47:['reise.rettshjelp.dekning','reise.rettshjelp.sum','reise.rettshjelp.egenandel']}
positive={3,4,12,14,18,20,22,23,27,36,42,45};P2={2,6,8,13,15,16,19,24,29,31,32,33,34,35,39,40,43,44,46,47}
why={1:'Familie avgrenset korrekt, men nordisk bosted/trygdvilkår mangler.',2:'Særavtaleutstasjonering beholdes som kundespesifikk, ikke vanlig produktkrav.',5:'UD/risikoaktiviteter finnes, men arbeids-/studiested,6000m og mobilunntak ikke konkret.',6:'Ulykke75år/24t riktig; førreisekjøp og avbestillingshendelsetid ikke representert.',7:'Force majeure/konkurs/lønns-/letekost og rus/slagsmål mangler samlet.',8:'Dekkedehendelser finnes; leid/lånt førreise og arbeidsgivereide objekter ikke representert.',9:'Kontanter10k, pass15k og arbeidsgiver50k er eksplisitte manglende delsummer.',10:'40kgruppe finnes; eget40k per øvrig gjenstand og sykkelkommunescope ikke representert.',11:'Materielle objektunntak (elsykkel/drone/verktøy/båt mv) mangler.',13:'Mistet/ukjent finnes; kosmetikk/emballasje/slitasje og sportsutstyribruk savnes.',15:'Flereunntak/2k korrekt; avtaleverksted og arbeids-/studieunntak ikke representert.',16:'Ny/brukt/edelmetall/samleinteresse og leverandørregler mangler.',17:'Mobil/elektronikk/sykkel/briller/toalettsaker fradragstabell mangler.',19:'Hovedårsaker riktig; privatkjøretøybergingskrav og EU261/mat/reisegjennomføring unntak savnes.',21:'Ubegrenset innhenting gjelder for sent fremmøte; forsinket eget transportmiddel har6000tak og24t vilkår. Katalogens samlede ruteclaim mister dette og500klær.',24:'Behandlingsparent riktig; legekost/medisin/transport/utsattopphold ikke spesifisert.',25:'Kjent/graviditet riktig; privatklinikkNorden/etterhjemkomst/fortsattutland/tolk og familiepåreisemål mangler.',26:'Psykologisk førstehjelp25000/skade er ikke representert.',28:'Innhenting av fastlagt reise etter sykdom150000/skade mangler.',29:'2pårørende/godkjenning riktig;veddød og telefon5000 mangler.',30:'Eneste medreisende50000/skade mangler.',31:'Hovedtrigger/godkjenning riktig; behandlingutilgjengelig/nyhjemreiseunntak mangler.',32:'2000 korrekt; reisefølge må ha forsikring hososs og alternative returregler/visumpoengunntak mangler.',33:'750/10d/3d riktig; ledsager/familiemedlem, førstelegedato mangler.',34:'5000 riktig; transport/opphold påreise oglegeforbud savnes.',35:'30d/SOS riktig;>5000forhåndog sykehus/tilkallskrav ikke hele.',37:'Aktivitetsunntakparent mister under16unntak,organiserteidrettskonkurranser/1Ginntektgrense.',38:'Arr<15%,flått/virus/psykiskutenfysisk og andreulykkesunntak mangler.',39:'2år/5%/1000riktig; barnetannsenest23 ogprivat/hjelpemiddelunntak mangler.',40:'3årfastsettelse ogførsykdomandel mangler.',41:'Hendelsesliste riktig;gruppe≤8/familiescope og innenlandregjeringsråd ikke presist.',43:'Delviskjent/graviditet riktig; delreise/visumskatt/poeng/arrangement ogforlangsykehus mangler.',44:'Myndighetsråd riktig; natur/pandemikunutenNorge og tidligerefredeligavgrensning ikke eksplisitt.',46:'Bevissum er legitimukjent; storeunntak/14fot10hk/750kSDR ikke konkretisert.',47:'100k250k/20 riktig; FinKN15kforlik25ksakkyndig20/interessetak ogtvistunntak savnes.'}
for n,q in enumerate(I['rules'],1):
 keys=K[n];cls=PRESENT if n in positive else COARSE if keys else MISSING;pri=''if cls==PRESENT else'P2'if n in P2 else'P1';reason=why.get(n,'Eksakt fullvilkår støtter tall og materiell regel; kundeverdi ikke oppfunnet.')
 if n==2:cls=CUSTOM;pri=''
 if n==21:cls='CATALOG_FACT_SEMANTICALLY_MISMAPPED'
 A.fact(pid,q['subject'],q['dimension'],q['value'],B+'fremtind-reise-vilkar.pdf',q['location'],cls,keys,pri,reason,'SCRC-054',inventory_id=q['id'],extra={'source_first_inventory':'fremtind-reise-independent-inventory.json'})
f=A.fact(pid,'Sikkerhetsforskrifter','source_support','Fullpakke slutter7.5.6før§8; kataloghenvisning7.6s5 finnes ikke. Fullvilkår/IPID viser til bevisstyrte sikkerhetsregler, ikke eksplisitt katalogens tilsyn/innsjekkingforbud.',B+'fremtind-reise-vilkar.pdf','s4–5§7.5.6/§8;IPID s2','CATALOG_FACT_NOT_SUPPORTED_BY_APPLICABLE_SOURCE',['reise.sikkerhet.reisegods'],'P1','Katalogens positivt formulerte plikter krever egen anvendelig sikkerhetsforskrift. HistoriskP10 kan ikke brukes som gjeldende kilde.','SCRC-054',inventory_id='FRE-48')
A.reverse(pid,{x['key']:{'locations':[{'artifact':B+Path(x['source']['filename']).name,'section':x['source'].get('section'),'page':x['source'].get('page')}]}for x in p['facts']})
for c in A.support:
 if c['product_identity']!=p['identity']:continue
 if c['key']=='reise.sikkerhet.reisegods':
  c.update(full_claim_validated=False,support_status='UNSUPPORTED_APPLICABILITY_OR_SEMANTICS',manual_reverse_evidence={'artifact':B+'fremtind-reise-vilkar.pdf','location':'s4–5','reason':'No§7.6; requirement not in full applicable archivedpackage'},source_fact_ids=[f['source_fact_id']],finding_ids=[f['finding_id']]);A.a['unsupported_catalog_claims']['proven'].append(dict(c))
 if c['key']=='reise.forsinkelse.rute':c.update(full_claim_validated=False,support_status='QUALIFIER_REVIEW_REQUIRED',support_scope='Unlimitedcatchup onlylatearrival;delayeddeparture6000cap+24h. Parent conditional attribution insufficient.')
A.product_review(pid,[B+'fremtind-reise-vilkar.pdf',B+'fremtind-reise-ipid.pdf'],True,'47 source-first material rules and full reverse. Shared liability/legal exacttext reused except layout. Missing channelweb originals do not justify assumed90/120/180choices;70standardIPID with actualbevis retains customer truth. HistoricalP10notusedasactive source.')
A.a['source_research_queue'].append(dict(queue_id='SR-fremtind-reise-security-channel',product=[pid],reason='CurrentfullPDFhasno§7.6; lacks standalone securityrequirements. LocalSB1/DNBReisesitecopies absent; no90/120/180 inference.',external_source_needed_if_unresolved='Gjeldende sikkerhetsforskrift og kanalproduktsider/valgstruktur med versjon. Ingen henting nå.',downloaded=False))
A.checkpoint('Active Fremtind Reise complete; missing sublimits and age table, delayed-departure qualification loss, unsupported security citation recorded','Reise','fremtind','eika-reise-p10')
