from continue_audit import *
A=Audit();I=load('fremtind-bobil-independent-inventory.json');B='catalog/sources/sparebank1-fremtind/';M='catalog/sources/mc-bobil/'
paths={k:B+n for k,n in {'ansvar':'Vilkar_ansvar_bil.pdf','mini':'Vilkar_Minikasko_Bil.pdf','kasko':'Vilkar_Kasko_Bil.pdf','rental':'Vilkar_leiebil.pdf','machine':'Vilkar_maskinskade.pdf','ipid':'IPID_Bil.pdf'}.items()};paths.update(topp=M+'fremtind-bobil-topp.pdf',web=M+'fremtind-dnb-bobil-page.html',general='catalog/sources/vehicle-extensions/fremtind-Generelle_vilkar_skadeforsikring.pdf')
A.root('SCRC-057','Fremtind Bobil har presise hovedsummer og Topp fukt/ferie, men mangler veihjelpens separate leiebilytelse, leasingberegning, oppgjør og flere tilleggsdetaljer. DNB-nettsidens motstridende sum/nivå/utleieregler må avklares separat.','57 source-first regler, currentfull13p/shared2025components,2optional fullterms,IPIDV106og DNBoriginal sammenholdt med4produkter.',['Bobil'],['fremtind'],'RB-53')
K={1:[],2:['avtale.geografi'],3:[],4:['kasko.egenandel'],5:[],6:[],7:['ansvar.dekning','ansvar.person.grense','ansvar.ting.grense'],8:['ulykke.dekning'],9:['ulykke.invaliditet','ulykke.dod'],10:['ulykke.invaliditet','ulykke.dod'],11:['rettshjelp.dekning','rettshjelp.geografi'],12:['rettshjelp.grense'],13:['rettshjelp.egenandel'],14:['rettshjelp.dekning'],15:[],16:['utstyr.grense','bobil.fortelt.grense','bobil.fortelt.begrensning'],17:['bobil.losore.grense','bobil.losore.gjenstand','bobil.losore.begrensning'],18:['brann.dekning'],19:['tyveri.dekning'],20:['glass.dekning'],21:['veihjelp.dekning'],22:[],23:['veihjelp.dekning'],24:['feilfylling.dekning'],25:['nyverdi.alder','nyverdi.km','nyverdi.skadegrad','nyverdi.begrensning'],26:['nyverdi.begrensning'],27:[],28:[],29:['tyveri.dekning'],30:['bobil.losore.grense'],31:[],32:['kasko.dekning','feilfylling.dekning'],33:['kasko.begrensning'],34:['kasko.egenandel'],35:['bobil.losore.grense','bobil.losore.gjenstand'],36:['nokkel.dekning','nokkel.grense','nokkel.egenandel'],37:['ladekabel.dekning','ladekabel.grense','ladekabel.egenandel'],38:['interiorrens.grense','interiorrens.egenandel'],39:['parkering.dekning','parkering.alder'],40:['feilfylling.egenandel'],41:['bobil.feriegaranti.dekning','bobil.feriegaranti.dagsbelop','bobil.feriegaranti.dager'],42:['bobil.fukt.dekning','bobil.fukt.alder','bobil.fukt.kontroll','bobil.fukt.begrensning'],43:['nyverdi.alder','nyverdi.km','nyverdi.skadegrad','nyverdi.begrensning'],44:['nyverdi.begrensning'],45:['leiebil.dekning','leiebil.dager','leiebil.dagsgrense','leiebil.bilklasse','leiebil.begrensning'],46:['leiebil.begrensning'],47:['maskinskade.alder','maskinskade.km'],48:['maskinskade.dekning'],49:['maskinskade.begrensning'],50:[],51:['maskinskade.egenandel.kilometer'],52:[],53:['kasko.begrensning'],54:['bobil.losore.grense','utstyr.grense','avtale.geografi','bobil.feriegaranti.dager','kasko.begrensning'],55:[],56:[],57:[]}
POS={9,13,16,17,18,32,35,39,40,41,42,46,47,51}
why={1:'14d eierskifte/personkrets mangler.',2:'Geografi korrekt i fullvilkår; grenseforsikring og webmotstrid skilles.',3:'Lagring/avregistrering mangler.',4:'Bevisvalg korrekt; høyeste perhendelse og rekkefølge mangler.',5:'Bonusfrie skadetyper ikke oppregnet.',6:'Bonusordning/tabell og3år bortfall mangler.',7:'Hovedsummer riktig; kontraktsansvarunntak mangler.',8:'Kjøretøyårsak riktig; sykdom/rusunntak mangler.',10:'Dødsfall1år oginvaliditet1–3år mangler.',11:'Norden/eier riktig; historisk tvistegrunnlag/solgtobjekt mangler.',12:'100/250k korrekt;FinKN15k/forlik25k/interessetak/sakkyndig20% mangler.',14:'Tvistunntak for yrke/andreobjekter/familie mv er ikke konkrete.',15:'Ekstrahjul/nøkkel/ladekabel ogugyldigtrim ikke uttrykt.',19:'Prøvekjøring riktig;husstand/ansattsjåførnegativ ikke uttrykt.',20:'Glassbrudd ogsolcelle riktig;50%markedsverditak mangler.',21:'Persontransportsyk/død ogbilligerefortsettelse ikke gjengitt av verkstedparent.',22:'Utenlands leiebil600/45 somdelavMini-redning er ikke egetvalgfrittleiebiltillegg. Mangler.',23:'Bilmedtilhenger/tomtank/50%verditak mangler i veihjelpparent.',24:'Tømming/rens10000 ogikke-startetmotor er egen redningsytelse, ikke samme som Kaskomotorskade vedfeilfylling.',25:'Grensene korrektpåKasko; utgåttmodell/sisteliste mangler. Mini har egen nivåkonflikt.',26:'Leasinghenvisning uten beregning/restmåneder.',27:'Privatbil≤3500kg garantiscope gir ikke sikkert genereltBobilpositive claim. Bevisklassing trengs.',28:'Kontantarbeid50%/alderslitasje/garantitap mangler.',29:'21d tyverivent ogforebyggende stjåletnøkkel ikke egen struktur.',30:'1/3verdiforringelseterskel mangler.',31:'Kjørelengdeproporsjonalreduksjon/trimrisiko mangler.',33:'Kataloghar noenviktigeunntak, men frost/bane/kurs/gradvis/næring ikke konkret.',34:'Kundebevisriktig;ungfører+12000/dyr−2000 mangler.',36:'Sum/egenandel riktig; autorisertplutseligytrekvalifikasjon komprimert.',43:'Alder/km80%lease korrekt;kontantsistelisteutgåttmodell mangler.',45:'Valg/tall/leieklasse riktig;utgiftsunntak ikke fullt konkret.',48:'Oppregnede komponenter er for grovt uten de faktisk navngitte motor/EV-/styringsdelene.',49:'Noenhovedunntak finnes;garanti/ledning/høyvoltkabel/infotainment/banekurs ogandrekomponentnegative mangler.',50:'Nyttbatterialdersfradrag5år10%max50%ogegenandelsrekkefølge mangler.',52:'Ikkekontantoppgjør for maskin mangler.',53:'DNB privatutleieinkludert2mnd står mot sammewebnegativ ogfullbeviskrav; ikke gjett.',54:'Forskjellige dokumentnivå-/kanalregler er reell konflikt; ikke velgnettside ellerfull mekanisk.',55:'Mini full§3.2 inneholdernyverdiregel mensweb/IPIDlegger påKasko; trengeravklaring.',56:'Kundespesifikke valg skal ikke fylles fra katalog.',57:'Felles unntak allerede identifisert; ikke hver generisk administrativregel ny fact.'}
for pid in ['fremtind-bobil-ansvar','fremtind-bobil-minikasko','fremtind-bobil-kasko','fremtind-bobil-topp']:
 p=A.p[pid];tier=pid.split('-')[-1];top=tier=='topp';physical=tier!='ansvar';kasko=tier in ['kasko','topp'];fs=p['facts']+sum(p['addonFacts'].values(),[]);used=set()
 for n,q in enumerate(I['rules'],1):
  if q['scope']=='physical'and not physical or q['scope']=='kasko'and not kasko or q['scope']=='topp'and not top or q['scope'].startswith('addon_')and not kasko:continue
  if top and n in [17,25,26]:continue
  if top and n in [37,38,44]:
   # Existing exact dimensions already validated in initial deep review: preserve IDs without duplicate occurrence.
   ids={37:'GAP-0135',38:'GAP-0134',44:'GAP-0133'};g=next(g for g in A.a['findings']if g['finding_id']==ids[n]);g['continuation_revalidated']=True;g['continuation_inventory_id']=q['id'];continue
  path=paths[q['doc']];used.add(path);keys=K[n];cls=PRESENT if n in POS else COARSE if any(f['key']in keys for f in fs)else MISSING;pri=''if cls==PRESENT else'P1'if n in {12,22,24,26,34,48,50,53,54,55}else'P2';reason=why.get(n,'Eksakt kilde ogproduktregel representert.');comp=''
  if n in [53,54,55] or n==25 and tier=='minikasko':cls='SOURCE_CONFLICT_REVIEW_REQUIRED';pri='P1'
  if n==27:cls='SOURCE_AMBIGUOUS';pri='P2'
  if n==56:cls=CUSTOM;pri=''
  if n==57:cls='SOURCE_ONLY_ACCEPTABLE';pri=''
  if q['scope'].startswith('addon_'):comp='fremtind-bobil-leiebil'if q['scope']=='addon_rental'else'fremtind-bobil-maskinskade'
  A.fact(pid,q['subject'],q['dimension'],q['value'],path,q['location'],cls,keys,pri,reason,'SCRC-057',component=comp,inventory_id=q['id'],extra={'source_first_inventory':'fremtind-bobil-independent-inventory.json'})
 A.reverse(pid,{f['key']:{'locations':[{'artifact':next((x for x in paths.values()if Path(x).name==f['source']['filename']),paths['topp']),'section':f['source'].get('section'),'page':f['source'].get('page')}]}for f in fs})
 conflicted=['avtale.geografi','utstyr.grense']+(['bobil.losore.grense','bobil.feriegaranti.dager','kasko.begrensning','maskinskade.dekning','leiebil.dekning']if top else['kasko.begrensning']if kasko else[])
 for cl in A.support:
  if cl['product_identity']==p['identity']and cl['key']in conflicted:cl.update(full_claim_validated=False,support_status='SOURCE_CONFLICT_REVIEW_REQUIRED',support_scope='Full named terms support numeric claim; DNB channel page conflicts materially. No silent source precedence.')
 A.product_review(pid,sorted(used|{paths['web'],paths['ipid'],paths['topp']}),True,'57 source-first rules with shared2025clauses reused and Bobil-special full13pchecked. Four exact products plus2optionals reviewed. Existing3initial findings revalidated without duplication. Fullclaimvalues checked; DNB/channel conflicts flagged, no forcedincludedoptional. COMPLETE available-local audit closure not allsourceconflicts resolved.')
for ad in A.a['addon_coverage']:
 if ad['addon_id']in['fremtind-bobil-leiebil','fremtind-bobil-maskinskade']:ad.update(status='COMPLETE_WITH_RECORDED_GAPS',fully_audited=True,notes='Exact named optional terms reviewed allrules;Kasko/Topp validavailability but DNB top included wording vsIPIDoptional requires channelconfirmation. No customer selection inferred.')
for i,(claim,observed)in enumerate([
 ('DNB equipment/contents/geography','WebFAQ10kfixedgear versusfull50k;webTopp80kcontents versusfull100k;webNorden versusfullEuropeexcludingfourcountries.'),
 ('DNB Top inclusions/privaterental','WebToppincludesmachine/rental, fullToppcontainsneither andIPIDcurrentoptional;webprivatehire2months included versuswebnegative andfullbevisrequired.'),
 ('DNB holiday/newvalue level','Webtwo weeks versusfull15days;Mini ownnewvalue1yr15kkm versusweb/IPIDKaskoonly.')],62):
 A.a['source_conflicts'].append(dict(id=f'SC-{i:03d}',provider='fremtind',family='Bobil',product='fremtind-bobil-*',sources=[paths['web'],paths['topp'],paths['ipid']],claim=claim,observed=observed,status='SOURCE_CONFLICT_REVIEW_REQUIRED',action='Request official exact DNB version/component package; do not choose favorable source automatically.'))
A.a['source_research_queue'].append(dict(queue_id='fremtind-bobil-dnb-conflicts',product='fremtind-bobil-*',reason='DNB page/fullterms/IPID conflicts across sums/geography/optionalstatus/privaterental/newvaluelevel',external_source_needed_if_unresolved='Dated channel-specific product clarification and applicable fullcomponents',downloaded=False))
A.checkpoint('Fremtind Bobil four levels and two addons reviewed; exact Topp positive controls retained, DNB source conflicts left unresolved','Båt','sparebank1-fremtind','sparebank1-fremtind-bat-delkasko')
