from continue_audit import *
A=Audit();I=load('storebrand-camp-independent-inventory.json');path=I['source'];general='catalog/sources/vehicle-extensions/storebrand-vilkar-generelle.pdf'
root=next(r for r in A.a['root_causes'] if r['root_cause_id']=='SCRC-011')
root['families']=sorted(set(root['families']+['Campingvogn','Tilhenger']))
root['description']+=' Campingvogn/Tilhenger i samme vehicle-object-katalogfunksjon bevarer korte hoveddekninger, men utelater konkrete camp02-dimensjoner. Kildekonflikter skilles fra påviste utelatelser.'
root['evidence']+=' camp02: 38 source-first regler sammenholdt med alle 53 basefacts i fem eksakte produkter; ingen tilleggskomponenter tilgjengelige.'
K={1:[],2:[],3:[],4:['avtale.geografi'],5:[],6:[],7:['fortelt.begrensning'],8:['fortelt.begrensning'],9:['losore.dekning','losore.grense'],10:[],11:[],12:[],13:[],14:[],15:[],16:['brann.dekning','brann.egenandel'],17:['tyveri.dekning'],18:['redning.dekning'],19:['redning.dekning'],20:['redning.dekning'],21:['kasko.dekning'],22:[],23:['brann.egenandel'],24:['nyverdi.dekning','nyverdi.alder','nyverdi.begrensning'],25:['fukt.dekning','fukt.alder','fukt.begrensning'],26:['fukt.begrensning'],27:['ferie.dekning','ferie.grense'],28:[],29:['fukt.begrensning'],30:['losore.dekning'],31:[],32:[],33:[],34:['rettshjelp.dekning'],35:['rettshjelp.grense'],36:[],37:[],38:[]}
why={2:'Tegningsforutsetningene kan påvirke om tilbudet er tilgjengelig; ikke dokumentert i katalogproduktet.',3:'Krav til bosted og panthavers bekreftelse mangler.',5:'Ansvar følger trekkbilens avtale; fravær av selvstendig ansvar kan ellers misforstås.',6:'Fastmontert utstyr og hjul er ikke konkret representert.',8:'Beviskravet finnes, men montering/demontering, løse ting og ikke-sammenbygget konstruksjon mangler.',9:'Summer finnes, men kamera som én gjenstand og husstand/reisefelle-omfang mangler.',11:'Muligheten for høyere løsøresum er ikke modellert; kundens konkrete valg/sum må fortsatt følge beviset.',12:'Last på tilhengeren er ikke omfattet; ingen eksplisitt avgrensning i dette produktet.',13:'Utstyrsfradragets start, prosent og tak mangler.',14:'Hele den konkrete bagasjetabellen og bruktverdi-prinsippet mangler.',15:'Høyeste egenandel ved samme hendelse mangler.',16:'Standardegenandel finnes, men hvilke brannårsaker som omfattes er bare included.',17:'Tyveriets egenandel, relaterte skadehendelser og husstands-unntak mangler.',18:'Included skjuler nivåavhengig geografi og transport-/reparasjonsvilkår.',19:'750 kroner egenandel og 5000 kroner faststed-transport mangler.',21:'Included skjuler uttrykkelig skadedyr, naturskade og ytre årsaker.',27:'Sum/dager finnes, men utløsende erstatningsmessig skade etter påbegynt ferie og alternativ overnatting mangler.',28:'Betalt utleie og næringsbruk krever særavtale; ingen tilsvarende avgrensning.',29:'Frost/snø, utetthet, råte, isolerglass og vibrasjon/vridning er ikke fullt representert. Super-fuktunntak beholdes.',30:'Løsørets konkrete gjenstandsunntak og ytre kaskohendelse mangler.',31:'Materielle oppgjørs-/elektronikk-/is-/garantiregler mangler.',32:'Sentrale forebyggingsvilkår for oppbevaring, frostsikring og tilbygg mangler.',33:'Kosmetisk funksjonsbasert oppgjør, godkjent verksted og 50 prosent arbeid uten verksted mangler.',34:'Rolle, Norden og tvist etter salg/leasingretur mangler bak included.',35:'100000 per tvist finnes, men konkret flerpartstabell mangler.',36:'Rettshjelp 4000 + 20 prosent mangler.',37:'Materielle rettshjelpunntak er ikke dokumentert i eksakt produkt.'}
ps=[p for p in A.c['products'] if p['providerId']=='storebrand' and p['insuranceType'] in ['Campingvogn','Tilhenger']]
for p in ps:
 pid=p['productId'];typ=p['insuranceType'];prefix='campingvogn' if typ=='Campingvogn' else 'tilhenger';lev='B' if pid.endswith('brann-og-tyveri') else 'S' if pid.endswith('super') else 'K';web=f'catalog/sources/vehicle-extensions/storebrand-{prefix}forsikring.html';fs=p['facts'];keysactual={f['key'] for f in fs}
 for r in I['rules']:
  n=int(r['inventory_id'].split('-')[-1])
  if typ not in r['types'] or lev not in r['levels']:continue
  keys=[prefix+'.'+k for k in K[n]];matched=[k for k in keys if k in keysactual]
  gap=n in why;cl=COARSE if matched else MISSING;prio=r['priority_if_missing'] if gap else '';reason=why.get(n,'Full katalogpåstand og kildeanvendelse kontrollert; dimensjonen er representert.')
  if not gap:cl=PRESENT
  if n in [1,22]:cl=CUSTOM;prio='';reason='Kundens valgte sum/egenandel er bevisstyrt, ingen fast verdi antas.'
  if n in [10,20,23]:cl='SOURCE_AMBIGUOUS';prio='';reason='Reell konflikt mellom lokale kilder eller kildeavsnitt. Ikke telt som sikkert missing/falseunknown.'
  if n==38:cl=ADMIN;prio='';reason='Administrative og generelle lov-/melderegler beholdes som kildeinformasjon.'
  A.fact(pid,r['subject'],r['dimension'],r['value'],web if r['page'] is None else path,r['section'] if r['page'] is None else f'PDF fysisk side {r["page"]} (trykt {r["page"]-1}), {r["section"]}',cl,matched or keys,prio,reason,'SCRC-011',inventory_id=r['inventory_id'],extra={'shared_source_inventory':'storebrand-camp-independent-inventory.json','source_rule_kind':r['kind'],'optional_availability_not_selection':r['kind']=='OPTIONAL','source_applicability':'camp02 exact type/level; conditional fortelt and increased sum not silently made selected'})
 verified={f['key']:{'artifact':path,'pdf_page':f['source'].get('page'),'section':f['source'].get('section'),'note':'Full 53 claim contents inspected; applicable full-term claim is supported, surrounding omissions listed separately.'} for f in fs}
 if typ=='Tilhenger':
  for k in [prefix+'.redning.dekning',prefix+'.brann.egenandel']:verified.pop(k,None)
  for c in A.support:
   if c['product_identity']==p['identity'] and c['key'] in [prefix+'.redning.dekning',prefix+'.brann.egenandel']:
    c.update(support_status='SOURCE_CONFLICT_REVIEW_REQUIRED',full_claim_validated=False,manual_reverse_evidence='Full terms support this claim; product page scopes/prices differ. Active application not resolved from local sources.')
 A.reverse(pid,verified)
 complete=typ=='Campingvogn' and lev!='S'
 A.product_review(pid,[path,web,general],complete,'Full 15-page camp02, exact product HTML and general11 by verified shared hash. 38 independent rules; all resolved facts, optional catalog availability and exact type applicability checked. '+('Package closed with recorded gaps.' if complete else 'Unclosed: Super contents sum conflict or Tilhenger website/full-term roadside/deductible scope conflict. No assumed reconciliation.'))
A.a['source_conflicts'].append(dict(id='SC-007',provider='storebrand',family='Campingvogn/Tilhenger',sources=[path,'catalog/sources/vehicle-extensions/storebrand-campingvognforsikring.html','catalog/sources/vehicle-extensions/storebrand-tilhengerforsikring.html'],claim='Super contents sum; Tilhenger roadside and deductibles',observed='Super table5=100000 vs text5/summary/damage tables=30000. Tilhenger website says roadside follows towing car/500; full terms included/750. Website fixed deductible1000 vs full terms8000 unless certificate.',status='SOURCE_APPLICABILITY_REVIEW_REQUIRED',action='Preserve conservative Super omission and conditional terms values; do not count ambiguity as proven missing. Obtain version/application clarification later.'))
A.checkpoint('Storebrand camp02 five products reviewed;two complete;three source conflicts retained','Innbo','storebrand','sb-innbo-standard')
