from continue_audit import *
A=Audit();I=load('frende-pet-independent-inventory.json')
A.root('SCRC-016','Frende pet packages encode six base facts and sparse optional components; source-documented limits, diagnosis conditions, settlement restrictions and services are absent or overly broad. Exact optional dependency of Bruksverdi on Tap is expressed in prose but not component membership.','lib/boat-pet-catalog.ts Frende pet definitions;32 source-first rules; full5/4page terms +2/2pageIPID+HTML;frende-pet-addon-probe.json proves Tap alone lacks bruksverdi facts and bruksverdi alone resolves withoutTap.',['Hund','Katt'],['frende'],'RB-14',complexity='SMALL_CODE')
K={1:['dyr.veterinar.sum.valgbar'],2:[],3:['dyr.veterinar.dekning'],4:['dyr.allergi.grense'],5:[],6:[],7:[],8:['dyr.veterinar.dekning'],9:['dyr.karenstid.sykdom'],10:[],11:[],12:[],13:[],14:['dyr.tannsykdom.dekning','dyr.tannsykdom.grense'],15:['dyr.tannsykdom.dekning'],16:['dyr.medisin.dekning'],17:['dyr.veterinar.sum.valgbar'],18:['dyr.veterinar.egenandel.fast','dyr.veterinar.egenandel.prosent'],19:['dyr.liv.dekning','dyr.liv.forsvinning'],20:['dyr.liv.dekning'],21:['dyr.liv.opphor'],22:[],23:[],24:[],25:['hund.bruksverdi.dekning','hund.bruksverdi.grense'],26:[],27:[],28:[],29:[],30:[],31:[],32:[]}
why={2:'Geografisk verdensdekning mangler.',3:'Inkludert sier ikke hvilke undersøkelser/behandlinger/klinikkmedisiner som omfattes.',4:'Beløp korrekt; førstegangsavgrensning, tidligere symptom og antistoffregel mangler.',5:'Konkrete diagnoser som gir unntak fra kastreringsunntaket mangler.',6:'Avliving/kremering2000 og10års/erstattetlidelsevilkår mangler.',7:'Base tannulykke begrenset til trekking brukne tenner mangler; ikke lik optional tannsykdom.',8:'Materielle veterinærunntak mangler.',9:'20d korrekt, men eksisterende lidelse og økningens begrensede karensscope mangler.',10:'Konkrete medfødte/leddtilstander og kontinuitet/foreldrekrav mangler.',11:'Korsbåndets alternative kontinuitetsvilkår mangler.',12:'Ett keisersnitt i livet og navngitte raseunntak mangler.',13:'Navngitte raseunntak for hud/øyne/luftveier mangler.',14:'Optional status og20000grense riktig; konkrete inkluderte behandlinger mangler.',15:'Tannsykdomunntak og særskilt ettårs etteropphørfrist mangler.',16:'Kun optional status;20000/event/år, reseptbehov og50%spesialfôr mangler.',17:'Perhendelse/år peker riktig, men samletvet+medisin og sammehendelse overflereår uttrykkes ikke.',20:'Tapsdekningens eksisterende/20d/komplikasjonsunntak mangler.',22:'Tap20%perheleår over7 mangler; ingen ny maksprosent antas.',23:'Tap0egenandel mangler.',24:'Erstatningsgrunnlag/bevistak,3mndventetid og tilbakebetalingsregel mangler.',25:'50% og Tap-tilknytning står i tekst; under8, fulltaptrentbrukshund og unntak mangler.',26:'Konkrete sikkerhetskrav mangler.',27:'Dokumenterte alders/overførings/annenforsikringsvilkår mangler.',28:'Katt-ID og hundsumterskel forID mangler.',29:'Videoveterinær uten egenandel mangler.',30:'Hundvet helelivet mangler; skal ikke arve Tapopphør10.',31:'Hundansvar ikkeomfattet mangler; separat innbodekning skal ikke impliseres.'}
for animal,typ in [('dog','hund'),('cat','katt')]:
 pid=f'frende-{typ}-veterin-r';p=A.p[pid];path=f'catalog/sources/boat-pet/frende-{animal}-terms.pdf';web=f'catalog/sources/boat-pet/frende-{animal}-product.html';ipid=f'catalog/sources/boat-pet/frende-{animal}-ipid.pdf';full=p['facts']+sum(p['addonFacts'].values(),[]);actual={f['key'] for f in full}
 for q in I['rules']:
  n=int(q['inventory_id'].split('-')[-1]);scope=q['scope']
  if scope in ['dog','dental','dogloss'] and animal!='dog':continue
  comp=f'frende-{typ}-'+({'dental':'tann','medicine':'medisin','loss':'tap','dogloss':'bruksverdi'}.get(scope,'')) if scope in ['dental','medicine','loss','dogloss'] else ''
  keys=K[n];cls=COARSE if any(k in actual for k in keys) else MISSING;pr='P2' if q['kind']=='P2' else 'P1';reason=why.get(n,'Exact source rule reviewed.');val=q['value']
  if n==1:cls=CUSTOM;pr='';reason='Valgt sum og dyr følger beviset. Ikke anta maksimum50k er kundens valgte sum.'
  if n==18:cls=PRESENT;pr='';reason='25% med minimum1000 korrekt i to eksisterende facts; ingen additiv1000+25%-påstand eller runtimeberegningsfeil påstås.'
  if n==19:
   if animal=='cat':cls=REVIEW;pr='';val='Fullvilkår2026 6.1: død/avliving eller stjålet ved innbrudd i bygning. IPID2025: stjålet eller kommer bort.';reason='Forsvinning i katalogen siterer2026fullterms som ikke dokumenterer dette; eldreIPIDstøtte finnes, så source/versionconflict beholdes.'
   else:cls=COARSE;reason='Død/avliving/forsvinning representert, men tyveri og fullt arbeidsfunksjonstap er ikke samlet under Tap-komponenten.'
  if n==21:cls=PRESENT;pr='';reason='Eksakt hovedforfall etter10år bevart, ikke erstattet med fødselsdag.'
  if n==32:cls=ADMIN;pr='';reason='Generelle saksbehandlingsplikter, ikke selvstendige dekningsfacts.'
  art=web if n in [27,28,30,31] else ipid if n==29 else path
  loc='HTMLFAQ' if art==web else 'IPIDside1' if art==ipid else f'PDFside{",".join(map(str,q["pages"]))}punkt{q["section"]}'
  A.fact(pid,q['subject'],q['dimension'],val,art,loc,cls,keys,pr,reason,'SCRC-016',comp,q['inventory_id'],extra={'shared_source_inventory':'frende-pet-independent-inventory.json','optional_availability_not_customer_selection':True})
 locs={'dyr.veterinar.dekning':(2,'4.1'),'dyr.veterinar.sum.valgbar':(4 if animal=='dog' else 3,'8.4' if animal=='dog' else '7.4'),'dyr.veterinar.egenandel.fast':(5 if animal=='dog' else 4,'8.6' if animal=='dog' else '7.6'),'dyr.veterinar.egenandel.prosent':(5 if animal=='dog' else 4,'8.6' if animal=='dog' else '7.6'),'dyr.allergi.grense':(2,'4.1'),'dyr.karenstid.sykdom':(3 if animal=='dog' else 2,'4.2'),'dyr.medisin.dekning':(3,'6' if animal=='dog' else '5'),'dyr.tannsykdom.dekning':(3,'5'),'dyr.tannsykdom.grense':(3,'5.1'),'dyr.liv.dekning':(3,'7' if animal=='dog' else '6'),'dyr.liv.opphor':(2,'2'),'hund.bruksverdi.dekning':(4,'7.1/7.3'),'hund.bruksverdi.grense':(4,'8.4')}
 if animal=='dog':locs['dyr.liv.forsvinning']=(3,'7.1')
 A.reverse(pid,{k:dict(artifact=path,pdf_page=pg,section=sec,location_correction=True,note='Exact claim supported; missing conditions separately inventoried. Optional does not imply customer selection.') for k,(pg,sec) in locs.items() if k in actual})
 if animal=='cat':
  for claim in A.support:
   if claim['product_identity']==p['identity'] and claim['key']=='dyr.liv.forsvinning':claim.update(full_claim_validated=False,support_status='SOURCE_VERSION_CONFLICT',manual_reverse_evidence='2026fullterms6.1onlytheftduringbuildingburglary;2025IPIDalso disappearance. Citation to2026 does not support broad disappearance; no unsupported global claim because older official support exists.')
 else:
  f=A.fact(pid,'Bruksverdi','Tap-componenttilknytning','Bruksegenskapstap er hendelse7.1.3 innen Tap,50%etter8.4. Catalogresolver tillater separatBruksverdi utenTap,ogTapalene mangler begge bruksverdifacts.',path,'PDFside3–4 punkt7/8.4','SEMANTICALLY_MISMAPPED',['hund.bruksverdi.dekning','hund.bruksverdi.grense'],'P1','Den dokumenterte deldekningen splittes til uavhengig addon uten dependency; exact pure-runtimeprobe viser begge retninger. Ingen feil faktisk kundevalg påstås.','SCRC-016','frende-hund-bruksverdi','FR-PE-DEPENDENCY',extra={'runtime_evidence':'frende-pet-addon-probe.json'})
  g=next(g for g in A.a['findings'] if g['finding_id']==f['finding_id']);g.update(remediation_type='ADDON',remediation_complexity='SMALL_CODE')
 A.product_review(pid,[path,ipid,web],animal=='dog','Full source-first package read; all exact base and optional facts reverse checked. Hund review closed with recorded dependency defect; Katt remainspartial for2025IPID/2026terms disappearance applicability. No newproducts or customerchoices invented.')
 for aid in p['addons']:
  ad=next(x for x in A.a['addon_coverage'] if x['addon_id']==aid);complete=aid!='frende-katt-tap';ad.update(status='COMPLETE' if complete else 'PARTIAL',fully_audited=complete,semantic_audit_status='COMPLETE' if complete else 'PARTIAL',notes='Source-first optional scope fully checked; recorded gaps remain. Dependency defect recorded, notimplemented.' if complete else 'Fullterms2026/IPID2025 disappearance conflict unresolved.')
A.a['source_conflicts'].append(dict(id='SC-011',provider='frende',family='Katt',sources=['catalog/sources/boat-pet/frende-cat-terms.pdf','catalog/sources/boat-pet/frende-cat-ipid.pdf'],claim='Tap: forsvinning versus theftduringbuildingburglary',observed='2026fullterms6.1doesnotlistdisappearance;2025IPIDlistsstolenorcomesaway;catalogincludesdisappearanceciting2026fullterms.',status='SOURCE_VERSION_APPLICABILITY_REVIEW_REQUIRED',action='Do not assert disappearance safely included under2026. No online research authorized; preserve conflict and seek exact current applicability later.'))
A.checkpoint('Frende pets source-first closure: Hund complete with recorded gaps; Katt source-version conflict; five optional packages closed','Bil','frende','frende-bil-ansvar')
