from continue_audit import *
A=Audit();I=load('frende-reise-independent-inventory.json');pid='frende-reiseforsikring';base='catalog/sources/frende/reise/';path=base+'Vilkar-reiseforsikring-01032026.pdf';p=A.p[pid]
A.root('SCRC-010','Frende Reise har en omfattende base, men enkelte eksplisitte avgrensninger og sekundærytelser er utelatt fra forfatterradene: blant annet familiekrav, avbestillingsvilkår, reisesykeunntak, innhenting av reiserute og dødsbegunstigelse. Ingen bevis for tap i motoren.','lib/frende-reise-catalog.ts:11–73: samtlige55 resolvedfacts,ingenaddons, allefullfelt og services inspisert mot56uavhengige kilderegler.',['Reise'],['frende'],'RB-09')
# Correct source section references against actual PDF headings; source meanings read before catalog.
sections={1:'1',2:'2.1–2.2',3:'2.1–2.2 + produktside FAQ',4:'2.1–2.2',5:'2.1',6:'3.1–3.2',7:'3.1',8:'3.1',9:'3.3',10:'3.4',11:'4.1',12:'4.2',13:'4.3',14:'4.4',15:'5.1–5.2',16:'5.1',17:'5.3',18:'5.2',19:'5.4',20:'5.4',21:'5.5',22:'5.5',23:'5.6',24:'10.4',25:'6.1–6.2',26:'6.2',27:'6.3',28:'6.4',29:'6.4',30:'6.5',31:'6.5–6.6',32:'6.7',33:'6.8',34:'6.9',35:'7.1',36:'7.1–7.2',37:'8.1–8.2',38:'9.1–9.2 og16/11',39:'10.5',40:'10.6',41:'11.1 og11.3–11.4',42:'11.5',43:'11.6.3',44:'11.3',45:'11.2',46:'12.1',47:'12.4',48:'12.2',49:'13.1',50:'13.4',51:'13.3–13.4',52:'16',53:'14–17 oggenerelle'}
K={1:['personer.omfang'],2:['varighet.maks','omrade.verden'],3:['varighet.enkeltreise_utvidelse'],4:['omrade.verden','omrade.ud'],5:['omrade.ud'],6:['avbestilling.dekning'],7:['avbestilling.dekning'],8:['avbestilling.dekning'],9:['avbestilling.dekning','medisinsk.graviditet'],10:['avbestilling.dekning'],11:['forsinkelse.rute'],12:['forsinkelse.rute'],13:['forsinkelse.hotell_arrangement'],14:['forsinkelse.unntak'],15:['bagasje.dekning'],16:['bagasje.uhell','bagasje.uhell_sum'],17:['bagasje.total','bagasje.per_gjenstand','bagasje.kontanter','bagasje.pass_billetter','bagasje.leid','bagasje.nokler'],18:['bagasje.dekning','bagasje.sportsutstyr'],19:['bagasje.forsinket'],20:['bagasje.forsinket'],21:['leiebil.egenandel'],22:['leiebil.egenandel'],23:['skadedyr.dekning'],24:['skadedyr.dekning','skadedyr.egenandel'],25:['medisinsk.behandling','medisinsk.kjent'],26:['aktivitet.unntak'],27:['medisinsk.behandling','medisinsk.kjent','medisinsk.graviditet'],28:['medisinsk.behandling','medisinsk.tann'],29:[],30:['hjemtransport','hjemkallelse'],31:['hjemtransport','sykeledsagelse'],32:[],33:['medisinsk.kriseterapi'],34:['tjeneste.alarm'],35:['reiseavbrudd'],36:['reiseavbrudd'],37:['evakuering'],38:['veterinar'],39:['bagasje.aldersfradrag'],40:['bagasje.egenandel'],41:['ulykke.invaliditet','ulykke.dodsfall','ulykke.dekning'],42:['ulykke.behandling'],43:['ulykke.invaliditet'],44:['ulykke.dodsfall'],45:['ulykke.dekning','aktivitet.unntak'],46:['ansvar.dekning'],47:['ansvar.sum','ansvar.egenandel'],48:['ansvar.dekning'],49:['rettshjelp.dekning'],50:['rettshjelp.sum','rettshjelp.egenandel'],51:['rettshjelp.dekning'],52:['sikkerhet.reisegods','bagasje.sykkel','veterinar','aktivitet.unntak','medisinsk.behandling'],53:['avtale.generellevilkar','avtale.forbehold'],54:['tjeneste.legehjelp'],55:[],56:[]}
coarse={1,6,7,8,9,10,11,14,15,18,27,28,43,44,45,49,51,54};missing={29,32,56}
reasons={1:'Katalog sier folketrygd/Norge bare om forsikringstaker; fullvilkår krever dette for alle forsikrede.',6:'Katalog mangler før-avreise-legebekreftelse og EØS-bosetting for den omfattede familiekretsen.',7:'Flyttet operasjonsdato mangler;14dagersvilkår ved nøkkelperson/rettsplikt mangler.',8:'Arrangement/utflukt krever dekket betalt overnatting, ikke selvstendig arrangement-only avbestilling.',9:'Avbestillingsutelukkelse for forventet kjent sykdom, kostnader etter årsak, påbegynt reise og førtegning uten kontinuitet fremgår ikke av avbestillingsfact; reisesykekjent er annen dekning.',10:'Uforsikrede medreisendes kostnader/timeshare ogrefunderbareskatter mangler i avbestillingsfact.',11:'Privatbil tekniskfeil/trafikkuhell må kreve berging; katalog tekniskfeil alene blir bredere.',14:'Forsinkelsens mat/drikke/taptinntekt og privat-/leasingbilunntak ikke representert.',15:'Reisegods skiller egen/lånt/leid fra eksplisitt unntatt arbeidsgiverutstyr; denne materialscope mangler.',18:'Familieforvoldt skade, kjøretøy/båttilbehør/nøkler og innsjekket væskesøl mangler; behold allerede korrekte kosmetikk/drone/slitasje-unntak.',27:'Private nordiske behandlere og lete-/redningsaksjon er eksplisitt unntatt, men ikke i katalogens medisinske facts.',28:'Egenbil5kr/km ved behandlingsreise mangler, tannsummer og øvrige kostnader er representert.',29:'Innhenting av reiserute etter legepålagt avbrudd ved sykdom er ikke representert av vær-/tekniskforsinkelsesfact.',32:'Særdekning ved eneste medreisendes sykdom/familiehendelse er ikke lik tilkalling av egenfamilie eller egen sykdom.',43:'Ettår førkrav/treår endeligvurdering og fradragfor tidligeremedisinskinvaliditet mangler.',44:'Dødsfall uten ektefelle/barn/samboer eller gyldig begunstigelse gir ikke ordinær utbetaling; sum alene skjuler dette.',45:'Rygg/nakke-bruddkrav og særskilt passasjerunntak samt PTSD-begrensning er ikke konkretisert i generellulykkestekst.',49:'Yrkesrelatert rettshjelp beskrives kategorisk unntatt; kilde har domstolsunntak for yrkesskade.',51:'Investeringsgrense100000/allaksjehandel, motpartskost ogankegebyr mangler.',54:'Tjenesten er korrektmodellert, men ubegrensetantall konsultasjoner er ikke eksplisitt bevart.',56:'Rabatt på preventiv bagasjefrysing er en egen omtalt fordel, ikke skadebekjempelsesdekningen.'}
for r in I['rules']:
 n=int(r['inventory_id'].split('-')[-1]);v=r['value'];s=path;page=r['page'];sec=sections.get(n,r['section'])
 if n==4:v='Hele verden; ikke hjem/jobb/skole/barnehage/midlertidig bosted; bretur i Arktis (unntatt Svalbard), Antarktis eller Grønland unntatt. Ikke alle reiser til geografien generelt.'
 if n in (41,44):page=12
 if n==45:page=11
 if n==43:page=12
 if n==54:s=base+'Legetime-pa-mobilen.html'
 if n==55:s=base+'Reiseforsikring-Midtosten-2026.html'
 if n==56:s=base+'Reiseforsikring-produktside.html'
 classification=COARSE if n in coarse else MISSING if n in missing else CUSTOM if n==3 else ADMIN if n==53 else 'SOURCE_ONLY_ACCEPTABLE' if n==55 else PRESENT
 priority=r['priority_if_missing'] if n in coarse|missing else ''
 reason=reasons.get(n,'Hele faktaverdien kontrollert på eksakt produkt; ikke bare nøkkeltilstedeværelse.')
 if n==55:reason='Ekstraordinær hendelses-/datospesifikk ordning, korrekt holdt utenfor ordinary canonicalbase; ikke katalogmangel.'
 A.fact(pid,r['subject'],r['dimension'],v,s,f'PDF side{page}, {sec}' if page else sec,classification,['reise.'+k for k in K[n]],priority,reason,'SCRC-010',inventory_id=r['inventory_id'])
# Reverse support: exact catalog claim justified, except pregnancy boundary awaiting wording review.
loc={f['key']:{'artifact':path if f['source']['documentId']=='frendeReiseTerms' else base+f['source']['filename'],'pdf_page':f['source'].get('page'),'section':f['source'].get('section'),'note':'Exact55factreview completed; missing surrounding dimensions logged independently.'} for f in p['facts'] if f['key']!='reise.medisinsk.graviditet'}
A.reverse(pid,loc)
A.fact(pid,'Graviditet','uke36formulering','Fullvilkår unntar etter36.svangerskapsuke. Katalogens første setning sier føruke36, mensandre sieretter36. Dette trenger presisjonskontroll; ingen antatt reduksjon av kundedekning.',path,'PDF side7,6.3 ogside3,3.3',REVIEW,['reise.medisinsk.graviditet'],reason='To formuleringer i ett katalogfact skaper muliggrenseuklarhet; ikke med i verifiserte P1/P2.')
A.a['source_conflicts'].append({'id':'SC-005','provider':'frende','family':'Reise','product':pid,'sources':[path,base+'Reiseforsikring-produktside.html'],'claim':'Forsinketarrangement ogfortsettelsesdekning','observed':'StoredHTML5000 versus fullterms2026 6000; HTMLsameconditionsforextension versus explicit fullterms7.1 noferiedaysforcontinuation.','status':'RESOLVED_BY_APPLICABLE_FULL_TERMS','action':'Katalogbruker6000ogeksplisittunntak korrekt. Ikke kataloggap.'})
A.product_review(pid,[path,base+'IPID-Reise-2026.pdf',base+'Generelle-vilkar-01012026.pdf',base+'Legetime-pa-mobilen.html',base+'Reiseforsikring-Midtosten-2026.html',base+'Reiseforsikring-produktside.html',base+'Reiseforsikring-vilkarsside.html'],False,'56independentsourcerules,all17pfull+2pIPID+4HTML+general4hashreuse;55fullfacts compared.54reverseclaimschecked; pregnancyweek36boundary wording stillreview. Materialmissing/coarsedimensionsarecatalogauthored,notruntime-loss. ExtraordinaryMiddleEastmeasureexcludedordinary. Historical2020notapplicable. Source-first inventory initialsectionnumbers reconciled toactualPDFheadings here.')
A.checkpoint('Frende Reise full package read;54reverseclaimschecked; oneboundaryreview remains','Bil','storebrand','sb-bil-ansvar')
