from continue_audit import *
A=Audit();I=load('frende-hus-independent-inventory.json');path=I['source'];pids=['frende-hus-standard','frende-hus-utvidet']
A.root('SCRC-009','Frende Hus har detaljert og stort sett korrekt basemodell. Enkelte oppgjørsvilkår, indeksprisstigning/egenbrukstap og konkrete unntak er ikke representert; dette er utelatte forfatterrader, ikke tap i inheritance. Aldersfradragets årsaksbegrensning finnes allerede i structuredValue, og materialunntaket i label; de er IKKE katalogmangler.','lib/frende-hus-catalog.ts:24–35,37–96,98–135; alle base-/inherited-/addonfactfelter inkl structuredValue/label kontrollert.',['Hus'],['frende'],'RB-08',complexity='SMALL_CODE')
K={1:['hus.forsikringsform'],2:['hus.bygninger.dekning','hus.bygninger.tilbehor'],3:['hus.ror.utvendig','hus.teknisk.solceller'],4:['hus.hage.objekter','hus.hage.basseng'],5:['hus.hage.brygge'],6:['hus.ror.utvendig'],7:['hus.brann.dekning','hus.elektrisk.dekning','hus.eksplosjon.dekning','hus.snovejr.dekning','hus.tyveri.dekning','hus.naturskade.dekning','hus.plutselig.dekning'],8:['hus.vann.utstromming','hus.vann.terreng','hus.ror.brudd'],9:[],10:['hus.skadedyr.bygningsskade'],11:['hus.skadedyr.bekjempelse'],12:['hus.ror.tining'],13:['hus.tilpasning.grense'],14:['hus.plutselig.dekning','hus.vatrom.folgeskade','hus.vatrom.selverommet','hus.takvegg.folgeskade','hus.handverker.folgeskade','hus.rate.dekning','hus.skadedyr.bygningsskade'],15:['hus.rydding.dekning','hus.leietap.skade'],16:['hus.pabud.dekning'],17:['hus.pabud.dekning'],18:['hus.gjenoppforing.hovedregel'],19:['hus.gjenoppforing.annetsted'],20:['hus.forsikringsform'],21:['hus.gjenoppforing.ingen'],22:[],23:['hus.aldersfradrag.utvendige_ledninger_tanker','hus.aldersfradrag.varmtvannsbereder_pumper','hus.aldersfradrag.basseng_boblebad','hus.aldersfradrag.oppvarming_kjoling'],24:['hus.aldersfradrag.utvendige_ledninger_tanker'],25:['hus.aldersfradrag.varmtvannsbereder_pumper'],26:['hus.aldersfradrag.basseng_boblebad','hus.aldersfradrag.oppvarming_kjoling'],27:['hus.egenandel.generell','hus.skadedyr.egenandel','hus.glass.egenandel','hus.naturskade.egenandel','hus.vannoverflate.egenandel'],28:['hus.egenandel.gjentatt_skade'],29:['hus.egenandel.fritak'],30:['hus.ansvar.dekning'],31:['hus.ansvar.grense','hus.ansvar.egenandel'],32:['hus.rettshjelp.dekning'],33:['hus.rettshjelp.grense','hus.rettshjelp.egenandel'],34:['hus.rettshjelp.dekning'],35:['hus.rettshjelp.dekning'],36:['hus.takvegg.folgeskade'],37:['hus.vatrom.folgeskade','hus.vatrom.selverommet'],38:['hus.handverker.folgeskade'],39:['hus.handverker.folgeskade','hus.takvegg.folgeskade'],40:['hus.glass.isolerglass_punktering'],41:['hus.rate.dekning'],42:['hus.rate.dekning'],43:['hus.skadedyr.bekjempelse'],44:['hus.rate.dekning'],45:['hus.utleie.vilkar','hus.utleie.skadeverk'],46:['hus.leietap.skade','hus.utleie.vilkar'],47:[],48:[],49:[]}
coarse={14,17,20,21,30,32,33,35,39,46};missing={9,22,48,49};source_ambiguous={2}
for pid in pids:
 p=A.p[pid]
 for r in I['rules']:
  n=int(r['inventory_id'].split('-')[-1]);value=r['value']
  if r['scope']=='extended' and pid!='frende-hus-utvidet':continue
  if n==7:value='Brann,elektrisk,eksplosjon,snø/vind,tyveri,naturskade og annen plutselig skade; forurensning inventoreres separat.'
  if n==15:value='Riving/rydding/deponering og bevisavtalt leietap i normal reparasjons-/gjenoppføringstid. Indeksprisstigning/egenbruk inventoreres separat.'
  if n==27:value='Avtalt egenandel;skadedyrskade6 000,bekjempelse2 000,glass6 000,naturskade8 000,vind/overflate-/terrengvann8 000 med mindre høyere avtalt. Sprengingstillegg inventoreres separat.'
  classification=COARSE if n in coarse else MISSING if n in missing else 'SOURCE_AMBIGUOUS' if n in source_ambiguous else CUSTOM if r['kind']=='CUSTOMER_SPECIFIC' else ADMIN if r['kind']=='ADMINISTRATIVE' else 'SOURCE_FACT_OPTIONAL_COMPONENT' if n==47 else PRESENT
  priority=r['priority_if_missing'] if n in coarse|missing else ''
  reason='Full kildebetydning kontrollert mot nøkkel, label, verdi, structuredValue, qualificationSource og komponenter.' if classification==PRESENT else 'Eksakt kildeavgrensning/ytelse er ikke fullstendig representert i resolved base, inheritance eller tilgjengelige tillegg.' if priority else 'Kundens valg/kildeusikkerhet/særskilt risikosituasjon holdes adskilt fra ordinær ubetinget produktdekning.'
  extra=None
  if n==47:
   extra={'catalog_non_runtime_component':'frendeHusConstruction','catalog_non_runtime_evidence':A.c['components']['frendeHusConstruction'],'availability_status':'INTENTIONALLY_NOT_ORDINARY_ADDON','needs_product_scope_decision':True}
   reason='Fem kildebaserte facts finnes i frendeHusConstruction, men komponenten inngår ikke i de to aktive produktene eller deres tilgjengelige addons. Ikke manglende katalogdata; valg av særskilt byggunderoppføring-flow er eget produktomfangsspørsmål.'
  A.fact(pid,r['subject'],r['dimension'],value,path,f"PDF side {r['page']}, {r['section']}",classification,K.get(n,[]),priority,reason,'SCRC-009',r['component'] if r['component']!='SOURCE_OPTIONAL_UNMODELED' else '',inventory_id=r['inventory_id'],extra=extra)
 for subject,dim,val,page,sec,keys,priority in [('Gjenoppføring','indeksprisstigning','Påløpte utgifter til prisstigning etter byggekostnadsindeksen i normal reparasjon/gjenoppføring.',5,'5.8/2',['hus.gjenoppforing.prisstigning'],'P2'),('Egenandel','sprenging','6 000 kroner i tillegg til ordinær egenandel ved sprenging på forsikringsstedet.',8,'6.14 – tabell',[],'P2')]:
  A.fact(pid,subject,dim,val,path,f'PDF side{page}, {sec}',MISSING,keys,priority,'Ingen tilsvarende resolved/optional fact i eksakt produkt.','SCRC-009')
 A.fact(pid,'Standard','import av alternative brannunntak','Standard5.1–5.6 har egne dekninger/unntak. Katalogens elektrisk/eksplosjon henviser samtidig til4.2, som står under alternativet Brann og naturskade. Flere gamle kryssreferanser i fullvilkåret gjør anvendelsen usikker.',path,'PDF side3–5,4.2 og5.1/5.6','SOURCE_AMBIGUOUS',['hus.elektrisk.dekning','hus.eksplosjon.dekning'],reason='Ikke kalt bevist unsupported claim. Avklar om4.2 gjelder valgt Standard, ikke bare alternativ brannforsikring.')
 loc={}
 for f in p['facts']+sum(p['addonFacts'].values(),[]):
  if f['key'] in ['hus.bygninger.dekning','hus.elektrisk.dekning','hus.eksplosjon.dekning']:continue
  loc[f['key']]={'artifact':path,'pdf_page':f['source'].get('page'),'section':f['source'].get('section'),'note':'Exact value, label and structuredValue checked; excluded three ambiguous source-applicability claims. Sources for IPID/general/HTML remain their own documents.'}
 A.reverse(pid,loc)
 A.product_review(pid,[path,'catalog/sources/frende/hus/canonical/IPID-Hus.pdf','catalog/sources/frende/hus/canonical/Husforsikring-produktside.html','catalog/sources/frende/hus/canonical/Rate-og-skadedyr-produktside.html','catalog/sources/frende/hus/canonical/Generelle-vilkar-01012026.pdf'],False,'50source-first rules, full16page terms+allIPID/HTML;general reused byexacthash. Age/egenandel tablepage8visualchecked. Three catalogsource applicability questions retained: smalloutbuilding source4.1/1–10 vs catalog5.1, alternativefire4.2 exclusions on Standard. Existing structured age deductions correctly preserve causes and materialexceptions; no gap counted. Two availableaddons complete. Five constructionfacts exist outside runtime; not counted missingdata.')
for aid in ['frende-hus-rate-skadedyr','frende-hus-utleie']:
 ad=next(x for x in A.a['addon_coverage'] if x['addon_id']==aid);ad.update(status='COMPLETE',semantic_audit_status='COMPLETE',fully_audited=True,notes='Exactaddon fullterms+baseprerequisites+bothproducts reviewed. Optionality retained. Detailed source omissions listed; raw source age/sourcehierarchy not generalized.')
 for f in A.f:
  if f['component']==aid:f['full_package_review_complete']=True
 for g in A.a['findings']:
  if g['component']==aid:g['complete_package_audited']=True
A.a['source_conflicts'].append({'id':'SC-004','provider':'frende','family':'Hus','product':pids,'sources':[path,'catalog/sources/frende/hus/canonical/Husforsikring-produktside.html'],'claim':'Tining og feilnummererte fullvilkårshenvisninger','observed':'HTMLmatrix includes tiningbothlevels butprose saysUtvidet;fullterms5.3 explicitlyStandard andcatalogcorrect. Other fullterm3.1 points4.1/1–10 although4.1has3items;cataloguses5.1.','status':'PARTIALLY_RESOLVED_SOURCE_WORDING','action':'Tiningresolvedbyfullterms;outbuilding/alternativefire scope remainsreview. No guessed sourcecorrection.'})
A.checkpoint('Frende Hus two full-package partial reviews; two material addons complete','Reise','frende','frende-reiseforsikring')
