from continue_audit import *
A=Audit();I=load('if-boat-independent-inventory.json');T='catalog/sources/boat-pet/if-boat-terms.pdf';D='catalog/sources/boat-pet/if-boat-ipid.pdf'
# Physical pages retained; exact section numbers corrected against source headings.
for n in [44,45,46,47]:I['rules'][n-1]['location']=I['rules'][n-1]['location'].replace('§7','§6.3')
for n,loc in [(48,'15–16 §9.1'),(49,'16 §9.2'),(50,'17–19 §10.2–10.7'),(51,'18–19 §10.6–7'),(52,'2 §2;20 §11')]:I['rules'][n-1]['location']=loc
save('if-boat-independent-inventory.json',I)
A.root('SCRC-041','If Båt representerer et lite utvalg hoveddekninger, men utelater materielle summer, egenandeler, nybåt- og Superytelser. Motor/gir-egenandelens minste8k-påstand overser dokumentert4kgren.','55source-firstregler fraBÅT2-1/IPID mot alle exactbase/addon/componentfacts; fullvilkår§4.9.5 har4ktil5år,8ktil10år og gradert11–15.',['Båt'],['if'],'RB-37')
K={1:[],2:['bat.geografi.omrade'],3:['bat.transport.dekning','bat.geografi.omrade'],4:[],5:[],6:['bat.losore.dekning','bat.losore.grense'],7:['bat.opplagsutstyr.dekning'],8:['bat.jolle.dekning','bat.jolle.grense'],9:['bat.losore.dekning'],10:['bat.ansvar.dekning','bat.rettshjelp.dekning','bat.ulykke.dekning'],11:['bat.brann.dekning','bat.tyveri.dekning'],12:['bat.kasko.dekning'],13:[],14:['bat.transport.dekning'],15:['bat.redning.dekning'],16:['bat.redning.dekning'],17:['bat.redning.dekning'],18:['bat.maskinskade.dekning'],19:['bat.maskinskade.dekning'],20:['bat.maskinskade.alder'],21:['bat.maskinskade.dekning'],22:['bat.maskinskade.dekning'],23:['bat.maskinskade.egenandel'],24:['bat.maskinskade.dekning'],25:[],26:['bat.losore.grense'],27:['bat.ferieavbrudd.dekning','bat.ferieavbrudd.dagsbelop','bat.ferieavbrudd.dager'],28:['bat.transport.dekning'],29:['bat.totalskade.dekning','bat.totalskade.alder'],30:['bat.opplagsutstyr.dekning'],31:[],32:[],33:['bat.kasko.dekning'],34:[],35:['bat.losore.dekning'],36:[],37:[],38:[],39:[],40:[],41:[],42:[],43:['bat.totalskade.dekning','bat.totalskade.alder'],44:['bat.rettshjelp.dekning'],45:['bat.brann.dekning','bat.tyveri.dekning'],46:['bat.tyveri.dekning'],47:['bat.kasko.dekning','bat.jolle.dekning'],48:['bat.ansvar.dekning'],49:['bat.ansvar.dekning'],50:['bat.ulykke.dekning'],51:['bat.ulykke.dekning'],52:['bat.rettshjelp.dekning'],53:[],54:['bat.jolle.dekning','bat.opplagsutstyr.dekning'],55:[]}
why={2:'Radius representert; nøyaktige overfarter/Svalbardgrense er bare dokumenterte overfarter.',3:'Katalogtransport etter skade er ikke samme som ordinær land/vann-transport/opplag eller seilregatta.',6:'50k riktig påKasko men midlertidigbagasje/andresrestprioritet ikke med;Delkasko manglerdennegrensen.',7:'50kopplagsutstyr mangler,med separatIPIDnivåavklaring forDelkasko.',8:'Jollensbåt-/motor-/verdigrenser mangler;sikreKasko+Super,Delkaskobevaresreview.',10:'Ansvar/rettshjelp representert,ulykke mangler separat positivefact.',11:'Hovedbrann/tyverimed;hærverk/lyn/eksplosjon kreverpresisering.',12:'BareInkludert beskriverikkehvilkeplutseligefarersomdekkes.',13:'Egen gratisundersøkelse ettergrunnstøting finnes ikkeikatalogen.',14:'Kaskotransportgrunn riktig,menikkeDelkasko ogverksted/midlertidigreparasjon mangler.',15:'Bergelønnutløsesavdekkedefarer ogsåDelkasko,ikkeubetingetKaskoassistanse.',16:'10%forsikringssum forpålagtvrakfjerningrepresenteresikkeavRedningInkludert.',17:'Slepetsutløser/mål ogforhåndsgodkjenningmangler.',19:'Dekningskomponentene skjules underMotor/girtillegg.',20:'15årerrettmen1januaretterkjøpny-alderberegning mangler.',21:'Garantibegrensning,slitasje/frost/konstruksjon ogøkonomi mangler.',22:'Vesentligdokumentasjons-/vedlikeholdsvilkårmangler.',23:'Påstand minst8k/aldersgradertprosent gjelderikketil5år4keller6–10årfast8k;reelle tabellgrener måbevares.',24:'Taketførskadegjenanskaffelsesverdi ogfradragsmekanisme mangler.',27:'BareInkludert mister2k/dag21dager/sesong/utløser.',28:'Hjemreise/henting erikke samme somgrunntransportverksted.',29:'Super3års kjøpsprisellerhøyeregjenanskaffelsemedsumtak mangler helt.',30:'OpplagsutstyrInkludert misterubegrensetsumoghvordanegenandelberegnes.',31:'Superuhell40k/gjenstandog2k/4kegenandelmangler helt.',32:'Uhell har eksplisittdata/phone/tabletunntak,ikkegenerell elektronikksikring.',33:'KaskoInkludertkanikkeerstattevarmkjøringogandrevesentligeunntak.',34:'Boblehavn-unntaksunntak børholdesatskiltfrafrostunntaket.',35:'Bagasje50k/unlimitederikkeuhellalene;farene/endeløsetingseparate.',36:'Utleieavtalebevis nødvendig;seilregatta måikkeforvekslesmedforbudtmotorrace.',38:'Vinterliggeerstyrtavsikkerhetskrav,ikkeetforbud;forebyggvilkårmangler.',40:'Sumtak/reparasjonsverdi/aldersfradragikkeikatalog.',42:'Mast/bomtotalskadeunntattaldersfradragmangler.',43:'Felles1år/60%nybåtregelmangler;ikkeifavøravufundertubetingetnyverdi.',44:'Egenandelansvar0/rettshjelp4k+20/redning0mangler.',45:'Standard6kforbrann/tyverimangler,bevisavvikmåbevares.',46:'Dokumenterte2k/4kfradrag mangler.',47:'Kasko6k/jolle4kmangler.',48:'AnsvarInkludertmister50mill/rolle.',50:'200kinvaliditet/100kdød/person/situasjonmangler.',52:'Nordenogettersalg/rolleutelatt;§22generalversjonmåidentifiseresførbeløpimporteres.',53:'IPIDtarforbeholdomfirmaregistreringogpermanentplassutenforNorden.',54:'Full§3.1ogIPIDmatrisegirulikavgrensning;ikkenormaliserkonfliktbort.'}
for tier in ['delkasko','kasko','super']:
 pid='if-bat-'+tier;p=A.p[pid];rows=[]
 for n,q in enumerate(I['rules'],1):
  if q['scope']=='upper' and tier=='delkasko' or q['scope']=='super' and tier!='super' or q['scope']=='lower' and tier=='super' or q['scope']=='motor' and tier=='delkasko':continue
  comp='if-bat-motor-gir' if q['scope']=='motor' else ''
  fs=p['addonFacts'].get(comp,[]) if comp else p['facts']
  cls=COARSE if any(f['key'] in K[n] for f in fs) else MISSING;pri='P1'
  if n in [1,5,9,11,19,21,22,24,28,32,34,35,38,39,40,41,42,46,49,51,53]:pri='P2'
  if n==18 or n==26:cls=PRESENT;pri=''
  if n==25:cls='SOURCE_FACT_OPTIONAL_COMPONENT';pri=''
  if n==4 or n==37:cls=CUSTOM;pri=''
  if n==55:cls=ADMIN;pri=''
  if n in [8,7] and tier=='delkasko' or n==54:cls='SOURCE_CONFLICT_REVIEW_REQUIRED';pri=''
  if n==23:cls='CATALOG_FACT_SEMANTICALLY_MISMAPPED'
  row=A.fact(pid,q['subject'],q['dimension'],q['value'],D if q['source']=='ipid' else T,q['location'],cls,K[n],pri,why.get(n,'Exactmaterialsourceelementcheckedagainstallresolvedbase/optionalcomponents;noequivalent found.'),'SCRC-041',component=comp,inventory_id=q['id'],extra={'source_first_inventory':'if-boat-independent-inventory.json'})
  rows.append(row)
 rev={}
 for cf in p['facts']+sum(p['addonFacts'].values(),[]):
  evidence=[f for f in rows if cf['key'] in f['proposed_keys']]
  if evidence:rev[cf['key']]={'locations':[{'artifact':f['source_artifact'],'location':f['source_location']} for f in evidence],'note':'Corepositiveclaimsverified;omittedqualificationsseparate.'}
 A.reverse(pid,rev)
 for claim in A.support:
  if claim['product_identity']==p['identity'] and claim['key']=='bat.maskinskade.egenandel':claim.update(support_status='CATALOG_FACT_SEMANTICALLY_MISMAPPED',full_claim_validated=False,manual_reverse_evidence={'artifact':T,'location':'6 §4.9.5','note':'Catalogminimum8kinvalidfor4kbranchthrough5years;percentageonly11–15.'})
 A.product_review(pid,[T,D],True,'55-rulesource-firstinventorycheckedagainstverythinexactcatalog;baseandoptionalMotor/girreversechecked.Motor4kbranchmateriallycontradictsminimum8ksummary.Superpurchasepriceguaranteeisnotunconditionalnewboat;basic1year60%ruleindependent.Jolle/storageDelkaskoIPIDconflictrecorded. Generallegal§22exactversionresearchgap,noamountguessed.')
for ad in A.a['addon_coverage']:
 if ad['addon_id']=='if-bat-motor-gir':ad.update(status='COMPLETE_WITH_RECORDED_GAPS',fully_audited=True,notes='Kasko/Superavailability,optionalstate,15yearengineage,fullcomponentlist,deductibletableandconditionsread§4.9;4kbranchmismatchrecorded. NotautomaticallyincludedSuper.')
A.a['source_conflicts'].append(dict(id='SC-044',provider='if',family='Båt',product=['if-bat-delkasko'],sources=[T,D],claim='Jolle/opplagsutstyr applicability Delkasko vs Kasko',observed='Full§3.1unqualifiedobjects;IPID1addsunderKasko. ExactDelkaskoapplicabilitycannotbesafelyflattened.',status='SOURCE_CONFLICT_REVIEW_REQUIRED',action='Getapplicableconfirmation/levelmatrix;preserveconflictwithoutfalseunavailable.'))
A.a.setdefault('source_research_queue',[]).append(dict(queue_id='SR-if-boat-general',product=['if-bat-delkasko','if-bat-kasko','if-bat-super'],reason='BÅT2-1incorporatesgenerals§22;localGEN2-9June2025haslegal§23,notidentifiedastheapplicable2023edition.',external_source_needed_if_unresolved='Exactapplicablegeneraltermsidentityandlegalcostsum,plusIPIDjolle/storagelevelclarification',downloaded=False))
A.checkpoint('If Båt three levels and Motor/gir addon complete; verified deductible mismatch and material thin-catalog gaps','Hund','if','if-hund-basis')
