from continue_audit import *
A=Audit();I=load('tryg-boat-independent-inventory.json');B='catalog/sources/boat-pet/'
A.root('SCRC-046','Tryg Båt modellerer rike Ekstra-/Maskin-/ulykkesvilkår hovedsakelig som inkludert/valgfritt og taper summer, vilkår og perioder; motoralder er komprimert feil. Grunnvilkårspakken er ufullstendig lokalt.','33uavhengigesource-firstreglerfra9originaler;faktiskPFB36900/36910/38900motkomponenter;egenprodukttermsikkegrunnKaskovilkår.',['Båt'],['tryg'],'RB-42')
K={1:['bat.geografi.dekning','bat.geografi.omrade'],2:[],3:[],4:[],5:['bat.ansvar.dekning','bat.rettshjelp.dekning'],6:['bat.brann.dekning'],7:['bat.tyveri.dekning','bat.transport.dekning'],8:['bat.losore.grense'],9:['bat.kasko.dekning','bat.haerverk.dekning','bat.transport.dekning'],10:['bat.kasko.begrensning'],11:['bat.drev.aldersfradrag'],12:['bat.redning.dekning','bat.redning.egenandel'],13:['bat.kasko.egenandel'],14:['bat.losore.grense','bat.losore.gjenstand'],15:['bat.dieseldyr.dekning','bat.dieseldyr.grense','bat.dieseldyr.egenandel'],16:['bat.opplagsutstyr.dekning','bat.opplagsutstyr.grense','bat.opplagsutstyr.egenandel'],17:['bat.jolle.dekning','bat.jolle.grense'],18:['bat.transport.dekning','bat.ferieavbrudd.dekning'],19:['bat.ferieavbrudd.dekning','bat.ferieavbrudd.dager','bat.ferieavbrudd.grense'],20:['bat.ferieavbrudd.grense'],21:['bat.plattform.grense'],22:['bat.nyverdi.dekning','bat.nyverdi.alder','bat.nyverdi.skadegrad'],23:['bat.maskinskade.dekning','bat.maskinskade.alder'],24:['bat.maskinskade.dekning'],25:['bat.maskinskade.egenandel'],26:['bat.maskinskade.begrensning'],27:['bat.ulykke.dekning'],28:['bat.ulykke.grense'],29:['bat.ulykke.begrensning'],30:[],31:['bat.kasko.egenandel'],32:['bat.rettshjelp.dekning','bat.rettshjelp.grense','bat.rettshjelp.egenandel'],33:[]}
why={1:'200nmogRusslandkorrektmenoverfarternevnesbaregenerelt/Nordenutelatt.',2:'Rolle/panthaveravtaleutelatt.',3:'14dny eierregelutelatt.',4:'Sesongpremieogoppgjørvedoppsigelsemangler.',6:'Inkludertutenbrann/kortslutning/opplagutløserogunntak.',7:'TyveriinkludertmenBTtransport/vrakfjerningutelatt.',8:'Løsørestore/materielleunntakikkegrunnmodellert;ingenantattsum.',9:'Inkludertmistervesentligetyperfareinklfeilfylling/transportvilkår.',10:'IPIDpositivekildertilkaskounntakikkeiinkludert.',11:'5årdrevnytt/25%eldrealdersfradragmangler.',12:'Assistanseinkludert,500egenandel/nærmestehavnmangler.',13:'Ekstra2kegenandelreduksjonmangler.',14:'100ksamlet30k/itemkundeutvidelse/ikkeutleiemangler.',15:'Dieseldyr50k/2.5kegenandelmangler.',16:'Opplagsutstyrbareinkludertuten30k/2.5k.',17:'Jollebareinkludertuten14fot/25hk/50k/2.5k.',18:'Transport/hjemreisepersonsykdom/3d-regelenmangler.',19:'Inkludertutelater2.5k/dag21d/feriemerenn6d/påbegyntdekketskade.',20:'Samlet20%båtsum100ktakmangler.',21:'Vannscooterplattform30k/2.5kmangler.',22:'Dokumentert3år60%nyverdiheltutelattfraEkstra.',23:'Under15/12årerikkesammesomutperiodenmotores15/12;seilbåts12årfraeldreIPIDvsnyttermmotortypeskilletavklares.',24:'Barevalgfrittutelaterdrivstoff/styring/kabling/varmgangogdiagnostikk.',25:'4ktom5årmotorderetter25%min4kmangler.',26:'E10/slitedel/næring/garantifallbackutelatt.',27:'Valgfrittmenrollekvalifikasjon/80årIPID/unsupportedsykehuswebmåbevares.',28:'200k100k20kunntak1.5millaggregatog1årsgrensemangler.',29:'Ulykkensvesentligeunntakogoppgjørsgrensermangler.',31:'Beviskundevalgikkeproduktfiksertsum.',32:'Rettshjelpbareinkludertuten100k250k20k/4k20%.',33:'HovedAnsvarBTKaskodekningsvilkårmanglerlokalt;bareproduktterms/IPID/webstøtte.'}
for pid in ['tryg-bat-ansvar','tryg-bat-brann-ansvar','tryg-bat-brann-tyveri-ansvar','tryg-bat-kasko-ansvar','tryg-bat-bat-ekstra']:
 p=A.p[pid];physical=pid!='tryg-bat-ansvar';theft=pid not in ['tryg-bat-ansvar','tryg-bat-brann-ansvar'];kasko=pid in ['tryg-bat-kasko-ansvar','tryg-bat-bat-ekstra'];extra=pid.endswith('ekstra');rows=[]
 paths={x:B+'tryg-boat-'+y for x,y in {'inboard':'inboard-terms.pdf','outboard':'outboard-terms.pdf','sail':'sail-terms.pdf','row':'row-terms.pdf','extra':'extra-terms.pdf','motor':'machinery-terms.pdf','accident':'accident-terms.pdf','ipid':'ipid.pdf','web':'product.html'}.items()};paths['legal']='catalog/sources/tryg/hus/05PGE91500.pdf';used={paths[k]for k in ['inboard','outboard','sail','row','ipid','web','legal','accident']}
 for n,q in enumerate(I['rules'],1):
  if q['scope']=='physical'and not physical or q['scope']in ['kasko','motor']and not kasko or q['scope']=='extra'and not extra or n==7and not theft:continue
  path=paths[q['source']];used.add(path);comp='tryg-bat-maskinskade'if q['scope']=='motor'else'tryg-bat-ulykke'if q['scope']=='accident'else''
  cls=COARSE if any(f['key']in K[n]for f in p['facts']+sum(p['addonFacts'].values(),[]))else MISSING;pri='P1'
  if n in [2,3,4,8,9,10,29]:pri='P2'
  if n==5:cls=PRESENT;pri=''
  if n==23:cls='CATALOG_FACT_SEMANTICALLY_MISMAPPED'
  if n==27:cls=COARSE # scope80IPID/websykehusnotforcedintoproduct
  if n==30:cls='SOURCE_ONLY_ACCEPTABLE';pri=''
  if n==31:cls=CUSTOM;pri=''
  if n==33:cls='SOURCE_PACKAGE_GAP';pri='P1'
  rows.append(A.fact(pid,q['subject'],q['dimension'],q['value'],path,q['location'],cls,K[n],pri,why.get(n,'Korrektpositiveinkludering,grunnsumikkerettmessigoppfunnet.'),'SCRC-046',component=comp,inventory_id=q['id'],extra={'source_first_inventory':'tryg-boat-independent-inventory.json'}))
 rev={}
 for cf in p['facts']+sum(p['addonFacts'].values(),[]):
  ee=[f for f in rows if cf['key']in f['proposed_keys']]
  if ee:rev[cf['key']]={'locations':[{'artifact':f['source_artifact'],'location':f['source_location']}for f in ee],'note':'Currentactualpositiveclaimsupportedbyexactproduct/add-on/IPID/web;incompleteunderlyingfulltermsnotinvented.'}
 A.reverse(pid,rev)
 for s in A.support:
  if s['product_identity']==p['identity']and s['key']=='bat.maskinskade.alder':
   ff=[f for f in rows if f['source_first_inventory_id']=='TR-BOAT-023'];s.update(support_status='CATALOG_FACT_SEMANTICALLY_MISMAPPED',full_claim_validated=False,manual_reverse_evidence={'artifact':paths['motor'],'location':'1 §1','note':'Under15/12vsutperioden15/12;seilbåtoldIPIDtypedconflictdistinct'},source_fact_ids=[f['source_fact_id']for f in ff],finding_ids=[f['finding_id']for f in ff]);A.a['unsupported_catalog_claims']['proven'].append(dict(s))
 A.product_review(pid,sorted(used),True,'All9localboatartifactsreviewed33rules+typedlegal. Deepreviewclosedwithinlocalavailability,notfulltermscompleteness:missingordinaryAnsvar/BT/KaskodetailedtermsflaggedSOURCE_PACKAGE_GAP. Allclaimsreviewed;Motorunderagecontradictionfound;nohull/liabilitysumsinvented. CanonicalBrannstandaloneexactavailabilityneedsfullcoveragepackage.')
for ad in A.a['addon_coverage']:
 if ad['addon_id']in['tryg-bat-maskinskade','tryg-bat-ulykke']:ad.update(status='COMPLETE_WITH_RECORDED_GAPS',fully_audited=True,notes='ExactPFB36910/38900wholetextchecked;sum/age/conditionalgapsandIPIDvariantconflictdocumented.')
A.a['source_conflicts'].append(dict(id='SC-050',provider='tryg',family='Båt',product='tryg-bat-maskinskade',sources=[B+'tryg-boat-ipid.pdf',B+'tryg-boat-machinery-terms.pdf'],claim='Seilbåt/motoralder',observed='IPIDJul2024utenbord/seilbåt12år;PFB36910Jan2026kunmotortype12påheng15innenbordutperioden;ikkevidereseilbåtgrenutentypedkilde.',status='SOURCE_CONFLICT_REVIEW_REQUIRED',action='Avklarexactmotorvariant/versjon;bevarnyperiodiskgrenseogeldreIPIDseparat.'))
A.a['source_research_queue'].append(dict(queue_id='SR-tryg-boat-mainterms',product=[p['productId']for p in A.p.values()if p['providerId']=='tryg'and p['insuranceType']=='Båt'],reason='LocalPFB33/34/35/37000producttermsdoNOTcontainordinaryAnsvar/BrannTyveri/Kaskoallclauses. FullcorepositiveclaimscoveredonlywhereIPID/webexplicit. NeedexactBrannstandaloneniveau/ansvarsum/basepropertylimits/allmajorqualifiers;IPID80år/websykehusvsaccidentfullnohospitalrule.',external_source_needed_if_unresolved='Exactordinaryboatliability/fire/theft/Kaskocoveragefullterms+safetyanddatedaccidentwebclarification;noassumeddata.',downloaded=False))
VV=load('verified-false-unknowns.json');A.a['catalog_counts']['verified_visible_false_unknown_cases']=len(VV);A.a['blindspot_validation']['visible_false_unknowns']=VV
A.checkpoint('Tryg boat five levels and two addons reviewed; rich extension omissions, wrong motor termination wording and missing core package flagged','Hund','tryg','tryg-hund-behandling')
