from continue_audit import *
A=Audit();I=load('tryg-reise-independent-inventory.json');B='catalog/sources/tryg/reise/canonical/'
A.root('SCRC-050','Tryg Reise har gode summer og mange vilkårsdimensjoner, men Tryg Legehjelp mangler på Ekstra, valgfrie/general egenandeler og ulykkesbegrensninger er ufullstendige. Lokale web/IPID-konflikter må avklares uten å erstatte bevisvalg.','52 source-first regler; alle13originaler/3nivåer/2ulykketillegg; sidebyttet runtime bekrefter Ekstra Legehjelp som falsk katalog-unknown.',['Reise'],['tryg'],'RB-46')
K={1:['reise.personer.omfang'],2:['reise.varighet.maks'],3:['reise.varighet.maks'],4:['reise.overnatting','reise.tjenestereise'],5:['reise.omrade.verden','reise.omrade.ud'],6:['reise.varighet.beregning','reise.varighet.automatisk_forlengelse'],7:['reise.avbestilling.dekning'],8:['reise.avbestilling.dekning'],9:['reise.avbestilling.sum'],10:['reise.avbestilling.dekning','reise.avbestilling.ud'],11:['reise.forsinkelse.rute'],12:['reise.forsinkelse.avgang_sum','reise.forsinkelse.fremmote_sum'],13:['reise.forsinkelse.hotell_arrangement','reise.forsinkelse.leiebilavtale','reise.forsinkelse.hotell_arrangement_sum','reise.forsinkelse.leiebilavtale_sum'],14:['reise.forsinkelse.rute'],15:['reise.bagasje.forsinket'],16:['reise.bagasje.forsinket_sum'],17:['reise.bagasje.dekning'],18:['reise.bagasje.total','reise.bagasje.per_gjenstand'],19:['reise.bagasje.nokler','reise.bagasje.kontanter','reise.bagasje.pass_billetter'],20:['reise.bagasje.uhell_begrensning'],21:['reise.bagasje.uhell','reise.bagasje.uhell_sum','reise.bagasje.uhell_egenandel'],22:['reise.bagasje.dekning'],23:['reise.bagasje.mobil_egenandel.gjentatt'],24:['reise.medisinsk.behandling','reise.medisinsk.graviditet'],25:['reise.medisinsk.behandling','reise.medisinsk.forlenget'],26:['reise.sykeledsagelse','reise.medisinsk.sum','reise.medisinsk.ledsager_sum'],27:[],28:['reise.medisinsk.eneste_medreisende_sum'],29:['reise.hjemtransport','reise.hjemtransport.sum'],30:['reise.reiseavbrudd','reise.reiseavbrudd.sum'],31:['reise.medisinsk.kjent','reise.medisinsk.tann'],32:['reise.evakuering','reise.evakuering.sum'],33:['reise.leiebil.egenandel','reise.leiebil.egenandel_sum'],34:['reise.idtyveri.dekning','reise.idtyveri.juridisk'],35:['reise.ansvar.sum','reise.ansvar.dekning'],36:['reise.rettshjelp.dekning'],37:['reise.rettshjelp.sum','reise.rettshjelp.egenandel'],38:[],39:['reise.tjeneste.legehjelp','reise.tjeneste.alarm'],40:['reise.tjeneste.lounge'],41:['reise.ulykke.dekning'],42:['reise.ulykke.invaliditet'],43:['reise.ulykke.dodsfall'],44:['reise.ulykke.behandling'],45:['reise.ulykke.invaliditet','reise.ulykke.dodsfall'],46:['reise.ulykke.dekning'],47:['reise.ulykke.dekning'],48:['reise.aktivitet.unntak','reise.aktivitet.dykking'],49:['reise.sikkerhet.reisegods'],50:['reise.sikkerhet.sykdom','reise.medisinsk.kjent'],51:[],52:[]}
coarse={3:('P1','Avtalt utvidelse er nevnt, men lokal kilde dokumenterer et konkret valgfritt enkeltreisevalg inntil12mnd som ikke representeres.'),7:('P1','Kravet om forsikring før første innbetaling og avbestillingsperioden fremgår ikke.'),8:('P2','Angitte behandlingstilfeller mister kravet om at operasjon var tidfestet og senere flyttet.'),10:('P1','Sentrale avbestillingsbegrensninger karantene/frykt, refusjon og sesongleie mangler; tjeneste/UD allerede representert.'),11:('P2','Kravet om manglende alternativ innen24timer for ny billett utelatt.'),14:('P2','Personalmangel/streik og EU-refusjon med 24h-unntak utelatt.'),17:('P1','Dyr er positivt, men egne/disponerte dyr er unntatt; hærverk unntar familie/lånebruker; 21d tapsregel mangler.'),22:('P2','Oppgjørsmetode og minimum1/3 verdifall/markedsverdi er ikke representert.'),25:('P2','60d sykehus korrekt; yttergrense til medisinsk forsvarlig hjemtransport mangler.'),28:('P2','Sum korrekt; barnunder21 medforeldre regnes ikke som eneste medreisende.'),29:('P2','Sum/forhåndsgodkjenning korrekt; barns hjemreise/beggeforeldre og ikke mellom to hjem mangler.'),30:('P2','Dagssum/kostnadsforhold korrekt; ettfamiliemedlemregel og planlagt reise over varighetsgrensen mangler.'),31:('P1','Kjent sykdom/tann korrekt; lete/redningsaksjon og høydesyke unntak mangler.'),34:('P2','25k og tap/ID-papir korrekt; rettssak/næring/familieforhold mangler.'),37:('P2','100k/250k/ingenreiseegenandel korrekt;20k tvistmotTryg og økonomiskinteressetak mangler.'),44:('P2','5%/3år korrekt; særregel for første permanente tannbehandling under18 mangler.'),45:('P1','1% korrekt; tidligere invaliditet fratrekk og dødsfallinnen1år/ingeninvaliditetda mangler.'),46:('P1','Materielle skadeutløser/unntak for ulykkeskomponent mangler.'),47:('P1','Yrkesutøvelsebegrensningen med landkontorunntak mangler.'),49:('P2','24–06 korrekt; verdisaker må bæres/safe og innsjekkingsforbud for elektronikk er ikke fullstendig.')}
for pid in ['tryg-reise','tryg-reise-ekstra','tryg-reise-premium']:
 p=A.p[pid];extra=pid.endswith('ekstra');premium=pid.endswith('premium');higher=extra or premium;fs=p['facts']+sum(p['addonFacts'].values(),[]);rows=[]
 for n,q in enumerate(I['rules'],1):
  if q['scope']=='higher'and not higher or q['scope']=='premium'and not premium:continue
  if n==39 and not higher:continue # No safe positive Legehjelp claim for entry level.
  if n in [6,23]and not premium:
   olds=[f for f in A.f if f['product']==pid and f['source_fact_id']in ['SF-0235','SF-0238','SF-0239','SF-0242']and ((n==6 and 'forleng' in f['semantic_dimension'].lower()+f['semantic_subject'].lower())or(n==23 and 'Mobil'in f['semantic_subject']))]
   if olds:
    for f in olds:f['continuation_inventory_links']=[q['id']]
    continue
  keys=K[n];doc=q['doc'];loc=q['location'];val=q['value'];cls=PRESENT;pri='';reason='Eksakt kilde, nivå, tall og betydning kontrollert; eksisterende parent/child/tillegg representerer regelen.'
  if premium and doc=='PRF46001-Reise-Reise-Ekstra.pdf':doc='PRF46003-Reise-Premium.pdf'
  if premium and doc=='PRF46010-Ulykke-Ulykke-Ekstra.pdf':doc='PRF46012-Ulykke-Premium.pdf'
  comp=('tryg-reise-ulykke-ekstra'if extra else'tryg-reise-ulykke')if q['scope']=='accident'and not premium else''
  if n in coarse:cls=COARSE;pri,reason=coarse[n]
  if n==1:cls=COARSE;pri='P1';val='Kun fast bosatt i Norge og medlem i norsk folketrygd.';reason='Den sikre eligibility-regelen mangler selv om familie/barnalder med rette holdes bevisstyrt ved kildekonflikt.'
  if n==2:
   val='Reise45d standard; bevisstyrt utvidelse.'if not higher else'Premium70d standard; bevisstyrt utvidelse.'if premium else val
   if extra:cls='SOURCE_CONFLICT_REVIEW_REQUIRED';pri='P1';reason='Samme offisielle web gir45og70 forEkstra; katalog45må ikke behandles konfliktfritt.'
  if n==4:val='Fritid med overnatting.'if not higher else'Fritids- og tjenestereiser med og uten overnatting.'
  if n==9:val='20 000pertilfelle/sikret.'if not higher else'Ingen øvre forsikringssum, med kostnadsbegrensninger.'
  if n==12:val='Avgang1500; fremmøte20 000herunderovernatting1500.'if not higher else'Avgang3000; fremmøteingenøvregrense,overnatting3000.'
  if n==15:cls='SOURCE_ONLY_ACCEPTABLE';reason='Triggeren korrekt representert; PIR/kvittering/dokumentadministrasjon trenger ikke egen sammenligningsrad.'
  if n==16:val=('5000'if higher else'2000')+'perperson,transitt500innenfor.'
  if n==18:val='Ingenoverordnetsum/40 000pergjenstandmedtilbehør.'if higher else'20 000total/6 000pergjenstandmedtilbehør.'
  if n==19:val='Nøkler4000;kontanter'+('6000/pass20 000'if higher else'3000/pass5000')+'forallesikrede.'
  if n==20:cls=REVIEW;reason='Unntakslistens plassering under Uhell gir ikke alene sikkert bevis for bredere Reisegods-scope. Ikke flagg base negativ eller feilskoping uten tydeligere avklaring.'
  if n==27:cls=MISSING;pri='P1';reason='Den separate ytelsen ved familie bosatt på reisemålet,14d, er ikke representert av sykeledsagelse.'
  if n==35:val=('4mill'if not higher else'15mill')+'perhendelseallesikrede utenforNorden; Augustsumtabell aktiv. Fellesansvarvilkår01.10 først fremtidig ved frosset snapshot.'
  if n==36:val='UtenforNorden første'+('70'if premium else'45')+'dagerferie; ikke automatisk forlenget av generell reiselengde.'
  if n==38:cls=MISSING;pri='P1';val='0eller1000valgbart; særskilte egenandeler bevares.'if higher else'1000standard; særskilte egenandeler bevares.';reason='Generell egenandel/valgstruktur finnes i lokal FAQ, men ingen base/addon fact; avtalt kundeverdi må forbli kundevalg.'
  if n==39 and extra:cls=MISSING;pri='P1';keys=['reise.tjeneste.legehjelp'];reason='IPID uttrykkelig inkluderer tjenesten i Ekstra; all resolved base/optional mangler og sideswapruntime viser unknown.'
  if n==40:cls='SOURCE_CONFLICT_REVIEW_REQUIRED';pri='P2';reason='Samme produktside oppgir både fire og fem medreisende. Katalogens fem støttes ett sted men ikke konfliktfritt.'
  if n==41:val='Premiumulykke inkludert.'if premium else'Ulykke Ekstra valgfri separat komponent.'if extra else'Ulykke valgfri separat komponent.'
  if n==42:val=('750 000'if premium else'500 000'if extra else'300 000')+'til69;100 000fra70utpolicyåret80; varig medisinsk invaliditet.'
  if n==43:val=('100 000/750 000'if premium else'100 000/500 000'if extra else'50 000/150 000')+'til20/21–69;100 000fra70utpolicyåret80.'
  if n==51:cls=MISSING;pri='P2';reason='Generelt streik/lockout/konkursunntak er ikke representert; reiseavbestillingsspesifikke unntak vurdert separat.'
  if n==52:cls=MISSING;pri='P2';reason='Kildebetinget3,50/km utgiftsregel ikke representert; ikke universell bildekning.'
  rows.append(A.fact(pid,q['subject'],q['dimension'],val,B+doc,loc,cls,keys,pri,reason,'SCRC-050',component=comp,inventory_id=q['id'],extra={'source_first_inventory':'tryg-reise-independent-inventory.json'}))
 A.reverse(pid,{cf['key']:{'locations':[{'artifact':B+cf['source']['filename'],'location':str(cf['source'].get('page'))+' '+str(cf['source'].get('section'))}],'note':'Exact numerical/main positive claim checked; omitted qualifiers separated; future liability wording not activated.'}for cf in fs})
 for claim in A.support:
  if claim['product_identity']==p['identity']and((extra and claim['key']=='reise.varighet.maks')or(premium and claim['key']=='reise.tjeneste.lounge')):claim.update(full_claim_validated=False,support_status='SOURCE_CONFLICT_REVIEW_REQUIRED',support_scope='Conflicting statements within official local page; no value selected by audit.')
 A.product_review(pid,[x for x in A.art if x.startswith(B)],True,'52 independent source rules, all13local originals reused by hash. Three levels and two optional components numerically and semantically checked. Rechtshelp0deduct explicit travel exception positive; source conflicts duration/family/lounge preserved. One Ekstra service omission runtime-proven. Customer choices remain customer facts; future liability terms not activated.')
for ad in A.a['addon_coverage']:
 if ad['addon_id']in['tryg-reise-ulykke','tryg-reise-ulykke-ekstra']:ad.update(status='COMPLETE_WITH_RECORDED_GAPS',fully_audited=True,notes='Availability/optional status and level-specific sums correct; material accident/occupation/death timing restrictions missing.')
for num,prod,claim,obs,docs in [(53,'tryg-reise-ekstra','Reisevarighet','Samme HTML45hovedtabell/FAQ,70backpacking/borteboendebarnFAQ.',['Reiseforsikring-produktside.html']),(54,'tryg-reise-*','Familiens barn/barnebarn','IPIDtilfyller21;webutpolicyår21/under21; barnebarnbosattellerreiserammen. Bevisstyrt måbevares.',['IPID-Reiseforsikring.pdf','Reiseforsikring-produktside.html']),(55,'tryg-reise-premium','Loungefølge','SammeHTMLinntil5medreisendeioversiktog4inyttiginformasjon.',['Reiseforsikring-produktside.html'])]:A.a['source_conflicts'].append(dict(id=f'SC-{num:03d}',provider='tryg',family='Reise',product=prod,sources=[B+d for d in docs],claim=claim,observed=obs,status='SOURCE_CONFLICT_REVIEW_REQUIRED',action='Avklar lokale kildeversjon/produktregel før konfliktverdi canonicaliseres; ikke gjett.'))
A.a['source_research_queue'].append(dict(queue_id='SR-tryg-reise-web-conflicts',product=['tryg-reise-ekstra','tryg-reise-premium'],reason='Ekstra45/70d, familiealder/scope og lounge4/5 krever eksplisitt dokumentavklaring. Gjeldende ansvarfull før01.10 mangler lokalt; sumtabell støtter summer.',external_source_needed_if_unresolved='Konsistent produkt/IPID/fullterms for disse reglene; ingen web hentet nå.',downloaded=False))
v=load('verified-false-unknowns.json');probe=load('runtime-tryg-reise-probe.json')[0];ff=[f for f in rows if False];ff=[f for f in A.f if f['product']=='tryg-reise-ekstra'and f.get('source_first_inventory_id')=='TRE-39'];assert probe['forward'][0]['first']['state']=='unknown'and probe['reverse'][0]['second']['state']=='unknown'
v.append(dict(product_identity=A.p['tryg-reise-ekstra']['identity'],key='reise.tjeneste.legehjelp',peer_identity=probe['right'],display_state='unknown',display_text='Ikke dokumentert i kataloggrunnlaget',source_fact_ids=[f['source_fact_id']for f in ff],finding_ids=[f['finding_id']for f in ff],side_swap_consistent=True,cause='IPIDJan2026 explicit Ekstra Tryg Legehjelp absent from resolvedbase+optional; Premium-only catalogfact.',source_scope_note='Exact IPID names Ekstra; not inferred from Premium.',probe='runtime-tryg-reise-probe.json'))
save('verified-false-unknowns.json',v);A.a['catalog_counts']['verified_visible_false_unknown_cases']=len(v);A.a['blindspot_validation']['visible_false_unknowns']=v
A.checkpoint('Tryg Reise all three levels and two accident addons closed; Ekstra Legehjelp false unknown verified; three local conflicts retained','Bil','fremtind','fremtind-bil-ansvar')
