from continue_audit import *
A=Audit();I=load('gjensidige-bil-independent-inventory.json');base='catalog/sources/gjensidige/';ipid=base+'Bilforsikring-Produktark-MOT01.pdf'
A.root('SCRC-022','Gjensidige Bil preserves exact main sums, detailed machine components and public-template qualifications, but omits material sublimits, family conditions, settlement, mobility branches and legal/bonus dimensions. Shared generic terms must remain scoped to named product levels.','73-rule independent inventory, all five local files fully read using exact normalized page identity reuse; resolved base/inheritance and four available addon definitions compared.',['Bil'],['gjensidige'],'RB-20')
K={1:['ansvar.dekning','rettshjelp.dekning','ulykke.omfang'],2:['ansvar.person.grense','ansvar.ting.grense'],3:['rettshjelp.grense'],4:['ulykke.dod','ulykke.invaliditet'],5:['geografi.dekning','geografi.rettshjelp'],6:[],7:[],8:[],9:[],10:[],11:[],12:[],13:[],14:[],15:[],16:['brann.dekning'],17:['tyveri.dekning'],18:['glass.dekning','glass.unntak'],19:['glass.egenandel.bytte','glass.egenandel.reparasjon'],20:['brann.egenandel','tyveri.egenandel'],21:['tilbehor.grense'],22:['losore.grense'],23:['veihjelp.egenandel'],24:['veihjelp.dekning'],25:['veihjelp.dekning'],26:['veihjelp.dekning'],27:[],28:[],29:['kasko.dekning','feilfylling.dekning'],30:['bilnokkel.dekning'],31:['bilnokkel.grense','bilnokkel.egenandel'],32:['ladekabel.dekning','ladekabel.egenandel'],33:['leiebil.dager','leiebil.bilklasse'],34:['leiebil.kondemnasjon'],35:['leiebil.unntak'],36:['leiebil.utland'],37:['leiebil.kontant'],38:['reparasjon.garanti'],39:['nyverdi.alder','nyverdi.km'],40:['nyverdi.skadegrad'],41:['nyverdi.unntak'],42:[],43:[],44:[],45:[],46:['maskinskade.alder','maskinskade.km'],47:['maskinskade.dekning','maskinskade.fossil','maskinskade.el','maskinskade.drivverk'],48:['maskinskade.unntak'],49:[],50:['maskinskade.egenandel.0-119999','maskinskade.egenandel.120000-159999','maskinskade.egenandel.160000-200000'],51:['parkering.dekning','parkering.alder','parkering.grense','kasko.egenandel','bonus.parkert'],52:['leiebil.teknisk'],53:['leasing.startleie'],54:['punktering.dekning','punktering.grense','punktering.egenandel'],55:['punktering.vilkar'],56:['leiebil.unntak'],57:['tilbehor.utvidelse','spesiallakk.dekning','funksjonsutstyr.dekning'],58:['ulykke.omfang'],59:['ulykke.dod'],60:['ulykke.invaliditet'],61:['ulykke.omfang'],62:['rettshjelp.dekning','geografi.rettshjelp'],63:['rettshjelp.dekning'],64:[],65:['rettshjelp.dekning'],66:['rettshjelp.grense'],67:['rettshjelp.egenandel'],68:[],69:['bonus.parkert'],70:[],71:['geografi.dekning'],72:[],73:[]}
present={1,5,16,17,18,20,21,22,23,29,31,32,39,41,46,47,50,51,53,67}
why={2:'Begge ansvarssummer korrekt; null ordinær egenandel er ikke representert.',3:'100 000 korrekt; økonomisk interesse-tak mangler.',4:'Begge grunnsummer korrekt; ingen ulykkesegenandel mangler.',19:'0/3000 egenandeler korrekt; reparasjonens1000kr forsikringssum er en separat manglende dimensjon, ikke egenandel.',24:'Generell berging/hjemtransport mister personhendelser, utelåsing, nærmesteverksted og påkoblet henger.',25:'To virkedager, hotellalternativ og persontransportvilkår mangler.',26:'Markedsverditak og vesentlige utgiftsunntak mangler.',30:'Én nøkkelskade per forsikringsår mangler.',33:'Maksimal bilklasse/tid representert; begrensningen til forsikret bils egen størrelse mangler. Pluss tid har i tillegg registrert IPIDkonflikt.',34:'30 dager ved totalskade/tyveri og oppgjørsstopp mangler som egen mobilitetsgren.',35:'Bare glass/punktering bevart; kontantoppgjør, sluttfrist, leverandør og utgiftsunntak mangler.',38:'8år/avtaleverksted korrekt; rustgaranti, tjenester og videreføring etter selskapsbytte mangler.',40:'Skadeterskel riktig; ny tilsvarende bil/kontantform og objektgrense3,5t ikke fullt representert.',48:'Clutch/eksos/filter nevnt; oljeforbruk-med-bruddunntak og clutchhydraulikk ikke representert.',52:'15d og verkstedvalg korrekt; valg av reparasjonstidspunkt mangler, sekundær detalj.',54:'Valgfri status/2500/1000 korrekt; uten bonustap mangler i add-on fakta.',55:'År/godkjentverksted/mønsterdybde korrekt; reparasjon-før-nytt og nødvendig antall dekk mangler.',56:'Leiebil ved barepunktering korrekt unntatt; følgeskade ordinær kasko er separat manglende sammenheng.',58:'Objekt-/personkrets riktig; ekstra fall/vridning/bruddmekanismer mangler.',59:'100000 og1år korrekt;50000 uten forsørgerkrets og avkortningsvilkår mangler.',60:'200000 riktig; proporsjonalitet, forfunksjon,3årsfastsettelse og1million hendelsestak mangler.',66:'Bare grunnsum; trinnvis flerpartsgrenser og økonomisk interesse-tak mangler.'}
for level,filename in [('ansvar','bil-ansvar-alminnelige-vilkar.pdf'),('delkasko','Bil-Delkasko-alminnelige-vilkar.pdf'),('kasko','Bil-Kasko-alminnelige-vilkar.pdf'),('pluss','Bil-Pluss-alminnelige-vilkar.pdf')]:
 pid='gj-bil-'+level;p=A.p[pid];lvl=['ansvar','delkasko','kasko','pluss'].index(level);path=base+filename;allfacts=p['facts']+sum(p['addonFacts'].values(),[]);actual={f['key'] for f in allfacts}
 for q in I['rules']:
  n=int(q['id'].split('-')[-1]);scope=q['scope'];src=path;loc=q['location'];comp=''
  if scope=='physical' and lvl<1:continue
  if scope=='lowerphysical' and lvl not in [1,2]:continue
  if scope=='kasko' and lvl<2:continue
  if scope=='pluss' and lvl<3:continue
  if scope=='optional' and n!=57 and lvl<2:continue
  if n in [1,57]:src=ipid;loc='1'
  elif lvl==0 and n>=58:loc={'5':'4','6':'5','7':'6','7–8':'6–7','7/9':'6/8','9':'8','10':'9','11':'10','11–12':'10–11','12':'11','11–14':'10–13'}.get(loc,loc)
  keys=K[n];cls=COARSE if any(k in actual for k in keys) else MISSING;pri='P1';reason=why.get(n,'Material source rule not fully represented by exact resolved base, inherited children or optional component.');val=q['value']
  if n in present:cls=PRESENT;pri='';reason='Exact value/meaning retained across cited base/inherited child facts; no missing claim for this dimension.'
  if n in [2,4,6,7,10,11,12,13,14,15,37,42,43,44,52,68,70,71,72]:pri='P2'
  if n==73:cls=ADMIN;pri='';reason='Administrative terms are not modeled as ordinary comparison facts.'
  if n==57:cls=REVIEW;pri='';reason='Optional availability and unknown sums correctly preserved; IPID does not prove exact eligibility for all4levels, especially Ansvar. No invented sums or not-covered assertion.'
  if n in [54,55,56]:comp='gj-punktering'
  if n==21:val='Fastmontert ekstrautstyr '+('10 000' if lvl==1 else '50 000')+' kr i offentlig eksempel; individuelt bevis gjelder foran.'
  if n==22:val='Løsøre '+('5 000' if lvl==1 else '10 000')+' kr i offentlig eksempel; individuelt bevis gjelder foran.'
  if n==28 and lvl==1:val='Delkasko unntar skade på batteri alene; ingen overføring av egen Kasko-varmgangsregel.'
  if n==31:val='Nøkkel '+('7 500' if lvl==2 else '15 000')+' kr; egenandel1 500 kr i offentlig eksempel.'
  if n==33:val='Leiebil maks egen bils størrelse, maksimalt mellomklasse stasjonsvogn; '+('30' if lvl==2 else '60')+' dager i normal reparasjonstid mens bil på verksted.'
  A.fact(pid,q['subject'],q['dimension'],val,src,'PDF '+loc,cls,keys,pri,reason,'SCRC-022',comp,q['id'],extra={'source_first_inventory':'gjensidige-bil-independent-inventory.json','customer_mode_impact_class':'LIKELY_SHARED_WITH_CUSTOMER_MODE' if pri else 'UNKNOWN','public_template_not_customer_selected':True})
 if lvl==1:
  A.fact(pid,'Reparasjonsgaranti','Delkasko anvendelighet','Det eksakte Delkasko-fullvilkåret har8årsreparasjonsgaranti for skade dekket av Gjensidige hos avtaleverksted; ikke avgrenset til Kasko i dette avsnittet.',path,'PDF15 Erstatningsregler',MISSING,['reparasjon.garanti'],'P1','Garantien finnes bare i Kasko-komponent i katalogen; egen Delkasko-kilde dokumenterer den samme fordelen. IPID lister først Kasko, men sier ikke at Delkasko er unntatt.','SCRC-022',inventory_id='GJ-BIL-074-DELPOSITIVE')
 if lvl==2:
  A.fact(pid,'Leiebil','bare veihjelp','Kasko-fullvilkår unntar leiebil ved veihjelp alene; separat ferieutvidelse utenfor Norden beholdes.',path,'PDF4 Dekkes ikke',COARSE,['leiebil.unntak'],'P1','Kasko og Pluss har ulike veihjelp/teknisk-leiebilregler; Kasko-unntaket mangler.','SCRC-022',inventory_id='GJ-BIL-075-KASKO')
 if lvl==3:
  A.fact(pid,'Leiebil','kildekonflikt reparasjonstid','Fullvilkår sier inntil60dager; IPID sier hele reparasjonstiden.',ipid,'PDF1 Pluss','SOURCE_CONFLICT_REVIEW_REQUIRED',['leiebil.dager'],'','Konflikten er registrert; ingen vilkårlig erstatning av60medubegrenset.','SCRC-022',inventory_id='GJ-BIL-076-CONFLICT')
 # Main catalog numeric/status claims individually checked from the source-first inventory above.
 excluded={'tilbehor.utvidelse','spesiallakk.dekning','funksjonsutstyr.dekning'}
 reverse={f['key']:dict(artifact=base+f['source']['filename'],pdf_page=f['source'].get('page'),section=f['source'].get('section'),note='Exact catalog wording/value supported; full local package and inherited equivalence reviewed. Context omissions recorded separately. Optional availability on Ansvar unresolved.') for f in allfacts if f['key'] not in excluded}
 A.reverse(pid,reverse)
 for cs in A.support:
  if cs['product_identity']==p['identity'] and cs['key'] in excluded:cs.update(support_status='SOURCE_APPLICABILITY_REVIEW_REQUIRED',full_claim_validated=False,manual_reverse_evidence='IPID1 supports generic optional offering; no exact level availability or sums. Conditional wording is conservative but Ansvar eligibility unverified.')
 A.product_review(pid,[path,ipid],True,'Complete source-first73rule inventory applied by exact level, all applicable chapters read with exact page reuse, all numeric/status catalog claims reverse reviewed. Optional3equipmentlevel eligibility and Pluss rental source conflict explicitly recorded. No private bevis, date inference or current customer totalskade overwrite. Complete review with recorded gaps and source uncertainty.')
for aid in ['gj-punktering','gj-utvidet-utstyr','gj-spesiallakk','gj-funksjonsutstyr']:
 ad=next(x for x in A.a['addon_coverage'] if x['addon_id']==aid);done=aid=='gj-punktering';ad.update(status='COMPLETE' if done else 'PARTIAL',fully_audited=done,semantic_audit_status='COMPLETE' if done else 'PARTIAL',notes='Kasko/Pluss optional offering, limit/deductible/control and consequences reviewed; two missing material details recorded.' if done else 'Generic option and customer-specific sum/extent verified; exact four-level eligibility not proven by IPID, especially Ansvar. No guessed default or amount.')
if not any(x['id']=='SC-016' for x in A.a['source_conflicts']):A.a['source_conflicts'].append(dict(id='SC-016',provider='gjensidige',family='Bil',product='gj-bil-pluss',sources=[base+'Bil-Pluss-alminnelige-vilkar.pdf',ipid],claim='Pluss rental repair period:60days versus entire repair period',observed='FulltermsPDF3 inntil60dager; IPID1 hele reparasjonstiden. Version/effective dates unknown, no chronological precedence.',status='SOURCE_CONFLICT_REVIEW_REQUIRED',action='Official exact product/version clarification needed; retain both statements and do not infer unlimited.'))
A.checkpoint('Gjensidige Bil four exact products fully reviewed; detailed numeric positive controls, material mobility/legal gaps, additive source conflict recorded','Innbo','gjensidige','gjensidige-innbo-standard')
