from continue_audit import *
A=Audit();I=load('tryg-pet-independent-inventory.json');B='catalog/sources/boat-pet/'
A.root('SCRC-047','Tryg dyr har hovedsummer fra valgstruktur og noen Ekstra-beløp, men utelater diagnoser/utløsere, livsvilkår og tjenester. Tidligere tidlig-auditfunn videreføres uten duplisering.','40source-firstreglerfra10lokaleoriginaler;alleheadclaimsog4tilleggkontrollertmedtypegrenser;SF0001–0032gjenbrukt.',['Hund','Katt'],['tryg'],'RB-43')
K={1:['dyr.geografi.omrade'],2:['dyr.avtale.alder'],3:['dyr.karenstid.sykdom'],4:['dyr.veterinar.dekning','dyr.diagnostikk.dekning'],5:['dyr.medisin.dekning','dyr.spesialfor.grense'],6:['dyr.avlivning.dekning'],7:['dyr.tannskade.dekning'],8:['dyr.fodsel.dekning'],9:['dyr.fodsel.dekning'],10:['dyr.ledd.begrensning'],11:['dyr.ledd.begrensning'],12:['dyr.veterinar.begrensning'],13:['dyr.rehabilitering.dekning'],14:['dyr.veterinar.egenandel.fast'],15:['dyr.veterinar.sum.valgbar'],16:['dyr.veterinar.begrensning'],17:['dyr.ekstra.dekning'],18:['dyr.rehabilitering.dekning','dyr.rehabilitering.grense'],19:['dyr.tannsykdom.dekning','dyr.tannsykdom.grense'],20:['dyr.tannsykdom.begrensning'],21:['dyr.tannsykdom.grense'],22:['dyr.huggorm.egenandel'],23:['dyr.valpekull.dekning'],24:['dyr.liv.dekning'],25:['dyr.liv.begrensning'],26:['dyr.kremering.grense'],27:['dyr.kremering.grense'],28:['dyr.liv.begrensning'],29:['dyr.liv.forsvinning'],30:['dyr.liv.forsvinning'],31:['dyr.bruksverdi.dekning'],32:['dyr.bruksverdi.grense'],33:['dyr.liv.aldersfradrag'],34:['dyr.liv.aldersfradrag'],35:['dyr.liv.opphor'],36:['dyr.firstvet.dekning'],37:['dyr.direkteoppgjor.dekning'],38:['dyr.liv.aldersfradrag'],39:['dyr.avlivning.dekning'],40:[]}
why={1:'Europaallerederegistrert;rollevilkårutfylling.',2:'Levetidallerederegistrert;35dtegningogstraksopphørvedeierskifteikkevist.',3:'20d/flytteunntakallerederegistrert;utvidelsesumøkning/valpekullunntakutfylling.',4:'CT/MRallerederegistrert;sykdomtidspunktførstesymptomutelatt.',5:'Medisinpositivog50%fôrgapallerederegistrert.',6:'Behandlingdekkeranbefaltavlivning,utenkremasjon;ikkevist.',7:'Ulykkesfrakturtrekkingvsandretannikkevist.',8:'Fødsel18mnd/livifare/5rasegrupper+blandingerutelatt.',9:'Kattfødselingenhundalder/unntakskalimporteres.',10:'Typepresisdiagnoselisteogfør4mndkravetutelatt.',11:'KattHD/CLPfør4mndkravmangler.',12:'Vesentligehovedunntakikkevist.',13:'Ekstrarehabvalgbarpositiv,menkonservativgrunnunntakikkerepresentert.',14:'Fast2.5k/gjentakensammeårsakkenfinnesikildemenbarebevisikatalog;alleredefunn.',15:'Valgbarbevisriktig;sumogperårmekanismealleredefunn.',16:'Ingentilgangutgifteretteropphørselvomskadeinntrafftidligeremangler.',17:'SeparateEkstraytelserkommeri tilleggtilBehandling,ikkeunderfellesvalgtgrense.',18:'10kogegenandeltidligere;ordinertveterinær/autorisertbehandlerkravutlatt.',19:'30kpert/årtidligerepositiv,flereeksaktebehandlingstriggereutelatt.',20:'Periodontittogfør4mndmelketennervilkårmangler.',23:'Livreddende10d5k/unge10k/kullgrensermangler;0egenandelallerederegistrert.',24:'BarevalgfrittlivutelaternødvendigvetavlivningmedgodprognoseunntakogRASEKATTscope.',25:'Leddbetingelsersammeartfør4mndutelatt.',26:'2kkremeringutoversummangler.',27:'1kkremeringutoversummangler.',28:'Livetsvesentligeunntakmangler.',29:'Forsvinninginkludertutelater30dogpolitiannonsering.',30:'Forsvinninginkludertutelater3mndogannonsering;nettsidepolitiavklaresseparat.',31:'Avl/brukaktive12mnd,under8år,3kull/5parringervilkårmangler.',32:'Bruksverdi50%ogfradragseneredødsoppgjørmangler.',33:'Fradraggaptidligere,hergjenanskaffelsestak/0egenandel.',34:'Fradraggaptidligere,hergjenanskaffelsestak/0egenandel.',35:'12årheadutelaterførsteforfallmekanisme.',36:'UbegrensetgratisFirstVet07–24mangler.',37:'Ikkedirekteoppgjør/vilkåret48tflesteikkegarantiikkevist.',38:'SC001eksisterendekonfliktbevares.',39:'DogwebFAQnegativavlivningmotfullpositivbøravklares.'}
for typ,stem in [('dog','hund'),('cat','katt')]:
 pid=f'tryg-{stem}-behandling';p=A.p[pid];prior=[f for f in A.f if f['product']==pid];rows=[]
 paths={k:B+f'tryg-{typ}-{suffix}'for k,suffix in {'treatment':'treatment-terms.pdf','extra':'extra-terms.pdf','life':'life-terms.pdf','web':'product.html'}.items()};paths.update(product=B+'tryg-dog-product-terms.pdf',ipid=B+'tryg-pet-ipid.pdf');used=set(paths.values())
 for n,q in enumerate(I['rules'],1):
  if q['type']not in ['both',typ]:continue
  comp=f'tryg-{stem}-ekstra'if q['scope']=='extra'else f'tryg-{stem}-dod'if q['scope']=='life'else''
  old=[];val=q['value'];loc=q['location']
  if n==1:old=[f for f in prior if f['semantic_subject']=='Geografi'];val='Taker/ektefelle/samboersammefolkeregisteradresse.'
  if n==2:old=[f for f in prior if f['semantic_subject']=='Veterinær'and f['semantic_dimension']=='opphør'];val='Fra35dagersalder;vedsalgavhendelseslutterstraks.'
  if n==3:old=[f for f in prior if f['semantic_subject']=='Karenstid'];val='20dvedsumøkning/utvidelse;ingenTrygvalpekull/overlevertvalpfrakullventetid.'
  if n==4:old=[f for f in prior if f['semantic_subject']=='Diagnostikk'];val='Sykdomtidspunktførstesymptomsenerestførstediagnose;ulykkeplutseligytrefysisk.'
  if n==5:old=[f for f in prior if f['semantic_subject']in['Legemidler','Spesialfôr og sjampo']]
  if n==14:old=[f for f in prior if f['semantic_subject']=='Veterinær'and'egenandel'in f['semantic_dimension']]
  if n==15:old=[f for f in prior if f['semantic_subject']=='Veterinær'and f['semantic_dimension']in['sumperioder','kundens valgte beløp']]
  if n==18:old=[f for f in prior if f['semantic_subject']in['Rehabilitering','Ekstra']];val='Rehabrekvirertavveterinær/klinikkautorisert;fysio/kiro/akupunktur/hydro/trykkbølge.'
  if n==19:old=[f for f in prior if f['semantic_subject']=='Tannsykdom'];val='Tannskade/sykdom/tannkjøtt/melketenner/medisinskproblemvedbittfeil;2.5kegenandelpertilfelle.'
  if n==21:old=[f for f in prior if f['semantic_subject']=='Tannresorpsjon']
  if n==22:old=[f for f in prior if f['semantic_subject']=='Huggormbitt']
  if n in [33,34]:old=[f for f in prior if f['semantic_subject']=='Liv'and f['semantic_dimension']=='aldersreduksjon'];val='Gjenanskaffelsestaktilsvarenderase;0egenandel.'
  for f in old:f['continuation_inventory_links']=list(set(f.get('continuation_inventory_links',[])+[q['id']]));rows.append(f)
  if n in [5,14,15,21,22,38]:continue
  cls=COARSE if any(f['key']in K[n]for f in p['facts']+sum(p['addonFacts'].values(),[]))else MISSING;pri='P1'
  if n in [1,2,3,4,12,16,17,18,19,28,29,30,33,34,37]:pri='P2'
  if n==40:cls=ADMIN;pri=''
  if n==39:cls='SOURCE_CONFLICT_REVIEW_REQUIRED';pri='P1'
  rows.append(A.fact(pid,q['subject'],q['dimension'],val,paths[q['source']],loc,cls,K[n],pri,why.get(n,'Source-backedmaterialconditionnotrepresented.'),'SCRC-047',component=comp,inventory_id=q['id'],extra={'source_first_inventory':'tryg-pet-independent-inventory.json'}))
 rev={}
 for cf in p['facts']+sum(p['addonFacts'].values(),[]):
  ee=[f for f in rows+prior if cf['key']in f['proposed_keys']]
  if ee:rev[cf['key']]={'locations':[{'artifact':f['source_artifact'],'location':f['source_location']}for f in ee],'note':'Exactcoreclaim/sumpositivereversecheck;per-case/annual/scope/conditionsgapsrecorded.'}
 A.reverse(pid,rev)
 A.product_review(pid,sorted(used),True,'40source-firstdimensions+original32factIDsreusedratherthanduplicated. All10localartifactsread,PLB52000Dyrbothspeciesexactscope. Basechoice/scopedaddonlimitskept;before4mnd/0deductible/ageintervalprecisionchecked;SC0019vs10notflattened.')
for ad in A.a['addon_coverage']:
 if ad['addon_id']in['tryg-hund-ekstra','tryg-hund-dod','tryg-katt-ekstra','tryg-katt-dod']:ad.update(status='COMPLETE_WITH_RECORDED_GAPS',fully_audited=True,notes='AllfulltermsandIPID/HTMLchecked;prior10k30kcontrols/known20d/TRfindingsreused;life/disappearance/breed/geographynewconditionsrecorded.')
A.a['source_conflicts'].append(dict(id='SC-051',provider='tryg',family='Hund',product='tryg-hund-behandling',sources=[B+'tryg-dog-treatment-terms.pdf',B+'tryg-dog-product.html'],claim='Avlivningsbehandling',observed='PLB52002Jan2026dekkeranbefaltavlivning;webFAQikkeavlivningblantikke-dekket,presiseringomoffentligkravuklar.',status='SOURCE_CONFLICT_REVIEW_REQUIRED',action='Bevarfullpositivmenavklaromwebkunspesifisererårsakeunntak. Ikkeekstrapolernegativ.' ))
A.a['source_research_queue'].append(dict(queue_id='SR-tryg-pet-source-conflicts',product=['tryg-hund-behandling','tryg-katt-behandling'],reason='SC0019vs10rasefradrag;SC051webavlivninguklar;kattsavnetpolitivilkårwebmenfullbareannonsering;IPIDbruksverdiunderHundExtraoverskriftvsfullHundDød.',external_source_needed_if_unresolved='Autoritativproduktversjon/kanalavklaring;ingenresearchnå.',downloaded=False))
A.checkpoint('Tryg Hund/Katt complete with four optional components; prior facts preserved, full type-specific conditions audited','Innbo','tryg','tryg-innbo')
