from continue_audit import *
A=Audit();I=load('frende-innbo-independent-inventory.json');pid='frende-innbo-standard';p=A.p[pid];path=I['source']
A.root('SCRC-008','Frende Innbo har et rikt og stort sett kildekorrekt radsett, men utelater enkelte standardhendelser, oppgjørsregler og konkrete vilkår bak generelle referanser. Uhell modellerer objektunntak, men ikke skadeårsaksunntak. Ingen runtime-tap av allerede definerte facts funnet.','lib/frende-innbo-catalog.ts:57–124; kilde 5.1–5.3,6.3–6.7,7.3,8–11; alle56base+7addonfacts semantisk kontrollert.',['Innbo'],['frende'],'RB-07',complexity='SMALL_CODE')
K={1:['innbo.forsikrede'],2:['innbo.geografi','innbo.lagring.tid'],3:['innbo.forsikringssum'],4:['innbo.verdigjenstander.enkeltgjenstand.grense','innbo.kunst.grense','innbo.samling.grense'],5:['innbo.hobbyveksthus.grense','innbo.basseng.grense','innbo.fritidsbat.grense','innbo.kjoretoytilbehor.grense','innbo.tilhenger.grense','innbo.yrkeslosore.grense'],6:['innbo.penger.grense'],7:['innbo.andres.grense'],8:['innbo.luftvannsport.grense','innbo.motorredskap.grense'],9:['sykkel.tyveri.grense'],10:['brann.dekning','naturskade.dekning','ran.dekning','tyveri.dekning'],11:['vann.dekning'],12:['tyveri.fellesbod.grense'],13:['tyveri.kjoretoy.grense','tyveri.uteareal.grense'],14:['tyveri.utenforhjem.grense'],15:['innbo.lagring.tid'],16:['glass.sanitaer.grense','tyveri.innbrudd.bygg.grense'],17:[],18:['innbo.datalager.grense'],19:['innbo.opphold.grense'],20:['innbo.vaesketap.grense'],21:['innbo.tilleggsinnredning.grense'],22:[],23:['innbo.egenandel'],24:['naturskade.egenandel'],25:['sykkel.egenandel'],26:['innbo.egenandel'],27:['skadedyr.dekning'],28:['skadedyr.grense','skadedyr.egenandel'],29:['skadedyr.dekning'],30:['ansvar.grense','ansvar.egenandel'],31:['ansvar.dekning'],32:['rettshjelp.grense'],33:['rettshjelp.egenandel'],34:['rettshjelp.egenandel'],35:['rettshjelp.dekning'],36:['rettshjelp.dekning'],37:['idtyveri.dekning','nettmisbruk.dekning'],38:['idtyveri.dekning','nettmisbruk.dekning'],39:['uhell.dekning'],40:['uhell.dekning','uhell.unntak'],41:['uhell.hjem.grense','uhell.grense','uhell.geografi','flytting.transport.grense'],42:['uhell.unntak'],43:['uhell.unntak'],44:['uhell.egenandel'],45:[],46:['sikkerhet.vann','sikkerhet.sykkel']}
coarse={8,11,15,19,21,29,31,32,34,36,38,43,46};missing={17,22,26,45};positive={1,2,3,4,5,6,7,9,10,12,13,14,16,18,20,24,25,27,28,30,33,37,39,40,41,42,44}
for r in I['rules']:
 n=int(r['inventory_id'].split('-')[-1]);value=r['value'];kind=r['kind'];component='' if r['component']=='base' else r['component']
 if n==10:value='Brann/nedsoting/lyn/elektrisk fenomen, eksplosjon/sprenging, naturskade, ran og tyveri/hærverk dokumentert som egne hendelser. Snø-/vindkollaps og fryser registreres separat.'
 if n==16:value='Glassruter og sanitærporselen 40 000 for leietaker/sameie/borettslag. Separat innbruddsbygningsgrense inventoreres under egen dimensjon.'
 classification=COARSE if n in coarse else MISSING if n in missing else PRESENT if n in positive else CUSTOM if kind=='CUSTOMER_SPECIFIC' else 'SOURCE_AMBIGUOUS' if kind=='SOURCE_AMBIGUOUS' else ADMIN
 priority=r['priority_if_missing'] if n in coarse|missing else ''
 reason='Eksakt source fact er representert av angitte base-/tilleggsrader.' if classification==PRESENT else 'Kundens faktiske egenandel krever bevis.' if classification==CUSTOM else 'Fullvilkåret inneholder konkret avgrensning/regel som ikke fremgår av katalogens eksisterende radsett. Ingen ny provider-ekvivalens antatt.' if priority else 'Kildeusikkerhet/administrasjon beholdes eksplisitt, ikke omsatt til sikker dekning.'
 A.fact(pid,r['subject'],r['dimension'],value,path,f"PDF side {r['page']}, {r['section']}",classification,K.get(n,[]),priority,reason,'SCRC-008',component,inventory_id=r['inventory_id'])
# Separate missing source concepts, not all hazards bundled into a generic gap.
for subject,dim,val,page,sec,keys in [('Snø/vind','sammenbrudd i bygning','Innbo ved bygningssammenbrudd som skyldes snøtyngde/snøpress eller vind svakere enn storm.',4,'5.1 / 12',[]),('Fryser','temperaturstigning','Utilsiktet temperaturstigning som skader matvarer og gir luktskade på fryser.',4,'5.1 / 14',['innbo.fryserinnhold.dekning']),('Innbrudd','skade på bygning','40 000 for bygningsskade ved innbrudd når sikrede er leietaker eller bor i borettslag/sameie.',5,'5.1',['tyveri.innbrudd.bygg.grense'])]:
 A.fact(pid,subject,dim,val,path,f'PDF side {page}, {sec}',MISSING,keys,'P2','Uttrykkelig standardytelse mangler helt i de56basefacts; valgfri Uhell er ikke erstatning for en inkludert standardytelse.','SCRC-008')
# Do not present unresolved law-scope inference as proved unsupported or complete reverse support.
A.fact(pid,'Naturskade','geografisk lovhenvisning','Fullvilkår henviser til naturskadeforsikringsloven og har nordisk generell geografi; katalogen sier Norge. Lokal kildepakke gjengir ikke lovens geografiske virkeområde.',path,'PDF side 4/4.1 og 6/6.4','REVIEW_REQUIRED',['naturskade.geografi'],reason='Ikke bevist feil. Lokal lovkilde eller eksplisitt geografi må avklare påstanden; ingen ny research utført.')
locations={}
for f in p['facts']+sum(p['addonFacts'].values(),[]):
 if f['key'] in ['naturskade.geografi','rettshjelp.dekning']:continue
 locations[f['key']]={'artifact':path,'pdf_page':13 if f['key']=='sikkerhet.vann' else f['source']['page'],'section':f['source']['section'],'location_correction':f['key']=='sikkerhet.vann','note':'Exact claim semantically checked against full source; surrounding omissions separately recorded.'}
A.reverse(pid,locations)
A.product_review(pid,[path,'catalog/sources/frende/innbo/IPID_Innbo.pdf','catalog/sources/frende/innbo/Generelle_vilkar-01012026.pdf'],False,'Full14-page terms,2-pageIPID and4-pagegeneral read;47source-first rules plus3independent sub-concepts. 61/63claims have reverse support. Need close source wording in legal cover (buildingowner vs residential policy), and geographic law-reference for naturskade; no web research permitted. No guessed closure. Uhell itself closed with recorded dated source conflict; base product remains partial.')
ad=next(x for x in A.a['addon_coverage'] if x['addon_id']=='frende-innbo-uhell');ad.update(status='COMPLETE',fully_audited=True,semantic_audit_status='COMPLETE',notes='All7addonclaims checked; fullsection11+6.7+geography read; optional selection protected. Newerfullterms versus olderIPID skadedyr wording flagged; no inferred payout.')
for f in A.f:
 if f['product']==pid and f['component']=='frende-innbo-uhell':f['full_package_review_complete']=True
for g in A.a['findings']:
 if g['product']==pid and g['component']=='frende-innbo-uhell':g['complete_package_audited']=True
A.a['source_conflicts'].append({'id':'SC-003','provider':'frende','family':'Innbo','product':pid,'component':'frende-innbo-uhell','claim':'Skade gjort av skadedyr under valgfri Uhell','sources':[path,'catalog/sources/frende/innbo/IPID_Innbo.pdf'],'observed':'IPID01.01.2025 inkluderer skade gjort av skadedyr; fullvilkår01.09.2026/11.4 unntar insekter og kjæledyr. Insekter er del av skadedyrbegrepet i7.2. Ulik datert kilde, ikke automatisk samtidigvilkårskonflikt.','action':'Prioriter avtaleversjon/fullvilkår. Behold eldreIPID som stale summary candidate; ikke utled bred skadedyrskadedekning fra det.','status':'STALE_SOURCE_CANDIDATE','confidence':'HIGH for differing text/date; no authority inference for individual contract'})
A.a['source_research_queue'].append({'queue_id':'SRQ-005','product':pid,'reason':'Two exact claims not locally closed: private legal role scope; naturskade Norway law reference.','local_work_first':'Inspect source-authority metadata and other already-local explicit Frende documents; no forced inheritance from Hus.','external_source_needed_if_unresolved':'Official clarification of Innbo9.1 scope; authoritative local law-geography evidence; updated IPID summary for pestdamage.','downloaded':False})
A.checkpoint('Frende Innbo full source inventory; Uhell complete, two base support questions retained','Hus','frende','frende-hus-standard')
