from continue_audit import *
A=Audit();I=load('frende-boat-independent-inventory.json');path=I['source'];web='catalog/sources/boat-pet/frende-boat-product.html';ipid='catalog/sources/boat-pet/frende-boat-ipid.pdf'
r=next(r for r in A.a['root_causes'] if r['root_cause_id']=='SCRC-003');r['providers']=sorted(set(r['providers']+['frende']));r['description']+=' Frende bruker samme grove boatCore/Fire/Kasko-funksjoner. Utvidet rekonstruerer Kasko uten dens løsørerad; to optional-komponenter har kun én tilgjengelighetsrad hver.';r['evidence']+='; lib/boat-pet-catalog.ts:100–110;Frende13pfullterms+2pIPID+HTML;45sourcefirstrules. Structural mechanism shared; provider rules independently sourced.'
K={1:[],2:['geografi.omrade'],3:[],4:['jolle.dekning','jolle.grense'],5:['losore.dekning','losore.grense'],6:[],7:['brann.dekning'],8:['tyveri.dekning'],9:['redning.dekning'],10:['kasko.dekning'],11:['kasko.dekning'],12:['redning.dekning'],13:['redning.dekning'],14:['redning.dekning'],15:['redning.dekning'],16:['maskinskade.dekning'],17:['maskinskade.dekning'],18:['maskinskade.dekning'],19:['maskinskade.dekning'],20:['opplagsutstyr.dekning'],21:[],22:[],23:[],24:[],25:[],26:[],27:[],28:[],29:[],30:[],31:['ulykke.dekning'],32:['ulykke.dekning'],33:['ulykke.dekning'],34:['ulykke.dekning'],35:['ansvar.dekning'],36:['ansvar.dekning'],37:['rettshjelp.dekning'],38:['rettshjelp.dekning'],39:['rettshjelp.dekning'],40:[],41:[],42:[],43:[],44:[],45:[]}
reason={1:'Medforsikret/bruker-krets mangler.',2:'Norden/angittefarvann skjuler12nm/øyer/hav og bevisført helårutvidelse.',4:'Jolle mangler på grunnnivåene; Utvidet sum finnes, men10fot/10hk/sammenbruk mangler.',6:'Kontanter/verdipapirer/opplagsunntak og utstyrsdefinisjon mangler.',7:'Kun Inkludert; konkrete brannårsaker/startkomponent/varmgang-unntak mangler.',8:'Kun Inkludert; midlertidiglandlagring og husstand/utlån-unntak mangler.',9:'Egen bergelønn i Brann/Tyveri mangler; bred redning på Kasko uttrykker ikke denne rettslige dekningen.',10:'Kun Inkludert; konkrete hendelser og betalt boblehavn mangler.',11:'Materielle kaskounntak og følgeskadeskillet mangler.',12:'Kun Inkludert; sykdom/ulykkeutløser og unntatte objekttyper mangler.',13:'Redningstiltak og vrak10prosent/offentligpålegg mangler.',14:'Separat geografisk hjemtransport/takbåtverdi/50000utvidet mangler.',15:'Redningsegenandel750 mangler.',16:'Valgfritt korrekt; konkrete komponenter/årsaker/diagnostikk mangler.',17:'Maskinskadeunntak og avvistgaranti-mekanisme mangler.',18:'Markedsverditak og hendelsesdatoregel mangler.',19:'Hele egenandelstabellen5–12+år mangler; tabellen dokumenterer ikke øvre dekningsalder.',21:'Ferieavbrudd1500x14/mai-aug/min7dferie mangler.',25:'Førsterisiko/verdiøkning/kontant50prosent/mva-regler mangler.',26:'Markedsverdi og30dagers tapsavklaring mangler.',27:'Seks konkrete aldersfradragsregler mangler.',29:'Ungfører8000/vintersynking4000 mangler.',30:'Tyveriegenandelsfritak ved kombinertFGalarm/gjenfinning mangler.',31:'Valgfritt korrekt; person/ulykkedefinisjon mangler.',32:'Dødsfall100000 og krets/21årvilkår mangler.',33:'Invaliditet200000,proposjonalt/fradrag/3år mangler.',34:'Konkrete ulykkeunntak og PTSD-unntaksregel mangler.',35:'Ansvar inkluderingsstatus korrekt; begge SDRsummer og0egenandel mangler.',36:'Ansvarskrets/unntak og synkingsforurensning mangler.',37:'Kun Inkludert; Norden/nykjøp/salg/voldgift mangler.',38:'100000/250000,økonomiskinteresse og4000+20% mangler.',39:'Konkrete rettshjelputgifter og materielle unntak mangler.',40:'Konkurranse og forhåndsavtalt utleie-bruksregel mangler.',41:'Sikkerhetskrav og sjøventilvinterdato mangler.',42:'Låsekrav og årlige ettersyn mangler.',43:'Sertifikat/lengde/føreralderskrav mangler.',44:'Nettsidens størrelse/fart og husbåt-tegningsvilkår mangler.'}
for pid in ['frende-bat-brann-og-tyveri','frende-bat-kasko','frende-bat-utvidet']:
 p=A.p[pid];full=p['facts']+sum(p['addonFacts'].values(),[]);actual={f['key'] for f in full}
 for q in I['rules']:
  n=int(q['inventory_id'].split('-')[-1]);lvl=q['levels'];comp='frende-bat-maskinskade' if lvl=='machine' else 'frende-bat-ulykke' if lvl=='accident' else ''
  if lvl in ['kasko','machine'] and pid.endswith('brann-og-tyveri'):continue
  if lvl=='utvidet' and not pid.endswith('utvidet'):continue
  keys=['bat.'+k for k in K[n]];matched=[k for k in keys if k in actual];cls=COARSE if matched else MISSING;pr=q['kind'];why=reason.get(n,'Applicable rule reviewed separately from unresolved source discrepancy.');val=q['value']
  if q['kind']=='REVIEW':cls=REVIEW;pr='';why='Kilde/applicability-konflikt, ikke sikker manglende verdi. '+val
  if n==5 and not pid.endswith('brann-og-tyveri'):
   val='Utvidet50000løstutstyr/personligløsøre; Kasko10000medkundespesifiktvalgi bevis.';cls=MISSING if pid.endswith('utvidet') else PRESENT;pr='P1' if cls==MISSING else '';why='Utvidet bygger boatKasko() på nytt og mister Kaskoens egen løsørerad; begge originalkilder bekrefter50000 påUtvidet.' if cls==MISSING else 'Kaskosum10000ogbevisforrang korrekt.'
  if q['kind']=='CUSTOMER_SPECIFIC':cls=CUSTOM;pr='';why='Bevisstyrt valg/sum/egenandel; ingen kundeavtale antas. Panthaver/motoralene er ikke eksisterende katalogprodukter.'
  if n==45:cls=ADMIN;pr='';why='Administrative regler uten egen ordinær dekningsrad.'
  art=web if n==44 else path;loc='HTML FAQ' if n==44 else f'PDF side {",".join(map(str,q["pages"]))}, punkt {q["section"]}'
  A.fact(pid,q['subject'],q['dimension'],val,art,loc,cls,matched or keys,pr,why,'SCRC-003',component=comp,inventory_id=q['inventory_id'],extra={'shared_source_inventory':'frende-boat-independent-inventory.json','exact_base_and_available_optional_claims_checked':len(full),'optional_availability_not_customer_selection':True})
 if pid.endswith('utvidet'):
  A.fact(pid,'Totalskadegaranti','sikkertomfang/alder','TilleggUtvidet har totalskadegaranti,3åretterkjøpfabrikknyforhandler,inntilforsikringssum,ikkenæring/utleie.80%fullvilkårvs60%HTMLholdes separat uavklart.',path,'PDFside5 punkt7.5',MISSING,['bat.nyverdi.dekning','bat.nyverdi.alder'],'P1','Selve garantien/alderen er dokumentert i begge kilder men mangler i katalogen; uavklart prosent brukes ikke som begrunnelse for å skjule de sikre dimensjonene.','SCRC-003',inventory_id='FR-BA-022-SAFE')
 locs={'bat.ansvar.dekning':(9,'12.1'),'bat.rettshjelp.dekning':(10,'13.1'),'bat.geografi.dekning':(2,'2'),'bat.geografi.omrade':(2,'2'),'bat.brann.dekning':(3,'4'),'bat.tyveri.dekning':(3,'4'),'bat.kasko.dekning':(3,'5'),'bat.redning.dekning':(4,'5.3'),'bat.losore.dekning':(2,'3.3'),'bat.losore.grense':(2,'3.3'),'bat.opplagsutstyr.dekning':(4,'7.1'),'bat.jolle.dekning':(2,'3.2'),'bat.jolle.grense':(2,'3.2'),'bat.maskinskade.dekning':(4,'6'),'bat.ulykke.dekning':(8,'11')}
 A.reverse(pid,{k:dict(artifact=path,pdf_page=pg,section=sec,location_correction=True,note='Exact inclusion/amount supported at corrected locator, surrounding missing dimensions listed. No invented customer choice.') for k,(pg,sec) in locs.items() if k in actual})
 # Transport/sjøsetting/opptak combined label not certified from transport clause alone.
 for claim in A.support:
  if claim['product_identity']==p['identity'] and claim['key']=='bat.transport.dekning':claim.update(full_claim_validated=False,support_status='APPLICABILITY_REVIEW_REQUIRED',manual_reverse_evidence='5.1.4 explicitly land/sea transport; combined label sjøsetting/opptak requires material event mapping review, no false unsupported assertion.')
 A.product_review(pid,[path,ipid,web],False,'Full13pterms+2pIPID+HTMLread;45sourcefirstrules, exact base/optional facts reviewed. Remaining applicability: BrannTyverilosøre,Utvidet80vs60/30kvs10k, transportlabel sjøsetting/opptak. No new research.')
for aid in ['frende-bat-maskinskade','frende-bat-ulykke']:
 ad=next(x for x in A.a['addon_coverage'] if x['addon_id']==aid);ad.update(status='COMPLETE',fully_audited=True,semantic_audit_status='COMPLETE',notes='Exact optional scope in2026fullterms+IPID+HTML reviewed. Four independent material rules per addon, availability correct but details missing. No customer selection inferred; no age limit inferred from deductible table.')
A.a['source_conflicts'].append(dict(id='SC-010',provider='frende',family='Båt',sources=[path,ipid,web],claim='Utvidet newvalue threshold/storage equipment sum; base contents; combined transport label',observed='Fullterms80%newvalue/30000storage vsHTML60%/10000. Mainterms3loosecontentsall versusHTML/IPIDBrannTyverirestrictions. Sjøsetting/opptak label broader than explicit transport clause needs eventscope review.',status='SOURCE_APPLICABILITY_REVIEW_REQUIRED',action='Retain uncertainties separately; safe guaranteeage3/Utvidetcontents50000 and fully documented optional tables independently recorded. No inferred age ceiling.'))
A.checkpoint('Frende Båt three packages reviewed;two complete optional audits;shared boat reconstruction gap independently proven','Hund','frende','frende-hund-veterinaer')
