from continue_audit import save
rows=[]
def r(sub,dim,val,page,sec,levels='ADKS',types='Bil|MC|Bobil|Snøscooter',priority='P2',kind='RULE'):
 rows.append(dict(inventory_id=f'SB-MO-{len(rows)+1:03}',subject=sub,dimension=dim,value=val,page=page,section=sec,levels=list(levels),types=types.split('|'),priority_if_missing=priority,kind=kind))
r('Produktomfang','nivå/bevis','Ansvar,Delkasko,Kasko,Super etterbevis; MC/Snøscooterproduktside bare Ansvar/Delkasko/Kasko; bevis går foran.',1,'Innledning+1.1','ADKS',priority='P1',kind='CUSTOMER_SPECIFIC')
r('Forsikret','person/bruk','Norgebosatt forsikringstaker; ansvar også rettmessigfører; panthaver måha bekreftelse.',5,'2')
r('Ansvar','registrering','Norskregistrert kjøretøy; ansvar opphører automatisk vedavregistrering, øvrigvalgtkasko fortsetter.',6,'3 og6.1','ADKS',priority='P1')
r('Geografi','hovedregel','EØS+Sveits, andreGrøntkortland iEuropainntil3måneder; ikkeTyrkia,Russland,Belarus,Kosovo.',6,'4','ADKS',priority='P1')
r('Ansvar','sum','Personubegrenset,ting100millioner;utenlandsstedslov,innenEØSnorsk hvisgunstigere;ingenegenandel.',9,'6.1','ADKS',priority='P1')
r('Brann','årsak/unntak','Åpenflamme,lyn,eksplosjon; batterialeneskade,kortslutning/opphetingutenåpenild ikke brann.',9,'6.2.1','DKS',priority='P1')
r('Brann','egenandel','8000 medmindrebevisannet;ladekabelaleneforsikretelbil/hybrid2000.',10,'6.2.1','DKS',priority='P1')
r('Tyveri','omfang','Tyveri/forsøk,åpenbartyverirelatert hærverk/innbrudd;husstandsmedlem ikketyveri;underslagprøvekjøring vedannonsert salg inkludert.',10,'6.2.2','DKS',priority='P1')
r('Tyveri','egenandel','8000 standard;FGalarmidriftskade reduserer4000.',10,'6.2.2','DKS',priority='P1')
r('Utstyr','standard','Originalsommer/vinterhjul,sikkerhetsutstyr,fastutstyrfraforhandlerførlevering,softwareoriginal;nøkleroriginale.',7,'5','DKS')
r('Sikkerhetsutstyr','MC/Snøscooter','Kjøredress,hjelm,hanske,støvler omfattes;ingen sumgrense men utstyretsoppgjørsregel.',7,'5','DKS','MC|Snøscooter','P1')
r('Fastmontert utstyr','sum/relativt tak','Delkasko/Kasko20000,Super50000;ikke merenn50prosent kjøretøyetsgjenanskaffelsesverdi;ettermontertsoftware/dekor/lakk/hjul/takboks.',7,'5 og6.4.7','DKS',priority='P1')
r('Bagasje','Bil','Delkasko/Kasko10000,Super20000;veddekketbrann/tyveri/kasko. Ikke penger/verdipapirer iSuper.',7,'5 og6.4.6','DKS','Bil','P1')
r('Bagasje','Bobil','Delkasko/Kasko30000;Super100000 for løsøre/personligeeiendeler.',7,'5 og6.4.8','DKS','Bobil','P1')
r('Bagasje','MC/Snøscooteravgrensning','Felles tabellgir10000 ordinærbagasje;MCproduktsiden unntarbagasje oggods;Superutvidelse eksplisitt ikkeMC/scooter. Avklar ordinærkollisjon.',7,'5 og6.4.6 +MCweb','DKS','MC|Snøscooter','P1','SOURCE_CONFLICT')
r('Ladekabel','omfang','Bil/elhybrid kabel oppbevartbil/låstbod/skap/lading;fastbygningsladestasjonikke;2000egenandelskadealene.',7,'5 og6.2.1/6.2.2/6.3','DKS','Bil|Bobil','P2')
r('Aldersfradrag','utstyr/dekk','Etterettårkan reduseredekk25prosentperårmax100;annetutstyr10prosentpåbegyntårmax50.',8,'5','DKS',priority='P1')
r('Aldersfradrag','bagasje','Klær1fradragsfrittår/10prosent;elektrisk5/10prosent;mobil/data1/20prosent;annet5/5prosent;allemax80. Kildetekstenregner toårklær20prosent.',8,'5 – tabell','DKS','Bil|Bobil','P1')
r('Veihjelp','geografi','DelkaskoNorden,Kasko/SuperEØS/Sveits+øvrigEuropamax3mnd oggeografiunntak.',11,'6.2.3 og4','DKS','Bil|MC|Bobil','P1')
r('Veihjelp','årsaker','Verksted/repsted vedkollisjon/tyveri/startstopp/tomellerfeilfylt tank/utelåsing/nøkkel/punktering;sykdom/ulykke/død kanhindreviderekjøring.',11,'6.2.3','DKS','Bil|MC|Bobil','P1')
r('Veihjelp','hjemtransporttak','Kjøretøyshjemtransportmaks50prosent kjøretøyverdi; subsidiærgaranti/medlemskap;passasjerreise/opphold rimeligste måte;tilhenger/campingunderbrukomfattesutenannendekning.',11,'6.2.3','DKS','Bil|MC|Bobil','P1')
r('Veihjelp','tilkomst/egenandel','Normaltfremkommeligutenadgangsrestriksjon;bestillesStorebrand;750egenandel.',11,'6.2.3,12/egenandel','DKS','Bil|MC|Bobil','P2')
r('Transport','Snøscootersærregel','Transportkost50prosent,begrenset halvpartavskadeerstatning,nårskadeoveregenandel;ingenandretransportutgifter. Websierikkeordinærveihjelp.',11,'6.2.3/5','DKS','Snøscooter','P1')
r('Glass','tak/egenandel','Plutselig brudd allekjøretøyruter;byttetak50prosentgjenanskaffelse;3000bytte,0reparasjon.',12,'6.2.4','DKS',priority='P1')
r('Naturskade','dekning/egenandel','Skred/storm/flom/stormflo/jordskjelv/vulkan iNorden;8000medmindreannet.',12,'6.2.5','DKS',priority='P1')
r('Kasko','årsaker','Sammenstøt/utforkjøring/velt/hærverk/feilfylling/annenplutseligytrepåvirkning i tilleggDelkasko.',12,'6.3','KS',priority='P1')
r('Kasko','egenandel/dyr','Bevisegenandel;dyrepåkjørsel reduserer6000 vedumiddelbarmeldingpoliti/viltnemnd.',13,'6.3','KS',priority='P1')
r('Nyverdi','ordinærpersonbil','Registrertperson/varebil;inntil1år15000km,rep>80prosentnylistepris;ikketidligereskade>10prosent;ikkelaset/taxi/trafikkskole/utleie/prøve/turist/eksport/diplomat;gjenkjøp.',24,'10.3,fortsetter25','DK','Bil','P1')
r('Nyverdi','Bobilordinær','TabellviserKasko1år15000;full10.3begrensettilregistrertperson/varebil. Bobilregistreringsklasse kanavgjøre;ikkeubetingettransfer.',24,'10.3 +1.2','K','Bobil','P1','SOURCE_AMBIGUOUS')
r('Nyverdi','Super','Inntil3år60000km;førstefabrikkregistrertpåforsikringstaker;taptellerrep>nylistepris;ingenførskade>10prosent;ikkeleased;gjenkjøp.',13,'6.4.1,fortsetter14','S','Bil|Bobil','P1')
r('Startleie','Super','Totalskadekvalifiserer6.4.1 ellertaptettertyveri30d;startleienedskrivesmåneder;ingenytelsehvisleasingfortsetterutenny startleie.',14,'6.4.2','S','Bil|Bobil','P1')
r('Maskinskade','alder/km','Inntil200000km og12år fraførstereg;ingenetterpassering;kmegenandel8000<100000,15000<150000,20000til200000;ingenbonus.',14,'6.4.3 og16','S','Bil|Bobil','P1')
r('Maskinskade','komponenter','Plutseliguforutsett fremdriftshindrendemekanisk/elektronisk skade i oppgitte motor/gir/drivlinje/elhybridbatteri/ladekomponenter,servo,varme/kjøledeler;clutch/svinghjul/sylinder/vaierkuninntil100000km.',14,'6.4.3,15','S','Bil|Bobil','P1')
r('Maskinskade','unntak','Ikke følgeskadefraekskludertkomponent;clutchlamell,slanger/filter/tank,understell/brems/lager/DPF,eksternladekabel,startbatteri,annetutenfordrivlinje.',15,'6.4.3','S','Bil|Bobil','P1')
r('Maskinskade','årsaksunntak/service','Ikkevarmgang/slitasje/korrosjon/klima/oljeoverforbruk/kapasitetstap/konstruksjonsoftwarefeil/ikke godkjenttrim;servicefulgtogdokumentert;garantikravførst,forgjeveskravkanomfattes.',16,'6.4.3','S','Bil|Bobil','P1')
r('Bilnøkkel','sum/egenandel','Mistet/stjålet/ytre skadet;ny/programmering/omkodingautorisert;20000/1000egenandel.',16,'6.4.4,17','S','Bil|Bobil','P1')
r('Bilnøkkel','unntak','Ikke gjenglemt/tekniskfeilalene,låsbytte/ECUomprogrammering,ekstradelnøkkel.',17,'6.4.4','S','Bil|Bobil','P1')
r('Parkering','sum/vilkår','25000utenbonus;tillfeldigskadefraannetukjentkjøretøy,kjenttid/sted,avtaleverksted;valgtkaskoegenandel;over25000ordinærbonus.',17,'6.4.5','S','Bil|Bobil','P1')
r('Fukt','BobilSuper','Nyereenn8produksjonsår;ferskvann/avløp/varmeanlegglekkasje;beståttautorisertfuktkontrollgiromfangettår;nykontrollkreves;ikkefrost;8000egenandel.',18,'6.4.8/1','S','Bobil','P1')
r('Feriegaranti','BobilSuper','Erstatningsmessigskadeetterpåbegyntferie;alternativovernatting1500/dagrestferiemaks15d;dokumentasjon.',18,'6.4.8/2','S','Bobil','P1')
r('Leiebil','valg/årsaker','BarebevisvalgtpåKasko/Super,dekkerutbetaltbrann/tyveri/kasko/skadevolderansvar;Supermaskinskadeinkl;ikke glassalene;forhåndsgodkjent.',18,'7','KS','Bil|Bobil','P1','OPTIONAL')
r('Leiebil','klasse','StandardklasseC/utvidetklasseI,ikkestørreennskadetkjøretøy;utennettverk350/dag.',19,'7.1','KS','Bil|Bobil','P1','OPTIONAL')
r('Leiebil','reparasjon','Maks60d,over30dspesialavtale;utenavtaleverksted15d;normalreparasjon+ventingmaksnormaltid.',19,'7.2','KS','Bil|Bobil','P1','OPTIONAL')
r('Leiebil','kontant','Ingenleid250/dagmax21dnormalrep;ingenleiebilkostvedkontantoppgjør.',19,'7.1–7.2','KS','Bil|Bobil','P1','OPTIONAL')
r('Leiebil','totalskade/tyveri','Totalskadefraregistrerttil15d etteravgjørelse;tyverifaktisktid+15d ettertilbud;utenleiebil250/dag15d.',19,'7.2','KS','Bil|Bobil','P1','OPTIONAL')
r('Leiebil','maskin/veibrudd','Supermaskin15d føravgjørelse,erstatningsmessiginntil60d;utilgjengeligvednaturulykkeveibrudd10d.',19,'7.2','KS','Bil|Bobil','P1','OPTIONAL')
r('Generelle unntak','bane/is/trim','Banekjøringunntattmedobligatoriskopplæring/glattbanetreningunntak;islagtutenmerketvei,ikke godkjenttrim,egenmaskin/elektronikkuteneksternskadeunntatt.',20,'8','DKS',priority='P1')
r('Bruk','utleie/næring','Skadevedbetaltprivatutleie/formidletutleie/næringunntattutenavtale;ogsåhåndverkerbiltil/fraarbeid.',20,'8/17–18','DKS',priority='P1')
r('Egenandel','ungfører','Vedavtaltingenunder23menyngrefører:15000ekstra.',21,'9.1','ADKS',priority='P1')
r('Sikkerhet','kjørelengde/service','Årligavtaltkjørelengde,sikkerhet/service/frost/sertifikat,last,låsing/spesifikklagring;risikoendringproportionalavkortning.',21,'9.1–9.2,22','ADKS',kind='CUSTOMER_SPECIFIC')
r('Oppgjør','reparasjon','Slitasjefradrag/skjønn,tilsvarendebruktedeler;utenverkstedarbeid50prosent;ikkeverdifall/avsavn/arbeidsinntekt.',23,'10.2,24','DKS',priority='P2')
r('Oppgjør','kosmetikkMC/Scooter','Kosmetikkskadeutenfunksjonstap kanrepareres/utbetales skjønn,ikkekravnye deler.',23,'10.2','DKS','MC|Snøscooter','P1')
r('Reparasjonsgaranti','Bil','Person/varebilinntil3,5tonn:8år fordekketskadereparasjonvedavtaleverksted,uavhengigsenereforsikringsgiver;kravinnento mndoppdaget.',24,'10.2.1','DKS','Bil','P2')
r('Bonus','unntak','Ingenbonustapdelkaskoskade,leiebilalene,Supermaskin,rapportertdyr,natur,feilfylling,nøkkel/parkeringSuper,øvelseskjøring.',26,'11.2','ADKS',priority='P2')
r('Bonus','opptrapping/tap','10poeng/skadefrittåropp70,3år70gir75;75ettertredjeårettap0mennullstillopptjening;førdet5;andre10.',26,'11.3–11.4','ADKS',priority='P2')
r('Ulykke','avtale/rolle/sum','Bevisvalgtfører/passasjer,ikke betaltpassasjer;død100000,invaliditet200000,barnunder18500000prosentvis;førerutenforkjøretøyhvisdirekteårsak.',27,'12.1–12.3','ADKS',priority='P1')
r('Ulykke','unntak','Ikkepsykisk/adferd;sykdomogsykdomsdisposisjon,ryggutenpåvistbrudd;arr/vansiringunder15prosentikkedekket.',28,'12.4','ADKS',priority='P1')
r('Ulykke','tidsfrist/invaliditetsberegning','Dødinnen2år;ettertoårkuninvaliditet;dødannenårsakinntoåringen;tidligerefunksjonstaptrekkes,medvirkendeforholdforholdsmessig.',29,'12.5.2–12.5.3','ADKS',priority='P2')
r('Rettshjelp','rolle/geografi','Eier/rettmessigfører/bruker/Norden;etterfølgendetvistvedsalg/tilbakeleveringleasingfortsetter.',30,'13.1–13.3,31','ADKS',priority='P1')
r('Rettshjelp','sum/egenandel','100000pertvist;3–10parter250000;11–25500000;26–49750000;50+énmillion;4000+20prosent én per tvist.',32,'13.5–13.6','ADKS',priority='P1')
r('Rettshjelp','unntak','Ikkenæring/familie/straff/førerkort/ubestridtgjeld/konkurs/advokatsalær/sameier/preeksisterendegrunnlag/ankerettsgebyr/motpartskost. Forvaltningsøksmålbareuttømtklage;BALavslagførjuridiskhjelp.',31,'13.4,32','ADKS',priority='P1')
r('Administrasjon','generellevilkår','Skademelding/skjønn/regress/fornyelse/klage oggenerellemotorforsikringsregler;ikkehverparagraphpremiumrad.',1,'Innledning+10+13.7','ADKS',kind='ADMINISTRATIVE')
r('Tegning','MC/scooter','Produktside:bilforsikringStorebrandkreves forMC;privateNorgeregistrerte;ATV/snøscooterinntil175HK.',None,'MCwebFAQ','ADK','MC|Snøscooter','P1',source if False else 'RULE')
r('Banekurs','MC','Produktside skriftligforhåndsgodkjentførerkurskanomfattes;ingenallbanedekning.',None,'MCwebFAQ','ADK','MC','P2')
r('Egenandel','MCene-fører','Vedavtaltrabattforbareforsikringstakerogannenfører:15000ekstra; ikke detsammesomunder23.',None,'MCwebFAQ','ADK','MC','P1')
r('Tegningsalder','BilSuper','ProduktsidekjøpSuperforbilsomsyvårellernyere;ikkeopphørsalder12år.',None,'BilwebFAQ','S','Bil','P1')
save('storebrand-motor-independent-inventory.json',{'phase':'SOURCE_INVENTORY_COMPLETE','source_first':True,'catalog_fact_values_inspected':False,'source':'catalog/sources/storebrand/vilkar-motorvognforsikring-motor09.pdf','read':'all33physicalpages;BilBobilandMCstoredHTML;general11alreadyreadbyidenticalhash','rules':rows,'notes':['PhysicalPDFpage=printedpage+1.','Sharedterms explicitlyincludeBil/MC/Bobil/Scooter,onlyexplicittypespecificexceptionssharedselectively.','MCbagageconflictandBobilordinarynewvalueunresolvednotguessed.','Accidentbevisconditionversusproductmatrixmustpreserveavailabilityselectiondistinction.']})
print(len(rows),'source-first rules saved')
