from continue_audit import save
R=[]
def r(s,d,v,p,sec,types='Campingvogn|Tilhenger',levels='BKS',prio='P2',kind='RULE'):
 R.append(dict(inventory_id=f'SB-CA-{len(R)+1:03}',subject=s,dimension=d,value=v,page=p,section=sec,types=types.split('|'),levels=list(levels),priority_if_missing=prio,kind=kind))
r('Avtale','bevis/sum','Valgt nivå og forsikringssum følger beviset. Gjenanskaffelsesverdi, begrenset av bevisets sum.',4,'5',kind='CUSTOMER_SPECIFIC')
r('Tegning','forutsetning','Norskregistrert, privat bruk/eie, inntil7 500kg; eksisterende Bil/Innbo/Hus/Hytte i Storebrand kreves.',None,'Produktsider/FAQ',prio='P1')
r('Sikrede','personkrets','Norsk bostedsadresse. Panthaver/økonomisk interessent omfattes ved bekreftelse.',3,'2')
r('Geografi','område','EØS/Sveits og andre europeiske Grønt kort-land i inntil3måneder; ikke Tyrkia/Russland/Belarus/Kosovo.',3,'4, fortsetter4',prio='P1')
r('Ansvar','trekkvogn','Ingen selvstendig ansvarsforsikring; trekkbilens ansvar dekker ved bruk sammen med bilen.',None,'Produktside FAQ',prio='P1')
r('Utstyr','fastmontert','Fast utstyr og originale hjul inngår i gjenanskaffelsesverdi/sum.',4,'5',prio='P1')
r('Fortelt/spikertelt','bevisført','Fortelt/bygningskonstruksjon må spesifiseres i beviset; inkluderes i avtalt sum.',4,'5','Campingvogn',prio='P1',kind='OPTIONAL')
r('Fortelt/spikertelt','avgrensning','Ikke skade under montering/demontering. Ikke sammenbygget konstruksjon: bare brann/lyn/eksplosjon. Ingen tyveri av løse ting i fortelt.',8,'7/17–20','Campingvogn',prio='P1',kind='OPTIONAL')
r('Løsøre','sum/pergjenstand','Campingvogn30 000 samlet og5 000 pergjenstand, kamera regnes som én ting; husstand/andre reisefelles løse ting innen sum.',4,'5','Campingvogn','BK','P1')
r('Løsøre','Superkildekonflikt','Super100 000 i tabell5, men30 000 i detaljtekst5 og skadeårsaktabeller1/6; produktside30 000. Ikke avgjør uten avklaring.',4,'5 og1/6','Campingvogn','S','P1','SOURCE_CONFLICT')
r('Løsøre','sumutvidelse','Høyere sum kan velges og fremgår av beviset; produktsiden nevner ekstra løsøreforsikring uten fast tilleggssum.',4,'5 +produktside','Campingvogn',prio='P1',kind='OPTIONAL')
r('Last','tilhenger','Ting som fraktes på tilhenger er ikke omfattet.',None,'Tilhengerproduktside/FAQ','Tilhenger',prio='P1')
r('Aldersfradrag','utstyr','Etterettår:10prosent per påbegyntår, maksimalt50prosent.',4,'5',prio='P1')
r('Aldersfradrag','bagasje','Klær1/10prosent,elektrisk5/10prosent,mobil/data1/20prosent,annet5/5prosent;max80. Første tall er antall år uten fradrag; brukt/arv/gave erstattes bruktverdi.',5,'5 – tabell','Campingvogn',prio='P1')
r('Egenandel','samordning','Kun høyeste egenandel ved samme hendelse.',5,'5')
r('Brann','omfang/egenandel','Åpen flamme/lyn/eksplosjon;8 000 med mindre annet avtalt.',5,'6.1.1',prio='P1')
r('Tyveri','omfang/egenandel','Tyveri/forsøk og relatert hærverk/innbrudd; ikke husstandsmedlem;8 000 med mindre annet avtalt.',6,'6.1.2',prio='P1')
r('Veihjelp','nivå/geografi','Brann/tyveri Norden;Kasko/Super dekket Europa inntil3måneder utenforEØS/Sveits. Nødvendig verkstedtransport eller billigere reparasjon påstedet.',6,'6.1.3 +4',prio='P1')
r('Veihjelp','faststed/egenandel','Faststående campingvogn:frigjøring/transport tilkjørbarvei5 000. Veihjelp750egenandel.',6,'6.1.3','Campingvogn',prio='P1')
r('Veihjelp','Tilhengerkonflikt','Fullvilkår selvstendig veihjelp750; produktside avhenger av trekkbilens dekning og sier500. Smalere kanalregel eller gammel produktside må avklares.',6,'6.1.3 +tilhengerFAQ','Tilhenger',prio='P1',kind='SOURCE_CONFLICT')
r('Kasko','årsaker','Sammenstøt/utforkjøring/velt/hærverk/naturskade/annen plutselig ytre påvirkning og skadedyr.',6,'6.2',levels='KS',prio='P1')
r('Kasko','egenandel','Fremgår av beviset; campingwebvalg4 000/8 000/16 000.',7,'6.2 +campingFAQ',levels='KS',kind='CUSTOMER_SPECIFIC')
r('Egenandel','Tilhengerkonflikt','Fullvilkårbrann/tyveri8 000/beviskanavvike; produktside fast1 000 uten valgmulighet. Ikke velg én uten kildeavklaring.',6,'6.1 +tilhengerFAQ','Tilhenger',prio='P1',kind='SOURCE_CONFLICT')
r('Nyverdi','Super','Inntil3år fra nyregistrert på forsikringstaker; tapt eller reparasjon overnylistepris; gjenkjøp tilsvarende. Ingen kilometergrense i denne dekningen.',7,'6.3.1','Campingvogn','S','P1')
r('Fukt/vann','Super','Campingvognnyereenn15år fra produksjon; fukt vegg/tak/gulv; kontroll uten anmerkning hosforhandler/verksted innenettår før oppdagelse;nykontrollårlig.',7,'6.3.2','Campingvogn','S','P1')
r('Fukt/vann','unntak','Frost/snøtyngde også medvirkende årsak unntatt.',8,'6.3.2 +7/21','Campingvogn','S','P1')
r('Feriegaranti','Super','Alternativovernatting1 500/dag restenavplanlagtferie,maks15d,etterdekketskade påpåbegyntferie.',8,'6.3.3','Campingvogn','S','P1')
r('Utleie/næring','særavtale','Privat/formidlet betaltutleie og næringsbruk unntatt med mindre avtalt.',8,'7/13–14',prio='P1')
r('Frost/snø/utetthet','unntak','Frost/snøtyngde unntatt;fukt/vann/råte/utetthet barefølgeskade ellersSuperregel;isolerglassutett ogvibrasjon/vridningujevnvei unntatt.',8,'7/21–24,fortsetter9',prio='P1')
r('Løsøre','unntak','Ikke smykker/klokker/kunst/penger/verdipapirer/forbruksvarer. Kaskoløsøre krever ytrehendelse som rammercampingvognen utenfra.',8,'7/15–19','Campingvogn',prio='P1')
r('Generelle unntak','elektronikk/is/garanti','Elektronikk uten annen dekketytrehendelse, umerketisvei, verdifall/arbeidsinntekt/avsavn unntatt; forgjeves leverandørkravkanlikeveldekkes.',8,'7')
r('Sikkerhet','forebygging','Frostvæske/tømming, vedlikehold/service,transportegnethet,låsing;tilbyggvær/vindforsvarligogoffentligkrav;ikkeflomutsattplassering.',9,'8,fortsetter10')
r('Oppgjør','kosmetikk/reparasjon','Funksjonsbevarende reparasjon eller skjønnskontant ved kosmetikk; ikke krav nye deler. Verksted/utbedring mågodkjennes;utenverksted50prosentarbeidspris.',11,'9.2',prio='P1')
r('Rettshjelp','rolle/geografi','Privat eier/rettmessigfører/bruker iNorden;etterfølgendesalgs-/leasingtilbakeleveringstvist også.',12,'10.1–10.3,13',prio='P1')
r('Rettshjelp','sum','100 000;3–10parter250 000,11–25=500 000,26–49=750 000,50+=énmillion.',14,'10.5',prio='P1')
r('Rettshjelp','egenandel','4 000+20prosent; én egenandel pertvist uansett flereparter.',15,'10.6',prio='P1')
r('Rettshjelp','unntak','Næring,familie,straff/førerkort,sameie,forvaltningførklageuttømt,preeksisterendegrunnlag,motpartskost/ankegebyr og flerekonkretelister.',14,'10.4',prio='P1')
r('Administrasjon','generelle regler','Fornyelse/meldeskade/skjønn/regress/oppgjørsadministrasjon og gener07 er kildeinformasjon,ikke hver enegen sammenligningsrad.',1,'Innledning+9+10.7',kind='ADMINISTRATIVE')
save('storebrand-camp-independent-inventory.json',dict(source_first=True,catalog_fact_values_inspected=False,phase='SOURCE_INVENTORY_COMPLETE',source='catalog/sources/vehicle-extensions/storebrand-vilkar-campingvogn-og-tilhenger.pdf',read='Full15physicalpages;bothstoredHTML;general11reusedbyhash',rules=R,notes=['Superlosore30000vs100000 source conflict preserved.','Tilhengerwebsite1000/500 vsfullterms8000/750 not silentlynormalized.','NoSuperforTilhenger;noinheritanceofcampingfukt/ferie/losore.']))
print(len(R),'independent rules saved')
