from continue_audit import *
R=[]
def r(s,d,v,l,scope='all',doc='terms'):
 R.append(dict(id=f'SBT-{len(R)+1:02d}',subject=s,dimension=d,value=v,location=l,scope=scope,doc=doc))
r('Sikrede','personkrets','Norsk bosatt eier, rettmessige brukere og avtalt registrert rettighetshaver; ny eier inntil 14 dager til ny avtale.','§1–3 fysisk s5')
r('Geografi','område','Hele året NO/SE/DK/FI 12 nm, Kattegat/Skagerrak øst Lindesnes–Hirtshals, Østersjøen/Finskebukta/Bottenvika; 1.4–30.9 øvrige Europa 200 nm inkl angitte øyoverfarter. Rettshjelp Norden.','§3 fysisk s5')
r('Registrering','vilkår','Norsk registrering; motor fra 10 hk / seil fra 4,5 m Småbåt eller Securmark og merke. Web sier over 10 hk / lengre enn 4,5 m og bare Småbåt.','§4 fysisk s5; web registrering')
r('Forsikrede ting','forsikringssum','Båt/motor/seil, naturlig tilbehør og fast utstyr innen avtalt sum; sikkerhetsutstyr uten begrensning i tillegg.','§4 fysisk s5–6')
r('Bagasje','sum','Midlertidig ombord 50000 per skadetilfelle; Super 100000; hvert objekt 15000. Ikke smykker, klokker, kunst, penger, papirer eller forbruksvarer.','§4/§5.1/§5.3.2/§6.10 fysisk s6–11')
r('Egenandel','mekanisme','Høyeste egenandel per hendelse; fradrag før egenandel; utleie dobler egenandel unntatt ≤15 fot båt til utleid fritidshus.','§4 fysisk s6')
r('Brann','utløser','Brann, lyn og eksplosjon.','§5.1 fysisk s7')
r('Tyveri','utløser','Tyveri og forsøk; hærverk i forbindelse med tyveri/innbrudd, ikke all skadeverk generelt.','§5.1 fysisk s7')
r('Redning','vilkår','Ubegrenset rimelig slep til trygg havn etter uforutsett uhell som hindrer videre ferd; bergelønn.','§5.1.3 fysisk s7–8')
r('Transport','vilkår','Verksted/foreløpig reparasjon etter dekket skade. Hjemtransport båt etter reparasjon/funnet etter tyveri; personer hjem eller rimeligere opphold. Delkasko bare brann/tyveri.','§5.1.3 fysisk s8')
r('Kriseterapi','grense og vilkår','10 timer innen 12 måneder; alvorlig ulykke/brann/ran/overfall/voldtekt med båt, avtalt psykolog, reise etter norske satser, utenlandsbehandling norske priser og ikke utenlandsreise; anmeldelse der relevant.','§5.1.3 fysisk s8')
r('Egenandel','faste satser','Brann/tyveri 6000 med mindre annet avtalt; redning 750. Tyveri av boltlåst motor eller FG sporing/Securmarkmerket båt reduserer 4000.','§5.1 egenandel fysisk s8')
r('Kasko','utløser','Sammenstøt/kantring/synking/plutselig ytre påvirkning, riggbrudd/følger, båt og tilbehør under transport.','§5.2 fysisk s9','kasko')
r('Opplagsutstyr','sum','Tyveri/skade inntil 20000.','§5.2 fysisk s9','kasko')
r('Drivstoff','avgrensning','Plutselig tilførsel av forurenset drivstoff eller feilfylling dekkes; drivstoff som blir forurenset i egen tank dekkes ikke.','§5.2/§6.22 fysisk s9/11','kasko')
r('Kasko egenandel','standard','8000 med mindre beviset sier annet; også Super.','§5.2–3 fysisk s9–10','kasko')
r('Ferieavbrudd','satser','Super 15.4–15.9; brann/tyveri/kasko; 2 promille avtalt sum per dag, inntil 30 dager/60000; normal reparasjon/ventetid, totaltap 30 dager.','§5.3.1 fysisk s9–10','super')
r('Super bagasje','sum','100000 samlet; §6.10 begrenser per ting 15000.','§5.3.2/§6.10 fysisk s10–11','super')
r('Super reisekostnader','utløser','Rimeligst videre til reisemål eller hjem når uhell hindrer ferd eller person rammet av sykdom/ulykke/død. Hjem båt til fast havn.','§5.3.3–4 fysisk s10','super')
r('Jolle','grense','Jolle/gummibåt/livbåt inntil 4 meter med utenbordsmotor inntil 10 hk innen avtalt sum.','§5.3.5 fysisk s10','super')
r('Totalskade','nytt objekt','Inntil 3 år fra kjøp som ny båt og/eller motor; tapt eller reparasjon >80% importørlistepris tilsvarende ny; inntil forsikringssum.','§5.3.6 fysisk s10','super')
r('Totalskade','brukt objekt','Inntil 3 år fra kjøp; kjøpspris, begrenset til sum og markedsverdi ved kjøp; hvis pris lavere brukes markedsverdi. Kjøp/eierskap må dokumenteres.','§5.3.6 fysisk s10','super')
r('Unntak','vær og gradvis','Konstruksjon, materialtretthet, råte/korrosjon; nedbør/snøis/frost, også medvirkende. Isberøring i boblehavn og frost etter ytre landstrømfeil unntatt fra unntaket.','§6 fysisk s11')
r('Unntak','isolert motor og seil','Motor alene bare ved oppgitte brann/tyveri/kaskohendelser; seil alene ved vind ikke dekket. Ingen generell maskinbrudddekning dokumentert.','§6.18–19 fysisk s11')
r('Unntak','bruksområde','Motorhastighetsregatta, yrke/utleievirksomhet uten særavtale; erstatning under garanti/ansvarlig tredjepart unntatt, men fallback når krav ikke fører fram og ellers dekket skade.','§6 fysisk s11')
r('Sikkerhet','plikt','Sjødyktighet/vedlikehold/tilsyn; bunnventiler stengt nov–mars; låst utstyr, innelagring motor under 40 hk, brannslokker og lagring/transportforskrifter.','§7 fysisk s12–13')
r('Ung fører','tilleggsegenandel','10000 ekstra dersom rabatt for ingen fører under 24 år og skade med yngre fører.','§7 fysisk s12')
r('Reparasjon','oppgjør','Reparasjon og likeverdige deler/selskapets verksted; forbedringsfradrag; eget arbeid 50%, MVA etter dokumentasjon, ikke verdiforringelse.','§8 fysisk s14–15')
r('Aldersfradrag','tabell','Drev/undervannshus 3 frie år deretter 10% maks50; rigg 5/5%/60; kalesje 2/10%/80; PC/navigasjon 1/10%/80; annen elektronikk 1/10%/50. Demontering/montering holdes utenfor.','§8.3 fysisk s15')
r('Ansvar','sum','3020000 SDR person og1510000 SDR ting; ikke NOK.','§9.1 fysisk s16')
r('Ansvar','egenandel og unntak','0 med mindre beviset sier annet; ikke forsett/familie/sameier/leide-lånte ting/transport/yrke/motorregatta/utvidet kontraktansvar.','§9 fysisk s16–17')
r('Vrak','dekning','Ubegrenset ved dekket skade; offentlig krav, fare, sjenanse/forsjemmelse etter vilkåret.','§5.1/§9 fysisk s4/16')
r('Rettshjelp','sum egenandel','100000 og økonomisk interesse; 3–10 parter250000,11–25 500000,26–49 750000,50+1000000. 4000+20%rest. Norden.','§10 fysisk s17–19')
r('Rettshjelp','vilkår','Eier/bruker/båtsalgstvister, også etter totaltap; ingen føravtaletvist, yrke/familie/straff, sameiere eller salær; kostnadsbegrensninger/forhåndsgodkjent sakkyndig.','§10 fysisk s17–19')
r('Ulykke','summer','100000 død,200000 voksen invaliditet,500000 barn under18; samlet1000000 per skadetilfelle. Ikke behandlingsutgifter.','§11 fysisk s20–22')
r('Ulykke','vilkår','Lovlig ombord ikke betalende/utleie; utenfor bare båt direkte årsak; død innen2år, invaliditet etter grad/forutgående funksjon; ingen sykdom/psykisk/forsett/arr<15%.','§11 fysisk s20–22')
r('Tilbud','valg og fordeler','Valgfri egenandel6000/8000/12000/16000; bevis styrer, spesialsatser. Kunde-/nettrabatt og båtvakt-tilbud er kjøpsforhold ikke nye ubetingede dekninger.','HTML egenandeler/fordeler','all','web')
r('IPID','oversikt','Delkasko/Kasko/Super; bagasje under Kasko i kortliste men fullvilkår+web uttrykkelig Delkasko, ikke bevis for eksklusjon. IPID totalforsvinning krever registrering mens fullvilkår godtar kjøpekontrakt.','IPID s1–2','all','ipid')
r('Generelt','administrasjon','Generelle Storebrandvilkår tidligere lest og gjenbrukt; varsling/skadeoppgjør/frister uten eget nytt sammenligningskonsept.','Generelle vilkår 11 sider')
save('storebrand-boat-independent-inventory.json',dict(source_first=True,rules=R,review='Alle22 fullvilkårsider båt03/1.9.2024, begge IPID-sider og hele produktsidens materialinnhold lest; general11 sider gjenbrukt. Inventaret ferdig før supplerende catalog-matching.'))
print(len(R))
