from continue_audit import save
R=[]
def r(scope,sub,dim,val,loc,src):R.append(dict(id=f'TR-BIL-{len(R)+1:03d}',scope=scope,subject=sub,dimension=dim,value=val,location=loc,source=src))
r('all','Ansvar','sum','Ubegrenset personskade;100millannen skade.','1 §1.1','ansvar')
r('all','Ansvar','utland','Skadestedetslov;Norskfører/passasjerfastbosattNorgehøyerenorskregel.','1 §1.1','ansvar')
r('all','Rettshjelp','status','Inkludert henvisningPGE91500.','1 §1.2','ansvar')
r('all','Rettshjelp','sum','100k/tvist;250k3ellerflereparter;20ktvistmotTrygomrettshjelp;økonomiskinteressebegrenser.','4 §6.1','legal')
r('all','Rettshjelp','egenandel','4k+20%overskytende,énpertvist.','5 §6.2','legal')
r('all','Rettshjelp','område/rolle','Norden,eier/rettmessigfører/bruker,ettersalgtvistogdirektepersonskadefører.','1 §3.1;2–3 §5.3','legal')
r('all','Rettshjelp','unntak','Ikkeannetkjøretøy/yrke/familie/sameiere/straffmedenfornærmetunntak/idømtkost;fullvilkår5.5.','1 §2.1;3–4 §5.5','legal')
r('physical','Utstyr','grense','Fastmontert/foliering10k;ekstrastandarddekksettinkl;spesiallakkikke,ikkeavtagbartutstyr/tilhenger.','1 §1','physical')
r('physical','Brann','omfang/egenandel','Åpenflamme/lyn/eksplosjon,6khvisikkelavereavtalt.','Delkasko1§2.1;Kasko2§2.2','physical')
r('physical','Tyveri','omfang/egenandel','Tyveri/brukstyveri/deler,tyveriforsøk/hærverk,6khvisikkelavereavtalt.','Delkasko1§2.2;Kasko2§2.3','physical')
r('physical','Glass','omfang/egenandel','Ruterinklglasstak,3kbytte/0reparasjon;avtaleverksted,EUtilstandkrav.','Delkasko1§2.3;Kasko2§2.4','physical')
r('physical','Veihjelp','persontransport','Skade/tyveriikkeutbedretraskt;hjem/videremaxhjemkostrimeligst;førersykdom/ulykke/dødpassasjerer.','Delkasko1–2§2.4;Kasko2§2.5','physical')
r('physical','Veihjelp','utløser/mål','Skade/utelåst/start/driftsstopp/tomdrivstoffstrøm;bilogtilhenger,nærmesteverksted,henting.','Delkasko2§2.4;Kasko2§2.5','physical')
r('physical','Veihjelp','tak/egenandel','Maks50%kjøretøyverdi;750egenandel.','Delkasko2§2.4;Kasko2–3§2.5','physical')
r('physical','Veihjelp','unntak','Ikkehaikere/annenavtale/garanti/redningsabonnement/utenveitilknytning.','Delkasko2§2.4;Kasko2§2.5','physical')
r('physical','Oppgjør','kontant/forbedring','70%takstutenMVAvedkontantreparasjon;ingenleiebil;slitasjeforbedringfradrag,markedsverdiførtotal.','Delkasko2–3§3;Kasko3§3','physical')
r('physical','Garanti','reparasjon','8årkarosseri,3årbruktmotorvedservice;mekaniskforhandlergaranti,slitedelerunntatt;starterutlevering,følgerbil,2mndmeldemangel.','Delkasko2–3§3.2;Kasko3§3.2','physical')
r('physical','Elektronikk','aldersfradrag','Fastmontert elektronikk10%perårfra nytt,maks50%;nyverdipåskadedagen.','Delkasko3§3.3;Kasko4§3.3','physical')
r('kasko','Kasko','utløser','Sammenstøt/utforkjøring/velt/hærverk/feilfylling/ytreplutselig<=1d/uventet;ikkemaskinbrudd/frost.','1 §2.1','kasko')
r('kasko','Ungfører','egenandel','Under23år+5k,unntatthovedeier/samboerektefelle/2000kmTryglappen;godkjentbane+20k.','1 §2.1','kasko')
r('kasko','Dyr/vær','egenandel','Dyrpåkjørsel2kutenbonusveddokumentertpolitiviltnemnd;værgarasjeparkert0egenandel.','1 §2.1','kasko')
r('kasko','Nyverdi','grenser','Innen1årnyregistrertpåtaker;reparasjon>80%nyverdi,ikkeover15kkm.','4 §3.4','kasko')
r('kasko','Nyverdi','form/vilkår','Nybiltilsvarende;utgåttmodellkjøpekontrakt;tyveriikkeigjen3uker;kontantalternativ;leasingunntatt.','4 §3.4','kasko')
r('extra','Ekstra','tilvalg','Bil/ElbilEkstraertilleggtilKasko.','1 §1','extra')
r('extra','Parkertskade','bonus/alder','Uk jentskadevolder,avtaleverksted,innen6årførstregistrert;normalKaskoegenandel.','1 §1','extra')
r('extra','Utstyr','samletgrense','Fastmontert+ekstradekkfelgerikke-standard samlet50k/sammehendelse;folieringmed,ikkeavtagbart.','1 §1','extra')
r('bil-extra','Feilfylling','rens','15kmotorrens/1kegenandel.BilEkstraspesifikt,ikkeimporttilElbilEkstra.','1 §1','bil-extra')
r('extra','Leiebil','periode/type','TilsvarendebilstørrelsemaksVWID4,ubegrensetkm,normalreparasjonmax60d.','1 §1','extra')
r('extra','Leiebil','kondemnasjon/tyveri','60dfratyverimeldt;14detterkondemnasjonsbeskjed,likevelmax60d.','1 §1','extra')
r('extra','Leiebil','naturulykke','Bruttveiforbindelsehindrerbiltilgang,inntil10d.','1 §1','extra')
r('extra','Leiebil','kvalifikasjon/unntak','Dekket skadeoveregenandel,leverandørformidlet;ikkeglassalene/nøkkel/ordinærkontant;ikkebøter/leieskade/egenandel/drivstoff/lading/parkering/bom/dropoff.','1 §1','extra')
r('extra','Bagasje','sum/egenandel','Tyverifra bil/låstboks10ksamlet5k/gjenstand1kegenandel;ikkenæring/penger/papir/dyr;trafikk/brannviaansvar.','1 §1','extra')
r('extra','Nøkkel','årstak/egenandel','Bilnøkkelogkupevarmerfjernkontrolltap/skade20k/forsikringsår,1kegenandel.','1 §1','extra')
r('extra','Ladekabel','fare/egenandel','Brann/tyveri/ytreplutseliguventetskade1kegenandel.','Bil1/Elbil2 §1','extra')
r('extra','Totalskade','alder/km/terskel','Innen3årnyregistrertpåtaker,maks60kkm,>80%nyverdi.','2 §1','extra')
r('extra','Totalskade','tilleggsytelse/form','Nybilmodellnivåårgang;abonnement/serviceavtalekjøretøyverdi10k;utgåttmodellkontrakt,3uketyveri/kontant.','2 §1','extra')
r('extra','Leasing','startleie','Totalskade/totalforsvinninggjenståendestartleieproporsjonetterrestperiode.','2 §1','extra')
r('motor','Maskinskade','tilvalg/grenser','TilleggKasko;200kkmellerutperiodenbilenblir10årførst;aldersidenførstereg.','1 §1','motor')
r('motor','Maskinskade','komponenter','Motor/gir/drivlinje/elektronikk/styring/AC/varme/sikkerhetkomfortliste;EVhøyvoltbatteri/ladekontakt/onboardlader.','1–2 §1','motor')
r('motor','Maskinskade','delgrense','Eksos/katalysator/partikkelfilter/dobbeltmasse/clutchbareinntil100kkm.','1 §1','motor')
r('motor','Maskinskade','egenandel','Inntil120kkm10k;120–160k14k;160–200k18k.','2 §1','motor')
r('motor','Maskinskade','unntak','Ikkelavvoltbatteri/mansjettalene/luftfjær/slitasje/korrosjon/modifisert/leasedEVbatteriannetdekket/garantiansvarmedregressnårkravikkeførerfram/bodel.','2 §1','motor')
r('rental','Leiebil separat','kilderegler','PAU27008effective1Oct2026:VW e-up10dnormalreparasjonubegrensetkm,angittleverandør,ikkeglass/nøkkel/ordinærkontant;ingenbonustap. Eksaktaktivkatalogkoblingsjekkes.','1','rental')
r('accident','Ulykke','rolle/utløser','Fører/passasjer i/påkjøretøy,ogutenforhvisdirekteårsak;plutseligytrefysiskulykke.','1 §1–2','accident')
r('accident','Ulykke','sum/dødstid','200kmedisinskinvaliditetgradert,100kdødinnen1år.','1–2 §2.2/3','accident')
r('accident','Ulykke','unntak','PsykiskunntattmedPTSDunntak,ansiktsvansiringmed,spisetann/infeksjonmedsårunntak/matforgiftning/sykdomutelatt.','1 §2.3','accident')
r('accident','Ulykke','oppgjør','Tidligerefunksjon/sykdomfradrag;ingeninvaliditetveddødinnen1år;etter1årinvaliditet;delinvaliditetforholdsmessig.','2 §3','accident')
r('accident-extra','Ulykke Ekstra','sum','500kinvaliditet,under18år1mill;100kdødinnen1år.','1–2 §2/3','accident-extra')
r('accident-extra','Ulykke Ekstra','sykehus','5kengangsbeløpperskadetilfellevedmin48tsammenhengendeinnleggelse.','1–2 §2.3/3.3','accident-extra')
r('accident-extra','Ulykke Ekstra','vilkår','Sammerolleulykke/unntakoggradertinvaliditet/tidligerefunksjon/1årdødregelsomPAU28003.','1–2 §2–3','accident-extra')
r('all','Felles egenandel','samtidighet','Sammehendelseiflereselskapetsforsikringerkunhøyesteegenandel.','2 §2.3','general')
r('all','Generelt','hovedunntak','Krigkjemi/atom/jordskjelvvulkan;fredeligavreiseutlandkrig1månedunntak;terror500millhendelse1mrdårligaggregertselskap.','3–4 §5','general')
r('all','Administrasjon','øvrig','Oppsigelse/garantiordning/skjønn/personvern/valutaadministrasjonkildebeholdt,ikkebehovegenproduktrad.','1–5','general')
r('all','Bonus','nivå','Ansvarbonustap;Delkaskoskaderikkebonus;Kaskokun§2.1minusdyrvilkår;alleundersøktetilleggutbetalingaleneikkebonustap.','sistekapitler','ansvar')
save('tryg-bil-independent-inventory.json',dict(source_first=True,originals='All9localBiloriginals+explicitlyreferencedsharedPGE91500/PGE91000read. PAU27008Octoberdatepreserved,noonlinefreshnessclaim.',rules=R))
print(len(R))
