from continue_audit import *
rows=[]
def r(s,d,v,doc,loc,scope='all'):
 rows.append(dict(id=f'TRE-{len(rows)+1:02d}',subject=s,dimension=d,value=v,doc=doc,location=loc,scope=scope))
r('Personkrets','eligibility','FastbosattNorge/folketrygd;enkelt/par/familie;barnadressehosforelderunder21;IPIDtil21 vswebutåret21ogbarnebarnreisemedkonflikt.','IPID-Reiseforsikring.pdf','s1;webFAQ')
r('Reiselengde','standard_conflict','Reise45,Premium70;Ekstra45tabell/hovedFAQ og70senereFAQ. Bevisavtalt;ikkevelgénutenavklaring.','Reiseforsikring-produktside.html','Reisedager;FAQbackpacking/borteboendebarn')
r('Reiselengde','optional_extension','Utvidet enkeltreiseinntil12mnd måavtales;ikkeautomatiskbase.','Reiseforsikring-produktside.html','FAQhvorlenge')
r('Reisedefinisjon','overnight_purpose','Reisebarefritidmedovernatting;Ekstra/Premiumfritid+tjenestereisermed/utenovernatting.','Reiseforsikring-produktside.html','Reiserutenovernatting/FAQ')
r('Geografi','excluded_places','Verden,ikkefast/midlertidighjem,fastarbeid/skole/SFO/barnehage;fritidsarrangementunntak.UDadvarselvedavreiseugyldighele reisen.','PRF46000-Produktvilkar.pdf','s1–2§3')
r('Reiseperiode','extension','Fra hjemNorge tilbake;forhåndsbestilthjemreiseutvides2dvedvær/teknikk/nødlanding/terror,30dveddekketsykdom/ulykke.','PRF46000-Produktvilkar.pdf','s2§4')
r('Avbestilling','timing','Aktivforsikringførførsteinnbetaling;avbestillingsdekningfrakjøptilavreisehjem.','PRF46000-Produktvilkar.pdf','s2§4;PRF46001s1§2.1')
r('Avbestilling','triggers','Akuttsykdom/alvorligulykke/uventetforverring/dødselv/nærfamilie/følge/enestemedreisendesfamilie;offentligsavnetsøk,flyttetfastsattoperasjon,fysiskboligskade,naturkatastrofe/UD.','PRF46001-Reise-Reise-Ekstra.pdf','s1–2§2')
r('Avbestilling','limits','Reise20 000pertilfelle/sikret;Ekstra/Premiumubegrenset.','Forsikringssummer-08.2026.pdf','s1')
r('Avbestilling','exclusions','Ikkeformålsbortfall,forlengetbehandling,karantene/frykt;UDvedbestilling,senerepåløpteutgifter,refusjon/bonus,skatt,tjeneste,andrepersoner,sesongleie/timeshare.','PRF46001-Reise-Reise-Ekstra.pdf','s2§2')
r('Forsinkelse','triggers_conditions','Forhåndsbestiltoffentligavgang/fremmøte;sistelokalrute;vær/teknikk/kollisjon/utforkjøring/nødlanding/terror.Innhenting/overnatting;nybillett nårarrangørikketarigjeninnen24h.','PRF46001-Reise-Reise-Ekstra.pdf','s2–3§3.1')
r('Forsinkelse','limits','Avgang1 500/3 000/3 000;fremmøte20 000/ubegrenset/ubegrenset,herunderovernatting1 500/3 000/3 000.','Forsikringssummer-08.2026.pdf','s1')
r('Tapt arrangement/hotell/leiebil','thresholds_limits','Ekstra/Premium1hotellnatt/arrangement5 000ettermin5h;forhåndsbetaltkansellertbil8 000ettermin1,5h. Reiseikke.','PRF46001-Reise-Reise-Ekstra.pdf','s3§3.2;sumtabells1','higher')
r('Forsinkelse','exclusions','Ikketjeneste,streik/personalmangel,privatbilutleier/annetkjøretøy/andrebrukere;EUrefusjonunntattmenfallbacketter24hutenalternativreise.','PRF46001-Reise-Reise-Ekstra.pdf','s3§3.3')
r('Bagasjeforsinkelse','trigger','Ekspedertikkeankommet;forbyttet4h;transittufrivilligovernatting.PIR/kvittering,innkjøpførsavnettilbake;ikkesistehjemflyplass/streik/refusjon.','PRF46001-Reise-Reise-Ekstra.pdf','s3–4§4')
r('Bagasjeforsinkelse','limits','Reise2 000/EkstraPremium5 000;transitt500 innen sum.','Forsikringssummer-08.2026.pdf','s1')
r('Reisegods','scope','Egne/hele-reisenlåntleidpersonligeting;tyveri/ran/innsjekket/tap21d/dyrikkeegne/trafikk/båtuhell/brann/vann/natur/hærverkikkefamilieellerlåntbruker.','PRF46001-Reise-Reise-Ekstra.pdf','s3–4§4')
r('Reisegods','limits','Reise20 000og6 000/itemmedtilbehør;Ekstra/Premiumingenoverordnetmax,40 000/itemmedtilbehør.','Forsikringssummer-08.2026.pdf','s1')
r('Reisegods','special_limits','Nøkler4 000alle;kontanter3 000/6 000samletallesikrede;pass/billettinklreise/opphold5 000/20 000samletalle.','Forsikringssummer-08.2026.pdf','s1')
r('Reisegods','material_exclusions','Ikke mistet/glemt,sykkelhjem/arbeid/studiekommune,arbeidsgiver/skoleeiendom,lokaltleidutstyr,motorvogner,verdipapir/data,indirektetap.','PRF46001-Reise-Reise-Ekstra.pdf','s4§4.1')
r('Uhell','trigger_limits','Ekstra/Premium8 000/år,1 500egenandel/tilfelle;ytrekjentårsakbestemttid;gjenstandmåvises;ikke mistet/glemt.','PRF46001-Reise-Reise-Ekstra.pdf','s4–5§4','higher')
r('Reisegods','settlement','Verditapfradragmin1/3;Trygvelgerreparasjon/ombruk/kontant;gave/arv/brukt/kunst/samlinger/bo markedsverdi.','PRF46001-Reise-Reise-Ekstra.pdf','s5§4.2')
r('Mobil','repeated_deductible','Fraandre tap/skadeinnen3forsikringsår2 000egenandel.','PRF46001-Reise-Reise-Ekstra.pdf','s5§4.2;sumtabells1')
r('Reisesyke','trigger','Uventetakuttsykdom/ulykke/alvorligforverring;fødselsuke37+/svangerskap/frivilligabortikkesykdommenulykke/sykdomkanværedekket.','PRF46001-Reise-Reise-Ekstra.pdf','s5§5.1')
r('Reisesyke','hospital_duration','Sykehusinntil60d;behandling/oppholdtilhjemtransportmedisinskforsvarlig;lege/medisin/fysio/transport.','PRF46001-Reise-Reise-Ekstra.pdf','s6§5.2')
r('Reisesyke','limits_companions','Samletingenmax;Reisetilkalling/ledsager30 000herunder1 500/dag;Ekstra/Premiumingenmax;inntil2nærstående,medisinskbehov/forhåndsgodkjent.','PRF46001-Reise-Reise-Ekstra.pdf','s6§5.2;sumtabells1')
r('Familie syk på reisemål','duration','Alvorlighendelsenærfamiliebosattreisemål14dmeropphold/mat+hjem;godkjennes.','PRF46001-Reise-Reise-Ekstra.pdf','s6§5.2')
r('Eneste medreisende syk','limits','Reise15 000herunder1 500/dag;Ekstra/Premium35 000;barnunder21medforeldererikkemedreisendemenfamilieytelsenkaninkluderebarn.','PRF46001-Reise-Reise-Ekstra.pdf','s6–7§5.3;sumtabells2')
r('Hjemtransport','scope','Ubegrenset;akuttalvorligsykdom/død/familiesavnetoffentligsøk/boligskade/nærfamilie,tidligereennplanlagt,forhåndsgodkjent. Barnunder21/beggeforeldremedsyktbarn;ikkemellommidlertidigogfasthjem.','PRF46001-Reise-Reise-Ekstra.pdf','s7§5.4;sumtabells2')
r('Reiseavbrudd','limits_conditions','Ekstra/Premium1 500/dag perperson;forhåndsbetaltkostnadforholdubenyttedager;sykehus/hjemtransport/evakuering/enesteledsager.EttfamiliemedlemhvisbeggeTryg;ikkehjemreisedag/tjeneste/forlangplanlagtreise/bonus/timeshare.','PRF46001-Reise-Reise-Ekstra.pdf','s7–8§5.5;sumtabells2','higher')
r('Reisesyke','exclusions','Kjentforutsebarforverring/planlagtbehandling,etterreisen,tannskade/sykdom,lete/redning,høydesyke;tilkallingikkegenhjem/arbeid/studiekommune.','PRF46001-Reise-Reise-Ekstra.pdf','s8§5.6')
r('Evakuering','conditions','UbegrensetmerutgiftervedUDevakueringsråd,førstemulighet,tilsikkertsted/Norden;ikkekjent/varsletsituasjonvedinnreise,refusjon,utenbestiltretur.','PRF46001-Reise-Reise-Ekstra.pdf','s8§6;sumtabells2')
r('Leiebilegenandel','scope','Ekstra/Premium40 000;bilfrautleiefirma,påferiemedmin1overnatting;ikkedeling,verkstedbil,flytting/varehenting,annetkjøretøy.','PRF46001-Reise-Reise-Ekstra.pdf','s8–9§7;sumtabells2','higher')
r('ID-tyveri','service_limits','Premium25 000juridiskbistandgodkjentnåradministrativhjelpikkelykkes;identitet/sosialemedieroppdaget+anmeldt;ikkeøkonomisktap/nyID/næring/familiekrim/rettssak.','PRF46003-Reise-Premium.pdf','s9§8','premium')
r('Privatansvar','sum_territory','Reise4mill,EkstraPremium15mill perhendelsealle;utenforNorden;sumtabellAug2026giraktivebeløp selvfellesvilkår01.10fremtidig.','Forsikringssummer-08.2026.pdf','s2;PRF46000s2')
r('Rettshjelp','duration_scope','UtenforNordenførste45dferieReise/Ekstra,70dPremium;egenreisevarighetsutvidelseutvidesikkeautomatiskher.','PGE91500-Rettshjelp.pdf','s2§5.1')
r('Rettshjelp','sum_deductible','100 000pertvist;250 000min3parter;20 000Trygtvist/økonomiskinteressetak;4 000+20%.','PGE91500-Rettshjelp.pdf','s4§6;sumtabells2')
r('Egenandel','selected_options','Reise1 000;EkstraPremium0eller1 000valg,særreglermobil/uhell/rettshjelpbevares.','Reiseforsikring-produktside.html','FAQegenandel')
r('Tryg Legehjelp','service','Ekstra/Premiumerfarnenorskelege/sykepleier365dforfamilie;akuttreiseTrygAlarm24/7.','IPID-Reiseforsikring.pdf','s1;webLegehjelp')
r('Lounge','service_conflict','PremiumSmartDelayregistrertfly>1time,5medreisende/40eurutenlounge;annenboks4medreisende.','Reiseforsikring-produktside.html','Lounge-tabell/nyttiginformasjon','premium')
r('Ulykke','included_optional','ReiseUlykkeogEkstraUlykkeEkstravalgbare;PremiumUlykkePremiuminkludert.','PRF46000-Produktvilkar.pdf','s1§2')
r('Ulykke','invalidity_sums','Til69:Ulykke300 000/Ekstra500 000/Premium750 000;fra70alle100 000utåret80;ingenyrkesinntektvurdering.','Forsikringssummer-08.2026.pdf','s3','accident')
r('Ulykke','death_sums','Til20:50 000/100 000/100 000;21–69:150 000/500 000/750 000;fra70alle100 000utåret80.','Forsikringssummer-08.2026.pdf','s3','accident')
r('Ulykke','treatment_limit','5%invaliditetssum;innen3år;under18permanenttanntilførstebehandlingkanutsettesselv3år,oppgjørvilkår;ikkeprivatklinikk.','PRF46010-Ulykke-Ulykke-Ekstra.pdf','s2–3§3.2;PRF46012s2–3;sumtabells3','accident')
r('Ulykke','threshold_death','Varigfra1%hvisikkeannetavtalt,tidligereinvaliditetfratrekkes;dødinnen1årellersikkedødserstatning;dødinnen1åringeninvaliditetutbetaling.','PRF46010-Ulykke-Ulykke-Ekstra.pdf','s1–3§§2–3;PRF46012samme','accident')
r('Ulykke','exclusions','Plutseligytrefysisk;ikkesykdomsbesvimelse,behandling,spisetann,matforgiftning,infeksjonstikkunntattsår/blod;PTSDetterulykkediagnosertfagspesialistunntakpsykiskeksklusjon.','PRF46010-Ulykke-Ulykke-Ekstra.pdf','s1§2.1;PRF46012s1','accident')
r('Ulykke','occupation','Yrkesskaderikkeunntattlandkontor/litenaktivitet,menoffshore/sjø/luft/sprengstoff/transport/lager/håndverk/landbrukalltidunntatt.','05000PF455-Sikkerhetsforskrift.pdf','s3§3.2','accident')
r('Risikoaktiviteter','age_scope','Base/strikkhopp,kampsport,motorsport,proff≥1G,dykkingutensertifikat,rus,ekspedisjonunntatt;ikkeunder16;lagidrett/sykkelrittkunreisegods.','05000PF455-Sikkerhetsforskrift.pdf','s2§3.1')
r('Reisegods','safety','Ingenbil/båt/telt/campingvognoppbevaring24–06;verdisakerbæres/safe,tyveriutsattikkeetterlates,elektronikk/verdi/skjørtikkesjekkesinn.','05000PF455-Sikkerhetsforskrift.pdf','s1§1.2')
r('Medisinsk sikkerhet','approval','Kontaktalarmsykehus/utgifter>5 000;skriftliglegeførreisekjentbehandling;godkjennhjemtransport/utsettelse.','05000PF455-Sikkerhetsforskrift.pdf','s2§2')
r('Fellesunntak','strike_bankruptcy','Streik/lockout/arbeidskonfliktogkonkursøkonomisktapikke.','PRF46000-Produktvilkar.pdf','s2§5')
r('Egen bil','mileage_compensation','3,50kr/km nårdekningomfatterprivatbilkjøring;ikkeubetingetkjøretøykostnad.','Forsikringssummer-08.2026.pdf','s1,3')
save('tryg-reise-independent-inventory.json',dict(source_first=True,rules=rows,rule_count=len(rows),notes=['Alle13lokaleoriginalerread/sharedhashreuse. WebFAQinternekonflikterbeholdes;tabellseparateenheter.']))
print(len(rows))
