from continue_audit import *
rows=[]
def r(s,d,v,doc,loc,scope='both'):
 rows.append(dict(id=f'THU-{len(rows)+1:02d}',subject=s,dimension=d,value=v,doc=doc,location=loc,scope=scope))
r('Forsikringsform','scope','Bygning fullverdi som standard, førsterisiko hvis bevis; Ekstra fullverdi. Særgrenser før bevisbeløp.','05PPK11501.pdf','s1;11502s1')
r('Bygning','art','Kunstnerisk utsmykning ikke Basis, inkludert Ekstra.','05PPK11501.pdf','s1§1.1;11502s1')
r('Rør','insured_property','Inn-/utvendige rør, unntatt basseng/brønn/borehull/drens/infiltrasjon/spredeledning; drens likevel brann/natur.','05PPK11501.pdf','s1§1.2;11502s1')
r('Hage','sum_scope','Basis500 000, ingen slik grense brann/natur ved bolighus/våningshus; Ekstra ingen særgrense. Basseng fastkoblet medregnes, brygger ikke.','05PPK11501.pdf','s1§1.3;11502s1')
r('Brygge','sum_perils','Flytebrygge/trebrygge100 000 kun brann/natur; høyere sum krever bevis.','05PPK11501.pdf','s1§1.3;11502s1')
r('Endringer','automatic_cover','Ny garasje/naust/uthus/tilbygg på stedet dekket fra oppføring til neste fornyelse selv ikke i bevis; meldes.','05PPK11501.pdf','s2§1.4;11502s1')
r('Riving/rydding','additional_expenses','Nødvendige merutgifter; ved førsterisiko20%sum. Kommer i tillegg til avtalt sum.','05PPK11501.pdf','s2§1.5;11502s1')
r('Offentlig påbud','sum','Basis2mill per tilfelle /førsterisiko20%max2mill; Ekstra ingen særgrense unntatt fredet bygning1mill.','05PPK11501.pdf','s2§1.5;11502s2')
r('Offentlig påbud','conditions','Kun skadeutløste påbud/skadet bygningsdel; ikke kjellerutgraving eller krav som kunne stilles uten skade; fem år gjenoppføring.','05PPK11501.pdf','s2§1.5,s7§3.6;11502s2,7')
r('Ubeboelighet/leietap','duration','Normal reparasjonstid, markedspris umøblerte rom, sparte utgifter/renter trekkes. Korttidsleieinntekter ikke omfattet.','05PPK11501.pdf','s2§1.5,s7–8§3.7–3.8;11502s8')
r('Prisstigning','duration','Normal reparasjon/gjenoppføring etter SSB, tillegg til sum.','05PPK11501.pdf','s2§1.5,s8§3.9;11502s8')
r('Klimatiltak','sum_trigger','Basis25 000/Ekstra50 000 ved fullverdi gjenoppføring og skade>75% av nybyggpris; utover offentlige krav, forhåndsgodkjent dokumentert energi/utslippsreduksjon.','05PPK11501.pdf','s2§1.6,s8§3.10;11502s2,8')
r('Rullestoltilpasning','sum_conditions','250 000 samlet alle sikrede per tilfelle; ulykke eller medfødt≥50%varig invaliditet; kostnad innen5år,0egenandel.','05PPK11502.pdf','s2§1.10,s8§3.11','extra')
r('Brann/elektrisk','coverage','Løs ild/elektrisk/lyn; ikke svi/gnist uten brann/kosmetikk.','05PPK11501.pdf','s3§2.1–2.2;11502s3')
r('Alarm','deductible_reduction','Brann/vannalarm alarmsentral6 000 redusert egenandel. Skade kun alarm/overspenningsvern0egenandel.','05PPK11501.pdf','s3§2.1/2.3,s5§3.2;11502s3–5')
r('Vann','triggers','Rør/akvarium/slokker, utvendig rør eller åpning etter dekket skade; terreng må gi stående vann over laveste gulv.','05PPK11501.pdf','s3§2.3;11502s3')
r('Vann','standard_exclusions','Basis ikke annen tak-/nedbør-/kondens/sopp/råte-/utettvåtromskade eller våtrommet selv.','05PPK11501.pdf','s3§2.3','base')
r('Vannstopper/overvann','zero_deductible','0egenandel ved innvendig rørbrudd med automatisk ventil i bruk hele bygget; overvannstank/magasin/dam ved ekstremnedbør.','05PPK11501.pdf','s3§2.3;11502s3–4')
r('Gjentatt vannskade','deductible_progression','+20 000 ved tilsvarende skade siste36mnd fra terreng eller innvendige rør; Ekstra også flatt tak/balkong/terrasse.','05PPK11501.pdf','s3§2.3;11502s4')
r('Terrengvann','minimum_deductible','Minimum8 000.','05PPK11501.pdf','s4§2.3;11502s4')
r('Tak/vegg lekkasje','extra_scope','Ekstra plutselig lekkasje over bakkeplan og utettvåtrom følge på tilstøtende/underliggende rom; ikke tak/takgjennomføring eldre50år, selve tak/veggsjikt, vedlikehold, konstruksjonsfeil eller sopp/råte.','05PPK11502.pdf','s3§2.3','extra')
r('Våtrom','craftsman_conditions','Ekstra følgeskade på våtrom fra autorisert arbeid/konstruksjon/montering innen10år mens forsikring aktiv; ikke feil uten følgeskade, ufaglært/eget arbeid/kosmetikk/sopp/råte.','05PPK11502.pdf','s3§2.3','extra')
r('Rørbrudd','scope_deductible','Innvendige rør/utstyr; utvendige væskerør/tanker/pumper/elektriske ledninger; egenandel per bruddsted.','05PPK11501.pdf','s4§2.4;11502s4')
r('Rørbrudd','base_exclusions','Basis ikke takrenne/nedløp eller frosset utvendig rør uten fysisk brudd.','05PPK11501.pdf','s4§2.4','base')
r('Staking/rørinspeksjon','deductible','Ekstra første staking/TV-undersøkelse0egenandel.','05PPK11502.pdf','s4§2.4','extra')
r('Tyveri/skadeverk','scope','På stedet; ikke beboers skadeverk i utleid rom/kosmetikk.','05PPK11501.pdf','s4§2.5;11502s4')
r('Plutselig skade','base_exclusions','Basis ikke fundament/setning/jordtrykk/frost/tele/konstruksjon/montering/slit/dyr; isolerglassutett ikke omfattet; glassbrudd unntak fra fundament/dyr; hage flomlikt likevel.','05PPK11501.pdf','s4§2.6','base')
r('Plutselig skade','extra_exclusions','Ekstra ikke kjæledyr/insekter/råte/slit/kosmetikk eller håndverkerfeil selv; følge av faglært arbeid innen10år, bare nødvendig tilkomst til følgeskade. Hage dyr/frost/klima ikke, flomlikt likevel.','05PPK11502.pdf','s4§2.6','extra')
r('Vær/snø','deductible','Vind under storm/snø/takras minimum8 000; Basis sprengning på stedet min10 000.','05PPK11501.pdf','s5§2.6;11502s5')
r('Gjenoppføring','conditions','Samme sted/formål/eier eller ektefelle/samboer/livsarving innen5år. Nybyggkjøp ikke gjenoppføring; ikke estetisk matching av uskadde deler.','05PPK11501.pdf','s5–6§3.3;11502s5–6')
r('Gjenoppføring','alternative_settlement','Annet sted i Norge: verdiøkning over40%trekkes; annet formål: hele økning; andre eiere/ikke innen5år/utenforland:max markedsverditap; riving:materialsalgsverdi.','05PPK11501.pdf','s6§3.3.2;11502s6–7')
r('Totalskade bolig','purchase_alternative','Annen bolig samme formål/fylke innen2år; eks.moms og maxgammelmarkedsverdi; ikke påbud/prisstigning; rettighetshavere samtykker.','05PPK11501.pdf','s6§3.3.2E;11502s6')
r('Fullverdigaranti','condition','Ekstra totalskade ingen fradrag for verdiøkning ved nytt.','05PPK11502.pdf','s6§3.3.1','extra')
r('Aldersfradrag','tables','Utvendig ikkeplast/bunnledning20år→5%max80; tank/kum20→5%max100; varmepumpe/varmtvann/pumpe/elektronikk5→10%max100; annenvarme10→10%max100; hvitevarer/boblebad5→10%max80;solcelle20→10%max80.','05PPK11501.pdf','s7§3.4;11502s7')
r('Aldersfradrag','mechanism','Før egenandel, hele reparasjon, eldste del; ikke fullverditotalskade/brann/natur.','05PPK11501.pdf','s7§3.4;11502s7')
r('Isolerglass','deduction','Ekstra punktering10frie år så10%max100; kun punktering, ikke alt glassbrudd.','05PPK11502.pdf','s7§3.4','extra')
r('Hageoppgjør','plant_age','Gjenoppretting; plante som vanlig ung handelsvare.','05PPK11501.pdf','s7§3.5;11502s7')
r('Oppgjør','labor','Eget arbeid300/time; leverandørpriser, dokumentert betalt moms; selskapet velger metode/ombruk.','05PPK11501.pdf','s5§3.1;11502s5')
r('Sikkerhet','material_obligations','Autoriserte VVS/elektro, reklamer håndverker, tak/rørfeil raskt, rens vår/høst, stopp vann etter1mndubebodd, varme/snø, oljetank ute av bruk fjernes.','05000PF115.pdf','s1–2')
r('Utleie/fraflytting','risk_change','Utleie må avtales unntatt nærfamilie; fraflytting begrenser skade som skyldes den, brann/natur fortsatt.','05000PF115.pdf','s2§2')
r('Ansvar','temporal_scope','Privat eiendomsansvar Norden; PGE90020lokalt5mill/4 000 gjelder01.10.2026, etter frosset snapshot.','05PGE90020.pdf','s1–2')
r('Rettshjelp','sum_scope','100 000/tvist250 000min3parter;20 000Trygtvist;økonomiskinteressetak;4 000+20%;Nordeneiendom,salg/vissekjøp,ikkeannenfast eiendom.','05PGE91500.pdf','s2§5.2,s4§6')
r('Natur','scope','Brannforsikret hus/innbo; hage5dekar/vei innenområdet, flyte/trebrygge100 000ikkeandel;8 000deduct;ikkevær/frostsnø alene.','05PGE90010.pdf','s1–2')
r('Utleietillegg','limits','Skadeverk bygg/hage/innbo500 000;tyveri/underslag500 000 pertilfelle fra leietaker/gjester;ubetalthusleie6mndén gang/leietaker;utkastelse20 000;6 000deduct leietap3mndmin10 000.','05PPK11506.pdf','s1§§1–2','rental')
r('Utleietillegg','safety','Skriftlig avtale tvangsfravikelse14d;depositum/bankgaranti3mndførinnflytting;varsel14dettermislighold,retting14d,begjæring/meldingTryginnen6uker.','05000PF121.pdf','s1','rental')
r('Utleietillegg','settlement','Kosmetikk/vedlikeholdunntatt;bygningsreglervedbygg;innbomin1/3verdifallførfradrag,brukt/arvet/gavemarkedstak,300/time.','05PPK11506.pdf','s1–3','rental')
r('Råte/skadedyr','scope_sum','VISbolig/frittståendegarasje,ikke næring/landbruk/basseng;råte,nedbrytningfraaktivvann>1år,dyr,innvendigmus/rotter+skadeinsekter;ubegrenset hvis ikke bevisgrenser.','05PPK40502.pdf','s1§§1–2','rot')
r('Råte/skadedyr','major_exclusions','Ikke utvendigtreverk/dør/vindu/tak/fastinnredning vedråte/vann;ikkemugg,kjæledyr,forebygging,tetting,utilstrekkeligisolasjonutenpåvistfall;utvendig/bunnrør,dyrebrann/vann,terrengvann,konstruksjonsvann ikke.','05PPK40502.pdf','s1§3','rot')
r('Råte/skadedyr','time_scope','Ingen skadeutvikling før/etter avtale;skadedyrførstartkanunntaksvisdekkeshvisforrigebygningdekningvilledekket;samtykke førbekjempelse.','05PPK40502.pdf','s1§3,s3§4.3.3','rot')
r('Råte/skadedyr','deductible','Skade6 000/bekjempelse2 000 med mindrebevis.','05PPK40502.pdf','s2§4.2','rot')
r('Råte/skadedyr','loss_of_rent','Normalreparasjon/markedsleie,sparingtrekkes;skriftligleiekontrakt,godkjenterom;utenboutgift50%markedspris;flytting/lagringdekkes,ikkehjemmekontor.','05PPK40502.pdf','s2§4.3.1','rot')
r('Råte/skadedyr','equipment_age','5frieårforinnebygdmaskin/varmepumpe/varmtvann/boblebad,10forvarmekabel/annenvarme;10%påbegyntårmax80;eldstedel.','05PPK40502.pdf','s2§4.3.2','rot')
r('Råte/skadedyr','water_age','Tak/balkong>30år,rør>50,våtrom>20:50%skadekostnad,max200 000;eldste konstruksjon.','05PPK40502.pdf','s3§4.4','rot')
r('Råte/skadedyr','water_caps','Takvann200 000/skade600 000/år;kondenshvitevarer/varmepumpe50 000/skade100 000/år.','05PPK40502.pdf','s3§4.6','rot')
r('Råte/skadedyr','price_vacancy','Prisstigning24mnd;fraflyttingbare råte/skadedyr ikke langvarigvann;VISgodkjentegetarbeid250/time.','05PPK40502.pdf','s2§4.1,s3§4.5/4.7','rot')
r('Bygg under oppføring','scope','Egetfullverdi underbygging,materialerlossetinkl,flyttedatoBygning11501;utvendigledninger/kunstikke.','05PPK11503.pdf','s1§1.1','construction')
r('Bygg under oppføring','garden','Hage50 000,ikkegrensebrann/natur;flyte/brygge100 000brann;ekstrabryggevedbevis.','05PPK11503.pdf','s1§1.2','construction')
r('Bygg under oppføring','expenses','Hvis entreprenørikkeharforsikring:riving/rydding,leietap24mnd,brakke/bod,egetinnbo300 000.','05PPK11503.pdf','s1§1.3','construction')
r('Bygg under oppføring','water_pipe','Basisvannunntak;terreng8 000;likvannskade36mnd+20 000;rørtestetavfagkyndigforinnvendigbrudd.','05PPK11503.pdf','s2§2.3–2.4','construction')
r('Bygg under oppføring','theft','Skadeverkbygg/tyverifra brakke;ting kun tettbyggdørvindupåplass,veggerkledd,taklagt.','05PPK11503.pdf','s3§2.5','construction')
r('Bygg under oppføring','sudden','Basisunntakfundament/konstruksjon/slit/dyr;vind/snø8 000sprengning10 000;glassunntakbevares.','05PPK11503.pdf','s3§2.6','construction')
r('Bygg under oppføring','liability','Privat byggherreansvarutvidettilbygg/graving/sprengningpåstedet.','05PPK11503.pdf','s3§2.7','construction')
r('Bygg under oppføring','settlement','Samme5år/sted/formålbyggeregler;ikkeordinæralternativkjøpannenbolig;aldersfradragsamebasetabell;innboarbeid75%/egen200,timebygg300.','05PPK11503.pdf','s4–7§3','construction')
r('Bygg under oppføring','safety','Stoppventilstengtutenarbeid,frosttømming,brakkerasikretmotborttransport.','05000PF118.pdf','s1','construction')
r('IPID','extra_coverage','2022Ekstraoppsummerer punktertvindu,utvendigrørtining,dyr,klimatiltak;råteskadedyrtilvalg. Fyll ikkeubetingededyre-ellerklimapåstander fra kortarket.','IPID-Hus.pdf','s1')
save('tryg-hus-independent-inventory.json',dict(source_first=True,rules=rows,rule_count=len(rows),all_sixteen_sources_read=True));print(len(rows))
