from continue_audit import save
R=[]
def r(typ,scope,sub,dim,val,src,loc):R.append(dict(id=f'TR-PET-{len(R)+1:03d}',type=typ,scope=scope,subject=sub,dimension=dim,value=val,source=src,location=loc))
r('both','base','Geografi/sikrede','område','Europa;taker/ektefelle/samboersammefolkeregisteradresse.','product','1 §1/3')
r('both','base','Alder/opphør','behandling','Fra35dagertilhelelivet;selgesavhendesslutterstraks.','product','1 §4')
r('both','all','Karenstid','20dogunntak','20dsykdomfraoppstart/sumøkning/utvidelse;ikkeekvivalentflyttingsammeeier;ingenvalpekullventetid/valpoverlevertmedTrygkull.','product','1 §4')
r('both','base','Veterinær','omfang','Sykdometterførstesymptom/ulykkeplutseligytrefysisk;undersøkelse/behandling CT/MRmedrekvisisjon.','treatment','1 §2/3')
r('both','base','Medisin/fôr','egenandelmekanisme','Veterinærordinertmedisin/legemiddel/spesialsjampo/spesialfôr;sisteto50%utgift. Ikkeegenandel50%generelt.','treatment','1 §3')
r('both','base','Avlivning','behandling','Anbefaltavveterinærdekkes;ikke kremasjon/etterutgifter iBehandling.','treatment','1 §3')
r('both','base','Tenner','ulykkesskade','Trekkavfrakturvedulykke;ikketann/tannkjøttsykdomogandrentannbehandling.','treatment','1 §3')
r('dog','base','Fødselshjelp','kvalifikasjon','Uavhengigårsakkenhundetter18mnd,veterinærbekrefterlivifare;ikke keisersnittEngelsk/Franskbulldog/Bostonterrier/Chihuahua/Pomeranianogblandinger.','treatment','1 §3')
r('cat','base','Fødselshjelp','kvalifikasjon','Veterinærbekrefterlivifare,ingen18mndellerhundraseunntak.','treatment','1 §3')
r('dog','base','Ledd/skjelett','kvalifikasjon','HD/AD/AA/OCD/patella/shortulna/CalvéLeggPerthes kreversammenhengendedekningfra før4mndsammeellerannet selskap.','treatment','1 §3')
r('cat','base','Ledd/skjelett','kvalifikasjon','HD/CalvéLeggPerthes kreversammenhengendedekningfra før4mnd;ikkekopierhundenslistetilkatt.','treatment','1 §3')
r('both','base','Unntak','vesentlige','Reise/transport/forebyggende/kryptorkisme/navlebrokk/kastreringsteriliseringmedunntakkjønnsorgansykdom/tidligereskader/sykdomutelatt.','treatment','1 §3')
r('dog','base','Rehabilitering','unavailable','Fysio/kiro/akupunktur/hydro/trykkbølgeunntattigrunn;Extraegenutvidelse.','treatment','1 §3')
r('both','base','Egenandel','fast/tilfelle','2.5k per sykdom/ulykkestilfelle;følgebesøkfor sammeårsakénskade.','treatment','1 §3;2 §4')
r('both','base','Forsikringssum','hendelse/år','Valgtbevis,sumpert sykdom/ulykke,allehendelsersamletårlig sammevalgtetak;ingenfastsumoppfunnet.','treatment','1 §1;2 §4')
r('both','all','Behandlingetteropphør','begrensning','Utgifteretteropphørerstattesikke selvomsykdomstartetiforsikringstid.','treatment','2 §4')
r('both','extra','Extra','tilleggsstruktur','Erstatningi tilleggtilBehandling;egnesummerogegenandeler,20d/ekvivalentflytteunntak.','extra','1–2 §3')
r('both','extra','Rehabilitering','sum/vilkår','Fysio/kiro/akupunktur/hydro/trykkbølge;rekvirertogdyreklinikk/autorisertbehandler;10k/sykdomulykke,2.5kegenandelpertilfelle.','extra','1 §2')
r('both','extra','Tenner','sum/egenandel','Tannskade/sykdom/tannkjøtt/melketenner/bittfeilmedmedisinskproblem;30k/sykdomulykkeOG30k/år;2.5kegenandelpertilfelle.','extra','1 §2')
r('both','extra','Tenner','vilkår','Tannsteinkunvedperiodontitt;melketenner/bittfeilkreverdekningfør4mnd.','extra','1 §2')
r('cat','extra','TR','årstak','Tannresorpsjon5k/årinnenodontologiens30k/år;ikkeheleproduktetsforsikringssum.','extra','1 §2')
r('dog','extra','Huggorm','egenandel','Undersøkelse/behandlinghuggormbitt0egenandel.','extra','1 §2')
r('both','extra','Valp/kattunge','sum/periode','Livreddendeavmorensungerførste10d;5k/unge10k/kull,0egenandel. Skiltfraegen12ukersValpekullprodukt.','extra','1 §2')
r('both','life','Liv','tilvalg/utløser','HundDød/RASEKATTDød,valgtbevis;sykdomulykkedød/nødvendigvetavlivning/tyveriforsvinning,ikkenåralternativbehandlinggirgodeprognoser.','life','1 §1/2')
r('both','life','Liv','leddvilkår','Før4mnduavbruttledddekningkrevesdødpåsammeartsdiagnosersombehandling.','life','1 §2')
r('dog','life','Kremering','sum','2kutoversum.','life','1 §2')
r('cat','life','Kremering','sum','1kutoversum.','life','1 §2')
r('both','life','Liv','unntak','Offentligkrav/atferd/psyke/temperament/preexisting/20dsykdomogøktbevisutelatt,medekvivalentflytteunntak.','life','1 §2')
r('dog','life','Forsvinning','ventetid','Politimelding+annonsering,tidligst30dettermeldtsavnet,ikkeetterlysingsutgifter.','life','1 §2')
r('cat','life','Forsvinning','ventetid','Annonsering,tidligst3mndettermeldtsavnet,ikkeetterlysingsutgifter;nettsideleggerpolitivilkårtil.','life','1 §2')
r('dog','life','Bruksverdi','vilkår','Varignedsattavl/bruketterakuttsykdomulykke;tispe3kull/hann5bedekninger;ferdigtrent/ferdighetogarbeidkonkurransesiste12mnd;under8år.','life','1–2 §2')
r('dog','life','Bruksverdi','sum','50%forsikringssum;utbetaltsumbortfallerfratrekksenerefalle død.','life','2 §3')
r('dog','life','Liv','aldersfradrag','Gjenanskaffelsesrasesumtak,20%årligfra7år,navngittstorefra5,navngittsmåfra9;min50%/min5k;0egenandel.','life','2 §3')
r('cat','life','Liv','aldersfradrag','Gjenanskaffelsesrasesumtak,20%årligfra7år,min40%,0egenandel.','life','1–2 §3')
r('both','life','Liv','opphør','Førsteforfall etter12år;ikkeautomatisk12årsdagsstopp.','product','1 §4')
r('both','base','FirstVet','tilgang','Ubegrensetgratisvideo07–24hverdag.','web','FirstVet')
r('both','base','Direkteoppgjør','tjeneste','Trygharikkedirekteoppgjør;flestesakergjøresoppstraks/påkontoinnen48timer,ikkeabsoluttgaranti.','web','Raskoggodhjelp')
r('dog','life','Liv','kildekonflikt','PLB52001småraseralder9vsweb10;foregåendeSC001bevares.','web','FAQ erstatninghunddør')
r('dog','base','Avlivning','kildekonflikt','Fulltermsdekkeravlivninganbefaltvet;webFAQlistesierikkeavlivning/offentligekrav;skalikkeslettefullvilkårspositiv.','web','FAQ dekkesikke')
r('both','base','Administrative','øvrig','Sikkerhetstell/opplysninger/oppgjørkildebeholdt;valpekull12uker/papegøyeutenforaktivtscope.','ipid','1–2')
save('tryg-pet-independent-inventory.json',dict(source_first=True,rules=R,note='Allsevenfullpetterms+twoHTML+IPIDread;PLB52000appliesbothspeciesdespitedogfilename;priorpartialfactsandSC001reused.'))
print(len(R))
