from continue_audit import *
# Independent inventory from full local sources, before reading exact resolved catalog.
rows=[]
def r(i,subject,dimension,value,doc,loc,level='both'):
 rows.append(dict(id='TIN-'+str(i).zfill(2),subject=subject,dimension=dimension,value=value,doc=doc,location=loc,level=level))
r(1,'Personkrets','household','Taker og ektefelle/samboer samme folkeregisteradresse og husstand, ikke bokollektiv; tredjepartsting ved avtalt risiko, ikke ren oppbevaring.','Produktvilkar_PPK13300.pdf','s1; PPK13301/2 §1.1')
r(2,'Geografi og flytting','temporary_location','Midlertidig borte i Norden; ny/gammel bolig ved flytting i inntil ett år; varig adresseendring må meldes.','Produktvilkar_PPK13300.pdf','s1')
r(3,'Forsikringssum','customer_choice','Avtalt sum; nyanskaffelser over sum frem til hovedforfall, skal meldes; særgrenser gjelder før valgt sum.','Innbo_og_losore_PPK13301.pdf','s1–2 §1.1; Ekstra samme')
r(4,'Yrkesløsøre','sum_location','Egne varer/løsøre i arbeid i forsikret bygning 50 000 / Ekstra 100 000.','Innbo_og_losore_PPK13301.pdf','s1 §1.1; Ekstra s1')
r(5,'Datarekonstruksjon','sum','10 000 / Ekstra 50 000 for manuskripter/tegninger/data.','Innbo_og_losore_PPK13301.pdf','s1 §1.1; Ekstra s1')
r(6,'Utrunnet væske','sum_trigger','Vann/olje/gass etter plutselig utstrømning fra rør/tilkoblet utstyr 20 000 / Ekstra 40 000.','Innbo_og_losore_PPK13301.pdf','s1 §1.1; Ekstra s1')
r(7,'Små bygninger','area_sum','Drivhus/annen bygning under 10 m² 30 000.','Innbo_og_losore_PPK13301.pdf','s1 §1.1; Ekstra s1')
r(8,'Kjøretøyrelatert løsøre','perils_limits','Kun brann/tyveri på stedet: bildeler, båt inntil 15 fot/10 hk, kano/kajakk, tilhenger 20 000 hver / Ekstra 40 000; særskilt dekning av rullestol 15 km/t og hobbydrone. Ikke øvrig motorvogn, el-sparkesykkel eller campingvogn.','Innbo_og_losore_PPK13301.pdf','s1 §1.1; Ekstra s1')
r(9,'Kontanter/programvare','additional_sum','Kontanter/verdipapir 20 000; programvare 5 000; sum i tillegg til valgt forsikringssum.','Innbo_og_losore_PPK13301.pdf','s2 §1.2; Ekstra s2')
r(10,'Merutgifter','moving_storage','Nødvendig riving/rydding/destruksjon samt flytting/lagring ved forhåndsgodkjenning, i tillegg til forsikringssum.','Innbo_og_losore_PPK13301.pdf','s2 §1.2; Ekstra s2')
r(11,'Midlertidig bosted','sum_duration_conditions','120 000 / Ekstra normal reparasjonstid; etter én uke forhåndsgodkjenning; innsparing motregnes; ikke leie av arbeidssted.','Innbo_og_losore_PPK13301.pdf','s2 §1.2,s5–6 §3; Ekstra s2,6')
r(12,'Leietakers påkostning','sum_trigger','150 000 / Ekstra 500 000 når leieavtale opphører som følge av bygningsskade; borettslag ikke leie i denne sammenheng.','Innbo_og_losore_PPK13301.pdf','s2 §1.2; Ekstra s2')
r(13,'Brann','trigger_exclusion','Løs ild; ikke svimerker/sot uten brann, glør/sparkskader alene.','Innbo_og_losore_PPK13301.pdf','s2 §2.1; Ekstra s2')
r(14,'Alarm','deductible_reduction','Brann/tyverialarm til alarmsentral kan redusere egenandel inntil 4 000; vannalarm med stenging/backventil tilsvarende ved relevante skader.','Innbo_og_losore_PPK13301.pdf','s2–4 §§2.1–2.4; Ekstra tilsvarende')
r(15,'Lyn/elektrisk fenomen','trigger_exclusion','Direkte lyn/elektrisk fenomen, men ikke kortslutning fordi vann er tilført.','Innbo_og_losore_PPK13301.pdf','s2 §2.2; Ekstra s2')
r(16,'Vann','covered_triggers','Plutselig rørutstrømning/slokkemiddel/akvarium/utvendig rør; terreng/grunn krever stående vann over laveste gulv.','Innbo_og_losore_PPK13301.pdf','s3 §2.3; Ekstra s3')
r(17,'Vann','level_specific','Innbo bare åpning etter annen erstatningsmessig skade; ikke annen nedbør/takrenne/nedløp/kondens/sopp/råte. Ekstra også overbakkelekkasje gjennom andre åpninger, fortsatt sopp/råte unntatt.','Innbo_og_losore_PPK13301.pdf','s3 §2.3; Ekstra s3')
r(18,'Vann fra terreng','deductible','Minimum 8 000.','Innbo_og_losore_PPK13301.pdf','s3 §2.3; Ekstra s3')
r(19,'Tyveri','private_room_storage_limits','Privat rom/bod med adgang fellesareal 50 000 / Ekstra 350 000; privat bod utenfor bosted 30 000 /60 000; fellesbod/fellesgarasje 15 000 i Innbo.','Innbo_og_losore_PPK13301.pdf','s3–4 §2.4; Ekstra s3–4')
r(20,'Tyveri utenfor hjemmet','sum_scope','Egen hage/balkong/terrasse 20 000 /40 000; Ekstra øvrig ute 30 000 per tilfelle, kontanter kun veskenapping.','Innbo_og_losore_PPK13301.pdf','s3–4 §2.4; Ekstra s4')
r(21,'Sykkeltyveri','sum_per_item','Sykkel/elsykkel/barnevogn/sykkeltilhenger utenfor stedet 20 000 /40 000 per gjenstand.','Innbo_og_losore_PPK13301.pdf','s3–4 §2.4; Ekstra s4')
r(22,'Sykkel','deductible_reduction','FG-register aktivt betalt abonnement gir 2 000 redusert egenandel.','Innbo_og_losore_PPK13301.pdf','s4 §2.4; Ekstra s4')
r(23,'Veskenapping','sum','15 000 i Innbo; Ekstra øvrigsted-ramme 30 000, kontanter bare ved veskenapping.','Innbo_og_losore_PPK13301.pdf','s3–4 §2.4; Ekstra s4')
r(24,'Bygningsskade ved tyveri','sum','Leid/andelseid bolig 20 000 /40 000.','Innbo_og_losore_PPK13301.pdf','s4 §2.4; Ekstra s4')
r(25,'Tyveri','exclusions','Ikke leietakers skadeverk i utleid rom eller cybertyveri/hacking; kosmetisk skade ikke dekket. Utleietillegg vurderes separat.','Innbo_og_losore_PPK13301.pdf','s4 §2.4; Ekstra s4')
r(26,'Flytting','theft_limit','Privat flytting innen valgt sum; transportbedrift/idrettslag inntil 30 000 per tilfelle.','Innbo_og_losore_Ekstra_PPK13302.pdf','s3–4 §2.4','extra')
r(27,'Andre skader','specified_perils','Mat fryser etter plutselig strøm/kjølesvikt 15 000; hvitevarer plutselig/uventet; byggkollaps av snø/vind under storm; sot/eksplosjon/sprengning.','Innbo_og_losore_PPK13301.pdf','s4 §2.5','base')
r(28,'Andre skader','exclusions','Ikke ukjent årsak, kosmetikk, garanti, slitasje/korrosjon/alder, frost, insekter/mugg/råte eller kjæledyr; ikke drivhusglass alene/teltkollaps.','Innbo_og_losore_PPK13301.pdf','s4 §2.5; Ekstra s4')
r(29,'Andre skader','deductibles','Vind/snø minimum 8 000; sprengning på stedet minimum 10 000 i Innbo.','Innbo_og_losore_PPK13301.pdf','s4 §2.5','base')
r(30,'Plutselig uforutsett skade','conditions_exclusions','Ikke at tingen bare er borte; sykkel over 40 000 og konkurranseskade unntatt; brann/elektrisk/vann/tyveri/natur reguleres uttømmende av egne punkter. Andre hovedunntak beholdes.','Innbo_og_losore_Ekstra_PPK13302.pdf','s4 §2.5','extra')
r(31,'Plutselig uforutsett skade','deductible','2 000; vind/snø minimum 8 000.','Innbo_og_losore_Ekstra_PPK13302.pdf','s4 §2.5','extra')
r(32,'Skadedyr','sum_scope','VIS bekjemper skadeinsekter/mus/rotter, ikke aktivitet før/etter periode; fast bolig Norge; samlet behandling+forhåndsgodkjent bosted 150 000 per tilfelle; egenandel 2 000.','Innbo_og_losore_Ekstra_PPK13302.pdf','s5 §2.6','extra')
r(33,'Glass/sanitær/integrerte hvitevarer','scope_trigger','Fastmontert i privat bebodd leid/andels-/selveierleilighet; plutselig brudd/lyn/elektrisk kortslutning; ikke kosmetikk.','Innbo_og_losore_Ekstra_PPK13302.pdf','s5 §2.7','extra')
r(34,'Oppgjør','age_deduction','Fradrag når verditap minst en tredjedel av reparasjon/gjenanskaffelse; ikke for småbygninger/drivhus.','Innbo_og_losore_PPK13301.pdf','s5 §3; Ekstra s6')
r(35,'Oppgjør','market_value_cap','Brukt/arvet/gave, antikvitet/kunst/samlinger, ikke i bruk, arving/bo: omsetningsverdibegrensning.','Innbo_og_losore_PPK13301.pdf','s5–6 §3; Ekstra s6')
r(36,'Oppgjør','method_labor','Tryg velger kontant/reparasjon/gjenanskaffelse, ombruk; eget arbeid 300/time, moms ved betalt/ikke fradragsført.','Innbo_og_losore_PPK13301.pdf','s5–6 §3; Ekstra s6–7')
r(37,'Naturskade','sum_deductible','Lovregulert brannforsikret innbo Norge; naturulykker, ikke nedbør/frost/snøtyngde; 8 000 egenandel.','Naturskade_PGE90010.pdf','s1–2 §§1–3')
r(38,'Privatansvar','sum_deductible','5 millioner per hendelse, 4 000 egenandel; privatperson Norden; også lovpålagt yrkesskadeansvar.','Privatansvar_PGE90020.pdf','s1–2 §§1–3.3 (01.10.2026)')
r(39,'Privatansvar','exclusions_exception','Yrkesaktivitet/familie/motorkjøretøy/fast eiendom/eid eller lånt ting unntatt; leid bolig ved brann/eksplosjon/rørvann eller olje likevel omfattet.','Privatansvar_PGE90020.pdf','s1–2 §3.2')
r(40,'Rettshjelp','sum_deductible','100 000 per tvist, 250 000 ved minst tre sikrede, 20 000 Tryg-tvist, maks økonomisk interesse; 4 000+20%.','Rettshjelp_PGE91500.pdf','s1–2 §§3–4')
r(41,'Rettshjelp','type_scope','Privatperson Norden; egne bolig/motor/båt/reise-regler går foran; ID-tyveritvist og visse boligkjøp/-salg; ikke nærings-/familie-/straffesaker.','Rettshjelp_PGE91500.pdf','s3 §5.4, §§6')
r(42,'Sikkerhet','material_obligations','Smykker/optikk/elektronikk/kontanter ikke i fellesadkomstbod/synlig bil/innsjekket bagasje; låsing/tilsyn; vannstengning etter måned ubebodd; varme/snømåking; sykler låst.','Sikkerhetsforskrifter_PF133.pdf','s1 §1.2')
r(43,'Utleie/fraflytting','risk_change','Betalt utleie krever avtale (familieunntak); fraflytting begrenser til brann/natur for fraflyttingsrelatert skade.','Sikkerhetsforskrifter_PF133.pdf','s2 §2')
r(44,'Utleietillegg','vandalism_theft','Valgfritt. Skadeverk 500 000/tilfelle; tyveri/underslag 500 000 fra leietaker/gjester; ikke bruksslitasje/vedlikehold.','Utleie_PPK13306.pdf','s1 §§1–2.2','addon')
r(45,'Utleietillegg','rent_loss','Ubetalt husleie inntil 6 måneder, én gang per leietaker; egenandel 3 måneders husleie minst 10 000.','Utleie_PPK13306.pdf','s1 §§2.3,2.5','addon')
r(46,'Utleietillegg','eviction_deductible','Nødvendig utkastelse ved avtaleslutt/brudd 20 000/tilfelle; øvrig egenandel 6 000/tilfelle.','Utleie_PPK13306.pdf','s1 §§2.4–2.5','addon')
r(47,'Utleietillegg','settlement','Tryg velger oppgjør/ombruk; fradrag ved minst en tredjedels verditap; brukt/arv/gave markedsverdi; eget arbeid 300/time.','Utleie_PPK13306.pdf','s2 §3','addon')
r(48,'IPID/fullvilkår','conflict_candidate','IPID 2022 nevner skade forårsaket av dyr og tapt husleie samlet, mens 2026 fullvilkår unntar kjæledyr og beskriver skadedyrbekjempelse; utleietillegg separat. Ikke inferer ubetinget dyreskade fra IPID.','IPID_Innbo.pdf','s1')
save('tryg-innbo-independent-inventory.json',dict(source_first=True,catalog_not_yet_inspected=True,rule_count=len(rows),rules=rows,notes=['Alle 10 lokale originaler gjennomgått; PGE91000/PGE91500 gjenbruk fra tidligere kontroll. Privatansvar ikraft 01.10 etter frosset snapshot 29.09; tydelig datoforbehold.']))
print(len(rows))
