from continue_audit import save
R=[]
def r(scope,sub,dim,val,src,loc):R.append(dict(id=f'TR-BOAT-{len(R)+1:03d}',scope=scope,subject=sub,dimension=dim,value=val,source=src,location=loc))
r('all','Geografi','omfang','Europa200nautiskemilfrafastlandunntattRusslandfarvann;overfartSvalbard/Island/Storbritannia/Madeira/Azorene/Kanariøyene+territorialfarvann;legalNorden.','inboard','1 §3')
r('all','Sikrede','rolle','Bevisnevntkunde,rettmessigbruker/føreransvar,panthaveravtalt.','inboard','1 §1')
r('all','Eierskifte','etterdekning','14dny eier hvisikkeegenforsikring.','inboard','1 §4')
r('all','Sesong','premie','Jan4/feb4/mar5/apr6/mai9/jun13/jul17/aug15/sep11/okt7/nov5/des4%;oppsigelsesrisikoikkeflattfordelt,likmånedligbetalingmulig.','inboard','1 §5')
r('all','Ansvar/rettshjelp','status','Ansvar+rettshjelpgjelderi tilleggtilavtaltdekning;privaterstatningsansvar. Sum foransvarikkedokumentertlokaltihoveddekningsvilkår.','inboard','1 §2')
r('physical','Brann','utløser','Brann/eksplosjon/kortslutning/lyn,sjøogopplag;ikkesviglo/tingmedhensiktvarme.','ipid','1')
r('physical','Tyveri','utløser','Tyveri/brukstyveri/forsøkav/fra;transportetterbranntyverinærmesteverkstedogvrakfjerningetterdekketskade.','ipid','1')
r('physical','Løsøre','scope/unntak','Plutseligskadeeiendeleribåtpåweb;IPIDikke penger/papirer/smykker/verdier/opplagutstyr/fortøyningsanordningutenfor. Basissumikkei lokalefullvilkår.','ipid','1')
r('kasko','Kasko','utløser','Grunnstøting/kollisjon/synking/kantring/transport/slipp/løft/hærverk/feilfylling/ytreplutseligskade.','web','Dekningstabell')
r('kasko','Kasko','unntak','Varmganguansettårsakmedmotortilleggsunntak;nedbør/frost/isberøring,seilhardt-værskadeunntatt.','ipid','1')
r('kasko','Drev','nydelsoppgjør','Totalskadeinntil5årdrevgisnytt;eldreinntil25%aldersfradrag. Drevetsalderikkehelebåtens.','web','Reparasjon/skifteavdrev')
r('kasko','Redning','assistanse','Uforutsettdriftsstans,slep nærmestehavn500egenandel.','web','Sleptilland')
r('extra','Ekstra','egenandelreduksjon','Reduksjon2kpåKasko,ikkeassistanseegenandel.','extra','1 §1.1')
r('extra','Løsøre','sum/vilkår','100kuavhengigbåtsum,30k/item;avtaltutvidelsei tillegg;ikkeutleie.','extra','1 §1.2')
r('extra','Dieseldyr','sum/egenandel','Tank/motorrensreparasjonmaxavtaltsum50k,egenandel2.5k.','extra','1 §1.3')
r('extra','Opplagsmateriell','sum/egenandel','30k/2.5kegenandel.','extra','1 §1.4')
r('extra','Småbåt/motor','grenser','Ensmåbåt14fot/énutenbordsmotormax25hk,50ksamlet/2.5kegenandel,slepejolle/lettbåt/gummi/redningsflåte.','extra','1 §1.5')
r('extra','Transport/opphold/hjemreise','utløser','Nærmesteverkstedhvisikkelokalreparasjonrimeligere;hentingvedetterlattbåt/skadesykdomsentralperson;hjemreiseikke sjødyktig/tyveri3d;sykdomulykkedødførersentralperson.','extra','1 §1.6')
r('extra','Ferieavbrudd','beløp/tid/utløser','Påbegyntferiementmerenn6d,avbruttvedtyveri/ikkesjødyktigskade;leiebil/leiebåt/opphold2.5k/dag21d,dokumentasjonskrav.','extra','2 §1.6')
r('extra','Transport/ferie','samlettak','Samlettransport/opphold/hjemreise/ferieavbrudd20%båtsummax100k.','extra','2 §1.6')
r('extra','Vannscooterplattform','sum/egenandel','Flytedokk/fortøyning30k/2.5kegenandel.','extra','2 §1.7')
r('extra','Nyverdi','alder/terskel/form','Nytilsvarendemerke/modellutstyrvedtotalskadeinnen3årkjøptny,>60%nyverdiutenegnerabatter,avtaltsumtak,originalkjøpekontrakt.','extra','2 §1.8')
r('motor','Maskinskade','valgfri/alder','TilleggKasko;utperiodenmotor+tilhørendekomponenter12årpåheng/15årinnenbord. IPIDskriverutenbord/seilbåt12år;variantmotortypescopeavklares.','motor','1 §1')
r('motor','Maskinskade','utløser/omfang','Varmgangplutseligkjøleblokkeringpåbåt/motor;bruddmotor/gir/aksel/styring/ror/drivstoff;instrumentelektriskkabling;diagnoseoveregenandel.','motor','1 §1')
r('motor','Maskinskade','egenandel','4ktom5årmotorderetter25%min4k.','motor','1 §1.1')
r('motor','Maskinskade','unntak','Slitasje/korrosjoninklE10/slitedeler/tidligerebrukinæring;garantimedfallbackregresshviskravikkeførerfram.','motor','1 §1')
r('accident','Ulykke','valgfri/rolle','Valgfrittførerpassasjerrettmessigombordogutenforhvisbåtdirekteårsak;IPIDover80unntatt;websykehusmenikkeeksplicittytelseilokaltPFB38900.','accident','1 §1/2')
r('accident','Ulykke','sum/grad','200kinvaliditetgradert,100kdødinnen1år;20khvisingenektefelleellerbarnunder20år;samlet1.5mill/ulykkealle.','accident','1–2 §3')
r('accident','Ulykke','unntak/oppgjør','PsykiskmedenPTSDunntak,tannspising/infeksjonmedsårunntak;sykdom/tidligerefunksjonfradrag;invaliditetikkev/1årdød.','accident','1–2 §2/3')
r('all','Sikkerhet','krav','Fortøyning/tilsyn,vannscooterlåst,aldri motorbåtkonkurranse,trening;keyseparat.','ipid','1–2')
r('all','Kundevalg','egenandel','WebKasko/BTfra4k,Ekstra4kreduksjon2k;Maskin4keldreprosent;bevisfastsettervalgtgrunndeductible.','web','FAQ egenandel')
r('all','Rettshjelp','sum/egenandel','PGE91500§5.3uttrykkeligmotorvognogbåt;100k250k20k/økonomiskinteresse;4k+20%,Norden,ettersalg/personskadefører.','legal','2–5 §5.3/6')
r('all','Generelt','kildetilgang','PFB33000/34000/35000/37000erproduktvilkårikke hovedAnsvar/BT/Kaskodekningsvilkår;dekkendegrunnkildermangler,IPID/webgirbareavgrensedepositivebevis.','inboard','1 §2')
save('tryg-boat-independent-inventory.json',dict(source_first=True,rules=R,note='Nineboatartifactsread;fourproductvariantsreadseparately,notmislabelledfullKaskoterms. SharedPGE91500exactboat§5.3reviewed.'))
print(len(R))
