from continue_audit import save
R=[]
def r(typ,scope,subject,dim,val,src,loc):R.append(dict(id=f'TR-EXT-{len(R)+1:03d}',type=typ,scope=scope,subject=subject,dimension=dim,value=val,source=src,location=loc))
r('all','all','Geografi','område','Europa unntatt Russland/Belarus/Tyrkia; rettshjelp Norden.','product','1 §3')
r('all','all','Sikrede/eierskifte','vilkår','Registerhovedeier/bevis,panthaveravtalt;14dny eier hvisikkeegenforsikring.','product','1 §1/4')
r('snow','all','Ansvar','sum','Ubegrensetperson/100millting;skadestedlov/norskførerpassasjerbedreregelhvisbosattNorge.','ansvar','1 §1')
r('snow','all','Avregistrering','regelkonflikt','Fullproduktansvaropphør,webansvar+ulykkeopphør/øvrigfortsetter,IPIDavskiltingavslutterforsikringen.','product','1 §4;IPID2;FAQ')
r('snow','all','Sesongpremie','fordeling','Jan12,feb18,marapr22hver,mai8,juni–nov2hver,des6%;månedbetalinglikebeløpmenoppsigelserisikofordelt.','product','1–2 §5')
r('snow','all','Sikkerhet','førere/bruk','Dødmannsknapp/-snorbrukeshvismontert;under23meldingunntatteier/ektefelle;kommersiellutleiemåavtales;baneforbudunntattgodkjentkurs+20k.','safety','1–2')
r('snow','physical','Utstyr','sum/omfang','Standardkjøretøy/deleroghjelm;fastutstyr10k/foliering,ikketilhenger/avtagbart/spesiallakk.','physical','1 §1')
r('snow','physical','Brann/tyveri','sum/egenandel','Åpenild/lyn/eksplosjon,tyveri/brukstyveri+forsøkshærverk;BrannTyverinivå6k,Kaskonivå4k.','physical','1 §2')
r('snow','physical','Redning','unavailable','Transporttilnærmestereparasjonsverkstedikkeerstattet.','physical','1–2 §3.1')
r('snow','kasko','Kasko','omfang','Kollisjon/utforkjøring/velt/hærverk/feilfylling/ytreplutselig<=ett døgn;valgtegenandelbevis.','kasko','1 §2.1')
r('snow','kasko','Vær','egenandel','Værskadeparkertinnendørsgarasje0egenandel.','kasko','3 §3.6')
r('snow','all','Førerulykke','valgfri/sum','PAU28002fører/passasjerbarehvisflerpersonregistrert;200kinvaliditetgradert/100kdødinnen1år;valgfritt. PAU28003førerpassasjeralternativmåholdesrettscope.','accident','1–2')
r('snow','all','Førerulykke','unntak/oppgjør','PTSDunntakfrapsykiskunntak,tannspising/infeksjonmedenkeltsårunntak,sammenvirkendesykdom/fradragfunksjon;ingeninvaliditetdødinnen1år.','accident','1–2 §2–3')
r('tow','all','Ansvar','trekkbil','Tilhenger/campingvognansvarvia trekkbil,ogsåsisttilkobletbilnårfrakoblet. Ikkeegenansvarsdekning.','web','FAQ ansvar')
r('tow','all','Grunnsum','kundespesifikk','Valgtforsikringssumbevis,maxmarkedsverdi;ikkeenverdigaranti.','physical','1 §1.1;3 §3.3')
r('tow','all','Utstyr','grense','Fasttilbehør10k;standardekstrahjulsett;spesiallakkikke;utbetalesutoverkjøretøyetsforsikringssum.','physical','1 §1.1;siste §3.4')
r('camp','all','Fortelt/terrasse','omfang','Allebyggematerialerkonstruertforvognen;innredningmed. Naturskadespikerteltmåinkluderesivalgtsum.','physical','1 §1.1;naturskade')
r('camp','base','Løsøre','grense/egenandel','15ksamlet5k/itemi vogn/fortelt,annenavtaltsum;ikke penger/papirer/antikviteter/smykker;BrannogsåCD/DVD/spill/vin/brennevinunntatt. Utovervognsum.','physical','1 §1.1;siste §3.4')
r('tow','all','Brann','egenandel','Åpenild/lyn/eksplosjon;BrannellerBrannTyveri4k,Kasko6k,hvisikkelavereavtalt.','physical','brann1§2.1;bt1§2.1;kasko2§2.2')
r('tow','theft','Tyveri','egenandel/omfang','Tyveri/brukstyveri/hærverkiforsøk;BrannTyveri4k,Kasko6k hvislavereikkeavtalt.','physical','bt1–2§2.2;kasko2§2.3')
r('camp','theft','Tyveri','forteltunntak','Tyverifraforteltavtøy/duk/lignendeikke. IkkeimportBobilregelomvognfjernet.','physical','bt1§2.2;kasko2§2.3')
r('tow','theft','Underslag','avtaltutleie','Tilhengeravtaltutleid,dekkestap3mndettermelding;ikkefamilie/ansatte. Ikkeautomatiskkundevalg.','physical','2 §2.2/2.3')
r('tow','all','Naturskade','omfang/egenandel','Brannforsikret;skred/storm/flom/stormflo/flodbølge/meteor/jordskjelv/vulkan;8kegenandel.','physical','brann1–2§2.2;bt2§2.3;kasko2–3§2.5')
r('tow','all','Naturskade','unntak','Ikke frost/tele/tørke/nedbør/snøtyngde/isgang/dyr/insekt/bakterie/sopp/råte.','physical','naturskadekapittel')
r('tow','kasko','Kasko','omfang/avgrensning','Kollisjon/utforkjøring/velt/hærverk/ytreplutselig<=24t;ikke frost/strømbrudd/renkonstruksjonssprekk/insektgnager;naturskadeegenregel.','kasko','1 §2.1')
r('tow','kasko','Vær','egenandel','Værskadeparkertinnendørsgarasje0egenandel.','kasko','2 §2.1')
r('tow','kasko','Glass','egenandel','3kbytte/0reparasjonhosavtaleverksted;bruddruteytreplutselig,ikkekrakelering/punktert.','kasko','2 §2.4')
r('all','physical','Reparasjon','oppgjør','70%takstutenMVAkontant;likeverdigdeler/fradragforbedring;ikkemerverditap/foreløpig/overnattarbeid.','physical','§3.2')
r('all','physical','Garanti','reparasjon','8årkarosseri/3årbruktmotorvedservice;mekanikkforhandlergaranti/slitedelerikke;2mndmelding. Kildenharbilgeneriskordlyd,ikkeinfermotorietilhenger.','physical','§3.2')
r('all','physical','Totalskade','marked','Markedsverdiførloss,fradragvrak/omregvedbeholdt;Towtakavtaltsum;ingen nyverdigaranti dokumentert.','physical','§3.3')
r('tow','all','Elektronikk','fradrag','10%årligfra nytt,maks50%,nyverdiskadedag.','physical','§3.3')
r('tow','all','Fjerning','utoversum','Rimelignødvendigfjerningavtotalskadetvognutoverforsikringssumveddekketskade.','physical','§3.4')
r('tow','all','Sikkerhet','grunn','Lås,nøkkelseparat;demontertforteltlåstbygningikke fellesgarasje;vær/vind/flomflytting/gassvedlikehold.','safety','1 §1.2')
r('tow','all','Utleie','valg/identifikasjon','Kommersiellutleierisikoavtales;bevisdekkerutleidcampingvognbegrensetidentifikasjonmedregress.','safety','2 §2/3.3')
r('camp','extra','Ekstra','kaskotillegg','CampingvognExtrautvidelseKasko1.risiko,ikkeTilhenger.','extra','1')
r('camp','extra','Fastutstyr','sum','50kfastmontert.','extra','1 Fastmontert')
r('camp','extra','Løsøre','grense/egenandel','50ksamlet,15kitekstilfortelt,10k/item;valgtsumi tillegg,1kegenandel;ikkehelt/delvisutleie.','extra','1 Løstutstyr')
r('camp','extra','Skadedyr','omfang','Insekt/gnager/øvrigskadepåvogn;hensattvognjevnliginnsyn/sikring/åpningerlukket/tomtformat.','extra','1; sikkerhet1')
r('camp','extra','Fukt','grense/egenandel','Innen10årførstregny,påløptforsikringstid;8kinntil5år;over5år25%min8k.','extra','1 Fuktskade')
r('camp','extra','Fukt','vilkår/unntak','Årligfukttesthvertforsikringsårgodkjentverksted/fabrikkrav,straksutbedring;ikke pipe/frost/fortelt/terrasse/teltvogn;garantiførstmedregresshviskravikkeførerfram.','extra','1 Fuktskade; sikkerhet1')
r('camp','extra','Ferieavbrudd','sum/tid/vilkår','Alleredepåbegyntferieavbrytespådekketskade;1.5k/dagmax14restplanlagtedager;leievognog/elleropphold,dokumenterutgift/rute/lengde,ikkeutleie/anskaffelsesgaranti.','extra','1 Avbruttferie')
r('all','all','Rettshjelp','sum/egenandel','Norden/motorPGE91500:100k/tvist,250kmin3parter,20kmotTrygsrettshjelp,økonomiskinteressetak;4k+20%.','legal','§5.3/6')
r('all','all','Rettshjelp','begrensning','Eier/bruker/fører,ettersalg/førerulykke;familie/yrke/annetkjøretøy/straffmedfornærmetunntak/idømtesaksomkostikke.','legal','§5.3/5.5')
r('all','all','Generelt','administrasjon','Felleshøyesteegenandel/krigterror/oppgjørsadministrasjonkildebeholdt.','general','1–5')
r('trailer','all','Objektvalg','type','Privatpersonbil/vare/båt/hestetilhenger;godsikkeegenstandardvaredekning.','web','FAQ type')
save('tryg-extensions-independent-inventory.json',dict(source_first=True,rules=R,note='AlluniquePDFsand6HTMLread;identicalhashoriginalsreadonce. SnowPAU26320/25505effectiveOct1;frozenSep29comparisonpreservedwithtemporalnote. HTMLresponsivecheckboxtextnotusedtoinfercoveragewithoutPDF.'))
print(len(R))
