from continue_audit import save
R=[]
def r(typ,scope,subject,dim,value,src,loc):R.append(dict(id=f'TR-MB-{len(R)+1:03d}',type=typ,scope=scope,subject=subject,dimension=dim,value=value,source=src,location=loc))
r('both','all','Sikrede','rolle','Registrert eier/forsikringsbevis; ansvar rettmessig fører; panthaver etter avtale.','product','1 §1')
r('both','all','Geografi','område','Europa unntatt Russland, Belarus og Tyrkia; rettshjelp Norden; særskilt grenseforsikring kan kreves.','product','1 §2')
r('both','all','Eierskifte','etterdekning','Ny eier inntil14d hvis ikke egen forsikring; ansvar avsluttes ved eierskifte.','product','1 §3–4')
r('mc','all','Avregistrering','videreføring','Ansvar opphører, andre dekninger videreføres.','product','1 §4')
r('bobil','all','Avregistrering','videreføring','Produktvilkår sier hele forsikringen opphører; IPID samme. Nettside sier kun ansvar/ulykke, øvrig videreføres. Kildekonflikt.','product','1 §4')
r('mc','all','Sesongpremie','fordeling','Måneder jan–des2/2/3/6/14/16/16/16/14/6/3/2%; lik månedlig betaling er ikke lik risikopremie ved oppsigelse.','product','1–2 §5')
r('both','all','Bonus','regler','AlternativA75% ellerB80%; A treårsopptjening, første skade tilbakeår1; B10%-tap; ansvar/Kasko bonustap med angitte unntak; brann/tyveri/redning ikke tap.','product','2 §5–6')
r('both','all','Sikkerhet','service','Autoriserte dokumenterte servicer; ikke effektøkning; fører kompetanse og sikring.','safety','1–3')
r('mc','all','Fører/bruk','avgrensning','Eier/ektefelle med mindre annen fører valgt; ikke kommersiell utleie/bud; låst bagasje tas ut over natten; bane forbudt med godkjentkurs-unntak og20kegenandel.','safety','1–2')
r('bobil','all','Årlig kjørelengde','kundespesifikk','Valgt i bevis; delår prorata; overkjøring meldes; avkortning ikke brann/tyveri/glass/redning/maskin.','safety','2')
r('bobil','all','Sikring/utleie','vilkår','Fortelt demonteres og låst bygning; fellesgarasje ikke tilstrekkelig; jevnlig skadedyrkontroll; gassvedlikehold. Kommersiell utleie må avtales, begrenset identifikasjon med regress.','safety','1–2')
r('both','physical','Utstyr','fastmontert','10k fastmontert inklfoliering; ekstra standardhjulsett; ikke avtagbart/tilhenger/spesiallakk.','physical','1 §1')
r('mc','physical','Bagasje','grunnsum','10k i låst boks; ikke penger/papirer/næringsgods. Web Kasko har dessuten5k per enkeltgjenstand.','physical','1 §1')
r('bobil','physical','Bagasje/fortelt','grunnsum','Løsøre15k,5k/gjenstand; fortelt med. Ikke penger/papirer/antikviteter/smykker/CD/DVD/spill/vin/brennevin.','physical','1 §1')
r('bobil','physical','Fortelt/terrasse','materialomfang','Bobil fast innredning og fortelt/terrasse alle byggematerialer; Kasko løsørerad sier tekstilfortelt.','physical','1 §1')
r('both','physical','Brann','status/egenandel','Åpen flamme/eksplosjon/lyn;6k med mindre lavere avtalt.','physical','Delkasko1§2.1;Kasko2§2.2')
r('both','physical','Tyveri','status/egenandel','Tyveri/brukstyveri/deler;hærverk vedtyveriforsøk;6k med mindre lavere avtalt.','physical','Delkasko1§2.2;Kasko2§2.3')
r('bobil','physical','Tyveri','fortelt/rental','Ikke løsøre fra tekstilfortelt, ikke fra fortelt når bobil fjernet, ikke fortelt/terrasse når bobil fjernet; meldt avtaltutleie underslag3mnd, ikke familie/ansatte.','physical','Delkasko1§2.2;Kasko2§2.3')
r('mc','physical','Glass','avgrensning','Bare tre/firehjulsMC; vindskjerm ikke; reparasjon0,bytte3k.','physical','Delkasko1§2.3;Kasko2§2.4')
r('bobil','physical','Glass','avgrensning','Reparasjon0/bytte3k; avtaleverksted; ikkeEU-riper/slitasje/krakelering/punktertglass.','physical','Delkasko1§2.3;Kasko2§2.4')
r('both','physical','Redning','utløsere','Skade/start/innlåst/tomdrivstoff/strøm/driftsstopp; tilhenger med, nærmeste verksted/henting; fører sykdom/ulykke/død gir passasjerretur.','physical','Delkasko1–2§2.4;Kasko2§2.5')
r('both','physical','Redning','tak/egenandel','750egenandel; transport50%kjøretøyverdi; rimeligst reise, videre maks hjemkost; ikke offroad/haik/annetabonnement/garanti.','physical','Delkasko2§2.4;Kasko2–3§2.5')
r('both','physical','Oppgjør','form','Reparasjon70%takstutenMVA vedkontant, ingenleiebil; bruktelikeverdige deler og forbedringsfradrag; markedsverdi vedtotaltap.','physical','Delkasko2–3§3;Kasko3§3')
r('both','physical','Verkstedgaranti','varighet','8årkarosseri/3årbruktmotorvedservice; følger kjøretøyet, melde mangel2mnd; slitedelerikke.','physical','Delkasko2–3§3.2;Kasko3§3.2')
r('bobil','physical','Elektronikk','aldersfradrag','10%perår fra nytt,maks50%,nyverdi skadedag. MC-terms inneholder ikke samme faste prosentsats.','physical','Delkasko3§3.3;Kasko4§3.3')
r('both','kasko','Kasko','utløsere','Sammenstøt/utforkjøring/velt/hærverk/feilfylling; ytreplutselig<=24t/uventet; ikke maskinbrudd/frost.','kasko','1 §2.1')
r('bobil','kasko','Skadedyr','omfang','Mus/rotter/insekter/skadedyr dekket; fortelt/terrasse med; ikke frost eller sviktendestrøm alene.','kasko','1 §2.1')
r('both','kasko','Dyr/vær','egenandel','Dyrepåkjørsel2k uten bonustap nårpoliti/viltnemndvarslet; værskade parkertgarasje0.','kasko','1 §2.1')
r('bobil','kasko','Ungfører','egenandel','Under23+5k med unntak forsikringstaker. Ikke Bil-unntak for ektefelle/Tryglappen.','kasko','1 §2.1')
r('mc','kasko','Nyverdi','grenser','Innen1år førstregsomny på taker; inntil10kkm; skade>80%nyverdi inkl rabatter.','kasko','4 §3.4')
r('mc','kasko','Nyverdi','vilkår/form','Tilsvarende nyMC, utgåttmodell kjøpekontrakt; tyveri3uker;kontantalternativ;leasing unntatt. Ingen3årsutvidelse i MCExtra.','kasko','4 §3.4')
r('bobil','kasko','Nyverdi','ingen sikker regel','Fullt lokalpakke gir ikke egen standard nyverdiregel for Bobil; ikke lån Bil/MC.','kasko','1–4')
r('mc','extra','Maskinskade','inkludert/alder','MCExtraKaskotillegg; motor/gir/drivlinje/ECU,diagnosekost; innen8årførstreg; ingen kilometergrense oppgitt.','extra','1 §1')
r('mc','extra','Maskinskade','egenandel','4k inntil3år;6k fra3til7år. Ikke anta egenandel for7–8år eller eksakt3årsgrense.','extra','1 §1')
r('mc','extra','Maskinskade','unntak','Ikke slitasje/korrosjon/tuning/vanligkaskoskade; garanti med dekning+regress hvis kravikkeførerfram.','extra','1 §1')
r('mc','extra','Parkert velting','bonus/alder','Ukjent skadevolder/velt ved parkering, innen6år, ingenbonustap.','extra','1 §1')
r('mc','extra','LeieMC/bil','sum/periode','500kr/dag10d normalreparasjon; firmafaktura, ikkeandreleieutgifter. Web100km/daggruppeB, fullvilkår ikke samme spesifisering.','extra','1 §1')
r('mc','extra','Bagasje','sum/vilkår','30k låst boks; ikkehaikere/næring/penger/papirer/dyr.','extra','1 §1')
r('both','extra','Fastutstyr','sum','Fastmontert og ekstra hjul/felger samlet50k/hendelse; ikke avtagbart.','extra','1 §1')
r('mc','extra','Ferge/tog','bonustap','Skade vedtransport på tog/ferge ingenbonustap.','extra','1 §1')
r('mc','extra','Reservedeler','langtur','Tekniskhavari minst3timerskjøringhjemmefra;3k ekstra levering;0egenandel.','extra','1 §1')
r('both','extra','Feilfylling','sum/egenandel','Motorrens15k,egenandel1k.','extra','mc2/bobil1 §1')
r('mc','extra','Nøkkel','sum/egenandel','20k tap/skade,1kegenandel; ikke eksplisitt årstak som Bobil.','extra','2 §1')
r('mc','extra','Sykehus','sum/varighet','5k engangsbeløp/skadetilfelle ved48tinnleggelse.','extra','2 §1')
r('mc','extra','Ulykke utvidelse','betinget sum','Bare hvis fører/passasjerulykke valgt og medisinsk invaliditet>25%, økes200ktil500k.','extra','2 §1')
r('bobil','extra','Bagasje/fortelt','sum/egenandel','100k løsøre,15kfortelt,10k/gjenstand; valgtutvidelse i tillegg;1kegenandel;ikkeutleie/haik/næring/verdier/dyr.','extra','1 §1')
r('bobil','extra','Nøkkel','årstak/egenandel','20k/forsikringsår, bilnøkkelogvarmerfjernkontroll,1kegenandel.','extra','1 §1')
r('bobil','extra','Fukt','alder/egenandel','Tak/vegg/gulv,innen15årførstreg/perioden;8k inntil10år,25%min8k10årellereldre. Bevar grenseoverlapp.','extra','1–2 §1')
r('bobil','extra','Fukt','vilkår/unntak','Årligkontrollhverforsikringsårgodkjentverksted,utbedringumiddelbart; ikke fortelt/terrasse/rørlekkasje/frost;garantiregress.','safety','1; ekstra2 §1')
r('bobil','extra','Ferieavbrudd','beløp/tid','Alleredepåbegyntreiseavbruttavdekketskade;2k/dagrestplanlagttidmax14d; leiebilog/ellerovernatting; dokumentertrute;ikkeutleie/andreleieutgifter/tilgjengelighetsgaranti.','extra','2 §1')
r('mc','all','Geografi','nettside konflikt','Nettside Europa/Israel/TyrkiaunntattRusslandBelarus vs hovedproduktvilkår eksklTyrkia.','web','FAQ Hvor gjelder')
r('mc','physical','Tyverialarm','egenandel','FG/fabrikkmontertsøkealarmaktivert fjerner tyveriegenandel ifølge produktside.','web','FAQ egenandel')
r('bobil','all','Avregistrering','nettside konflikt','Nettside kunansvar/ulykkeopphører,øvrigdekket; fullvilkår/IPIDaltopphører.','web','FAQ avregistrering')
r('bobil','extra','Fukt','Avara alternativ','AvaraMoist fra2026 godkjentsomårligfukttest;10%markedsrabatt erikke selvstendigdekning.','web','FAQ Avara')
r('bobil','motor','Maskinskade','tilvalg/grenser','TilleggKasko/BobilExtra:200kkm ellerutperiodenkjøretøy10årførst,ikke bodel;10/14/18kved120/160/200kkm. Inngangs180kkmpåweb skiltfraopphør200k.','motor','1–2 §1')
r('bobil','motor','Maskinskade','komponenter/unntak','Motor/gir/drivlinje/elektronikkmeddelgrense100kkmforutvalgtedeler,garanti/slitasje/korrosjon/modifikasjonunntak; bodelutstyrunntatt.','motor','1–2 §1')
r('both','all','Ulykke','valgfri','Fører/passasjerulykke valgfritt alle nivåer;200kinvaliditet/100kdød,tilleggsforsikringikkekundevalg.','accident','1–2')
r('both','all','Ansvar','sum','Ubegrensetperson/100millting;Bilansvarsloven.','ansvar','1 §1.1')
r('both','all','Rettshjelp','sum/egenandel','PGE91500motorNorden:100k/tvist,250k3parter,20ktvistTrygrettshjelp,økonomiskinteressetak;4k+20%.','legal','2–5 §5.3/6')
r('both','all','Rettshjelp','hovedunntak','Familie/yrke/annetkjøretøy/straffmedenfornærmetunntak/idømtkostikke;ettersalgogførerpersonskademed.','legal','2–4 §5.3/5.5')
r('both','all','Generelt','øvrig','Felleshøyesteegenandelsregel/krigmedutlandsunntak/terroraggregat; oppgjøradministrasjon kildebeholdt.','general','1–5')
save('tryg-mc-bobil-independent-inventory.json',dict(source_first=True,rules=R,read_scope='All dedicated local MC/Bobil fullterms/IPIDs/productHTML/terms-index plus explicit shared references. No catalog consulted in deriving rules; reused exact Bil shared wording only after applicability verified.'))
print(len(R))
