import json,collections
from pathlib import Path
O=Path('/tmp/source-catalog-completeness-audit');R=Path('/Users/morten/Documents/forsikringsapp')
J=json.loads((O/'audit.json').read_text());C=J['catalog_counts'];F=J['findings'];SF=J['manual_review']['source_facts'];P={p['product_id']:p for p in J['product_coverage']}
def link(label,path):return f'[{label}](<{path}>)'
def src(path):return link(Path(path).name,R/path)
def out(name):return link(name,O/name)
def esc(t):return str(t).replace('|','／').replace('\n',' ')
def table(headers,rows):return '\n'.join(['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(esc(c) for c in row)+' |' for row in rows])
def sec(name,text):return '\n## '+name+'\n\n'+text+'\n'
M='# SOURCE → CATALOG COMPLETENESS AUDIT — manuell kontrolljournal\n\n'
M+='Status **PARTIAL**. «Manuell» betyr kildelesing og semantisk kontroll i denne revisjonen, ikke uavhengig jurist-/menneskeattest. Ingen full produktevaluering er lukket. Dokumentlesing, faktakontroll og komplett kildeinventar er tre forskjellige milepæler.\n\n'
M+='## Gjennomgåtte produkter\n\n'
M+=table(['Eksakt produkt','Scope / versjon','Dybde','Hva som faktisk ble lest og hva som gjenstår'],[(v['product_id'],v['scope']+' / '+str(P[v['product_id']]['version']),v['depth'],v['reasoning']) for v in J['manual_review']['products']])
M+='\n\nAlle31 ovenfor har `full_product_inventory_complete=false`. De173 øvrige identitetene ligger eksplisitt som NOT_STARTED i produktledger. Minst24 komplette dybdegjennomganger og to per familie er ikke oppnådd;Bil har bare én delvis kontroll. De historiske reiseproduktene er fortsatt ekskludert fra aktiv sammenligning.\n'
M+='\n## P0 / P1 — alle dedupliserte grupper\n\nP0=0 påvist i det gjennomgåtte materialet. P1=88 produkt-/dimensjonsforekomster fordelt på52 signaturer. En signatur kan påvirke flere eksakte produktnivåer; forekomstene skal ikke telles som ulike rotårsaker.\n'
for sig in dict.fromkeys(f['signature'] for f in F if f['severity']=='P1'):
 fs=[f for f in F if f['signature']==sig];a=fs[0]
 M+=f"\n### {a['root_cause_id']} / {sig} — {a['semantic_concept']}: {a['semantic_dimension']}\n\n"
 M+=f"- Finding-IDer: {', '.join(x['finding_id'] for x in fs)}.\n- Eksakte produkter: {', '.join('`'+x['product_identity']+'`' for x in fs)}.\n- Komponent: `{a['component'] or 'BASE'}`.\n- Kilde: {src(a['source_artifact'])}, {a['source_location']}; SHA-256 `{a['source_hash']}`.\n- Kildestøtte: {a['source_evidence']}.\n"
 cat=a['catalog_evidence']
 M+='- Katalogtilstand: '+('; '.join('`'+f['key']+'`: '+f['value'] for f in cat) if isinstance(cat,list) else 'Ingen semantisk motpart i kontrollert base/tillegg; se eksakt snapshot og produkt-ID i CSV.')+'\n'
 M+=f"- Klassifisering: **{a['classification']}**, P1, {a['confidence']}.\n- Rådgiverbetydning: {a['advisor_impact']}\n- Årsak/remediering: {a['root_cause_id']}, {a['remediation_batch']}; {a['remediation_complexity']}.\n- Kontroll: kilde og eksisterende katalog manuelt motkontrollert for denne dimensjonen. Full kildepakke er ikke attestert som komplett.\n"
M+='\n## P2 — alle dedupliserte grupper\n\n'+table(['Finding-IDer','Produkt(er)','Emne / dimensjon','Kilde','Betydning'],[(', '.join(x['finding_id'] for x in F if x['signature']==sig),', '.join(x['product'] for x in F if x['signature']==sig),a['semantic_concept']+' / '+a['semantic_dimension'],a['source_artifact']+'; '+a['source_location'],a['advisor_impact']) for sig in dict.fromkeys(f['signature'] for f in F if f['severity']=='P2') for a in [next(f for f in F if f['signature']==sig)]])+'\n'
M+='\n## Kandidater som IKKE er oppgradert til bevist feil\n\n'
M+=table(['Produkt','Tema','Grunn','Kilde'],[(f['product'],f['semantic_subject']+' / '+f['semantic_dimension'],f['reason'],f['source_artifact']+'; '+f['source_location']) for f in SF if f['classification']=='REVIEW_REQUIRED'])
M+='\n\nEksempler: Storebrand Båt selvstendig maskinskade er ikke konkludert som falskt ukjent; Tryg Bobil får ikke MCs nyverdigaranti; Tryg Innbo Ekstras arvede fellesgarasjeverdi er en støtte-kandidat, ikke bevist feilbeløp. Frende Tilhenger2000/6000egenandel krever hierarkiavklaring.\n'
M+='\n## Positive kontroller og legitime utelatelser\n\n'+table(['Kilde-fact-ID','Eksakt produkt','Komponent','Semantikk','Klassifikasjon','Katalogkeys'],[(f['source_fact_id'],f['product'],f['component'] or 'BASE',f['structured_value'],f['classification'],', '.join(f['proposed_keys'])) for f in SF if f['classification'] in ['SOURCE_FACT_PRESENT_AND_CATALOGUED','SOURCE_FACT_CUSTOMER_SPECIFIC','NOT_COMPARISON_RELEVANT']])+'\n'
M+='\n## Visuell PDF-kontroll\n\nIf Hund side2 (nivåtabell) ble rendret med lokal PDF-motor og visuelt inspisert: '+out('if-dog-page2.png')+'. Øvrige kontroller bruker lokalt ekstrahert tekst; kompleks tabellstruktur og roterte tegn skal visuelt etterkontrolleres før endelig komplett-status.\n'
M+='\n## Fortsettelse\n\n'+out('resume.json')+' har alle eksakte identiteter og startfingeravtrykk. Ikke gjenta SHA/parsing av uendrede kilder; ikke gjenbruk en produkts konklusjon på en annen art/kanal bare fordi PDF-hashen er lik.\n'
(O/'manual-review.md').write_text(M)
S='# SOURCE → CATALOG COMPLETENESS AUDIT\n'
S+=sec('SOURCE_CATALOG_COMPLETENESS_AUDIT','**PARTIAL.** Den skjulte kilde→katalog-mangelen er bevist, men hele katalogen er ikke semantisk ferdigrevidert. Ingen produkt- eller familiegjennomgang erklæres komplett. Dette er et etterprøvbart revisjonscheckpoint, ikke en ferdig godkjenning av204 produkter.')
S+=sec('VERSION',f"- Run: `{J['metadata']['run_id']}`\n- Tid: `{J['metadata']['timestamp']}`\n- Branch: `main`\n- HEAD: `{J['metadata']['head']}`\n- Working tree: clean før og etter.\n- Catalog SHA-256: `{J['metadata']['catalog_fingerprint']}`\n- Source corpus SHA-256: `{J['metadata']['source_corpus_fingerprint']}`\n- Full integritetskontroll: {out('repo-integrity.json')}.")
S+=sec('SCOPE',f"**204 produkter,202 aktive i produktmodus,2 historiske,84 add-ons,12 familier,10 provider-IDer,3 agreement scopes.** Historiske Eika Reise-produkter ble ikke aktivert.\n\nScope er `ordinary`, `ordinary-sparebank1` og `ordinary-dnb`. De7 ikke-ordinary MC/Bobil-produktene beholdes separat.2 av disse har målrettede kontroller;5 gjenstår. Nullversjon beholdes som null, aldri erstattet med kilde-/hentedato.\n\n4 922 base-fact-forekomster,5 646 base+tilgjengelige tillegg per produkt,3 819 komponentdefinisjoner og5 435 materialiserte aktive produktfacts er ulike telleenheter. Ingen av disse er antall komplette semantiske kildefakta.")
S+=sec('AUDIT METHOD','1. Frys HEAD,Git-status og SHA-256 for alle tracked/untracked prosjektfiler.\n2. Enumerer faktisk runtime-katalog inkl. arv,tillegg,scope,kilder og materialisering.\n3. Oppdag lokale originaler også uten runtime-lenker; verifiser tilgjengelige manifest-/source-hasher og dedupliser tekstlesing på hash.\n4. Les lokale fullvilkår/IPID/produktsider utover allerede modellerte keys. Bind hver påstand til eksakt produkt,type,nivå,scope,komponent og kildepunkt.\n5. Sammenhold kildepåstander med hele relevante base-/tilleggsnapshot; en manglende nøkkel alene er ikke bevis. Bevar kundevalg,kvalifikasjoner og leverandørspesifikke mekanismer.\n6. Prøv utvalgte allerede beviste mangler i eksisterende rene comparison/presentation-funksjoner;ikke all-pairs.\n7. Registrer motsatt kontroll katalog→kilde,men merk uprøvde påstander UNREVIEWED.\n\nKildelesingen var ikke fullstendig blind mot katalogen for alle familier. If-pakken ble lest før eksakt nøkkelkontroll; øvrige hadde kombinert lesing/motkontroll. Dette er ikke formell eller matematisk bevisføring for hele katalogen.')
S+=sec('PRODUCT COVERAGE',f"204/204 strukturelt registrert. **31 delvis semantisk kontrollert,173 ikke startet semantisk,0 fullstendig lukket.** Alle204 trenger full kildepakke-/støttelukking.\n\n{out('product-ledger.csv')} viser hver identitet og resterende arbeid. `MATERIAL_GAPS` betyr påvist materiell mangel,ikke ferdig produktaudit. Tom `supported_catalog_fact_count` betyr ikke målt,ikke null støttede fakta.")
S+=sec('ADD-ON COVERAGE',f"84/84 registrert;7 har kontrollerte dimensjoner,77 ikke semantisk startet,0 komplette. Tilleggsforekomster per produkt teller flere ganger i faktainventaret,men addondefinisjoner telles én gang. Valgfrie komponenter holdes valgfrie. Frende Snøscooters kildebelagte ulykkesvalg finnes ikke blant disse84.\n\n{out('addon-ledger.csv')}.")
S+=sec('SOURCE COVERAGE',f"322 originalfiler =246PDF+76HTML.291 unike SHA-256,31 duplikatbaner.1 437 unike PDF-sider ble tekstekstrahert.356 runtime source records og5 manifests kartlagt.0 hashavvik mot deklarerte hasher,0 uløste runtime-lenker,0 uleselige filer og0 nesten tomme uttrekk.\n\n38 filbaner/36 unike kildeartefakter inngår i registrert delvis manuell lesing.43 originaler har ingen direkte runtime source record;det gjør dem ikke ugyldige eller automatisk anvendelige.\n\n**Parsing er ikke semantisk revisjon.** Oppdaterte aktive nettsider er ikke kontrollert. Full kildepakke per produkt er ikke lukket. {out('source-artifact-ledger.csv')}, {out('source-record-ledger.csv')}, {out('source-package-summary.csv')}.")
S+=sec('BLINDSPOT VALIDATION','**Bekreftet.** If Hund Standard allergibehandling,Tryg Hund CT/MR,Storebrand Båt redning/ulykke/opplagsutstyr og Fremtind MC nyverdi finnes i egne lokale kilder,men mangler relevante katalogdimensjoner.\n\nIfs ulykkestannbehandling finnes eksplisitt på alle tre nivåer i både Hund og Katt,samtidig som ingen eksisterende peer eksponerte samme nøkkel. Dette er et blindfelt som all-pairs/unknown-telling alene ikke finner. Det er ikke brukt til å anta at alle providers har lik tanndekning.')
S+=sec('GLOBAL CATALOG STATUS','**REMEDIATION_REQUIRED**,foreløpig og basert på kontrollerte materielle funn. Ukontrollert scope kan ha flere mangler. Ingen katalogbred READY-attest er gitt.')
S+=sec('CATALOG PILOT GATE','**REMEDIATION_REQUIRED.** Svar på om en NITO-rådgiver nå kan stole på den komplette produktsammenligningen som beslutningsstøtte: **NEI – REMEDIERING KREVES.**\n\nDette bygger på konkrete lokale kildebelagte P1-hull,ikke et krav om at alle vilkårssetninger skal bli UI-rader. Allerede riktige dimensjoner er fortsatt nyttige. Produktkorrekthet og den separate NITO security/GDPR-gaten er ulike vurderinger.')
S+=sec('FAMILY RESULTS',table(['Familie','Produkter','Delvis/komplett','Kilde-facts','Representert','Mangler','For grovt','P1','P2','Status'],[(f['family'],f['products'],str(f['products_partially_reviewed'])+'/0',f['sourcefacts'],f['represented'],f['missing'],f['too_coarse'],f['P1'],f['P2'],f['family_status']) for f in J['family_results']])+'\n\nAlle12 checkpoints er INCOMPLETE. Hus/Reise har ingen påvist mangel i den begrensede kontrollen;det er ikke en NO_MATERIAL_GAP_FOUND-attest. Familiens kildefilantall overlapper og skal ikke summeres som unike originaler. '+out('family-summary.csv')+'.')
S+=sec('P0 FINDINGS','**P0=0 påvist.** Den uferdige revisjonen beviser ikke fravær av P0 i hele katalogen.')
S+=sec('P1 FINDINGS','**88 eksakte produkt-/dimensjonsforekomster,52 dedupliserte signaturer.** Hver har kildepunkt,offentlig kildeparafrase,eksakt katalogtilstand,produktidentitet,rotårsak og manuell dimensjonskontroll.\n\n'+table(['Årsak','P1-forekomster','Konkrete grupper som må vurderes'],[
 ('SCRC-001 Tryg Hund/Katt',13,'Standardegenandel2500;sum per sykdom/ulykke OG år;CT/MR;livslang behandling;Ekstra-egenandeler;livsreduksjon;Katt TR-særgrense.'),
 ('SCRC-002 If Hund/Katt',27,'Ulykkestannbehandling alle nivåer;Basis medisin hos veterinær;Standard tann-livstidsgrense/allergi;Super skadefritt-årsvilkår for rollover;KattSuperTR;ventetid/flytteunntak;livslang veterinær.'),
 ('SCRC-003 Storebrand Båt',28,'Ansvarssummer i SDR;rettshjelp sum/egenandel;ulykke;bagasje inkl. unntak for gjenstand over15000;redning/egenandel;brann/tyveri-egenandel;opplagsutstyr;rigg;Super sesong/dagssats,ny/brukt totalskade og jolle.'),
 ('SCRC-004 Frende kjøretøy',16,'Rettshjelpgrenser/egenandel;Snøscooter tyverioppgjør60% uten gjenanskaffelse innen60d;valgfri ulykke;Campingvogn gjenstandsgrense og utleie-tilleggsegenandel.'),
 ('SCRC-005 Tryg eldre familier',2,'Innbo/Basis ogEkstra minimum8000egenandel ved terreng-/grunnvann.'),
 ('SCRC-006 Fremtind scoped MC/Bobil',2,'MC Kasko nyverdi3mnd/2000km med øvrigevilkår;BobilTopp leasing/startleie-oppgjørsmodell.')])+'\n\n**Alle52 P1-grupper er listet enkeltvis** med identiteter og bevis i '+out('manual-review.md')+'. Alle88 forekomster finnes i '+out('gap-findings.csv')+'. Tallene betyr ikke88 uavhengige rotårsaker eller88 feil i sammenligningsmotoren.')
S+=sec('P2 / P3 SUMMARY','P2=47forekomster/30signaturer;P3=0 registrert. Blant mønstrene er hendelsesspesifikke egenandelslettelser,aldersfradrag,transport-/sykehusfordeler,geografi og underdetaljer for medisin/rehabilitering. Dette er kandidater til nested detaljer. Lavere prioritet kan vurderes etter full audit;de skal ikke automatisk fylles inn som symmetriske universalfakta.')
S+=sec('VERIFIED CATALOG FALSE UNKNOWNS',table(['Eget produkt','Manglende nøkkel','Kildebevis','Runtime'],[(f['product_identity'],f['key'],', '.join(f['source_fact_ids']),f['display_text']) for f in J['blindspot_validation']['visible_false_unknowns']])+'\n\n6 bekreftede synlige tilfeller,alle med samme resultat ved sidebytte. Dette er diagnostiske cases,ikke totalt antall false unknowns. To tann-prober hadde ingen peer-rad og er derfor ikke telt som synlig unknown. '+out('verified-false-unknowns.json')+' og '+out('runtime-probes.json')+'.')
S+=sec('TOO-COARSE FACTS','45 kontrollerte forekomster. Eksempler: If Standard viser riktig tannbeløp,men utelater at grensen gjelder **hele dyrets liv**. If Super beskriver ubrukt sumoverføring,men utelater **skadefritt år**. Tryg peker bare på beviset når standardegenandel står i fullvilkåret. Storebrand Super har ferieavbruddets antall/sum,men mangler **dagssats og sesong**. Dette er betydningsbærende dimensjoner,ikke ønske om lengre markedsføringstekst.')
S+=sec('UNSUPPORTED CATALOG CLAIMS','0 endelig bevist;full reverse-audit er ikke ferdig.1 eksplisitt kandidat: **Tryg Innbo Ekstra — tyveri.fellesgarasje.grense**,arvet15000 fraBasis. Ekstra har egne tyverivilkår. Hele gjenværende kildepakke må lukkes før påstanden klassifiseres som unsupported eller endres. '+out('unsupported-catalog-facts.csv')+' og '+out('catalog-fact-support.csv')+'.')
S+=sec('SEMANTIC MISMATCHES','0 separat klassifiserte/beviste nøkkel-feil i det kontrollerte utvalget. Betydningsforskyvning fra utelatt periode/betingelse er klassifisert TOO_COARSE for å unngå dobbelttelling. Mulig Innbo-arverest og trailer-egenandelsforrang er REVIEW_REQUIRED. Ingen eksisterende km-/pris-/coverage-statusfeil er antatt på nytt.')
S+=sec('POSITIVE CONTROLS','### HUND\n\nIf Liv er fortsatt separat,valgfritt og rase-/artsavhengig. Tryg Ekstra bevarer10000rehab og30000tannramme. Faktisk valgt veterinærsum/egenandel holdes kundespesifikk.\n\n### BOBIL\n\nTryg Ekstra bevarer100000løsøre,10000gjenstand,15000fortelt samt fuktalder/egenandel/unntak og feriegaranti. FremtindDNB Topp bevarer parkeringsalder,ferie1500/dag15d og autorisert årlig fuktkontroll.\n\n### BÅT\n\nStorebrand bevarer sesongavgrenset geografi og grunnleggende kasko. Ingen uavhengig maskinskadedekning oppfunnet fra kaskohendelser. Kundens båtverdi/valgte egenandel fylles ikke inn som sikkert valgt.\n\n### MC\n\nTryg bevarer1år/10000km/>80%,glass kun3-/4hjulsMC,maskinskade8år og egenandelsintervaller. FremtindSB1s spesifikke MC-leiebil350/dag15d er korrekt beholdt tross generelt leiebilunntak i nabopunkt. Glass for andre kjøretøytyper ble ikke overført til MC.\n\n73 representerte source-fact-forekomster,19 kundespesifikke og18 administrative/annenprodukt-henvisninger. Dette er dimensjonskontroller,ikke godkjenning av hele produktene.')
S+=sec('SOURCE PACKAGE GAPS','Alle356 runtime-kilder kan knyttes til lokale originaler. Ingen bevist korrupt fil. **Semantisk pakkeavgrensning gjenstår for alle204 produkter.** Dette skal ikke kalles «manglende dokument» uten mer kontroll. Trygs behandling-/produktvilkår finnes allerede lokalt selv om basens runtime-seed bygger på IPID. Ingen ny nedlasting trengs for de dokumenterte gapene.')
S+=sec('SOURCE CONFLICTS','- **SC-001:** TrygHund livsreduksjon,eldste rasegruppe:fullvilkår9år mot lagret produktside10år. Den uomstridte20%-/gulvmodellen er rapportert separat;startalderen er ikke valgt vilkårlig.\n- **SC-002:** FrendeTilhenger har2000særregel og generelle6000brann/tyveriregler. Dette er foreløpig forrangs-/tolkningsspørsmål,ikke bevist to aktive motstridende satser.\n\nKildenes faktiske versjon/virkeområde må avklares;metadata/hentedato løser ikke materiell konflikt.')
S+=sec('CANONICAL MODEL GAPS','Ingen bred engine-/schema-blokkering er bevist. Mange mangler passer eksisterende canonical keys. Enkelte provider-spesifikke oppgjørs-/tjenesteregler mangler en avklart detaljplassering;vurder begrenset registry/metadata-utvidelse etter audit. Ingen automatisk symmetri eller «alle selskaper må ha samme fact»-krav. '+out('family-semantic-map.csv')+'.')
S+=sec('PRESENTATION GAPS','Ingen selvstendig ny UI-feil er bevist. Seks kontroller viser at UI gjengir den sparsomme katalogen som unknown. Riktig tiltak vil være kildebelagt katalog-/dimensjonsarbeid etter review,ikke at UI tolker PDF eller skjuler unknown. Source-fakta uten peer-nøkkel viser også at kompletthet ikke kan avgjøres fra dagens UI alene.')
S+=sec('ROOT CAUSE CANDIDATES',table(['ID','Lag / konkret mekanisme','Bevis','Forekomster'],[(r['root_cause_id'],r['description'],r['evidence'],r['finding_count']) for r in J['root_causes']])+'\n\nBuilder/resolver materialiserer de oppgitte radene;de inspiserte manglene er synlige allerede i authoredcatalog. Dette beviser lokalisering av tapet,men ikke hvorfor tidligere forfatter valgte utvalget. Generelle «katalogen trenger mer data»-funn uten konkret kilde og produkt er ikke opprettet. '+out('root-cause-candidates.csv')+'.')
S+=sec('PDF / CUSTOMER IMPACT','Ingen kundedokumenter eller private blindtester ble brukt. Manglende katalogdimensjoner kan også svekke enrichment ved dokumentstillhet,men det er ikke bevis for en extraction-feil. Enhver senere rettelse må bevare document>catalog,selected/not_selected/unknown,kundevalgte summer og valgfrie tillegg. Ingen nye AI-kall eller promptendringer er nødvendige for å forklare de beviste kataloghullene;eventuelle nye nøkkeldimensjoner må vurderes separat i customerflow.')
S+=sec('REMEDIATION BATCHES',table(['Batch','Omfang','Kompleksitet','Status'],[(b['batch_id'],', '.join(b['families']),b['complexity'],b['status']) for b in J['remediation_batches']])+'\n\nAlle forslag er inaktive. Sourcebinding,type/scope/version,nivåarv,optional-status og dokumentprioritet må bevares. '+out('remediation-batches.csv')+'. Ikke begynn retting på grunnlag av dette checkpointet før resterende audit og human review.')
S+=sec('SOURCE RESEARCH QUEUE',table(['ID','Problem','Lokalt først','Ekstern kilde bare ved fortsatt uklarhet'],[(q['queue_id'],q['reason'],q['local_work_first'],q['external_source_needed_if_unresolved']) for q in J['source_research_queue']])+'\n\nIngen ny research er gjennomført. Eksisterende dokumentmetadata med ukjent dato forblir ukjent. Den store restmengden skyldes uferdig gjennomgang,ikke påvist fravær av lokale kilder.')
S+=sec('DEEP REVIEW','11 produkter har omfattende lokale kildepakke-lesinger (Tryg/IfHund/Katt og StorebrandBåt),13 har målrettet hele-dokument-kontroll og7 har seksjonskontroll. **0 har full kildefactinventering og motsatt støttekontroll ferdig.** Kravet≥24 komplette dybdegjennomganger og≥2 per familie er ikke oppfylt. Se '+out('manual-review.md')+'.')
S+=sec('AUDIT QUALITY CHECK','Avstemming:253 source-fact-forekomster=73representert+90mangler+45forgrovt+19kundevalg+18administrativt+8review.135funn=88P1+47P2=82unikesignaturer;ingen P0/P3 registrert.31delvis+173ikke-startet=204.7delvis+77ikke-startet=84tillegg.\n\nUtvidet kontroll av JSON/CSV,ID-er,lenker,hash og krysstelling skrives i '+out('quality-check.json')+'. Ingen kompletthetsprosent beregnes fordi totalt antall relevante kildefakta ikke er kjent. Positivekontroller og nulldata er ikke brukt til provider-ranking.')
S+=sec('REPO INTEGRITY','**UNCHANGED.** HEAD,branch,status,stageddiff,trackeddiff,untrackedfingerprint og innholdshasher for alle prosjektfiler er identiske med baseline. `git diff --check`bestått.\n\nIngen endring i kode,katalogfacts,canonicaldata,manifester,originalkilder,tester eller repodokumentasjon. Ingen .env/Railway/tracing,Gitmutasjoner eller deploy. Alle auditverktøy og resultater er under`/tmp/source-catalog-completeness-audit/`. Forrige`/tmp/nito-prepilot-audit/`er bevart.')
required=['audit-summary.md','audit.json','product-ledger.csv','addon-ledger.csv','gap-findings.csv','source-fact-inventory.csv','family-summary.csv','root-cause-candidates.csv','manual-review.md']
extra=['source-artifact-ledger.csv','source-record-ledger.csv','source-package-summary.csv','catalog-fact-support.csv','unsupported-catalog-facts.csv','family-semantic-map.csv','remediation-batches.csv','source-research-queue.csv','verified-false-unknowns.json','runtime-probes.json','repo-integrity.json','quality-check.json','resume.json']
S+=sec('OUTPUT FILES','\n'.join('- '+out(n) for n in required)+'\n\nTilleggsfiler:\n\n'+'\n'.join('- '+out(n) for n in extra)+'\n\nReproduserbare scripts,catalogsnapshot,baseline,corpusmetadata og lokale tekstcacher ligger i samme midlertidige mappe. Ingen DOCX laget;ingen filer kopiert inn i repo.')
S+=sec('LIMITATIONS','\n'.join('- '+x for x in J['limitations'])+'\n- Semantisk model reasoning er ikke matematisk bevis eller juridisk avgjørelse av et erstatningskrav.\n- Resultatet gjelder dette lokale kildegrunnlaget;offentlig kildeferskhet er ikke uavhengig verifisert.\n- Auditens omfang overstiger ferdig semantisk kontroll i denne gjennomgangen;statusen skal ikke løftes til COMPLETE ved å telle parse-/ledger-rader.')
S+=sec('RECOMMENDATION','Katalogen skal ikke gis en samlet NITO-rådgivergodkjenning nå. Bevar kjente riktige mekanismer,og bruk de konkrete P1-funnene i human review. **Neste handling er å fortsette denne auditen**,ikke implementere alle kandidater eller bestille generell ny research. Dette følger PARTIAL-regelen og unngår endringer basert på uferdig støtte-/scopekontroll.')
S+=sec('NEXT STEP','Fortsett fra '+out('resume.json')+' etter kontroll av samme HEAD og fingeravtrykk. Fullfør31 delvis reviderte produkter,173 øvrige og alle84 tillegg,med24+ komplette dybdekontroller og minst2 per familie. Rebruk faktiske kildeuttrekk,ikke arts-/nivåkonklusjoner. Lukk deretter reverse support og velg ett human-review/remedieringsoppdrag. Ingen av disse neste oppgavene er startet her.\n\n**SOURCE_CATALOG_COMPLETENESS_AUDIT_PARTIAL**')
(O/'audit-summary.md').write_text(S)
print('report written',len(S),'manual',len(M))
