import type { CatalogSource } from "./product-catalog.ts";
import { buildBoatPetCatalog, type BoatPetAddOnDefinition, type BoatPetProductDefinition, type BoatPetRow } from "./boat-pet-catalog-builder.ts";
import type { AgreementScopeDefinition } from "./agreement-scope.ts";

type SourceSeed = {
  id?: string;
  providerId: string; company: string; type: "båt" | "hund" | "katt"; filename: string;
  version: string; termsNumber: string; url: string; sha256: string; sourceType?: CatalogSource["sourceType"];
};

const sourceSeeds: SourceSeed[] = [
  { id: "boat-pet:tryg:hund:treatment", providerId: "tryg", company: "Tryg", type: "hund", filename: "tryg-dog-treatment-terms.pdf", version: "2026-01-01", termsNumber: "PLB52002", url: "https://www.tryg.no/forsikringer/dyreforsikring/hundeforsikring", sha256: "63af7ce2b7ce309879d3e97cdfca3014ba249f1dc7347eef44bd7c768fd162d3" },
  { id: "boat-pet:tryg:hund:product", providerId: "tryg", company: "Tryg", type: "hund", filename: "tryg-dog-product-terms.pdf", version: "2026-05-10", termsNumber: "PLB52000", url: "https://www.tryg.no/forsikringer/dyreforsikring/hundeforsikring", sha256: "a7936fd27cd305b1a6eeb8153d8289dffff5c075e0e50ffbd9590f8bb2d83318" },
  { id: "boat-pet:tryg:katt:treatment", providerId: "tryg", company: "Tryg", type: "katt", filename: "tryg-cat-treatment-terms.pdf", version: "2026-07-01", termsNumber: "PLB52006", url: "https://www.tryg.no/forsikringer/dyreforsikring/katteforsikring", sha256: "fa7297b2b37cab3f8e8d51151643bcd4293fc7fbb0a33f77de86108af16bf9dc" },
  { id: "boat-pet:tryg:katt:product", providerId: "tryg", company: "Tryg", type: "katt", filename: "tryg-dog-product-terms.pdf", version: "2026-05-10", termsNumber: "PLB52000", url: "https://www.tryg.no/forsikringer/dyreforsikring/hundeforsikring", sha256: "a7936fd27cd305b1a6eeb8153d8289dffff5c075e0e50ffbd9590f8bb2d83318" },
  { providerId: "tryg", company: "Tryg", type: "båt", filename: "tryg-boat-ipid.pdf", version: "2024-07-01", termsNumber: "IPID Fritidsbåtforsikring", url: "https://www.tryg.no/system/files/download/pdf/ipid/IPID-Batforsikring.pdf", sha256: "75d8af24d727a2994d3fc2ae566ad075f1cb7f7edad4993d78c3b59bc1700ff5", sourceType: "ipid" },
  { providerId: "tryg", company: "Tryg", type: "hund", filename: "tryg-pet-ipid.pdf", version: "2026-09-01", termsNumber: "IPID Dyreforsikring", url: "https://www.tryg.no/system/files/download/pdf/ipid/IPID-Hund-og-katt.pdf", sha256: "41843abc16ad8ee39782e70f29d8cbb115463bcebe28882cca42078ce07fd824" , sourceType: "ipid"},
  { providerId: "tryg", company: "Tryg", type: "katt", filename: "tryg-pet-ipid.pdf", version: "2026-09-01", termsNumber: "IPID Dyreforsikring", url: "https://www.tryg.no/system/files/download/pdf/ipid/IPID-Hund-og-katt.pdf", sha256: "41843abc16ad8ee39782e70f29d8cbb115463bcebe28882cca42078ce07fd824", sourceType: "ipid" },
  { id: "boat-pet:tryg:båt:machinery", providerId: "tryg", company: "Tryg", type: "båt", filename: "tryg-boat-machinery-terms.pdf", version: "2026-01-01", termsNumber: "PFB36910", url: "https://www.tryg.no/forsikringer/kjoretoy/batforsikring", sha256: "c4a722384e402e7581f9a2b718b0fbe90b622912261b41279e1904a9d960f50d" },
  { id: "boat-pet:tryg:båt:accident", providerId: "tryg", company: "Tryg", type: "båt", filename: "tryg-boat-accident-terms.pdf", version: "2022-02-01", termsNumber: "PFB38900", url: "https://www.tryg.no/forsikringer/kjoretoy/batforsikring", sha256: "0d1cbbbdc41c4ee3a25a511eac8fdd194737bce2577c9a657256589ae221b95c" },
  { id: "boat-pet:tryg:hund:extra", providerId: "tryg", company: "Tryg", type: "hund", filename: "tryg-dog-extra-terms.pdf", version: "2025-07-01", termsNumber: "PLB52003", url: "https://www.tryg.no/forsikringer/hundeforsikring", sha256: "10972b0580b3cc804419621d3c5193d9be3e8bc24e8bafb58519e6e0a203af2c" },
  { id: "boat-pet:tryg:katt:extra", providerId: "tryg", company: "Tryg", type: "katt", filename: "tryg-cat-extra-terms.pdf", version: "2025-07-01", termsNumber: "PLB52004", url: "https://www.tryg.no/forsikringer/katteforsikring", sha256: "f4267143ea6f0643341503cf60ce50ce7036cf83af21b3ec29f514d1a7738972" },
  { id: "boat-pet:tryg:hund:life", providerId: "tryg", company: "Tryg", type: "hund", filename: "tryg-dog-life-terms.pdf", version: "2026-01-01", termsNumber: "PLB52001", url: "https://www.tryg.no/forsikringer/hundeforsikring", sha256: "5d5e22fa589538a2708b87616b339eec0c3f0a27c5b322fa48d1b4582e013fcc" },
  { id: "boat-pet:tryg:katt:life", providerId: "tryg", company: "Tryg", type: "katt", filename: "tryg-cat-life-terms.pdf", version: "2026-01-01", termsNumber: "PLB52005", url: "https://www.tryg.no/forsikringer/katteforsikring", sha256: "8024b9853d3ff80259f939418f31f03e332d280bfca612d613390a7699e5eb3c" },
  { providerId: "if", company: "If", type: "båt", filename: "if-boat-terms.pdf", version: "2023-02-01", termsNumber: "BÅT2-1", url: "https://if.no/apps/vilkarsbasendokument/Vilkaar?produkt=B%C3%A5tforsikring", sha256: "57e7aac8542dd10bfc92611f380b68754905b6808a66590307af86517c2072ae" },
  { providerId: "if", company: "If", type: "hund", filename: "if-dog-terms.pdf", version: "2022-12-01", termsNumber: "Hundeforsikring", url: "https://if.no/apps/vilkarsbasendokument/Vilkaar?produkt=Hundeforsikring", sha256: "d2372736a4d99d4c434ac87ea068c5051908742ae03e454220b6b1cc1d436c75" },
  { providerId: "if", company: "If", type: "katt", filename: "if-cat-terms.pdf", version: "2022-12-01", termsNumber: "Katteforsikring", url: "https://if.no/apps/vilkarsbasendokument/Vilkaar?produkt=Katteforsikring", sha256: "bcd631394fbfe7d0a6f0de3d7e79dc82aee2f5d5bb16d4a0b7192e177716abe7" },
  { providerId: "gjensidige", company: "Gjensidige", type: "båt", filename: "gjensidige-boat-ipid.pdf", version: "", termsNumber: "EAP14", url: "https://www.gjensidige.no/forsikring/batforsikring", sha256: "c0e14e39f1c5dce3c6d238e8822eb14267e998ad0e762f08887d05bc3cb9c7a0", sourceType: "ipid" },
  { providerId: "gjensidige", company: "Gjensidige", type: "hund", filename: "gjensidige-dog-ipid.pdf", version: "", termsNumber: "EAP32", url: "https://www.gjensidige.no/forsikring/dyreforsikring/hundeforsikring", sha256: "aa39107d5777e4f0a342918ef9e4ceba8828793665a3dc2eb41172107d1404ba", sourceType: "ipid" },
  { providerId: "gjensidige", company: "Gjensidige", type: "katt", filename: "gjensidige-cat-ipid.pdf", version: "", termsNumber: "EAP30", url: "https://www.gjensidige.no/forsikring/dyreforsikring/katteforsikring", sha256: "314d266136da6b7b5aec994b70d45591e687bd5baac203fe0609437e7fdc4ee8", sourceType: "ipid" },
  { id: "boat-pet:gjensidige:hund:life-use", providerId: "gjensidige", company: "Gjensidige", type: "hund", filename: "gjensidige-dog-life-use-terms.pdf", version: "", termsNumber: "Hund Liv og Bruk", url: "https://www.gjensidige.no/forsikring/dyreforsikring/hundeforsikring", sha256: "90536e3520ee46f476f480be9760bc92bd40162e29fd53e914df44b70ea150ea", sourceType: "full_terms" },
  { id: "boat-pet:gjensidige:katt:life-use", providerId: "gjensidige", company: "Gjensidige", type: "katt", filename: "gjensidige-cat-life-use-terms.pdf", version: "", termsNumber: "Katt Liv og Bruk", url: "https://www.gjensidige.no/forsikring/dyreforsikring/katteforsikring", sha256: "47750999d5bdbe5fc9bf5a2ffe24def17dd1664a2b8f9886bc7868dbf8049f5e", sourceType: "full_terms" },
  { id: "boat-pet:gjensidige:hund:product", providerId: "gjensidige", company: "Gjensidige", type: "hund", filename: "gjensidige-dog-product.html", version: "", termsNumber: "Hundeforsikring – produktoversikt", url: "https://www.gjensidige.no/forsikring/dyreforsikring/hundeforsikring", sha256: "fd3fcb6e6b69803bcf7fdaeec80802fab764f74a0f465e5fd5c063c2eed8db58", sourceType: "product_page" },
  { id: "boat-pet:gjensidige:katt:product", providerId: "gjensidige", company: "Gjensidige", type: "katt", filename: "gjensidige-cat-product.html", version: "", termsNumber: "Katteforsikring – produktoversikt", url: "https://www.gjensidige.no/forsikring/dyreforsikring/katteforsikring", sha256: "f9bc6e31f84bfe1660b0014798ce144fa6fc5ee7f34ccbe14acf28feab883d4f", sourceType: "product_page" },
  { providerId: "storebrand", company: "Storebrand", type: "båt", filename: "storebrand-boat-terms.pdf", version: "2024-09-01", termsNumber: "båt03", url: "https://www.storebrand.no/privat/forsikring/batforsikring", sha256: "e945049a6b9fba643d9804279690fc8e1dfbb1cd4a419a81503e58fd5b959baa" },
  { providerId: "storebrand", company: "Storebrand", type: "hund", filename: "storebrand-pet-terms.pdf", version: "2025-02-01", termsNumber: "dyr04", url: "https://www.storebrand.no/privat/forsikring/hundeforsikring", sha256: "b236f856380b8010c7439765ea72a88d076e5d387d4653a7f033980892732591" },
  { providerId: "storebrand", company: "Storebrand", type: "katt", filename: "storebrand-pet-terms.pdf", version: "2025-02-01", termsNumber: "dyr04", url: "https://www.storebrand.no/privat/forsikring/katteforsikring", sha256: "b236f856380b8010c7439765ea72a88d076e5d387d4653a7f033980892732591" },
  { providerId: "sparebank1-fremtind", company: "Fremtind", type: "båt", filename: "fremtind-boat-terms.pdf", version: "2024-06-10", termsNumber: "PMO-380.000-004", url: "https://www.sparebank1.no/nb/bank/privat/forsikring/batforsikring.html", sha256: "1364fc8bde39923ea1e9f0f36a9d9abf5596721958114b93485b5c730d70669f" },
  { providerId: "sparebank1-fremtind", company: "Fremtind", type: "hund", filename: "fremtind-dog-vet-terms.pdf", version: "2025-08-07", termsNumber: "PBK-231.200-004", url: "https://www.sparebank1.no/nb/bank/privat/forsikring/hundeforsikring.html", sha256: "5897fd60318410bdc5481e12d4cd6454e7fe4741682a13e5289991f211b7d9f7" },
  { providerId: "sparebank1-fremtind", company: "Fremtind", type: "katt", filename: "fremtind-cat-vet-terms.pdf", version: "2025-08-07", termsNumber: "PBK-231.300-002", url: "https://www.sparebank1.no/nb/bank/privat/forsikring/katteforsikring.html", sha256: "91385b8b466923a5ca1c37d8f53781c5af3f63e3f6e037afae367f4399b75286" },
  { id: "boat-pet:sparebank1-fremtind:hund:life", providerId: "sparebank1-fremtind", company: "Fremtind", type: "hund", filename: "fremtind-dog-life-terms.pdf", version: "2025-08-07", termsNumber: "PBK-231.210-002", url: "https://www.sparebank1.no/nb/bank/privat/forsikring/hundeforsikring.html", sha256: "8445f2c6faede5cfe1c6054e58cc880fc4cea1bbc31321ddc76fdbd035dcf43d" },
  { id: "boat-pet:sparebank1-fremtind:katt:product", providerId: "sparebank1-fremtind", company: "Fremtind", type: "katt", filename: "fremtind-sb1-cat-product.html", version: "", termsNumber: "Katteforsikring – produktoversikt", url: "https://www.sparebank1.no/nb/bank/privat/forsikring/katteforsikring.html", sha256: "5b962b11a638938059382c92afd678406585edc9c97b74de7f659286441d217b", sourceType: "product_page" },
  { id: "boat-pet:sparebank1-fremtind:katt:life", providerId: "sparebank1-fremtind", company: "Fremtind", type: "katt", filename: "fremtind-cat-life-terms.pdf", version: "2025-08-07", termsNumber: "PBK-231.310-002", url: "https://www.sparebank1.no/nb/bank/privat/forsikring/katteforsikring.html", sha256: "9b9b295ff51687c8361c1e2fb8fc192fb26fbc0112d5e78b4e569b9d6c4c27ac" },
  { id: "boat-pet:sparebank1-fremtind:hund:use", providerId: "sparebank1-fremtind", company: "Fremtind", type: "hund", filename: "fremtind-dog-use-terms.pdf", version: "2025-08-07", termsNumber: "PBK-231.220-002", url: "https://www.sparebank1.no/nb/bank/privat/forsikring/hundeforsikring.html", sha256: "456a1c4f38b4c3934bf0b4c9ed1167e805d5238fb1960115d9cb1e2e65aafcc2" },
  { providerId: "frende", company: "Frende", type: "båt", filename: "frende-boat-terms.pdf", version: "2026-01-01", termsNumber: "Båtforsikring", url: "https://www.frende.no/forsikringer/batforsikring/", sha256: "272b9c86efaf39c30930b284fdadc49019d4e2f98ca13c2de426d0ec2f4f66d0" },
  { providerId: "frende", company: "Frende", type: "hund", filename: "frende-dog-terms.pdf", version: "2026-01-01", termsNumber: "Hundeforsikring", url: "https://www.frende.no/forsikringer/hundeforsikring/", sha256: "6d052e5092d9f92050dcf95a92fa6ce5deda18a5825cdd00ca1c8cd2658c9135" },
  { providerId: "frende", company: "Frende", type: "katt", filename: "frende-cat-terms.pdf", version: "2026-01-01", termsNumber: "Katteforsikring", url: "https://www.frende.no/forsikringer/katteforsikring/", sha256: "5c7791b59cf84da6ef475020f997bac1cc13a865777bdc791b2c3f7ba4b4fe6b" },
];

const sourceId = (providerId: string, type: string) => `boat-pet:${providerId}:${type}`;
export const boatPetSources: Record<string, CatalogSource> = Object.fromEntries(sourceSeeds.map((seed) => {
  const id = seed.id ?? sourceId(seed.providerId, seed.type);
  return [id, {
    id, filename: seed.filename, providerId: seed.providerId, company: seed.company,
    insuranceType: seed.type === "båt" ? "Båt" : seed.type === "hund" ? "Hund" : "Katt",
    agreementScope: "ordinary", sourceType: seed.sourceType ?? "full_terms", termsNumber: seed.termsNumber,
    effectiveFrom: seed.version, version: seed.version, url: seed.url, sha256: seed.sha256, documentName: seed.termsNumber,
  } satisfies CatalogSource];
}));

const row = (key: string, value: string, providerId: string, type: "båt" | "hund" | "katt", page: number, section: string, classification?: BoatPetRow["deductibleClassification"], exactSourceId?: string): BoatPetRow => ({
  key, value, sourceId: exactSourceId ?? sourceId(providerId, type), page, section,
  ...(classification ? { deductibleClassification: classification } : {}),
});

const boatCore = (providerId: string, geography: string): BoatPetRow[] => [
  row("bat.ansvar.dekning", "Inkludert", providerId, "båt", 1, "Produktoversikt"),
  row("bat.rettshjelp.dekning", "Inkludert", providerId, "båt", 1, "Produktoversikt"),
  row("bat.geografi.dekning", "Inkludert", providerId, "båt", 1, "Geografisk område"),
  row("bat.geografi.omrade", geography, providerId, "båt", 1, "Geografisk område"),
];
const boatFire = (providerId: string, geography: string): BoatPetRow[] => [
  ...boatCore(providerId, geography),
  row("bat.brann.dekning", "Inkludert", providerId, "båt", 1, "Brann"),
  row("bat.tyveri.dekning", "Inkludert", providerId, "båt", 1, "Tyveri"),
];
const boatKasko = (providerId: string, geography: string): BoatPetRow[] => [
  ...boatFire(providerId, geography),
  row("bat.kasko.dekning", "Inkludert", providerId, "båt", 1, "Kasko"),
  row("bat.redning.dekning", "Inkludert", providerId, "båt", 1, "Redning og berging"),
  row("bat.transport.dekning", "Inkludert ved dekningsmessig skade", providerId, "båt", 1, "Transport"),
];
const product = (
  providerId: string, company: string, name: string, rows: BoatPetRow[], version: string | null,
): BoatPetProductDefinition => ({
  providerId, company, type: "båt", agreementScope: "ordinary",
  productId: `${providerId}-bat-${name.toLocaleLowerCase("nb-NO").normalize("NFKD").replace(/\p{M}/gu, "").replace(/[^a-z0-9]+/gu, "-").replace(/^-|-$/gu, "")}`,
  name, version, sourceId: sourceId(providerId, "båt"), rows,
});

// Frende's own levels and source clauses; no changes to the shared boat seeds.
const frendeBoatRow = (key: string, value: string, page: number, section: string, classification?: BoatPetRow["deductibleClassification"]) =>
  row(key, value, "frende", "båt", page, section, classification);
const frendeBoatCore: BoatPetRow[] = [
  frendeBoatRow("bat.geografi.dekning", "Inkludert innenfor det dokumenterte fartsområdet", 2, "2"),
  frendeBoatRow("bat.geografi.omrade", "Norge, Sverige, Danmark og Finland samt 12 nautiske mil fra fastlandets grunnlinje; Kattegat og Skagerrak øst for Lindesnes–Hirtshals, Østersjøen, Finskebukta og Bottenvika. 1. mai–30. september også resten av Europa og 200 nautiske mil fra det europeiske fastlandets grunnlinje, samt overfart til Island, Storbritannia, Svalbard, Madeira, Azorene og Kanariøyene. Helårsutvidelse krever at utvidet fartsområde står i forsikringsbeviset.", 2, "2"),
  frendeBoatRow("bat.ansvar.dekning", "Rettslig erstatningsansvar som eier eller rettmessig fører for skade på andre personer eller andres ting. Gjelder alle båtforsikringer, bortsett fra båtmotor.", 9, "12.1"),
  frendeBoatRow("bat.ansvar.grense", "Per hendelse: 3 020 000 SDR for personskade og 1 510 000 SDR for tingskade. Ingen egenandel.", 10, "12.4"),
  frendeBoatRow("bat.ansvar.begrensning", "Omfatter ikke forsett, yrke eller virksomhet, ansvar overfor familien eller selskap hvor du/familien har styreverv, er daglig leder eller eier minst 50 %, egen andel av felleseie, krenkelser/bøter/gebyrer, lånte/brukte/oppbevarte ting, avtaleansvar eller frafalt regress. Forurensning må være plutselig og uforutsett; gradvise prosesser og forurensning fra grunnstøtt, forlist eller sunket båt er unntatt. Vrakfjerning omfattes bare som angitt i 5.3 nr. 4.", 9, "12.2"),
  frendeBoatRow("bat.rettshjelp.dekning", "Rettshjelp i Norden for personlig eier, rettmessig bruker eller fører. Omfatter tvist ved salg med opphørt forsikring og kjøp av nytt fartøy når nåværende fartøy var forsikret i Frende. Samme tvist blir ikke flere tvister ved flere spørsmål/søksmål. Voldgift og særdomstol omfattes når tvisten ellers kunne vært ført for alminnelige domstoler.", 10, "13.1, jf. 2"),
  frendeBoatRow("bat.rettshjelp.grense", "100 000 kr per tvist; 250 000 kr samlet ved tre eller flere parter på samme side, også på tvers av forsikringer/selskaper. Begrenset til den økonomiske interessen i saken. Uforsikrede parter bærer sin andel og holdes utenfor erstatningsberegningen.", 11, "13.4"),
  frendeBoatRow("bat.rettshjelp.egenandel", "4 000 kr pluss 20 % av øvrige kostnader; én egenandel per tvist også ved flere parter på samme side", 11, "13.4", "coverage"),
  frendeBoatRow("bat.rettshjelp.begrensning", "Rimelige og nødvendige utgifter til egen advokat, registrert rettshjelper, retten, godkjent advokatmekler og sakkyndige; ved rettsbehandling også vitner og rettsgebyr til forliksrådet/tingretten. Ikke ankegebyr, idømte eller avtalte saksomkostninger. Tilkjente omkostninger trekkes fra, med unntak ved dokumentert betalingsudyktig motpart. Unntatt tvist mellom sameiere, yrke/virksomhet, familie/arv/skifte, namsmyndigheter, ubestridt inkasso, gjeldsforhandling/konkurs/akkord, straffesak, krenkelser/bøter/gebyrer, ulovlig handling, forvaltningsvedtak før fullt utnyttet klageadgang og søksmål, advokat-/sakkyndigsalær og eget rettshjelpsavslag. Ikke utgifter før tvist eller grunnlag som oppstod før forsikringen.", 10, "13.2–13.3 (fortsatt side 11)"),
  frendeBoatRow("bat.jolle.dekning", "Egen jolle eller gummibåt inntil 10 fot, brukt sammen med båten, med tilhørende utenbordsmotor inntil 10 hk", 2, "3.2"),
  frendeBoatRow("bat.jolle.grense", "Inntil 20 000 kr totalt for jolle/gummibåt og tilhørende motor", 2, "3.2"),
];
const frendeBoatFire: BoatPetRow[] = [
  ...frendeBoatCore,
  frendeBoatRow("bat.brann.dekning", "Brann, lynnedslag og eksplosjon når brann og tyveri inngår i forsikringsbeviset", 3, "4.1.1"),
  frendeBoatRow("bat.brann.begrensning", "Varmgang i motor eller drivverk erstattes ikke, men følgeskade som skyldes brann omfattes. Delen eller komponenten der brann eller kortslutning oppstod erstattes ikke; følgeskaden omfattes.", 3, "4.2.1–2"),
  frendeBoatRow("bat.tyveri.dekning", "Tyveri og forsøk på tyveri av eller fra båten. Båtdeler og løst båtutstyr midlertidig i land omfattes i avlåst bod, rom eller bygning som bare du har tilgang til.", 3, "4.1.2–3"),
  frendeBoatRow("bat.tyveri.begrensning", "Tyveri eller underslag utført av husstandsmedlem eller ansatt omfattes ikke; heller ikke når noen har lånt eller prøvd båten uten å levere den tilbake.", 3, "4.2 a–b"),
  frendeBoatRow("bat.redning.dekning", "Bare ansvaret for bergelønn etter sjølovens kapittel 16 under brann og tyveri", 3, "4.1.4"),
  frendeBoatRow("bat.redning.begrensning", "Bergelønn etter 4.1.4 gir ikke redningstiltak eller hjemtransport etter kaskodekningens 5.3.", 3, "4.1.4, jf. 5.1–5.3"),
];
const frendeBoatRescue = (extended: boolean): BoatPetRow[] => [
  frendeBoatRow("bat.redning.dekning", "Ved dekningsmessig båtskade, eller akutt sykdom, ulykke eller død hos deg, fører eller passasjer som gjør at båtturen ikke kan fortsette: rimelige og nødvendige redningstiltak. Assistanse/slep til nærmeste trygge havn; forhåndsgodkjent transport til nærmeste verksted eller rimeligere reparasjon på stedet; bergelønn; vrakfjerning ved offentlig pålegg inntil 10 % av båtens forsikringssum. Merutgifter til lokal overnatting, sykehus/lege, rimeligste hjemreise for personer og avtalt hotell i stedet for hjemreise ved reparasjon innen rimelig tid. Hjemtransport av båt krever at båten må etterlates som følge av 5.1.", 4, "5.3, jf. 5.1"),
  frendeBoatRow("bat.redning.begrensning", "Redningstiltak etter 5.3 gjelder ikke vannscooter, kano eller kajakk. Hjemreise/hotell for personer og hjemtransport av båt har de særskilte utløsere og avtalekravene i 5.3.", 3, "5.1, jf. 5.3 side 4"),
  frendeBoatRow("bat.redning.geografi", extended ? "Hjemtransport av båt fra Norge og Sverige samt øvrig dokumentert fartsområde etter 2 og 7.4" : "Hjemtransport av båt bare i Norge og Sverige", 2, extended ? "2, jf. 7.4 side 5" : "2, jf. 5.3 side 4"),
  frendeBoatRow("bat.redning.grense", extended ? "Hjemtransport fra Norge/Sverige begrenset til båtens verdi; merutgifter fra andre land inntil 50 000 kr" : "Hjemtransport begrenset til båtens verdi på tidspunktet for hjemtransport", extended ? 5 : 4, extended ? "7.4, jf. 5.3" : "5.3 d"),
  frendeBoatRow("bat.redning.egenandel", "750 kr", 4, "5.3", "coverage"),
];
const frendeBoatKasko = (extended: boolean): BoatPetRow[] => [
  ...frendeBoatFire.filter(r => !r.key.startsWith("bat.redning.")),
  frendeBoatRow("bat.kasko.dekning", "Plutselig og uforutsett skade ved hærverk, sammenstøt, grunnstøting, stranding, kantring, synking, brudd på mast/bom, transport til lands/vanns og annen ytre påvirkning som ikke er unntatt i 5.2. Svikt i boblehavn omfattes når båten mot betaling er i opplag hos andre.", 3, "5.1"),
  frendeBoatRow("bat.kasko.begrensning", "Unntatt vind som bare skader seil, berøring med is, frost/is-sprengning/nedbør, snøras eller sammenbrutt overdekning (unntak ved betalt opplag hos andre), varmgang i motor/drivverk, forurenset/infisert/feilaktig drivstoff og mangelfull utbedring av tidligere skade. Følgeskade av varmgang på annet enn motor/drivverk omfattes. Motorskade krever de særskilte årsakene i 5.2 c. Garanti er primær; avvist krav kan omfattes med regress. Utbedring av produksjons-/konstruksjons-/materialfeil, utmatting, slitasje, tæring, råte og korrosjon omfattes ikke; følgeskade omfattes dersom båten var sjødyktig.", 3, "5.2"),
  ...frendeBoatRescue(extended),
  frendeBoatRow("bat.transport.dekning", "Inkludert ved dekningsmessig skade", 3, "5.1.4"),
  frendeBoatRow("bat.losore.dekning", "Løst utstyr og personlig løsøre; kundens forsikringsbevis har forrang", 2, extended ? "3.3, jf. 7.3 side 5" : "3.3"),
  frendeBoatRow("bat.losore.grense", extended ? "50 000 kr på Utvidet, med kundens forsikringsbevis som grunnlag for avtalte summer" : "10 000 kr dersom annen sum ikke står i forsikringsbeviset", extended ? 5 : 2, extended ? "7.3" : "3.3"),
];
const frendeBoatMachine: BoatPetRow[] = [
  frendeBoatRow("bat.maskinskade.dekning", "Valgfritt når oppført i forsikringsbeviset: plutselig og uforutsett motorskade ved varmgang fra tilstoppet kjølesystem, forurenset drivstoff (dieseldyr), eller brudd på fremdriftsmotor, gir, aksling, styring, ror og drivstoffsystem. Nødvendig demontering og undersøkelse for å avklare dekning omfattes.", 4, "6.1"),
  frendeBoatRow("bat.maskinskade.begrensning", "Garanti er primær; dersom garantikrav ikke fører frem kan dekningsmessig skade erstattes og Frende overtar kravet. Unntatt utilstrekkelig vedlikehold, frost, korrosjon/tæring, åpenbar feilbruk i strid med produsentens forskrifter, gradvis forringelse/utmatting og motor til lettbåt eller ekstra motor. Erstatningen er begrenset til motorens/drivverkets markedsverdi på skadetidspunktet. Udokumentert hendelsesdato regnes som meldedato. Egenandelstabellen fastsetter ikke en maksimal dekningsalder.", 4, "6.2, jf. 10.5 og 10.7 side 7–8"),
  frendeBoatRow("bat.maskinskade.egenandel", "Motorens alder: til og med 5 år 6 000 kr; 6 år 10 % minst 7 000 kr; 7 år 20 % minst 8 000 kr; 8 år 30 % minst 9 000 kr; 9 år 40 % minst 10 000 kr; 10 år 50 % minst 11 000 kr; 11 år 60 % minst 12 000 kr; 12 år eller mer 70 % minst 13 000 kr", 7, "10.7 (fortsatt side 8)", "coverage"),
];
const frendeBoatAccident: BoatPetRow[] = [
  frendeBoatRow("bat.ulykke.dekning", "Valgfritt når oppført i forsikringsbeviset: fører, passasjerer og rettmessig bruker når båten brukes lovlig. Kroppsskade direkte forårsaket av en plutselig ytre, uventet fysisk hendelse; sykdom, slag, illebefinnende eller annen sykelig tilstand regnes ikke som ulykke.", 8, "11.1"),
  frendeBoatRow("bat.ulykke.dod", "100 000 kr dersom avdøde etterlater ektefelle, samboer eller barn, eller var under 21 år på ulykkestidspunktet. Begunstigelse etter testament følger forsikringsavtaleloven kapittel 15; ellers ektefelle/barn etter §15-1.", 8, "11.2"),
  frendeBoatRow("bat.ulykke.invaliditet", "200 000 kr ved 100 % livsvarig medisinsk invaliditet, forholdsmessig ved delvis invaliditet og samlet høyst 100 % av summen. Endelig oppgjør innen tre år, eventuelt antatt livsvarig invaliditet på treårsdagen. Tidligere redusert funksjon/sykelig tilstand gir fradrag; tidligere ubrukbar kroppsdel gir ikke erstatning. Død før fastsatt invaliditet gir dødsfallserstatning i stedet.", 8, "11.3"),
  frendeBoatRow("bat.ulykke.begrensning", "Ikke rygg-/nakkelidelser uten røntgenpåvist ulykkesbrudd i ryggsøylen, selvmord/forsøk, psykiske skader (unntatt ICD-10 F43.1 PTSD som følge av fysisk skade med livsvarig erstatningsmessig invaliditet), rus/bedøvende midler eller motorsport med båt/vannscooter.", 8, "11.4 (fortsatt side 9)"),
];

const boatProducts: BoatPetProductDefinition[] = [
  product("tryg", "Tryg", "Ansvar", boatCore("tryg", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter; Russland er unntatt"), "2024-07-01"),
  product("tryg", "Tryg", "Brann/Ansvar", [...boatCore("tryg", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter; Russland er unntatt"), row("bat.brann.dekning", "Inkludert", "tryg", "båt", 1, "Brann/Ansvar")], "2024-07-01"),
  product("tryg", "Tryg", "Brann/Tyveri/Ansvar", boatFire("tryg", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter; Russland er unntatt"), "2024-07-01"),
  product("tryg", "Tryg", "Kasko/Ansvar", [...boatKasko("tryg", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter; Russland er unntatt"), row("bat.haerverk.dekning", "Inkludert", "tryg", "båt", 1, "Kasko/Ansvar")], "2024-07-01"),
  product("tryg", "Tryg", "Båt Ekstra", [...boatKasko("tryg", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter; Russland er unntatt"), row("bat.ferieavbrudd.dekning", "Inkludert", "tryg", "båt", 1, "Båt Ekstra"), row("bat.opplagsutstyr.dekning", "Inkludert", "tryg", "båt", 1, "Båt Ekstra"), row("bat.jolle.dekning", "Inkludert", "tryg", "båt", 1, "Båt Ekstra")], "2024-07-01"),
  product("if", "If", "Delkasko", boatFire("if", "Europa og europeiske farvann inntil 200 nautiske mil fra grunnlinjen, med dokumenterte overfarter"), "2023-02-01"),
  product("if", "If", "Kasko", [...boatKasko("if", "Europa og europeiske farvann inntil 200 nautiske mil fra grunnlinjen, med dokumenterte overfarter"), row("bat.losore.dekning", "Inkludert", "if", "båt", 3, "Hva er forsikret"), row("bat.losore.grense", "50 000 kr per skadetilfelle", "if", "båt", 3, "Hva er forsikret")], "2023-02-01"),
  product("if", "If", "Super", [...boatKasko("if", "Europa og europeiske farvann inntil 200 nautiske mil fra grunnlinjen, med dokumenterte overfarter"), row("bat.ferieavbrudd.dekning", "Inkludert", "if", "båt", 6, "4.10 Superforsikring"), row("bat.losore.grense", "Uten særskilt sumbegrensning innenfor produktvilkårene", "if", "båt", 6, "4.10.1"), row("bat.opplagsutstyr.dekning", "Inkludert", "if", "båt", 6, "4.10.6")], "2023-02-01"),
  product("gjensidige", "Gjensidige", "Delkasko", boatFire("gjensidige", "Europa inntil 200 nautiske mil fra land"), null),
  product("gjensidige", "Gjensidige", "Kasko", boatKasko("gjensidige", "Europa inntil 200 nautiske mil fra land"), null),
  product("gjensidige", "Gjensidige", "Pluss", [...boatKasko("gjensidige", "Europa inntil 200 nautiske mil fra land"), row("bat.totalskade.dekning", "Inkludert", "gjensidige", "båt", 1, "Pluss"), row("bat.maskinskade.dekning", "Inkludert med motor- og båttypebegrensninger", "gjensidige", "båt", 1, "Pluss"), row("bat.maskinskade.alder", "Motor og drivverk eldre enn 10 år er unntatt", "gjensidige", "båt", 1, "Pluss"), row("bat.ferieavbrudd.dekning", "Inkludert", "gjensidige", "båt", 1, "Pluss")], null),
  product("storebrand", "Storebrand", "Delkasko", boatFire("storebrand", "Norden; 1. april–30. september også Europa inntil 200 nautiske mil og dokumenterte overfarter"), "2024-09-01"),
  product("storebrand", "Storebrand", "Kasko", [...boatKasko("storebrand", "Norden; 1. april–30. september også Europa inntil 200 nautiske mil og dokumenterte overfarter"), row("bat.opplagsutstyr.dekning", "Inkludert", "storebrand", "båt", 8, "5.2 Kasko")], "2024-09-01"),
  product("storebrand", "Storebrand", "Super", [...boatKasko("storebrand", "Norden; 1. april–30. september også Europa inntil 200 nautiske mil og dokumenterte overfarter"), row("bat.opplagsutstyr.dekning", "Inkludert", "storebrand", "båt", 9, "5.2 Dekningstabell"), row("bat.opplagsutstyr.grense", "20 000 kr", "storebrand", "båt", 9, "5.2 Dekningstabell"), row("bat.ferieavbrudd.dekning", "Inkludert", "storebrand", "båt", 8, "5.3 Super"), row("bat.ferieavbrudd.dager", "Inntil 30 dager", "storebrand", "båt", 8, "5.3 Super"), row("bat.ferieavbrudd.grense", "Inntil 60 000 kr", "storebrand", "båt", 8, "5.3 Super"), row("bat.totalskade.dekning", "Inkludert", "storebrand", "båt", 8, "5.3 Super"), row("bat.totalskade.alder", "Inntil 3 år fra kjøpsdato", "storebrand", "båt", 8, "5.3 Super")], "2024-09-01"),
  product("sparebank1-fremtind", "Fremtind", "Delkasko", boatFire("sparebank1-fremtind", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter"), "2024-06-10"),
  product("sparebank1-fremtind", "Fremtind", "Kasko", [...boatKasko("sparebank1-fremtind", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter"), row("bat.ferieavbrudd.dekning", "Inkludert", "sparebank1-fremtind", "båt", 7, "Kasko"), row("bat.ferieavbrudd.dager", "Inntil 10 dager", "sparebank1-fremtind", "båt", 7, "Kasko"), row("bat.ferieavbrudd.dagsbelop", "Inntil 1 000 kr per dag", "sparebank1-fremtind", "båt", 7, "Kasko")], "2024-06-10"),
  product("sparebank1-fremtind", "Fremtind", "Toppkasko", [...boatKasko("sparebank1-fremtind", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter"), row("bat.ferieavbrudd.dekning", "Inkludert", "sparebank1-fremtind", "båt", 8, "Toppkasko"), row("bat.ferieavbrudd.dager", "Inntil 15 dager", "sparebank1-fremtind", "båt", 8, "Toppkasko"), row("bat.ferieavbrudd.dagsbelop", "Inntil 1 500 kr per dag", "sparebank1-fremtind", "båt", 8, "Toppkasko"), row("bat.totalskade.dekning", "Inkludert", "sparebank1-fremtind", "båt", 9, "Totalskadegaranti"), row("bat.maskinskade.dekning", "Inkludert med dokumenterte motor- og aldersbegrensninger", "sparebank1-fremtind", "båt", 8, "Toppkasko"), row("bat.maskinskade.egenandel", "4 000 kr, med vilkårets fradragsregel", "sparebank1-fremtind", "båt", 9, "Maskin-/seilskade", "coverage")], "2024-06-10"),
  product("frende", "Frende", "Brann og tyveri", frendeBoatFire, "2026-01-01"),
  product("frende", "Frende", "Kasko", frendeBoatKasko(false), "2026-01-01"),
  product("frende", "Frende", "Utvidet", [...frendeBoatKasko(true), row("bat.opplagsutstyr.dekning", "Inkludert", "frende", "båt", 3, "Hva som er forsikret")], "2026-01-01"),
];

const boatAddOns: BoatPetAddOnDefinition[] = [
  { providerId: "tryg", company: "Tryg", type: "båt", agreementScope: "ordinary", id: "tryg-bat-maskinskade", name: "Maskinskade", sourceId: sourceId("tryg", "båt"), requiresLevel: ["Kasko/Ansvar", "Båt Ekstra"], rows: [row("bat.maskinskade.dekning", "Valgfritt tillegg", "tryg", "båt", 1, "Maskinskade", undefined, "boat-pet:tryg:båt:machinery"), row("bat.maskinskade.alder", "Innenbordsmotor under 15 år; utenbordsmotor/seilbåt under 12 år", "tryg", "båt", 1, "Maskinskade", undefined, "boat-pet:tryg:båt:machinery")] },
  { providerId: "tryg", company: "Tryg", type: "båt", agreementScope: "ordinary", id: "tryg-bat-ulykke", name: "Fører- og passasjerulykke", sourceId: sourceId("tryg", "båt"), requiresLevel: ["Ansvar", "Brann/Ansvar", "Brann/Tyveri/Ansvar", "Kasko/Ansvar", "Båt Ekstra"], rows: [row("bat.ulykke.dekning", "Valgfritt tillegg", "tryg", "båt", 1, "Fører- og passasjerulykke", undefined, "boat-pet:tryg:båt:accident")] },
  { providerId: "if", company: "If", type: "båt", agreementScope: "ordinary", id: "if-bat-motor-gir", name: "Motor- og girskade", sourceId: sourceId("if", "båt"), requiresLevel: ["Kasko", "Super"], rows: [row("bat.maskinskade.dekning", "Valgfritt tillegg til Kasko", "if", "båt", 5, "4.9"), row("bat.maskinskade.alder", "Dekningen opphører når motor, gir eller drivverk er eldre enn 15 år", "if", "båt", 5, "4.9.2"), row("bat.maskinskade.egenandel", "Alder på motor, gir og drivverk: til og med 5 år 4 000 kr; over 5 til og med 10 år 8 000 kr; til og med 11 år 10 %, 12 år 20 %, 13 år 30 %, 14 år 40 % og 15 år 50 % av reparasjonskostnaden. Minst 8 000 kr gjelder prosentgrenene. Over 15 år opphører dekningen. Alder regnes fra 1. januar året etter kjøp som ny.", "if", "båt", 6, "4.9.5", "coverage") ] },
  { providerId: "frende", company: "Frende", type: "båt", agreementScope: "ordinary", id: "frende-bat-maskinskade", name: "Maskinskade", sourceId: sourceId("frende", "båt"), requiresLevel: ["Kasko", "Utvidet"], rows: frendeBoatMachine },
  { providerId: "frende", company: "Frende", type: "båt", agreementScope: "ordinary", id: "frende-bat-ulykke", name: "Fører- og passasjerulykke", sourceId: sourceId("frende", "båt"), requiresLevel: ["Brann og tyveri", "Kasko", "Utvidet"], rows: frendeBoatAccident },
];

const petProduct = (providerId: string, company: string, type: "hund" | "katt", name: string, version: string | null, rows: BoatPetRow[]): BoatPetProductDefinition => ({
  providerId, company, type, agreementScope: "ordinary", productId: `${providerId}-${type}-${name.toLocaleLowerCase("nb-NO").normalize("NFKD").replace(/\p{M}/gu, "").replace(/[^a-z0-9]+/gu, "-").replace(/^-|-$/gu, "")}`,
  name, version, sourceId: sourceId(providerId, type), rows,
});
const vetBase = (providerId: string, type: "hund" | "katt", sum: string, deductibleValue: string, versionSection = "Veterinærbehandling"): BoatPetRow[] => [
  row("dyr.veterinar.dekning", "Inkludert", providerId, type, 1, versionSection),
  row("dyr.veterinar.sum.valgbar", sum, providerId, type, 1, versionSection),
  row("dyr.veterinar.egenandel.fast", deductibleValue, providerId, type, 1, versionSection, "reference"),
];
// If Hund: own-source clauses apply to each ordinary veterinary level.
const ifDogCommon = (type: "hund" | "katt"): BoatPetRow[] => type === "hund" ? [
  row("dyr.tannskade.dekning", "Tannbehandling ved ulykkeshendelse, inkludert rotspissabcess ved avskalling/fraktur, innenfor valgt veterinærsum", "if", "hund", 4, "5.1.2"),
  row("dyr.karenstid.sykdom", "20 dager: sykdom, feil eller svakheter som hunden hadde ved ikrafttredelse, eller som påvises eller viser symptomer innen 20 dager etter kjøp. Karenstiden gjelder ikke ved flytting fra annet selskap eller tidligere forsikring i If med annen eier. Ved forhøyelse av forsikringssum eller utvidelse starter ny karenstid bare for forhøyelsen/utvidelsen.", "if", "hund", 8, "6.2.1"),
  row("dyr.veterinaralder.opphor", "Veterinærforsikringen kan beholdes hele hundens liv", "if", "hund", 4, "4 Varighet"),
] : [];
// If Katt: distinct frozen cat clauses, never inherited from dog terms.
const ifCatCommon = (type: "hund" | "katt"): BoatPetRow[] => type === "katt" ? [
  row("dyr.tannskade.dekning", "Tannbehandling ved ulykkeshendelse, inkludert rotspissabcess ved avskalling/fraktur, innenfor valgt veterinærsum", "if", "katt", 4, "5.1.2"),
  row("dyr.karenstid.sykdom", "20 dager: sykdom, feil eller svakheter som katten hadde ved ikrafttredelse, eller som påvises eller viser symptomer innen 20 dager etter kjøp. Karenstiden gjelder ikke ved flytting fra annet selskap eller tidligere forsikring i If med annen eier. Ved forhøyelse av forsikringssum eller utvidelse starter ny karenstid bare for forhøyelsen/utvidelsen.", "if", "katt", 7, "6.2.1"),
  row("dyr.veterinaralder.opphor", "Veterinærforsikringen kan beholdes hele kattens liv", "if", "katt", 4, "4 Varighet"),
] : [];
const petProducts: BoatPetProductDefinition[] = [
  petProduct("tryg", "Tryg", "hund", "Behandling", "2026-09-01", [
    ...vetBase("tryg", "hund", "Kundens valgte sum fremgår av forsikringsbeviset", "Fremgår av forsikringsbeviset").filter((fact) => fact.key === "dyr.veterinar.dekning"),
    row("dyr.veterinar.egenandel.fast", "2 500 kr per sykdom og per ulykkestilfelle", "tryg", "hund", 1, "3 Hvilke utgifter som erstattes – Egenandel", "coverage", "boat-pet:tryg:hund:treatment"),
    { ...row("dyr.veterinar.sum.valgbar", "Kundens valgte forsikringssum fremgår av forsikringsbeviset. Utgifter per sykdom og per ulykkesskade erstattes inntil summen på skadedagen; besøk og utgifter fra samme sykdom eller ulykke regnes som én skade. Samlede utgifter ved flere sykdommer eller ulykkesskader er også begrenset til forsikringssummen per forsikringsår.", "tryg", "hund", 2, "4 Slik beregnes erstatningen", undefined, "boat-pet:tryg:hund:treatment"), qualificationSource: { sourceId: "boat-pet:tryg:hund:treatment", page: 1, section: "1 HVA FORSIKRINGEN OMFATTER" } },
    row("dyr.diagnostikk.dekning", "CT og MR rekvirert og ordinert av veterinær ved sykdom eller ulykkesskade i forsikringstiden", "tryg", "hund", 1, "2–3 Tilfeller og utgifter", undefined, "boat-pet:tryg:hund:treatment"),
    row("dyr.veterinaralder.opphor", "Hund Behandling og Hund Ekstra kan beholdes hele dyrets levetid", "tryg", "hund", 1, "4 Når forsikringen gjelder", undefined, "boat-pet:tryg:hund:product"),
    row("dyr.tannskade.dekning", "Trekking av ulykkesskadde tenner ved tannfraktur dekkes. Annen behandling av tannskade og behandling av tann- og tannkjøttsykdommer er unntatt fra Hund Behandling.", "tryg", "hund", 1, "3 Hvilke utgifter som erstattes – tannfraktur og unntak", undefined, "boat-pet:tryg:hund:treatment"),
    row("dyr.fodsel.dekning", "Fødselshjelp uavhengig av årsak dekkes kun etter at hunden har fylt 18 måneder, når veterinær har bekreftet at hundens liv er i fare. Keisersnitt hos Engelsk og Fransk Bulldog, Boston Terrier, Chihuahua og Pomeranian er unntatt; for blandingsrasehund gjelder unntaket når hunden er blandet av rase med unntak.", "tryg", "hund", 1, "3 Hvilke utgifter som erstattes – fødselshjelp og unntak", undefined, "boat-pet:tryg:hund:treatment"),
    row("dyr.medisin.dekning", "Inkludert", "tryg", "hund", 1, "Hund Behandling"),
    row("dyr.karenstid.sykdom", "20 dager", "tryg", "hund", 1, "Begrensninger"),
  ]),
  petProduct("tryg", "Tryg", "katt", "Behandling", "2026-09-01", [
    ...vetBase("tryg", "katt", "Kundens valgte sum fremgår av forsikringsbeviset", "Fremgår av forsikringsbeviset").filter((fact) => fact.key === "dyr.veterinar.dekning"),
    row("dyr.veterinar.egenandel.fast", "2 500 kr per sykdom og per ulykkestilfelle", "tryg", "katt", 1, "3 Hvilke utgifter som erstattes – Egenandel", "coverage", "boat-pet:tryg:katt:treatment"),
    { ...row("dyr.veterinar.sum.valgbar", "Kundens valgte forsikringssum fremgår av forsikringsbeviset. Utgifter per sykdom og per ulykkesskade erstattes inntil summen på skadedagen; besøk og utgifter fra samme sykdom eller ulykke regnes som én skade. Samlede utgifter ved flere sykdommer eller ulykkesskader er også begrenset til forsikringssummen per forsikringsår.", "tryg", "katt", 2, "4 Slik beregnes erstatningen", undefined, "boat-pet:tryg:katt:treatment"), qualificationSource: { sourceId: "boat-pet:tryg:katt:treatment", page: 1, section: "1 HVA FORSIKRINGEN OMFATTER" } },
    row("dyr.diagnostikk.dekning", "CT og MR rekvirert og ordinert av veterinær ved sykdom eller ulykkesskade i forsikringstiden", "tryg", "katt", 1, "2–3 Tilfeller og utgifter", undefined, "boat-pet:tryg:katt:treatment"),
    row("dyr.veterinaralder.opphor", "Katt Behandling og Katt Ekstra kan beholdes hele dyrets levetid", "tryg", "katt", 1, "4 Når forsikringen gjelder", undefined, "boat-pet:tryg:katt:product"),
    row("dyr.tannskade.dekning", "Trekking av ulykkesskadde tenner ved tannfraktur dekkes. Annen behandling av tannskade og behandling av tann- og tannkjøttsykdommer er unntatt fra Katt Behandling.", "tryg", "katt", 1, "3 Hvilke utgifter som erstattes – tannfraktur og unntak", undefined, "boat-pet:tryg:katt:treatment"),
    row("dyr.fodsel.dekning", "Fødselshjelp uavhengig av årsak når veterinær har bekreftet at kattens liv er i fare", "tryg", "katt", 1, "3 Hvilke utgifter som erstattes – fødselshjelp", undefined, "boat-pet:tryg:katt:treatment"),
    row("dyr.medisin.dekning", "Inkludert", "tryg", "katt", 1, "Katt Behandling"),
    row("dyr.karenstid.sykdom", "20 dager", "tryg", "katt", 1, "Begrensninger"),
  ]),
  ...(["hund", "katt"] as const).flatMap((type) => [
    petProduct("if", "If", type, "Basis", "2022-12-01", [...vetBase("if", type, "Valgbar forsikringssum; faktisk valg står i forsikringsbeviset", "Valgbar egenandel; faktisk valg står i forsikringsbeviset"), ...ifDogCommon(type), ...ifCatCommon(type), ...(type === "hund" ? [row("dyr.medisin.dekning", "Medisiner, bandasjemateriell, body/halskrage og potesokk brukt som del av behandlingen hos veterinæren, innenfor valgt veterinærsum. Separat kjøp etter konsultasjonen/operasjonen omfattes av Standard og Super.", "if", "hund", 4, "5.1.1")] : [row("dyr.medisin.dekning", "Medisiner, bandasjemateriell, body/halskrage og potesokk brukt som del av behandlingen hos veterinæren, innenfor valgt veterinærsum. Separat kjøp etter konsultasjonen/operasjonen omfattes av Standard og Super.", "if", "katt", 4, "5.1.1")])]),
    petProduct("if", "If", type, "Standard", "2022-12-01", [...vetBase("if", type, "Valgbar forsikringssum; faktisk valg står i forsikringsbeviset", "Valgbar egenandel; faktisk valg står i forsikringsbeviset"), ...ifDogCommon(type), ...ifCatCommon(type), row("dyr.medisin.dekning", "Inkludert", "if", type, 1, "Standard"), row("dyr.tannsykdom.dekning", "Inkludert med egen dokumentert grense", "if", type, 1, "Standard"), row("dyr.tannsykdom.grense", type === "hund" ? "Inntil 15 000 kr i løpet av hundens liv for karies og tannresorpsjon (TR), innenfor valgt veterinærsum. Tilbakeholdte melketenner, tanncyster, emaljedefekter og bittfeil omfattes i tillegg når medisinsk nødvendig dersom hunden har vært forsikret med tilsvarende veterinærdekning før fylte fire måneder." : "Karies og tannresorpsjon (TR): inntil 5 000 kr i løpet av kattens liv, innenfor valgt veterinærsum. I tillegg dekkes tilbakeholdte melketenner, tanncyster, emaljedefekter og bittfeil når medisinsk nødvendig dersom katten har vært forsikret før fylte fire måneder.", "if", type, 4, "5.1.3"), ...(type === "hund" ? [row("dyr.allergi.dekning", "Utredning og behandling av allergi innenfor valgt veterinærsum", "if", "hund", 4, "5.1.4"), row("dyr.allergi.grense", "Behandling av allergi: inntil 15 000 kr i løpet av hundens liv, innenfor valgt veterinærsum", "if", "hund", 4, "5.1.4")] : [row("dyr.allergi.dekning", "Utredning og behandling av allergi innenfor valgt veterinærsum", "if", "katt", 4, "5.1.4"), row("dyr.allergi.grense", "Behandling av allergi: inntil 15 000 kr i løpet av kattens liv, innenfor valgt veterinærsum", "if", "katt", 4, "5.1.4")])]),
    petProduct("if", "If", type, "Super", "2022-12-01", [...vetBase("if", type, "Valgbar forsikringssum; faktisk valg står i forsikringsbeviset", "Valgbar egenandel; faktisk valg står i forsikringsbeviset"), ...ifDogCommon(type), ...ifCatCommon(type), row("dyr.veterinar.rollover", type === "hund" ? "Ved skadefritt forsikringsår rulles 10 000 kr automatisk over til neste forsikringsår. Ved nedjustering av forsikringssum reduseres oppspart rollover tilsvarende. Maksimal oppspart sum er det dobbelte av valgt forsikringssum. Opptjening og bruk gjelder bare så lenge Super veterinærforsikring beholdes." : "Ved skadefritt forsikringsår rulles 10 000 kr automatisk over til neste forsikringsår. Ved nedjustering av forsikringssum reduseres oppspart rollover tilsvarende. Maksimal oppspart sum er det dobbelte av valgt forsikringssum. Opptjening og bruk gjelder bare så lenge Super veterinærforsikring beholdes.", "if", type, 5, "5.1.9"), row("dyr.medisin.dekning", "Inkludert", "if", type, 1, "Super"), row("dyr.tannsykdom.dekning", type === "hund" ? "Tannbehandling ved karies og tannresorpsjon (TR). Tilbakeholdte melketenner, tanncyster, emaljedefekter og bittfeil dekkes når medisinsk nødvendig dersom hunden har vært forsikret med tilsvarende veterinærdekning før fylte fire måneder." : "Tannbehandling ved karies og tannresorpsjon (TR). Tilbakeholdte melketenner, tanncyster, emaljedefekter og bittfeil dekkes når medisinsk nødvendig dersom katten har vært forsikret før fylte fire måneder. Inntil valgt forsikringssum for veterinærutgifter årlig, men tannresorpsjon (TR) dekkes med inntil 5 000 kr årlig.", "if", type, 4, "5.1.3"), ...(type === "hund" ? [row("dyr.tannsykdom.grense", "Inntil valgt forsikringssum for veterinærutgifter årlig", "if", "hund", 4, "5.1.3")] : []), row("dyr.rehabilitering.dekning", "Inkludert", "if", type, 1, "Super"), row("dyr.allergi.dekning", "Inkludert innen valgt veterinærsum", "if", type, 1, "Super")]),
  ]),
  petProduct("gjensidige", "Gjensidige", "hund", "Behandling", null, [
    ...vetBase("gjensidige", "hund", "Valgt forsikringssum fremgår av forsikringsbeviset", "Fremgår av forsikringsbeviset").map(fact => fact.key === "dyr.veterinar.sum.valgbar" ? {
      ...fact, value: "Valg mellom 20 000, 30 000, 40 000 eller 50 000 kr. Valgt forsikringssum fremgår av forsikringsbeviset.",
      sourceId: "boat-pet:gjensidige:hund:product", page: 1, section: "Behandling – valgbar forsikringssum",
      qualificationSource: { sourceId: fact.sourceId, page: fact.page, section: fact.section },
    } : fact),
    row("dyr.rehabilitering.grense", "Inntil 5 000 kr", "gjensidige", "hund", 1, "Behandling"), row("dyr.allergi.grense", "Inntil 5 000 kr", "gjensidige", "hund", 1, "Behandling"),
  ]),
  petProduct("gjensidige", "Gjensidige", "katt", "Behandling", null, [...vetBase("gjensidige", "katt", "Valgt forsikringssum fremgår av forsikringsbeviset", "Fremgår av forsikringsbeviset"), row("dyr.allergi.grense", "Inntil 5 000 kr", "gjensidige", "katt", 1, "Behandling")]),
  petProduct("storebrand", "Storebrand", "hund", "Veterinær", "2025-02-01", [...vetBase("storebrand", "hund", "Valgt forsikringssum per forsikringsår fremgår av forsikringsbeviset", "2 500 kr per skadetilfelle"), row("dyr.veterinaralder.opphor", "Veterinærforsikringen gjelder livet ut", "storebrand", "hund", 2, "B.1")]),
  petProduct("storebrand", "Storebrand", "katt", "Veterinær", "2025-02-01", [...vetBase("storebrand", "katt", "Valgt forsikringssum per forsikringsår fremgår av forsikringsbeviset", "2 500 kr per skadetilfelle"), row("dyr.veterinaralder.opphor", "Veterinærforsikringen gjelder livet ut", "storebrand", "katt", 2, "B.1")]),
  ...(["hund", "katt"] as const).flatMap((type) => {
    const life = [row("dyr.liv.dekning", "Inkludert", "storebrand", type, 1, "Dødsfall"), row("dyr.liv.sum.valgbar", "Valgt forsikringssum fremgår av forsikringsbeviset", "storebrand", type, 1, "Dødsfall"), row("dyr.liv.reduksjon.start", "Fra 8 år", "storebrand", type, 1, "Dødsfall"), row("dyr.liv.reduksjon.sats", "90 % ved 8 år, 75 % ved 9 år og 60 % ved 10 år", "storebrand", type, 1, "Dødsfall"), row("dyr.liv.opphor", "Første forfall etter fylte 10 år", "storebrand", type, 1, "Dødsfall"), ...(type === "hund" ? [row("hund.bruksverdi.dekning", "Inkludert i valgt dødsfallsdekning", "storebrand", type, 1, "Dødsfall og nedsatt bruksverdi"), row("hund.bruksverdi.grense", "Maksimalt 50 % av hundens forsikringssum for død", "storebrand", type, 1, "Dødsfall og nedsatt bruksverdi")] : [])];
    return [
      petProduct("storebrand", "Storebrand", type, "Dødsfall", "2025-02-01", life),
      petProduct("storebrand", "Storebrand", type, "Veterinær og Dødsfall", "2025-02-01", [...vetBase("storebrand", type, "Valgt forsikringssum per forsikringsår fremgår av forsikringsbeviset", "2 500 kr per skadetilfelle"), row("dyr.veterinaralder.opphor", "Veterinærforsikringen gjelder livet ut", "storebrand", type, 2, "B.1"), ...life]),
    ];
  }),
  petProduct("sparebank1-fremtind", "Fremtind", "hund", "Veterinær", "2025-08-07", [
    ...vetBase("sparebank1-fremtind", "hund", "Valgt forsikringssum gjelder per forsikringsår", "Valg mellom 1 300, 2 000 eller 3 500 kr").filter((fact) => fact.key === "dyr.veterinar.sum.valgbar"),
    row("dyr.veterinar.dekning", "Inkludert: nødvendige veterinærutgifter som følge av sykdom eller ulykkesskade, og komplikasjoner som følge av vaksinasjon eller kastrering/sterilisering, innenfor valgt forsikringssum per forsikringsår.", "sparebank1-fremtind", "hund", 1, "7 Veterinærutgifter", undefined, "boat-pet:sparebank1-fremtind:hund"),
    row("dyr.medisin.dekning", "Inkludert: utgifter til reseptbelagte medisiner innenfor valgt forsikringssum per forsikringsår.", "sparebank1-fremtind", "hund", 1, "7 Veterinærutgifter – reseptbelagte medisiner", undefined, "boat-pet:sparebank1-fremtind:hund"),
    row("dyr.veterinar.egenandel.fast", "Valg mellom 1 300, 2 000 eller 3 500 kr: kun én valgt fast egenandel i en egenandelsperiode på 135 dager regnet fra og med første veterinærutgift.", "sparebank1-fremtind", "hund", 2, "8 Erstatningsregler – egenandel", "reference", "boat-pet:sparebank1-fremtind:hund"),
    row("dyr.veterinar.egenandel.prosent", "20 % av resterende veterinærutgifter etter den valgte faste egenandelen.", "sparebank1-fremtind", "hund", 2, "8 Erstatningsregler – egenandel", "coverage", "boat-pet:sparebank1-fremtind:hund"),
    row("dyr.veterinar.egenandel.periode", "135 dager regnet fra og med første veterinærutgift; kun én valgt fast egenandel i perioden.", "sparebank1-fremtind", "hund", 2, "8 Erstatningsregler – egenandel", "coverage", "boat-pet:sparebank1-fremtind:hund"),
    row("dyr.allergi.dekning", "Utredning, behandling og medisiner til atopi/allergi", "sparebank1-fremtind", "hund", 1, "7 Veterinærutgifter"), row("dyr.allergi.grense", "Inntil 15 000 kr i løpet av hundens liv, innenfor valgt forsikringssum", "sparebank1-fremtind", "hund", 1, "7 Veterinærutgifter"), row("dyr.diagnostikk.dekning", "MR/CT inkludert", "sparebank1-fremtind", "hund", 1, "7 Veterinærutgifter"), row("dyr.diagnostikk.grense", "MR/CT samlet inntil 15 000 kr per forsikringsår, innenfor valgt forsikringssum", "sparebank1-fremtind", "hund", 1, "7 Veterinærutgifter"),
  ]),
  petProduct("sparebank1-fremtind", "Fremtind", "katt", "Veterinær", "2025-08-07", [
    ...vetBase("sparebank1-fremtind", "katt", "Valgt forsikringssum gjelder per forsikringsår", "Valg mellom 1 300, 2 000 eller 4 000 kr").filter((fact) => fact.key === "dyr.veterinar.sum.valgbar"),
    row("dyr.veterinar.egenandel.fast", "Valg mellom 1 300, 2 000 eller 4 000 kr", "sparebank1-fremtind", "katt", 2, "8 Erstatningsregler", "reference"),
    row("dyr.diagnostikk.grense", "MR/CT samlet inntil 15 000 kr per forsikringsår", "sparebank1-fremtind", "katt", 1, "Veterinærutgifter"),
    row("dyr.veterinar.dekning", "Nødvendige veterinærutgifter som følge av sykdom eller ulykkesskade, inkludert komplikasjoner som følge av vaksinasjon eller kastrering/sterilisering; innenfor valgt forsikringssum per forsikringsår.", "sparebank1-fremtind", "katt", 1, "7 Veterinærutgifter", undefined, "boat-pet:sparebank1-fremtind:katt"),
    row("dyr.medisin.dekning", "Utgifter til reseptbelagte medisiner innenfor valgt forsikringssum per forsikringsår", "sparebank1-fremtind", "katt", 1, "7 Veterinærutgifter", undefined, "boat-pet:sparebank1-fremtind:katt"),
    row("dyr.rehabilitering.dekning", "Ikke dekket. Veterinærutgifter Katt omfatter ikke fysioterapi, rehabilitering, kiropraktikk eller alternativ behandling.", "sparebank1-fremtind", "katt", 2, "7 Veterinærutgifter – Kostnader til", undefined, "boat-pet:sparebank1-fremtind:katt"),
    row("dyr.veterinar.begrensning", "Kostnader til transport, reiseutgifter og hjemmebesøk; gebyrer, attester, salgsartikler, kosttilskudd eller fôr selv om anbefalt av veterinær; forebyggende undersøkelser eller behandlinger dekkes ikke.", "sparebank1-fremtind", "katt", 2, "7 Veterinærutgifter – kostnader", undefined, "boat-pet:sparebank1-fremtind:katt"),
    row("dyr.veterinar.egenandel.prosent", "20 % av resterende veterinærutgifter etter fast egenandel", "sparebank1-fremtind", "katt", 2, "8 Erstatningsregler", undefined, "boat-pet:sparebank1-fremtind:katt"),
    row("dyr.veterinar.egenandel.periode", "135 dager fra og med første veterinærutgift; kun én fast egenandel i perioden", "sparebank1-fremtind", "katt", 2, "8 Erstatningsregler", undefined, "boat-pet:sparebank1-fremtind:katt"),
  ]),
  petProduct("frende", "Frende", "hund", "Veterinær", "2026-01-01", [
    row("dyr.veterinar.dekning", "Rimelige og nødvendige utgifter til undersøkelse og behandling av syk eller skadet hund, inkludert medisiner og materiell som veterinæren bruker, og nødvendig opphold på dyrehospital/-klinikk", "frende", "hund", 2, "4.1.1"),
    row("dyr.veterinar.sum.valgbar", "Per skadetilfelle og samlet per forsikringsår; faktisk sum står i forsikringsbeviset. Samlet erstatning for veterinærutgifter og medisinutgifter per skadetilfelle er begrenset til bevisets sum, også når samme skadetilfelle gir veterinærutgifter over flere forsikringsår", "frende", "hund", 4, "8.4, jf. 4.1 side 2"),
    row("dyr.veterinar.egenandel.fast", "Minst 1 000 kr per skadetilfelle", "frende", "hund", 1, "Veterinærbehandling", "reference"),
    row("dyr.veterinar.egenandel.prosent", "25 % av skaden", "frende", "hund", 4, "8.6 Egenandel", "coverage"),
    row("dyr.allergi.grense", "Inntil 15 000 kr til førstegangsdiagnostisering og behandling av allergi/atopi. Unntatt hund med symptomer på øre- eller hudlidelser før kjøp eller innen 20 dager etterpå. Antistoffer i blodprøve før tre måneder etter kjøp regnes som allergi påbegynt før forsikringen", "frende", "hund", 2, "4.1.4 og 4.2.4 (fortsatt side 3)"),
    row("dyr.karenstid.sykdom", "20 dager fra opprinnelig kjøp i Frende eller tidligere selskap; eksisterende sykdom eller skade er unntatt. Ved økning av forsikringssummen gjelder karens bare økningen", "frende", "hund", 3, "4.2.11"),
    row("dyr.veterinar.begrensning", "Unntatt forebyggende undersøkelse/behandling, rehabilitering, reiser, fôr, foreskrevne/utleverte medisiner og forbindingsmateriell, alternativ undersøkelse/behandling, adferdsforstyrrelser/unormalt temperament og komplikasjoner etter behandling av sykdom/skade som ikke omfattes. Tannbehandling er avgrenset til trekking av tenner knekt ved ulykke; særskilte raseunntak i 4.2.7–9 gjelder. Behandling etter at hunden ikke lenger er forsikret i Frende er unntatt, selv om sykdom/skade inntraff i forsikringstiden", "frende", "hund", 2, "4.2.1–3, 5–10 og 12 (fortsatt side 3)"),
  ]),
  petProduct("frende", "Frende", "katt", "Veterinær", "2026-01-01", [
    row("dyr.veterinar.dekning", "Rimelige og nødvendige utgifter til undersøkelse og behandling av syk eller skadet katt, inkludert medisiner og materiell som veterinæren bruker, og nødvendig opphold på dyrehospital/-klinikk", "frende", "katt", 2, "4.1.1"),
    row("dyr.veterinar.sum.valgbar", "Samlet erstatning for alle veterinærutgifter og alle medisinutgifter per skadetilfelle er begrenset til forsikringssummen i forsikringsbeviset; dette gjelder også når samme skadetilfelle gir veterinærutgifter over flere forsikringsår", "frende", "katt", 3, "7.4 Forsikringssum"),
    row("dyr.veterinar.egenandel.fast", "Minst 1 000 kr per skadetilfelle", "frende", "katt", 1, "Veterinærbehandling", "reference"),
    row("dyr.veterinar.egenandel.prosent", "25 % av skaden", "frende", "katt", 4, "7.6 Egenandel", "coverage"),
    row("dyr.allergi.grense", "Inntil 15 000 kr til førstegangsdiagnostisering og behandling av allergi/atopi. Unntatt katt med symptomer på øre- eller hudlidelser før kjøp eller innen 20 dager etterpå. Antistoffer i blodprøve før tre måneder etter kjøp regnes som allergi påbegynt før forsikringen", "frende", "katt", 2, "4.1.2 og 4.2.4"),
    row("dyr.karenstid.sykdom", "20 dager fra opprinnelig kjøp i Frende eller tidligere selskap; eksisterende sykdom eller skade er unntatt. Ved økning av forsikringssummen gjelder karens bare økningen", "frende", "katt", 2, "4.2.8"),
    row("dyr.veterinar.begrensning", "Unntatt forebyggende undersøkelse/behandling, rehabilitering, reiser, fôr, foreskrevne/utleverte medisiner og forbindingsmateriell, alternativ undersøkelse/behandling, adferdsforstyrrelser/unormalt temperament og komplikasjoner etter behandling av sykdom/skade som ikke omfattes. Tannbehandling er avgrenset til trekking av tenner knekt ved ulykke. Behandling etter at katten ikke lenger er forsikret i Frende er unntatt, selv om sykdom/skade inntraff i forsikringstiden", "frende", "katt", 2, "4.2.1–3, 5–7 og 9"),
  ]),
];

const petAddOn = (providerId: string, company: string, type: "hund" | "katt", id: string, name: string, requiresLevel: string[], rows: BoatPetRow[]): BoatPetAddOnDefinition => ({ providerId, company, type, agreementScope: "ordinary", id, name, sourceId: sourceId(providerId, type), requiresLevel, rows });

const gjensidigeBruk = (type: "hund" | "katt"): BoatPetAddOnDefinition => {
  const fullTerms = `boat-pet:gjensidige:${type}:life-use`;
  const qualified = (key: string, value: string, page: number, section: string): BoatPetRow => ({
    ...row(key, value, "gjensidige", type, page, section, undefined, fullTerms),
    qualificationSource: { sourceId: `boat-pet:gjensidige:${type}:product`, page: 1, section: "Bruk – tillegg til Liv" },
  });
  return {
    ...petAddOn("gjensidige", "Gjensidige", type, `gjensidige-${type}-bruk`, "Bruk", ["Behandling"], [
      qualified(`${type}.bruksverdi.dekning`, "Valgfritt tillegg til valgt Liv: livsvarig tap av bruksverdi innenfor forsikret bruksområde som følge av sykdom eller ulykke", 2, "Hvilke skader/hendelser – tap av bruksverdi"),
      qualified(`${type}.bruksverdi.alder`, `Bruk opphører ved hovedforfall det året ${type === "hund" ? "hunden fyller 8" : "katten fyller 10"} år`, type === "hund" ? 3 : 2, "Opphør – Bruk"),
      qualified(`${type}.bruksverdi.begrensning`, type === "hund"
        ? "Bruksegenskapen må være dokumentert tapt av veterinær. Avlshund: fysisk mistet avlsevnen 100 %; hannhund far til minst 1 kull siste 2 år, tispe født minst 1 kull på normal måte siste 2 år før sykdom/skade. Jakthund, gjeterhund og tjenestehund: trent for og regelmessig brukt til formålet, bruksegenskapen nedsatt minst 50 %. Hunden må være utredet, adekvat behandlet og ha gjennomgått tilstrekkelig lang rekonvalesens."
        : "Avlskatt: bruksegenskapen må være dokumentert tapt av veterinær og avlsevnen fysisk mistet 100 %. Hannkatt far til minst 1 kull siste 2 år; hunnkatt født minst 1 kull på normal måte siste 2 år før sykdom/skade.", 2, "Forutsetninger – tap av bruksverdi"),
      ...(type === "hund" ? [qualified("hund.bruksverdi.grense", "Ved tap av bruksverdi er erstatningsgrunnlaget forsikringssummen. Det gjøres fradrag for gjenverdi minimum kr 5 000. Ved utbetalt erstatning for tap av bruksverdi blir forsikringssummen for Død endret i samsvar med gjenverdien.", 8, "Erstatningsgrunnlag – tap av bruksverdi")] : []),
    ]),
    requiresAddOnIds: [`gjensidige-${type}-liv`],
    selectionEvidenceKeys: [`${type}.bruksverdi.dekning`],
  };
};

const frendeDogUseRows: BoatPetRow[] = [
  { ...row("hund.bruksverdi.dekning", "Betinget del av valgt Tap-dekning: helt tap av bruksegenskaper etter sykdom eller ulykke for ferdig trent hund som regelmessig brukes til et spesielt formål", "frende", "hund", 4, "7.1.3 Tap av brukshund"),
    qualificationSource: { sourceId: sourceId("frende", "hund"), page: 4, section: "7.3 Særvilkår og 8.2 Veterinærattest" } },
  row("hund.bruksverdi.grense", "50 % av forsikringssummen som står i forsikringsbeviset for Tap av hunden. Tidligere utbetaling for tap av bruksegenskaper trekkes fra senere dødsfallserstatning.", "frende", "hund", 4, "8.4 Forsikringssum"),
  row("hund.bruksverdi.alder", "Hunden må være under 8 år; tap av bruksegenskaper erstattes ikke når hunden er åtte år eller eldre", "frende", "hund", 4, "7.3.1 Tap av brukshund"),
  row("hund.bruksverdi.begrensning", "Ferdig trent og regelmessig brukt til et spesielt formål; helt tap etter sykdom eller ulykke må dokumenteres med veterinærattest (§§7.1.3 og 8.2). Tap av avlsegenskaper er unntatt. Særvilkår §7.3 for medfødte sykdommer, hofte-/albueleddsykdommer, OCD, patellaluksasjon og lang bløt gane: sammenhengende veterinærdekning fra før 4 måneder, eller ved HD/AA/AD tidligere avlest fri av NKK. Ved HD må foreldrene dokumenteres, være frirøntget og avlest av NKK.", "frende", "hund", 4, "7.1.3, 7.3 og 8.2"),
];
const fremtindDogEarlyLifeGroup = "berner sennenhund, grand danois, irsk ulvehund, leonberger, newfoundlandshund, pyrenéerhund, napolitansk mastiff og sanktbernhardshund";
const fremtindDogLateLifeGroup = "bichon havanais, border terrier, cairn terrier, chihuahua, chinese crested, dvergschnauzer, finsk lapphund, finsk spets, foxterrier, islandsk fårehund, jack russel terrier, lhasa apso, toy-, dverg- og mellompuddel, kleiner og grosser münsterländer, norrbottenspets, norsk buhund, papillon, phalène, schnauzer, shih tzu, softcoated wheaten terrier, tibetansk spaniel, tibetansk terrier, västgötaspets, welsh springer spaniel, west highland white terrier, whippet";
const petAddOns: BoatPetAddOnDefinition[] = [
  petAddOn("tryg", "Tryg", "hund", "tryg-hund-ekstra", "Ekstra", ["Behandling"], [
    row("dyr.rehabilitering.dekning", "Valgfritt tillegg", "tryg", "hund", 1, "Hund Ekstra", undefined, "boat-pet:tryg:hund:extra"),
    row("dyr.rehabilitering.grense", "10 000 kr per sykdom eller ulykkesskade", "tryg", "hund", 1, "Hund Ekstra", undefined, "boat-pet:tryg:hund:extra"),
    row("dyr.tannsykdom.dekning", "Valgfritt tillegg", "tryg", "hund", 1, "Hund Ekstra", undefined, "boat-pet:tryg:hund:extra"),
    row("dyr.tannsykdom.grense", "30 000 kr per sykdom eller ulykkesskade og per forsikringsår", "tryg", "hund", 1, "Hund Ekstra", undefined, "boat-pet:tryg:hund:extra"),
    row("dyr.tannsykdom.begrensning", "Fjerning av tannstein erstattes kun ved påvist periodontitt. Trekking av tilbakeholdte melketenner eller behandling av tannstillingsfeil som medfører medisinske problemer krever sammenhengende forsikring med dekning for dette i Tryg eller annet selskap fra før 4 måneders alder.", "tryg", "hund", 1, "2 Tann- og tannkjøttsykdommer", undefined, "boat-pet:tryg:hund:extra"),
  ]),
  petAddOn("tryg", "Tryg", "katt", "tryg-katt-ekstra", "Ekstra", ["Behandling"], [
    row("dyr.rehabilitering.dekning", "Valgfritt tillegg", "tryg", "katt", 1, "Katt Ekstra", undefined, "boat-pet:tryg:katt:extra"),
    row("dyr.rehabilitering.grense", "10 000 kr per sykdom eller ulykkesskade", "tryg", "katt", 1, "Katt Ekstra", undefined, "boat-pet:tryg:katt:extra"),
    row("dyr.tannsykdom.dekning", "Valgfritt tillegg", "tryg", "katt", 1, "Katt Ekstra", undefined, "boat-pet:tryg:katt:extra"),
    row("dyr.tannsykdom.grense", "30 000 kr per sykdom og per ulykkesskade, og maksimalt 30 000 kr samlet per forsikringsår. Innenfor denne tannrammen er behandling av tannresorpsjon begrenset til 5 000 kr per forsikringsår.", "tryg", "katt", 1, "2 Tann- og tannkjøttsykdommer", undefined, "boat-pet:tryg:katt:extra"),
    row("dyr.tannsykdom.begrensning", "Fjerning av tannstein erstattes kun ved påvist periodontitt. Trekking av tilbakeholdte melketenner eller behandling av tannstillingsfeil som medfører medisinske problemer krever sammenhengende forsikring med dekning for dette i Tryg eller annet selskap fra før 4 måneders alder.", "tryg", "katt", 1, "2 Tann- og tannkjøttsykdommer", undefined, "boat-pet:tryg:katt:extra"),
  ]),
  petAddOn("tryg", "Tryg", "hund", "tryg-hund-dod", "Hund død", ["Behandling"], [
    row("dyr.liv.forsvinning", "Inkludert i livsdekningen", "tryg", "hund", 1, "Hund død", undefined, "boat-pet:tryg:hund:life"),
    { ...row("dyr.liv.dekning", "Valgfri separat dekning for hunden i forsikringsbeviset: død eller avliving som følge av sykdom eller ulykkesskade, samt hund som blir borte eller bortført. Avliving må være nødvendig av dyrevernmessige hensyn og anbefalt av veterinær; avliving dekkes ikke dersom alternativ behandling eller medisin gir god prognose. Valgt forsikringssum fremgår av forsikringsbeviset og er begrenset til gjenanskaffelsespris for tilsvarende hund av samme rase.", "tryg", "hund", 1, "1–3 Hund død – omfang, utløsere og erstatning", undefined, "boat-pet:tryg:hund:life"), qualificationSource: { sourceId: "boat-pet:tryg:hund:life", page: 2, section: "3 Slik beregnes erstatningen – gjenanskaffelsespris" } },
    row("dyr.liv.begrensning", "Død eller avliving som følge av hofteleddsdysplasi (HD), albueleddsdysplasi (AD), albueleddsartrose (AA), Osteochondrose (OCD), patellaluksasjon, short ulna eller Calvé-Legg-Perthes krever sammenhengende forsikring med dekning for dette i Tryg eller annet selskap fra før 4 måneders alder.", "tryg", "hund", 1, "2 Tilleggsbestemmelser – død og avlivning", undefined, "boat-pet:tryg:hund:life"),
    row("dyr.liv.reduksjon.start", "Startalder avhenger av hunderase; startalderen for sen rasegruppe er uavklart i kildegrunnlaget.", "tryg", "hund", 2, "3 Slik beregnes erstatningen – raseavhengig startalder", undefined, "boat-pet:tryg:hund:life"),
    row("dyr.liv.reduksjon.sats", "Erstatningen reduseres med 20 % per år i aldersfradrag; minste erstatning etter aldersfradrag er 50 % av forsikringssummen, minimum 5 000 kr. Startalderen avhenger av rasegruppe og er ikke fastsatt her.", "tryg", "hund", 2, "3 Slik beregnes erstatningen – aldersfradrag og minste erstatning", undefined, "boat-pet:tryg:hund:life"),
    row("dyr.liv.opphor", "Hund død opphører ved første forfall etter at hunden har oppnådd maksimal alder på 12 år.", "tryg", "hund", 1, "4 Når forsikringen gjelder – maksimal alder og første forfall", undefined, "boat-pet:tryg:hund:product"),
  ]),
  petAddOn("tryg", "Tryg", "katt", "tryg-katt-dod", "Rasekatt død", ["Behandling"], [
    row("dyr.liv.forsvinning", "Inkludert i livsdekningen", "tryg", "katt", 1, "Rasekatt død", undefined, "boat-pet:tryg:katt:life"),
    row("dyr.liv.dekning", "Valgfri separat dekning for rasekatten i forsikringsbeviset: død eller avliving som følge av sykdom eller ulykkesskade, samt katt som blir borte eller bortført. Avliving må være nødvendig av dyrevernmessige hensyn og anbefalt av veterinær; avliving dekkes ikke dersom alternativ behandling eller medisin gir god prognose. Valgt forsikringssum fremgår av beviset og er begrenset til gjenanskaffelsespris for tilsvarende katt av samme rase.", "tryg", "katt", 1, "1–3 Rasekatt død – omfang, utløsere og erstatning", undefined, "boat-pet:tryg:katt:life"),
    row("dyr.liv.begrensning", "Død eller avliving som følge av hofteleddsdysplasi (HD) eller Calvé-Legg-Perthes krever sammenhengende forsikring med dekning for dette i Tryg eller annet selskap fra før 4 måneders alder.", "tryg", "katt", 1, "2 Tilleggsbestemmelser – død og avlivning", undefined, "boat-pet:tryg:katt:life"),
    row("dyr.liv.reduksjon.start", "Fra katten er blitt 7 år", "tryg", "katt", 1, "3 Slik beregnes erstatningen", undefined, "boat-pet:tryg:katt:life"),
    { ...row("dyr.liv.reduksjon.sats", "Erstatningen reduseres med 20 % per år i aldersfradrag; minste erstatning etter aldersfradrag er 40 % av forsikringssummen.", "tryg", "katt", 1, "3 Slik beregnes erstatningen", undefined, "boat-pet:tryg:katt:life"), qualificationSource: { sourceId: "boat-pet:tryg:katt:life", page: 2, section: "3 Slik beregnes erstatningen – minste erstatning" } },
    row("dyr.liv.opphor", "Rasekatt død opphører ved første forfall etter at katten har oppnådd maksimal alder på 12 år.", "tryg", "katt", 1, "4 Når forsikringen gjelder – maksimal alder og første forfall", undefined, "boat-pet:tryg:katt:product"),
  ]),
  ...(["hund", "katt"] as const).map((type) => petAddOn("if", "If", type, `${type === "hund" ? "if-hund" : "if-katt"}-liv`, "Liv", ["Basis", "Standard", "Super"], [row("dyr.liv.dekning", "Valgfri separat dekning", "if", type, 1, "Liv"), row("dyr.liv.sum.valgbar", "Forsikringssum velges og står i forsikringsbeviset", "if", type, 1, "Liv"), row("dyr.liv.reduksjon.start", type === "hund" ? "Gruppe 1 (berner sennenhund, grand danois, irsk ulvehund, leonberger, newfoundlandshund, pyreenerhund, napolitansk mastiff og sankt bernardshund): ved hver fornyelse fra året hunden fyller 6 år. Gruppe 2 (alle andre raser som ikke inngår i gruppe 1 og gruppe 3, samt blandingshunder): fra året hunden fyller 8 år. Gruppe 3 (bichon havanais, border terrier, cairn terrier, chihuahua, chinese crested, dvergschnauzer, finsk lapphund, finsk spetts, foxterrier, islandsk fårehund, jack russel terrier, lhasa apso, toy-, dverg- og mellompuddel, kleiner mustlander, norrbottenspets, norsk buhund, papillon, phalene, schnauzer, shih tzu, softcoated wheaten terrier, tibetansk spaniel, tibetansk terrier, welsh springer spaniel, west highland white terrier og whippet): fra året hunden fyller 10 år." : "Fra 10 år", "if", type, type === "hund" ? 6 : 5, type === "hund" ? "5.2" : "Liv"), row("dyr.liv.reduksjon.sats", "20 % av siste forsikringsårs forsikringssum per fornyelse", "if", type, type === "hund" ? 6 : 5, type === "hund" ? "5.2" : "Liv"), row("dyr.liv.opphor", type === "hund" ? "Gruppe 1: ved fornyelse det året hunden blir 8 år. Gruppe 2: ved hovedforfall det året hunden blir 10 år. Gruppe 3: ved hovedforfall det året hunden blir 12 år. Rasegruppene følger 5.2." : "Ved fornyelse det året katten blir 13 år", "if", type, type === "hund" ? 6 : 5, type === "hund" ? "5.2" : "Liv")])),
  petAddOn("gjensidige", "Gjensidige", "hund", "gjensidige-hund-liv", "Liv", ["Behandling"], [row("dyr.liv.dekning", "Valgfri modul", "gjensidige", "hund", 1, "Liv")]),
  gjensidigeBruk("hund"),
  petAddOn("gjensidige", "Gjensidige", "katt", "gjensidige-katt-liv", "Liv", ["Behandling"], [row("dyr.liv.dekning", "Valgfri modul", "gjensidige", "katt", 1, "Liv")]),
  gjensidigeBruk("katt"),
  petAddOn("sparebank1-fremtind", "Fremtind", "hund", "sparebank1-fremtind-hund-topp", "Topp veterinærutgifter", ["Veterinær"], [
    { ...row("dyr.allergi.dekning", "Valgfri utvidelse: utredning, behandling og medisiner til atopi/allergi innenfor valgt forsikringssum per forsikringsår og med valgt egenandel.", "sparebank1-fremtind", "hund", 3, "Topp veterinærutgifter – atopi/allergi", undefined, "boat-pet:sparebank1-fremtind:hund"), qualificationSource: { sourceId: "boat-pet:sparebank1-fremtind:hund", page: 1, section: "6 Forsikringssum og egenandel" } },
    { ...row("dyr.allergi.grense", "Innenfor valgt forsikringssum per forsikringsår og med valgt egenandel; ingen egen livstidsgrense på 15 000 kr når Topp er valgt.", "sparebank1-fremtind", "hund", 3, "Topp veterinærutgifter – atopi/allergi", undefined, "boat-pet:sparebank1-fremtind:hund"), qualificationSource: { sourceId: "boat-pet:sparebank1-fremtind:hund", page: 1, section: "6 Forsikringssum og egenandel" } },
    { ...row("dyr.diagnostikk.dekning", "Valgfri utvidelse: MR/CT innenfor valgt forsikringssum per forsikringsår og med valgt egenandel.", "sparebank1-fremtind", "hund", 3, "Topp veterinærutgifter – MR/CT", undefined, "boat-pet:sparebank1-fremtind:hund"), qualificationSource: { sourceId: "boat-pet:sparebank1-fremtind:hund", page: 1, section: "6 Forsikringssum og egenandel" } },
    { ...row("dyr.diagnostikk.grense", "MR/CT innenfor valgt forsikringssum per forsikringsår og med valgt egenandel; ingen egen årsgrense på 15 000 kr når Topp er valgt.", "sparebank1-fremtind", "hund", 3, "Topp veterinærutgifter – MR/CT", undefined, "boat-pet:sparebank1-fremtind:hund"), qualificationSource: { sourceId: "boat-pet:sparebank1-fremtind:hund", page: 1, section: "6 Forsikringssum og egenandel" } },
    { ...row("dyr.tannsykdom.dekning", "Valgfri utvidelse: tannbehandling for karies, emaljedefekt og tannresorpsjon. Tilbakeholdte melketenner, tanncyster, tannstilling- og bittfeil dekkes dersom det er medisinsk nødvendig og hunden er forsikret før fire måneders alder. Ved korrigering av tannstilling- og bittfeil kreves veterinærattest fra hunden er mellom syv uker og fire måneders alder, uten anmerking på tenner/bitt. Innenfor valgt forsikringssum per forsikringsår og med valgt egenandel.", "sparebank1-fremtind", "hund", 3, "Topp veterinærutgifter – tannbehandling", undefined, "boat-pet:sparebank1-fremtind:hund"), qualificationSource: { sourceId: "boat-pet:sparebank1-fremtind:hund", page: 1, section: "6 Forsikringssum og egenandel" } },
    { ...row("dyr.rehabilitering.dekning", "Valgfri utvidelse. Fysioterapi, rehabilitering og kiropraktikk utført i løpet av 6 måneder etter bestilling fra behandlende veterinær, innenfor valgt forsikringssum per forsikringsår og med valgt egenandel.", "sparebank1-fremtind", "hund", 3, "Topp veterinærutgifter", undefined, "boat-pet:sparebank1-fremtind:hund"), qualificationSource: { sourceId: "boat-pet:sparebank1-fremtind:hund", page: 1, section: "6 Forsikringssum og egenandel" } },
  ]),
  ...(["hund", "katt"] as const).map((type) => {
    const lifeSource = `boat-pet:sparebank1-fremtind:${type}:life`;
    if (type === "katt") return petAddOn("sparebank1-fremtind", "Fremtind", "katt", "sparebank1-fremtind-katt-liv", "Død, tap og tyveri", ["Veterinær"], [
      { ...row("dyr.liv.dekning", "Valgfri separat dekning for rasekatt: kattens verdi ved død eller nødvendig avliving som følge av ulykke eller sykdom dekket av veterinærforsikringen, samt forsvinning og tyveri. Sykdommer/lidelser og kostnader som ikke dekkes av veterinærforsikringen er unntatt. Inntil valgt forsikringssum i kundens forsikringsbevis.", "sparebank1-fremtind", "katt", 1, "Død/tap katt – dekker og dekker ikke", undefined, "boat-pet:sparebank1-fremtind:katt:life"), qualificationSource: { sourceId: "boat-pet:sparebank1-fremtind:katt:product", page: 1, section: "Dekninger – Død eller avlivning og Tap eller tyveri: kun rasekatt" } },
      row("dyr.liv.reduksjon.start", "Aldersfradrag ved hovedforfall etter at katten har fylt 7 år", "sparebank1-fremtind", "katt", 1, "Erstatningsregler", undefined, "boat-pet:sparebank1-fremtind:katt:life"),
      row("dyr.liv.reduksjon.sats", "20 % per år av den totale erstatningen; forsikringssummen blir ikke satt lavere enn 1 500 kr", "sparebank1-fremtind", "katt", 1, "Erstatningsregler", undefined, "boat-pet:sparebank1-fremtind:katt:life"),
      row("dyr.liv.opphor", "Død, tyveri og forsvinning opphører automatisk ved hovedforfall etter at katten har fylt 12 år", "sparebank1-fremtind", "katt", 1, "Opphør av forsikringen", undefined, "boat-pet:sparebank1-fremtind:katt:life"),
      row("dyr.liv.forsvinning", "Inkludert når Liv er valgt: forsvunnet katt skal meldes til politiet og etterlyses ved annonsering. Erstatning utbetales tidligst 3 måneder etter at hendelsen er meldt til oss og politiet.", "sparebank1-fremtind", "katt", 1, "Erstatningsregler – forsvinning og tyveri", undefined, "boat-pet:sparebank1-fremtind:katt:life"),
      row("dyr.liv.tyveri", "Inkludert når Liv er valgt: stjålet katt skal meldes til politiet og etterlyses ved annonsering. Erstatning utbetales tidligst 3 måneder etter at hendelsen er meldt til oss og politiet.", "sparebank1-fremtind", "katt", 1, "Erstatningsregler – forsvinning og tyveri", undefined, "boat-pet:sparebank1-fremtind:katt:life"),
      row("dyr.liv.begrensning", "Livsforsikring ved død/avliving og tap/tyveri gjelder kun rasekatt", "sparebank1-fremtind", "katt", 1, "SB1matrix/IPID – død/avliving og tap/tyveri", undefined, "boat-pet:sparebank1-fremtind:katt:product"),
    ]);
    return petAddOn("sparebank1-fremtind", "Fremtind", type, `sparebank1-fremtind-${type}-liv`, "Død, tap og tyveri", ["Veterinær"], [row("dyr.liv.dekning", "Valgfri separat dekning for hunden i forsikringsbeviset inntil valgt forsikringssum: hundens verdi hvis hunden dør eller må avlives i forsikringstiden som følge av ulykke eller sykdom som er dekket av veterinærforsikringen, samt forsvinning og tyveri. Sykdommer, lidelser og kostnader som ikke er dekket av veterinærforsikringen er unntatt. Erstatningen er gjenanskaffelseskostnad for tilsvarende hund på skadedagen, begrenset til valgt forsikringssum.", "sparebank1-fremtind", "hund", 1, "Død/tap hund – dekning og erstatningsregler", undefined, "boat-pet:sparebank1-fremtind:hund:life"), row("dyr.liv.forsvinning", "Inkludert når livsdekningen er valgt: stjålet/forsvunnet hund skal meldes til politiet og etterlyses ved annonsering. Erstatningen utbetales tidligst 3 måneder etter at hendelsen er meldt til selskapet og politiet.", "sparebank1-fremtind", "hund", 1, "Død/tap hund – stjålet/forsvunnet hund", undefined, "boat-pet:sparebank1-fremtind:hund:life"), row("dyr.liv.tyveri", "Inkludert når livsdekningen er valgt: stjålet/forsvunnet hund skal meldes til politiet og etterlyses ved annonsering. Erstatningen utbetales tidligst 3 måneder etter at hendelsen er meldt til selskapet og politiet.", "sparebank1-fremtind", "hund", 1, "Død/tap hund – stjålet/forsvunnet hund", undefined, "boat-pet:sparebank1-fremtind:hund:life"), row("dyr.liv.reduksjon.start", type === "hund" ? `Fullvilkåret oppgir hovedforfall etter fylte 5 år for ${fremtindDogEarlyLifeGroup}; 7 år for øvrige raser og blandingshund; 9 år for ${fremtindDogLateLifeGroup}` : "Etter fylte 7 år", "sparebank1-fremtind", type, 1, "Erstatningsregler", undefined, lifeSource), row("dyr.liv.reduksjon.sats", type === "hund" ? "20 % per år av total erstatning; forsikringssummen settes ikke lavere enn 1 500 kr" : "20 % per år", "sparebank1-fremtind", type, 1, "Erstatningsregler", undefined, lifeSource), row("dyr.liv.opphor", type === "hund" ? `Fullvilkåret oppgir opphør ved hovedforfall etter fylte 8 år for ${fremtindDogEarlyLifeGroup}; 10 år for øvrige raser og blandingshund; 12 år for ${fremtindDogLateLifeGroup}` : "Etter fylte 12 år", "sparebank1-fremtind", type, 1, "Opphør", undefined, lifeSource)]);
  }),
  petAddOn("sparebank1-fremtind", "Fremtind", "hund", "sparebank1-fremtind-hund-bruk", "Bruksverdi", ["Veterinær"], [
    row("hund.bruksverdi.dekning", "Valgfri separat dekning: varig tap av bruksverdi som følge av ulykke eller sykdom som er dekket av veterinærforsikringen, inntil valgt forsikringssum. Tapet må dokumenteres av veterinær etter utredning, behandling og tilstrekkelig lang hvileperiode. Dokumentert praktisk arbeid eller offisiell konkurransevirksomhet de siste 12 månedene før sykdom eller skade oppsto er påkrevd.", "sparebank1-fremtind", "hund", 1, "Tap av bruksverdi hund – dekning og dokumentasjon", undefined, "boat-pet:sparebank1-fremtind:hund:use"),
    row("hund.bruksverdi.begrensning", "Jakthund, gjeterhund og tjenestehund må være trent for og regelmessig brukt til formålet, med minst 50 % redusert bruksegenskap. Avlshund må ha mistet avlsevnen 100 %: hannhund må være far til minst ett kull siste to år, og tispe må ha født minst ett kull på normal måte siste to år før sykdom/skade; parringen/kullene må være registrert i Norsk Kennel Klubb. Tap av utstillingsevner og andre bruksområder enn avl, jakt, gjeting og tjeneste er unntatt, samt sykdommer, lidelser og kostnader som ikke dekkes av veterinærforsikringen.", "sparebank1-fremtind", "hund", 1, "Tap av bruksverdi hund – forutsetninger og unntak", undefined, "boat-pet:sparebank1-fremtind:hund:use"),
    row("hund.bruksverdi.alder", "Opphører ved hovedforfall etter fylte 8 år", "sparebank1-fremtind", "hund", 1, "Opphør", undefined, "boat-pet:sparebank1-fremtind:hund:use"),
  ]),
  ...(["hund", "katt"] as const).flatMap((type) => [
    petAddOn("frende", "Frende", type, `frende-${type}-medisin`, "Medisin", ["Veterinær"], [type === "hund"
      ? row("dyr.medisin.dekning", "Valgfri dekning når oppført i forsikringsbeviset: rimelige og nødvendige utgifter til reseptbelagte medisiner ved skade/sykdom som omfattes av punkt 4 og 5; 50 % av veterinærforeskrevet spesialfôr. Inntil 20 000 kr per skadetilfelle og samlet per forsikringsår", "frende", type, 3, "6 Medisinutgifter")
      : row("dyr.medisin.dekning", "Valgfri dekning når oppført i forsikringsbeviset: rimelige og nødvendige utgifter til reseptbelagte medisiner ved skade/sykdom som omfattes av punkt 4; 50 % av veterinærforeskrevet spesialfôr. Inntil 20 000 kr per skadetilfelle og samlet per forsikringsår", "frende", type, 3, "5 Medisinutgifter")]),
    ...(type === "hund" ? [petAddOn("frende", "Frende", type, "frende-hund-tann", "Tann", ["Veterinær"], [
      row("dyr.tannsykdom.dekning", "Valgfri dekning når oppført i forsikringsbeviset: rimelige og nødvendige utgifter til tann- og tannkjøttsykdommer, inkludert medisiner/materiell veterinæren bruker og nødvendig klinikkopphold; trekking av tilbakeholdte melketenner og medisinsk nødvendig retting av tannstillingsfeil", "frende", type, 3, "5.1"),
      row("dyr.tannsykdom.grense", "Inntil 20 000 kr per skadetilfelle og samlet per forsikringsår", "frende", type, 3, "5.1"),
      row("dyr.tannsykdom.begrensning", "Unntatt forebyggende undersøkelse/behandling, rehabilitering, reiser, fôr, foreskrevne/utleverte medisiner og forbindingsmateriell. Eksisterende sykdom/skade ved kjøp i Frende eller tidligere selskap og sykdom innen 20 dager er unntatt; ved sumøkning bare økningen. Behandling av dekket skade/sykdom mer enn ett år etter opphør er unntatt", "frende", type, 3, "5.2"),
    ])] : []),
    { ...petAddOn("frende", "Frende", type, `frende-${type}-tap`, "Tap", ["Veterinær"], [...(type === "hund" ? [
      row("dyr.liv.dekning", "Valgfri dekning når oppført i forsikringsbeviset: hunden dør eller avlives av dyrevernhensyn etter ulykke/sykdom, blir stjålet eller forsvinner, eller helt taper bruksegenskaper etter ulykke/sykdom som dokumentert ferdig trent og regelmessig brukt brukshund", "frende", type, 3, "7.1 (fortsatt side 4)"),
      row("dyr.liv.begrensning", "Unntatt sykdom/skade ved kjøp i Frende eller tidligere selskap, eller innen 20 dager etter kjøp; ved sumøkning bare økningen. Avliving på grunn av adferdsforstyrrelser/unormalt temperament eller komplikasjoner etter behandling/operative inngrep som ikke omfattes er unntatt", "frende", type, 4, "7.2"),
    ] : [row("dyr.liv.dekning", "Valgfri dekning når oppført i forsikringsbeviset", "frende", type, 3, "Tap"),
      row("dyr.liv.begrensning", "Unntatt sykdom/skade ved kjøp i Frende eller tidligere selskap, eller som oppstår innen 20 dager etter kjøp; ved sumøkning bare økningen. Avliving etter komplikasjoner etter behandling og operative inngrep som ikke omfattes av forsikringen er unntatt", "frende", type, 3, "6.2"),
    ]), row("dyr.liv.forsvinning", "Inkludert i valgt Tap-dekning", "frende", type, 3, "Tap"), row("dyr.liv.opphor", "Første hovedforfall etter 10 år", "frende", type, 2, "Hvor og når"), ...(type === "hund" ? frendeDogUseRows : [])]),
      ...(type === "hund" ? { selectionEvidenceKeys: ["dyr.liv.dekning"] } : {}) },
  ]),
];

const built = buildBoatPetCatalog(boatPetSources, [...boatProducts, ...petProducts], [...boatAddOns, ...petAddOns]);
// Topp erstatter bare de uttrykkelig utvidede basisreglene når tillegget er valgt.
for (const fact of built.facts["sparebank1-fremtind-hund-topp"]) {
  if (["dyr.allergi.dekning", "dyr.allergi.grense", "dyr.diagnostikk.dekning", "dyr.diagnostikk.grense"].includes(fact.key)) {
    fact.replacesBase = true;
  }
}
export const boatPetProducts = built.products;
export const boatPetFacts = built.facts;
export const boatPetAddOns = built.addOns;
export const boatPetAgreementScopes: AgreementScopeDefinition[] = [];
