import type { CatalogSource } from "./product-catalog.ts";
import { buildBoatPetCatalog, type BoatPetAddOnDefinition, type BoatPetProductDefinition, type BoatPetRow } from "./boat-pet-catalog-builder.ts";
import type { AgreementScopeDefinition } from "./agreement-scope.ts";

type SourceSeed = {
  id?: string;
  providerId: string; company: string; type: "båt" | "hund" | "katt"; filename: string;
  version: string; termsNumber: string; url: string; sha256: string; sourceType?: CatalogSource["sourceType"];
};

const sourceSeeds: SourceSeed[] = [
  { providerId: "tryg", company: "Tryg", type: "båt", filename: "tryg-boat-ipid.pdf", version: "2024-07-01", termsNumber: "IPID Fritidsbåtforsikring", url: "https://www.tryg.no/system/files/download/pdf/ipid/IPID-Batforsikring.pdf", sha256: "75d8af24d727a2994d3fc2ae566ad075f1cb7f7edad4993d78c3b59bc1700ff5", sourceType: "ipid" },
  { providerId: "tryg", company: "Tryg", type: "hund", filename: "tryg-pet-ipid.pdf", version: "2026-09-01", termsNumber: "IPID Dyreforsikring", url: "https://www.tryg.no/system/files/download/pdf/ipid/IPID-Hund-og-katt.pdf", sha256: "41843abc16ad8ee39782e70f29d8cbb115463bcebe28882cca42078ce07fd824" , sourceType: "ipid"},
  { providerId: "tryg", company: "Tryg", type: "katt", filename: "tryg-pet-ipid.pdf", version: "2026-09-01", termsNumber: "IPID Dyreforsikring", url: "https://www.tryg.no/system/files/download/pdf/ipid/IPID-Hund-og-katt.pdf", sha256: "41843abc16ad8ee39782e70f29d8cbb115463bcebe28882cca42078ce07fd824", sourceType: "ipid" },
  { id: "boat-pet:tryg:båt:machinery", providerId: "tryg", company: "Tryg", type: "båt", filename: "tryg-boat-machinery-terms.pdf", version: "2026-01-01", termsNumber: "PFB36910", url: "https://www.tryg.no/forsikringer/kjoretoy/batforsikring", sha256: "c4a722384e402e7581f9a2b718b0fbe90b622912261b41279e1904a9d960f50d" },
  { id: "boat-pet:tryg:båt:accident", providerId: "tryg", company: "Tryg", type: "båt", filename: "tryg-boat-accident-terms.pdf", version: "2022-02-01", termsNumber: "PFB38900", url: "https://www.tryg.no/forsikringer/kjoretoy/batforsikring", sha256: "0d1cbbbdc41c4ee3a25a511eac8fdd194737bce2577c9a657256589ae221b95c" },
  { id: "boat-pet:tryg:hund:extra", providerId: "tryg", company: "Tryg", type: "hund", filename: "tryg-dog-extra-terms.pdf", version: "2025-07-01", termsNumber: "PLB52003", url: "https://www.tryg.no/forsikringer/hundeforsikring", sha256: "10972b0580b3cc804419621d3c5193d9be3e8bc24e8bafb58519e6e0a203af2c" },
  { id: "boat-pet:tryg:katt:extra", providerId: "tryg", company: "Tryg", type: "katt", filename: "tryg-cat-extra-terms.pdf", version: "2025-07-01", termsNumber: "PLB52004", url: "https://www.tryg.no/forsikringer/katteforsikring", sha256: "f4267143ea6f0643341503cf60ce50ce7036cf83af21b3ec29f514d1a7738972" },
  { id: "boat-pet:tryg:hund:life", providerId: "tryg", company: "Tryg", type: "hund", filename: "tryg-dog-life-terms.pdf", version: "2026-01-01", termsNumber: "PLB52001", url: "https://www.tryg.no/forsikringer/hundeforsikring", sha256: "5d5e22fa589538a2708b87616b339eec0c3f0a27c5b322fa48d1b4582e013fcc" },
  { id: "boat-pet:tryg:katt:life", providerId: "tryg", company: "Tryg", type: "katt", filename: "tryg-cat-life-terms.pdf", version: "2026-01-01", termsNumber: "PLB52005", url: "https://www.tryg.no/forsikringer/katteforsikring", sha256: "8024b9853d3ff80259f939418f31f03e332d280bfca612d613390a7699e5eb3c" },
  { providerId: "if", company: "If", type: "båt", filename: "if-boat-terms.pdf", version: "2023-02-01", termsNumber: "BÅT2-1", url: "https://if.no/apps/vilkarsbasendokument/Vilkaar?produkt=B%C3%A5tforsikring", sha256: "57e7aac8542dd10bfc92611f380b68754905b6808a66590307af86517c2072ae" },
  { providerId: "if", company: "If", type: "hund", filename: "if-dog-terms.pdf", version: "2022-12-01", termsNumber: "Hundeforsikring", url: "https://if.no/apps/vilkarsbasendokument/Vilkaar?produkt=Hundeforsikring", sha256: "d2372736a4d99d4c434ac87ea068c5051908742ae03e454220b6b1cc1d436c75" },
  { providerId: "if", company: "If", type: "katt", filename: "if-cat-terms.pdf", version: "2022-12-01", termsNumber: "Katteforsikring", url: "https://if.no/apps/vilkarsbasendokument/Vilkaar?produkt=Katteforsikring", sha256: "bcd631394fbfe7d0a6f0de3d7e79dc82aee2f5d5bb16d4a0b7192e177716abe7" },
  { providerId: "gjensidige", company: "Gjensidige", type: "båt", filename: "gjensidige-boat-ipid.pdf", version: "", termsNumber: "EAP14", url: "https://www.gjensidige.no/forsikring/batforsikring", sha256: "c0e14e39f1c5dce3c6d238e8822eb14267e998ad0e762f08887d05bc3cb9c7a0", sourceType: "ipid" },
  { providerId: "gjensidige", company: "Gjensidige", type: "hund", filename: "gjensidige-dog-ipid.pdf", version: "", termsNumber: "EAP32", url: "https://www.gjensidige.no/forsikring/dyreforsikring/hundeforsikring", sha256: "aa39107d5777e4f0a342918ef9e4ceba8828793665a3dc2eb41172107d1404ba", sourceType: "ipid" },
  { providerId: "gjensidige", company: "Gjensidige", type: "katt", filename: "gjensidige-cat-ipid.pdf", version: "", termsNumber: "EAP30", url: "https://www.gjensidige.no/forsikring/dyreforsikring/katteforsikring", sha256: "314d266136da6b7b5aec994b70d45591e687bd5baac203fe0609437e7fdc4ee8", sourceType: "ipid" },
  { providerId: "storebrand", company: "Storebrand", type: "båt", filename: "storebrand-boat-terms.pdf", version: "2024-09-01", termsNumber: "båt03", url: "https://www.storebrand.no/privat/forsikring/batforsikring", sha256: "e945049a6b9fba643d9804279690fc8e1dfbb1cd4a419a81503e58fd5b959baa" },
  { providerId: "storebrand", company: "Storebrand", type: "hund", filename: "storebrand-pet-terms.pdf", version: "2025-02-01", termsNumber: "dyr04", url: "https://www.storebrand.no/privat/forsikring/hundeforsikring", sha256: "b236f856380b8010c7439765ea72a88d076e5d387d4653a7f033980892732591" },
  { providerId: "storebrand", company: "Storebrand", type: "katt", filename: "storebrand-pet-terms.pdf", version: "2025-02-01", termsNumber: "dyr04", url: "https://www.storebrand.no/privat/forsikring/katteforsikring", sha256: "b236f856380b8010c7439765ea72a88d076e5d387d4653a7f033980892732591" },
  { providerId: "sparebank1-fremtind", company: "Fremtind", type: "båt", filename: "fremtind-boat-terms.pdf", version: "2024-06-10", termsNumber: "PMO-380.000-004", url: "https://www.sparebank1.no/nb/bank/privat/forsikring/batforsikring.html", sha256: "1364fc8bde39923ea1e9f0f36a9d9abf5596721958114b93485b5c730d70669f" },
  { providerId: "sparebank1-fremtind", company: "Fremtind", type: "hund", filename: "fremtind-dog-vet-terms.pdf", version: "2025-08-07", termsNumber: "PBK-231.200-004", url: "https://www.sparebank1.no/nb/bank/privat/forsikring/hundeforsikring.html", sha256: "5897fd60318410bdc5481e12d4cd6454e7fe4741682a13e5289991f211b7d9f7" },
  { providerId: "sparebank1-fremtind", company: "Fremtind", type: "katt", filename: "fremtind-cat-vet-terms.pdf", version: "2025-08-07", termsNumber: "PBK-231.300-002", url: "https://www.sparebank1.no/nb/bank/privat/forsikring/katteforsikring.html", sha256: "91385b8b466923a5ca1c37d8f53781c5af3f63e3f6e037afae367f4399b75286" },
  { id: "boat-pet:sparebank1-fremtind:hund:life", providerId: "sparebank1-fremtind", company: "Fremtind", type: "hund", filename: "fremtind-dog-life-terms.pdf", version: "2025-08-07", termsNumber: "PBK-231.210-002", url: "https://www.sparebank1.no/nb/bank/privat/forsikring/hundeforsikring.html", sha256: "8445f2c6faede5cfe1c6054e58cc880fc4cea1bbc31321ddc76fdbd035dcf43d" },
  { id: "boat-pet:sparebank1-fremtind:katt:life", providerId: "sparebank1-fremtind", company: "Fremtind", type: "katt", filename: "fremtind-cat-life-terms.pdf", version: "2025-08-07", termsNumber: "PBK-231.310-002", url: "https://www.sparebank1.no/nb/bank/privat/forsikring/katteforsikring.html", sha256: "9b9b295ff51687c8361c1e2fb8fc192fb26fbc0112d5e78b4e569b9d6c4c27ac" },
  { id: "boat-pet:sparebank1-fremtind:hund:use", providerId: "sparebank1-fremtind", company: "Fremtind", type: "hund", filename: "fremtind-dog-use-terms.pdf", version: "2025-08-07", termsNumber: "PBK-231.220-002", url: "https://www.sparebank1.no/nb/bank/privat/forsikring/hundeforsikring.html", sha256: "456a1c4f38b4c3934bf0b4c9ed1167e805d5238fb1960115d9cb1e2e65aafcc2" },
  { providerId: "frende", company: "Frende", type: "båt", filename: "frende-boat-terms.pdf", version: "2026-01-01", termsNumber: "Båtforsikring", url: "https://www.frende.no/forsikringer/batforsikring/", sha256: "272b9c86efaf39c30930b284fdadc49019d4e2f98ca13c2de426d0ec2f4f66d0" },
  { providerId: "frende", company: "Frende", type: "hund", filename: "frende-dog-terms.pdf", version: "2026-01-01", termsNumber: "Hundeforsikring", url: "https://www.frende.no/forsikringer/hundeforsikring/", sha256: "6d052e5092d9f92050dcf95a92fa6ce5deda18a5825cdd00ca1c8cd2658c9135" },
  { providerId: "frende", company: "Frende", type: "katt", filename: "frende-cat-terms.pdf", version: "2026-01-01", termsNumber: "Katteforsikring", url: "https://www.frende.no/forsikringer/katteforsikring/", sha256: "5c7791b59cf84da6ef475020f997bac1cc13a865777bdc791b2c3f7ba4b4fe6b" },
];

const sourceId = (providerId: string, type: string) => `boat-pet:${providerId}:${type}`;
export const boatPetSources: Record<string, CatalogSource> = Object.fromEntries(sourceSeeds.map((seed) => {
  const id = seed.id ?? sourceId(seed.providerId, seed.type);
  return [id, {
    id, filename: seed.filename, providerId: seed.providerId, company: seed.company,
    insuranceType: seed.type === "båt" ? "Båt" : seed.type === "hund" ? "Hund" : "Katt",
    agreementScope: "ordinary", sourceType: seed.sourceType ?? "full_terms", termsNumber: seed.termsNumber,
    effectiveFrom: seed.version, version: seed.version, url: seed.url, sha256: seed.sha256, documentName: seed.termsNumber,
  } satisfies CatalogSource];
}));

const row = (key: string, value: string, providerId: string, type: "båt" | "hund" | "katt", page: number, section: string, classification?: BoatPetRow["deductibleClassification"], exactSourceId?: string): BoatPetRow => ({
  key, value, sourceId: exactSourceId ?? sourceId(providerId, type), page, section,
  ...(classification ? { deductibleClassification: classification } : {}),
});

const boatCore = (providerId: string, geography: string): BoatPetRow[] => [
  row("bat.ansvar.dekning", "Inkludert", providerId, "båt", 1, "Produktoversikt"),
  row("bat.rettshjelp.dekning", "Inkludert", providerId, "båt", 1, "Produktoversikt"),
  row("bat.geografi.dekning", "Inkludert", providerId, "båt", 1, "Geografisk område"),
  row("bat.geografi.omrade", geography, providerId, "båt", 1, "Geografisk område"),
];
const boatFire = (providerId: string, geography: string): BoatPetRow[] => [
  ...boatCore(providerId, geography),
  row("bat.brann.dekning", "Inkludert", providerId, "båt", 1, "Brann"),
  row("bat.tyveri.dekning", "Inkludert", providerId, "båt", 1, "Tyveri"),
];
const boatKasko = (providerId: string, geography: string): BoatPetRow[] => [
  ...boatFire(providerId, geography),
  row("bat.kasko.dekning", "Inkludert", providerId, "båt", 1, "Kasko"),
  row("bat.redning.dekning", "Inkludert", providerId, "båt", 1, "Redning og berging"),
  row("bat.transport.dekning", "Inkludert ved dekningsmessig skade", providerId, "båt", 1, "Transport"),
];
const product = (
  providerId: string, company: string, name: string, rows: BoatPetRow[], version: string | null,
): BoatPetProductDefinition => ({
  providerId, company, type: "båt", agreementScope: "ordinary",
  productId: `${providerId}-bat-${name.toLocaleLowerCase("nb-NO").normalize("NFKD").replace(/\p{M}/gu, "").replace(/[^a-z0-9]+/gu, "-").replace(/^-|-$/gu, "")}`,
  name, version, sourceId: sourceId(providerId, "båt"), rows,
});

const boatProducts: BoatPetProductDefinition[] = [
  product("tryg", "Tryg", "Ansvar", boatCore("tryg", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter; Russland er unntatt"), "2024-07-01"),
  product("tryg", "Tryg", "Brann/Ansvar", [...boatCore("tryg", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter; Russland er unntatt"), row("bat.brann.dekning", "Inkludert", "tryg", "båt", 1, "Brann/Ansvar")], "2024-07-01"),
  product("tryg", "Tryg", "Brann/Tyveri/Ansvar", boatFire("tryg", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter; Russland er unntatt"), "2024-07-01"),
  product("tryg", "Tryg", "Kasko/Ansvar", [...boatKasko("tryg", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter; Russland er unntatt"), row("bat.haerverk.dekning", "Inkludert", "tryg", "båt", 1, "Kasko/Ansvar")], "2024-07-01"),
  product("tryg", "Tryg", "Båt Ekstra", [...boatKasko("tryg", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter; Russland er unntatt"), row("bat.ferieavbrudd.dekning", "Inkludert", "tryg", "båt", 1, "Båt Ekstra"), row("bat.opplagsutstyr.dekning", "Inkludert", "tryg", "båt", 1, "Båt Ekstra"), row("bat.jolle.dekning", "Inkludert", "tryg", "båt", 1, "Båt Ekstra")], "2024-07-01"),
  product("if", "If", "Delkasko", boatFire("if", "Europa og europeiske farvann inntil 200 nautiske mil fra grunnlinjen, med dokumenterte overfarter"), "2023-02-01"),
  product("if", "If", "Kasko", [...boatKasko("if", "Europa og europeiske farvann inntil 200 nautiske mil fra grunnlinjen, med dokumenterte overfarter"), row("bat.losore.dekning", "Inkludert", "if", "båt", 3, "Hva er forsikret"), row("bat.losore.grense", "50 000 kr per skadetilfelle", "if", "båt", 3, "Hva er forsikret")], "2023-02-01"),
  product("if", "If", "Super", [...boatKasko("if", "Europa og europeiske farvann inntil 200 nautiske mil fra grunnlinjen, med dokumenterte overfarter"), row("bat.ferieavbrudd.dekning", "Inkludert", "if", "båt", 6, "4.10 Superforsikring"), row("bat.losore.grense", "Uten særskilt sumbegrensning innenfor produktvilkårene", "if", "båt", 6, "4.10.1"), row("bat.opplagsutstyr.dekning", "Inkludert", "if", "båt", 6, "4.10.6")], "2023-02-01"),
  product("gjensidige", "Gjensidige", "Delkasko", boatFire("gjensidige", "Europa inntil 200 nautiske mil fra land"), null),
  product("gjensidige", "Gjensidige", "Kasko", boatKasko("gjensidige", "Europa inntil 200 nautiske mil fra land"), null),
  product("gjensidige", "Gjensidige", "Pluss", [...boatKasko("gjensidige", "Europa inntil 200 nautiske mil fra land"), row("bat.totalskade.dekning", "Inkludert", "gjensidige", "båt", 1, "Pluss"), row("bat.maskinskade.dekning", "Inkludert med motor- og båttypebegrensninger", "gjensidige", "båt", 1, "Pluss"), row("bat.maskinskade.alder", "Motor og drivverk eldre enn 10 år er unntatt", "gjensidige", "båt", 1, "Pluss"), row("bat.ferieavbrudd.dekning", "Inkludert", "gjensidige", "båt", 1, "Pluss")], null),
  product("storebrand", "Storebrand", "Delkasko", boatFire("storebrand", "Norden; 1. april–30. september også Europa inntil 200 nautiske mil og dokumenterte overfarter"), "2024-09-01"),
  product("storebrand", "Storebrand", "Kasko", [...boatKasko("storebrand", "Norden; 1. april–30. september også Europa inntil 200 nautiske mil og dokumenterte overfarter"), row("bat.opplagsutstyr.dekning", "Inkludert", "storebrand", "båt", 8, "5.2 Kasko")], "2024-09-01"),
  product("storebrand", "Storebrand", "Super", [...boatKasko("storebrand", "Norden; 1. april–30. september også Europa inntil 200 nautiske mil og dokumenterte overfarter"), row("bat.ferieavbrudd.dekning", "Inkludert", "storebrand", "båt", 8, "5.3 Super"), row("bat.ferieavbrudd.dager", "Inntil 30 dager", "storebrand", "båt", 8, "5.3 Super"), row("bat.ferieavbrudd.grense", "Inntil 60 000 kr", "storebrand", "båt", 8, "5.3 Super"), row("bat.totalskade.dekning", "Inkludert", "storebrand", "båt", 8, "5.3 Super"), row("bat.totalskade.alder", "Inntil 3 år fra kjøpsdato", "storebrand", "båt", 8, "5.3 Super")], "2024-09-01"),
  product("sparebank1-fremtind", "Fremtind", "Delkasko", boatFire("sparebank1-fremtind", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter"), "2024-06-10"),
  product("sparebank1-fremtind", "Fremtind", "Kasko", [...boatKasko("sparebank1-fremtind", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter"), row("bat.ferieavbrudd.dekning", "Inkludert", "sparebank1-fremtind", "båt", 7, "Kasko"), row("bat.ferieavbrudd.dager", "Inntil 10 dager", "sparebank1-fremtind", "båt", 7, "Kasko"), row("bat.ferieavbrudd.dagsbelop", "Inntil 1 000 kr per dag", "sparebank1-fremtind", "båt", 7, "Kasko")], "2024-06-10"),
  product("sparebank1-fremtind", "Fremtind", "Toppkasko", [...boatKasko("sparebank1-fremtind", "Europa inntil 200 nautiske mil fra fastlandet, med dokumenterte overfarter"), row("bat.ferieavbrudd.dekning", "Inkludert", "sparebank1-fremtind", "båt", 8, "Toppkasko"), row("bat.ferieavbrudd.dager", "Inntil 15 dager", "sparebank1-fremtind", "båt", 8, "Toppkasko"), row("bat.ferieavbrudd.dagsbelop", "Inntil 1 500 kr per dag", "sparebank1-fremtind", "båt", 8, "Toppkasko"), row("bat.totalskade.dekning", "Inkludert", "sparebank1-fremtind", "båt", 9, "Totalskadegaranti"), row("bat.maskinskade.dekning", "Inkludert med dokumenterte motor- og aldersbegrensninger", "sparebank1-fremtind", "båt", 8, "Toppkasko"), row("bat.maskinskade.egenandel", "4 000 kr, med vilkårets fradragsregel", "sparebank1-fremtind", "båt", 9, "Maskin-/seilskade", "coverage")], "2024-06-10"),
  product("frende", "Frende", "Brann og tyveri", boatFire("frende", "Norden og angitte farvann; 1. mai–30. september utvidet til Europa inntil 200 nautiske mil"), "2026-01-01"),
  product("frende", "Frende", "Kasko", [...boatKasko("frende", "Norden og angitte farvann; 1. mai–30. september utvidet til Europa inntil 200 nautiske mil"), row("bat.losore.dekning", "Inkludert", "frende", "båt", 3, "Hva som er forsikret"), row("bat.losore.grense", "10 000 kr dersom annen sum ikke står i forsikringsbeviset", "frende", "båt", 3, "Hva som er forsikret")], "2026-01-01"),
  product("frende", "Frende", "Utvidet", [...boatKasko("frende", "Norden og angitte farvann; 1. mai–30. september utvidet til Europa inntil 200 nautiske mil"), row("bat.opplagsutstyr.dekning", "Inkludert", "frende", "båt", 3, "Hva som er forsikret"), row("bat.jolle.dekning", "Inkludert", "frende", "båt", 3, "Hva som er forsikret"), row("bat.jolle.grense", "20 000 kr for dokumentert jolle/motor", "frende", "båt", 3, "Hva som er forsikret")], "2026-01-01"),
];

const boatAddOns: BoatPetAddOnDefinition[] = [
  { providerId: "tryg", company: "Tryg", type: "båt", agreementScope: "ordinary", id: "tryg-bat-maskinskade", name: "Maskinskade", sourceId: sourceId("tryg", "båt"), requiresLevel: ["Kasko/Ansvar", "Båt Ekstra"], rows: [row("bat.maskinskade.dekning", "Valgfritt tillegg", "tryg", "båt", 1, "Maskinskade", undefined, "boat-pet:tryg:båt:machinery"), row("bat.maskinskade.alder", "Innenbordsmotor under 15 år; utenbordsmotor/seilbåt under 12 år", "tryg", "båt", 1, "Maskinskade", undefined, "boat-pet:tryg:båt:machinery")] },
  { providerId: "tryg", company: "Tryg", type: "båt", agreementScope: "ordinary", id: "tryg-bat-ulykke", name: "Fører- og passasjerulykke", sourceId: sourceId("tryg", "båt"), requiresLevel: ["Ansvar", "Brann/Ansvar", "Brann/Tyveri/Ansvar", "Kasko/Ansvar", "Båt Ekstra"], rows: [row("bat.ulykke.dekning", "Valgfritt tillegg", "tryg", "båt", 1, "Fører- og passasjerulykke", undefined, "boat-pet:tryg:båt:accident")] },
  { providerId: "if", company: "If", type: "båt", agreementScope: "ordinary", id: "if-bat-motor-gir", name: "Motor- og girskade", sourceId: sourceId("if", "båt"), requiresLevel: ["Kasko", "Super"], rows: [row("bat.maskinskade.dekning", "Valgfritt tillegg til Kasko", "if", "båt", 5, "4.9"), row("bat.maskinskade.alder", "Dekningen opphører når motor, gir eller drivverk er eldre enn 15 år", "if", "båt", 5, "4.9.2"), row("bat.maskinskade.egenandel", "Aldersgradert prosentandel, minst 8 000 kr", "if", "båt", 6, "4.9.5", "coverage") ] },
  { providerId: "frende", company: "Frende", type: "båt", agreementScope: "ordinary", id: "frende-bat-maskinskade", name: "Maskinskade", sourceId: sourceId("frende", "båt"), requiresLevel: ["Kasko", "Utvidet"], rows: [row("bat.maskinskade.dekning", "Valgfritt når oppført i forsikringsbeviset", "frende", "båt", 1, "Valgfrie dekninger")] },
  { providerId: "frende", company: "Frende", type: "båt", agreementScope: "ordinary", id: "frende-bat-ulykke", name: "Fører- og passasjerulykke", sourceId: sourceId("frende", "båt"), requiresLevel: ["Brann og tyveri", "Kasko", "Utvidet"], rows: [row("bat.ulykke.dekning", "Valgfritt når oppført i forsikringsbeviset", "frende", "båt", 1, "Valgfrie dekninger")] },
];

const petProduct = (providerId: string, company: string, type: "hund" | "katt", name: string, version: string | null, rows: BoatPetRow[]): BoatPetProductDefinition => ({
  providerId, company, type, agreementScope: "ordinary", productId: `${providerId}-${type}-${name.toLocaleLowerCase("nb-NO").normalize("NFKD").replace(/\p{M}/gu, "").replace(/[^a-z0-9]+/gu, "-").replace(/^-|-$/gu, "")}`,
  name, version, sourceId: sourceId(providerId, type), rows,
});
const vetBase = (providerId: string, type: "hund" | "katt", sum: string, deductibleValue: string, versionSection = "Veterinærbehandling"): BoatPetRow[] => [
  row("dyr.veterinar.dekning", "Inkludert", providerId, type, 1, versionSection),
  row("dyr.veterinar.sum.valgbar", sum, providerId, type, 1, versionSection),
  row("dyr.veterinar.egenandel.fast", deductibleValue, providerId, type, 1, versionSection, "reference"),
];
const petProducts: BoatPetProductDefinition[] = [
  petProduct("tryg", "Tryg", "hund", "Behandling", "2026-09-01", [...vetBase("tryg", "hund", "Kundens valgte sum fremgår av forsikringsbeviset", "Fremgår av forsikringsbeviset"), row("dyr.medisin.dekning", "Inkludert", "tryg", "hund", 1, "Hund Behandling"), row("dyr.karenstid.sykdom", "20 dager", "tryg", "hund", 1, "Begrensninger")]),
  petProduct("tryg", "Tryg", "katt", "Behandling", "2026-09-01", [...vetBase("tryg", "katt", "Kundens valgte sum fremgår av forsikringsbeviset", "Fremgår av forsikringsbeviset"), row("dyr.medisin.dekning", "Inkludert", "tryg", "katt", 1, "Katt Behandling"), row("dyr.karenstid.sykdom", "20 dager", "tryg", "katt", 1, "Begrensninger")]),
  ...(["hund", "katt"] as const).flatMap((type) => [
    petProduct("if", "If", type, "Basis", "2022-12-01", vetBase("if", type, "Valgbar forsikringssum; faktisk valg står i forsikringsbeviset", "Valgbar egenandel; faktisk valg står i forsikringsbeviset")),
    petProduct("if", "If", type, "Standard", "2022-12-01", [...vetBase("if", type, "Valgbar forsikringssum; faktisk valg står i forsikringsbeviset", "Valgbar egenandel; faktisk valg står i forsikringsbeviset"), row("dyr.medisin.dekning", "Inkludert", "if", type, 1, "Standard"), row("dyr.tannsykdom.dekning", "Inkludert med egen dokumentert grense", "if", type, 1, "Standard"), row("dyr.tannsykdom.grense", type === "hund" ? "15 000 kr" : "5 000 kr", "if", type, 1, "Standard")]),
    petProduct("if", "If", type, "Super", "2022-12-01", [...vetBase("if", type, "Valgbar forsikringssum; faktisk valg står i forsikringsbeviset", "Valgbar egenandel; faktisk valg står i forsikringsbeviset"), row("dyr.veterinar.rollover", "10 000 kr ubrukt sum overføres automatisk; samlet oppspart sum kan ikke overstige det dobbelte av valgt forsikringssum", "if", type, 4, "Rollover"), row("dyr.medisin.dekning", "Inkludert", "if", type, 1, "Super"), row("dyr.tannsykdom.dekning", "Inkludert innen valgt veterinærsum", "if", type, 1, "Super"), row("dyr.rehabilitering.dekning", "Inkludert", "if", type, 1, "Super"), row("dyr.allergi.dekning", "Inkludert innen valgt veterinærsum", "if", type, 1, "Super")]),
  ]),
  petProduct("gjensidige", "Gjensidige", "hund", "Behandling", null, [...vetBase("gjensidige", "hund", "Valgt forsikringssum fremgår av forsikringsbeviset", "Fremgår av forsikringsbeviset"), row("dyr.rehabilitering.grense", "Inntil 5 000 kr", "gjensidige", "hund", 1, "Behandling"), row("dyr.allergi.grense", "Inntil 5 000 kr", "gjensidige", "hund", 1, "Behandling")]),
  petProduct("gjensidige", "Gjensidige", "katt", "Behandling", null, [...vetBase("gjensidige", "katt", "Valgt forsikringssum fremgår av forsikringsbeviset", "Fremgår av forsikringsbeviset"), row("dyr.allergi.grense", "Inntil 5 000 kr", "gjensidige", "katt", 1, "Behandling")]),
  petProduct("storebrand", "Storebrand", "hund", "Veterinær", "2025-02-01", [...vetBase("storebrand", "hund", "Valgt forsikringssum per forsikringsår fremgår av forsikringsbeviset", "2 500 kr per skadetilfelle"), row("dyr.veterinaralder.opphor", "Veterinærforsikringen gjelder livet ut", "storebrand", "hund", 2, "B.1")]),
  petProduct("storebrand", "Storebrand", "katt", "Veterinær", "2025-02-01", [...vetBase("storebrand", "katt", "Valgt forsikringssum per forsikringsår fremgår av forsikringsbeviset", "2 500 kr per skadetilfelle"), row("dyr.veterinaralder.opphor", "Veterinærforsikringen gjelder livet ut", "storebrand", "katt", 2, "B.1")]),
  ...(["hund", "katt"] as const).flatMap((type) => {
    const life = [row("dyr.liv.dekning", "Inkludert", "storebrand", type, 1, "Dødsfall"), row("dyr.liv.sum.valgbar", "Valgt forsikringssum fremgår av forsikringsbeviset", "storebrand", type, 1, "Dødsfall"), row("dyr.liv.reduksjon.start", "Fra 8 år", "storebrand", type, 1, "Dødsfall"), row("dyr.liv.reduksjon.sats", "90 % ved 8 år, 75 % ved 9 år og 60 % ved 10 år", "storebrand", type, 1, "Dødsfall"), row("dyr.liv.opphor", "Første forfall etter fylte 10 år", "storebrand", type, 1, "Dødsfall"), ...(type === "hund" ? [row("hund.bruksverdi.dekning", "Inkludert i valgt dødsfallsdekning", "storebrand", type, 1, "Dødsfall og nedsatt bruksverdi"), row("hund.bruksverdi.grense", "Maksimalt 50 % av hundens forsikringssum for død", "storebrand", type, 1, "Dødsfall og nedsatt bruksverdi")] : [])];
    return [
      petProduct("storebrand", "Storebrand", type, "Dødsfall", "2025-02-01", life),
      petProduct("storebrand", "Storebrand", type, "Veterinær og Dødsfall", "2025-02-01", [...vetBase("storebrand", type, "Valgt forsikringssum per forsikringsår fremgår av forsikringsbeviset", "2 500 kr per skadetilfelle"), row("dyr.veterinaralder.opphor", "Veterinærforsikringen gjelder livet ut", "storebrand", type, 2, "B.1"), ...life]),
    ];
  }),
  petProduct("sparebank1-fremtind", "Fremtind", "hund", "Veterinær", "2025-08-07", [...vetBase("sparebank1-fremtind", "hund", "Valgt forsikringssum gjelder per forsikringsår", "Valg mellom 1 300, 2 000 eller 3 500 kr"), row("dyr.veterinar.egenandel.periode", "135 dager", "sparebank1-fremtind", "hund", 2, "Forsikringssum og egenandel"), row("dyr.diagnostikk.grense", "MR/CT innen valgt forsikringssum", "sparebank1-fremtind", "hund", 2, "Veterinærutgifter")]),
  petProduct("sparebank1-fremtind", "Fremtind", "katt", "Veterinær", "2025-08-07", [...vetBase("sparebank1-fremtind", "katt", "Valgt forsikringssum gjelder per forsikringsår", "Valg mellom 1 300, 2 000 eller 4 000 kr"), row("dyr.veterinar.egenandel.periode", "135 dager", "sparebank1-fremtind", "katt", 2, "Forsikringssum og egenandel"), row("dyr.diagnostikk.grense", "MR/CT samlet inntil 15 000 kr per forsikringsår", "sparebank1-fremtind", "katt", 2, "Veterinærutgifter")]),
  petProduct("frende", "Frende", "hund", "Veterinær", "2026-01-01", [...vetBase("frende", "hund", "Per skadetilfelle og samlet per forsikringsår; faktisk sum står i forsikringsbeviset", "Minst 1 000 kr per skadetilfelle"), row("dyr.veterinar.egenandel.prosent", "25 % av skaden", "frende", "hund", 4, "8.6 Egenandel", "coverage"), row("dyr.allergi.grense", "Inntil 15 000 kr", "frende", "hund", 2, "Veterinærutgifter"), row("dyr.karenstid.sykdom", "20 dager", "frende", "hund", 3, "Begrensninger")]),
  petProduct("frende", "Frende", "katt", "Veterinær", "2026-01-01", [...vetBase("frende", "katt", "Per skadetilfelle og samlet per forsikringsår; faktisk sum står i forsikringsbeviset", "Minst 1 000 kr per skadetilfelle"), row("dyr.veterinar.egenandel.prosent", "25 % av skaden", "frende", "katt", 4, "7.6 Egenandel", "coverage"), row("dyr.allergi.grense", "Inntil 15 000 kr", "frende", "katt", 2, "Veterinærutgifter"), row("dyr.karenstid.sykdom", "20 dager", "frende", "katt", 2, "Begrensninger")]),
];

const petAddOn = (providerId: string, company: string, type: "hund" | "katt", id: string, name: string, requiresLevel: string[], rows: BoatPetRow[]): BoatPetAddOnDefinition => ({ providerId, company, type, agreementScope: "ordinary", id, name, sourceId: sourceId(providerId, type), requiresLevel, rows });
const petAddOns: BoatPetAddOnDefinition[] = [
  petAddOn("tryg", "Tryg", "hund", "tryg-hund-ekstra", "Ekstra", ["Behandling"], [row("dyr.rehabilitering.dekning", "Valgfritt tillegg", "tryg", "hund", 1, "Hund Ekstra", undefined, "boat-pet:tryg:hund:extra"), row("dyr.rehabilitering.grense", "10 000 kr per sykdom eller ulykkesskade", "tryg", "hund", 1, "Hund Ekstra", undefined, "boat-pet:tryg:hund:extra"), row("dyr.tannsykdom.dekning", "Valgfritt tillegg", "tryg", "hund", 1, "Hund Ekstra", undefined, "boat-pet:tryg:hund:extra"), row("dyr.tannsykdom.grense", "30 000 kr per sykdom eller ulykkesskade og per forsikringsår", "tryg", "hund", 1, "Hund Ekstra", undefined, "boat-pet:tryg:hund:extra")]),
  petAddOn("tryg", "Tryg", "katt", "tryg-katt-ekstra", "Ekstra", ["Behandling"], [row("dyr.rehabilitering.dekning", "Valgfritt tillegg", "tryg", "katt", 1, "Katt Ekstra", undefined, "boat-pet:tryg:katt:extra"), row("dyr.rehabilitering.grense", "10 000 kr per sykdom eller ulykkesskade", "tryg", "katt", 1, "Katt Ekstra", undefined, "boat-pet:tryg:katt:extra"), row("dyr.tannsykdom.dekning", "Valgfritt tillegg", "tryg", "katt", 1, "Katt Ekstra", undefined, "boat-pet:tryg:katt:extra"), row("dyr.tannsykdom.grense", "30 000 kr per sykdom eller ulykkesskade og per forsikringsår", "tryg", "katt", 1, "Katt Ekstra", undefined, "boat-pet:tryg:katt:extra")]),
  petAddOn("tryg", "Tryg", "hund", "tryg-hund-dod", "Hund død", ["Behandling"], [row("dyr.liv.dekning", "Valgfri separat dekning", "tryg", "hund", 1, "Hund død", undefined, "boat-pet:tryg:hund:life"), row("dyr.liv.forsvinning", "Inkludert i livsdekningen", "tryg", "hund", 1, "Hund død", undefined, "boat-pet:tryg:hund:life"), row("dyr.liv.opphor", "Kan beholdes til hunden fyller 12 år", "tryg", "hund", 2, "Når forsikringen slutter", undefined, "boat-pet:tryg:hund:life")]),
  petAddOn("tryg", "Tryg", "katt", "tryg-katt-dod", "Rasekatt død", ["Behandling"], [row("dyr.liv.dekning", "Valgfri separat dekning", "tryg", "katt", 1, "Rasekatt død", undefined, "boat-pet:tryg:katt:life"), row("dyr.liv.forsvinning", "Inkludert i livsdekningen", "tryg", "katt", 1, "Rasekatt død", undefined, "boat-pet:tryg:katt:life"), row("dyr.liv.opphor", "Kan beholdes til katten fyller 12 år", "tryg", "katt", 2, "Når forsikringen slutter", undefined, "boat-pet:tryg:katt:life")]),
  ...(["hund", "katt"] as const).map((type) => petAddOn("if", "If", type, `${type === "hund" ? "if-hund" : "if-katt"}-liv`, "Liv", ["Basis", "Standard", "Super"], [row("dyr.liv.dekning", "Valgfri separat dekning", "if", type, 1, "Liv"), row("dyr.liv.sum.valgbar", "Forsikringssum velges og står i forsikringsbeviset", "if", type, 1, "Liv"), row("dyr.liv.reduksjon.start", type === "hund" ? "Startalder varierer etter dokumentert rasegruppe" : "Fra 10 år", "if", type, 5, "Liv"), row("dyr.liv.reduksjon.sats", "20 % av siste forsikringsårs forsikringssum per fornyelse", "if", type, 5, "Liv"), row("dyr.liv.opphor", type === "hund" ? "Opphørsalder varierer etter dokumentert rasegruppe" : "Ved fornyelse det året katten blir 13 år", "if", type, 5, "Liv")])),
  petAddOn("gjensidige", "Gjensidige", "hund", "gjensidige-hund-liv", "Liv", ["Behandling"], [row("dyr.liv.dekning", "Valgfri modul", "gjensidige", "hund", 1, "Liv")]),
  petAddOn("gjensidige", "Gjensidige", "hund", "gjensidige-hund-bruk", "Bruk", ["Behandling"], [row("hund.bruksverdi.dekning", "Valgfri modul", "gjensidige", "hund", 1, "Bruk")]),
  petAddOn("gjensidige", "Gjensidige", "katt", "gjensidige-katt-liv", "Liv", ["Behandling"], [row("dyr.liv.dekning", "Valgfri modul", "gjensidige", "katt", 1, "Liv")]),
  petAddOn("sparebank1-fremtind", "Fremtind", "hund", "sparebank1-fremtind-hund-topp", "Topp veterinærutgifter", ["Veterinær"], [row("dyr.allergi.dekning", "Valgfri utvidelse", "sparebank1-fremtind", "hund", 3, "Topp veterinærutgifter"), row("dyr.diagnostikk.dekning", "Valgfri utvidelse", "sparebank1-fremtind", "hund", 3, "Topp veterinærutgifter"), row("dyr.tannsykdom.dekning", "Valgfri utvidelse", "sparebank1-fremtind", "hund", 3, "Topp veterinærutgifter"), row("dyr.rehabilitering.dekning", "Valgfri utvidelse", "sparebank1-fremtind", "hund", 3, "Topp veterinærutgifter")]),
  ...(["hund", "katt"] as const).map((type) => {
    const lifeSource = `boat-pet:sparebank1-fremtind:${type}:life`;
    return petAddOn("sparebank1-fremtind", "Fremtind", type, `sparebank1-fremtind-${type}-liv`, "Død, tap og tyveri", ["Veterinær"], [row("dyr.liv.dekning", "Valgfri separat dekning", "sparebank1-fremtind", type, 1, "Liv", undefined, lifeSource), row("dyr.liv.forsvinning", "Inkludert når livsdekningen er valgt", "sparebank1-fremtind", type, 1, "Liv", undefined, lifeSource), row("dyr.liv.tyveri", "Inkludert når livsdekningen er valgt", "sparebank1-fremtind", type, 1, "Liv", undefined, lifeSource), row("dyr.liv.reduksjon.start", type === "hund" ? "5 eller 7 år, avhengig av dokumentert rasegruppe" : "Etter fylte 7 år", "sparebank1-fremtind", type, 1, "Erstatningsregler", undefined, lifeSource), row("dyr.liv.reduksjon.sats", "20 % per år", "sparebank1-fremtind", type, 1, "Erstatningsregler", undefined, lifeSource), row("dyr.liv.opphor", type === "hund" ? "8, 10 eller 12 år, avhengig av dokumentert rasegruppe" : "Etter fylte 12 år", "sparebank1-fremtind", type, 1, "Opphør", undefined, lifeSource)]);
  }),
  petAddOn("sparebank1-fremtind", "Fremtind", "hund", "sparebank1-fremtind-hund-bruk", "Bruksverdi", ["Veterinær"], [row("hund.bruksverdi.dekning", "Valgfri separat dekning", "sparebank1-fremtind", "hund", 1, "Bruksverdi", undefined, "boat-pet:sparebank1-fremtind:hund:use"), row("hund.bruksverdi.alder", "Opphører ved hovedforfall etter fylte 8 år", "sparebank1-fremtind", "hund", 1, "Opphør", undefined, "boat-pet:sparebank1-fremtind:hund:use")]),
  ...(["hund", "katt"] as const).flatMap((type) => [
    petAddOn("frende", "Frende", type, `frende-${type}-medisin`, "Medisin", ["Veterinær"], [row("dyr.medisin.dekning", "Valgfri dekning når oppført i forsikringsbeviset", "frende", type, 3, "Medisinutgifter")]),
    ...(type === "hund" ? [petAddOn("frende", "Frende", type, "frende-hund-tann", "Tann", ["Veterinær"], [row("dyr.tannsykdom.dekning", "Valgfri dekning når oppført i forsikringsbeviset", "frende", type, 3, "Tannsykdommer"), row("dyr.tannsykdom.grense", "Inntil 20 000 kr per skadetilfelle og forsikringsår", "frende", type, 3, "Tannsykdommer")])] : []),
    petAddOn("frende", "Frende", type, `frende-${type}-tap`, "Tap", ["Veterinær"], [row("dyr.liv.dekning", "Valgfri dekning når oppført i forsikringsbeviset", "frende", type, 3, "Tap"), row("dyr.liv.forsvinning", "Inkludert i valgt Tap-dekning", "frende", type, 3, "Tap"), row("dyr.liv.opphor", "Første hovedforfall etter 10 år", "frende", type, 2, "Hvor og når")]),
  ]),
  petAddOn("frende", "Frende", "hund", "frende-hund-bruksverdi", "Bruksverdi", ["Veterinær"], [row("hund.bruksverdi.dekning", "Hundespesifikk del av valgt Tap-dekning", "frende", "hund", 4, "Tap av brukshund"), row("hund.bruksverdi.grense", "50 % av forsikringssummen for tap av hunden", "frende", "hund", 4, "Tap av brukshund")]),
];

const built = buildBoatPetCatalog(boatPetSources, [...boatProducts, ...petProducts], [...boatAddOns, ...petAddOns]);
export const boatPetProducts = built.products;
export const boatPetFacts = built.facts;
export const boatPetAddOns = built.addOns;
export const boatPetAgreementScopes: AgreementScopeDefinition[] = [];
