import type { CatalogFact, CatalogProduct } from "./product-catalog.ts";
import { frendeReiseSources } from "./frende-reise-sources.ts";
export { frendeReiseSources } from "./frende-reise-sources.ts";

type Row = [string, string, string, string, number, CatalogFact["deductibleClassification"]?];
function facts(sourceId: string, rows: Row[]): CatalogFact[] {
  const s = frendeReiseSources[sourceId];
  return rows.map(([key, label, value, section, page, deductibleClassification]) => ({
    key: `reise.${key}`, label, value,
    ...(deductibleClassification ? { deductibleClassification } : {}),
    source: { documentId: s.id, section, page, filename: s.filename, termsNumber: s.termsNumber,
      effectiveFrom: s.effectiveFrom, company: s.company, url: s.url, productCode: s.productCode,
      version: s.version, note: "Forsikringsbeviset går foran for sikrede, enkeltperson/familie, varighet og fortsettelsesforsikring, geografisk område, summer, egenandeler, reservasjoner og særvilkår." },
  }));
}

const coverage = facts("frendeReiseTerms", [
  ["avtale.forbehold", "Forsikringsbevisets forrang", "Forsikringsbeviset avgjør om avtalen gjelder enkeltperson eller familie, hvem som er forsikret, faktisk reisevarighet og fortsettelsesforsikringens periode/geografi, dekninger, summer, egenandeler, reservasjoner og særvilkår.", "Innledning", 1],
  ["personer.omfang", "Enkeltperson eller familie", "Alle forsikrede må være medlem av folketrygden og ha folkeregistrert adresse i Norge. Familie i forsikringsbeviset omfatter ektefelle, samboer i ekteskapslignende forhold, barn, fosterbarn i husstanden, adoptivbarn og barn født av surrogat til fylte 21 år, samt barnebarn/oldebarn under 21 år på felles reise når de ikke har egen reiseforsikring.", "1 Hvem som er forsikret", 2],
  ["omrade.verden", "Geografisk område", "Fritid, ferie- og tjenestereise i hele verden i inntil 75 dager, fra bostedsadressen i Norge til retur til samme adresse. Gjelder ikke hjemme, på jobb, hybel/brakke/midlertidig bosted, undervisningssted, SFO/barnehage eller rutinemessige arbeidsreiser.", "2 Hvor og når forsikringen gjelder", 2],
  ["varighet.maks", "Maksimal standard reisevarighet", "75 dager per reise i hele verden.", "2.1", 2],
  ["varighet.enkeltreise_utvidelse", "Fortsettelsesforsikring", "Kundespesifikk fortsettelsesforsikring for reiser utover 75 dager må bestilles og betales før avreise, gjelder én reise og må tegnes på nytt for hver lang reise. Forsikringsbeviset angir perioden og om geografien er Norden, Europa eller hele verden. Dette er ikke et eget hovedprodukt.", "2.1–2.2", 2],
  ["omrade.ud", "UD, krig og risikoområder", "Gjelder ikke bretur i Arktis (Svalbard er uttrykkelig unntatt fra dette bretur-unntaket), Antarktis eller Grønland, eller reise til område UD fraråder eller med overhengende fare ved krig, opprør, terror, naturkatastrofe eller epidemi/pandemi. Avbestilling for reise bestilt og betalt før nytt reiseråd har egen dekning.", "2.1", 2],
  ["avbestilling.dekning", "Avbestilling", "Ingen generell øvre sum for dokumenterte, ikke-refunderbare transport- og overnattingsutgifter. Forhåndsbetalte arrangementer og utflukter som inngår i turen dekkes bare når overnattingsutgiftene erstattes. Plutselig og uventet akutt sykdom/ulykkesskade eller akutt forverring etter at reisen er betalt kan gi dekning; Frende kan kreve legeattest, og legen må ha vurdert tilstanden før avreise. Alvorlig sykdom eller død i nærmeste familie, hos den eneste medreisende eller i dennes familie omfattes når vedkommende bor i EØS. Inntil seks personer i reisefølget, endret operasjonsdato, nødvendig nøkkelperson eller rettsinnkalling mindre enn 14 dager før avreise, nødvendig tilstedeværelse etter boligskade og ny UD-/krigs-/terror-/natur-/epidemihendelse har egne vilkår. Unntatt er sannsynlige komplikasjoner, forverring eller behandlingsbehov ved kjent sykdom før bestilling; fødsel eller svangerskapskomplikasjoner etter 36. svangerskapsuke; planlagt behandling eller rekonvalesens som varer lenger enn forventet; bortfalt reiseformål; hel eller delvis betaling før forsikringen ble kjøpt, med mindre den er flyttet fra et annet selskap som også dekker avbestilling; betaling etter avbestillingshendelsen; og påbegynt reise. Konkurs, bonuspoeng, skole/kurs, messer/seminarer, timeshare, skatt/avgift og andre medlemsfordeler er blant utgiftsunntakene. Andre i reisefølget dekkes bare hvis de selv er omfattet av forsikringen.", "3.1–3.4 (fortsetter side 4)", 3],
  ["forsinkelse.rute", "Forsinket fremmøte og avgang", "Ved minst 1,5 times forsinket fremmøte til forhåndsbetalt transport på grunn av ekstreme værforhold eller ulykke som fører til trafikkaos, teknisk feil/trafikkuhell i offentlig transport, eller teknisk feil/trafikkuhell som krever berging av kjøretøyet du reiser med, dekkes nødvendige merutgifter til å innhente reiseruten. Leiebil dekkes frem til første bestemmelsessted. Forsinket eller kansellert offentlig transport ved vær/teknisk feil gir egen dekning når transportøren ikke kan tilby ny reise innen 24 timer og reisen var bestilt før forsinkelsen. Innhenting har ingen generell øvre sum; overnatting er begrenset til 6 000 kr per person. Forsinkelsen må dokumenteres; ny reise og overnatting må først kreves av transportøren.", "4.1–4.2", 4],
  ["forsinkelse.hotell_arrangement", "Tapt overnatting, arrangement og utflukt", "Ved minst åtte timers sen ankomst til endelig reisemål dekkes forhåndsbetalt overnatting og billetter til arrangement/utflukt, inntil 6 000 kr per person. Reisen må ha minst én overnatting, og dette gjelder ikke tjenestereise.", "4.3", 4],
  ["forsinkelse.unntak", "Streik, konkurs og transportøransvar", "Ingen forsinkelsesdekning ved streik, lockout, annen arbeidskonflikt, personalmangel eller konkurs. Refunderbare utgifter og transportørens ansvar går foran.", "4.4 og 5.4", 5],
  ["bagasje.dekning", "Reisegods", "Egne ting til bruk på reisen og lånte/leide ting når eieren krever erstatning for skade eller tap; arbeidsgivers ting er unntatt. Tyveri, ran, skadeverk, trafikk-/båtuhell, brann, vannlednings-/naturskade og transportørens skade eller tap av innsjekket bagasje omfattes, men transportørens ansvar går foran. Reiseuhell krever en plutselig, uforutsett ytre hendelse som du ser når den skjer. Unntatt er skade på koffert/bag; rift, hull, svimerker, hakk, riper, avskallinger, flekker og lignende; slitasje, forbruk eller forhold ved tingen selv; væskesøl på innsjekket bagasje; kjøretøy/båt med tilbehør, nøkler og tilhenger; luftsportsutstyr og droner i bruk; ufortollede tollpliktige gjenstander; skade forårsaket av ektefelle/samboer, barn, foreldre eller søsken; og sykkelskade som ikke påvirker bruk av sykkelen. Mistet, glemt eller bortkommet gods erstattes ikke.", "5.1–5.2", 5],
  ["bagasje.total", "Reisegods – samlet sum", "Ingen generell samlet øvre sum; kategori- og enkeltgjenstandsgrenser gjelder.", "5.3", 5],
  ["bagasje.per_gjenstand", "Enkeltgjenstand", "40 000 kr per enkeltgjenstand med tilbehør.", "5.3", 5],
  ["bagasje.verdisaker", "Verdigjenstander", "Ingen egen samlet kategorigrense, men 40 000 kr per enkeltgjenstand gjelder. Frende kan kreve særskilt kjøpsdokumentasjon for smykker, klokker, elektronikk og merkevarer.", "5.3 og 10.2", 5],
  ["bagasje.sportsutstyr", "Sportsutstyr", "Ingen egen samlet kategorigrense, men 40 000 kr per enkeltgjenstand gjelder. Luftsportsutstyr og droner i bruk er unntatt; skade på sykkel som ikke påvirker bruk av sykkelen er unntatt.", "5.2–5.3", 5],
  ["bagasje.sykkel", "Sykkel", "Sykkel og elsykkel omfattes innenfor enkeltgjenstandsgrensen 40 000 kr. Sykkel skal låses fast, og tilbehør skal sikres etter sikkerhetsforskriften.", "5.1–5.3 og 16", 5],
  ["bagasje.kontanter", "Penger og verdipapirer", "10 000 kr samlet per person.", "5.3", 5],
  ["bagasje.pass_billetter", "Pass og reisedokumenter", "20 000 kr samlet per person for pass, reisedokumenter og nødvendige utgifter ved tap.", "5.3", 5],
  ["bagasje.nokler", "Bolignøkler", "4 000 kr samlet per person.", "5.3", 5],
  ["bagasje.leid", "Leide ting på reisemålet", "20 000 kr samlet per person.", "5.3", 5],
  ["bagasje.uhell", "Uhell på reisegods", "Plutselig og uforutsett ytre fysisk skade som du ser idet den skjer, inntil 8 000 kr per forsikringsår. Mistet, glemt, bortkommet, kosmetisk skade, slitasje og mekaniske/iboende feil omfattes ikke.", "5.1–5.2", 5],
  ["bagasje.uhell_sum", "Uhell – sum", "8 000 kr per forsikringsår.", "5.1", 5],
  ["bagasje.forsinket", "Forsinket bagasje", "På utreise dekkes nødvendige klær/toalettsaker og leie av ski-, golf-, fiskeutstyr eller lignende inntil 6 000 kr per person mens innsjekket gods er savnet. PIR-rapport og kvitteringer kreves. Ufrivillig transitt med overnatting har 500 kr per person.", "5.4", 6],
  ["leiebil.egenandel", "Egenandel leid bil eller motorsykkel", "Ingen generell øvre sum for dokumentert egenandel ved tyveri eller ytre skade på forsikret personbil/motorsykkel leid fra utleiefirma på feriereise med minst én overnatting. Bobil, andre kjøretøy, privatleie, bildeling og leasing er unntatt; skaden må være dekket av kjøretøyets forsikring og kjent ved innlevering.", "5.5", 6],
  ["skadedyr.dekning", "Veggedyr og kakerlakker", "VIS Forsikring dekker forhåndsgodkjent bekjempelse av veggedyr/kakerlakker i reisegods etter hjemkomst og i fast bolig når skadeinsekter er tatt med fra reise, inntil 50 000 kr per tilfelle og to tilfeller per år. Forebygging, vedlikehold og aktivitet før kjøpet/etter opphør er unntatt.", "5.6 og 10.4", 6],
  ["skadedyr.egenandel", "Veggedyr/kakerlakker – egenandel", "2 000 kr ved bekjempelse i fast bolig og 500 kr ved behandling av reisegods.", "10.4", 10, "override"],
  ["medisinsk.behandling", "Akutt sykdom og personskade", "Ingen generell øvre sum for nødvendige lege-, sykehus-, reseptmedisin-, legeforeskrevet fysikalsk/kiropraktisk behandlings-, behandlingsreise- og legeordinert hotellutgifter ved plutselig akutt sykdom/ulykke. Varsling kreves ved forventet kostnad over 5 000 kr eller sykehus. Egen bil til og fra slik medisinsk behandling erstattes med 5 kr per kilometer. Ikke-akutt eller forventet sykdom/forverring, kontroll/rutinebehandling, planlagt operasjon/behandling, fortsatt behandling utenfor Norge når behandlende lege og Falck Global Assistance finner hjemtransport forsvarlig, behandling hos privat sykehus eller lege i Norge eller Norden, fødsel/svangerskapskomplikasjoner etter 36. svangerskapsuke, lete- og redningsaksjoner og utgifter etter hjemkomst er unntatt fra denne dekningen.", "6.1 (side 6), 6.3–6.4", 7],
  ["medisinsk.tann", "Tannbehandling", "Inntil 5 000 kr etter ulykkesskade og inntil 1 000 kr ved tannskade under spising.", "6.4", 7],
  ["medisinsk.kjent", "Kjent sykdom", "Kjent sykdom/lidelse omfattes bare når lege ved Falck Global Assistance vurderer forverringen som plutselig og uventet. Kontroll, rutinebehandling, planlagt behandling og ikke-akutte/sannsynlige forverringer er unntatt.", "6 og 6.3", 6],
  ["medisinsk.graviditet", "Graviditet og fødsel", "Akutt sykdom og uventede komplikasjoner kan omfattes før uke 36. Fødsel og svangerskapskomplikasjoner etter 36. svangerskapsuke er unntatt fra reisesyke og avbestilling.", "3.3 og 6.3", 3],
  ["hjemtransport", "Hjemtransport", "Ingen generell øvre sum for forhåndsgodkjent, medisinsk nødvendig hjemtransport og nødvendig ledsager. Ved dødsfall dekkes hjemtransport; begravelse på stedet inntil 40 000 kr. Retur til reisemålet kan dekkes innen 14 dager og innen planlagt reisetid.", "6.5", 7],
  ["hjemkallelse", "Hjemkalling", "Forhåndsgodkjent tidligere hjemreise uten generell øvre sum ved alvorlig akutt sykdom/død i nærmeste familie bosatt i EØS eller nødvendig tilstedeværelse etter skade på egen bolig eller bedrift.", "6.5", 7],
  ["sykeledsagelse", "Tilkalling", "Forhåndsgodkjente nødvendige reise- og overnattingsutgifter for inntil to personer fra Norden når sykdom/skade er svært alvorlig eller sikrede dør. Ikke tilkalling til landsdelen sikrede bor i.", "6.6", 8],
  ["medisinsk.kriseterapi", "Psykolog eller psykiater", "Inntil 20 000 kr for nødvendig behandling i Norge etter akutt psykisk krise fra ran, overfall, ulykkesskade, brann, trafikkulykke, naturkatastrofe, kapring eller terrorangrep.", "6.8", 8],
  ["reiseavbrudd", "Tapte feriedager", "Ingen generell øvre sum for forholdsmessig tap av transport og overnatting ved godkjent hjemtransport, sykehus/legeordinert sengeleie eller evakuering. I tillegg dekkes inntil to forhåndsbetalte arrangementer/utflukter og én medreisende. Gjelder ikke fortsettelsesforsikring.", "7", 8],
  ["evakuering", "Alvorlige hendelser og evakuering", "Ved krig, opprør, terror, naturkatastrofe eller epidemi/pandemi som oppstår mens du er i området gjelder dekningen inntil seks uker. Ved overhengende fare og klar UD-oppfordring dekkes forhåndsgodkjente nødvendige merutgifter til evakuering hjem uten generell øvre sum.", "8", 9],
  ["veterinar", "Veterinærutgifter", "Inntil 1 000 kr per skade for nødvendige veterinærutgifter ved akutt sykdom/ulykke for eget kjæledyr på reise utenfor Norden; ID-merking og vaksinering kreves. Konkurranse-, utstillings- og avlsreise er unntatt.", "9 og 16", 9],
  ["bagasje.egenandel", "Generell egenandel", "Ingen egenandel på reiseforsikringen med mindre forsikringsbeviset sier noe annet. Veggedyr/kakerlakker og rettshjelp har uttrykkelige særregler.", "10.6", 10, "reference"],
  ["bagasje.aldersfradrag", "Alder og slitasje", "Fradrag fastsettes konkret ut fra sannsynlig brukstid, slitasje, alder, nedsatt bruksmulighet og markedsverdi på tilsvarende brukte ting; eldste skadde del styrer når deler har ulik alder.", "10.5", 10],
  ["ulykke.dekning", "Integrert reiseulykke", "Gjelder ulykkesskade på reisen frem til fylte 80 år. Ulykken må være en plutselig, uventet ytre fysisk hendelse; slag, illebefinnende, besvimelse, sykdom eller lyte er ikke et ulykkestilfelle. Medisinsk behandling, undersøkelse eller medisiner er unntatt med mindre behandlingen gjelder en omfattet ulykkesskade. Rygg-/nakkelidelser og smerter må skyldes brudd i ryggsøylen påvist ved røntgen eller lignende etter ulykken; dette unntaket gjelder ikke rettmessig fører eller passasjer i kjøretøy. Selvmord/forsøk er unntatt, også ved sinnslidelse. Sjokk/psykisk skade er unntatt med mindre ICD-10 F43.1 (PTSD) er oppfylt og sjokkskaden følger fysisk skade med livsvarig medisinsk invaliditet som erstattes. Forgiftning av mat, drikke eller nytelsesmidler er unntatt, men ikke for barn under 16 år. Insektsstikk og hjerte-/karsykdom, kreft eller artritt som fører til død/invaliditet er unntatt, sistnevnte selv om ulykkesskade er årsaken. Overstadig beruselse, risikosport, forbrytelse, ulovlig virksomhet og slagsmål er unntatt; slagsmål-unntaket gjelder ikke barn under 16 år. Grov uaktsomhet eller forsett kan redusere eller fjerne erstatningen.", "11.1–11.2", 11],
  ["ulykke.invaliditet", "Reiseulykke – medisinsk invaliditet", "Ved 100 % varig medisinsk invaliditet: 500 000 kr for voksen og 700 000 kr for barn under 21 år. Etter fylte 75 år er summen 100 000 kr; dekningen opphører ved 80 år. Delvis invaliditet utbetales forholdsmessig uten progressiv overerstatning.", "11.4", 12],
  ["ulykke.dodsfall", "Reiseulykke – dødsfall", "500 000 kr for voksen og 150 000 kr for barn under 21 år. Etter fylte 75 år er summen 100 000 kr; dekningen opphører ved 80 år. Tidligere invaliditetserstatning for samme skade trekkes fra. Testamentarisk begunstigelse følger forsikringsavtaleloven kapittel 15; ellers betales ektefelle eller barn etter § 15-1, og samboer hvis det ikke finnes ektefelle eller barn. Uten testamentarisk begunstiget, ektefelle, samboer eller barn utbetales ikke erstatning. For barn under 21 år betales foreldrene, eller forsikringstakeren hvis foreldrene er skilt eller separert.", "11.3", 12],
  ["ulykke.behandling", "Reiseulykke – behandlingsutgifter", "Nødvendig behandling i Norge i inntil tre år, begrenset til 5 % av invaliditetssummen: offentlig refusjonsberettiget lege/tannlege/fysioterapi, foreskrevne medisiner/protese og offentlig transport som ikke refunderes. Ingen egenandel; tyggeskade, hjelpemidler og rehabilitering/opptrening er unntatt.", "11.5–11.6", 12],
  ["ansvar.dekning", "Privatansvar", "Rettslig erstatningsansvar som privatperson for person- eller tingskade på reise utenfor Norden. Yrke/næring, motorvogn/båt/luftfartøy, familie, leide/lånte/brukte ting og avtaleansvar er blant unntakene.", "12", 13],
  ["ansvar.sum", "Privatansvar – sum", "15 000 000 kr per skadetilfelle og samlet per år.", "12.4", 14],
  ["ansvar.egenandel", "Privatansvar – egenandel", "Ingen egenandel.", "12.4", 14, "override"],
  ["rettshjelp.dekning", "Rettshjelp", "Rimelige og nødvendige advokat-, retts-, sakkyndig- og vitneutgifter ved privat tvist om noe som oppstår på reise utenfor Norden. Yrke, næring, styreoppdrag og eierskap/feste av fast eiendom er unntatt. Ved erstatningskrav etter yrkesskadeforsikringsloven dekkes likevel rettshjelputgifter som påløper etter at saken er brakt inn for domstolene. Familie/skifte, straffesak og kjøretøy er blant de øvrige unntakene.", "13.1–13.3", 14],
  ["rettshjelp.sum", "Rettshjelp – sum", "100 000 kr per tvist, også når flere parter står på samme side, begrenset til sikredes økonomiske interesse.", "13.4", 15],
  ["rettshjelp.egenandel", "Rettshjelp – egenandel", "4 000 kr pluss 20 % av øvrige kostnader per tvist.", "13.4", 15, "override"],
  ["aktivitet.unntak", "Sport og aktiviteter", "Sykdom/skade og reiseulykke unntar blant annet inntekts-/sponsoridrett over 1 G, motorsport, full-/semikontakt kampsport, forbunds-/kretsserie og cup (unntatt bedriftsidrett), basehopp, fallskjermhopp og dykking dypere enn 40 meter. Dykking krever sertifikat for aktuell dybde. Opphold over 6 000 moh. og de særskilte polar-/Grønland-reglene gjelder som egne begrensninger.", "6.2, 11.2 og 16", 7],
  ["sikkerhet.reisegods", "Sikkerhetsforskrifter", "Reisegods skal holdes under tilsyn eller låses/sikres forsvarlig. Kontanter, pass, klokker, smykker og elektronikk skal bæres eller ligge i safe og aldri sendes som innsjekket bagasje; sykkel skal låses fast. Transportskade/tap må meldes på stedet.", "16", 16],
]);

const services = [
  ...facts("frendeReiseTerms", [["tjeneste.alarm", "Falck Global Assistance", "Døgnåpen alarmsentral for sykdom, ulykke, medisinsk assistanse, forhåndsgodkjenning, hjemtransport, tilkalling og evakuering. Medisinsk rådgivning før reise er en informasjonstjeneste, ikke en forsikringssum.", "6.9 og skadehjelp", 8]]),
  ...facts("frendeReiseDoctor", [["tjeneste.legehjelp", "Legetime på mobilen via Eyr", "Gratis videokonsultasjon med norsk lege for personer med gyldig Frende reiseforsikring når de blir syke eller skadet på fritidsreise i Norge eller utlandet. Tjeneste, ikke forsikringssum; alvorlige tilfeller skal håndteres via alarmsentral/akutthjelp.", "Legetime på mobilen", 1]]),
];

export const frendeReiseFacts: Record<string, CatalogFact[]> = {
  frendeReiseCoverage: coverage,
  frendeReiseServices: services,
  frendeReiseIpid: facts("frendeReiseIpid", [["avtale.ipid", "IPID – produktoversikt", "Produktarket, sist oppdatert 01.06.2026, bekrefter ett produkt for enkeltperson eller familie, sentrale dekninger og begrensninger. Forsikringsbevis og fullvilkår styrer.", "Produktoversikt", 1]]),
  frendeReiseGeneral: facts("frendeReiseGeneral", [["avtale.generellevilkar", "Generelle vilkår", "Generelle regler om blant annet oppsigelse, skadeoppgjør, samlet ansvar ved krig/terror og datakriminalitet gjelder sammen med reisevilkåret.", "Generelle vilkår", 1]]),
};

export const frendeReiseProducts: CatalogProduct[] = [{
  company: "Frende", insuranceType: "Reise", name: "Reiseforsikring", providerId: "frende",
  productId: "frende-reiseforsikring", version: "2026-03-01", sourceId: "frendeReiseTerms",
  componentIds: ["frendeReiseIpid", "frendeReiseGeneral", "frendeReiseCoverage", "frendeReiseServices"],
}];
export const frendeReiseAddOns = [];
