from pathlib import Path
import json,csv,hashlib,subprocess,datetime,shutil
O=Path('/tmp/nito-catalog-remediation-evening');R=Path('/Users/morten/Documents/forsikringsapp')
def load(p):return json.load(open(p))
def dump(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def git(*a):return subprocess.check_output(['git','-c','core.quotePath=false',*a],cwd=R,text=True).strip()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
s=load(O/'resume.json');baseline=load(O/'baseline.json');triage=load(Path('/tmp/source-catalog-remediation-triage/triage.json'));plan={b['batch_id']:b for b in triage['batches']};entry=load(O/'wave2-entry.json');audit=load(O/'final-targeted-audit.json');comparisons=load(O/'final-comparison-audit.json')
files=git('ls-files').splitlines()+git('ls-files','--others','--exclude-standard').splitlines();hashes={p:sha(R/p) for p in files if p and not Path(p).name.startswith('.env')}
assert hashes==s['project_hashes'];assert git('rev-parse','HEAD')==baseline['head'];assert git('branch','--show-current')=='main';assert git('diff','--cached','--name-only')==''
current_evidence={str(p):sha(p) for root in ['/tmp/source-catalog-completeness-audit','/tmp/source-catalog-remediation-triage'] for p in Path(root).rglob('*') if p.is_file()}
assert current_evidence==baseline['immutable'],'Evidence directories changed (contents or membership)'
subprocess.run(['git','diff','--check'],cwd=R,check=True)
assert 'ℹ pass 2038' in (O/'final-full.log').read_text();assert 'ℹ fail 0' in (O/'final-full.log').read_text();assert '"result": "PASS"' in (O/'final-runtime.log').read_text()
validation={'full_suite':{'pass':2038,'fail':0,'existing_tests':1996,'new_tests_total':42,'new_tests_this_continuation':34,'preserved_B001_B002_tests':8},'wave1_suite':'2016/2016 PASS','typescript':'PASS','eslint':'PASS','webpack_build':'PASS','synthetic_http_pdf_runtime':'PASS','git_diff_check':'PASS','first_full_attempt':'2037/2038; existing progress ordering flake','diagnostic_rerun':'Unchanged customer-price-trace suite22/22 PASS; unchanged full suite2038/2038 PASS','new_test_cases_corrected':4,'existing_test_cases_updated_to_proven_source_truth':6,'unresolved_failures':0,'new_test_harness_corrections_by_batch':{'B-003':2,'B-006':1,'B-009':1},'production_regressions_observed':0}
dump(O/'validation.json',validation)
wave2=[b['batch'] for b in entry if b['eligible']];assert all(b in s['completed_batches'] for b in wave2);skipped=[b for b in entry if not b['eligible']]
gate={'status':'PASS','scope':'Authorized safe Wave2 subset only; full Wave2 includes seven prerequisite-gated skipped batches','implemented':wave2,'skipped':skipped,'blocked':[],'P1_resolved':sum(plan[b]['P1_signature_count'] for b in wave2),'test_suite':'2038/2038 PASS','source_reaudit':'final-targeted-audit.json','comparison_audit':comparisons,'validation':'validation.json','prerequisite_policy':'No unreviewed canonical/mapping change; Bruk/Liv, age start/expiry, event/period and optional/customer choices remain distinct','wave3_started':False}
dump(O/'wave2-gate.json',gate)
ledger=load(O/'batch-ledger.json')
for e in skipped:
 bid=e['batch']
 if not any(r['batch_id']==bid and r['status']=='SKIPPED_PREREQUISITE' for r in ledger):ledger.append({'batch_id':bid,'wave':2,'status':'SKIPPED_PREREQUISITE','files_changed':[],'tests_added':0,'tests_run':'Not implemented','targeted_audit':'wave2-entry.json','P1_signatures_targeted':plan[bid]['P1_signature_count'],'P1_signatures_resolved':0,'regressions':0,'notes':e['readiness']+'; required: '+', '.join(e['dependencies'])})
dump(O/'batch-ledger.json',ledger)
with (O/'batch-ledger.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=list(ledger[0]));w.writeheader();w.writerows({k:json.dumps(v,ensure_ascii=False) if isinstance(v,list) else v for k,v in row.items()} for row in ledger)
with (O/'test-diagnostics.csv').open() as f:diagnostics=list(csv.DictReader(f))
for row in diagnostics:
 if row['result'] in ['CONTRACT_VERIFIED_BEFORE_CORRECTION','SOURCE_VERIFIED_BEFORE_CORRECTION']:row['result']='CORRECTED FROM DOCUMENTED EVIDENCE; focused and full2038/2038 PASS'
 if row['batch_id']=='WAVE2_GATE':row['result']='NO EDITS; isolated22/22 and subsequent full2038/2038 PASS; original failure retained in final-full-first-attempt.log'
with (O/'test-diagnostics.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=list(diagnostics[0]));w.writeheader();w.writerows(diagnostics)
s.update({'status':'EVENING_REMEDIATION_CONTINUATION_COMPLETE','gate_status':{'wave1':'PASS','wave2':'PASS_FOR_AUTHORIZED_SAFE_SUBSET'},'next_batch':None,'blocked_batches':[],'skipped_batches':[e['batch'] for e in skipped],'next_action':'Review completed changes and pending Wave2 prerequisites. Wave3 requires separate authorization; not started.','CATALOG_PILOT_GATE':'REMEDIATION_REQUIRED','timestamp':datetime.datetime.now(datetime.timezone.utc).isoformat()});dump(O/'resume.json',s)
shutil.copyfile(O/'B-016-after.json',O/'final-catalog.json')
changed=sorted(p for p in hashes if hashes[p]!=baseline['repo_hashes'].get(p))
integrity={'status':'PASS','head':git('rev-parse','HEAD'),'branch':'main','staged_files':0,'changed_files':changed,'production_files':len([p for p in changed if p.startswith('lib/')]),'test_files':len([p for p in changed if p.startswith('tests/')]),'immutable_audit_triage_files':len(current_evidence),'evidence_file_membership_and_hashes':'UNCHANGED','catalog_source_artifacts_manifests':'UNCHANGED','env_read_or_written':False,'new_sources_or_private_customer_documents':False,'git_mutations':False,'railway_changes':False,'full_source_reaudit_claimed':False};dump(O/'final-integrity.json',integrity)
report=[]
report+=['EVENING_REMEDIATION_CONTINUATION_COMPLETE','', 'Kontrollert fortsettelse fra B-001/B-002, ikke restart. HEAD '+baseline['head']+' på main. De to PASS-batchene og deres8tester er bevart. Ingen staging/commit/push/deploy.', '', 'B-003 diagnose: Uavhengig kontraktkontroll viste at ukjent/ikke-tilgjengelig add-on skal gi feil (ikke undefined), og at addOns er ExtractedAddOn-objekter, ikke strenger. To nye tester ble korrigert etter dokumentert diagnose. Produksjonskontrakten ble ikke endret for å passe tester.', '', 'BATCHRESULTATER:']
for bid in s['completed_batches']:
 b=plan[bid];r=next(r for r in reversed(ledger) if r['batch_id']==bid and r['status']=='PASS');report.append(f"{bid} | PASS | Wave{b['wave']} | {b['P1_signature_count']} P1 | {r['tests_added']} nye tester | {b['title']}")
report+=['','Wave1gate PASS:7P1 og8 strict unsupported claims kontrollert;2016/2016tester. Wave2gate PASS for tillatt scope:8batcher/14P1. Totalt21P1 (2tidligere+19denne fortsettelsen),29P1-forekomster og3tilgrensendeP2-forekomster,32lukkede funn-IDer. Dette er ikke en ny full katalogaudit.','', 'SKIPPET FOR MANGLENDE FORHÅNDSVURDERING:']
report += [e['batch']+' | '+e['readiness']+' | '+', '.join(e['dependencies']) for e in skipped]
report+=['','TESTDIAGNOSTIKK:4nye testcases korrigert (B0032,B0061,B0091). Ingen batch krevde mer enn2nye harnesskorreksjoner.6eksisterende testcases i4filer oppdatert fordi de eksplisitt forventet kildeavkreftede verdier/scope (B0041,B0051,B0101,B0143). B014 var én samlet kildebasert forventningsoppdatering, ikke gjentatt mutasjon av produksjon. Full evidens i test-diagnostics.csv.','B006: en artifact PASS ble skrevet før testresultatet var korrekt kontrollert. Dette ble rettet og batchen kjørt grønn før B007 startet; historikken er bevart i ledger/diagnostikk.','Første sluttkjøring:2037/2038; én eksisterende tracing-test feilet på global rekkefølge av parallelle progress-hendelser. Resultat-snapshots var identiske. Ingen kode/test ble endret. Isolert22/22PASS og ny fullkjøring2038/2038PASS. Feillogg bevart. Timing-følsom test registrert som gjenværende teknisk begrensning.','Ingen observerte produksjonsregresjoner eller uløste testfeil.','', 'SLUTTVALIDERING:2038/2038 (1996eksisterende+42nye).34nye i denne fortsettelsen,8bevart fraB001/B002. TypeScriptPASS, ESLintPASS, webpack production buildPASS, syntetisk HTTP/PDF-runtimePASS, git diff --checkPASS. Ingen reelle kunde-PDFer eller eksterne AI-kall brukt.','', 'MÅLRETTET RE-AUDIT:15aksepterte batcher revidert mot egne frosne kilder og parent/detail-/nivåkrav.16kildehashes verifisert.204produktidentiteter/202aktive beholdt.22produkter endret innen eksakte tillatte nøkler;182produkter helt uendret i base, alle enkeltvise tillegg og materialisert produktmodus.714sammenligningsretninger/496berørte rader bestått, inklusive sidebytte og likt produkt. Hele factlister per nøkkel (inklusive duplikater) ble kontrollert; ingen uventede felter eller metadata endret.','Kundekontroller: eksplisitt dokumentverdi vinner; stille/avvist valgfritt tillegg forblir uvalgt; valgt Topp overstyrer bare de relevante grensene; alder/reduksjon/opphør, perår/livstid/pergjenstand og sted/produktnivå holdes adskilt. Ingen motor-, UI-, matching-, normaliserings- eller schemaendringer.','B010: fullvilkårets komplette rasegrupper5/7/9 ogopphør8/10/12 gjengis med hovedforfall og eksplisitt kildeattribusjon. SC068-konflikten mot produktsidens tidspunkt er ikke avgjort.','', 'ENDREDE PROSJEKTFILER (11katalogproduksjon+6testfiler):']
report+=changed
report+=['','INTEGRITET:main/HEADuendret,0staged.17tilsiktede lokale endrede/nye filer. Alle892filer i audit-/triagedirektoriene uendret både i filsett og hash. Offentlige originalkilder og manifests uendret. Ingen .env.local-/Railway-endringer, ingen nye kilder eller private dokumenter. Ingen commit/push/reset/revert/stash/clean.','', 'ARTEFAKTER:batch-ledger.csv/json,resume.json,test-diagnostics.csv,validation.json,wave1-gate.json,wave2-gate.json,final-targeted-audit.json,final-comparison-audit.json,final-integrity.json og per-batch før/etter/audit/patch/testlogger ligger i /tmp/nito-catalog-remediation-evening/.', '', 'NESTE STEG: menneskelig gjennomgang av disse lokale endringene og de syv ventende Wave2-forhåndsvurderingene. Ingen neste implementeringsbatch er startet. Wave3(73batcher/1035P1),Wave4/5,kildeforskning/reviews og endelig full re-audit gjenstår; krever ny godkjenning.','CATALOG_PILOT_GATE = REMEDIATION_REQUIRED.','Ingen pilot-ready-påstand.']
(O/'final-report.txt').write_text('\n'.join(report)+'\n')
print(json.dumps({'status':s['status'],'files':len(changed),'tests':2038,'P1':21,'immutable':len(current_evidence),'staged':0},ensure_ascii=False))
